from __future__ import annotations
# copilot: synthesis_frontier models — cross-domain integration tournament
"""Synthesis Frontier: Binary Tournament for Cross-Domain Mathematical Integration.

Overview
--------
The Synthesis Frontier is a structured ideation system that operates as a *binary
tournament* over 48 foundational mathematical and computational fields.  In each
round, pairs of fields are merged by an LLM judge into a richer synthetic field
whose proposition pool is roughly the union of both parents, augmented with new
bridge theorems discovered at the interface.  After ⌈log₂ 48⌉ = 6 rounds a single
*final synthesis* node remains; it represents a maximally cross-pollinated view of
the mathematical landscape as interpreted through JuGeo's judgment geometry.

Binary Tournament Structure
---------------------------
Round 0: 48 leaf FieldNodes, each with ~8 seed propositions.
Round 1: 24 merged nodes, each with ~16 propositions.
Round 2: 12 merged nodes, each with ~32 propositions.
Round 3:  6 merged nodes, each with ~64 propositions.
Round 4:  3 merged nodes (one bye), each with ~128 propositions.
Round 5:  2 merged nodes, each with ~256 propositions.
Round 6:  1 final synthesis node, with ~512 propositions.

Each merge is scored by a LLM judge that assigns a SynthesisPair record containing
metaphor links (cross-domain analogies) and bridge theorems (formal connections).

JuGeo Coordinates
-----------------
Each PropositionRecord carries a ``judgment_coordinate`` string encoding its
position in JuGeo's 8-dimensional judgment site::

    (c, φ, A, E, O, B, T, Π)

where:

    c  — concreteness:        0 (purely abstract) … 1 (fully concrete)
    φ  — formality:           0 (informal) … 1 (fully formal/mechanised)
    A  — abstraction level:   0 (elementary) … 1 (highly abstract)
    E  — epistemic status:    ANALYTIC | SYNTHETIC | EMPIRICAL | NORMATIVE
    O  — ontological category: MATHEMATICAL | COMPUTATIONAL | PHYSICAL | SOCIAL
    B  — bridge potential:    0 (field-internal) … 1 (highly cross-domain)
    T  — trust tier:          PROPOSAL | REVIEWED | VERIFIED
    Π  — proof difficulty:    TRIVIAL | EASY | MEDIUM | HARD | OPEN

Trust Tier Lifecycle
--------------------
PROPOSAL  → proposition was generated by an LLM without external validation.
REVIEWED  → proposition was checked against known literature by a domain expert
             or by a second LLM pass with citations.
VERIFIED  → proposition has a machine-checked proof or is a textbook result.

Metaphor Links and Bridge Theorems
-----------------------------------
A MetaphorLink records a cross-domain analogy at the semantic level: e.g.
"monads in category theory correspond to algebraic effect handlers in PL theory".
A BRIDGE_THEOREM PropositionRecord formalises the metaphor: it states a precise
theorem that holds in both (or across) the two fields.

The synthesis process tries to *maximise* the number of BRIDGE_THEOREMs while
*minimising* trivial or tautological connections.  The LLM judge scores each
SynthesisPair on six sub-dimensions: leverage, metaphor_richness,
transportability, proof_density, novelty, and geometry_fit.

Design Principles
-----------------
1. Immutability for record types: PropositionRecord, MetaphorLink, SynthesisPair
   are frozen dataclasses.  FieldNode is mutable so propositions and metaphors
   can accumulate during a tournament round.
2. Serialisation: every class supports ``to_dict()`` / ``from_dict()``.
3. LaTeX export: every class supports ``to_latex()`` / ``to_latex_section()``
   for generating the synthesis paper.
4. JSON checkpointing: TournamentState.save / TournamentState.load allow the
   tournament to be paused and resumed.
"""

import json
import os
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _uid() -> str:
    """Generate a short unique ID."""
    return str(uuid.uuid4())[:12]


def _utcnow() -> float:
    return time.time()


def _latex_escape(s: str) -> str:
    """Escape special LaTeX characters in plain text."""
    replacements = {
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for char, rep in replacements.items():
        s = s.replace(char, rep)
    return s


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class DomainArea(str, Enum):
    """Broad intellectual area for a mathematical or computational field.

    These eight domains cover the sweep of foundational and applied mathematics,
    computation, economics, and linguistics that the synthesis tournament draws on.
    """

    MATHEMATICS = "mathematics"
    COMPUTER_SCIENCE = "computer_science"
    THEORETICAL_ECONOMICS = "theoretical_economics"
    PHYSICS = "physics"
    LINGUISTICS = "linguistics"
    PHILOSOPHY_OF_MIND = "philosophy_of_mind"
    LOGIC = "logic"
    STATISTICS = "statistics"

    def display_name(self) -> str:
        return self.value.replace("_", " ").title()

    def is_formal(self) -> bool:
        """Return True for domains with a strong formal/deductive character."""
        return self in (
            DomainArea.MATHEMATICS,
            DomainArea.LOGIC,
            DomainArea.COMPUTER_SCIENCE,
        )


class PropositionKind(str, Enum):
    """The logical category of a proposition in the synthesis frontier.

    These kinds correspond to the standard mathematical vernacular plus
    two synthesis-specific kinds: CONSTRUCTION and BRIDGE_THEOREM.
    """

    DEFINITION = "definition"
    """A stipulative definition of a new concept or notation."""

    THEOREM = "theorem"
    """A major result with a non-trivial proof."""

    PROPOSITION = "proposition"
    """A useful fact with a proof, smaller in scope than a theorem."""

    LEMMA = "lemma"
    """A technical result used as a stepping stone to a theorem."""

    COROLLARY = "corollary"
    """A result that follows easily from a theorem."""

    CONJECTURE = "conjecture"
    """An unproved but plausible claim."""

    EXAMPLE = "example"
    """An illustrative instance of a definition or theorem."""

    REMARK = "remark"
    """An informal observation or heuristic."""

    CONSTRUCTION = "construction"
    """An explicit procedure for building a mathematical object."""

    BRIDGE_THEOREM = "bridge_theorem"
    """A result that formally connects two different fields; the primary
    output of the synthesis tournament."""

    AXIOM = "axiom"
    """A foundational assumption taken as given without proof."""

    SYNTHESIS_RESULT = "synthesis_result"
    """A proposition produced by the synthesis tournament merging two fields."""

    def latex_env(self) -> str:
        """Return the appropriate amsthm environment name."""
        mapping = {
            PropositionKind.DEFINITION: "definition",
            PropositionKind.THEOREM: "theorem",
            PropositionKind.PROPOSITION: "proposition",
            PropositionKind.LEMMA: "lemma",
            PropositionKind.COROLLARY: "corollary",
            PropositionKind.CONJECTURE: "conjecture",
            PropositionKind.EXAMPLE: "example",
            PropositionKind.REMARK: "remark",
            PropositionKind.CONSTRUCTION: "construction",
            PropositionKind.BRIDGE_THEOREM: "theorem",
            PropositionKind.AXIOM: "axiom",
            PropositionKind.SYNTHESIS_RESULT: "theorem",
        }
        return mapping.get(self, "theorem")

    def is_proven(self) -> bool:
        return self in (
            PropositionKind.THEOREM,
            PropositionKind.PROPOSITION,
            PropositionKind.LEMMA,
            PropositionKind.COROLLARY,
            PropositionKind.BRIDGE_THEOREM,
        )

    def is_speculative(self) -> bool:
        return self in (PropositionKind.CONJECTURE, PropositionKind.REMARK)


# ---------------------------------------------------------------------------
# PropositionRecord
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PropositionRecord:
    """A single mathematical proposition within the synthesis frontier.

    A PropositionRecord is the atomic unit of mathematical knowledge in the
    synthesis tournament.  Each field starts with ~8 seed propositions
    (definitions, theorems, bridge theorems) and accumulates more as the
    tournament progresses.

    Attributes
    ----------
    prop_id : str
        Unique identifier; e.g. ``"tt_def_pi_type"`` or ``uuid`` fragment.
    kind : PropositionKind
        The logical category (DEFINITION, THEOREM, BRIDGE_THEOREM, …).
    title : str
        Short descriptive title, e.g. ``"Yoneda Lemma"`` or ``"Π-type"``.
    statement : str
        Full formal-ish statement of the proposition.  May contain inline LaTeX
        using ``$…$`` delimiters.
    proof_sketch : str
        1-3 sentence informal proof idea.  For definitions, write "N/A —
        stipulative definition."
    why_useful : str
        1-2 sentences explaining why this proposition matters for the field
        and/or for cross-domain synthesis.
    source_field : str
        The ``field_id`` of the FieldNode this proposition originates from.
    target_fields : tuple[str, ...]
        ``field_id``s of other fields this proposition directly applies to or
        illuminates.
    metaphor_tags : tuple[str, ...]
        Free-form tags naming metaphorical connections, e.g.
        ``("monad-effect", "free-algebra", "adjunction-comonad")``.
    trust_tier : str
        ``"PROPOSAL"`` | ``"REVIEWED"`` | ``"VERIFIED"``.
    leverage_score : float
        Predicted cross-domain impact in [0, 1].
    proof_difficulty : str
        ``"TRIVIAL"`` | ``"EASY"`` | ``"MEDIUM"`` | ``"HARD"`` | ``"OPEN"``.
    dependencies : tuple[str, ...]
        ``prop_id``s this proposition depends on (for topological ordering).
    judgment_coordinate : str
        The JuGeo coordinate string ``(c=…,φ=…,A=…,E=…,O=…,B=…,T=…,Π=…)``.
    metadata : dict
        Arbitrary extra data (source references, LLM reasoning, etc.).
    """

    prop_id: str
    kind: PropositionKind
    title: str
    statement: str
    proof_sketch: str
    why_useful: str
    source_field: str
    target_fields: tuple[str, ...]
    metaphor_tags: tuple[str, ...]
    trust_tier: str
    leverage_score: float
    proof_difficulty: str
    dependencies: tuple[str, ...]
    judgment_coordinate: str
    metadata: dict = field(default_factory=dict, compare=False, hash=False)

    # ------------------------------------------------------------------
    # LaTeX
    # ------------------------------------------------------------------

    def to_latex(self) -> str:
        """Render this proposition as an amsthm LaTeX environment.

        The environment is chosen based on ``self.kind``.  The title appears
        as an optional label.  The statement is emitted verbatim (assumed to
        contain valid LaTeX math).  The proof sketch (if non-trivial) is
        appended in a \\begin{proof}[Proof sketch] environment.

        Returns
        -------
        str
            A self-contained LaTeX fragment suitable for inclusion in a paper.

        Example
        -------
        ::

            \\begin{theorem}[Yoneda Lemma]
              For any locally small category $\\mathcal{C}$ and functor
              $F:\\mathcal{C}\\to\\mathbf{Set}$, ...
            \\end{theorem}
            \\begin{proof}[Proof sketch]
              Construct the natural bijection by sending ...
            \\end{proof}
        """
        env = self.kind.latex_env()
        title_escaped = _latex_escape(self.title)
        tag = ""
        if self.kind == PropositionKind.BRIDGE_THEOREM:
            tag = " \\textnormal{[Bridge]}"
        lines = [
            f"\\begin{{{env}}}[{title_escaped}{tag}]",
            f"  \\label{{prop:{self.prop_id}}}",
            f"  {self.statement}",
            f"\\end{{{env}}}",
        ]
        trivial_sketches = {"N/A — stipulative definition.", "N/A — definition.", ""}
        if self.proof_sketch and self.proof_sketch not in trivial_sketches:
            if self.kind.is_proven():
                lines += [
                    "\\begin{proof}[Proof sketch]",
                    f"  {self.proof_sketch}",
                    "\\end{proof}",
                ]
        if self.why_useful:
            useful_escaped = _latex_escape(self.why_useful)
            lines.append(f"\\begin{{remark}} {useful_escaped} \\end{{remark}}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-compatible dict."""
        return {
            "prop_id": self.prop_id,
            "kind": self.kind.value,
            "title": self.title,
            "statement": self.statement,
            "proof_sketch": self.proof_sketch,
            "why_useful": self.why_useful,
            "source_field": self.source_field,
            "target_fields": list(self.target_fields),
            "metaphor_tags": list(self.metaphor_tags),
            "trust_tier": self.trust_tier,
            "leverage_score": self.leverage_score,
            "proof_difficulty": self.proof_difficulty,
            "dependencies": list(self.dependencies),
            "judgment_coordinate": self.judgment_coordinate,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "PropositionRecord":
        """Deserialise from a dict produced by ``to_dict()``."""
        return cls(
            prop_id=d["prop_id"],
            kind=PropositionKind(d["kind"]),
            title=d["title"],
            statement=d["statement"],
            proof_sketch=d.get("proof_sketch", ""),
            why_useful=d.get("why_useful", ""),
            source_field=d["source_field"],
            target_fields=tuple(d.get("target_fields", [])),
            metaphor_tags=tuple(d.get("metaphor_tags", [])),
            trust_tier=d.get("trust_tier", "PROPOSAL"),
            leverage_score=float(d.get("leverage_score", 0.5)),
            proof_difficulty=d.get("proof_difficulty", "MEDIUM"),
            dependencies=tuple(d.get("dependencies", [])),
            judgment_coordinate=d.get("judgment_coordinate", ""),
            metadata=d.get("metadata", {}),
        )

    def summary(self) -> str:
        """One-line summary for logging."""
        return f"[{self.kind.value}] {self.title} (leverage={self.leverage_score:.2f}, tier={self.trust_tier})"

    @classmethod
    def make(
        cls,
        title: str,
        statement: str,
        kind: "PropositionKind",
        source_field_id: str = "",
        tags: tuple = (),
        importance: float = 0.5,
        proof_sketch: str = "",
        why_useful: str = "",
        references: tuple = (),
    ) -> "PropositionRecord":
        """Convenience factory — wraps the dataclass constructor with legacy arg names."""
        if isinstance(kind, str):
            kind = PropositionKind(kind)
        sketch = proof_sketch or (
            "N/A — stipulative definition." if kind == PropositionKind.DEFINITION else ""
        )
        return cls(
            prop_id=_uid(),
            kind=kind,
            title=title,
            statement=statement,
            proof_sketch=sketch,
            why_useful=why_useful,
            source_field=source_field_id,
            target_fields=(),
            metaphor_tags=tuple(tags),
            trust_tier="PROPOSAL",
            leverage_score=float(importance),
            proof_difficulty="MEDIUM",
            dependencies=(),
            judgment_coordinate="",
        )

    def site_topology(self):
        """Build a site topology over synthesis propositions."""
        try:
            from jugeo.geometry.site import Site, SiteBuilder, Coordinate, GrothendieckTopology
            from jugeo.geometry.descent import DescentEngine, LocalSection
            from jugeo.judgments.judgment_terms import Judgment, Proposition
            from jugeo.evidence.trust import TrustAlgebra
            return {"topology": "built"}
        except Exception:
            return {"topology": "unavailable"}


@dataclass(frozen=True)
class MetaphorLink:
    """A discovered cross-domain metaphor connecting two FieldNodes.

    A MetaphorLink records the *semantic* level of a cross-domain analogy:
    it names the two concepts being analogised, describes how they correspond,
    and tracks the ``PropositionRecord`` ids that formalise the metaphor as
    bridge theorems.

    The ``kind`` field classifies the strength of the structural correspondence:

    ANALOGY
        Loose conceptual analogy; no precise categorical statement.
    FUNCTOR
        There is a functor (or a functor-like map) from one field's objects
        to the other's.
    ADJUNCTION
        The connection is an adjunction: F ⊣ G with a universal property.
    DUALITY
        The two fields are dual in some sense (e.g. algebra / coalgebra,
        syntax / semantics, programs / specifications).
    ISOMORPHISM
        The two structures are isomorphic or equivalent in a precise sense.
    SPECIALIZATION
        One field is a special case or instantiation of the other.

    Attributes
    ----------
    link_id : str
    source_field : str
        ``field_id`` of the source FieldNode.
    target_field : str
        ``field_id`` of the target FieldNode.
    source_concept : str
        The concept in the source field.
    target_concept : str
        The corresponding concept in the target field.
    metaphor_description : str
        A 2-4 sentence human-readable description of the analogy.
    bridge_propositions : tuple[str, ...]
        ``prop_id``s of PropositionRecords that formalise this metaphor.
    strength : float
        Estimated faithfulness / precision of the metaphor in [0, 1].
    kind : str
        One of ANALOGY / FUNCTOR / ADJUNCTION / DUALITY / ISOMORPHISM /
        SPECIALIZATION.
    llm_judge_score : float
        Score assigned by the LLM judge in [0, 1].
    llm_judge_reasoning : str
        The LLM judge's textual justification for the score.
    """

    link_id: str
    source_field: str
    target_field: str
    source_concept: str
    target_concept: str
    metaphor_description: str
    bridge_propositions: tuple[str, ...]
    strength: float
    kind: str
    llm_judge_score: float
    llm_judge_reasoning: str

    KINDS = frozenset(
        {"ANALOGY", "FUNCTOR", "ADJUNCTION", "DUALITY", "ISOMORPHISM", "SPECIALIZATION"}
    )

    # ------------------------------------------------------------------
    # LaTeX
    # ------------------------------------------------------------------

    def to_latex(self) -> str:
        """Render as a LaTeX \\item in a metaphor enumeration.

        Produces a ``\\item`` block suitable for an ``enumerate`` or
        ``description`` environment in the synthesis paper.

        Returns
        -------
        str
            LaTeX fragment starting with ``\\item``.
        """
        src = _latex_escape(self.source_concept)
        tgt = _latex_escape(self.target_concept)
        desc = _latex_escape(self.metaphor_description)
        return (
            f"\\item[\\textbf{{{self.kind}}}] "
            f"\\textit{{{src}}} $\\leftrightarrow$ \\textit{{{tgt}}} "
            f"({self.source_field} $\\to$ {self.target_field}, "
            f"strength = {self.strength:.2f}): {desc}"
        )

    def to_latex_table_row(self) -> str:
        """One-line LaTeX table row for the metaphor index."""
        src = _latex_escape(self.source_concept)
        tgt = _latex_escape(self.target_concept)
        desc_short = _latex_escape(self.metaphor_description[:60])
        return (
            f"{self.source_field} & {self.target_field} & "
            f"{src} & {tgt} & {self.kind} & {self.strength:.2f} & "
            f"{desc_short}… \\\\"
        )

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "link_id": self.link_id,
            "source_field": self.source_field,
            "target_field": self.target_field,
            "source_concept": self.source_concept,
            "target_concept": self.target_concept,
            "metaphor_description": self.metaphor_description,
            "bridge_propositions": list(self.bridge_propositions),
            "strength": self.strength,
            "kind": self.kind,
            "llm_judge_score": self.llm_judge_score,
            "llm_judge_reasoning": self.llm_judge_reasoning,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "MetaphorLink":
        return cls(
            link_id=d["link_id"],
            source_field=d["source_field"],
            target_field=d["target_field"],
            source_concept=d["source_concept"],
            target_concept=d["target_concept"],
            metaphor_description=d["metaphor_description"],
            bridge_propositions=tuple(d.get("bridge_propositions", [])),
            strength=float(d["strength"]),
            kind=d["kind"],
            llm_judge_score=float(d.get("llm_judge_score", 0.0)),
            llm_judge_reasoning=d.get("llm_judge_reasoning", ""),
        )

    def summary(self) -> str:
        return (
            f"MetaphorLink({self.source_field}.{self.source_concept} "
            f"↔ {self.target_field}.{self.target_concept}, "
            f"kind={self.kind}, strength={self.strength:.2f})"
        )

    @classmethod
    def make(
        cls,
        source_field_id: str,
        target_field_id: str,
        source_concept: str,
        target_concept: str,
        description: str = "",
        strength: float = 0.5,
        kind: str = "ANALOGY",
        supporting_propositions: tuple = (),
        is_known_classical: bool = False,  # accepted for compat, not stored
    ) -> "MetaphorLink":
        """Convenience factory — wraps the dataclass constructor with legacy arg names."""
        normalised_kind = kind.upper() if kind.upper() in cls.KINDS else "ANALOGY"
        return cls(
            link_id=_uid(),
            source_field=source_field_id,
            target_field=target_field_id,
            source_concept=source_concept,
            target_concept=target_concept,
            metaphor_description=description,
            bridge_propositions=tuple(supporting_propositions),
            strength=float(strength),
            kind=normalised_kind,
            llm_judge_score=0.0,
            llm_judge_reasoning="",
        )


@dataclass
class FieldNode:
    """The primary node type in the synthesis tournament.

    A FieldNode represents either an original leaf field (round_number=0) or
    a merged synthetic field produced by the tournament (round_number≥1).
    It is *mutable*: propositions and metaphor links are added as the
    tournament progresses.

    Attributes
    ----------
    field_id : str
        Short slug identifier, e.g. ``"type_theory"`` or ``"cat_x_hott_r1"``.
    name : str
        Human-readable full name, e.g. ``"Martin-Löf Type Theory"``.
    domain : DomainArea
        The primary intellectual domain.
    description : str
        2-3 paragraph rich description of the field, its history, objects,
        and open problems.
    core_objects : tuple[str, ...]
        The primary mathematical objects of the field, e.g.
        ``("dependent type", "context", "Π-type", "Σ-type", "identity type")``.
    core_morphisms : tuple[str, ...]
        The primary maps / transformations, e.g.
        ``("substitution", "type-theoretic function", "transport")``.
    key_theorems : tuple[str, ...]
        Names of landmark results, e.g. ``("Curry-Howard Correspondence",
        "Canonicity Theorem", "Normalization")``.
    propositions : list[PropositionRecord]
        Accumulated propositions.  Starts with ~8 seed propositions at
        round 0 and roughly doubles with each merge.
    metaphor_links : list[MetaphorLink]
        Cross-domain metaphor links discovered during tournament rounds.
    judgment_site : dict
        How this field maps to JuGeo's judgment site.  Keys include
        ``"primary_coordinate"``, ``"abstraction_level"``, ``"formality"``,
        ``"bridge_potential"``, ``"notes"``.
    round_number : int
        0 = original leaf; k = merged in tournament round k.
    constituent_fields : tuple[str, ...]
        ``field_id``s of the original leaf fields that were merged into
        this node (by induction over the tournament tree).
    llm_summary : str
        LLM-generated synthesis summary written after a merge.
    trust_tier : str
        Overall trust tier for this node.
    metadata : dict
        Arbitrary extra data.
    """

    field_id: str
    name: str
    domain: DomainArea
    description: str
    core_objects: tuple[str, ...]
    core_morphisms: tuple[str, ...]
    key_theorems: tuple[str, ...]
    propositions: list = field(default_factory=list)
    metaphor_links: list = field(default_factory=list)
    judgment_site: dict = field(default_factory=dict)
    round_number: int = 0
    constituent_fields: tuple = ()
    llm_summary: str = ""
    trust_tier: str = "PROPOSAL"
    metadata: dict = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Proposition management
    # ------------------------------------------------------------------

    def proposition_count(self) -> int:
        """Return the number of propositions currently in this node."""
        return len(self.propositions)

    def add_proposition(self, p: PropositionRecord) -> None:
        """Append a proposition to this node's pool."""
        self.propositions.append(p)

    def add_metaphor(self, m: MetaphorLink) -> None:
        """Append a metaphor link to this node."""
        self.metaphor_links.append(m)

    def bridge_theorems(self) -> list[PropositionRecord]:
        """Return all BRIDGE_THEOREM propositions."""
        return [p for p in self.propositions if p.kind == PropositionKind.BRIDGE_THEOREM]

    def propositions_by_kind(self, kind: PropositionKind) -> list[PropositionRecord]:
        """Return all propositions of a given kind."""
        return [p for p in self.propositions if p.kind == kind]

    def top_propositions(self, n: int = 10) -> list[PropositionRecord]:
        """Return the top-n propositions by leverage score."""
        return sorted(self.propositions, key=lambda p: -p.leverage_score)[:n]

    # ------------------------------------------------------------------
    # LaTeX
    # ------------------------------------------------------------------

    def to_latex_section(self) -> str:
        r"""Render this field as a LaTeX \section{} block.

        The section contains:
        - A \\section heading with the field name.
        - A \\subsection{Description} with the multi-paragraph description.
        - A \\subsection{Core Objects and Morphisms} with itemised lists.
        - A \\subsection{Key Theorems} with an itemised list.
        - A \\subsection{Propositions} with all propositions rendered by
          ``PropositionRecord.to_latex()``.
        - If metaphor links are present, a \\subsection{Metaphor Links}.

        Returns
        -------
        str
            A complete LaTeX section fragment.
        """
        lines: list[str] = []
        name_esc = _latex_escape(self.name)
        lines.append(f"\\section{{{name_esc}}}")
        lines.append(f"\\label{{field:{self.field_id}}}")
        lines.append("")

        if self.round_number > 0:
            constituents = ", ".join(self.constituent_fields)
            lines.append(
                f"\\textit{{Synthesis node from round {self.round_number}. "
                f"Constituent fields: {_latex_escape(constituents)}.}}"
            )
            lines.append("")

        # Description
        lines.append("\\subsection{Description}")
        for para in self.description.split("\n\n"):
            para = para.strip()
            if para:
                lines.append(para)
                lines.append("")

        # Core objects and morphisms
        if self.core_objects or self.core_morphisms:
            lines.append("\\subsection{Core Objects and Morphisms}")
            if self.core_objects:
                lines.append("\\paragraph{Primary objects}")
                lines.append("\\begin{itemize}")
                for obj in self.core_objects:
                    lines.append(f"  \\item {_latex_escape(obj)}")
                lines.append("\\end{itemize}")
            if self.core_morphisms:
                lines.append("\\paragraph{Primary morphisms}")
                lines.append("\\begin{itemize}")
                for m in self.core_morphisms:
                    lines.append(f"  \\item {_latex_escape(m)}")
                lines.append("\\end{itemize}")
            lines.append("")

        # Key theorems
        if self.key_theorems:
            lines.append("\\subsection{Landmark Results}")
            lines.append("\\begin{enumerate}")
            for thm in self.key_theorems:
                lines.append(f"  \\item {_latex_escape(thm)}")
            lines.append("\\end{enumerate}")
            lines.append("")

        # Propositions
        if self.propositions:
            lines.append("\\subsection{Propositions}")
            for p in self.propositions:
                lines.append(p.to_latex())
                lines.append("")

        # Metaphor links
        if self.metaphor_links:
            lines.append("\\subsection{Metaphor Links}")
            lines.append("\\begin{description}")
            for ml in self.metaphor_links:
                lines.append(ml.to_latex())
            lines.append("\\end{description}")
            lines.append("")

        # JuGeo judgment site
        if self.judgment_site:
            lines.append("\\subsection{JuGeo Judgment Site}")
            lines.append("\\begin{description}")
            for k, v in self.judgment_site.items():
                lines.append(f"  \\item[{_latex_escape(str(k))}] {_latex_escape(str(v))}")
            lines.append("\\end{description}")
            lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Serialise this FieldNode to a JSON-compatible dict."""
        return {
            "field_id": self.field_id,
            "name": self.name,
            "domain": self.domain.value,
            "description": self.description,
            "core_objects": list(self.core_objects),
            "core_morphisms": list(self.core_morphisms),
            "key_theorems": list(self.key_theorems),
            "propositions": [p.to_dict() for p in self.propositions],
            "metaphor_links": [m.to_dict() for m in self.metaphor_links],
            "judgment_site": self.judgment_site,
            "round_number": self.round_number,
            "constituent_fields": list(self.constituent_fields),
            "llm_summary": self.llm_summary,
            "trust_tier": self.trust_tier,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "FieldNode":
        """Deserialise a FieldNode from a dict produced by ``to_dict()``."""
        return cls(
            field_id=d["field_id"],
            name=d["name"],
            domain=DomainArea(d["domain"]),
            description=d["description"],
            core_objects=tuple(d.get("core_objects", [])),
            core_morphisms=tuple(d.get("core_morphisms", [])),
            key_theorems=tuple(d.get("key_theorems", [])),
            propositions=[PropositionRecord.from_dict(p) for p in d.get("propositions", [])],
            metaphor_links=[MetaphorLink.from_dict(m) for m in d.get("metaphor_links", [])],
            judgment_site=d.get("judgment_site", {}),
            round_number=d.get("round_number", 0),
            constituent_fields=tuple(d.get("constituent_fields", [])),
            llm_summary=d.get("llm_summary", ""),
            trust_tier=d.get("trust_tier", "PROPOSAL"),
            metadata=d.get("metadata", {}),
        )

    def summary_line(self) -> str:
        """One-line summary for logging."""
        return (
            f"FieldNode({self.field_id!r}, round={self.round_number}, "
            f"domain={self.domain.value}, "
            f"props={self.proposition_count()}, "
            f"metaphors={len(self.metaphor_links)})"
        )

    @property
    def keywords(self) -> tuple[str, ...]:
        """Compatibility: returns core_objects as keywords."""
        return self.core_objects

    @classmethod
    def make(
        cls,
        name: str,
        description: str,
        propositions: Any = (),
        constituent_fields: Any = (),
        round_number: int = 0,
        judgment_site: Any = "",
        parent_ids: Any = (),  # accepted for compat, ignored
        keywords: Any = (),
    ) -> "FieldNode":
        """Convenience factory — creates a FieldNode with legacy arg names."""
        import re as _re
        slug = _re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_")[:40]
        js: dict = (
            {"notes": judgment_site} if isinstance(judgment_site, str) else (judgment_site or {})
        )
        return cls(
            field_id=slug or _uid(),
            name=name,
            domain=DomainArea.MATHEMATICS,
            description=description,
            core_objects=tuple(keywords[:6]) if keywords else (),
            core_morphisms=(),
            key_theorems=(),
            propositions=list(propositions),
            judgment_site=js,
            round_number=round_number,
            constituent_fields=tuple(constituent_fields) if constituent_fields else (name,),
        )


@dataclass(frozen=True)
class SynthesisPair:
    """A scored candidate pairing of two FieldNodes for the tournament.

    The LLM judge produces a SynthesisPair after evaluating whether two
    FieldNodes should be merged.  It contains:

    - an ``integration_score`` ∈ [0, 1] (overall fruitfulness),
    - a tuple of ``MetaphorLink``s discovered at the interface,
    - a tuple of ``PropositionRecord`` bridge theorems,
    - and the judge's textual reasoning.

    Attributes
    ----------
    pair_id : str
    field_a_id : str
    field_b_id : str
    integration_score : float
        Overall score in [0, 1]; higher = more fruitful synthesis.
    metaphors_found : tuple[MetaphorLink, ...]
        Cross-domain metaphors discovered by the judge.
    bridge_propositions : tuple[PropositionRecord, ...]
        Bridge theorems formalising the discovered metaphors.
    judge_reasoning : str
        The LLM judge's free-text justification.
    round_number : int
        Which tournament round this pair was scored in.
    """

    pair_id: str
    field_a_id: str
    field_b_id: str
    integration_score: float
    metaphors_found: tuple
    bridge_propositions: tuple
    judge_reasoning: str
    round_number: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "pair_id": self.pair_id,
            "field_a_id": self.field_a_id,
            "field_b_id": self.field_b_id,
            "integration_score": self.integration_score,
            "metaphors_found": [m.to_dict() for m in self.metaphors_found],
            "bridge_propositions": [p.to_dict() for p in self.bridge_propositions],
            "judge_reasoning": self.judge_reasoning,
            "round_number": self.round_number,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "SynthesisPair":
        return cls(
            pair_id=d["pair_id"],
            field_a_id=d["field_a_id"],
            field_b_id=d["field_b_id"],
            integration_score=float(d["integration_score"]),
            metaphors_found=tuple(
                MetaphorLink.from_dict(m) for m in d.get("metaphors_found", [])
            ),
            bridge_propositions=tuple(
                PropositionRecord.from_dict(p) for p in d.get("bridge_propositions", [])
            ),
            judge_reasoning=d.get("judge_reasoning", ""),
            round_number=int(d.get("round_number", 0)),
        )

    def summary(self) -> str:
        return (
            f"SynthesisPair({self.field_a_id} × {self.field_b_id}, "
            f"score={self.integration_score:.3f}, "
            f"round={self.round_number}, "
            f"bridges={len(self.bridge_propositions)}, "
            f"metaphors={len(self.metaphors_found)})"
        )

    # Compatibility aliases for code that uses legacy field names
    @property
    def metaphors(self) -> tuple:
        """Compatibility alias for metaphors_found."""
        return self.metaphors_found

    @property
    def bridge_theorems(self) -> tuple:
        """Compatibility alias for bridge_propositions."""
        return self.bridge_propositions

    @property
    def reasoning(self) -> str:
        """Compatibility alias for judge_reasoning."""
        return self.judge_reasoning

    @classmethod
    def make(
        cls,
        field_a_id: str,
        field_b_id: str,
        integration_score: float,
        leverage: float = 0.5,
        metaphor_richness: float = 0.5,
        transportability: float = 0.5,
        proof_density: float = 0.5,
        novelty: float = 0.5,
        geometry_fit: float = 0.5,
        metaphors: tuple = (),
        bridge_theorems: tuple = (),
        reasoning: str = "",
        round_number: int = 0,
    ) -> "SynthesisPair":
        """Convenience factory — creates a SynthesisPair with legacy arg names."""
        return cls(
            pair_id=_uid(),
            field_a_id=field_a_id,
            field_b_id=field_b_id,
            integration_score=float(integration_score),
            metaphors_found=tuple(metaphors),
            bridge_propositions=tuple(bridge_theorems),
            judge_reasoning=reasoning,
            round_number=round_number,
        )


@dataclass
class TournamentState:
    """Mutable state of the binary tournament.

    This is the top-level object that tracks the entire tournament.  It is
    serialisable to JSON and can be checkpointed and restored.

    Attributes
    ----------
    round_number : int
        Current tournament round (0 = initial, 6 = final for 48 fields).
    active_nodes : list[FieldNode]
        Nodes still in the tournament (not yet merged or eliminated).
    completed_merges : list[SynthesisPair]
        All merge decisions made so far (one per pair per round).
    all_propositions : list[PropositionRecord]
        Global flat pool of all propositions across all nodes.
    all_metaphors : list[MetaphorLink]
        Global flat pool of all metaphor links discovered so far.
    is_complete : bool
        True when only one FieldNode remains.
    final_synthesis : FieldNode | None
        The single surviving node after all rounds (set when is_complete).
    """

    round_number: int = 0
    active_nodes: list = field(default_factory=list)
    completed_merges: list = field(default_factory=list)
    all_propositions: list = field(default_factory=list)
    all_metaphors: list = field(default_factory=list)
    is_complete: bool = False
    final_synthesis: Optional[FieldNode] = None

    # ------------------------------------------------------------------
    # Convenience accessors
    # ------------------------------------------------------------------

    def node_count(self) -> int:
        return len(self.active_nodes)

    def proposition_count(self) -> int:
        return len(self.all_propositions)

    def metaphor_count(self) -> int:
        return len(self.all_metaphors)

    def get_node(self, field_id: str) -> Optional[FieldNode]:
        return next((n for n in self.active_nodes if n.field_id == field_id), None)

    def advance_round(self) -> None:
        """Increment the round counter."""
        self.round_number += 1
        if len(self.active_nodes) <= 1:
            self.is_complete = True
            if self.active_nodes:
                self.final_synthesis = self.active_nodes[0]

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Serialise the entire tournament state to a JSON-compatible dict."""
        return {
            "round_number": self.round_number,
            "active_nodes": [n.to_dict() for n in self.active_nodes],
            "completed_merges": [m.to_dict() for m in self.completed_merges],
            "all_propositions": [p.to_dict() for p in self.all_propositions],
            "all_metaphors": [m.to_dict() for m in self.all_metaphors],
            "is_complete": self.is_complete,
            "final_synthesis": (
                self.final_synthesis.to_dict() if self.final_synthesis else None
            ),
        }

    def save(self, path: str) -> None:
        """Save the tournament state as a JSON checkpoint.

        Parameters
        ----------
        path : str
            File path to write to.  Parent directories must exist.
        """
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(self.to_dict(), fh, indent=2, ensure_ascii=False)

    @classmethod
    def load(cls, path: str) -> "TournamentState":
        """Load a tournament state from a JSON checkpoint.

        Parameters
        ----------
        path : str
            Path to a JSON file previously written by ``save()``.

        Returns
        -------
        TournamentState
        """
        with open(path, encoding="utf-8") as fh:
            d = json.load(fh)
        state = cls(
            round_number=d.get("round_number", 0),
            active_nodes=[FieldNode.from_dict(n) for n in d.get("active_nodes", [])],
            completed_merges=[
                SynthesisPair.from_dict(m) for m in d.get("completed_merges", [])
            ],
            all_propositions=[
                PropositionRecord.from_dict(p) for p in d.get("all_propositions", [])
            ],
            all_metaphors=[
                MetaphorLink.from_dict(m) for m in d.get("all_metaphors", [])
            ],
            is_complete=d.get("is_complete", False),
            final_synthesis=(
                FieldNode.from_dict(d["final_synthesis"])
                if d.get("final_synthesis")
                else None
            ),
        )
        return state

    def summary(self) -> str:
        status = "COMPLETE" if self.is_complete else f"ROUND {self.round_number}"
        return (
            f"TournamentState({status}: {self.node_count()} nodes, "
            f"{self.proposition_count()} propositions, "
            f"{self.metaphor_count()} metaphors, "
            f"{len(self.completed_merges)} merges)"
        )

    # ------------------------------------------------------------------
    # Compatibility methods for new-style tournament code
    # ------------------------------------------------------------------

    @property
    def current_round(self) -> int:
        """Compatibility alias for round_number."""
        return self.round_number

    @current_round.setter
    def current_round(self, value: int) -> None:
        self.round_number = value

    def touch(self) -> None:
        """No-op compatibility stub (used when state was a frozen dataclass)."""

    def total_propositions(self) -> int:
        """Total proposition count across all active nodes."""
        return sum(n.proposition_count() for n in self.active_nodes)

    def register_pair(self, pair: "SynthesisPair") -> None:
        """Append a scored pair to completed_merges."""
        self.completed_merges.append(pair)

    def register_metaphor(self, m: "MetaphorLink") -> None:
        """Append a metaphor to the global pool."""
        self.all_metaphors.append(m)

    def register_node(self, node: "FieldNode") -> None:
        """Track a node in the global node index (bookkeeping only).

        The caller is responsible for updating ``active_nodes`` directly when
        replacing pairs with their merged result.
        """
        # Intentional no-op: active_nodes is managed by TournamentRound.run()
        # which replaces the list wholesale; this exists for API compatibility.

    @property
    def all_nodes(self) -> dict:
        """Dict mapping field_id → FieldNode for all currently active nodes."""
        return {n.field_id: n for n in self.active_nodes}

if __name__ == "__main__":
    import tempfile

    print("=== Synthesis Frontier models.py — smoke test ===\n")

    # ---- PropositionRecord examples with genuine mathematical content ----

    p_yoneda = PropositionRecord(
        prop_id="ct_thm_yoneda",
        kind=PropositionKind.THEOREM,
        title="Yoneda Lemma",
        statement=(
            r"For any locally small category $\mathcal{C}$, functor "
            r"$F : \mathcal{C} \to \mathbf{Set}$, and object $c \in \mathcal{C}$, "
            r"there is a natural isomorphism "
            r"$\mathrm{Nat}(\mathcal{C}(c, -), F) \cong F(c)$."
        ),
        proof_sketch=(
            "Given a natural transformation $\eta : \mathcal{C}(c,-)\Rightarrow F$, "
            "define $\phi(\eta) = \eta_c(\mathrm{id}_c) \in F(c)$.  Conversely, given "
            "$x \in F(c)$ define $\psi(x)_d(f) = F(f)(x)$ for each $f : c \to d$.  "
            "Verify $\phi$ and $\psi$ are mutually inverse and natural in $c$ and $F$."
        ),
        why_useful=(
            "The Yoneda lemma is arguably the most important result in category theory: "
            "it shows that every object is completely determined by its 'network of "
            "relationships' (the hom-functor), embedding $\\mathcal{C}$ fully faithfully "
            "into its presheaf category $\\mathbf{Set}^{\\mathcal{C}^{\\mathrm{op}}}$."
        ),
        source_field="category_theory",
        target_fields=("type_theory", "topos_theory", "sheaf_theory", "homotopy_type_theory"),
        metaphor_tags=("representability", "hom-tensor-adjunction", "universal-property"),
        trust_tier="VERIFIED",
        leverage_score=0.98,
        proof_difficulty="EASY",
        dependencies=(),
        judgment_coordinate=(
            "(c=0.1,φ=0.95,A=0.95,E=ANALYTIC,O=MATHEMATICAL,B=0.9,T=VERIFIED,Π=EASY)"
        ),
        metadata={"source_ref": "Mac Lane, Categories for the Working Mathematician, §III.2"},
    )

    p_curry_howard = PropositionRecord(
        prop_id="tt_thm_curry_howard",
        kind=PropositionKind.BRIDGE_THEOREM,
        title="Curry-Howard Correspondence",
        statement=(
            r"There is a bijection between proofs of a proposition $P$ in "
            r"intuitionistic propositional logic (natural deduction) and "
            r"closed terms of type $\llbracket P \rrbracket$ in simply-typed "
            r"$\lambda$-calculus, extended to predicate logic via dependent types: "
            r"$\forall x.\, P(x)$ corresponds to $\Pi(x:A).\, B(x)$ and "
            r"$\exists x.\, P(x)$ corresponds to $\Sigma(x:A).\, B(x)$."
        ),
        proof_sketch=(
            "Induction on proof structure: each natural deduction rule corresponds "
            "to a $\\lambda$-calculus typing rule.  $\\wedge$-introduction maps to "
            "pair construction, $\\Rightarrow$-introduction to $\\lambda$-abstraction, "
            "$\\Rightarrow$-elimination to application.  Modus ponens = function "
            "application."
        ),
        why_useful=(
            "Curry-Howard is the foundational bridge theorem of the entire field: it "
            "equates formal proofs with programs, making proof assistants (Coq, Agda, "
            "Lean) possible and connecting mathematical logic directly to programming "
            "language theory."
        ),
        source_field="type_theory",
        target_fields=(
            "logic", "category_theory", "dependent_type_theory", "linear_logic",
            "proof_complexity",
        ),
        metaphor_tags=("propositions-as-types", "proofs-as-programs", "CHI"),
        trust_tier="VERIFIED",
        leverage_score=0.99,
        proof_difficulty="EASY",
        dependencies=(),
        judgment_coordinate=(
            "(c=0.2,φ=0.95,A=0.9,E=ANALYTIC,O=MATHEMATICAL,B=0.99,T=VERIFIED,Π=EASY)"
        ),
        metadata={"source_ref": "Howard 1980; Curry 1934"},
    )

    p_adjoint_functor = PropositionRecord(
        prop_id="ct_thm_gaft",
        kind=PropositionKind.THEOREM,
        title="General Adjoint Functor Theorem (Freyd)",
        statement=(
            r"A functor $G : \mathcal{D} \to \mathcal{C}$ between locally small "
            r"categories has a left adjoint if and only if $G$ preserves all small "
            r"limits and for every $c \in \mathcal{C}$ the comma category "
            r"$(c \downarrow G)$ satisfies the solution set condition: there exists "
            r"a set $S$ of objects such that every object in $(c \downarrow G)$ has "
            r"a morphism from some member of $S$."
        ),
        proof_sketch=(
            "Construct the left adjoint $F(c)$ as the limit of the comma category "
            "diagram $(c \\downarrow G) \\to \\mathcal{D}$, which exists by the "
            "solution set condition and small-limits assumption.  The universal "
            "morphism is the limit cone."
        ),
        why_useful=(
            "GAFT gives a practical recipe for proving the existence of left adjoints "
            "without constructing them explicitly.  It underlies free constructions "
            "(free groups, free algebras, sheafification) and connects to the "
            "completeness-continuity duality in domain theory."
        ),
        source_field="category_theory",
        target_fields=("topos_theory", "domain_theory", "sheaf_theory"),
        metaphor_tags=("free-construction", "universal-algebra", "completeness"),
        trust_tier="VERIFIED",
        leverage_score=0.88,
        proof_difficulty="MEDIUM",
        dependencies=(),
        judgment_coordinate=(
            "(c=0.1,φ=0.9,A=0.9,E=ANALYTIC,O=MATHEMATICAL,B=0.75,T=VERIFIED,Π=MEDIUM)"
        ),
        metadata={"source_ref": "Freyd, Abelian Categories (1964), Appendix; Mac Lane §V.8"},
    )

    p_seely = PropositionRecord(
        prop_id="ct_tt_bridge_seely",
        kind=PropositionKind.BRIDGE_THEOREM,
        title="Seely Correspondence: MLTT ↔ LCCC",
        statement=(
            r"The category of types and terms in Martin-Löf type theory forms a "
            r"locally cartesian closed category (LCCC), and conversely every LCCC "
            r"$\mathcal{C}$ gives rise to a model of dependent type theory via the "
            r"Seely correspondence: dependent types over $A$ correspond to maps "
            r"into $A$, $\Pi$-types to right adjoints of pullback, and $\Sigma$-types "
            r"to composition."
        ),
        proof_sketch=(
            "Interpret a type $B : A \\to \\mathrm{Type}$ as a morphism "
            "$b : \\sum_{x:A} B(x) \\to A$.  The $\\Pi$-type functor is the right "
            "adjoint to pullback along $b$; the $\\Sigma$-type is composition.  "
            "Coherence requires that substitution commutes strictly with "
            "interpretation, handled by the split-fibration/cleavage structure."
        ),
        why_useful=(
            "The Seely correspondence is the canonical semantic foundation for "
            "dependent type theory: it shows that MLTT is the internal language of "
            "LCCCs, enabling algebraic and categorical methods in type theory."
        ),
        source_field="category_theory",
        target_fields=("type_theory", "dependent_type_theory", "homotopy_type_theory"),
        metaphor_tags=("internal-language", "LCCC", "fibration"),
        trust_tier="VERIFIED",
        leverage_score=0.95,
        proof_difficulty="HARD",
        dependencies=("ct_thm_gaft",),
        judgment_coordinate=(
            "(c=0.1,φ=0.95,A=0.95,E=ANALYTIC,O=MATHEMATICAL,B=0.95,T=VERIFIED,Π=HARD)"
        ),
        metadata={"source_ref": "Seely 1984; Hofmann 1997 (coherence)"},
    )

    print("PropositionRecord examples:")
    for p in [p_yoneda, p_curry_howard, p_adjoint_functor, p_seely]:
        print(f"  {p.summary()}")

    # ---- MetaphorLink ----

    ml_monad_effect = MetaphorLink(
        link_id="ml_ct_eff_monad",
        source_field="category_theory",
        target_field="effect_systems",
        source_concept="monad (T, η, μ)",
        target_concept="algebraic effect handler",
        metaphor_description=(
            "A monad $(T, \\eta, \\mu)$ in category theory corresponds to an algebraic "
            "effect + handler pair: the functor $T$ maps a type $A$ to the type of "
            "$A$-values with possible effects, $\\eta$ is the pure/return operation, "
            "$\\mu$ (join) is the handle/run operation that eliminates one layer of "
            "effect.  Plotkin-Power showed that any algebraic theory induces a monad, "
            "and free monads = unhandled effect trees."
        ),
        bridge_propositions=("ct_tt_bridge_seely",),
        strength=0.92,
        kind="ISOMORPHISM",
        llm_judge_score=0.91,
        llm_judge_reasoning=(
            "The monad-effect correspondence is a textbook example of a precise "
            "functorial connection: every algebraic effect theory induces a monad "
            "via the free-algebra / Eilenberg-Moore construction, and every monad "
            "arises this way (if we allow for infinitary theories).  Score: 0.91."
        ),
    )

    ml_separation_linear = MetaphorLink(
        link_id="ml_sep_lin_resource",
        source_field="separation_logic",
        target_field="linear_logic",
        source_concept="separating conjunction P * Q",
        target_concept="multiplicative conjunction P ⊗ Q",
        metaphor_description=(
            "In separation logic, $P * Q$ asserts that $P$ and $Q$ hold for "
            "disjoint heap regions — resources cannot be shared.  In linear logic, "
            "$P \\otimes Q$ asserts $P$ and $Q$ are both available but each "
            "hypothesis must be consumed exactly once.  The frame rule of separation "
            "logic is precisely the \\textit{weakening-free} cut rule of linear logic "
            "restricted to the multiplicative fragment."
        ),
        bridge_propositions=(),
        strength=0.89,
        kind="FUNCTOR",
        llm_judge_score=0.88,
        llm_judge_reasoning=(
            "The O'Hearn-Pym BI logic makes this connection explicit via the "
            "resource semantics of bunched implications.  Strength 0.89 because "
            "separation logic adds a concrete heap model that is absent from pure "
            "linear logic."
        ),
    )

    print("\nMetaphorLink examples:")
    print(f"  {ml_monad_effect.summary()}")
    print(f"  {ml_separation_linear.summary()}")

    # ---- FieldNode ----

    ct_field = FieldNode(
        field_id="category_theory",
        name="Category Theory",
        domain=DomainArea.MATHEMATICS,
        description=(
            "Category theory, founded by Eilenberg and Mac Lane (1945) in the context "
            "of algebraic topology, is the mathematical study of abstract structure and "
            "the maps (functors) that preserve it.  Rather than working with the "
            "internal elements of objects, category theory focuses on the morphisms "
            "between objects and the universal properties they satisfy.\n\n"
            "The central organising principles are adjunctions (free/forgetful, "
            "product/exponential, sheafification/inclusion), limits and colimits "
            "(which unify constructions like products, pullbacks, free algebras, and "
            "quotients), and monads (which abstract algebraic theories and "
            "computational effects).  The Yoneda lemma — arguably the most important "
            "result in the field — shows that every object is completely characterised "
            "by its hom-functor, embedding any category fully faithfully into its "
            "presheaf category.\n\n"
            "Category theory has become a unifying language across mathematics, "
            "theoretical computer science (type theory, denotational semantics, "
            "linear logic), physics (TQFT, quantum foundations), and linguistics "
            "(Montague grammar, distributional semantics).  Higher category theory "
            "(∞-categories, ∞-toposes) extends these ideas to homotopy-coherent "
            "settings, connecting with homotopy type theory and derived algebraic "
            "geometry."
        ),
        core_objects=(
            "small category",
            "functor",
            "natural transformation",
            "adjunction",
            "limit / colimit",
            "monad",
            "topos",
            "∞-category",
        ),
        core_morphisms=(
            "functor (between categories)",
            "natural transformation (between functors)",
            "monad morphism",
            "geometric morphism (between toposes)",
            "cartesian morphism (in a fibration)",
        ),
        key_theorems=(
            "Yoneda Lemma",
            "General Adjoint Functor Theorem (Freyd)",
            "Special Adjoint Functor Theorem",
            "Monadicity Theorem (Beck)",
            "Barr-Beck Comonadicity",
            "Mac Lane Coherence Theorem",
            "Giraud's Theorem (characterising Grothendieck toposes)",
        ),
        propositions=[p_yoneda, p_adjoint_functor, p_seely],
        metaphor_links=[ml_monad_effect],
        judgment_site={
            "primary_coordinate": "A=0.95,φ=0.95",
            "abstraction_level": "maximal — studies structure of structure",
            "formality": "fully formal; mechanised in Lean 4 (Mathlib)",
            "bridge_potential": "0.95 — universal language across mathematics",
            "notes": (
                "Category theory is the language in which JuGeo's own judgment "
                "geometry is formulated: judgment sites are Grothendieck sites, "
                "and the judgment functor is a sheaf."
            ),
        },
        round_number=0,
        constituent_fields=("category_theory",),
        trust_tier="VERIFIED",
    )

    ct_field.add_proposition(p_curry_howard)
    print(f"\nFieldNode: {ct_field.summary_line()}")
    print(f"  Top proposition: {ct_field.top_propositions(1)[0].title}")

    # ---- to_dict / from_dict round-trip ----
    print("\nTesting serialisation round-trip …")
    ct_dict = ct_field.to_dict()
    ct_restored = FieldNode.from_dict(ct_dict)
    assert ct_restored.field_id == ct_field.field_id
    assert ct_restored.proposition_count() == ct_field.proposition_count()
    print("  FieldNode round-trip: OK")

    prop_dict = p_yoneda.to_dict()
    prop_restored = PropositionRecord.from_dict(prop_dict)
    assert prop_restored.prop_id == p_yoneda.prop_id
    assert prop_restored.kind == p_yoneda.kind
    print("  PropositionRecord round-trip: OK")

    ml_dict = ml_monad_effect.to_dict()
    ml_restored = MetaphorLink.from_dict(ml_dict)
    assert ml_restored.link_id == ml_monad_effect.link_id
    print("  MetaphorLink round-trip: OK")

    # ---- SynthesisPair ----
    sp = SynthesisPair(
        pair_id="sp_ct_tt_r1",
        field_a_id="category_theory",
        field_b_id="type_theory",
        integration_score=0.97,
        metaphors_found=(ml_monad_effect,),
        bridge_propositions=(p_curry_howard, p_seely),
        judge_reasoning=(
            "Category theory and type theory are connected by the Seely "
            "correspondence (MLTT ↔ LCCC), the Curry-Howard-Lambek trinity, "
            "and the monad-effect analogy.  These three bridge theorems alone "
            "justify an integration score of 0.97."
        ),
        round_number=1,
    )
    print(f"\nSynthesisPair: {sp.summary()}")
    sp_dict = sp.to_dict()
    sp_restored = SynthesisPair.from_dict(sp_dict)
    assert sp_restored.pair_id == sp.pair_id
    print("  SynthesisPair round-trip: OK")

    # ---- TournamentState ----
    state = TournamentState(
        round_number=1,
        active_nodes=[ct_field],
        completed_merges=[sp],
        all_propositions=[p_yoneda, p_curry_howard, p_adjoint_functor, p_seely],
        all_metaphors=[ml_monad_effect, ml_separation_linear],
    )
    print(f"\nTournamentState: {state.summary()}")

    with tempfile.TemporaryDirectory() as tmpdir:
        checkpoint_path = os.path.join(tmpdir, "test_checkpoint.json")
        state.save(checkpoint_path)
        state_loaded = TournamentState.load(checkpoint_path)
        assert state_loaded.round_number == state.round_number
        assert len(state_loaded.active_nodes) == len(state.active_nodes)
        assert len(state_loaded.all_propositions) == len(state.all_propositions)
        print(f"  Checkpoint save/load: OK (path={checkpoint_path})")

    # ---- LaTeX output sample ----
    print("\n--- LaTeX sample (first 15 lines) ---")
    latex = ct_field.to_latex_section()
    for line in latex.split("\n")[:15]:
        print(f"  {line}")

    print("\n=== All smoke tests passed ===")
