from __future__ import annotations

"""
theory2.tex Ch19 §1 — Import is Execution Plus Namespace Transport
===================================================================

This module formalizes the semantics of Python's import system through the lens
of jugeo's site-theoretic judgment framework.  The central thesis (Ch19 §1) is:

    **An import statement is simultaneously**
    1. **Execution** — the interpreter runs the body of the imported module
       (or retrieves the already-executed module object from ``sys.modules``).
    2. **Namespace transport** — selected names (or the whole module object)
       are injected into the importing namespace, constituting a *morphism*
       between two coordinate objects in the site.

This dual character is not merely academic.  It has direct consequences for
reasoning about Python programs:

* **Execution effects are irreversible** by default.  If ``import m`` causes
  ``m`` to register a signal handler, open a socket, or write to disk, that
  effect is observable even if the importing namespace later deletes the name.

* **Namespace transport is selective and order-dependent.**  ``from m import f``
  transports only ``f``, binding it to the caller's namespace under the same
  name (or an alias).  This creates a *fork* in provenance: the caller's ``f``
  and ``m.f`` may diverge after reassignment.

* **Star imports collapse provenance.**  ``from m import *`` transports every
  public name in ``m.__all__`` (or every non-underscore-prefixed name if
  ``__all__`` is absent), making it impossible for static analysis to determine
  the origin of any given name without reading ``m`` itself.

* **Conditional imports introduce branching.**  ``try: import fast_impl except
  ImportError: import slow_impl`` means the effective namespace depends on
  runtime availability of packages, creating a *branching topology* in the
  import graph.

Formalisation (site-theoretic sketch)
--------------------------------------
Let **C** be the category whose objects are Python modules (identified by their
fully-qualified names) and whose morphisms are import relationships.  A morphism
``f : A → B`` exists when module ``B`` imports from module ``A``.

A *covering family* for object ``A`` is a collection of modules that together
"cover" the interface of ``A`` — i.e., every public name in ``A`` is imported
by at least one member of the family.  This mirrors the Grothendieck topology
condition that every object is covered by the sieve generated by its covering
families.

An *import execution record* is a carrier in the judgment sense: it witnesses
that the execution of module ``m`` took place at a specific timestamp, that the
namespace of the importer before and after the import had specific key-sets, and
that the import either succeeded or failed with a given error message.

A *namespace delta record* captures the difference between the importer's
namespace before and after executing an import statement, decomposed into added,
removed, and changed names.  This is the concrete manifestation of the
"namespace transport" half of the thesis.

References
----------
* theory2.tex Ch19 §1 "Import is execution plus namespace transport"
* PEP 302 — New Import Hooks
* PEP 328 — Imports: Multi-Line and Absolute/Relative
* PEP 366 — Main module explicit relative imports
* importlib documentation: https://docs.python.org/3/library/importlib.html
* sys.modules contract: CPython/Lib/importlib/_bootstrap.py

Author: jugeo project — generated with Copilot assistance
"""

import ast
import importlib
import importlib.machinery
import importlib.util
import logging
import pkgutil
import sys
import time
import types
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

# copilot: standard jugeo logger — all submodules in this package use __name__
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Cross-package jugeo imports with full stub fallbacks
# (theory2.tex Ch19 §1 requires these even in standalone / partial-install mode)
# ---------------------------------------------------------------------------

try:
    from jugeo.geometry.site import (
        Coordinate, CoordinateKind, Morphism, MorphismKind,
        Site, SiteBuilder, CoveringFamily, GrothendieckTopology, CoordinateObject,
    )
except ImportError:
    from dataclasses import dataclass as _dc, field as _field
    from enum import Enum

    class CoordinateKind(Enum):
        MODULE = "module"
        FUNCTION = "function"
        INTERFACE = "interface"
        TEST = "test"
        THEOREM = "theorem"
        REGION = "region"

    class MorphismKind(Enum):
        RESTRICTION = "restriction"
        INCLUSION = "inclusion"
        TRANSPORT = "transport"
        REFINEMENT = "refinement"

    @_dc(frozen=True)
    class Coordinate:
        components: tuple = ()
        kind: "CoordinateKind" = CoordinateKind.MODULE
        support_labels: frozenset = frozenset()

    CoordinateObject = Coordinate

    @_dc(frozen=True)
    class Morphism:
        source: "Coordinate" = None
        target: "Coordinate" = None
        kind: "MorphismKind" = MorphismKind.INCLUSION
        label: str = ""

    @_dc
    class CoveringFamily:
        base: "Coordinate" = None
        members: list = _field(default_factory=list)

    @_dc
    class GrothendieckTopology:
        name: str = "custom"

    @_dc
    class Site:
        label: str = ""
        _coords: list = _field(default_factory=list)
        _morphisms: list = _field(default_factory=list)

        def add_coordinate(self, c):
            self._coords.append(c)
            return self

        def add_morphism(self, m):
            self._morphisms.append(m)
            return self

        def objects(self):
            return list(self._coords)

        def morphisms_from(self, c):
            return [m for m in self._morphisms if getattr(m, "source", None) == c]

    @_dc
    class SiteBuilder:
        _coords: list = _field(default_factory=list)
        _morphisms: list = _field(default_factory=list)

        def add_coordinate(self, c):
            self._coords.append(c)
            return self

        def add_morphism(self, m):
            self._morphisms.append(m)
            return self

        def build(self):
            return Site()


try:
    from jugeo.judgments.judgment_terms import (
        Judgment, JudgmentStatus, TrustLevel, Proposition, PropositionKind,
        Carrier, EvidenceBundle, EvidenceItem, EvidenceItemKind,
        ResidualObligation, Obstruction, TrustAnnotation, Provenance,
    )
except ImportError:
    from enum import Enum
    from dataclasses import dataclass as _dc, field as _field

    class JudgmentStatus(str, Enum):
        PROPOSED = "proposed"
        SETTLED = "settled"
        OBSTRUCTED = "obstructed"
        OPEN = "open"

    class TrustLevel(int, Enum):
        COPILOT_SUGGESTED = 1
        ORACLE_PROPOSED = 2
        RUNTIME_WITNESSED = 3
        VERIFIED = 4

    class PropositionKind(str, Enum):
        STRUCTURAL = "structural"
        BEHAVIORAL = "behavioral"
        TEMPORAL = "temporal"
        INVARIANT = "invariant"
        LIVENESS = "liveness"
        SAFETY = "safety"

    class EvidenceItemKind(str, Enum):
        STATIC_ANALYSIS = "static_analysis"
        RUNTIME_TRACE = "runtime_trace"
        THEOREM_PROOF = "theorem_proof"
        COPILOT_ANNOTATION = "copilot_annotation"

    @_dc(frozen=True)
    class Proposition:
        kind: "PropositionKind" = PropositionKind.STRUCTURAL
        statement: str = ""
        label: str = ""

    @_dc(frozen=True)
    class Carrier:
        coordinate: object = None
        payload: object = None
        label: str = ""

    @_dc
    class EvidenceItem:
        kind: "EvidenceItemKind" = EvidenceItemKind.STATIC_ANALYSIS
        payload: object = None
        label: str = ""

    @_dc
    class EvidenceBundle:
        items: list = _field(default_factory=list)

        def add(self, item):
            self.items.append(item)
            return self

    @_dc
    class TrustAnnotation:
        level: "TrustLevel" = TrustLevel.COPILOT_SUGGESTED
        rationale: str = ""

    @_dc
    class Provenance:
        source: str = ""
        module: str = ""
        timestamp: str = ""

    @_dc
    class ResidualObligation:
        description: str = ""
        discharged: bool = False

    @_dc
    class Obstruction:
        description: str = ""
        coordinate: object = None

    @_dc
    class Judgment:
        status: "JudgmentStatus" = JudgmentStatus.PROPOSED
        proposition: "Proposition" = None
        carrier: "Carrier" = None
        evidence: "EvidenceBundle" = _field(default_factory=EvidenceBundle)
        trust: "TrustAnnotation" = _field(default_factory=TrustAnnotation)
        provenance: "Provenance" = _field(default_factory=Provenance)
        obligations: list = _field(default_factory=list)
        label: str = ""

        def settle(self):
            self.status = JudgmentStatus.SETTLED
            return self

        def obstruct(self, obs):
            self.status = JudgmentStatus.OBSTRUCTED
            return self


try:
    from jugeo.solver.z3_session import SolveOutcome, Z3Formula, Z3Session, z3_available
except ImportError:
    from enum import Enum
    from dataclasses import dataclass as _dc

    class SolveOutcome(str, Enum):
        SAT = "sat"
        UNSAT = "unsat"
        UNKNOWN = "unknown"

    @_dc
    class Z3Formula:
        smt2: str = ""
        label: str = ""

    @_dc
    class Z3Session:
        def check(self, formula):
            return SolveOutcome.UNKNOWN

        def add_assertion(self, formula):
            return self

    def z3_available() -> bool:
        return False


# ===========================================================================
# §1 — Domain enumerations
# ===========================================================================

class ImportKind(str, Enum):
    """
    Classifies the syntactic form of a Python import statement.

    theory2.tex Ch19 §1 distinguishes five import forms, each with distinct
    implications for namespace transport and execution semantics:

    ABSOLUTE
        ``import foo`` or ``import foo.bar`` — resolves against sys.path
        from the package root.  Execution of ``foo`` (and its ancestors) is
        triggered the first time.  The name ``foo`` (or ``foo.bar``) is
        added to the importing namespace.

    RELATIVE
        ``from . import sibling`` or ``from ..utils import helper`` — resolved
        relative to the importing package's ``__name__``.  Requires that the
        importing module already has a ``__package__`` attribute set by the
        loader.  Enables refactoring of intra-package references without
        touching absolute paths.

    STAR
        ``from module import *`` — transports every public name from
        ``module.__all__`` (or every non-underscore name if ``__all__`` is
        absent) into the importing namespace.  Provenance of individual names
        is lost unless explicit ``__all__`` is defined in the source module.
        Static analysis tools must inspect the source module to enumerate
        transported names.

    FROM
        ``from module import name`` or ``from module import name as alias`` —
        transports a specific set of names, optionally under aliases.  This is
        the most explicit form and supports fine-grained dependency analysis.
        The source module is still fully executed.

    CONDITIONAL
        A structural classification applied post-hoc by the analyzer when an
        import statement appears inside a ``try/except ImportError`` block,
        an ``if TYPE_CHECKING:`` guard, or inside an ``if sys.platform ==``
        branch.  The import's effect on the runtime namespace is conditional
        on environment state.
    """

    ABSOLUTE = "absolute"
    RELATIVE = "relative"
    STAR = "star"
    FROM = "from"
    CONDITIONAL = "conditional"


# ===========================================================================
# §2 — Immutable value objects (frozen dataclasses)
# ===========================================================================

@dataclass(frozen=True, slots=True)
class ImportExecutionRecord:
    """
    An immutable record of a single import statement's execution.

    theory2.tex Ch19 §1 — Execution witness carrier.

    Each field captures one observable aspect of the import event.  The
    frozen/slots combination ensures that records can be used as dict keys
    and stored in sets without accidental mutation.

    Fields
    ------
    module_name : str
        Fully-qualified name of the module being imported (e.g.,
        ``"jugeo.geometry.site"`` or ``"os.path"``).  For relative imports
        this is the resolved absolute name after package prefix expansion.

    imported_names : tuple[str, ...]
        The specific names extracted into the importing namespace.  Empty
        tuple for ``import foo`` style (the name added is the module's top-
        level identifier, not an attribute).  For ``from m import f, g``
        this would be ``("f", "g")``.

    execution_timestamp : float
        ``time.time()`` value recorded immediately after the import
        completed (or failed).  Useful for reconstructing import ordering
        and detecting import-time races in multi-threaded programs.

    namespace_before : tuple[str, ...]
        Sorted snapshot of ``list(caller_globals.keys())`` taken immediately
        before the import statement was executed.  Stored as a sorted tuple
        for canonical representation and hashability.

    namespace_after : tuple[str, ...]
        Sorted snapshot of ``list(caller_globals.keys())`` taken immediately
        after the import completed.  The delta between this and
        ``namespace_before`` yields the transported names.

    execution_succeeded : bool
        ``True`` if the import completed without raising an exception.
        ``False`` if the import raised ``ImportError``, ``ModuleNotFoundError``,
        or any other exception during module body execution.

    error_message : str
        Empty string when ``execution_succeeded`` is ``True``.  Otherwise
        contains ``str(exc)`` from the caught exception, providing
        diagnostic context.

    # copilot: this record is the central evidence unit for import-execution judgments
    """

    module_name: str
    imported_names: tuple
    execution_timestamp: float
    namespace_before: tuple
    namespace_after: tuple
    execution_succeeded: bool
    error_message: str

    @property
    def transported_names(self) -> frozenset:
        """
        Derive transported names as the set difference between namespace_after
        and namespace_before.

        Returns the frozenset of names that appeared in the namespace after
        the import that were not present before.  This is a pure function of
        the two namespace snapshots and does not require re-execution.

        # copilot: set arithmetic on tuples — convert to frozensets first
        """
        return frozenset(self.namespace_after) - frozenset(self.namespace_before)

    @property
    def removed_names(self) -> frozenset:
        """
        Names that were in namespace_before but not in namespace_after.

        In normal import scenarios this should be empty, but star-imports that
        shadow builtins or ``del`` statements in module bodies can cause names
        to disappear.  This property surfaces such anomalies.

        # copilot: removal of names during import is an anti-pattern worth flagging
        """
        return frozenset(self.namespace_before) - frozenset(self.namespace_after)

    def as_coordinate(self) -> "Coordinate":
        """
        Lift this record to a ``Coordinate`` in the site of modules.

        The coordinate's ``components`` field is set to a one-element tuple
        containing the module name.  The ``kind`` is set to
        ``CoordinateKind.MODULE``.

        # copilot: used by build_execution_judgment to attach records to the site
        """
        return Coordinate(
            components=(self.module_name,),
            kind=CoordinateKind.MODULE,
            support_labels=frozenset(self.imported_names),
        )


@dataclass(frozen=True, slots=True)
class NamespaceTransportResult:
    """
    Immutable record of a namespace transport morphism between two modules.

    theory2.tex Ch19 §1 — Namespace transport morphism.

    When module B imports names from module A, a morphism A → B is created
    in the site of modules.  This record captures the metadata of that
    morphism: what was transported, in which direction, and what coordinate
    object represents the target.

    Fields
    ------
    source_module : str
        Fully-qualified name of the module supplying the names (the domain
        of the morphism, e.g., ``"jugeo.geometry.site"``).

    target_module : str
        Fully-qualified name of the module receiving the names (the codomain,
        e.g., ``"jugeo.python_runtime.import_graph....``).

    transported_names : tuple[str, ...]
        Sorted tuple of the names that were transported.  For a star import
        this is the expansion of ``__all__`` at transport time.

    morphism_kind : str
        String representation of the ``MorphismKind`` value that best
        describes the transport.  Typically ``"inclusion"`` for direct
        imports, ``"restriction"`` for selective (from … import …) imports,
        and ``"transport"`` for aliased imports.

    coordinate : object
        The ``Coordinate`` (or stub equivalent) representing the target module
        in the site.  Used when building judgments to identify the locus of
        the transport event.

    # copilot: this is the dual of ImportExecutionRecord — execution witness vs morphism record
    """

    source_module: str
    target_module: str
    transported_names: tuple
    morphism_kind: str
    coordinate: object

    def as_morphism(self) -> "Morphism":
        """
        Construct a ``Morphism`` site object from this transport result.

        The source coordinate is built from ``source_module`` and the target
        from ``target_module``.  The morphism kind is parsed from the string
        field ``morphism_kind``.

        # copilot: bridges the transport record to the jugeo geometry layer
        """
        src = Coordinate(components=(self.source_module,), kind=CoordinateKind.MODULE)
        tgt = Coordinate(components=(self.target_module,), kind=CoordinateKind.MODULE)
        try:
            mk = MorphismKind(self.morphism_kind)
        except ValueError:
            mk = MorphismKind.INCLUSION
        return Morphism(source=src, target=tgt, kind=mk, label=str(self.transported_names))


@dataclass(frozen=True, slots=True)
class ShadowedNameRecord:
    """
    Record of a name that is shadowed by an import in the same module.

    theory2.tex Ch19 §1 — Name shadowing in namespace transport.

    When an import statement introduces a name that already exists in the
    local namespace, the original binding is overwritten (shadowed).  This
    can cause subtle bugs, especially with star imports.  The shadowing record
    captures the origin modules of both the original and the shadowing
    definitions so that provenance can be reconstructed.

    Fields
    ------
    name : str
        The Python identifier that was shadowed.

    original_module : str
        Fully-qualified name of the module that originally defined ``name``
        in the importing namespace (may be ``"<builtins>"`` or ``"<local>"``
        for names that were defined locally rather than imported).

    shadowing_module : str
        Fully-qualified name of the module whose import caused the shadowing.
        For star imports this is the module that owns ``name`` in its
        ``__all__`` or public namespace.

    line_no : int
        Line number in the source file of the import statement that caused
        the shadowing.  Set to ``-1`` if the line number could not be
        determined (e.g., when the analysis is performed on a compiled
        ``.pyc`` without source).

    # copilot: shadowing detection is important for star-import safety analysis
    """

    name: str
    original_module: str
    shadowing_module: str
    line_no: int


@dataclass(frozen=True, slots=True)
class ExecutionWitnessRecord:
    """
    Witness that a module's body was executed (or retrieved from cache).

    theory2.tex Ch19 §1 — Execution witness in the judgment sense.

    The CPython import system caches module objects in ``sys.modules``.  After
    the first import of a module, subsequent ``import`` statements retrieve the
    cached object without re-executing the module body.  This record
    distinguishes between a *fresh execution* (module not in ``sys.modules``
    before the import) and a *cache retrieval* (module already present).

    Fields
    ------
    module_name : str
        Fully-qualified name of the module.

    sys_modules_key : str
        The key under which the module is stored in ``sys.modules``.  Usually
        identical to ``module_name`` but can differ for namespace packages or
        modules that manipulate ``sys.modules`` directly.

    load_time_ns : int
        Time in nanoseconds taken to complete the import (0 for cache hits).
        Measured using ``time.time_ns()`` bracketing the import call.

    frame_count : int
        Number of frames on the call stack at the moment the import was
        triggered.  Useful for detecting deeply-nested or circular imports.

    witness_level : int
        Encodes the trust level of this witness:
        1 = spec found by importlib (module exists but not yet loaded),
        2 = module loaded from cache (no re-execution),
        3 = module freshly executed (full execution witness),
        4 = module executed and all assertions passed (verified witness).

    # copilot: load_time_ns=0 means cache hit; load_time_ns>0 means fresh execution
    """

    module_name: str
    sys_modules_key: str
    load_time_ns: int
    frame_count: int
    witness_level: int

    @property
    def was_cache_hit(self) -> bool:
        """
        True if the module was retrieved from ``sys.modules`` without
        re-executing its body.

        A cache hit is identified by ``load_time_ns == 0`` OR by checking
        whether ``sys_modules_key in sys.modules`` was true before the import.
        This property uses only the recorded data (``load_time_ns``).

        # copilot: cache hits have witness_level=2 by convention in this module
        """
        return self.load_time_ns == 0 or self.witness_level == 2

    @property
    def trust_level(self) -> "TrustLevel":
        """
        Map ``witness_level`` to a ``TrustLevel`` enum value for use in
        jugeo judgment construction.

        Mapping:
        - witness_level 1 → TrustLevel.COPILOT_SUGGESTED
        - witness_level 2 → TrustLevel.ORACLE_PROPOSED
        - witness_level 3 → TrustLevel.RUNTIME_WITNESSED
        - witness_level 4 → TrustLevel.VERIFIED

        # copilot: aligns execution witness quality with jugeo's trust hierarchy
        """
        _map = {
            1: TrustLevel.COPILOT_SUGGESTED,
            2: TrustLevel.ORACLE_PROPOSED,
            3: TrustLevel.RUNTIME_WITNESSED,
            4: TrustLevel.VERIFIED,
        }
        return _map.get(self.witness_level, TrustLevel.COPILOT_SUGGESTED)


@dataclass(frozen=True, slots=True)
class NamespaceDeltaRecord:
    """
    Captures the change in a module's public namespace caused by an import.

    theory2.tex Ch19 §1 — Namespace delta as transport measurement.

    A namespace delta is the concrete, observable consequence of the
    "namespace transport" half of the import thesis.  By recording what
    names were added, removed, and changed (i.e., same name but different
    object identity) we obtain a precise accounting of what information
    flowed into the importing namespace.

    Fields
    ------
    module_name : str
        The module whose namespace was altered.  This is the *target* of
        the transport (the importer), not the source.

    added_names : frozenset[str]
        Names that appeared in the namespace after the import that were
        not present before.  These are the successfully transported names.

    removed_names : frozenset[str]
        Names that were present before the import but absent after.
        Non-empty only in unusual cases (e.g., a module body that deletes
        globals, or a ``from m import *`` that shadows then deletes a name).

    changed_names : frozenset[str]
        Names whose binding changed (different ``id()``) without the name
        being added or removed.  Indicates a *rebinding* — typically caused
        by a later ``from m import f`` overwriting a previously imported ``f``.

    delta_size : int
        Total number of name changes: ``len(added) + len(removed) + len(changed)``.
        A convenience field for quick filtering without recomputing set sizes.

    # copilot: delta_size > 0 is a necessary condition for any namespace transport having occurred
    """

    module_name: str
    added_names: frozenset
    removed_names: frozenset
    changed_names: frozenset
    delta_size: int

    @property
    def is_noop(self) -> bool:
        """
        True if this delta represents no observable change to the namespace.

        This can happen when an import is performed purely for its side effects
        (e.g., ``import logging`` when ``logging`` is already in the namespace
        under the same binding) or when ``import m`` is repeated and ``m`` was
        already bound.

        # copilot: noop deltas still represent execution events — the module body ran (or was cached)
        """
        return self.delta_size == 0

    @property
    def summary(self) -> str:
        """
        Human-readable one-liner summarising the delta for log output.

        # copilot: used by the coordinator's logging calls
        """
        return (
            f"NamespaceDelta({self.module_name!r}: "
            f"+{len(self.added_names)} -{len(self.removed_names)} ~{len(self.changed_names)})"
        )


# ===========================================================================
# §3 — Stateful coordinator and analyzer classes
# ===========================================================================

@dataclass
class ImportExecutionNamespaceTransportCoordinator:
    """
    Coordinates the analysis of import statements in a Python source file.

    theory2.tex Ch19 §1 — Central coordinator for import execution analysis.

    This class is the primary entry point for the module.  It accepts a path
    to a ``.py`` file, parses its AST, extracts all import statements, and
    produces a list of ``ImportExecutionRecord`` objects.  It also builds
    jugeo ``Judgment`` objects for each import, attaching execution evidence
    and namespace transport morphisms to the site.

    The coordinator maintains mutable state:
    - ``records``: accumulated ``ImportExecutionRecord`` objects from the
      most recent ``run()`` call.
    - ``judgments``: accumulated ``Judgment`` objects built from those records.
    - ``site_builder``: a ``SiteBuilder`` accumulating coordinates and morphisms.

    Usage
    -----
    >>> coord = ImportExecutionNamespaceTransportCoordinator()
    >>> records = coord.run("path/to/module.py")
    >>> judgments = [coord.build_execution_judgment(r) for r in records]

    # copilot: mutable because it accumulates state across calls to run()
    """

    records: list = field(default_factory=list)
    judgments: list = field(default_factory=list)
    site_builder: object = field(default_factory=SiteBuilder)

    # copilot: _source_path is set by run() and used by other methods for context
    _source_path: str = field(default="", repr=False)

    def analyze_import_statement(self, stmt: ast.stmt) -> ImportExecutionRecord:
        """
        Produce an ``ImportExecutionRecord`` from a single AST import node.

        Accepts either ``ast.Import`` or ``ast.ImportFrom`` nodes.  Extracts
        the module name(s), the imported names (if any), and the line number.
        Since this is static analysis (not live execution), ``execution_timestamp``
        is set to the current wall time, ``namespace_before`` and
        ``namespace_after`` are left as empty tuples, and ``execution_succeeded``
        is set to ``True`` (optimistic assumption — the analyzer has no way to
        know whether the import will succeed at runtime).

        Parameters
        ----------
        stmt : ast.stmt
            An ``ast.Import`` or ``ast.ImportFrom`` node extracted from the
            module's AST.  Passing other node types will raise ``TypeError``.

        Returns
        -------
        ImportExecutionRecord
            A fully-populated record.  ``imported_names`` is a sorted tuple of
            the names that will be introduced into the importing namespace.

        Raises
        ------
        TypeError
            If ``stmt`` is not an ``ast.Import`` or ``ast.ImportFrom`` node.

        # copilot: this is static analysis only — no actual import is executed here
        """
        if not isinstance(stmt, (ast.Import, ast.ImportFrom)):
            raise TypeError(
                f"Expected ast.Import or ast.ImportFrom, got {type(stmt).__name__}"
            )

        ts = time.time()

        if isinstance(stmt, ast.Import):
            # copilot: ast.Import has a list of aliases (name, asname pairs)
            module_name = stmt.names[0].name if stmt.names else "<unknown>"
            imported_names = tuple(
                sorted(
                    alias.asname if alias.asname else alias.name.split(".")[0]
                    for alias in stmt.names
                )
            )
        else:
            # copilot: ast.ImportFrom has module, names (aliases), level (relative dots)
            module_name = stmt.module or "<relative>"
            if stmt.names and stmt.names[0].name == "*":
                # star import — we record a sentinel
                imported_names = ("*",)
            else:
                imported_names = tuple(
                    sorted(
                        alias.asname if alias.asname else alias.name
                        for alias in stmt.names
                    )
                )

        log.debug(
            "analyze_import_statement: module=%r names=%r line=%d",
            module_name,
            imported_names,
            getattr(stmt, "lineno", -1),
        )

        return ImportExecutionRecord(
            module_name=module_name,
            imported_names=imported_names,
            execution_timestamp=ts,
            namespace_before=(),
            namespace_after=imported_names,  # optimistic: assume all names land
            execution_succeeded=True,
            error_message="",
        )

    def coordinate_namespace_transport(
        self,
        source_module: str,
        target_module: str,
        names: list[str],
    ) -> NamespaceTransportResult:
        """
        Build a ``NamespaceTransportResult`` representing the morphism from
        ``source_module`` to ``target_module`` transporting ``names``.

        This method also registers the corresponding coordinate and morphism
        objects with the internal ``SiteBuilder`` so that the accumulated site
        can later be retrieved for judgment construction.

        Parameters
        ----------
        source_module : str
            Fully-qualified name of the supplying module.
        target_module : str
            Fully-qualified name of the consuming (importing) module.
        names : list[str]
            Names being transported.  Pass ``["*"]`` for star imports.

        Returns
        -------
        NamespaceTransportResult
            Immutable record of the transport.

        # copilot: registers coords and morphisms in site_builder as a side effect
        """
        src_coord = Coordinate(
            components=(source_module,),
            kind=CoordinateKind.MODULE,
            support_labels=frozenset(names),
        )
        tgt_coord = Coordinate(
            components=(target_module,),
            kind=CoordinateKind.MODULE,
            support_labels=frozenset(),
        )
        morphism_kind = (
            MorphismKind.RESTRICTION.value
            if names and names != ["*"]
            else MorphismKind.INCLUSION.value
        )
        morph = Morphism(
            source=src_coord,
            target=tgt_coord,
            kind=MorphismKind(morphism_kind),
            label=f"transport:{','.join(names)}",
        )
        self.site_builder.add_coordinate(src_coord)
        self.site_builder.add_coordinate(tgt_coord)
        self.site_builder.add_morphism(morph)

        result = NamespaceTransportResult(
            source_module=source_module,
            target_module=target_module,
            transported_names=tuple(sorted(names)),
            morphism_kind=morphism_kind,
            coordinate=tgt_coord,
        )
        log.debug(
            "coordinate_namespace_transport: %r → %r (%d names)",
            source_module,
            target_module,
            len(names),
        )
        return result

    def build_execution_judgment(self, record: ImportExecutionRecord) -> Judgment:
        """
        Construct a jugeo ``Judgment`` from an ``ImportExecutionRecord``.

        The judgment's proposition states that the import of ``record.module_name``
        constitutes an execution event and namespace transport.  Evidence is
        attached from the record's fields.  The trust level is set to
        ``RUNTIME_WITNESSED`` if ``execution_succeeded`` is ``True``, otherwise
        ``COPILOT_SUGGESTED`` (static-analysis-only guess).

        Parameters
        ----------
        record : ImportExecutionRecord
            The execution record to lift into a judgment.

        Returns
        -------
        Judgment
            A fully-populated judgment object.  Appended to ``self.judgments``.

        # copilot: this bridges the import analysis layer to the jugeo judgment layer
        """
        prop = Proposition(
            kind=PropositionKind.STRUCTURAL,
            statement=(
                f"import of '{record.module_name}' is execution plus namespace transport "
                f"(transported: {sorted(record.transported_names)})"
            ),
            label=f"import::{record.module_name}",
        )
        coord = record.as_coordinate()
        carrier = Carrier(
            coordinate=coord,
            payload=record,
            label=f"execution_record::{record.module_name}",
        )
        trust_level = (
            TrustLevel.RUNTIME_WITNESSED
            if record.execution_succeeded
            else TrustLevel.COPILOT_SUGGESTED
        )
        trust = TrustAnnotation(
            level=trust_level,
            rationale=(
                "Execution succeeded with namespace transport"
                if record.execution_succeeded
                else f"Import failed: {record.error_message}"
            ),
        )
        evidence_item = EvidenceItem(
            kind=EvidenceItemKind.STATIC_ANALYSIS,
            payload={
                "module_name": record.module_name,
                "imported_names": record.imported_names,
                "transported_names": sorted(record.transported_names),
                "execution_succeeded": record.execution_succeeded,
            },
            label="import_execution_static_analysis",
        )
        bundle = EvidenceBundle()
        bundle.add(evidence_item)
        prov = Provenance(
            source=self._source_path,
            module=__name__,
            timestamp=str(record.execution_timestamp),
        )
        j = Judgment(
            status=JudgmentStatus.SETTLED if record.execution_succeeded else JudgmentStatus.OBSTRUCTED,
            proposition=prop,
            carrier=carrier,
            evidence=bundle,
            trust=trust,
            provenance=prov,
            label=f"judgment::import::{record.module_name}",
        )
        self.judgments.append(j)
        return j

    def run(self, module_path: str) -> list:
        """
        Parse a ``.py`` file and return ``ImportExecutionRecord`` objects for
        every import statement found at module level.

        Steps:
        1. Read ``module_path`` from disk.
        2. Parse with ``ast.parse``.
        3. Walk the top-level statements looking for ``ast.Import`` and
           ``ast.ImportFrom`` nodes.
        4. Call ``analyze_import_statement`` for each.
        5. Accumulate results into ``self.records``.

        Parameters
        ----------
        module_path : str
            Filesystem path to a ``.py`` source file.

        Returns
        -------
        list[ImportExecutionRecord]
            All records extracted from the file.  Also stored in ``self.records``.

        # copilot: only top-level imports are extracted; nested imports (inside functions) are skipped
        """
        self._source_path = module_path
        self.records.clear()

        log.info("ImportExecutionNamespaceTransportCoordinator.run: reading %r", module_path)

        try:
            with open(module_path, "r", encoding="utf-8") as fh:
                source = fh.read()
        except OSError as exc:
            log.error("run: cannot read %r: %s", module_path, exc)
            return []

        try:
            tree = ast.parse(source, filename=module_path)
        except SyntaxError as exc:
            log.error("run: syntax error in %r: %s", module_path, exc)
            return []

        for node in ast.iter_child_nodes(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                # copilot: extract top-level imports only
                record = self.analyze_import_statement(node)
                self.records.append(record)

        log.info(
            "run: found %d import statements in %r",
            len(self.records),
            module_path,
        )
        return list(self.records)


@dataclass
class ImportExecutionNamespaceTransportAnalyzer:
    """
    Static analyzer for import statements in Python source code.

    theory2.tex Ch19 §1 — Static analysis component of the import graph.

    While the coordinator focuses on producing judgment-ready records,
    this analyzer focuses on structural properties of the import graph:
    dependency graphs, shadowed name detection, and import classification.

    The analyzer is designed to be used on source strings (not live modules),
    making it suitable for offline analysis of large codebases.

    State
    -----
    _cache : dict
        Maps ``(source_hash, operation)`` pairs to results, avoiding redundant
        parsing of the same source.

    # copilot: stateless between different sources, but caches results within a session
    """

    _cache: dict = field(default_factory=dict)

    def extract_import_statements(self, source: str) -> list:
        """
        Parse ``source`` and return all AST import nodes, including those
        nested inside function bodies, class bodies, and try/except blocks.

        Parameters
        ----------
        source : str
            Python source code as a string.

        Returns
        -------
        list[ast.stmt]
            All ``ast.Import`` and ``ast.ImportFrom`` nodes found anywhere
            in the AST (uses ``ast.walk`` for full traversal).

        # copilot: ast.walk visits every node in DFS order — no depth limit
        """
        try:
            tree = ast.parse(source)
        except SyntaxError as exc:
            log.warning("extract_import_statements: syntax error: %s", exc)
            return []

        result = [
            node
            for node in ast.walk(tree)
            if isinstance(node, (ast.Import, ast.ImportFrom))
        ]
        log.debug("extract_import_statements: found %d import nodes", len(result))
        return result

    def classify_import(self, node: ast.stmt) -> ImportKind:
        """
        Classify a single import AST node into an ``ImportKind`` value.

        Classification rules:
        - ``ast.Import`` → ``ImportKind.ABSOLUTE``
        - ``ast.ImportFrom`` with ``level > 0`` → ``ImportKind.RELATIVE``
        - ``ast.ImportFrom`` with ``names[0].name == '*'`` → ``ImportKind.STAR``
        - ``ast.ImportFrom`` with ``level == 0`` → ``ImportKind.FROM``
        - Any import inside a ``Try`` node → ``ImportKind.CONDITIONAL``
          (this classification requires the parent context, which is set by
          the caller; this method returns the basic form classification).

        Parameters
        ----------
        node : ast.stmt
            An AST import node.

        Returns
        -------
        ImportKind
            The classification of the import form.

        # copilot: CONDITIONAL classification requires caller to check parent context
        """
        if isinstance(node, ast.Import):
            return ImportKind.ABSOLUTE
        if isinstance(node, ast.ImportFrom):
            if node.level and node.level > 0:
                return ImportKind.RELATIVE
            if node.names and node.names[0].name == "*":
                return ImportKind.STAR
            return ImportKind.FROM
        # copilot: fallback — should not be reached for well-formed ASTs
        return ImportKind.ABSOLUTE

    def build_dependency_graph(self, module_name: str) -> dict:
        """
        Build a module dependency graph rooted at ``module_name``.

        Uses ``importlib.util.find_spec`` to locate the source file for
        ``module_name``, reads it, extracts all import statements, and
        recursively processes each imported module (up to a maximum depth
        to prevent infinite recursion on circular imports).

        Parameters
        ----------
        module_name : str
            Fully-qualified module name, e.g., ``"jugeo.geometry.site"``.

        Returns
        -------
        dict[str, list[str]]
            Maps each discovered module name to the list of module names it
            directly imports.  Modules that could not be located are mapped
            to an empty list.

        # copilot: max_depth=3 prevents infinite recursion on circular import graphs
        """
        graph: dict = {}
        self._build_graph_recursive(module_name, graph, depth=0, max_depth=3)
        return graph

    def _build_graph_recursive(
        self,
        module_name: str,
        graph: dict,
        depth: int,
        max_depth: int,
    ) -> None:
        """
        Internal recursive helper for ``build_dependency_graph``.

        Mutates ``graph`` in-place.  Stops recursion when depth exceeds
        ``max_depth`` or when the module has already been processed.

        # copilot: guard against already-visited modules to prevent cycles
        """
        if module_name in graph or depth > max_depth:
            return

        graph[module_name] = []

        spec = importlib.util.find_spec(module_name)
        if spec is None or spec.origin is None:
            log.debug("_build_graph_recursive: no spec for %r", module_name)
            return

        try:
            with open(spec.origin, "r", encoding="utf-8") as fh:
                source = fh.read()
        except OSError:
            log.debug("_build_graph_recursive: cannot read %r", spec.origin)
            return

        stmts = self.extract_import_statements(source)
        for stmt in stmts:
            if isinstance(stmt, ast.ImportFrom) and stmt.module:
                dep = stmt.module
            elif isinstance(stmt, ast.Import) and stmt.names:
                dep = stmt.names[0].name
            else:
                continue
            graph[module_name].append(dep)
            self._build_graph_recursive(dep, graph, depth + 1, max_depth)

    def detect_shadowed_names(self, stmts: list) -> list:
        """
        Detect names that are shadowed by a later import in the same list.

        Iterates through ``stmts`` in order, maintaining a running dict of
        ``name → module`` bindings.  When a later import introduces a name
        that is already bound (from a prior import in the same module), a
        ``ShadowedNameRecord`` is emitted.

        Parameters
        ----------
        stmts : list[ast.stmt]
            A list of AST import nodes (as returned by
            ``extract_import_statements``).  Non-import nodes are silently
            skipped.

        Returns
        -------
        list[ShadowedNameRecord]
            One record per shadowing event.  Empty if no shadowing is detected.

        # copilot: order matters — earlier imports are shadowed by later ones
        """
        # Maps name → (module, lineno)
        seen: dict = {}
        shadows: list = []

        for stmt in stmts:
            if isinstance(stmt, ast.Import):
                for alias in stmt.names:
                    bound_name = alias.asname if alias.asname else alias.name.split(".")[0]
                    module = alias.name
                    lineno = getattr(stmt, "lineno", -1)
                    if bound_name in seen:
                        orig_module, _ = seen[bound_name]
                        shadows.append(
                            ShadowedNameRecord(
                                name=bound_name,
                                original_module=orig_module,
                                shadowing_module=module,
                                line_no=lineno,
                            )
                        )
                        log.debug(
                            "detect_shadowed_names: '%s' shadowed by %r at line %d",
                            bound_name,
                            module,
                            lineno,
                        )
                    seen[bound_name] = (module, lineno)

            elif isinstance(stmt, ast.ImportFrom):
                module = stmt.module or "<relative>"
                lineno = getattr(stmt, "lineno", -1)
                if stmt.names and stmt.names[0].name == "*":
                    # copilot: star imports may shadow anything; record conservatively
                    continue
                for alias in stmt.names:
                    bound_name = alias.asname if alias.asname else alias.name
                    if bound_name in seen:
                        orig_module, _ = seen[bound_name]
                        shadows.append(
                            ShadowedNameRecord(
                                name=bound_name,
                                original_module=orig_module,
                                shadowing_module=module,
                                line_no=lineno,
                            )
                        )
                    seen[bound_name] = (module, lineno)

        return shadows


@dataclass
class ImportExecutionNamespaceTransportWitness:
    """
    Runtime witness for import execution and namespace transport.

    theory2.tex Ch19 §1 — Runtime witnessing of import events.

    Where the coordinator and analyzer operate on source text, this class
    operates at runtime by actually invoking the import machinery and
    recording what happens.  It uses ``importlib.util.find_spec`` to check
    module availability, ``time.time_ns`` for high-resolution timing, and
    ``sys._getframe`` for frame-depth measurement.

    The witness class is the highest-trust analysis component in this
    module.  Its records carry ``TrustLevel.RUNTIME_WITNESSED`` or higher.

    State
    -----
    witnessed_modules : dict[str, ExecutionWitnessRecord]
        Maps module name → most recent ``ExecutionWitnessRecord``.

    witnessed_deltas : list[NamespaceDeltaRecord]
        Accumulated delta records from all ``record_namespace_delta`` calls.

    # copilot: this class performs actual imports — use with caution in production
    """

    witnessed_modules: dict = field(default_factory=dict)
    witnessed_deltas: list = field(default_factory=list)

    def witness_import_execution(self, module_name: str) -> "ExecutionWitnessRecord":
        """
        Witness the import of ``module_name`` using ``importlib.util.find_spec``
        and, if not already cached, ``importlib.import_module``.

        Steps:
        1. Check whether ``module_name`` is already in ``sys.modules``.
        2. Record ``time.time_ns()`` before and after.
        3. Use ``find_spec`` to verify the module exists without loading it.
        4. If not in cache: call ``importlib.import_module``.
        5. Record frame count at the call site.

        Parameters
        ----------
        module_name : str
            Fully-qualified module name to witness.

        Returns
        -------
        ExecutionWitnessRecord
            Populated record.  Also stored in ``self.witnessed_modules``.

        # copilot: importlib.import_module runs the module body if not cached
        """
        already_loaded = module_name in sys.modules
        frame_count = 0
        try:
            frame = sys._getframe(0)
            while frame is not None:
                frame_count += 1
                frame = frame.f_back
        except AttributeError:
            pass

        spec = importlib.util.find_spec(module_name)
        if spec is None:
            # Module doesn't exist — witness level 0 (not found)
            record = ExecutionWitnessRecord(
                module_name=module_name,
                sys_modules_key=module_name,
                load_time_ns=0,
                frame_count=frame_count,
                witness_level=1,
            )
            self.witnessed_modules[module_name] = record
            log.warning("witness_import_execution: spec not found for %r", module_name)
            return record

        if already_loaded:
            # Cache hit — no re-execution
            record = ExecutionWitnessRecord(
                module_name=module_name,
                sys_modules_key=module_name,
                load_time_ns=0,
                frame_count=frame_count,
                witness_level=2,
            )
        else:
            # Fresh import — measure execution time
            t0 = time.time_ns()
            try:
                importlib.import_module(module_name)
                load_time_ns = time.time_ns() - t0
                witness_level = 3
                log.info(
                    "witness_import_execution: loaded %r in %d ns",
                    module_name,
                    load_time_ns,
                )
            except Exception as exc:
                load_time_ns = time.time_ns() - t0
                witness_level = 1
                log.error(
                    "witness_import_execution: failed to import %r: %s",
                    module_name,
                    exc,
                )
            record = ExecutionWitnessRecord(
                module_name=module_name,
                sys_modules_key=module_name,
                load_time_ns=load_time_ns,
                frame_count=frame_count,
                witness_level=witness_level,
            )

        self.witnessed_modules[module_name] = record
        return record

    def record_namespace_delta(
        self,
        before: dict,
        after: dict,
        module_name: str,
    ) -> NamespaceDeltaRecord:
        """
        Compute the namespace delta between two snapshots of a module's globals.

        Parameters
        ----------
        before : dict
            Snapshot of the module's namespace (e.g., ``dict(globals())``)
            taken immediately before executing an import statement.

        after : dict
            Snapshot taken immediately after.

        module_name : str
            Name of the module being analyzed (used as the record's label).

        Returns
        -------
        NamespaceDeltaRecord
            The computed delta.  Also appended to ``self.witnessed_deltas``.

        # copilot: snapshots must be full copies of globals() — not references to the live dict
        """
        before_keys = frozenset(before.keys())
        after_keys = frozenset(after.keys())

        added = after_keys - before_keys
        removed = before_keys - after_keys
        shared = before_keys & after_keys

        # copilot: detect rebindings — same key, different object id
        changed = frozenset(
            k for k in shared if id(before[k]) != id(after[k])
        )

        delta_size = len(added) + len(removed) + len(changed)

        record = NamespaceDeltaRecord(
            module_name=module_name,
            added_names=added,
            removed_names=removed,
            changed_names=changed,
            delta_size=delta_size,
        )
        self.witnessed_deltas.append(record)
        log.debug("record_namespace_delta: %s", record.summary)
        return record

    def build_witness_judgment(self, record: ExecutionWitnessRecord) -> Judgment:
        """
        Construct a jugeo ``Judgment`` from an ``ExecutionWitnessRecord``.

        The proposition states that the module was executed (or retrieved from
        cache) with the recorded timing and frame depth.  The trust level
        corresponds to the ``witness_level`` in the record.

        Parameters
        ----------
        record : ExecutionWitnessRecord
            The witness record to lift into a judgment.

        Returns
        -------
        Judgment
            A fully-populated judgment.

        # copilot: witness judgments carry higher trust than static-analysis judgments
        """
        execution_mode = "cached" if record.was_cache_hit else f"executed in {record.load_time_ns}ns"
        prop = Proposition(
            kind=PropositionKind.BEHAVIORAL,
            statement=(
                f"module '{record.module_name}' import was {execution_mode}, "
                f"witnessed at frame depth {record.frame_count}"
            ),
            label=f"witness::{record.module_name}",
        )
        coord = Coordinate(
            components=(record.module_name,),
            kind=CoordinateKind.MODULE,
            support_labels=frozenset({record.sys_modules_key}),
        )
        carrier = Carrier(
            coordinate=coord,
            payload=record,
            label=f"witness_record::{record.module_name}",
        )
        trust = TrustAnnotation(
            level=record.trust_level,
            rationale=(
                f"Runtime witness at level {record.witness_level}: {execution_mode}"
            ),
        )
        evidence_item = EvidenceItem(
            kind=EvidenceItemKind.RUNTIME_TRACE,
            payload={
                "module_name": record.module_name,
                "load_time_ns": record.load_time_ns,
                "frame_count": record.frame_count,
                "witness_level": record.witness_level,
                "was_cache_hit": record.was_cache_hit,
            },
            label="runtime_witness",
        )
        bundle = EvidenceBundle()
        bundle.add(evidence_item)
        prov = Provenance(
            source=__file__,
            module=__name__,
            timestamp=str(time.time()),
        )
        status = (
            JudgmentStatus.SETTLED
            if record.witness_level >= 2
            else JudgmentStatus.OPEN
        )
        return Judgment(
            status=status,
            proposition=prop,
            carrier=carrier,
            evidence=bundle,
            trust=trust,
            provenance=prov,
            label=f"judgment::witness::{record.module_name}",
        )


# ===========================================================================
# §4 — Module-level convenience functions
# ===========================================================================

def analyze_file(path: str) -> tuple:
    """
    Convenience function: parse a file and return (records, judgments).

    Creates a fresh ``ImportExecutionNamespaceTransportCoordinator``, runs it
    on ``path``, and builds a judgment for every record.

    Parameters
    ----------
    path : str
        Filesystem path to a Python source file.

    Returns
    -------
    tuple[list[ImportExecutionRecord], list[Judgment]]
        All records and their corresponding judgments.

    # copilot: shorthand for one-off analysis without managing coordinator state
    """
    coord = ImportExecutionNamespaceTransportCoordinator()
    records = coord.run(path)
    judgments = [coord.build_execution_judgment(r) for r in records]
    return records, judgments


def classify_source_imports(source: str) -> dict:
    """
    Classify all import statements in ``source`` and return a dict mapping
    each ``ImportKind`` to the list of module names imported with that form.

    Parameters
    ----------
    source : str
        Python source code string.

    Returns
    -------
    dict[ImportKind, list[str]]
        Classification result.

    # copilot: useful for quick auditing of import forms in a module
    """
    analyzer = ImportExecutionNamespaceTransportAnalyzer()
    stmts = analyzer.extract_import_statements(source)
    result: dict = {kind: [] for kind in ImportKind}
    for stmt in stmts:
        kind = analyzer.classify_import(stmt)
        if isinstance(stmt, ast.ImportFrom):
            name = stmt.module or "<relative>"
        else:
            name = stmt.names[0].name if stmt.names else "<unknown>"
        result[kind].append(name)
    return result


# ===========================================================================
# §5 — Smoke test
# ===========================================================================

if __name__ == "__main__":
    """
    Smoke test for theory2.tex Ch19 §1 — Import is execution plus namespace transport.

    Exercises all three major classes and the two convenience functions.
    Prints a summary of findings to stdout.

    # copilot: run with `python -m jugeo.python_runtime.import_graph....` or directly
    """
    import os

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

    print("=" * 70)
    print("Smoke test: Import is execution plus namespace transport")
    print("theory2.tex Ch19 §1")
    print("=" * 70)

    # -------------------------------------------------------------------
    # 1. Coordinator: analyze this file itself
    # -------------------------------------------------------------------
    print("\n--- 1. ImportExecutionNamespaceTransportCoordinator ---")
    coord = ImportExecutionNamespaceTransportCoordinator()
    this_file = os.path.abspath(__file__)
    records = coord.run(this_file)
    print(f"  Found {len(records)} import statements in {os.path.basename(this_file)!r}")
    for r in records[:5]:
        print(f"    module={r.module_name!r}  names={r.imported_names}  ok={r.execution_succeeded}")
    if len(records) > 5:
        print(f"    ... and {len(records) - 5} more")

    # -------------------------------------------------------------------
    # 2. Coordinator: namespace transport coordination
    # -------------------------------------------------------------------
    transport_result = coord.coordinate_namespace_transport(
        source_module="os.path",
        target_module=__name__,
        names=["join", "exists", "abspath"],
    )
    print(f"\n  Transport result: {transport_result.source_module} → {transport_result.target_module}")
    print(f"  Transported names: {transport_result.transported_names}")
    print(f"  Morphism kind: {transport_result.morphism_kind}")

    # -------------------------------------------------------------------
    # 3. Coordinator: build judgment for first record
    # -------------------------------------------------------------------
    if records:
        j = coord.build_execution_judgment(records[0])
        print(f"\n  Judgment for first import: status={j.status}  trust={j.trust.level}")
        print(f"  Proposition: {j.proposition.statement[:80]}...")

    # -------------------------------------------------------------------
    # 4. Analyzer: extract, classify, detect shadows
    # -------------------------------------------------------------------
    print("\n--- 2. ImportExecutionNamespaceTransportAnalyzer ---")
    analyzer = ImportExecutionNamespaceTransportAnalyzer()
    sample_source = """
import os
import sys
from collections import OrderedDict
from os.path import join
from . import sibling
from typing import *
from os import path
from collections import OrderedDict as OD
"""
    stmts = analyzer.extract_import_statements(sample_source)
    print(f"  Extracted {len(stmts)} import statements from sample source")

    classifications = {}
    for s in stmts:
        k = analyzer.classify_import(s)
        classifications[k] = classifications.get(k, 0) + 1
    for kind, count in sorted(classifications.items(), key=lambda x: x[0].value):
        print(f"    {kind.value}: {count}")

    shadows = analyzer.detect_shadowed_names(stmts)
    if shadows:
        print(f"  Detected {len(shadows)} shadowed name(s):")
        for sh in shadows:
            print(f"    '{sh.name}' shadowed by {sh.shadowing_module!r} at line {sh.line_no}")
    else:
        print("  No shadowed names detected in sample source")

    # -------------------------------------------------------------------
    # 5. Witness: witness stdlib modules
    # -------------------------------------------------------------------
    print("\n--- 3. ImportExecutionNamespaceTransportWitness ---")
    witness = ImportExecutionNamespaceTransportWitness()
    test_modules = ["os", "sys", "collections", "pathlib", "jugeo.geometry.site"]
    for mod_name in test_modules:
        rec = witness.witness_import_execution(mod_name)
        status = "CACHED" if rec.was_cache_hit else f"LOADED in {rec.load_time_ns}ns"
        print(f"  {mod_name!r}: {status} (witness_level={rec.witness_level})")

    # -------------------------------------------------------------------
    # 6. Witness: namespace delta
    # -------------------------------------------------------------------
    print("\n--- 4. Namespace delta recording ---")
    before_ns: dict = {"x": 1, "y": 2, "z": 3}
    after_ns: dict = {"x": 1, "y": 99, "w": 4}  # y changed, z removed, w added
    delta = witness.record_namespace_delta(before_ns, after_ns, "smoke_test_module")
    print(f"  {delta.summary}")
    print(f"  added={sorted(delta.added_names)}  removed={sorted(delta.removed_names)}  changed={sorted(delta.changed_names)}")

    # -------------------------------------------------------------------
    # 7. Witness: build witness judgment
    # -------------------------------------------------------------------
    if witness.witnessed_modules:
        first_mod = next(iter(witness.witnessed_modules))
        wj = witness.build_witness_judgment(witness.witnessed_modules[first_mod])
        print(f"\n  Witness judgment for {first_mod!r}: status={wj.status}  trust={wj.trust.level}")
        print(f"  Proposition: {wj.proposition.statement[:80]}...")

    # -------------------------------------------------------------------
    # 8. Convenience functions
    # -------------------------------------------------------------------
    print("\n--- 5. Convenience functions ---")
    recs2, jdgs2 = analyze_file(this_file)
    print(f"  analyze_file: {len(recs2)} records, {len(jdgs2)} judgments")

    classifications2 = classify_source_imports(sample_source)
    print("  classify_source_imports results:")
    for kind, names in classifications2.items():
        if names:
            print(f"    {kind.value}: {names}")

    print("\n" + "=" * 70)
    print("Smoke test PASSED")
    print("=" * 70)
