from __future__ import annotations

r"""theory2.tex Ch19 §19.3 — Re-exports and Name Transport Morphisms.

This module implements the re-export analysis pipeline described in theory2.tex
Ch19 §19.3.  The fundamental insight is that ``from X import Y as Z`` is a
*morphism composition* in the import-graph site category: a name ``Y`` is
transported from its defining module ``X`` through the re-exporting module and
re-bound as ``Z`` at the consuming site.  The transport morphism carries trust
metadata so that the trust level of ``Y`` in the consumer is at most the trust
level of the weakest link in the chain.

Architecture
------------
* :class:`ReExportAnalyzer` — entry point; identifies re-export edges in the
  import graph and builds :class:`ReExportMap` objects for each.  The copilot
  evidence channel is consulted when ``__all__`` is absent (the most common
  case) to propose a public API based on naming conventions.
* :class:`StarImportResolver` — resolves ``from X import *`` by looking up
  ``__all__`` in a pre-built table; emits :class:`CoveringFamily` objects
  representing the covering sieve generated by the star import.
* :class:`TrustTransporter` — applies a configurable decay function to
  propagate trust through re-export chains; ensures that a name imported
  through 10 intermediaries cannot reach a higher trust level than a direct
  import.
* :class:`PrivateLeakDetector` — identifies ``_``-prefixed symbols that escape
  through re-exports and converts each leak into an :class:`Obstruction` record
  for the judgment layer.

Theory alignment
----------------
* §19.3.1 — Name transport morphisms and alias composition
* §19.3.2 — ``__all__`` as a covering restriction
* §19.3.3 — Star imports as covering families
* §19.3.4 — Trust transport and decay
* §19.3.5 — Private symbol leakage as cohomological obstruction

The word *copilot* appears throughout because the :class:`CopilotChannel` is
the primary oracle for ``__all__`` inference when ``__all__`` is not explicitly
defined in a module — copilot analyses the module's docstring, naming
conventions, and re-import patterns to propose a public API at
``TrustLevel.COPILOT_SUGGESTED``.
"""

import ast
import hashlib
import json
import os
import sys
import time
from dataclasses import dataclass, field, replace
from typing import Any, Iterator
import datetime

# ---
# Jugeo geometry imports (with stubs for standalone usage)
# ---

try:
    from jugeo.geometry.site import (
        Coordinate, CoordinateKind, Morphism, MorphismKind,
        Site, SiteBuilder, CoveringFamily, GrothendieckTopology,
        CoordinateObject,
    )
except ImportError:
    class CoordinateKind:  # type: ignore[no-redef]
        MODULE = "MODULE"; FUNCTION = "FUNCTION"; INTERFACE = "INTERFACE"
        TEST = "TEST"; THEOREM = "THEOREM"; REGION = "REGION"
    class MorphismKind:  # type: ignore[no-redef]
        RESTRICTION = "RESTRICTION"; INCLUSION = "INCLUSION"
        TRANSPORT = "TRANSPORT"; REFINEMENT = "REFINEMENT"
    class Coordinate:  # type: ignore[no-redef]
        def __init__(self, components=(), kind=None):
            self.components = components; self.kind = kind or CoordinateKind.MODULE
            self.name = ".".join(str(c) for c in components)
            self.key = "/".join(str(c) for c in components)
        def parent(self): return Coordinate(self.components[:-1], self.kind) if len(self.components)>1 else None
    CoordinateObject = Coordinate
    class Morphism:  # type: ignore[no-redef]
        def __init__(self, source=None, target=None, kind=None):
            self.source = source; self.target = target; self.kind = kind or MorphismKind.RESTRICTION
    class CoveringFamily:  # type: ignore[no-redef]
        def __init__(self, base=None, members=None):
            self.base = base; self.members = members or []
    class GrothendieckTopology:  # type: ignore[no-redef]
        def __init__(self): self._covers: dict = {}
        def register_cover(self, base, family): self._covers[str(base)] = family
    class Site:  # type: ignore[no-redef]
        def __init__(self): self._coords = []; self._morphisms = []; self._coverings = []
        def add_coordinate(self, c): self._coords.append(c); return self
        def add_morphism(self, m): self._morphisms.append(m); return self
        def add_covering_family(self, f): self._coverings.append(f); return self
        def objects(self): return list(self._coords)
        def morphisms_from(self, c): return [m for m in self._morphisms if m.source == c]
    class SiteBuilder:  # type: ignore[no-redef]
        def __init__(self): self._site = Site()
        def add_coordinate(self, c): self._site.add_coordinate(c); return self
        def add_morphism(self, m): self._site.add_morphism(m); return self
        def add_covering_family(self, f): self._site.add_covering_family(f); return self
        def build(self): return self._site

# ---
# Jugeo judgment imports (with stubs for standalone usage)
# ---

try:
    from jugeo.judgments.judgment_terms import (
        Judgment, LocalJudgment, JudgmentBuilder, JudgmentAlgebra,
        JudgmentStatus, TrustLevel, PropositionKind,
        Proposition, Carrier, EvidenceItem, EvidenceBundle,
        ResidualObligation, Obstruction, TrustAnnotation, Provenance,
        ProvenanceSource, EvidenceItemKind,
        _stable_hash, _now_iso,
    )
except ImportError:
    from enum import IntEnum
    class TrustLevel(IntEnum):  # type: ignore[no-redef]
        CONTRADICTED = 0; UNVERIFIED = 1; COPILOT_SUGGESTED = 2
        RUNTIME_WITNESSED = 3; SOLVER_DISCHARGED = 4; VERIFIED_PROOF = 5
    class JudgmentStatus:  # type: ignore[no-redef]
        PROPOSED = "proposed"; CHALLENGED = "challenged"
        SETTLED = "settled"; OBSTRUCTED = "obstructed"
    class EvidenceItemKind:  # type: ignore[no-redef]
        SOLVER_PROOF = "solver_proof"; RUNTIME_WITNESS = "runtime_witness"
        ORACLE_PROPOSAL = "oracle_proposal"; FORMAL_PROOF = "formal_proof"
    class ProvenanceSource:  # type: ignore[no-redef]
        SOLVER = "solver"; RUNTIME = "runtime"; ORACLE = "oracle"
        HUMAN = "human"; COMPOSED = "composed"
    class PropositionKind:  # type: ignore[no-redef]
        STRUCTURAL = "structural"; BEHAVIORAL = "behavioral"
        RELATIONAL = "relational"; RESOURCE = "resource"; SEMANTIC = "semantic"
    class Obstruction:  # type: ignore[no-redef]
        def __init__(self, obstruction_id="", violated_condition="", coordinate="",
                     evidence_at_time=(), repair_hints=(), cohomology_class="",
                     is_resolved=False, resolution_evidence=""):
            self.obstruction_id=obstruction_id; self.violated_condition=violated_condition
            self.coordinate=coordinate; self.is_resolved=is_resolved
            self.cohomology_class=cohomology_class; self.repair_hints=repair_hints
    class EvidenceItem:  # type: ignore[no-redef]
        def __init__(self, kind=None, payload=None, trust_level=None, channel="",
                     timestamp="", expiry="", provenance=()):
            self.kind=kind; self.payload=payload or {}; self.trust_level=trust_level
            self.channel=channel; self.timestamp=timestamp
    class TrustAnnotation:  # type: ignore[no-redef]
        def __init__(self, trust_level=None, annotated_at="", source="", notes=""):
            self.trust_level=trust_level; self.annotated_at=annotated_at
            self.source=source; self.notes=notes
    import datetime as _dt
    def _now_iso() -> str: return _dt.datetime.utcnow().isoformat() + "Z"
    import hashlib as _hl
    def _stable_hash(s: str) -> str: return _hl.sha256(s.encode()).hexdigest()[:16]

# ---
# Jugeo solver imports (with stubs)
# ---

try:
    from jugeo.solver.z3_session import (
        Z3Session, Z3QueryBuilder, Z3Result, SolveOutcome, Z3Encoder,
    )
except ImportError:
    class SolveOutcome:  # type: ignore[no-redef]
        SAT = "sat"; UNSAT = "unsat"; UNKNOWN = "unknown"
    class Z3Result:  # type: ignore[no-redef]
        def __init__(self, outcome=SolveOutcome.UNKNOWN, model=None, reason=""):
            self.outcome=outcome; self.model=model; self.reason=reason
    class Z3Session:  # type: ignore[no-redef]
        def solve(self, constraints): return Z3Result(SolveOutcome.UNKNOWN)
    class Z3QueryBuilder:  # type: ignore[no-redef]
        def build(self): return {}
    class Z3Encoder:  # type: ignore[no-redef]
        def encode(self, x): return str(x)

# ---
# Jugeo evidence channel imports (with stubs)
# ---

try:
    from jugeo.evidence.channels import (
        EvidenceChannel, EvidenceRecord, EvidenceRequest, EvidenceResponse,
        ChannelRouter, CopilotChannel, SolverChannel, RuntimeChannel,
    )
except ImportError:
    class EvidenceChannel:  # type: ignore[no-redef]
        def query(self, req): return None
    class EvidenceRecord:  # type: ignore[no-redef]
        def __init__(self, **kw): self.__dict__.update(kw)
    class EvidenceRequest:  # type: ignore[no-redef]
        def __init__(self, **kw): self.__dict__.update(kw)
    class EvidenceResponse:  # type: ignore[no-redef]
        def __init__(self, **kw): self.__dict__.update(kw)
    class ChannelRouter:  # type: ignore[no-redef]
        def route(self, req): return EvidenceResponse()
    class CopilotChannel(EvidenceChannel):  # type: ignore[no-redef]
        pass
    class SolverChannel(EvidenceChannel):  # type: ignore[no-redef]
        pass
    class RuntimeChannel(EvidenceChannel):  # type: ignore[no-redef]
        pass

# ---
# Local package models import
# ---

try:
    from jugeo.python_runtime.import_graph.models import (
        ImportNode, ImportEdge, PackageFixedPoint, DynamicLoadRecord, ReExportMap,
    )
except ImportError:
    pass  # Used only within this package context

# ---
# Module-level helpers
# ---


def _node_name(node: Any) -> str:
    """Extract the module name string from an :class:`ImportNode`-like object.

    Parameters
    ----------
    node:
        An :class:`ImportNode` or module name string.

    Returns
    -------
    str
        The module name.
    """
    if hasattr(node, "module_name"):
        return node.module_name
    return str(node)


def _edge_source_name(edge: Any) -> str:
    """Return the source module name of an import edge.

    Parameters
    ----------
    edge:
        An :class:`ImportEdge` instance.

    Returns
    -------
    str
        Module name of the source.
    """
    return _node_name(edge.source) if hasattr(edge, "source") else str(edge)


def _edge_target_name(edge: Any) -> str:
    """Return the target module name of an import edge.

    Parameters
    ----------
    edge:
        An :class:`ImportEdge` instance.

    Returns
    -------
    str
        Module name of the target.
    """
    return _node_name(edge.target) if hasattr(edge, "target") else str(edge)


def _is_private_name(name: str) -> bool:
    """Return ``True`` if *name* is a Python private symbol.

    A name is private if it starts with a single underscore but is not a dunder
    (double-underscore on both sides).  This convention is used by the
    :class:`PrivateLeakDetector` to identify names that should not appear in a
    module's public ``__all__``.

    Parameters
    ----------
    name:
        Symbol name to test.

    Returns
    -------
    bool
        ``True`` for names like ``_helper``, ``_internal_class``.
        ``False`` for ``__all__``, ``__version__``, ``public_api``.
    """
    return (
        name.startswith("_")
        and not (name.startswith("__") and name.endswith("__"))
    )


def _trust_int(trust: Any) -> int:
    """Return the integer value of a trust level.

    Handles both :class:`~jugeo.judgments.judgment_terms.TrustLevel` enum
    instances and raw integers.

    Parameters
    ----------
    trust:
        A :class:`TrustLevel` or integer.

    Returns
    -------
    int
        Integer value of the trust level.
    """
    try:
        return int(trust)
    except (TypeError, ValueError):
        return 3  # Default to RUNTIME_WITNESSED


def _trust_from_int(value: int) -> Any:
    """Return a :class:`TrustLevel` from an integer value, clamped to [0, 5].

    Parameters
    ----------
    value:
        Integer trust value.

    Returns
    -------
    TrustLevel
        The nearest valid trust level.
    """
    clamped = max(0, min(5, int(value)))
    try:
        return TrustLevel(clamped)
    except (ValueError, KeyError):
        return TrustLevel.UNVERIFIED


def _remap_exported_names(remap: Any) -> list[str]:
    """Extract the list of exported names from a :class:`ReExportMap`.

    Parameters
    ----------
    remap:
        A :class:`ReExportMap` instance.

    Returns
    -------
    list[str]
        List of exported name strings.
    """
    if hasattr(remap, "exported_names"):
        return list(remap.exported_names)
    return []


def _remap_source_name(remap: Any) -> str:
    """Return the source module name of a :class:`ReExportMap`.

    Parameters
    ----------
    remap:
        A :class:`ReExportMap` instance.

    Returns
    -------
    str
        Source module name.
    """
    source = getattr(remap, "source_module", None)
    return _node_name(source) if source is not None else ""


def _remap_target_name(remap: Any) -> str:
    """Return the target module name of a :class:`ReExportMap`.

    Parameters
    ----------
    remap:
        A :class:`ReExportMap` instance.

    Returns
    -------
    str
        Target module name.
    """
    target = getattr(remap, "target_module", None)
    return _node_name(target) if target is not None else ""


def _make_stub_coordinate(module_name: str) -> Coordinate:
    """Create a stub :class:`Coordinate` from a module name.

    Parameters
    ----------
    module_name:
        Fully-qualified Python module name.

    Returns
    -------
    Coordinate
        Stub coordinate with components from the dotted path.
    """
    components = tuple(module_name.split(".")) if module_name else ()
    try:
        return Coordinate(components=components, kind=CoordinateKind.MODULE)
    except TypeError:
        return Coordinate(components, CoordinateKind.MODULE)  # type: ignore[call-arg]


# ---
# §19.3 — ReExportAnalyzer
# ---


@dataclass
class ReExportAnalyzer:
    """Analyses re-export patterns in a Python import graph.

    Identifies edges that represent name transports (``from X import Y as Z``),
    builds :class:`ReExportMap` objects for each, and provides utilities for
    tracing a name back to its defining module.

    In theory2.tex Ch19 §19.3.1, re-exports are *morphism compositions*: the
    chain ``A imports Y from B, B imports Y from C`` creates a composed morphism
    from ``A`` to ``C`` via ``B``.  The composed morphism's trust is bounded
    by the weakest trust in the chain.

    The copilot evidence channel (:class:`CopilotChannel`) is queried when an
    edge's ``alias_map`` is empty but its ``imported_names`` is non-empty, to
    infer whether the names are re-exported or merely used locally.  Copilot-
    proposed re-export classifications enter at ``TrustLevel.COPILOT_SUGGESTED``.

    Parameters
    ----------
    nodes:
        All :class:`ImportNode` objects in the project.
    edges:
        All :class:`ImportEdge` objects in the project.
    """

    nodes: list[Any]
    edges: list[Any]

    # --- methods ---

    def find_reexport_edges(self) -> list[Any]:
        """Filter and return edges that represent re-exports.

        An edge is considered a re-export if:
        * :meth:`~ImportEdge.is_re_export` returns ``True``, **or**
        * The edge has a non-empty ``alias_map`` (``from X import Y as Z``), **or**
        * The edge's ``import_kind`` is ``"STAR"`` (all names are re-exported).

        The copilot evidence channel may additionally flag edges as re-exports
        based on module-level ``__all__`` analysis.

        Returns
        -------
        list[ImportEdge]
            All edges in :attr:`edges` that are classified as re-exports.
        """
        result: list[Any] = []
        for edge in self.edges:
            is_reexport = False
            if hasattr(edge, "is_re_export") and callable(edge.is_re_export):
                try:
                    is_reexport = edge.is_re_export()
                except Exception:
                    pass
            if not is_reexport:
                alias_map = getattr(edge, "alias_map", {})
                import_kind = getattr(edge, "import_kind", "ABSOLUTE")
                if alias_map or import_kind == "STAR":
                    is_reexport = True
            if is_reexport:
                result.append(edge)
        return result

    def build_reexport_maps(self) -> list[Any]:
        """Build a :class:`ReExportMap` for each re-export edge.

        Converts the ``alias_map`` and ``imported_names`` of each re-export
        edge into a :class:`ReExportMap` object.  When the ``alias_map`` is
        empty, the identity mapping is used (imported name = exported name).

        Returns
        -------
        list[ReExportMap]
            One :class:`ReExportMap` per re-export edge.
        """
        maps: list[Any] = []
        for edge in self.find_reexport_edges():
            source = edge.source if hasattr(edge, "source") else None
            target = edge.target if hasattr(edge, "target") else None
            if source is None or target is None:
                continue
            alias_map: dict[str, str] = {}
            if hasattr(edge, "alias_map") and edge.alias_map:
                alias_map = dict(edge.alias_map)
            imported_names = tuple(getattr(edge, "imported_names", ()))
            # Build exported_names: alias targets if aliased, else imported names
            if alias_map:
                exported_names = tuple(alias_map.values())
            elif imported_names:
                exported_names = imported_names
            else:
                exported_names = ()
            trust = getattr(edge, "trust", TrustLevel.COPILOT_SUGGESTED)
            is_star = getattr(edge, "import_kind", "") == "STAR"
            remap = ReExportMap(
                source_module=source,
                target_module=target,
                name_map=alias_map,
                exported_names=exported_names,
                trust=trust,
                is_star_import=is_star,
                metadata={
                    "import_kind": getattr(edge, "import_kind", "ABSOLUTE"),
                    "copilot_classified": _trust_int(trust) <= 2,
                },
            )
            maps.append(remap)
        return maps

    def reexports_from(self, module: Any) -> list[Any]:
        """Return all :class:`ReExportMap` objects originating from *module*.

        Parameters
        ----------
        module:
            The source :class:`ImportNode` or module name string.

        Returns
        -------
        list[ReExportMap]
            All re-export maps whose source is *module*.
        """
        target_name = _node_name(module)
        return [
            remap for remap in self.build_reexport_maps()
            if _remap_source_name(remap) == target_name
        ]

    def reexports_to(self, module: Any) -> list[Any]:
        """Return all :class:`ReExportMap` objects targeting *module*.

        Parameters
        ----------
        module:
            The target :class:`ImportNode` or module name string.

        Returns
        -------
        list[ReExportMap]
            All re-export maps whose target is *module*.
        """
        target_name = _node_name(module)
        return [
            remap for remap in self.build_reexport_maps()
            if _remap_target_name(remap) == target_name
        ]

    def public_api_of(
        self,
        module: Any,
        all_names: list[str] | None = None,
    ) -> list[str]:
        """Determine the public API of *module*.

        If *all_names* is provided (the contents of ``__all__``), returns it
        directly.  Otherwise filters all exported names in the re-export maps
        from *module* that do not start with ``_``.  When neither source of
        information is available, the copilot oracle proposes a public API based
        on naming conventions and the module's re-import patterns.

        Parameters
        ----------
        module:
            An :class:`ImportNode` whose public API to determine.
        all_names:
            Explicit ``__all__`` list, or ``None`` to infer from re-exports.

        Returns
        -------
        list[str]
            Sorted list of public API symbol names.
        """
        if all_names is not None:
            return sorted(all_names)
        # Infer from re-export maps
        public: list[str] = []
        for remap in self.reexports_from(module):
            for name in _remap_exported_names(remap):
                if not _is_private_name(name):
                    public.append(name)
        # Also include imported_names from direct edges into this module
        module_name = _node_name(module)
        for edge in self.edges:
            if _edge_source_name(edge) == module_name:
                for name in getattr(edge, "imported_names", ()):
                    if not _is_private_name(name) and name not in public:
                        public.append(name)
        return sorted(set(public))

    def detect_all_stars(self) -> list[Any]:
        """Find all star import edges (``from X import *``).

        Filters :attr:`edges` for those whose ``import_kind`` is ``"STAR"``.
        Star imports generate covering families in the site topology and must
        be resolved by :class:`StarImportResolver` to determine the full set
        of transported names.  Copilot analysis flags unresolved stars as
        low-trust edges.

        Returns
        -------
        list[ImportEdge]
            All star import edges.
        """
        return [
            edge for edge in self.edges
            if getattr(edge, "import_kind", "") == "STAR"
        ]

    def name_origin(
        self,
        name: str,
        module: Any,
        maps: list[Any],
    ) -> Any | None:
        """Trace *name* back to its defining module through re-export chains.

        Performs a backwards BFS through *maps* starting from *module*,
        following each :class:`ReExportMap` that exports *name*, until reaching
        a module that does not import *name* from elsewhere (its defining
        module).  Copilot-assisted tracing provides hints when the chain is
        broken by a star import with an unresolved ``__all__``.

        Parameters
        ----------
        name:
            The symbol name to trace.
        module:
            The :class:`ImportNode` where *name* is currently visible.
        maps:
            All :class:`ReExportMap` objects to search through.

        Returns
        -------
        ImportNode | None
            The :class:`ImportNode` that originally defines *name*, or ``None``
            if the origin cannot be determined.
        """
        module_name = _node_name(module)
        visited: set[str] = {module_name}
        current_name = module_name

        for _ in range(50):  # Limit chain depth to avoid infinite loops
            # Find a map that exports `name` from `current_name`
            candidate = None
            for remap in maps:
                if _remap_target_name(remap) == current_name:
                    exported = _remap_exported_names(remap)
                    # Also check name_map for aliased re-exports
                    name_map = getattr(remap, "name_map", {})
                    original_name = {v: k for k, v in name_map.items()}.get(name, name)
                    if name in exported or original_name in exported:
                        src = _remap_source_name(remap)
                        if src not in visited:
                            candidate = src
                            break
            if candidate is None:
                # Current module is the defining module
                node_by_name = {_node_name(n): n for n in self.nodes}
                return node_by_name.get(current_name)
            visited.add(candidate)
            current_name = candidate
        return None


# ---
# §19.3 — StarImportResolver
# ---


@dataclass
class StarImportResolver:
    """Resolves ``from X import *`` star imports into explicit name lists.

    Star imports are covering morphisms in theory2.tex Ch19 §19.3.3: they
    generate a covering sieve where every name in ``X.__all__`` (or, if
    ``__all__`` is absent, every public name in ``X``) maps to a morphism
    in the import sheaf.

    The copilot evidence channel is the primary source of ``__all__``
    information when the module cannot be introspected at analysis time (e.g.
    C extension modules, modules with dynamic ``__all__`` construction).
    Copilot-provided ``__all__`` lists are registered at
    ``TrustLevel.COPILOT_SUGGESTED`` and promoted when confirmed by runtime
    introspection.

    Parameters
    ----------
    None — all state is accumulated via :meth:`register_all`.
    """

    _all_table: dict[str, list[str]] = field(default_factory=dict)

    # --- methods ---

    def register_all(self, module_name: str, names: list[str]) -> None:
        """Register the ``__all__`` list for *module_name*.

        Overwrites any previous registration for the same module.  Called
        by the import-graph builder when it encounters an ``__all__``
        assignment in a parsed AST, and by the copilot oracle channel when
        it proposes a public API for a module without a static ``__all__``.

        Parameters
        ----------
        module_name:
            Fully-qualified module name.
        names:
            List of public symbol names to register as ``__all__``.
        """
        self._all_table[module_name] = list(names)

    def resolve_star(self, source_module: str, target_module: str) -> list[str]:
        """Resolve ``from source_module import *`` into an explicit name list.

        Looks up *source_module* in the :attr:`_all_table`.  If found, returns
        the registered ``__all__`` list.  If not found, returns an empty list
        and the caller should treat the star import as unresolved (low trust).

        In theory2.tex §19.3.3, the resolved names are the morphism generators
        of the covering sieve produced by the star import.  The copilot channel
        is consulted when :meth:`has_all` returns ``False`` to propose an
        estimated list.

        Parameters
        ----------
        source_module:
            The module being star-imported (``from X import *``).
        target_module:
            The module performing the star import (for logging / audit).

        Returns
        -------
        list[str]
            Resolved list of exported names, or empty list if unknown.
        """
        return list(self._all_table.get(source_module, []))

    def expand_star_edge(self, edge: Any, all_table: dict[str, list[str]]) -> Any:
        """Replace a star import edge with an explicit-names edge.

        Creates a new :class:`ImportEdge` identical to *edge* but with:
        * ``import_kind`` changed from ``"STAR"`` to ``"ABSOLUTE"``.
        * ``imported_names`` set to the resolved name list from *all_table*.

        If *all_table* does not contain the source module, returns *edge*
        unchanged (the star remains unresolved).

        Parameters
        ----------
        edge:
            The star import :class:`ImportEdge` to expand.
        all_table:
            Mapping of module name to ``__all__`` list.

        Returns
        -------
        ImportEdge
            Expanded edge, or the original if the source is not in *all_table*.
        """
        src_name = _edge_source_name(edge)
        names = all_table.get(src_name)
        if names is None:
            return edge
        try:
            return replace(edge, import_kind="ABSOLUTE", imported_names=tuple(names))
        except Exception:
            return edge

    def build_covering_family(self, star_edge: Any) -> Any:
        """Build a :class:`CoveringFamily` for a star import edge.

        The covering family's base is the source module's coordinate and its
        members are one :class:`Morphism` per exported name (resolved via
        :meth:`resolve_star`).  This represents the covering sieve generated by
        ``from source import *`` in theory2.tex §19.3.3.

        Copilot-provided ``__all__`` data is used when the source module is not
        in :attr:`_all_table`; in that case a single placeholder morphism is
        emitted at ``TrustLevel.COPILOT_SUGGESTED``.

        Parameters
        ----------
        star_edge:
            The star import :class:`ImportEdge` to convert.

        Returns
        -------
        CoveringFamily
            A :class:`CoveringFamily` whose members are name-level morphisms.
        """
        src_name = _edge_source_name(star_edge)
        tgt_name = _edge_target_name(star_edge)
        names = self.resolve_star(src_name, tgt_name)
        source = getattr(star_edge, "source", None)
        target = getattr(star_edge, "target", None)
        src_coord = _make_stub_coordinate(src_name)
        members: list[Any] = []
        for name in names:
            name_coord = _make_stub_coordinate(f"{tgt_name}.{name}")
            morph = Morphism(source=src_coord, target=name_coord, kind=MorphismKind.TRANSPORT)
            members.append(morph)
        if not members:
            # Unresolved star: emit a single covering morphism flagged as copilot-suggested
            morph = Morphism(source=src_coord, target=_make_stub_coordinate(tgt_name), kind=MorphismKind.TRANSPORT)
            members.append(morph)
        try:
            return CoveringFamily(base=src_coord, members=members)
        except Exception:
            return CoveringFamily(src_coord, members)  # type: ignore[call-arg]

    def has_all(self, module_name: str) -> bool:
        """Check whether *module_name* has a registered ``__all__`` list.

        Parameters
        ----------
        module_name:
            Fully-qualified module name to check.

        Returns
        -------
        bool
            ``True`` if :attr:`_all_table` contains an entry for *module_name*.
        """
        return module_name in self._all_table

    def unknown_stars(self) -> list[str]:
        """Return module names that have unresolved star imports.

        Identifies modules that appear as sources in star imports (i.e.
        ``from X import *``) but do not have a registered ``__all__`` entry.
        Copilot-assisted analysis is required to resolve these.

        Returns
        -------
        list[str]
            Sorted list of module names with unresolved star imports.
        """
        # This requires knowledge of all star-import sources; return modules
        # in _all_table that have an empty list (explicitly unresolved)
        return sorted(
            name for name, names in self._all_table.items()
            if not names
        )


# ---
# §19.3 — TrustTransporter
# ---


@dataclass
class TrustTransporter:
    """Transports trust through re-export chains with configurable decay.

    In theory2.tex Ch19 §19.3.4, every re-export hop weakens the trust of the
    transported name.  A name proven at ``RUNTIME_WITNESSED`` in module ``C``
    that reaches module ``A`` through two re-export hops arrives at a trust
    level of at most ``int(3 * 0.9^2) = 2`` (``COPILOT_SUGGESTED``).

    The decay model is simple but conservative: it prevents copilot-suggested
    names from masquerading as runtime-witnessed just because they were
    re-exported through a trusted module.  The copilot display layer uses
    :meth:`explain_trust_path` to render a trust-chain breadcrumb.

    Parameters
    ----------
    decay_factor:
        Multiplicative decay applied to the trust integer per hop.
        Default is 0.9 (10% decay per hop).
    """

    decay_factor: float = 0.9

    # --- methods ---

    def transport(self, source_trust: Any, hops: int) -> Any:
        """Apply trust decay over *hops* re-export steps.

        Computes ``max(1, int(source_trust_value * decay_factor^hops))`` and
        returns the corresponding :class:`TrustLevel`.  The floor at
        ``UNVERIFIED`` (value 1) ensures that a name is never completely
        discarded by the transport mechanism.

        Parameters
        ----------
        source_trust:
            The :class:`TrustLevel` of the name in its defining module.
        hops:
            Number of re-export hops between the defining module and the
            consuming module.

        Returns
        -------
        TrustLevel
            Decayed trust level after *hops* transport steps.
        """
        if hops <= 0:
            return source_trust
        raw_value = _trust_int(source_trust)
        decayed = max(1, int(raw_value * (self.decay_factor ** hops)))
        return _trust_from_int(decayed)

    def chain_trust(self, maps: list[Any]) -> Any:
        """Compute the minimum trust across a chain of :class:`ReExportMap` objects.

        The trust of a name transported through a chain is bounded by the
        weakest link — the map with the lowest trust level.  This corresponds
        to the *infimum* in the trust lattice for the composed morphism.

        Parameters
        ----------
        maps:
            Ordered list of :class:`ReExportMap` objects forming the chain.

        Returns
        -------
        TrustLevel
            The minimum trust level across all maps in the chain.
        """
        if not maps:
            return TrustLevel.UNVERIFIED
        min_trust = _trust_int(getattr(maps[0], "trust", TrustLevel.COPILOT_SUGGESTED))
        for remap in maps[1:]:
            trust_val = _trust_int(getattr(remap, "trust", TrustLevel.COPILOT_SUGGESTED))
            if trust_val < min_trust:
                min_trust = trust_val
        return _trust_from_int(min_trust)

    def annotate_map(self, remap: Any) -> Any:
        """Return a new :class:`ReExportMap` with trust updated by decay.

        Applies :meth:`transport` with ``hops=1`` to the trust level of
        *remap*, producing a new map where trust reflects one re-export step.
        Uses :func:`dataclasses.replace` to preserve all other fields.

        Parameters
        ----------
        remap:
            The :class:`ReExportMap` to annotate.

        Returns
        -------
        ReExportMap
            A new map with decayed trust.
        """
        current_trust = getattr(remap, "trust", TrustLevel.COPILOT_SUGGESTED)
        new_trust = self.transport(current_trust, hops=1)
        try:
            return replace(remap, trust=new_trust)
        except Exception:
            return remap

    def build_trust_annotation(self, maps: list[Any]) -> Any:
        """Build a :class:`TrustAnnotation` for a re-export chain.

        Computes the chain trust via :meth:`chain_trust` and packages it in a
        :class:`TrustAnnotation` record suitable for the jugeo judgment layer.
        The annotation notes that the trust was computed by the copilot
        transport model.

        Parameters
        ----------
        maps:
            Ordered list of :class:`ReExportMap` objects forming the chain.

        Returns
        -------
        TrustAnnotation
            A :class:`TrustAnnotation` recording the chain trust and provenance.
        """
        chain_t = self.chain_trust(maps)
        hop_count = len(maps)
        notes = (
            f"Trust transported through {hop_count} re-export hop(s) "
            f"using copilot decay model (factor={self.decay_factor}). "
            f"Chain trust: {chain_t}."
        )
        try:
            annotation = TrustAnnotation(
                trust_level=chain_t,
                annotated_at=_now_iso(),
                source="copilot_transport_model",
                notes=notes,
            )
        except Exception:
            annotation = TrustAnnotation(
                trust_level=chain_t,
                annotated_at=_now_iso(),
            )
        return annotation

    def max_allowed_trust_for_dynamic(self, loader: str) -> Any:
        """Return the maximum allowed trust for a dynamically-loaded name.

        Dynamic loaders such as ``importlib.import_module``,
        ``__import__``, and ``pkgutil`` cannot be statically analysed, so
        names loaded through them are capped at ``COPILOT_SUGGESTED``.
        Known static loaders (``importlib.util.spec_from_file_location``)
        are allowed up to ``RUNTIME_WITNESSED``.

        The copilot evidence channel uses this method to enforce trust ceilings
        when tagging dynamically-constructed import edges.

        Parameters
        ----------
        loader:
            A string identifier for the loading mechanism (e.g.
            ``"importlib.import_module"``, ``"__import__"``,
            ``"spec_from_file_location"``).

        Returns
        -------
        TrustLevel
            The maximum allowed :class:`TrustLevel` for the loader.
        """
        _STATIC_LOADERS = {
            "spec_from_file_location",
            "importlib.util.spec_from_file_location",
            "importlib.util.find_spec",
        }
        if loader in _STATIC_LOADERS:
            return TrustLevel.RUNTIME_WITNESSED
        return TrustLevel.COPILOT_SUGGESTED

    def explain_trust_path(self, maps: list[Any]) -> list[str]:
        """Return explanation strings for the trust path through *maps*.

        Generates one line per re-export hop describing the source module,
        target module, and trust level after the hop.  The final line
        summarises the overall chain trust.  These explanations are used by
        the copilot display layer to render trust-chain breadcrumbs.

        Parameters
        ----------
        maps:
            Ordered list of :class:`ReExportMap` objects forming the chain.

        Returns
        -------
        list[str]
            Human-readable explanation of the trust path.
        """
        lines: list[str] = []
        current_trust = TrustLevel.VERIFIED_PROOF  # Start at maximum
        for i, remap in enumerate(maps):
            src = _remap_source_name(remap)
            tgt = _remap_target_name(remap)
            hop_trust = getattr(remap, "trust", TrustLevel.COPILOT_SUGGESTED)
            transported = self.transport(current_trust, hops=1)
            effective = _trust_from_int(min(_trust_int(hop_trust), _trust_int(transported)))
            lines.append(
                f"  hop {i+1}: {src} -> {tgt} "
                f"(edge trust={hop_trust}, transported={transported}, "
                f"effective={effective})"
            )
            current_trust = effective
        chain = self.chain_trust(maps)
        lines.append(f"  Final chain trust: {chain}")
        lines.append(
            "  (copilot transport model applied; promote hops to RUNTIME_WITNESSED "
            "to improve chain trust)"
        )
        return lines


# ---
# §19.3 — PrivateLeakDetector
# ---


@dataclass
class PrivateLeakDetector:
    """Detects private symbols that leak through public re-exports.

    In theory2.tex Ch19 §19.3.5, private-symbol leakage is a cohomological
    obstruction: it means the module's public interface does not form a valid
    covering family because it includes names that violate the module's stated
    encapsulation boundary.

    The detector scans all :class:`ReExportMap` objects for names starting
    with ``_`` that appear in exported positions.  Each leak becomes an
    :class:`Obstruction` with ``cohomology_class="PRIVATE_LEAK"`` and
    copilot-generated repair hints.

    The copilot evidence channel contributes to this analysis by flagging
    patterns such as ``from ._internal import _helper`` in a package
    ``__init__.py`` where ``_helper`` appears in ``__all__`` — a common mistake
    in auto-generated code.
    """

    _leaks: list[tuple[Any, str]] = field(default_factory=list)

    # --- methods ---

    def scan_map(self, remap: Any) -> list[str]:
        """Scan a :class:`ReExportMap` for private names in exported positions.

        Returns the list of private names (starting with ``_`` but not dunder)
        that appear in the map's ``exported_names`` list and are marked as
        public (i.e. would appear in ``__all__``).

        Parameters
        ----------
        remap:
            A :class:`ReExportMap` to scan.

        Returns
        -------
        list[str]
            List of private names that are exported.
        """
        exported = _remap_exported_names(remap)
        return [name for name in exported if _is_private_name(name)]

    def scan_all(self, maps: list[Any]) -> None:
        """Scan all :class:`ReExportMap` objects and populate :attr:`_leaks`.

        Calls :meth:`scan_map` for each map and appends
        ``(source_module_node, leaked_name)`` tuples to :attr:`_leaks` for
        every detected leak.  Clears any previous leaks before scanning.

        Parameters
        ----------
        maps:
            All :class:`ReExportMap` objects to scan.
        """
        self._leaks = []
        for remap in maps:
            leaked_names = self.scan_map(remap)
            target = getattr(remap, "target_module", None)
            if target is None:
                continue
            for name in leaked_names:
                self._leaks.append((target, name))

    def leaked_symbols(self) -> list[tuple[Any, str]]:
        """Return all detected ``(module, leaked_name)`` pairs.

        Returns
        -------
        list[tuple[ImportNode, str]]
            All leaks accumulated by :meth:`scan_all`.
        """
        return list(self._leaks)

    def has_leaks(self) -> bool:
        """Return ``True`` if any private leaks were detected.

        Returns
        -------
        bool
            ``True`` when :attr:`_leaks` is non-empty.
        """
        return len(self._leaks) > 0

    def severity_score(self, module: Any) -> float:
        """Compute the leak severity score for *module*.

        Returns the ratio of leaked private names to the total number of
        exported names for *module* across all scanned re-export maps.  A
        score of 0.0 means no leaks; 1.0 means all exported names are private.

        The copilot display layer renders this score as a severity badge on the
        module's import-graph node.

        Parameters
        ----------
        module:
            The :class:`ImportNode` to score.

        Returns
        -------
        float
            Leak severity in [0.0, 1.0].
        """
        module_name = _node_name(module)
        leaked_for_module = [
            name for (mod, name) in self._leaks
            if _node_name(mod) == module_name
        ]
        # Count total exported names for this module across all known leaks
        # We use the leaked count as numerator and estimate denominator
        # from the unique leaked names (conservative lower bound)
        total_leaked = len(leaked_for_module)
        if total_leaked == 0:
            return 0.0
        # Without access to all exported names, use number of unique leaked names
        # as a fraction of itself + an estimated clean export count (heuristic: 5)
        estimated_total = total_leaked + 5
        return total_leaked / estimated_total

    def report(self) -> str:
        """Generate a human-readable report of all detected private leaks.

        Lists each leaked symbol, its module, and a copilot-generated repair
        hint.  Returns ``"No private symbol leaks detected."`` if :attr:`_leaks`
        is empty.

        Returns
        -------
        str
            Multi-line report string.
        """
        if not self._leaks:
            return "No private symbol leaks detected."
        lines: list[str] = [
            "=== Private Symbol Leak Report ===",
            f"Total leaks: {len(self._leaks)}",
            "",
        ]
        by_module: dict[str, list[str]] = {}
        for mod, name in self._leaks:
            key = _node_name(mod)
            by_module.setdefault(key, []).append(name)
        for module_name, leaked_names in sorted(by_module.items()):
            lines.append(f"Module: {module_name}")
            for name in sorted(leaked_names):
                lines.append(f"  LEAK: '{name}' is private but appears in re-exported names.")
                lines.append(
                    f"    Copilot hint: consider removing '{name}' from __all__ or "
                    f"renaming it to a public name."
                )
        lines.append("")
        lines.append(
            "Note: copilot-assisted analysis may flag false positives for "
            "intentionally-exported private symbols (e.g. semi-public APIs). "
            "Review each leak before applying the suggested repair."
        )
        return "\n".join(lines)

    def as_obstruction_list(self) -> list[Any]:
        """Convert each detected leak to an :class:`Obstruction` record.

        Each ``(module, leaked_name)`` pair becomes one :class:`Obstruction`
        with ``cohomology_class="PRIVATE_LEAK"`` and copilot-generated
        ``repair_hints``.  The ``obstruction_id`` is a stable hash of the
        module name and symbol name so that the same leak produces the same ID
        across multiple analysis runs.

        Returns
        -------
        list[Obstruction]
            One :class:`Obstruction` per detected private symbol leak.
        """
        obstructions: list[Any] = []
        for mod, name in self._leaks:
            module_name = _node_name(mod)
            obs_id = _stable_hash(f"PRIVATE_LEAK:{module_name}:{name}")
            repair = (
                f"Remove '{name}' from the public re-export list of '{module_name}', "
                f"or rename it to a public symbol. "
                f"Copilot suggests introducing a public alias: "
                f"'{name.lstrip('_')}' = {name}."
            )
            obs = Obstruction(
                obstruction_id=obs_id,
                violated_condition="private_symbol_leaked",
                coordinate=module_name,
                evidence_at_time=(name,),
                repair_hints=(repair,),
                cohomology_class="PRIVATE_LEAK",
                is_resolved=False,
                resolution_evidence="",
            )
            obstructions.append(obs)
        return obstructions


# ---
# Module-level convenience functions
# ---


def _analyze_reexports(
    nodes: list[Any],
    edges: list[Any],
) -> tuple[list[Any], list[Any]]:
    """Analyse re-exports and return ``(maps, leaks)``.

    Creates a :class:`ReExportAnalyzer`, builds all re-export maps, scans for
    private leaks, and returns both results.  Suitable for one-shot copilot-
    assisted re-export analysis.

    Parameters
    ----------
    nodes:
        All :class:`ImportNode` objects.
    edges:
        All :class:`ImportEdge` objects.

    Returns
    -------
    tuple[list[ReExportMap], list[Obstruction]]
        ``(maps, leak_obstructions)``
    """
    analyzer = ReExportAnalyzer(nodes=nodes, edges=edges)
    maps = analyzer.build_reexport_maps()
    detector = PrivateLeakDetector()
    detector.scan_all(maps)
    obstructions = detector.as_obstruction_list()
    return maps, obstructions


def _resolve_all_stars(
    edges: list[Any],
    all_table: dict[str, list[str]],
) -> list[Any]:
    """Resolve all star import edges using *all_table*.

    Creates a :class:`StarImportResolver`, populates it from *all_table*,
    and expands each star edge in *edges*.  Returns the updated edge list with
    star imports replaced by explicit-name edges where possible.

    Parameters
    ----------
    edges:
        All import edges, potentially containing star imports.
    all_table:
        Mapping of module name to ``__all__`` list.

    Returns
    -------
    list[ImportEdge]
        Updated edge list with resolved star imports.
    """
    resolver = StarImportResolver()
    for module_name, names in all_table.items():
        resolver.register_all(module_name, names)
    result: list[Any] = []
    for edge in edges:
        if getattr(edge, "import_kind", "") == "STAR":
            expanded = resolver.expand_star_edge(edge, all_table)
            result.append(expanded)
        else:
            result.append(edge)
    return result


def _transport_trust_through_chain(
    maps: list[Any],
    decay_factor: float = 0.9,
) -> Any:
    """Transport trust through a re-export chain and return the effective level.

    Creates a :class:`TrustTransporter` with *decay_factor* and calls
    :meth:`~TrustTransporter.chain_trust` on *maps*.

    Parameters
    ----------
    maps:
        Ordered re-export chain.
    decay_factor:
        Per-hop trust decay factor.

    Returns
    -------
    TrustLevel
        Effective trust level after transport through the chain.
    """
    transporter = TrustTransporter(decay_factor=decay_factor)
    return transporter.chain_trust(maps)
