"""Generate CSS and JavaScript for Flask apps — stdlib only."""
from __future__ import annotations

import textwrap
from .models import AppSpec, RouteSpec, FormSpec, ResponseType


class CSSGenerator:
    """Produces CSS source strings."""

    def generate_base_css(self) -> str:
        return textwrap.dedent("""\
/* ========================================================================
   Base CSS — generated by JuGeo webapp generation
   ======================================================================== */

/* --- Custom Properties ------------------------------------------------- */
:root {
    --color-primary: #2563eb;
    --color-secondary: #7c3aed;
    --color-success: #16a34a;
    --color-warning: #d97706;
    --color-danger: #dc2626;
    --color-info: #0891b2;
    --color-light: #f8fafc;
    --color-dark: #1e293b;
    --color-bg: #ffffff;
    --color-text: #1e293b;
    --color-muted: #64748b;
    --color-border: #e2e8f0;
    --font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif;
    --font-mono: 'Fira Code', 'Courier New', monospace;
    --radius: 0.375rem;
    --shadow: 0 1px 3px rgba(0,0,0,0.12);
    --shadow-lg: 0 10px 15px rgba(0,0,0,0.1);
    --transition: 0.2s ease;
}

/* --- Reset ------------------------------------------------------------- */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { font-size: 16px; line-height: 1.6; scroll-behavior: smooth; }
body {
    font-family: var(--font-sans);
    color: var(--color-text);
    background: var(--color-bg);
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}
a { color: var(--color-primary); text-decoration: none; transition: color var(--transition); }
a:hover { color: var(--color-secondary); text-decoration: underline; }
img { max-width: 100%; height: auto; }

/* --- Typography -------------------------------------------------------- */
h1, h2, h3, h4, h5, h6 { margin-bottom: 0.5em; font-weight: 600; line-height: 1.25; }
h1 { font-size: 2rem; }
h2 { font-size: 1.5rem; }
h3 { font-size: 1.25rem; }
p { margin-bottom: 1rem; }
code, pre { font-family: var(--font-mono); background: var(--color-light); border-radius: var(--radius); }
code { padding: 0.125em 0.25em; font-size: 0.875em; }
pre { padding: 1rem; overflow-x: auto; }

/* --- Layout ------------------------------------------------------------ */
.container { width: 100%; max-width: 1200px; margin: 0 auto; padding: 1rem; flex: 1; }
.row { display: flex; flex-wrap: wrap; gap: 1rem; }
.col { flex: 1; }

/* --- Navbar ------------------------------------------------------------ */
.navbar {
    display: flex; align-items: center; justify-content: space-between;
    padding: 0.75rem 1.5rem; background: var(--color-dark); color: #fff;
}
.navbar a { color: #fff; }
.navbar-brand a { font-weight: 700; font-size: 1.25rem; }
.navbar-nav { list-style: none; display: flex; gap: 1rem; }
.navbar-toggle { display: none; background: none; border: none; color: #fff; font-size: 1.5rem; cursor: pointer; }

/* --- Cards ------------------------------------------------------------- */
.card {
    background: var(--color-bg); border: 1px solid var(--color-border);
    border-radius: var(--radius); box-shadow: var(--shadow); overflow: hidden;
}
.card-header { padding: 1rem; border-bottom: 1px solid var(--color-border); }
.card-body { padding: 1rem; }
.card-footer { padding: 0.75rem 1rem; border-top: 1px solid var(--color-border); background: var(--color-light); }

/* --- Tables ------------------------------------------------------------ */
.table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; }
.table th, .table td { padding: 0.75rem; text-align: left; border-bottom: 1px solid var(--color-border); }
.table th { background: var(--color-light); font-weight: 600; }
.table tbody tr:hover { background: var(--color-light); }

/* --- Forms ------------------------------------------------------------- */
.form-group { margin-bottom: 1rem; }
.form-group label { display: block; margin-bottom: 0.25rem; font-weight: 500; }
.form-group input,
.form-group select,
.form-group textarea {
    width: 100%; padding: 0.5rem 0.75rem;
    border: 1px solid var(--color-border); border-radius: var(--radius);
    font-size: 1rem; transition: border-color var(--transition);
}
.form-group input:focus,
.form-group select:focus,
.form-group textarea:focus { outline: none; border-color: var(--color-primary); box-shadow: 0 0 0 3px rgba(37,99,235,0.15); }
textarea { min-height: 6rem; resize: vertical; }

/* --- Buttons ----------------------------------------------------------- */
.btn {
    display: inline-block; padding: 0.5rem 1rem; border: none; border-radius: var(--radius);
    font-size: 1rem; font-weight: 500; cursor: pointer; text-align: center;
    transition: background var(--transition), transform var(--transition);
}
.btn:hover { transform: translateY(-1px); }
.btn-primary { background: var(--color-primary); color: #fff; }
.btn-primary:hover { background: #1d4ed8; color: #fff; text-decoration: none; }
.btn-secondary { background: var(--color-secondary); color: #fff; }
.btn-danger { background: var(--color-danger); color: #fff; }
.btn-success { background: var(--color-success); color: #fff; }

/* --- Alerts / Flash ---------------------------------------------------- */
.alert {
    padding: 0.75rem 1rem; margin-bottom: 1rem; border-radius: var(--radius);
    border: 1px solid transparent;
}
.alert-success { background: #dcfce7; border-color: #86efac; color: #166534; }
.alert-danger, .alert-error { background: #fee2e2; border-color: #fca5a5; color: #991b1b; }
.alert-warning { background: #fef3c7; border-color: #fcd34d; color: #92400e; }
.alert-info { background: #e0f2fe; border-color: #7dd3fc; color: #075985; }
.flash-messages { max-width: 1200px; margin: 0 auto; padding: 0 1rem; }

/* --- Pagination -------------------------------------------------------- */
.pagination { display: flex; gap: 0.25rem; justify-content: center; margin: 1rem 0; }
.pagination a { padding: 0.5rem 0.75rem; border: 1px solid var(--color-border); border-radius: var(--radius); }
.pagination a.active { background: var(--color-primary); color: #fff; border-color: var(--color-primary); }

/* --- Modal ------------------------------------------------------------- */
.modal { display: none; position: fixed; inset: 0; z-index: 1000; }
.modal.active { display: flex; align-items: center; justify-content: center; }
.modal-overlay { position: absolute; inset: 0; background: rgba(0,0,0,0.5); }
.modal-content { position: relative; background: var(--color-bg); border-radius: var(--radius); box-shadow: var(--shadow-lg); max-width: 600px; width: 90%; }
.modal-header { display: flex; justify-content: space-between; align-items: center; padding: 1rem; border-bottom: 1px solid var(--color-border); }
.modal-body { padding: 1rem; }
.modal-close { background: none; border: none; font-size: 1.5rem; cursor: pointer; }

/* --- Error page -------------------------------------------------------- */
.error-page { text-align: center; padding: 4rem 1rem; }
.error-page h1 { font-size: 6rem; color: var(--color-muted); }

/* --- Dashboard --------------------------------------------------------- */
.dashboard-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1rem; }
.dashboard-grid .card .value { font-size: 2rem; font-weight: 700; color: var(--color-primary); }

/* --- Detail view ------------------------------------------------------- */
.detail-view p { margin-bottom: 0.5rem; }

/* --- Footer ------------------------------------------------------------ */
.footer { padding: 1rem; text-align: center; color: var(--color-muted); border-top: 1px solid var(--color-border); margin-top: auto; }

/* --- Responsive breakpoints -------------------------------------------- */
@media (max-width: 576px) {
    .container { padding: 0.5rem; }
    h1 { font-size: 1.5rem; }
    .navbar { flex-wrap: wrap; }
    .navbar-nav { display: none; flex-direction: column; width: 100%; }
    .navbar-nav.active { display: flex; }
    .navbar-toggle { display: block; }
    .dashboard-grid { grid-template-columns: 1fr; }
}
@media (min-width: 768px) {
    .container { padding: 1.5rem; }
}
@media (min-width: 992px) {
    .container { max-width: 960px; }
}
@media (min-width: 1200px) {
    .container { max-width: 1140px; }
}

/* --- Dark mode --------------------------------------------------------- */
@media (prefers-color-scheme: dark) {
    :root {
        --color-bg: #0f172a;
        --color-text: #e2e8f0;
        --color-light: #1e293b;
        --color-border: #334155;
        --color-muted: #94a3b8;
    }
    .navbar { background: #020617; }
    .table th { background: #1e293b; }
    code, pre { background: #1e293b; }
}

/* --- Print ------------------------------------------------------------- */
@media print {
    .navbar, .footer, .flash-messages, .btn { display: none; }
    body { color: #000; background: #fff; }
    .container { max-width: 100%; }
    a { color: #000; text-decoration: underline; }
}
""")

    def generate_custom_css(self, app_spec: AppSpec) -> str:
        name = app_spec.name
        return textwrap.dedent(f"""\
/* Custom styles for {name} */
.app-header {{
    background: var(--color-primary);
    color: #fff;
    padding: 2rem;
    text-align: center;
}}
""")


class JSGenerator:
    """Produces JavaScript source strings."""

    def generate_base_js(self) -> str:
        return textwrap.dedent("""\
/* ========================================================================
   Base JS — generated by JuGeo webapp generation
   ======================================================================== */
document.addEventListener('DOMContentLoaded', function() {

    // --- Flash message auto-dismiss ---
    var alerts = document.querySelectorAll('.alert');
    alerts.forEach(function(alert) {
        setTimeout(function() {
            alert.style.transition = 'opacity 0.5s';
            alert.style.opacity = '0';
            setTimeout(function() { alert.remove(); }, 500);
        }, 5000);
    });

    // --- Mobile menu toggle ---
    var toggle = document.querySelector('.navbar-toggle');
    var nav = document.querySelector('.navbar-nav');
    if (toggle && nav) {
        toggle.addEventListener('click', function() {
            nav.classList.toggle('active');
        });
    }

    // --- Modal open / close ---
    document.querySelectorAll('[data-modal]').forEach(function(btn) {
        btn.addEventListener('click', function() {
            var modal = document.getElementById(btn.dataset.modal);
            if (modal) modal.classList.add('active');
        });
    });
    document.querySelectorAll('.modal-close, .modal-overlay').forEach(function(el) {
        el.addEventListener('click', function() {
            var modal = el.closest('.modal');
            if (modal) modal.classList.remove('active');
        });
    });

    // --- CSRF token extraction ---
    function getCsrfToken() {
        var meta = document.querySelector('meta[name="csrf-token"]');
        return meta ? meta.getAttribute('content') : '';
    }

    // --- Fetch wrapper with error handling ---
    window.apiFetch = function(url, options) {
        options = options || {};
        options.headers = options.headers || {};
        options.headers['Content-Type'] = options.headers['Content-Type'] || 'application/json';
        var token = getCsrfToken();
        if (token) {
            options.headers['X-CSRFToken'] = token;
        }
        return fetch(url, options)
            .then(function(response) {
                if (!response.ok) {
                    throw new Error('HTTP ' + response.status + ': ' + response.statusText);
                }
                return response.json();
            })
            .catch(function(error) {
                console.error('API Error:', error);
                throw error;
            });
    };

    // --- Form validation helpers ---
    window.validateForm = function(formEl) {
        var valid = true;
        formEl.querySelectorAll('[required]').forEach(function(field) {
            if (!field.value.trim()) {
                field.classList.add('is-invalid');
                valid = false;
            } else {
                field.classList.remove('is-invalid');
            }
        });
        return valid;
    };

    // Auto-attach validation to forms with data-validate
    document.querySelectorAll('form[data-validate]').forEach(function(form) {
        form.addEventListener('submit', function(e) {
            if (!window.validateForm(form)) {
                e.preventDefault();
            }
        });
    });
});
""")

    def generate_api_client(self, routes: list) -> str:
        api_routes = [r for r in routes if getattr(r, 'response_type', None) == ResponseType.JSON]
        lines = [
            "/* Auto-generated API client */",
            "var API = (function() {",
            "    var base = '';",
            "",
        ]
        for route in api_routes:
            handler = route.handler_name or route.url.strip("/").replace("/", "_")
            methods = route.methods if route.methods else ["GET"]
            method = methods[0]
            lines.append(f"    function {handler}(data) {{")
            lines.append(f"        return apiFetch(base + '{route.url}', {{")
            lines.append(f"            method: '{method}',")
            if method in ("POST", "PUT", "PATCH"):
                lines.append("            body: JSON.stringify(data)")
            lines.append("        });")
            lines.append("    }")
            lines.append("")
        lines.append("    return {")
        for route in api_routes:
            handler = route.handler_name or route.url.strip("/").replace("/", "_")
            lines.append(f"        {handler}: {handler},")
        lines.append("    };")
        lines.append("})();")
        return "\n".join(lines)

    def generate_form_validation(self, forms: list) -> str:
        lines = ["/* Auto-generated form validation */"]
        for form in forms:
            name = form.name if hasattr(form, "name") else str(form)
            lines.append(f"// Validation for {name}")
            lines.append(f"(function() {{")
            lines.append(f"    var form = document.querySelector('form[data-form=\"{name}\"]');")
            lines.append(f"    if (form) {{")
            lines.append(f"        form.addEventListener('submit', function(e) {{")
            lines.append(f"            if (!window.validateForm(form)) e.preventDefault();")
            lines.append(f"        }});")
            lines.append(f"    }}")
            lines.append(f"}})();")
            lines.append("")
        return "\n".join(lines)
