r"""theory2.tex Ch31 §31.3 — Algebraic Data Type Surfaces in Z3.

An *algebraic surface* is the interface of a Z3 algebraic datatype: the
set of constructors, recognizers, and accessor functions that define how
values of the sort are created and destructed.

Given a sort :math:`T` with constructors :math:`c_1, \\ldots, c_n`, the
surface consists of:

.. math::

   \\text{Surface}(T)
   = \\bigl\\{c_i : A^{(i)}_1 \\times \\cdots \\times A^{(i)}_{k_i} \\to T\\bigr\\}_{i=1}^{n}
   \\cup \\bigl\\{\\mathrm{is}\\text{-}c_i : T \\to \\mathbb{B}\\bigr\\}_{i=1}^{n}
   \\cup \\bigl\\{\\pi^{(i)}_j : T \\to A^{(i)}_j\\bigr\\}_{i,j}

Fold/unfold (§31.3.2):

.. math::

   \\mathrm{fold}_{T}(f_1, \\ldots, f_n)(\\mathrm{c}_i(x_1, \\ldots, x_{k_i}))
   = f_i(x_1, \\ldots, x_{k_i})

The surface abstraction is central to the partiality-model reconstruction
pipeline because each algebraic datatype produced by the Z3 encoder must
be disassembled by traversing its surface.  Without a uniform surface
API, the reconstruction layer would need bespoke destructuring logic for
every distinct algebraic sort, which would be fragile and non-compositional.

§31.3.1 — Constructor specifications
--------------------------------------
Each constructor :math:`c_i` carries an *arity* :math:`k_i \\ge 0`, a list
of *field sorts* :math:`A^{(i)}_1, \\ldots, A^{(i)}_{k_i}`, and optional
*field names* that become the accessor (projection) function names in SMT-LIB 2.

§31.3.3 — Recognizer predicates
---------------------------------
The recognizer :math:`\\mathrm{is}\\text{-}c_i : T \\to \\mathbb{B}` is the
unique predicate generated by ``declare-datatypes`` for every constructor.
Composing recognizers with Boolean guards yields conditional projections.

§31.3.4 — Fold combinators
----------------------------
A *fold* over sort :math:`T` is a function
:math:`\\text{fold}_T : (A^{(1)} \\to R) \\times \\cdots \\times (A^{(n)} \\to R) \\to T \\to R`
that eliminates a value of sort :math:`T` by dispatching on its constructor.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# Standard library imports
# ---------------------------------------------------------------------------
import hashlib
import json
import time
import uuid
from dataclasses import dataclass, field
import dataclasses
from enum import Enum
from typing import Any

# ---------------------------------------------------------------------------
# Optional jugeo subpackage imports — gracefully degrade when unavailable
# ---------------------------------------------------------------------------

try:
    from jugeo.solver.z3_session import Z3Session, Z3Formula, Z3Encoder, Z3Decoder, Z3Result
    _Z3_SESSION_AVAILABLE = True
except ImportError:
    _Z3_SESSION_AVAILABLE = False
    class Z3Session: pass  # type: ignore[misc]
    class Z3Formula: pass  # type: ignore[misc]
    class Z3Encoder: pass  # type: ignore[misc]
    class Z3Decoder: pass  # type: ignore[misc]
    class Z3Result: pass  # type: ignore[misc]

try:
    from jugeo.solver.reconstruction import ModelReconstructor as SolverModelReconstruction
    _RECONSTRUCTION_AVAILABLE = True
except ImportError:
    _RECONSTRUCTION_AVAILABLE = False
    class SolverModelReconstruction: pass  # type: ignore[misc]

try:
    from jugeo.judgments.judgment_terms import JudgmentTerm, Judgment
    _JUDGMENTS_AVAILABLE = True
except ImportError:
    _JUDGMENTS_AVAILABLE = False
    class JudgmentTerm: pass  # type: ignore[misc]
    class Judgment: pass  # type: ignore[misc]

try:
    from jugeo.evidence.trust import TrustAlgebra, TrustLevel
    _TRUST_AVAILABLE = True
except ImportError:
    _TRUST_AVAILABLE = False
    class TrustAlgebra: pass  # type: ignore[misc]
    class TrustLevel: pass  # type: ignore[misc]


# ---------------------------------------------------------------------------
# §31.3 Enumerations
# ---------------------------------------------------------------------------


class ConstructorArity(str, Enum):
    """Classifies a constructor by its number of fields.

    This mirrors the standard arity hierarchy used in type-theoretic
    presentations of algebraic data types.  Nullary constructors
    correspond to constants / atoms; unary constructors act as wrappers;
    binary and n-ary constructors are proper product types.
    """

    NULLARY = "nullary"
    """No fields — a constant/atom constructor (e.g. ``nil``, ``true``)."""

    UNARY = "unary"
    """Exactly one field — a wrapper or coercion constructor."""

    BINARY = "binary"
    """Exactly two fields — a pair-like constructor."""

    NARY = "nary"
    """Three or more fields — a general product constructor."""


class SurfaceKind(str, Enum):
    """Characterizes the recursion structure of an algebraic sort's surface.

    The distinction between inductive and coinductive surfaces matters for
    the fold/unfold semantics: inductive surfaces support structural
    recursion that provably terminates, whereas coinductive surfaces
    support corecursion / stream-like infinite values.
    """

    INDUCTIVE = "inductive"
    """Standard inductive / well-founded ADT (e.g. lists, trees)."""

    COINDUCTIVE = "coinductive"
    """Coinductive / potentially-infinite ADT (e.g. streams, lazy trees)."""

    RECURSIVE = "recursive"
    """Self-referential ADT without a coinductive type annotation."""

    MUTUAL = "mutual"
    """Two or more sorts defined by mutual recursion."""

    SIMPLE = "simple"
    """Non-recursive enum or product — no recursion at all."""


class ProjectionMode(str, Enum):
    """Indicates whether a surface projection is total or may be undefined.

    Totality is critical in Z3 because SMT-LIB 2 projections (accessors)
    are technically total functions; however, applying an accessor from
    constructor :math:`c_i` to a value built by :math:`c_j \\neq c_i`
    yields an unspecified (but semantically valid) value.  Marking
    projections as PARTIAL or CONDITIONAL lets downstream code insert
    recognizer guards before applying them.
    """

    TOTAL = "total"
    """Safe to apply to any value of the sort without a guard."""

    PARTIAL = "partial"
    """Should only be applied after a recognizer check."""

    CONDITIONAL = "conditional"
    """Totalized by a supplied Boolean guard expression."""


# ---------------------------------------------------------------------------
# §31.3.1 — ConstructorSpec
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ConstructorSpec:
    """Specification of a single algebraic datatype constructor.

    A :class:`ConstructorSpec` captures the complete *signature* of one
    constructor within a ``declare-datatypes`` declaration in SMT-LIB 2.
    It stores the constructor name, the sorts of each field, and optional
    human-readable names for the fields (which become the accessor
    function identifiers).

    Parameters
    ----------
    name:
        The constructor identifier, e.g. ``"cons"`` or ``"leaf"``.
    field_sorts:
        A tuple of sort-name strings for each field, in declaration order,
        e.g. ``("Int", "List_Int")``.
    field_names:
        A tuple of accessor-function names corresponding positionally to
        ``field_sorts``.  May be shorter than ``field_sorts`` or empty,
        in which case auto-generated names of the form ``field_i`` are used.
    spec_id:
        A UUID string that uniquely identifies this constructor spec
        instance, used for caching and equality checks across serialization
        boundaries.

    Examples
    --------
    >>> spec = ConstructorSpec(name="cons", field_sorts=("Int", "List_Int"),
    ...                        field_names=("head", "tail"))
    >>> spec.arity()
    2
    >>> spec.arity_kind()
    <ConstructorArity.BINARY: 'binary'>
    >>> spec.to_smt2_constructor()
    '(cons (head Int) (tail List_Int))'
    """

    name: str
    field_sorts: tuple[str, ...] = ()
    field_names: tuple[str, ...] = ()
    spec_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # ------------------------------------------------------------------
    # Arity helpers
    # ------------------------------------------------------------------

    def arity(self) -> int:
        """Return the number of fields (arguments) this constructor takes.

        For a nullary constructor (constant) this is 0; for a binary
        constructor it is 2, etc.

        Returns
        -------
        int
            ``len(self.field_sorts)``
        """
        return len(self.field_sorts)

    def arity_kind(self) -> ConstructorArity:
        """Classify this constructor's arity as a :class:`ConstructorArity` variant.

        Returns
        -------
        ConstructorArity
            - ``NULLARY`` when :meth:`arity` is 0
            - ``UNARY``   when :meth:`arity` is 1
            - ``BINARY``  when :meth:`arity` is 2
            - ``NARY``    when :meth:`arity` is ≥ 3
        """
        n = self.arity()
        if n == 0:
            return ConstructorArity.NULLARY
        if n == 1:
            return ConstructorArity.UNARY
        if n == 2:
            return ConstructorArity.BINARY
        return ConstructorArity.NARY

    # ------------------------------------------------------------------
    # Field accessors
    # ------------------------------------------------------------------

    def field_at(self, idx: int) -> tuple[str, str]:
        """Return the ``(field_name, sort_name)`` pair at position *idx*.

        If the ``field_names`` tuple is shorter than ``field_sorts`` at
        position *idx*, a synthetic name ``field_{idx}`` is substituted.

        Parameters
        ----------
        idx:
            Zero-based index into the field list.

        Returns
        -------
        tuple[str, str]
            ``(name, sort)`` pair for the requested field.

        Raises
        ------
        IndexError
            When *idx* is out of range for ``field_sorts``.
        """
        if idx < 0 or idx >= len(self.field_sorts):
            raise IndexError(
                f"ConstructorSpec '{self.name}': field index {idx} is out of range "
                f"(arity={self.arity()})"
            )
        sort = self.field_sorts[idx]
        if idx < len(self.field_names):
            name = self.field_names[idx]
        else:
            name = f"field_{idx}"
        return (name, sort)

    # ------------------------------------------------------------------
    # SMT-LIB 2 emission
    # ------------------------------------------------------------------

    def to_smt2_constructor(self) -> str:
        """Render this constructor as an SMT-LIB 2 constructor clause.

        For a nullary constructor this produces ``(name)``.
        For constructors with fields it produces
        ``(name (field0_name field0_sort) … (fieldN_name fieldN_sort))``.

        Returns
        -------
        str
            Well-formed SMT-LIB 2 constructor clause fragment, suitable
            for embedding inside a ``declare-datatypes`` expression.
        """
        if self.arity() == 0:
            return f"({self.name})"
        field_parts: list[str] = []
        for i in range(self.arity()):
            fname, fsort = self.field_at(i)
            field_parts.append(f"({fname} {fsort})")
        fields_str = " ".join(field_parts)
        return f"({self.name} {fields_str})"

    def recognizer_name(self) -> str:
        """Return the SMT-LIB 2 recognizer function name for this constructor.

        By the SMT-LIB 2 standard for algebraic datatypes, the recognizer
        is named ``is-<constructor>``.

        Returns
        -------
        str
            e.g. ``"is-cons"`` for a constructor named ``"cons"``.
        """
        return f"is-{self.name}"

    def accessor_name(self, field_idx: int) -> str:
        """Return the accessor (projection) function name for field *field_idx*.

        If the field has an explicit name in ``field_names``, that name is
        returned directly (as it will be the declared accessor name).
        Otherwise, a synthetic accessor name ``{constructor_name}-{field_idx}``
        is returned following the JuGeo naming convention.

        Parameters
        ----------
        field_idx:
            Zero-based index of the field whose accessor name is requested.

        Returns
        -------
        str
            Accessor function name.
        """
        if field_idx < len(self.field_names):
            return self.field_names[field_idx]
        return f"{self.name}-{field_idx}"

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def validate(self) -> list[str]:
        """Check the internal consistency of this constructor specification.

        Validation rules:

        1. ``name`` must be a non-empty string.
        2. If ``field_names`` is non-empty it must have the same length as
           ``field_sorts`` (extra names are ignored upstream, but mismatches
           indicate caller bugs).
        3. Each element of ``field_sorts`` must be a non-empty string.

        Returns
        -------
        list[str]
            A list of human-readable error messages.  An empty list means
            the spec is valid.
        """
        errors: list[str] = []
        if not self.name or not self.name.strip():
            errors.append("ConstructorSpec: 'name' must be a non-empty string.")
        if self.field_names and len(self.field_names) != len(self.field_sorts):
            errors.append(
                f"ConstructorSpec '{self.name}': field_names length "
                f"({len(self.field_names)}) != field_sorts length "
                f"({len(self.field_sorts)})."
            )
        for i, s in enumerate(self.field_sorts):
            if not s or not s.strip():
                errors.append(
                    f"ConstructorSpec '{self.name}': field_sorts[{i}] is empty."
                )
        return errors

    def to_dict(self) -> dict[str, Any]:
        """Serialize this spec to a JSON-compatible dictionary.

        Tuples are converted to lists so the result round-trips cleanly
        through ``json.dumps`` / ``json.loads``.

        Returns
        -------
        dict[str, Any]
            Dictionary with keys ``name``, ``field_sorts``, ``field_names``,
            ``spec_id``, and ``arity``.
        """
        return {
            "name": self.name,
            "field_sorts": list(self.field_sorts),
            "field_names": list(self.field_names),
            "spec_id": self.spec_id,
            "arity": self.arity(),
            "arity_kind": self.arity_kind().value,
        }


# ---------------------------------------------------------------------------
# §31.3.3 — RecognizerPredicate
# ---------------------------------------------------------------------------


@dataclass
class RecognizerPredicate:
    """A recognizer predicate associated with a single ADT constructor.

    Recognizers are the boolean-valued functions ``is-c_i : T → Bool``
    generated by ``declare-datatypes``.  This class provides a thin
    wrapper that allows recognizers to be composed with guards, negated,
    and emitted as SMT-LIB 2 assertions.

    Parameters
    ----------
    constructor_name:
        The constructor whose values this recognizer identifies.
    sort_name:
        The ADT sort name that owns this constructor.
    predicate_smt2:
        The SMT-LIB 2 function identifier for the recognizer.  If empty,
        the default ``is-{constructor_name}`` is used (set in
        ``__post_init__``).
    pred_id:
        UUID string uniquely identifying this recognizer instance.

    Notes
    -----
    Recognizer predicates are always *total*: they return ``true`` exactly
    for values built by their corresponding constructor, and ``false`` for
    all other constructor variants.
    """

    constructor_name: str
    sort_name: str
    predicate_smt2: str = ""
    pred_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def __post_init__(self) -> None:
        """Populate ``predicate_smt2`` from the constructor name if not supplied."""
        if not self.predicate_smt2:
            # Standard SMT-LIB 2 recognizer naming convention.
            self.predicate_smt2 = f"is-{self.constructor_name}"

    # ------------------------------------------------------------------
    # Application helpers
    # ------------------------------------------------------------------

    def apply_to(self, term: str) -> str:
        """Apply this recognizer to an SMT-LIB 2 term expression.

        Parameters
        ----------
        term:
            An SMT-LIB 2 expression denoting a value of ``sort_name``.

        Returns
        -------
        str
            The application expression, e.g. ``"(is-cons x)"``.
        """
        return f"({self.predicate_smt2} {term})"

    def negate(self) -> RecognizerPredicate:
        """Return a new recognizer predicate that is logically negated.

        The negated recognizer is true for every value of the sort that
        was *not* built by ``constructor_name``.  This is useful when
        constructing case-split complements.

        Returns
        -------
        RecognizerPredicate
            A fresh instance whose ``predicate_smt2`` wraps the original
            in ``(not …)``.
        """
        negated_smt2 = f"(not (is-{self.constructor_name} x))"
        return RecognizerPredicate(
            constructor_name=self.constructor_name,
            sort_name=self.sort_name,
            predicate_smt2=negated_smt2,
            pred_id=str(uuid.uuid4()),
        )

    def to_smt2_assert(self, term: str) -> str:
        """Emit this recognizer as a top-level ``(assert …)`` statement.

        Parameters
        ----------
        term:
            The term to be asserted as satisfying this recognizer.

        Returns
        -------
        str
            A complete SMT-LIB 2 assertion, e.g.
            ``"(assert (is-cons x))"``.
        """
        return f"(assert ({self.predicate_smt2} {term}))"

    def compose_with_guard(self, guard: str) -> str:
        """Produce a conjunction of this recognizer and an external guard.

        This is used to build conditional projections: the recognizer
        ensures we are looking at the right constructor, and the guard
        encodes additional semantic constraints.

        Parameters
        ----------
        guard:
            An SMT-LIB 2 Boolean expression (may reference variable
            ``x`` which is the implicit subject of this recognizer).

        Returns
        -------
        str
            An SMT-LIB 2 ``(and …)`` expression combining both conditions.
        """
        return f"(and ({self.predicate_smt2} x) {guard})"

    def is_trivial(self) -> bool:
        """Return ``True`` if this recognizer is the constant ``true`` or ``false``.

        Trivial recognizers arise when placeholder predicates are used
        during construction, before the actual recognizer name is known.

        Returns
        -------
        bool
            ``True`` iff ``predicate_smt2`` (stripped) is ``"true"`` or
            ``"false"``.
        """
        return self.predicate_smt2.strip() in ("true", "false")


# ---------------------------------------------------------------------------
# §31.3.2 — AlgebraicFold
# ---------------------------------------------------------------------------


@dataclass
class AlgebraicFold:
    """Fold combinator for a single algebraic sort.

    An :class:`AlgebraicFold` captures the *elimination principle* of an
    algebraic datatype: given one case expression per constructor, it
    dispatches on the outermost constructor of a value and evaluates the
    corresponding case.

    In SMT-LIB 2, folds are realized as nested ``(ite (is-c_i x) e_i …)``
    chains because SMT-LIB 2 (prior to the ``match`` extension) lacks
    native pattern matching.

    Parameters
    ----------
    sort_name:
        The ADT sort being folded over, e.g. ``"List_Int"``.
    constructors:
        An ordered list of :class:`ConstructorSpec` instances for all
        constructors of ``sort_name``.  The ordering determines the
        nesting order of the generated ``ite`` chain.
    result_sort:
        The SMT-LIB 2 sort of the fold's result.  Defaults to ``"Bool"``.
    fold_id:
        UUID string uniquely identifying this fold instance.
    """

    sort_name: str
    constructors: list[ConstructorSpec] = field(default_factory=list)
    result_sort: str = "Bool"
    fold_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # ------------------------------------------------------------------
    # Mutation
    # ------------------------------------------------------------------

    def add_case(self, constructor: ConstructorSpec) -> None:
        """Add a constructor to this fold if not already present.

        Deduplication is by constructor *name*; two specs with the same
        name are considered the same constructor regardless of their
        ``spec_id`` values.

        Parameters
        ----------
        constructor:
            The :class:`ConstructorSpec` to register.
        """
        existing_names = {c.name for c in self.constructors}
        if constructor.name not in existing_names:
            self.constructors.append(constructor)

    # ------------------------------------------------------------------
    # SMT-LIB 2 code generation
    # ------------------------------------------------------------------

    def build_fold_function(self, case_exprs: dict[str, str]) -> str:
        """Generate an SMT-LIB 2 ``define-fun`` that realizes this fold.

        The generated function takes a single argument ``x`` of sort
        ``sort_name`` and returns a value of sort ``result_sort`` by
        dispatching on ``x``'s outermost constructor using a nested
        ``ite`` chain.

        Parameters
        ----------
        case_exprs:
            Mapping from constructor name to the SMT-LIB 2 expression
            that should be returned for that constructor.  Missing
            constructors default to ``"undefined"`` (a free constant).

        Returns
        -------
        str
            A multi-line SMT-LIB 2 ``(define-fun …)`` definition.
        """
        fold_name = f"fold_{self.sort_name}_{self.fold_id[:8]}"
        match_body = self.build_match_expression("x", case_exprs)
        lines = [
            f"; Fold over algebraic sort {self.sort_name}",
            f"(define-fun {fold_name}",
            f"  ((x {self.sort_name}))",
            f"  {self.result_sort}",
            f"  {match_body})",
        ]
        return "\n".join(lines)

    def build_induction_scheme(self) -> str:
        """Emit a multi-line SMT-LIB 2 comment describing the induction scheme.

        The induction scheme for a simple inductive ADT states that a
        property ``P`` holds for all values of the sort if it holds for
        each constructor case (with the induction hypothesis applied to
        recursive sub-terms).

        Returns
        -------
        str
            A block comment string suitable for inclusion in a ``.smt2``
            file as documentation.
        """
        lines: list[str] = [
            f"; ── Induction scheme for sort: {self.sort_name} ──────────────────",
            f"; To prove (forall ((x {self.sort_name})) (P x)), it suffices to show:",
        ]
        for spec in self.constructors:
            if spec.arity() == 0:
                lines.append(f";   Base case: (P ({spec.name}))")
            else:
                hyps = " ".join(
                    f"(P ({spec.accessor_name(i)} x))"
                    for i in range(spec.arity())
                    if spec.field_sorts[i] == self.sort_name  # only recursive fields
                )
                if hyps:
                    lines.append(
                        f";   Inductive case for {spec.name}: "
                        f"assuming {hyps}, prove (P ({spec.name} …))"
                    )
                else:
                    lines.append(
                        f";   Constructor case for {spec.name}: prove (P ({spec.name} …))"
                    )
        lines.append("; ─────────────────────────────────────────────────────────────")
        return "\n".join(lines)

    def build_match_expression(self, term: str, cases: dict[str, str]) -> str:
        """Build a nested SMT-LIB 2 ``ite`` chain for constructor dispatch.

        The chain has the form::

            (ite (is-c1 term) e1
              (ite (is-c2 term) e2
                …
                  eN))

        where ``eN`` is the last case (used without a guard to ensure the
        expression is always defined).

        Parameters
        ----------
        term:
            The SMT-LIB 2 term being dispatched on.
        cases:
            Mapping from constructor name to result expression.

        Returns
        -------
        str
            Nested ``ite`` expression as a string.
        """
        if not self.constructors:
            return "undefined"

        # Build the chain from the inside out (right-to-left).
        # The last constructor acts as the default (else) branch.
        specs = self.constructors
        # Innermost (last) case — used as the default else.
        last = specs[-1]
        result = cases.get(last.name, "undefined")

        # Wrap each preceding constructor in an ite.
        for spec in reversed(specs[:-1]):
            cond = f"(is-{spec.name} {term})"
            then_expr = cases.get(spec.name, "undefined")
            result = f"(ite {cond} {then_expr} {result})"

        # If there is only one constructor, return its expression directly.
        if len(specs) == 1:
            result = cases.get(specs[0].name, "undefined")

        return result

    def validate_cases(self, cases: dict[str, str]) -> list[str]:
        """Return error messages for any constructors missing from *cases*.

        Parameters
        ----------
        cases:
            The case-expression mapping to validate.

        Returns
        -------
        list[str]
            One error string per missing constructor.  Empty when all
            constructors are covered.
        """
        errors: list[str] = []
        for spec in self.constructors:
            if spec.name not in cases:
                errors.append(
                    f"AlgebraicFold: missing case expression for constructor "
                    f"'{spec.name}' in sort '{self.sort_name}'."
                )
        return errors

    def to_recursive_definition(self, func_name: str, cases: dict[str, str]) -> str:
        """Emit a named recursive-style ``define-fun`` for this fold.

        Unlike :meth:`build_fold_function` (which auto-generates a name),
        this method uses the caller-supplied *func_name* directly.

        Parameters
        ----------
        func_name:
            The SMT-LIB 2 function identifier to declare.
        cases:
            Per-constructor case expressions.

        Returns
        -------
        str
            A ``(define-fun …)`` definition string.
        """
        match_expr = self.build_match_expression("x", cases)
        return (
            f"(define-fun {func_name}\n"
            f"  ((x {self.sort_name}))\n"
            f"  {self.result_sort}\n"
            f"  {match_expr})"
        )


# ---------------------------------------------------------------------------
# §31.3.4 — SurfaceProjection
# ---------------------------------------------------------------------------


@dataclass
class SurfaceProjection:
    """A single projection (accessor) function from an algebraic sort.

    A :class:`SurfaceProjection` represents the accessor function
    :math:`\\pi^{(i)}_j : T \\to A^{(i)}_j` that extracts the *j*-th field
    of a value built by the *i*-th constructor.

    Because SMT-LIB 2 accessors are *total* (they return an unspecified
    but type-correct value when applied to the wrong constructor), this
    class tracks whether the projection is safe to apply unconditionally
    (``TOTAL``), requires a recognizer guard (``PARTIAL``), or has been
    explicitly totalized with a supplied guard condition (``CONDITIONAL``).

    Parameters
    ----------
    source_sort:
        The ADT sort being projected from.
    target_sort:
        The sort of the field value extracted.
    projection_name:
        The SMT-LIB 2 accessor function name.
    mode:
        :class:`ProjectionMode` indicating totality.
    projection_id:
        UUID string uniquely identifying this projection instance.
    guard_condition:
        An SMT-LIB 2 Boolean guard that must hold before applying the
        projection (relevant only for ``CONDITIONAL`` mode).
    """

    source_sort: str
    target_sort: str
    projection_name: str
    mode: ProjectionMode = ProjectionMode.TOTAL
    projection_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    guard_condition: str = "true"

    # ------------------------------------------------------------------
    # Application
    # ------------------------------------------------------------------

    def apply(self, term: str) -> str:
        """Apply this projection to an SMT-LIB 2 term.

        Parameters
        ----------
        term:
            The term of sort ``source_sort`` to project from.

        Returns
        -------
        str
            The application expression, e.g. ``"(head x)"``.
        """
        return f"({self.projection_name} {term})"

    def is_total_projection(self) -> bool:
        """Return ``True`` iff this projection can be applied without a guard.

        Returns
        -------
        bool
            ``True`` iff ``self.mode == ProjectionMode.TOTAL``.
        """
        return self.mode == ProjectionMode.TOTAL

    def compose_with(self, other: SurfaceProjection) -> SurfaceProjection:
        """Compose this projection with *other*, yielding a new projection.

        The composed projection applies ``self`` first, then ``other``.
        The resulting mode is ``PARTIAL`` if either operand is partial;
        otherwise it is ``TOTAL``.

        Parameters
        ----------
        other:
            The projection to apply after ``self``.

        Returns
        -------
        SurfaceProjection
            A fresh :class:`SurfaceProjection` representing the composition.
        """
        composed_name = f"{self.projection_name}_then_{other.projection_name}"
        composed_mode = (
            ProjectionMode.PARTIAL
            if self.mode == ProjectionMode.PARTIAL
            or other.mode == ProjectionMode.PARTIAL
            else ProjectionMode.TOTAL
        )
        return SurfaceProjection(
            source_sort=self.source_sort,
            target_sort=other.target_sort,
            projection_name=composed_name,
            mode=composed_mode,
            projection_id=str(uuid.uuid4()),
            guard_condition="true",
        )

    def to_smt2_definition(self, body: str) -> str:
        """Emit an SMT-LIB 2 ``define-fun`` for this projection with a given body.

        Parameters
        ----------
        body:
            The body expression; this will be used verbatim as the
            return expression of the define-fun.

        Returns
        -------
        str
            A complete ``(define-fun …)`` definition.
        """
        return (
            f"(define-fun {self.projection_name}"
            f" ((x {self.source_sort}))"
            f" {self.target_sort}"
            f" {body})"
        )

    def partial_to_total(self, default: str) -> SurfaceProjection:
        """Totalize a partial projection by supplying a default value.

        When a partial projection is applied outside its valid domain, the
        totalized version returns *default* instead of an unspecified
        value.

        Parameters
        ----------
        default:
            An SMT-LIB 2 expression of sort ``target_sort`` to use as the
            default value.

        Returns
        -------
        SurfaceProjection
            A new ``TOTAL`` projection whose name is annotated with
            ``_totalized``.
        """
        totalized_name = f"{self.projection_name}_totalized"
        return SurfaceProjection(
            source_sort=self.source_sort,
            target_sort=self.target_sort,
            projection_name=totalized_name,
            mode=ProjectionMode.TOTAL,
            projection_id=str(uuid.uuid4()),
            guard_condition=default,  # store default as guard_condition for reference
        )

    def copilot_suggest_guard(self, sort_info: dict[str, Any]) -> str:
        """Suggest a recognizer guard for this projection based on sort metadata.

        Inspects *sort_info* for a ``"constructors"`` key containing
        constructor names, and builds an ``(or …)`` of recognizer
        applications that scope the projection to valid constructors.

        Parameters
        ----------
        sort_info:
            A dictionary that may contain ``"constructors": list[str]``
            listing all constructor names for ``source_sort``.

        Returns
        -------
        str
            An SMT-LIB 2 Boolean expression, e.g.
            ``"(or (is-cons x) (is-pair x))"``.  Falls back to ``"true"``
            when no constructor information is available.
        """
        constructors: list[str] = sort_info.get("constructors", [])
        if not constructors:
            # No constructor information available; use trivially-true guard.
            return "true"
        if len(constructors) == 1:
            # Single constructor — recognizer is always true; guard is trivial.
            return f"(is-{constructors[0]} x)"
        # Build an or-expression over all recognizers.
        recognizer_apps = " ".join(f"(is-{c} x)" for c in constructors)
        return f"(or {recognizer_apps})"


# ---------------------------------------------------------------------------
# §31.3 — Module-level factory functions
# ---------------------------------------------------------------------------


def build_constructor_spec(
    name: str,
    fields: list[tuple[str, str]],
) -> ConstructorSpec:
    """Build a :class:`ConstructorSpec` from a list of ``(field_name, sort)`` pairs.

    This convenience function is the primary entry point for constructing
    :class:`ConstructorSpec` instances when the fields are supplied as
    a list of name-sort pairs rather than separate tuples.

    Parameters
    ----------
    name:
        Constructor identifier.
    fields:
        Ordered list of ``(field_name, sort_name)`` pairs.

    Returns
    -------
    ConstructorSpec
        A freshly created spec instance.

    Examples
    --------
    >>> spec = build_constructor_spec("cons", [("head", "Int"), ("tail", "List_Int")])
    >>> spec.arity()
    2
    >>> spec.field_at(0)
    ('head', 'Int')
    """
    if not fields:
        return ConstructorSpec(name=name)
    field_names = tuple(f[0] for f in fields)
    field_sorts = tuple(f[1] for f in fields)
    return ConstructorSpec(name=name, field_sorts=field_sorts, field_names=field_names)


def declare_algebraic_surface(
    sort_name: str,
    specs: list[ConstructorSpec],
) -> str:
    """Produce a complete SMT-LIB 2 ``declare-datatypes`` command for *sort_name*.

    The resulting declaration is well-formed for a single non-parametric
    algebraic sort with the given constructors.

    Parameters
    ----------
    sort_name:
        The sort identifier to declare.
    specs:
        All constructors for the sort, in declaration order.

    Returns
    -------
    str
        A ``(declare-datatypes …)`` command string.

    Examples
    --------
    >>> nil = ConstructorSpec(name="nil")
    >>> cons = build_constructor_spec("cons", [("head", "Int"), ("tail", "List_Int")])
    >>> print(declare_algebraic_surface("List_Int", [nil, cons]))
    (declare-datatypes ((List_Int 0)) (((nil) (cons (head Int) (tail List_Int)))))
    """
    constructor_clauses = " ".join(spec.to_smt2_constructor() for spec in specs)
    return f"(declare-datatypes (({sort_name} 0)) (({constructor_clauses})))"


def fold_over_surface(
    surface_sort: str,
    fold: AlgebraicFold,
    term: str,
    cases: dict[str, str],
) -> str:
    """Compute the SMT-LIB 2 fold expression for *term* over *surface_sort*.

    Delegates to :meth:`AlgebraicFold.build_match_expression` after
    verifying that *fold* targets the correct sort.

    Parameters
    ----------
    surface_sort:
        The sort name; used for a consistency assertion.
    fold:
        The :class:`AlgebraicFold` whose match expression is used.
    term:
        The SMT-LIB 2 term being folded over.
    cases:
        Per-constructor case expressions.

    Returns
    -------
    str
        The nested ``ite`` expression for the fold.

    Raises
    ------
    ValueError
        When ``fold.sort_name`` does not match ``surface_sort``.
    """
    if fold.sort_name != surface_sort:
        raise ValueError(
            f"fold_over_surface: fold is for sort '{fold.sort_name}' "
            f"but surface_sort is '{surface_sort}'."
        )
    return fold.build_match_expression(term, cases)


def project_surface_field(
    sort_name: str,
    constructor: str,
    field_idx: int,
    term: str,
) -> str:
    """Produce the SMT-LIB 2 expression that projects field *field_idx*.

    This is a low-level helper that emits the accessor application
    following the JuGeo naming convention ``{constructor}-field-{field_idx}``.

    Parameters
    ----------
    sort_name:
        The ADT sort name (used for documentation / error messages).
    constructor:
        The constructor name whose field is being projected.
    field_idx:
        Zero-based field index.
    term:
        The SMT-LIB 2 term of sort *sort_name* to project from.

    Returns
    -------
    str
        An accessor application expression, e.g. ``"(cons-field-0 x)"``.
    """
    accessor = f"{constructor}-field-{field_idx}"
    return f"({accessor} {term})"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

__all__ = [
    "ConstructorArity",
    "SurfaceKind",
    "ProjectionMode",
    "ConstructorSpec",
    "RecognizerPredicate",
    "AlgebraicFold",
    "SurfaceProjection",
    "build_constructor_spec",
    "declare_algebraic_surface",
    "fold_over_surface",
    "project_surface_field",
]
