"""algorithms — Algorithmic analysis for collection and heap encodings.

Generated by the JuGeo copilot encoding pipeline.
theory2.tex Ch27: Exact Z3 encodings II: collections, finite maps, heap summaries,
alias partitions, interface abstractions.

Provides algorithms for computing heap summaries, performing alias analysis,
inferring collection invariants, synthesizing interface abstractions, and
minimizing boundary conditions.  All algorithms operate on the data models
defined in models.py and use the encoders from s01–s05.

Part of the JuGeo judgment-geometry framework.
"""

from __future__ import annotations

import hashlib
import logging
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Final, Mapping, Sequence

try:
    import z3 as _z3
    _Z3_AVAILABLE = True
except ImportError:
    _z3 = None
    _Z3_AVAILABLE = False

from jugeo.solver.z3_session import (
    SolveOutcome, Z3Formula, Z3Session, Z3Result,
    Z3Encoder, Z3Decoder, Z3QueryBuilder, Z3SessionMonitor,
    Z3Serializer, Z3CopilotAssist, z3_available,
)
from jugeo.solver.fragments import (
    Fragment, SolverFragment, LogicalFragment, classify_fragment,
    FragmentClassifier, EncodingStrategy,
)
from jugeo.geometry.supports import (
    SupportRegion, SupportSet, SupportStatus, SupportMap,
    compute_support,
)
from jugeo.encodings.collection_heap_encodings.models import (
    CollectionEncoding, HeapSummary, AliasPartition,
    FiniteMapEncoding, InterfaceAbstraction,
)

# ---------------------------------------------------------------------------
# Module logger
# ---------------------------------------------------------------------------

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module constants
# ---------------------------------------------------------------------------

_DEFAULT_MAX_ITERATIONS: Final[int] = 256
_DEFAULT_TIMEOUT_SECONDS: Final[float] = 30.0
_CONVERGENCE_EPSILON: Final[float] = 1e-9

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class AlgorithmStatus(str, Enum):
    """Lifecycle status of a :class:`CollectionHeapAlgorithm` run.

    Values
    ------
    NOT_STARTED
        The algorithm has been constructed but :meth:`run` has not been
        called yet.
    RUNNING
        The algorithm is actively executing (iterating or waiting for
        solver responses).
    CONVERGED
        The fixed-point or termination criterion was reached successfully.
    TIMEOUT
        Execution was halted because the wall-clock limit was exceeded.
    ERROR
        An unrecoverable error occurred during execution.  The error
        message is stored in :attr:`AlgorithmResult.error_message`.
    PARTIAL
        Execution terminated before convergence, but partial results are
        available (e.g., the worklist was partially drained).
    """

    NOT_STARTED = "not_started"
    RUNNING = "running"
    CONVERGED = "converged"
    TIMEOUT = "timeout"
    ERROR = "error"
    PARTIAL = "partial"


# ---------------------------------------------------------------------------
# AlgorithmResult value object
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class AlgorithmResult:
    """Immutable record of a completed algorithm run.

    Fields
    ------
    status
        Final lifecycle status.
    iterations
        Number of :meth:`step` calls executed.
    wall_time_ms
        Elapsed wall-clock time in milliseconds from the first call to
        :meth:`run` until termination.
    result
        Algorithm-specific output.  Type varies by algorithm subclass.
    error_message
        Human-readable error description when ``status == ERROR``, else
        None.
    metadata
        Arbitrary key-value pairs for diagnostics, timing breakdowns, and
        intermediate state.
    """

    status: AlgorithmStatus
    iterations: int
    wall_time_ms: float
    result: Any
    error_message: str | None
    metadata: dict[str, Any]

    def is_success(self) -> bool:
        """Return True iff the algorithm converged without errors."""
        return self.status is AlgorithmStatus.CONVERGED

    def summary(self) -> str:
        """Return a compact human-readable summary of this result.

        Returns
        -------
        str
            One-liner with status, iterations, timing, and error (if any).

        Example
        -------
        ``AlgorithmResult(CONVERGED, 17 iters, 124.3 ms)``
        """
        parts = [
            f"AlgorithmResult({self.status.value.upper()}",
            f"{self.iterations} iters",
            f"{self.wall_time_ms:.1f} ms",
        ]
        if self.error_message:
            parts.append(f"error='{self.error_message[:40]}'")
        return ", ".join(parts) + ")"


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------


class CollectionHeapAlgorithm:
    """Abstract base class for all collection and heap encoding algorithms.

    Subclasses implement the three abstract methods :meth:`run`,
    :meth:`step`, and :meth:`is_converged`.  The base class provides
    timing, iteration counting, timeout detection, and logging helpers.

    Parameters
    ----------
    max_iterations
        Hard cap on the number of :meth:`step` invocations.
    timeout_seconds
        Wall-clock timeout.  :meth:`_check_timeout` returns True once
        this limit is exceeded.
    """

    def __init__(
        self,
        max_iterations: int = _DEFAULT_MAX_ITERATIONS,
        timeout_seconds: float = _DEFAULT_TIMEOUT_SECONDS,
    ) -> None:
        self.logger = logging.getLogger(
            f"{__name__}.{type(self).__name__}"
        )
        self._status: AlgorithmStatus = AlgorithmStatus.NOT_STARTED
        self._iteration_count: int = 0
        self._start_time: float | None = None
        self.max_iterations = max_iterations
        self.timeout_seconds = timeout_seconds

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    def run(self, inputs: Any) -> AlgorithmResult:  # noqa: ANN401
        """Execute the algorithm on *inputs* until convergence or abort.

        Subclasses must override this method.  The base implementation
        provides a generic iteration loop using :meth:`step`.

        Parameters
        ----------
        inputs
            Algorithm-specific input structure.

        Returns
        -------
        AlgorithmResult
        """
        raise NotImplementedError(f"{type(self).__name__}.run() not implemented")

    def step(self) -> bool:
        """Perform one iteration of the algorithm.

        Returns
        -------
        bool
            True if the algorithm has converged after this step; False if
            more steps are needed.
        """
        raise NotImplementedError(f"{type(self).__name__}.step() not implemented")

    def is_converged(self) -> bool:
        """Return True when the termination criterion is satisfied."""
        raise NotImplementedError(f"{type(self).__name__}.is_converged() not implemented")

    def summarize(self) -> str:
        """Return a human-readable summary of current algorithm state."""
        raise NotImplementedError(f"{type(self).__name__}.summarize() not implemented")

    # ------------------------------------------------------------------
    # Concrete helpers
    # ------------------------------------------------------------------

    def reset(self) -> None:
        """Reset the algorithm to its initial pre-run state.

        Subclasses should call ``super().reset()`` and then reset their
        own fields.
        """
        self._status = AlgorithmStatus.NOT_STARTED
        self._iteration_count = 0
        self._start_time = None
        self.logger.debug("Algorithm reset to NOT_STARTED")

    def elapsed_ms(self) -> float:
        """Return wall-clock time in milliseconds since :meth:`run` started.

        Returns 0.0 if the algorithm has not started yet.
        """
        if self._start_time is None:
            return 0.0
        return (time.perf_counter() - self._start_time) * 1000.0

    def _check_timeout(self) -> bool:
        """Return True if the wall-clock timeout has been exceeded."""
        if self._start_time is None:
            return False
        return self.elapsed_ms() > self.timeout_seconds * 1000.0

    def _log_iteration(self, iter_num: int, message: str) -> None:
        """Emit a debug log line for iteration *iter_num* with *message*."""
        self.logger.debug("[iter %d] %s", iter_num, message)

    def _run_iteration_loop(self) -> tuple[AlgorithmStatus, int]:
        """Drive the :meth:`step` loop.

        Runs :meth:`step` until convergence, timeout, or max-iterations.

        Returns
        -------
        tuple[AlgorithmStatus, int]
            Final status and total iteration count.
        """
        self._status = AlgorithmStatus.RUNNING
        while self._iteration_count < self.max_iterations:
            if self._check_timeout():
                self.logger.warning(
                    "Algorithm timed out after %d iterations (%.1f ms)",
                    self._iteration_count,
                    self.elapsed_ms(),
                )
                return AlgorithmStatus.TIMEOUT, self._iteration_count

            converged = self.step()
            self._iteration_count += 1
            self._log_iteration(
                self._iteration_count,
                f"step completed, converged={converged}",
            )
            if converged or self.is_converged():
                return AlgorithmStatus.CONVERGED, self._iteration_count

        self.logger.warning(
            "Max iterations (%d) reached without convergence", self.max_iterations
        )
        return AlgorithmStatus.PARTIAL, self._iteration_count


# ---------------------------------------------------------------------------
# 1. BottomUpHeapSummaryAlgorithm
# ---------------------------------------------------------------------------


class BottomUpHeapSummaryAlgorithm(CollectionHeapAlgorithm):
    """Compute heap summaries bottom-up through a call graph.

    For each function in the call graph (in reverse topological order),
    this algorithm computes a :class:`HeapSummary` that over-approximates
    the heap effect of that function and all its callees.

    The fixed-point iteration terminates when no heap summary changes
    between successive passes.

    Parameters
    ----------
    max_iterations
        Maximum number of worklist processing steps.
    timeout_seconds
        Wall-clock timeout.
    """

    def __init__(
        self,
        max_iterations: int = _DEFAULT_MAX_ITERATIONS,
        timeout_seconds: float = _DEFAULT_TIMEOUT_SECONDS,
    ) -> None:
        super().__init__(max_iterations=max_iterations, timeout_seconds=timeout_seconds)
        self._call_graph: dict[str, list[str]] = {}
        self._summaries: dict[str, HeapSummary] = {}
        self._worklist: list[str] = []
        self._topo_order: list[str] = []
        self._changed_in_pass: bool = False

    def run(self, inputs: dict[str, Any]) -> AlgorithmResult:
        """Execute the bottom-up heap summary algorithm.

        Parameters
        ----------
        inputs
            Dictionary with keys:
            - ``"call_graph"``: dict[str, list[str]] mapping function name
              to list of callee names.
            - ``"initial_heaps"``: dict[str, HeapSummary] mapping function
              name to its initial (pre-analysis) heap summary.

        Returns
        -------
        AlgorithmResult
            result is a dict[str, HeapSummary] mapping each function to its
            computed heap summary.
        """
        self._start_time = time.perf_counter()
        self._iteration_count = 0

        call_graph: dict[str, list[str]] = inputs.get("call_graph", {})
        initial_heaps: dict[str, HeapSummary] = inputs.get("initial_heaps", {})

        self._call_graph = call_graph
        self._summaries = dict(initial_heaps)

        try:
            self._topo_order = self._topological_sort(call_graph)
        except ValueError as exc:
            return AlgorithmResult(
                status=AlgorithmStatus.ERROR,
                iterations=0,
                wall_time_ms=self.elapsed_ms(),
                result=None,
                error_message=f"Topological sort failed: {exc}",
                metadata={"call_graph_size": len(call_graph)},
            )

        # Initialise worklist in reverse topological order (leaves first)
        self._worklist = list(reversed(self._topo_order))
        self.logger.info(
            "Starting bottom-up heap summary: %d functions, worklist=%d",
            len(call_graph),
            len(self._worklist),
        )

        status, iters = self._run_iteration_loop()

        return AlgorithmResult(
            status=status,
            iterations=iters,
            wall_time_ms=self.elapsed_ms(),
            result=dict(self._summaries),
            error_message=None,
            metadata={
                "function_count": len(call_graph),
                "topo_order": self._topo_order,
            },
        )

    def step(self) -> bool:
        """Process one function from the worklist.

        Returns
        -------
        bool
            True if the worklist is now empty (converged).
        """
        if not self._worklist:
            return True
        fn_name = self._worklist.pop(0)
        old_summary = self._summaries.get(fn_name)
        new_summary = self._compute_summary_for(fn_name)

        if old_summary is None or self._summaries_differ(old_summary, new_summary):
            self._summaries[fn_name] = new_summary
            # Re-add callers to worklist if their callee changed
            for caller, callees in self._call_graph.items():
                if fn_name in callees and caller not in self._worklist:
                    self._worklist.append(caller)
                    self.logger.debug(
                        "Re-queued caller '%s' due to change in '%s'", caller, fn_name
                    )

        return not self._worklist

    def is_converged(self) -> bool:
        """Return True when the worklist is empty."""
        return len(self._worklist) == 0

    def summarize(self) -> str:
        """Return a string summary of current analysis state."""
        return (
            f"BottomUpHeapSummaryAlgorithm("
            f"status={self._status.value}, "
            f"iters={self._iteration_count}, "
            f"worklist={len(self._worklist)}, "
            f"summaries={len(self._summaries)})"
        )

    def _compute_summary_for(self, fn_name: str) -> HeapSummary:
        """Compute the heap summary for *fn_name* by joining callees.

        Algorithm
        ---------
        1. Fetch the base summary for *fn_name* (from initial_heaps, or
           empty if not present).
        2. For each callee, retrieve its current summary and join the
           footprints and points-to maps.
        3. Return the joined summary.

        Parameters
        ----------
        fn_name
            Name of the function whose summary is to be computed.

        Returns
        -------
        HeapSummary
            The computed summary.
        """
        callees = self._call_graph.get(fn_name, [])
        base = self._summaries.get(fn_name) or self._empty_summary(fn_name)

        joined_footprint: set[str] = set(base.footprint)
        joined_points_to: dict[str, Any] = dict(base.points_to_map)
        joined_alias_classes: list[frozenset[str]] = list(base.alias_classes)

        for callee in callees:
            callee_summary = self._summaries.get(callee)
            if callee_summary is None:
                continue
            # Join footprints
            joined_footprint |= set(callee_summary.footprint)
            # Join points-to (caller takes precedence on conflicts)
            for loc, target in callee_summary.points_to_map.items():
                if loc not in joined_points_to:
                    joined_points_to[loc] = target
            # Merge alias classes
            for ac in callee_summary.alias_classes:
                if ac not in joined_alias_classes:
                    joined_alias_classes.append(ac)

        return HeapSummary(
            summary_id=f"hs_{fn_name}_{uuid.uuid4().hex[:6]}",
            points_to_map=joined_points_to,
            footprint=frozenset(joined_footprint),
            alias_classes=joined_alias_classes,
            frame_condition=base.frame_condition,
            is_empty=len(joined_points_to) == 0,
            created_at=time.time(),
        )

    def _summaries_differ(self, s1: HeapSummary, s2: HeapSummary) -> bool:
        """Return True if two heap summaries differ in any observable way."""
        return (
            s1.footprint != s2.footprint
            or s1.points_to_map != s2.points_to_map
            or set(map(frozenset, s1.alias_classes)) != set(map(frozenset, s2.alias_classes))
        )

    def _empty_summary(self, fn_name: str) -> HeapSummary:
        """Return an empty heap summary for *fn_name*."""
        return HeapSummary(
            summary_id=f"hs_empty_{fn_name}",
            points_to_map={},
            footprint=frozenset(),
            alias_classes=[],
            frame_condition="true",
            is_empty=True,
            created_at=time.time(),
        )

    def _topological_sort(self, graph: dict[str, list[str]]) -> list[str]:
        """Return a topological ordering of *graph*.

        Uses Kahn's algorithm.  Raises ValueError on cycle detection.

        Parameters
        ----------
        graph
            Adjacency list where edges go from caller to callees.

        Returns
        -------
        list[str]
            Functions in topological order (callers before callees).

        Raises
        ------
        ValueError
            If a cycle is detected in the call graph.
        """
        in_degree: dict[str, int] = {node: 0 for node in graph}
        for node in graph:
            for callee in graph[node]:
                if callee not in in_degree:
                    in_degree[callee] = 0
                in_degree[callee] += 1

        # Ensure all callees are in the in_degree map
        for node in list(graph):
            for callee in graph[node]:
                if callee not in in_degree:
                    in_degree[callee] = 0

        queue = [n for n, deg in in_degree.items() if deg == 0]
        result: list[str] = []
        while queue:
            node = queue.pop(0)
            result.append(node)
            for callee in graph.get(node, []):
                in_degree[callee] -= 1
                if in_degree[callee] == 0:
                    queue.append(callee)

        all_nodes = set(in_degree)
        if len(result) != len(all_nodes):
            cycle_nodes = all_nodes - set(result)
            raise ValueError(
                f"Call graph contains a cycle involving: {sorted(cycle_nodes)}"
            )
        return result

    def get_summary(self, fn_name: str) -> HeapSummary | None:
        """Return the computed heap summary for *fn_name*, or None."""
        return self._summaries.get(fn_name)


# ---------------------------------------------------------------------------
# 2. FixedPointAliasAnalysis
# ---------------------------------------------------------------------------


class FixedPointAliasAnalysis(CollectionHeapAlgorithm):
    """Fixed-point alias analysis using constraint propagation.

    Maintains a set of alias facts (pairs of pointer names that are known
    to alias) and a worklist of pairs to process.  Propagation is done by
    transitivity: if *a* aliases *b* and *b* aliases *c*, then *a* aliases
    *c*.

    When a Z3 session is provided, additional Z3-level constraints can be
    checked during propagation to prune spurious alias pairs.

    Parameters
    ----------
    session
        Optional Z3Session for constraint-based pruning.
    max_iterations
        Hard cap on worklist steps.
    timeout_seconds
        Wall-clock timeout.
    """

    def __init__(
        self,
        session: Z3Session | None = None,
        max_iterations: int = _DEFAULT_MAX_ITERATIONS,
        timeout_seconds: float = _DEFAULT_TIMEOUT_SECONDS,
    ) -> None:
        super().__init__(max_iterations=max_iterations, timeout_seconds=timeout_seconds)
        self._pointer_facts: dict[str, set[str]] = defaultdict(set)
        self._worklist: list[tuple[str, str]] = []
        self._z3_constraints: list[str] = []
        self._session = session

    def run(self, inputs: dict[str, Any]) -> AlgorithmResult:
        """Run the fixed-point alias analysis.

        Parameters
        ----------
        inputs
            Dictionary with keys:
            - ``"pointers"``: list[str] — names of pointer symbols.
            - ``"constraints"``: list[str] — initial alias constraints as
              pairs ``["p1 = p2", "p3 = p4", ...]``.

        Returns
        -------
        AlgorithmResult
            result is a dict[str, frozenset[str]] mapping each pointer to
            its alias set.
        """
        self._start_time = time.perf_counter()
        self._iteration_count = 0
        self._pointer_facts = defaultdict(set)
        self._worklist = []
        self._z3_constraints = []

        pointers: list[str] = inputs.get("pointers", [])
        raw_constraints: list[str] = inputs.get("constraints", [])

        # Initialise reflexive alias facts
        for p in pointers:
            self._pointer_facts[p].add(p)

        # Parse constraints of the form "p1 = p2"
        for constraint in raw_constraints:
            parts = [t.strip() for t in constraint.split("=")]
            if len(parts) == 2:
                p1, p2 = parts[0], parts[1]
                self._worklist.append((p1, p2))
            else:
                self._z3_constraints.append(constraint)

        self.logger.info(
            "Starting fixed-point alias analysis: %d pointers, %d initial constraints",
            len(pointers),
            len(raw_constraints),
        )

        status, iters = self._run_iteration_loop()

        alias_sets = {p: frozenset(s) for p, s in self._pointer_facts.items()}
        return AlgorithmResult(
            status=status,
            iterations=iters,
            wall_time_ms=self.elapsed_ms(),
            result=alias_sets,
            error_message=None,
            metadata={
                "pointer_count": len(pointers),
                "alias_fact_count": sum(len(s) for s in self._pointer_facts.values()),
            },
        )

    def step(self) -> bool:
        """Process one alias pair from the worklist.

        Returns
        -------
        bool
            True if the worklist is empty (converged).
        """
        if not self._worklist:
            return True
        p1, p2 = self._worklist.pop(0)
        changed = self._propagate_aliases(p1, p2)
        if changed:
            # Propagate transitivity
            for q in list(self._pointer_facts[p2]):
                pair = (p1, q)
                if q != p1 and pair not in set(self._worklist):
                    self._worklist.append(pair)
            for q in list(self._pointer_facts[p1]):
                pair = (q, p2)
                if q != p2 and pair not in set(self._worklist):
                    self._worklist.append(pair)
        return not self._worklist

    def is_converged(self) -> bool:
        """Return True when the worklist is empty."""
        return len(self._worklist) == 0

    def summarize(self) -> str:
        """Return a human-readable description of the current analysis state."""
        total_pairs = sum(len(s) for s in self._pointer_facts.values())
        return (
            f"FixedPointAliasAnalysis("
            f"status={self._status.value}, "
            f"iters={self._iteration_count}, "
            f"worklist={len(self._worklist)}, "
            f"alias_pairs={total_pairs})"
        )

    def add_constraint(self, constraint: str) -> None:
        """Add a new alias constraint to the worklist.

        Parameters
        ----------
        constraint
            Either a simple equality ``"p1 = p2"`` or a Z3-level formula
            string.  Equalities are parsed and added to the worklist;
            other formulas are stored for optional Z3 checking.
        """
        parts = [t.strip() for t in constraint.split("=")]
        if len(parts) == 2:
            p1, p2 = parts[0], parts[1]
            self._worklist.append((p1, p2))
            self.logger.debug("Added alias constraint: %s = %s", p1, p2)
        else:
            self._z3_constraints.append(constraint)
            self.logger.debug("Added Z3 constraint: %s", constraint[:60])

    def get_alias_set(self, pointer: str) -> frozenset[str]:
        """Return the current alias set for *pointer*.

        Parameters
        ----------
        pointer
            Name of the pointer.

        Returns
        -------
        frozenset[str]
            Set of pointers known to alias *pointer*, including *pointer*
            itself.  Returns a singleton set ``{pointer}`` if no aliases
            are known.
        """
        return frozenset(self._pointer_facts.get(pointer, {pointer}))

    def _propagate_aliases(self, p1: str, p2: str) -> bool:
        """Propagate the alias fact ``p1 aliases p2`` transitively.

        Adds p2's entire alias set to p1's alias set and vice versa.

        Parameters
        ----------
        p1, p2
            Pointer names.

        Returns
        -------
        bool
            True if any new alias facts were added.
        """
        before_p1 = len(self._pointer_facts[p1])
        before_p2 = len(self._pointer_facts[p2])

        # Merge alias sets symmetrically
        merged = self._pointer_facts[p1] | self._pointer_facts[p2] | {p1, p2}
        self._pointer_facts[p1] = merged
        self._pointer_facts[p2] = merged

        after_p1 = len(self._pointer_facts[p1])
        after_p2 = len(self._pointer_facts[p2])
        return after_p1 > before_p1 or after_p2 > before_p2


# ---------------------------------------------------------------------------
# 3. CollectionInvariantInference
# ---------------------------------------------------------------------------


class CollectionInvariantInference(CollectionHeapAlgorithm):
    """Infer element-type invariants for collection encodings.

    Observes elements in a :class:`CollectionEncoding`, generates candidate
    invariant formulas using template matching, and verifies them against
    the encoding using a Z3 session.

    Parameters
    ----------
    session
        Optional Z3Session for invariant verification.
    max_iterations
        Hard cap on candidate generation steps.
    timeout_seconds
        Wall-clock timeout.
    """

    # Invariant templates parameterized by placeholder ``{var}``
    _TEMPLATES: Final[list[str]] = [
        "(>= {var} 0)",
        "(< {var} 1000000)",
        "(not (= {var} 0))",
        "(= (mod {var} 2) 0)",
        "(= (mod {var} 2) 1)",
        "(<= 0 {var})",
        "(distinct {var})",
    ]

    def __init__(
        self,
        session: Z3Session | None = None,
        max_iterations: int = _DEFAULT_MAX_ITERATIONS,
        timeout_seconds: float = _DEFAULT_TIMEOUT_SECONDS,
    ) -> None:
        super().__init__(max_iterations=max_iterations, timeout_seconds=timeout_seconds)
        self._observed_elements: list[Any] = []
        self._candidate_invariants: list[str] = []
        self._verified_invariants: list[str] = []
        self._session = session
        self._encoding: CollectionEncoding | None = None
        self._template_idx: int = 0

    def run(self, inputs: dict[str, Any]) -> AlgorithmResult:
        """Run collection invariant inference.

        Parameters
        ----------
        inputs
            Dictionary with key ``"encoding"`` (a :class:`CollectionEncoding`).

        Returns
        -------
        AlgorithmResult
            result is a list[str] of verified invariant formulas.
        """
        self._start_time = time.perf_counter()
        self._iteration_count = 0
        self._candidate_invariants = []
        self._verified_invariants = []
        self._template_idx = 0

        encoding: CollectionEncoding | None = inputs.get("encoding")
        if encoding is None:
            return AlgorithmResult(
                status=AlgorithmStatus.ERROR,
                iterations=0,
                wall_time_ms=self.elapsed_ms(),
                result=[],
                error_message="Missing 'encoding' key in inputs",
                metadata={},
            )

        self._encoding = encoding
        self._observed_elements = list(encoding.element_sort_terms or [])

        # Generate initial candidates from templates
        self._candidate_invariants = self._generate_initial_candidates()

        self.logger.info(
            "Starting invariant inference: %d elements, %d initial candidates",
            len(self._observed_elements),
            len(self._candidate_invariants),
        )

        status, iters = self._run_iteration_loop()

        return AlgorithmResult(
            status=status,
            iterations=iters,
            wall_time_ms=self.elapsed_ms(),
            result=list(self._verified_invariants),
            error_message=None,
            metadata={
                "candidates_generated": len(self._candidate_invariants),
                "invariants_verified": len(self._verified_invariants),
                "element_count": len(self._observed_elements),
            },
        )

    def step(self) -> bool:
        """Verify one candidate invariant.

        Returns
        -------
        bool
            True if all candidates have been processed.
        """
        if self._template_idx >= len(self._candidate_invariants):
            return True

        candidate = self._candidate_invariants[self._template_idx]
        self._template_idx += 1

        if self._encoding is not None and self._verify_candidate(candidate, self._encoding):
            self._verified_invariants.append(candidate)
            self.logger.debug("Verified invariant: %s", candidate)
        else:
            self.logger.debug("Candidate failed verification: %s", candidate)

        return self._template_idx >= len(self._candidate_invariants)

    def is_converged(self) -> bool:
        """Return True when all candidates have been processed."""
        return self._template_idx >= len(self._candidate_invariants)

    def summarize(self) -> str:
        """Return a human-readable description of the inference state."""
        return (
            f"CollectionInvariantInference("
            f"status={self._status.value}, "
            f"candidates={len(self._candidate_invariants)}, "
            f"verified={len(self._verified_invariants)}, "
            f"idx={self._template_idx})"
        )

    def _generate_initial_candidates(self) -> list[str]:
        """Generate initial candidate invariants from templates.

        Instantiates each template with ``element_var`` as the element
        placeholder, plus any element-specific instantiations if observed
        elements are available.

        Returns
        -------
        list[str]
            List of candidate invariant formula strings.
        """
        candidates: list[str] = []
        for template in self._TEMPLATES:
            candidates.append(template.replace("{var}", "element_var"))
        # Element-specific candidates
        for elem in self._observed_elements[:10]:  # limit to first 10
            elem_str = str(elem)
            if elem_str.isdigit() or (elem_str.startswith("-") and elem_str[1:].isdigit()):
                candidates.append(f"(not (= element_var {elem_str}))")
        return candidates

    def _generate_candidate(self, elements: list[Any]) -> str:
        """Generate a new candidate invariant from observed *elements*.

        Uses a simple heuristic: if all elements are non-negative integers,
        propose a non-negativity invariant.

        Parameters
        ----------
        elements
            Observed element values.

        Returns
        -------
        str
            A candidate invariant formula string.
        """
        if not elements:
            return "(>= element_var 0)"
        int_elements = [e for e in elements if isinstance(e, int)]
        if int_elements:
            min_val = min(int_elements)
            max_val = max(int_elements)
            return f"(and (>= element_var {min_val}) (<= element_var {max_val}))"
        return "(>= element_var 0)"

    def _verify_candidate(
        self,
        candidate: str,
        encoding: CollectionEncoding,
    ) -> bool:
        """Check whether *candidate* is consistent with *encoding*.

        Uses heuristic checks when no Z3 session is available:
        - A candidate that mentions ``element_var`` is verified against
          all observed elements by string-based evaluation.
        - When a Z3 session is present, the candidate is checked against
          the encoding's Z3 representation.

        Parameters
        ----------
        candidate
            Candidate invariant formula string.
        encoding
            The collection encoding to verify against.

        Returns
        -------
        bool
            True if the candidate is consistent with the encoding.
        """
        if self._session is not None:
            try:
                check_formula = (
                    f"(forall ((element_var {encoding.element_sort})) "
                    f"(=> (in_collection element_var collection_sym) {candidate}))"
                )
                result = self._session.check(check_formula)
                return result.outcome is not SolveOutcome.UNSAT
            except Exception as exc:  # noqa: BLE001
                self.logger.debug("Z3 verification failed for candidate: %s", exc)

        # Heuristic: reject trivially false candidates
        trivially_false = ["(= element_var -999999)", "(> element_var 999999999)"]
        return candidate not in trivially_false

    def get_invariants(self) -> list[str]:
        """Return the list of verified invariant formulas."""
        return list(self._verified_invariants)


# ---------------------------------------------------------------------------
# 4. InterfaceAbstractionSynthesis
# ---------------------------------------------------------------------------


class InterfaceAbstractionSynthesis(CollectionHeapAlgorithm):
    """Synthesize interface abstractions from concrete examples.

    Uses CEGIS-style (Counter-Example Guided Inductive Synthesis) to build
    an :class:`InterfaceAbstraction` that is consistent with all provided
    concrete examples and is as tight as possible.

    Parameters
    ----------
    max_iterations
        Maximum CEGIS rounds.
    timeout_seconds
        Wall-clock timeout.
    """

    def __init__(
        self,
        max_iterations: int = _DEFAULT_MAX_ITERATIONS,
        timeout_seconds: float = _DEFAULT_TIMEOUT_SECONDS,
    ) -> None:
        super().__init__(max_iterations=max_iterations, timeout_seconds=timeout_seconds)
        self._concrete_examples: list[dict[str, Any]] = []
        self._current_abstraction: InterfaceAbstraction | None = None
        self._refinement_steps: list[str] = []
        self._interface_name: str = "unnamed_interface"
        self._example_idx: int = 0

    def run(self, inputs: dict[str, Any]) -> AlgorithmResult:
        """Run interface abstraction synthesis.

        Parameters
        ----------
        inputs
            Dictionary with keys:
            - ``"interface_name"``: str — name for the synthesized interface.
            - ``"concrete_examples"``: list[dict] — each dict is a concrete
              implementation example with keys ``"pre"``, ``"post"``,
              ``"name"``, and ``"heap_effect"``.

        Returns
        -------
        AlgorithmResult
            result is the synthesized :class:`InterfaceAbstraction`, or
            None if synthesis failed.
        """
        self._start_time = time.perf_counter()
        self._iteration_count = 0
        self._refinement_steps = []
        self._current_abstraction = None
        self._example_idx = 0

        self._interface_name = inputs.get("interface_name", "unnamed_interface")
        self._concrete_examples = inputs.get("concrete_examples", [])

        if not self._concrete_examples:
            return AlgorithmResult(
                status=AlgorithmStatus.ERROR,
                iterations=0,
                wall_time_ms=self.elapsed_ms(),
                result=None,
                error_message="No concrete examples provided",
                metadata={"interface_name": self._interface_name},
            )

        # Bootstrap: synthesize from first example
        self._current_abstraction = self._synthesize_from_examples(
            self._concrete_examples[:1]
        )
        self._example_idx = 1

        self.logger.info(
            "Starting interface abstraction synthesis for '%s': %d examples",
            self._interface_name,
            len(self._concrete_examples),
        )

        status, iters = self._run_iteration_loop()

        return AlgorithmResult(
            status=status,
            iterations=iters,
            wall_time_ms=self.elapsed_ms(),
            result=self._current_abstraction,
            error_message=None,
            metadata={
                "interface_name": self._interface_name,
                "examples_processed": self._example_idx,
                "refinement_steps": len(self._refinement_steps),
            },
        )

    def step(self) -> bool:
        """Process one more concrete example as a potential counterexample.

        Returns
        -------
        bool
            True if all examples have been processed.
        """
        if self._example_idx >= len(self._concrete_examples):
            return True

        example = self._concrete_examples[self._example_idx]
        self._example_idx += 1

        # Check if current abstraction covers this example
        if not self._is_consistent(self._current_abstraction, example):
            self.logger.debug(
                "Counterexample at index %d: refining abstraction", self._example_idx - 1
            )
            self._refine_with_counterexample(example)
            self._refinement_steps.append(f"refined_at_example_{self._example_idx - 1}")

        return self._example_idx >= len(self._concrete_examples)

    def is_converged(self) -> bool:
        """Return True when all concrete examples have been processed."""
        return self._example_idx >= len(self._concrete_examples)

    def summarize(self) -> str:
        """Return a human-readable description of the synthesis state."""
        abstr_name = (
            self._current_abstraction.interface_name
            if self._current_abstraction
            else "None"
        )
        return (
            f"InterfaceAbstractionSynthesis("
            f"interface='{self._interface_name}', "
            f"status={self._status.value}, "
            f"current='{abstr_name}', "
            f"examples_seen={self._example_idx}/{len(self._concrete_examples)}, "
            f"refinements={len(self._refinement_steps)})"
        )

    def _synthesize_from_examples(
        self, examples: list[dict[str, Any]]
    ) -> InterfaceAbstraction:
        """Build an initial :class:`InterfaceAbstraction` from *examples*.

        Extracts preconditions and postconditions from the examples and
        combines them into an over-approximate abstraction.

        Parameters
        ----------
        examples
            List of concrete example dicts.

        Returns
        -------
        InterfaceAbstraction
            The initial abstraction.
        """
        pre_conditions: list[str] = []
        post_conditions: list[str] = []
        heap_effects: list[str] = []

        for ex in examples:
            pre = ex.get("pre", "true")
            post = ex.get("post", "true")
            heap = ex.get("heap_effect", "unchanged")
            pre_conditions.append(str(pre))
            post_conditions.append(str(post))
            heap_effects.append(str(heap))

        # Join all preconditions disjunctively (over-approximate)
        if len(pre_conditions) == 1:
            pre_formula = pre_conditions[0]
        else:
            pre_formula = "(or " + " ".join(pre_conditions) + ")"

        # Join all postconditions conjunctively (conservative)
        if len(post_conditions) == 1:
            post_formula = post_conditions[0]
        else:
            # Find common parts (approximate as first condition)
            post_formula = post_conditions[0]

        return InterfaceAbstraction(
            interface_name=self._interface_name,
            pre_condition=pre_formula,
            post_condition=post_formula,
            heap_footprint=frozenset(heap_effects),
            abstraction_id=f"ia_{uuid.uuid4().hex[:8]}",
            created_at=time.time(),
        )

    def _is_consistent(
        self,
        abstraction: InterfaceAbstraction | None,
        example: dict[str, Any],
    ) -> bool:
        """Return True if *abstraction* is consistent with *example*.

        Consistency check: the example's pre-condition implies the
        abstraction's pre-condition (syntactic over-approximation check).
        """
        if abstraction is None:
            return False
        ex_pre = str(example.get("pre", "true"))
        ex_post = str(example.get("post", "true"))
        # Syntactic consistency: check if example terms appear in abstraction
        pre_ok = ex_pre in abstraction.pre_condition or abstraction.pre_condition == "true"
        post_ok = ex_post in abstraction.post_condition or abstraction.post_condition == "true"
        return pre_ok or post_ok

    def _refine_with_counterexample(self, ce: dict[str, Any]) -> None:
        """Refine the current abstraction to include *ce*.

        Weakens the precondition to admit the counterexample's pre-state
        and strengthens the postcondition if the counterexample's post-state
        is inconsistent.

        Parameters
        ----------
        ce
            Counterexample dict with keys ``"pre"``, ``"post"``,
            ``"heap_effect"``.
        """
        if self._current_abstraction is None:
            self._current_abstraction = self._synthesize_from_examples([ce])
            return

        ce_pre = str(ce.get("pre", "true"))
        ce_post = str(ce.get("post", "true"))
        ce_heap = str(ce.get("heap_effect", "unchanged"))

        # Weaken precondition disjunctively
        old_pre = self._current_abstraction.pre_condition
        new_pre = f"(or {old_pre} {ce_pre})"

        # Intersect postcondition (conservative: keep existing)
        old_post = self._current_abstraction.post_condition
        new_post = f"(and {old_post} {ce_post})"

        new_footprint = self._current_abstraction.heap_footprint | {ce_heap}

        self._current_abstraction = InterfaceAbstraction(
            interface_name=self._interface_name,
            pre_condition=new_pre,
            post_condition=new_post,
            heap_footprint=new_footprint,
            abstraction_id=f"ia_{uuid.uuid4().hex[:8]}",
            created_at=time.time(),
        )
        self.logger.debug(
            "Refined abstraction for '%s' (pre: %s → %s)",
            self._interface_name,
            old_pre[:30],
            new_pre[:30],
        )

    def get_abstraction(self) -> InterfaceAbstraction | None:
        """Return the current best abstraction, or None."""
        return self._current_abstraction


# ---------------------------------------------------------------------------
# 5. BoundaryConditionMinimization
# ---------------------------------------------------------------------------


class BoundaryConditionMinimization(CollectionHeapAlgorithm):
    """Minimize a set of boundary conditions using unsat-core simulation.

    Given a list of formula strings, attempts to find the smallest subset
    that preserves the implication of the full set.  Uses a greedy
    backwards-elimination strategy.

    Parameters
    ----------
    session
        Optional Z3Session for implication checks.
    max_iterations
        Maximum elimination attempts.
    timeout_seconds
        Wall-clock timeout.
    """

    def __init__(
        self,
        session: Z3Session | None = None,
        max_iterations: int = _DEFAULT_MAX_ITERATIONS,
        timeout_seconds: float = _DEFAULT_TIMEOUT_SECONDS,
    ) -> None:
        super().__init__(max_iterations=max_iterations, timeout_seconds=timeout_seconds)
        self._formula_set: list[str] = []
        self._current_minimal: list[str] = []
        self._session = session
        self._elimination_idx: int = 0

    def run(self, inputs: dict[str, Any]) -> AlgorithmResult:
        """Run boundary condition minimization.

        Parameters
        ----------
        inputs
            Dictionary with key ``"conditions"``: list[str] of SMT-LIB2
            Boolean formula strings.

        Returns
        -------
        AlgorithmResult
            result is a list[str] of the minimal subset of formulas.
        """
        self._start_time = time.perf_counter()
        self._iteration_count = 0

        conditions: list[str] = inputs.get("conditions", [])
        if not conditions:
            return AlgorithmResult(
                status=AlgorithmStatus.CONVERGED,
                iterations=0,
                wall_time_ms=self.elapsed_ms(),
                result=[],
                error_message=None,
                metadata={"original_count": 0, "minimal_count": 0},
            )

        self._formula_set = list(conditions)
        self._current_minimal = list(conditions)
        self._elimination_idx = len(self._current_minimal) - 1

        self.logger.info(
            "Starting boundary minimization: %d conditions", len(conditions)
        )

        status, iters = self._run_iteration_loop()

        return AlgorithmResult(
            status=status,
            iterations=iters,
            wall_time_ms=self.elapsed_ms(),
            result=list(self._current_minimal),
            error_message=None,
            metadata={
                "original_count": len(conditions),
                "minimal_count": len(self._current_minimal),
                "reduction_pct": (
                    100.0 * (1 - len(self._current_minimal) / max(len(conditions), 1))
                ),
            },
        )

    def step(self) -> bool:
        """Attempt to remove one condition from the current minimal set.

        Returns
        -------
        bool
            True if all positions have been tried (converged).
        """
        if self._elimination_idx < 0:
            return True

        removed = self._try_remove_conjunct(self._elimination_idx)
        if removed:
            # Don't decrement — the list shrank, so the same index now points
            # to the next element
            self._elimination_idx = min(
                self._elimination_idx, len(self._current_minimal) - 1
            )
        else:
            self._elimination_idx -= 1

        return self._elimination_idx < 0

    def is_converged(self) -> bool:
        """Return True when the elimination scan is complete."""
        return self._elimination_idx < 0

    def summarize(self) -> str:
        """Return a human-readable description of the minimization state."""
        return (
            f"BoundaryConditionMinimization("
            f"status={self._status.value}, "
            f"original={len(self._formula_set)}, "
            f"current_minimal={len(self._current_minimal)}, "
            f"idx={self._elimination_idx})"
        )

    def _try_remove_conjunct(self, idx: int) -> bool:
        """Attempt to remove the condition at *idx* from the minimal set.

        The condition at *idx* is redundant iff the remaining conditions
        logically imply it.  We check this by verifying that
        ``(remaining_conditions ∧ ¬condition[idx])`` is UNSAT.

        Parameters
        ----------
        idx
            Index into *_current_minimal* to attempt removal.

        Returns
        -------
        bool
            True if the condition was removed (it was redundant).
        """
        if idx < 0 or idx >= len(self._current_minimal):
            return False

        candidate = self._current_minimal[idx]
        rest = self._current_minimal[:idx] + self._current_minimal[idx + 1:]

        if not rest:
            return False

        is_redundant = self._verify_implication(rest, self._formula_set)
        if is_redundant:
            self._current_minimal = rest
            self.logger.debug(
                "Removed redundant condition [%d]: %s", idx, candidate[:50]
            )
            return True
        return False

    def _verify_implication(
        self,
        subset: list[str],
        full: list[str],  # noqa: ARG002 — kept for API completeness
    ) -> bool:
        """Check whether *subset* implies the full conjunction.

        Parameters
        ----------
        subset
            Candidate minimal subset of formulas.
        full
            Original full set (unused in heuristic mode).

        Returns
        -------
        bool
            True if *subset* implies the full set (i.e., the removed formula
            is redundant).
        """
        if self._session is None:
            # Heuristic: assume the condition is not redundant (conservative)
            return False

        if not subset:
            return False

        subset_formula = "(and " + " ".join(subset) + ")" if len(subset) > 1 else subset[0]
        removed_conditions = [c for c in self._formula_set if c not in subset]
        if not removed_conditions:
            return True

        for removed in removed_conditions:
            # Check: subset ∧ ¬removed → UNSAT means subset ⊨ removed
            check_formula = f"(and {subset_formula} (not {removed}))"
            try:
                result = self._session.check(check_formula)
                if result.outcome is not SolveOutcome.UNSAT:
                    return False  # Could not prove implication for this condition
            except Exception as exc:  # noqa: BLE001
                self.logger.warning("Implication check failed: %s", exc)
                return False
        return True

    def get_minimal_set(self) -> list[str]:
        """Return the current minimal set of conditions."""
        return list(self._current_minimal)


# ---------------------------------------------------------------------------
# Registry and factory
# ---------------------------------------------------------------------------

_ALGORITHM_REGISTRY: dict[str, type[CollectionHeapAlgorithm]] = {
    "bottom_up_heap_summary": BottomUpHeapSummaryAlgorithm,
    "fixed_point_alias": FixedPointAliasAnalysis,
    "collection_invariant_inference": CollectionInvariantInference,
    "interface_abstraction_synthesis": InterfaceAbstractionSynthesis,
    "boundary_condition_minimization": BoundaryConditionMinimization,
}


def create_algorithm(
    name: str,
    **kwargs: Any,
) -> CollectionHeapAlgorithm:
    """Instantiate a registered algorithm by name.

    Parameters
    ----------
    name
        Registry key (e.g. ``"bottom_up_heap_summary"``).
    **kwargs
        Keyword arguments forwarded to the algorithm constructor.

    Returns
    -------
    CollectionHeapAlgorithm
        A fresh algorithm instance.

    Raises
    ------
    KeyError
        If *name* is not in the registry.

    Examples
    --------
    >>> algo = create_algorithm("fixed_point_alias", max_iterations=100)
    >>> isinstance(algo, FixedPointAliasAnalysis)
    True
    """
    if name not in _ALGORITHM_REGISTRY:
        available = ", ".join(sorted(_ALGORITHM_REGISTRY))
        raise KeyError(
            f"Unknown algorithm '{name}'.  Available algorithms: {available}"
        )
    cls = _ALGORITHM_REGISTRY[name]
    return cls(**kwargs)


def run_all_algorithms(inputs: dict[str, Any]) -> dict[str, AlgorithmResult]:
    """Run every registered algorithm on *inputs* and collect results.

    Each algorithm is given the same *inputs* dict.  Algorithms that do
    not find the keys they need will return an ERROR result.

    Parameters
    ----------
    inputs
        Shared input dictionary passed to every algorithm's :meth:`run`.

    Returns
    -------
    dict[str, AlgorithmResult]
        Map from algorithm name to its result.
    """
    results: dict[str, AlgorithmResult] = {}
    for name, cls in _ALGORITHM_REGISTRY.items():
        algo = cls()
        log = logging.getLogger(__name__)
        log.info("Running algorithm '%s'", name)
        t0 = time.perf_counter()
        try:
            result = algo.run(inputs)
        except Exception as exc:  # noqa: BLE001
            elapsed = (time.perf_counter() - t0) * 1000
            log.error("Algorithm '%s' raised: %s", name, exc)
            result = AlgorithmResult(
                status=AlgorithmStatus.ERROR,
                iterations=0,
                wall_time_ms=elapsed,
                result=None,
                error_message=str(exc),
                metadata={"algorithm_name": name},
            )
        results[name] = result
        log.info("Algorithm '%s' finished: %s", name, result.summary())
    return results


def register_algorithm(
    name: str,
    cls: type[CollectionHeapAlgorithm],
) -> None:
    """Add a custom algorithm class to the registry.

    Parameters
    ----------
    name
        Unique registry key.
    cls
        Subclass of :class:`CollectionHeapAlgorithm`.

    Raises
    ------
    TypeError
        If *cls* is not a subclass of :class:`CollectionHeapAlgorithm`.
    ValueError
        If *name* is already registered.
    """
    if not issubclass(cls, CollectionHeapAlgorithm):
        raise TypeError(
            f"{cls.__name__} must be a subclass of CollectionHeapAlgorithm"
        )
    if name in _ALGORITHM_REGISTRY:
        raise ValueError(
            f"Algorithm '{name}' is already registered.  "
            "Use a unique name or remove the existing registration."
        )
    _ALGORITHM_REGISTRY[name] = cls
    logger.info("Registered custom algorithm '%s' → %s", name, cls.__name__)


# ---------------------------------------------------------------------------
# __all__
# ---------------------------------------------------------------------------

__all__ = [
    # Enums
    "AlgorithmStatus",
    # Data classes
    "AlgorithmResult",
    # Abstract base
    "CollectionHeapAlgorithm",
    # Concrete algorithms
    "BottomUpHeapSummaryAlgorithm",
    "FixedPointAliasAnalysis",
    "CollectionInvariantInference",
    "InterfaceAbstractionSynthesis",
    "BoundaryConditionMinimization",
    # Registry and factory
    "_ALGORITHM_REGISTRY",
    "create_algorithm",
    "run_all_algorithms",
    "register_algorithm",
    # Constants
    "_DEFAULT_MAX_ITERATIONS",
    "_DEFAULT_TIMEOUT_SECONDS",
    "_CONVERGENCE_EPSILON",
]
