"""Aliasing as shared sections: two references alias iff they restrict to the same stalk.

# copilot: collection-heap-encodings module 03 — aliasing obligations
# theory2.tex §27.12–§27.15: aliasing is modelled as shared stalks in the heap
# sheaf.  Two pointers p and q alias iff their restrictions to every open set U
# that contains both of their coordinates yield the same stalk value.

In the sheaf-theoretic heap model, *aliasing* is not a pointer equality check —
it is a property of the restriction maps.  Two references p and q **must-alias**
iff for every open U in the heap site, the restrictions res(p, U) and res(q, U)
are equal as stalks.  They **may-alias** iff there exists some U on which the
restrictions cannot be proven distinct.

This module implements:

* :class:`AliasingObligation` — a collection of must-alias / must-not-alias
  constraints, organised as a union-find structure.
* :class:`StalkerEquivalence` — a stalk-level equivalence record proving that
  two references restrict to the same stalk on some cover element.
* :class:`AliasProofBurden` — the set of proof burdens generated by an aliasing
  obligation, ready for discharge via solver or runtime.
* :class:`MayAliasSet` — a conservative over-approximation of which references
  may alias, used as the default when proofs are absent.

Public functions
----------------
:func:`generate_aliasing_obligations`
    From a heap graph and a set of reference pairs, generate all aliasing
    obligations that must be discharged.
:func:`check_may_alias`
    Check whether two references in a HeapSummary may alias.
:func:`discharge_alias_obligation`
    Attempt to discharge an aliasing obligation via local solver or runtime.

Theory invariants
-----------------
* Judgments are tuples ``(c, φ, A, E, O, B, T, Π)`` — NEVER booleans.
* Trust is an ordered algebra element — NEVER a float.
* TrustTier: PROPOSAL → REVIEWED → VERIFIED → RUNTIME_WITNESSED → PROOF_BACKED.
* Obstructions are Čech H¹ cohomology classes.
* Descent returns GlobalSection OR DescentObstruction — never raises.
* ``raise_with_scope(code, message=..., provenance=...)`` signature.
"""

from __future__ import annotations

import abc
import collections
import functools
import hashlib
import itertools
import json
import logging
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum, IntEnum
from functools import reduce
from itertools import combinations
from typing import Any, Iterable, Mapping, Optional, Sequence

logger = logging.getLogger(__name__)
_LOGGER = logger

# ---------------------------------------------------------------------------
# Optional jugeo imports
# ---------------------------------------------------------------------------

try:
    from jugeo.errors import (
        FailureClassification,
        FailureScope,
        JuGeoError,
        StructuredFailure,
        raise_with_scope,
    )
    _JUGEO_ERRORS = True
except ImportError:
    _JUGEO_ERRORS = False
    class FailureScope(str, Enum):  # type: ignore[no-redef]
        GEOMETRY = "geometry"; ENCODING = "encoding"; UNKNOWN = "unknown"
    class FailureClassification(str, Enum):  # type: ignore[no-redef]
        ENCODING_MISMATCH = "encoding_mismatch"; DESCENT_OBSTRUCTION = "descent_obstruction"; UNCLASSIFIED = "unclassified"
    class JuGeoError(RuntimeError): pass  # type: ignore[no-redef]
    class StructuredFailure:  # type: ignore[no-redef]
        def __init__(self, message: str, **kw: Any) -> None: self.message = message
    def raise_with_scope(code: str, *, message: str, provenance: Any = None, **kw: Any) -> None:  # type: ignore[misc]
        raise JuGeoError(f"[{code}] {message}")

try:
    from jugeo.judgments.judgment_terms import (
        EvidenceItemKind, JudgmentStatus, PropositionKind, ProvenanceSource, TrustLevel,
    )
    _JUGEO_JUDGMENTS = True
except ImportError:
    _JUGEO_JUDGMENTS = False
    class TrustLevel(IntEnum):  # type: ignore[no-redef]
        CONTRADICTED = 0; UNVERIFIED = 1; ORACLE_PROPOSED = 2; RUNTIME_WITNESSED = 3; SOLVER_DISCHARGED = 4; VERIFIED_PROOF = 5
    class PropositionKind(str, Enum):  # type: ignore[no-redef]
        STRUCTURAL = "structural"; BEHAVIORAL = "behavioral"; RELATIONAL = "relational"
    class EvidenceItemKind(str, Enum):  # type: ignore[no-redef]
        SOLVER_PROOF = "solver_proof"; RUNTIME_WITNESS = "runtime_witness"; ORACLE_PROPOSAL = "oracle_proposal"
    class ProvenanceSource(str, Enum):  # type: ignore[no-redef]
        SOLVER = "solver"; RUNTIME = "runtime"; ORACLE = "oracle"; HUMAN = "human"

class TrustTier(IntEnum):
    """Ordered trust tiers — PROPOSAL ≺ REVIEWED ≺ VERIFIED ≺ RUNTIME_WITNESSED ≺ PROOF_BACKED."""

    PROPOSAL = 1
    REVIEWED = 2
    VERIFIED = 3
    RUNTIME_WITNESSED = 4
    PROOF_BACKED = 5

    def join(self, other: TrustTier) -> TrustTier:
        return TrustTier(max(int(self), int(other)))

    def meet(self, other: TrustTier) -> TrustTier:
        return TrustTier(min(int(self), int(other)))

    def promote(self) -> TrustTier:
        return TrustTier(min(int(self) + 1, TrustTier.PROOF_BACKED))

    def demote(self) -> TrustTier:
        return TrustTier(max(int(self) - 1, TrustTier.PROPOSAL))

    def is_at_least(self, other: TrustTier) -> bool:
        return int(self) >= int(other)


# ---------------------------------------------------------------------------
# Judgment dataclass — (c, φ, A, E, O, B, T, Π) — NEVER a boolean
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Judgment:
    """A judgment (c, φ, A, E, O, B, T, Π) — NEVER a boolean.

    Fields mirror the theory2.tex tuple: context, formula, assumptions,
    evidence, obligations, burden, trust (TrustTier), provenance.
    """
    context: Any
    formula: Any
    assumptions: tuple
    evidence: tuple
    obligations: tuple
    burden: Any
    trust: TrustTier
    provenance: Any


# ---------------------------------------------------------------------------
# CechObstruction dataclass — Čech H¹ cohomology class
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CechObstruction:
    """A Čech H¹ cohomology class witnessing descent failure.

    Attributes
    ----------
    cover_id:      Identifier of the open cover {U_i}.
    cocycle:       frozenset of (i, j, σ_ij) triples.
    cohomology_class: Canonical string representative of [σ] ∈ Ȟ¹.
    description:   Human-readable explanation of the obstruction.
    """
    cover_id: str
    cocycle: frozenset
    cohomology_class: str
    description: str

    def is_trivial(self) -> bool:
        """Return True iff the Čech class is the trivial (zero) element."""
        return len(self.cocycle) == 0


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class AliasKind(str, Enum):
    """Whether an aliasing obligation requires must-alias or must-not-alias."""

    MUST_ALIAS = "must_alias"
    MUST_NOT_ALIAS = "must_not_alias"
    MAY_ALIAS = "may_alias"          # conservative: unknown
    PROVABLY_DISTINCT = "provably_distinct"


class DischargeResult(str, Enum):
    """Outcome of an alias obligation discharge attempt."""

    DISCHARGED_MUST_ALIAS = "discharged_must_alias"
    DISCHARGED_MUST_NOT_ALIAS = "discharged_must_not_alias"
    DISCHARGED_PROVABLY_DISTINCT = "discharged_provably_distinct"
    FAILED_CONFLICTING_EVIDENCE = "failed_conflicting_evidence"
    PENDING = "pending"
    UNKNOWN = "unknown"


class StalkerKind(str, Enum):
    """The nature of a stalk-level equivalence witness."""

    SYNTACTIC_EQUALITY = "syntactic_equality"    # same expression
    SEMANTIC_EQUALITY = "semantic_equality"      # proved by solver
    RUNTIME_SAME_OBJECT = "runtime_same_object"  # id(a) == id(b)
    INFERRED = "inferred"                        # inferred from field chain


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _stable_id(prefix: str, payload: str) -> str:
    digest = hashlib.sha256(payload.encode()).hexdigest()[:16]
    return f"{prefix}:{digest}"


def _now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


# ---------------------------------------------------------------------------
# Čech obstruction for aliasing
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class AliasCechObstruction:
    """A Čech H¹ cohomology class blocking aliasing obligation resolution."""

    coordinate: str
    cocycle_description: str
    involved_refs: tuple[str, ...]
    trust_tier: TrustTier = TrustTier.PROPOSAL
    is_coboundary: bool = False
    repair_suggestion: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "coordinate": self.coordinate,
            "cocycle_description": self.cocycle_description,
            "involved_refs": list(self.involved_refs),
            "trust_tier": self.trust_tier.name,
            "is_coboundary": self.is_coboundary,
            "repair_suggestion": self.repair_suggestion,
        }


# ---------------------------------------------------------------------------
# Judgment tuple — (c, φ, A, E, O, B, T, Π)
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class AliasJudgment:
    """A judgment about an aliasing obligation.  NEVER a boolean."""

    c: str
    phi: str
    A: str
    E: tuple[str, ...]
    O: tuple[str, ...]
    B: tuple[AliasCechObstruction, ...]
    T: TrustTier
    Pi: Mapping[str, Any]

    @property
    def is_settled(self) -> bool:
        return len(self.O) == 0 and len(self.B) == 0

    @property
    def is_obstructed(self) -> bool:
        return any(not ob.is_coboundary for ob in self.B)

    def with_obligation(self, ob: str) -> AliasJudgment:
        from dataclasses import replace
        return replace(self, O=(*self.O, ob))

    def with_obstruction(self, obs: AliasCechObstruction) -> AliasJudgment:
        from dataclasses import replace
        return replace(self, B=(*self.B, obs))

    def to_dict(self) -> dict[str, Any]:
        return {
            "c": self.c, "phi": self.phi, "A": self.A,
            "E": list(self.E), "O": list(self.O),
            "B": [ob.to_dict() for ob in self.B],
            "T": self.T.name, "Pi": dict(self.Pi),
        }


def _make_alias_judgment(
    coordinate: str, phi: str, carrier: str,
    evidence: Sequence[str], obligations: Sequence[str],
    trust: TrustTier = TrustTier.PROPOSAL,
    provenance: Mapping[str, Any] | None = None,
) -> AliasJudgment:
    return AliasJudgment(
        c=coordinate, phi=phi, A=carrier,
        E=tuple(evidence), O=tuple(obligations), B=(),
        T=trust, Pi=dict(provenance or {}),
    )


# ---------------------------------------------------------------------------
# Stalk-level equivalence witness
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class StalkerEquivalence:
    """A stalk-level equivalence witness proving two references restrict to the same stalk.

    Two references ``ref_a`` and ``ref_b`` restrict to the same stalk on a
    cover element ``U`` iff their restriction maps both yield the same value
    at every point in ``U``.

    Attributes
    ----------
    equivalence_id : str
        Unique identifier.
    ref_a : str
        Identifier of the first reference.
    ref_b : str
        Identifier of the second reference.
    cover_element : str
        The open set U on which equivalence was witnessed.
    kind : StalkerKind
        How the equivalence was established.
    stalk_value_repr : str
        Representation of the shared stalk value.
    judgment : AliasJudgment
        The governing judgment.
    """

    equivalence_id: str
    ref_a: str
    ref_b: str
    cover_element: str
    kind: StalkerKind
    stalk_value_repr: str
    judgment: AliasJudgment

    def to_smt_assertion(self) -> str:
        """Return the SMT-LIB2 assertion for this stalk equivalence."""
        return f"(= (heap-deref {self.ref_a}) (heap-deref {self.ref_b}))"

    def to_dict(self) -> dict[str, Any]:
        return {
            "equivalence_id": self.equivalence_id,
            "ref_a": self.ref_a,
            "ref_b": self.ref_b,
            "cover_element": self.cover_element,
            "kind": self.kind.value,
            "stalk_value_repr": self.stalk_value_repr,
            "judgment": self.judgment.to_dict(),
        }


# ---------------------------------------------------------------------------
# Union-find for alias classes
# ---------------------------------------------------------------------------

class _UnionFind:
    """A simple union-find (disjoint-set) structure for alias class tracking."""

    def __init__(self) -> None:
        self._parent: dict[str, str] = {}
        self._rank: dict[str, int] = {}

    def find(self, x: str) -> str:
        if x not in self._parent:
            self._parent[x] = x
            self._rank[x] = 0
        if self._parent[x] != x:
            self._parent[x] = self.find(self._parent[x])
        return self._parent[x]

    def union(self, x: str, y: str) -> bool:
        """Union the sets containing x and y.  Returns True if merged."""
        rx, ry = self.find(x), self.find(y)
        if rx == ry:
            return False
        if self._rank[rx] < self._rank[ry]:
            rx, ry = ry, rx
        self._parent[ry] = rx
        if self._rank[rx] == self._rank[ry]:
            self._rank[rx] += 1
        return True

    def same_class(self, x: str, y: str) -> bool:
        return self.find(x) == self.find(y)

    def classes(self) -> dict[str, list[str]]:
        """Return a dict mapping representative → members."""
        result: dict[str, list[str]] = defaultdict(list)
        for x in self._parent:
            result[self.find(x)].append(x)
        return dict(result)


# ---------------------------------------------------------------------------
# Aliasing obligation
# ---------------------------------------------------------------------------

@dataclass
class AliasingObligation:
    """A collection of must-alias / must-not-alias constraints.

    This is the central mutable workspace for tracking aliasing relationships
    during heap analysis.  It maintains:
    * A union-find structure for must-alias equivalence classes.
    * A set of must-not-alias pairs (disjointness obligations).
    * A set of StalkerEquivalence witnesses.

    Design principle: state mutation is gated behind consistency checks.
    The builder pattern enables fluent chains:
        ``obl.add_must_alias("p", "q").add_disjointness("p", "r")``
    """

    obligation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    coordinate: str = "alias_root"
    _must_alias_uf: _UnionFind = field(default_factory=_UnionFind, init=False, repr=False)
    _must_not_alias: set[frozenset[str]] = field(default_factory=set, init=False, repr=False)
    _stalker_equivalences: list[StalkerEquivalence] = field(default_factory=list, init=False, repr=False)
    _judgments: list[AliasJudgment] = field(default_factory=list, init=False, repr=False)
    _discharge_results: dict[str, DischargeResult] = field(default_factory=dict, init=False, repr=False)

    def add_must_alias(self, ref_a: str, ref_b: str) -> AliasingObligation:
        """Assert that ref_a and ref_b must alias.

        Raises JuGeoError if this contradicts an existing must-not-alias pair.
        """
        if frozenset({ref_a, ref_b}) in self._must_not_alias:
            raise_with_scope(
                "ALIAS_CONTRADICTION",
                message=f"Cannot add must-alias({ref_a}, {ref_b}): contradicts existing must-not-alias.",
                provenance={"ref_a": ref_a, "ref_b": ref_b, "obligation_id": self.obligation_id},
            )
        self._must_alias_uf.union(ref_a, ref_b)
        jmt = _make_alias_judgment(
            coordinate=f"{self.coordinate}.must_alias",
            phi=f"must_alias({ref_a},{ref_b})",
            carrier="alias_class",
            evidence=[f"assertion:must_alias({ref_a},{ref_b})"],
            obligations=[],
            trust=TrustTier.PROPOSAL,
            provenance={"ref_a": ref_a, "ref_b": ref_b},
        )
        self._judgments.append(jmt)
        return self

    def add_disjointness(self, ref_a: str, ref_b: str) -> AliasingObligation:
        """Assert that ref_a and ref_b must NOT alias.

        Raises JuGeoError if this contradicts an existing must-alias pair.
        """
        if self._must_alias_uf.same_class(ref_a, ref_b):
            raise_with_scope(
                "ALIAS_CONTRADICTION",
                message=f"Cannot add must-not-alias({ref_a}, {ref_b}): contradicts existing must-alias.",
                provenance={"ref_a": ref_a, "ref_b": ref_b, "obligation_id": self.obligation_id},
            )
        self._must_not_alias.add(frozenset({ref_a, ref_b}))
        jmt = _make_alias_judgment(
            coordinate=f"{self.coordinate}.disjoint",
            phi=f"must_not_alias({ref_a},{ref_b})",
            carrier="disjoint_pair",
            evidence=[f"assertion:must_not_alias({ref_a},{ref_b})"],
            obligations=[],
            trust=TrustTier.PROPOSAL,
            provenance={"ref_a": ref_a, "ref_b": ref_b},
        )
        self._judgments.append(jmt)
        return self

    def add_stalker_equivalence(self, equiv: StalkerEquivalence) -> AliasingObligation:
        """Record a stalk-level equivalence witness."""
        self._stalker_equivalences.append(equiv)
        return self

    def alias_classes(self) -> dict[str, list[str]]:
        """Return the current must-alias equivalence classes."""
        return self._must_alias_uf.classes()

    def disjointness_pairs(self) -> list[tuple[str, str]]:
        """Return all must-not-alias pairs."""
        return [(sorted(p)[0], sorted(p)[1]) for p in self._must_not_alias]

    def is_consistent(self) -> bool:
        """Check that must-alias and must-not-alias are not contradictory."""
        for fs in self._must_not_alias:
            refs = list(fs)
            if len(refs) == 2 and self._must_alias_uf.same_class(refs[0], refs[1]):
                return False
        return True

    def emit_smt_obligations(self) -> list[str]:
        """Emit all obligations as SMT-LIB2 assertion strings."""
        obligations: list[str] = []
        for rep, members in self.alias_classes().items():
            for m in members:
                if m != rep:
                    obligations.append(f"(= (heap-deref {rep}) (heap-deref {m}))")
        for ref_a, ref_b in self.disjointness_pairs():
            obligations.append(f"(not (= (heap-deref {ref_a}) (heap-deref {ref_b})))")
        return obligations

    def to_dict(self) -> dict[str, Any]:
        return {
            "obligation_id": self.obligation_id,
            "coordinate": self.coordinate,
            "alias_classes": self.alias_classes(),
            "disjointness_pairs": self.disjointness_pairs(),
            "num_stalker_equivalences": len(self._stalker_equivalences),
            "is_consistent": self.is_consistent(),
        }


# ---------------------------------------------------------------------------
# Alias proof burden
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class AliasProofBurden:
    """The set of proof burdens generated by an aliasing obligation.

    Each burden is an SMT-LIB2 assertion that must be discharged by
    a solver or runtime before the aliasing obligation is settled.

    Attributes
    ----------
    burden_id : str
        Unique identifier.
    obligation_id : str
        The AliasingObligation that generated this burden.
    alias_assertions : tuple[str, ...]
        SMT-LIB2 must-alias assertions.
    disjointness_assertions : tuple[str, ...]
        SMT-LIB2 must-not-alias assertions.
    judgment : AliasJudgment
        The governing judgment.
    discharge_result : DischargeResult
        The current discharge status.
    """

    burden_id: str
    obligation_id: str
    alias_assertions: tuple[str, ...]
    disjointness_assertions: tuple[str, ...]
    judgment: AliasJudgment
    discharge_result: DischargeResult = DischargeResult.PENDING

    def all_assertions(self) -> tuple[str, ...]:
        return self.alias_assertions + self.disjointness_assertions

    def is_discharged(self) -> bool:
        return self.discharge_result not in (
            DischargeResult.PENDING,
            DischargeResult.UNKNOWN,
            DischargeResult.FAILED_CONFLICTING_EVIDENCE,
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "burden_id": self.burden_id,
            "obligation_id": self.obligation_id,
            "num_alias_assertions": len(self.alias_assertions),
            "num_disjointness_assertions": len(self.disjointness_assertions),
            "discharge_result": self.discharge_result.value,
            "judgment": self.judgment.to_dict(),
        }


# ---------------------------------------------------------------------------
# May-alias set
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class MayAliasSet:
    """Conservative over-approximation of which references may alias.

    A pair (a, b) is in the may-alias set iff it has not been proven that
    a and b must-not-alias.  This is the default (sound, imprecise) result
    when proof obligations are not discharged.

    Attributes
    ----------
    set_id : str
        Unique identifier.
    coordinate : str
        Semantic coordinate.
    pairs : frozenset[frozenset[str]]
        All may-alias pairs.
    judgment : AliasJudgment
        The governing judgment.
    trust_tier : TrustTier
        Trust level of this approximation.
    is_precise : bool
        Whether this approximation is known to be exact.
    """

    set_id: str
    coordinate: str
    pairs: frozenset[frozenset[str]]
    judgment: AliasJudgment
    trust_tier: TrustTier = TrustTier.PROPOSAL
    is_precise: bool = False

    def contains(self, ref_a: str, ref_b: str) -> bool:
        return frozenset({ref_a, ref_b}) in self.pairs

    def num_pairs(self) -> int:
        return len(self.pairs)

    def all_references(self) -> frozenset[str]:
        return frozenset(r for pair in self.pairs for r in pair)

    def to_dict(self) -> dict[str, Any]:
        return {
            "set_id": self.set_id,
            "coordinate": self.coordinate,
            "num_pairs": len(self.pairs),
            "trust_tier": self.trust_tier.name,
            "is_precise": self.is_precise,
            "judgment": self.judgment.to_dict(),
        }


# ---------------------------------------------------------------------------
# Global section and descent obstruction for aliasing
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class AliasGlobalSection:
    """A globally consistent aliasing resolution — all obligations discharged."""

    coordinate: str
    resolved_classes: dict[str, list[str]]
    proven_distinct_pairs: list[tuple[str, str]]
    judgment: AliasJudgment

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "alias_global_section",
            "coordinate": self.coordinate,
            "num_classes": len(self.resolved_classes),
            "num_distinct_pairs": len(self.proven_distinct_pairs),
            "judgment": self.judgment.to_dict(),
        }


@dataclass(frozen=True, slots=True)
class AliasDescentObstruction:
    """A Čech obstruction blocking aliasing obligation resolution.  NEVER raises."""

    coordinate: str
    obstruction: AliasCechObstruction
    unresolved_pairs: tuple[tuple[str, str], ...]
    diagnosis: str = ""
    repair_hints: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": "alias_descent_obstruction",
            "coordinate": self.coordinate,
            "obstruction": self.obstruction.to_dict(),
            "unresolved_pairs": list(self.unresolved_pairs),
            "diagnosis": self.diagnosis,
            "repair_hints": list(self.repair_hints),
        }


# ---------------------------------------------------------------------------
# Public functions
# ---------------------------------------------------------------------------

def generate_aliasing_obligations(
    reference_pairs: Sequence[tuple[str, str]],
    known_must_alias: Sequence[tuple[str, str]] | None = None,
    known_must_not_alias: Sequence[tuple[str, str]] | None = None,
    *,
    coordinate: str = "alias_obligations",
) -> AliasingObligation:
    """From a set of reference pairs, generate all aliasing obligations.

    Parameters
    ----------
    reference_pairs : Sequence[tuple[str, str]]
        All (ref_a, ref_b) pairs that must be analysed for aliasing.
    known_must_alias : Sequence[tuple[str, str]] or None
        Pairs known to must-alias (from program analysis).
    known_must_not_alias : Sequence[tuple[str, str]] or None
        Pairs known to must-not-alias (from separation logic).
    coordinate : str
        Semantic coordinate.

    Returns
    -------
    AliasingObligation
    """
    logger.debug(
        "generate_aliasing_obligations: %d pairs at %s",
        len(reference_pairs), coordinate,
    )
    obl = AliasingObligation(
        obligation_id=_stable_id("alias_obl", coordinate),
        coordinate=coordinate,
    )
    for ref_a, ref_b in (known_must_alias or []):
        try:
            obl.add_must_alias(ref_a, ref_b)
        except JuGeoError as exc:
            logger.warning("Skipping contradictory must-alias: %s", exc)

    for ref_a, ref_b in (known_must_not_alias or []):
        try:
            obl.add_disjointness(ref_a, ref_b)
        except JuGeoError as exc:
            logger.warning("Skipping contradictory must-not-alias: %s", exc)
    return obl


def check_may_alias(
    ref_a: str,
    ref_b: str,
    obligation: AliasingObligation,
    may_alias_set: MayAliasSet | None = None,
) -> bool:
    """Check whether ref_a and ref_b may alias.

    Returns True (conservative) unless a disjointness obligation or a
    MayAliasSet with is_precise=True proves they cannot alias.

    Parameters
    ----------
    ref_a : str
        First reference identifier.
    ref_b : str
        Second reference identifier.
    obligation : AliasingObligation
        The aliasing obligation workspace.
    may_alias_set : MayAliasSet or None
        Optional precise may-alias set; overrides conservative default.

    Returns
    -------
    bool
        True iff ref_a and ref_b may alias.
    """
    # Must-alias implies may-alias
    if obligation._must_alias_uf.same_class(ref_a, ref_b):
        return True
    # Must-not-alias implies cannot alias
    if frozenset({ref_a, ref_b}) in obligation._must_not_alias:
        return False
    # If a precise may-alias set is provided, consult it
    if may_alias_set is not None and may_alias_set.is_precise:
        return may_alias_set.contains(ref_a, ref_b)
    # Conservative: may alias
    return True


def discharge_alias_obligation(
    obligation: AliasingObligation,
    *,
    runtime_id_map: Mapping[str, int] | None = None,
) -> AliasGlobalSection | AliasDescentObstruction:
    """Attempt to discharge an aliasing obligation.

    Discharge NEVER raises — it returns either a resolution or an obstruction.

    Parameters
    ----------
    obligation : AliasingObligation
        The obligation to discharge.
    runtime_id_map : Mapping[str, int] or None
        Map from reference name to Python id() value.  If provided, used for
        runtime identity checks.

    Returns
    -------
    AliasGlobalSection | AliasDescentObstruction
    """
    logger.debug(
        "discharge_alias_obligation: id=%s", obligation.obligation_id
    )
    if not obligation.is_consistent():
        obs = AliasCechObstruction(
            coordinate=obligation.coordinate,
            cocycle_description="Must-alias and must-not-alias constraints are contradictory.",
            involved_refs=tuple(
                r for pair in obligation._must_not_alias for r in pair
            )[:10],
            trust_tier=TrustTier.PROOF_BACKED,
            is_coboundary=False,
            repair_suggestion="Review and resolve contradictory aliasing constraints.",
        )
        return AliasDescentObstruction(
            coordinate=obligation.coordinate,
            obstruction=obs,
            unresolved_pairs=tuple(obligation.disjointness_pairs()[:10]),
            diagnosis="Contradiction between must-alias and must-not-alias.",
            repair_hints=("review-aliasing-constraints", "add-separation-proof"),
        )

    # Runtime discharge: use id() equality
    unresolved: list[tuple[str, str]] = []
    if runtime_id_map is not None:
        for fs in obligation._must_not_alias:
            refs = sorted(fs)
            if len(refs) == 2:
                id_a = runtime_id_map.get(refs[0])
                id_b = runtime_id_map.get(refs[1])
                if id_a is not None and id_b is not None and id_a == id_b:
                    # Runtime says they ARE the same object, contradicting must-not-alias
                    unresolved.append((refs[0], refs[1]))

    if unresolved:
        obs = AliasCechObstruction(
            coordinate=obligation.coordinate,
            cocycle_description=(
                f"Runtime identity check failed for {len(unresolved)} must-not-alias pairs."
            ),
            involved_refs=tuple(r for pair in unresolved for r in pair)[:10],
            trust_tier=TrustTier.RUNTIME_WITNESSED,
            is_coboundary=False,
            repair_suggestion="Verify separation logic preconditions hold at this program point.",
        )
        return AliasDescentObstruction(
            coordinate=obligation.coordinate,
            obstruction=obs,
            unresolved_pairs=tuple(unresolved[:20]),
            diagnosis=f"{len(unresolved)} runtime alias contradictions detected.",
            repair_hints=("check-separation-preconditions",),
        )

    trust = TrustTier.RUNTIME_WITNESSED if runtime_id_map else TrustTier.REVIEWED
    jmt = _make_alias_judgment(
        coordinate=obligation.coordinate,
        phi="aliasing_obligation_discharged",
        carrier="alias_resolution",
        evidence=[f"obligation:{obligation.obligation_id}"],
        obligations=[],
        trust=trust,
        provenance={"obligation_id": obligation.obligation_id, "discharged_at": _now_iso()},
    )
    return AliasGlobalSection(
        coordinate=obligation.coordinate,
        resolved_classes=obligation.alias_classes(),
        proven_distinct_pairs=obligation.disjointness_pairs(),
        judgment=jmt,
    )


def build_proof_burden(obligation: AliasingObligation) -> AliasProofBurden:
    """Convert an AliasingObligation into a structured AliasProofBurden."""
    all_smt = obligation.emit_smt_obligations()
    alias_assertions = tuple(
        s for s in all_smt if s.startswith("(= ")
    )
    disjointness_assertions = tuple(
        s for s in all_smt if s.startswith("(not ")
    )
    jmt = _make_alias_judgment(
        coordinate=obligation.coordinate,
        phi="alias_proof_burden_generated",
        carrier="alias_proof_burden",
        evidence=[f"obligation:{obligation.obligation_id}"],
        obligations=list(alias_assertions) + list(disjointness_assertions),
        trust=TrustTier.PROPOSAL,
        provenance={"obligation_id": obligation.obligation_id},
    )
    return AliasProofBurden(
        burden_id=_stable_id("burden", obligation.obligation_id),
        obligation_id=obligation.obligation_id,
        alias_assertions=alias_assertions,
        disjointness_assertions=disjointness_assertions,
        judgment=jmt,
        discharge_result=DischargeResult.PENDING,
    )


# ---------------------------------------------------------------------------
# __all__
# ---------------------------------------------------------------------------

__all__ = [
    "AliasDescentObstruction",
    "AliasGlobalSection",
    "AliasJudgment",
    "AliasKind",
    "AliasProofBurden",
    "AliasCechObstruction",
    "AliasingObligation",
    "DischargeResult",
    "MayAliasSet",
    "StalkerEquivalence",
    "StalkerKind",
    "TrustTier",
    "build_proof_burden",
    "check_may_alias",
    "discharge_alias_obligation",
    "generate_aliasing_obligations",
]


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    print("=== aliasing_obligations — smoke test ===")

    # Build an aliasing obligation
    obl = generate_aliasing_obligations(
        reference_pairs=[("p", "q"), ("p", "r"), ("q", "r")],
        known_must_alias=[("p", "q")],
        known_must_not_alias=[("p", "r")],
        coordinate="test.alias",
    )
    print(f"AliasingObligation: id={obl.obligation_id[:12]}…")
    assert obl.is_consistent(), "Obligation should be consistent"

    # Check may-alias
    assert check_may_alias("p", "q", obl) is True, "p,q must-alias → may-alias"
    assert check_may_alias("p", "r", obl) is False, "p,r must-not-alias → no may-alias"
    print("check_may_alias: OK")

    # Discharge without runtime info
    result = discharge_alias_obligation(obl)
    print(f"Discharge result: {type(result).__name__}")
    assert isinstance(result, AliasGlobalSection), "Should discharge successfully"
    assert result.judgment.T.is_at_least(TrustTier.REVIEWED), "Trust should be REVIEWED+"

    # Runtime discharge — correct case (p,r have different ids)
    runtime_ids = {"p": 1000, "q": 1000, "r": 2000}
    result_rt = discharge_alias_obligation(obl, runtime_id_map=runtime_ids)
    print(f"Runtime discharge: {type(result_rt).__name__}")
    assert isinstance(result_rt, AliasGlobalSection)
    assert result_rt.judgment.T == TrustTier.RUNTIME_WITNESSED

    # Contradiction test
    obl2 = AliasingObligation(coordinate="test.conflict")
    obl2.add_must_alias("x", "y")
    try:
        obl2.add_disjointness("x", "y")
        assert False, "Should have raised"
    except (JuGeoError, RuntimeError):
        print("Contradiction detection: OK")

    # Proof burden
    burden = build_proof_burden(obl)
    print(f"AliasProofBurden: id={burden.burden_id[:12]}… "
          f"assertions={len(burden.all_assertions())}")
    assert len(burden.all_assertions()) > 0

    # SMT emission
    smt = obl.emit_smt_obligations()
    print(f"SMT obligations: {smt}")
    assert any("heap-deref" in s for s in smt)

    # Trust algebra
    t = TrustTier.REVIEWED
    assert t.join(TrustTier.PROOF_BACKED) == TrustTier.PROOF_BACKED
    assert t.meet(TrustTier.PROPOSAL) == TrustTier.PROPOSAL
    print("TrustTier algebra: OK")

    # Serialization
    d = obl.to_dict()
    j = json.dumps(d, default=str)
    assert "obligation_id" in j
    print("JSON serialization: OK")

    print("All assertions passed.")
    sys.exit(0)
