"""
heap_summary_encoder — Heap points-to constraints in separation logic style.

Generated by the JuGeo copilot encoding pipeline.
theory2.tex Ch27: Exact Z3 encodings II: collections, finite maps, heap summaries,
alias partitions, interface abstractions.

Encodes heap memory as Z3 arrays of location→value with separation logic structure.
Supports the points-to predicate (loc ↦ val), separating conjunction (∗),
the empty heap (emp), and the frame rule.  Footprint tracking ensures that
composed heaps have disjoint footprints.

Part of the JuGeo judgment-geometry framework.

Background
----------
Chapter 27 §27.7–§27.10 of theory2.tex develops the encoding of heap memory in
separation logic (SL) into Z3 array constraints.  The central insight is that
a *symbolic heap* — a conjunction of points-to predicates ``l₁↦v₁ ∗ … ∗ lₙ↦vₙ``
— is satisfiable iff the locations ``l₁, …, lₙ`` are pairwise distinct, which
reduces to a set of disequality constraints over integers (or uninterpreted
location sorts).

Points-to encoding (§27.7)
    ``loc ↦ val`` is represented by declaring a heap array
    ``(declare-fun heap (Int) Int)`` and asserting ``(= (heap loc) val)``.
    The footprint is the singleton set ``{loc}``.

Separating conjunction (§27.8)
    ``h1 ∗ h2`` requires the footprints of ``h1`` and ``h2`` to be disjoint.
    The encoding merges both separating conjuncts and adds the disjointness
    constraint ``(not (= loc1 loc2))`` for every pair (loc1 ∈ fp1, loc2 ∈ fp2).

Frame rule (§27.9)
    A heap ``h`` satisfies the frame rule for frame predicate ``F`` when
    behaviour restricted to its footprint is unaffected by arbitrary heap
    extensions outside the footprint.  We encode this as an extra free-
    variable assertion over the frame region.

Empty heap (§27.10)
    ``emp`` is the unit for ∗.  It has an empty footprint and makes no
    assertions about the heap array.

Allocation / deallocation (§27.11)
    Allocation adds a fresh location (unconstrained value) to the footprint.
    Deallocation removes a location from the footprint and invalidates
    prior assertions about its value.

All encodings produce a :class:`~jugeo.encodings.collection_heap_encodings.models.HeapSummary`
with:
  * ``points_to_map``        — dict mapping location names to value expressions.
  * ``footprint``            — frozenset of owned location names.
  * ``separating_conjuncts`` — list of SMT-LIB2 ``(assert ...)`` strings.
  * ``frame_condition``      — optional frame predicate string.
  * ``metadata``             — stores ``heap_kind``, ``name``, ``declarations``,
                               and ``composition_log`` for downstream stages.

The :class:`HeapSummaryEncoder` is the primary entry point.
"""

from __future__ import annotations

import hashlib
import logging
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Z3 lazy import
# ---------------------------------------------------------------------------

try:
    import z3 as _z3
    _Z3_AVAILABLE = True
except ImportError:
    _z3 = None  # type: ignore[assignment]
    _Z3_AVAILABLE = False

# ---------------------------------------------------------------------------
# Jugeo solver / geometry imports — all guarded
# ---------------------------------------------------------------------------

try:
    from jugeo.solver.z3_session import (
        SolveOutcome,
        Z3Formula,
        Z3Session,
        Z3Result,
        Z3Encoder,
        Z3Decoder,
        Z3QueryBuilder,
        Z3SessionMonitor,
        Z3Serializer,
        Z3CopilotAssist,
        z3_available,
    )
    _Z3_SESSION_AVAILABLE = True
except ImportError:
    _Z3_SESSION_AVAILABLE = False
    SolveOutcome = None  # type: ignore[assignment,misc]
    Z3Formula = None  # type: ignore[assignment,misc]
    Z3Session = None  # type: ignore[assignment,misc]
    Z3Result = None  # type: ignore[assignment,misc]
    Z3Encoder = None  # type: ignore[assignment,misc]
    Z3Decoder = None  # type: ignore[assignment,misc]
    Z3QueryBuilder = None  # type: ignore[assignment,misc]
    Z3SessionMonitor = None  # type: ignore[assignment,misc]
    Z3Serializer = None  # type: ignore[assignment,misc]
    Z3CopilotAssist = None  # type: ignore[assignment,misc]

    def z3_available() -> bool:  # type: ignore[misc]
        return False

try:
    from jugeo.solver.fragments import (
        Fragment,
        SolverFragment,
        LogicalFragment,
        classify_fragment,
        FragmentClassifier,
        EncodingStrategy,
    )
    _FRAGMENTS_AVAILABLE = True
except ImportError:
    _FRAGMENTS_AVAILABLE = False
    Fragment = None  # type: ignore[assignment,misc]
    SolverFragment = None  # type: ignore[assignment,misc]
    LogicalFragment = None  # type: ignore[assignment,misc]
    classify_fragment = None  # type: ignore[assignment]
    FragmentClassifier = None  # type: ignore[assignment,misc]
    EncodingStrategy = None  # type: ignore[assignment,misc]

try:
    from jugeo.geometry.supports import (
        SupportRegion,
        SupportSet,
        SupportStatus,
        SupportMap,
        compute_support,
    )
    _SUPPORTS_AVAILABLE = True
except ImportError:
    _SUPPORTS_AVAILABLE = False
    SupportRegion = None  # type: ignore[assignment,misc]
    SupportSet = None  # type: ignore[assignment,misc]
    SupportStatus = None  # type: ignore[assignment,misc]
    SupportMap = None  # type: ignore[assignment,misc]
    compute_support = None  # type: ignore[assignment]

try:
    from jugeo.encodings.collection_heap_encodings.models import (
        CollectionEncoding,
        HeapSummary,
        AliasPartition,
        FiniteMapEncoding,
        InterfaceAbstraction,
    )
    _MODELS_AVAILABLE = True
except ImportError:
    _MODELS_AVAILABLE = False

    # ------------------------------------------------------------------
    # Inline fallback model definitions (field-compatible with real models)
    # ------------------------------------------------------------------

    @dataclass(slots=True)
    class CollectionEncoding:  # type: ignore[no-redef]
        """Fallback CollectionEncoding."""

        name: str
        element_sort: str = "Int"
        index_sort: str = "Int"
        array_expr: str = ""
        invariants: list[str] = field(default_factory=list)
        provenance: dict[str, Any] = field(default_factory=dict)
        encoding_id: str = field(default_factory=lambda: f"enc_{uuid.uuid4().hex[:12]}")
        created_at: float = field(default_factory=time.time)
        metadata: dict[str, Any] = field(default_factory=dict)

    @dataclass(slots=True)
    class HeapSummary:  # type: ignore[no-redef]
        """Fallback HeapSummary with field-compatible schema.

        Fields match the real model in
        ``jugeo.encodings.collection_heap_encodings.models``.

        Fields
        ------
        location_sort : str
            Z3 sort for heap locations (e.g. ``"Int"``).
        value_sort : str
            Z3 sort for heap values (e.g. ``"Int"``).
        points_to_map : dict[str, str]
            Maps location names to value expressions.
        footprint : frozenset[str]
            Set of location names owned by this heap.
        separating_conjuncts : list[str]
            SMT-LIB2 ``(assert ...)`` strings for all heap assertions.
        frame_condition : str | None
            Optional frame predicate string.
        heap_id : str
            UUID4 identifier for this heap summary.
        created_at : float
            UNIX timestamp.
        metadata : dict[str, Any]
            Free-form pipeline annotations.  The encoder stores ``heap_kind``,
            ``name``, ``declarations``, and ``composition_log`` here.
        """

        location_sort: str = "Int"
        value_sort: str = "Int"
        points_to_map: dict[str, str] = field(default_factory=dict)
        footprint: frozenset[str] = field(default_factory=frozenset)
        separating_conjuncts: list[str] = field(default_factory=list)
        frame_condition: str | None = None
        heap_id: str = field(default_factory=lambda: f"heap_{uuid.uuid4().hex[:12]}")
        created_at: float = field(default_factory=time.time)
        metadata: dict[str, Any] = field(default_factory=dict)

    @dataclass(slots=True)
    class AliasPartition:  # type: ignore[no-redef]
        """Fallback AliasPartition."""

        pointer_sort: str = "Ptr"
        alias_class_fn: str = ""
        disjointness_axioms: list[str] = field(default_factory=list)
        must_alias_pairs: list[tuple[str, str]] = field(default_factory=list)
        must_not_alias_pairs: list[tuple[str, str]] = field(default_factory=list)
        partition_classes: list[frozenset[str]] = field(default_factory=list)
        partition_id: str = field(default_factory=lambda: f"part_{uuid.uuid4().hex[:12]}")
        created_at: float = field(default_factory=time.time)

    @dataclass(slots=True)
    class FiniteMapEncoding:  # type: ignore[no-redef]
        """Fallback FiniteMapEncoding."""

        domain_sort: str = "Int"
        range_sort: str = "Int"
        map_fn: str = "f"
        defined_set: list[str] = field(default_factory=list)
        undefinedness_axiom: str = ""
        update_axioms: list[str] = field(default_factory=list)
        map_id: str = field(default_factory=lambda: f"map_{uuid.uuid4().hex[:12]}")
        created_at: float = field(default_factory=time.time)
        metadata: dict[str, Any] = field(default_factory=dict)

    @dataclass(slots=True)
    class InterfaceAbstraction:  # type: ignore[no-redef]
        """Fallback InterfaceAbstraction."""

        interface_name: str = ""
        abstract_sort: str = "Abs"
        method_signatures: dict[str, tuple[list[str], str]] = field(default_factory=dict)
        refinement_map: dict[str, str] = field(default_factory=dict)
        abstraction_axioms: list[str] = field(default_factory=list)
        concrete_sort: str | None = None
        abstraction_id: str = field(default_factory=lambda: f"abs_{uuid.uuid4().hex[:12]}")
        created_at: float = field(default_factory=time.time)
        metadata: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

_EMP_HEAP_EXPR: str = "emp"
"""The separation-logic expression for the empty heap (unit for ∗).

In our encoding, the empty heap contributes no separating conjuncts and has an
empty footprint.  The string ``"emp"`` is used for logging and formula display.
"""

_POINTS_TO_TEMPLATE: str = "(assert (= ({heap} {loc}) {val}))"
"""SMT-LIB2 template for a single points-to assertion.

Placeholders:
  {heap} — the Z3 heap array symbol name.
  {loc}  — the SMT-LIB2 literal for the location.
  {val}  — the SMT-LIB2 literal for the value.
"""

_STAR_SEPARATOR: str = " * "
"""Human-readable separator used when displaying separating conjunctions."""

_HEAP_ENCODING_VERSION: str = "1.0.0-ch27"
"""Semantic version of this heap encoding module."""

_DEFAULT_LOCATION_SORT: str = "Int"
"""Default Z3 sort for heap locations (integer-addressed heap model)."""

_DEFAULT_VALUE_SORT: str = "Int"
"""Default Z3 sort for heap values (untyped heap stores integers)."""


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class HeapKind(str, Enum):
    """Enumeration of separation-logic heap forms.

    Each member corresponds to one of the structural heap forms defined in
    §27.7–§27.11 of theory2.tex.

    Members
    -------
    EMPTY
        The empty heap ``emp``.  Identity element for separating conjunction.
        Has an empty footprint and makes no assertions.
    POINTS_TO
        A single points-to cell ``loc ↦ val``.  The canonical atomic heap form.
        Footprint is the singleton ``{loc}``.
    STAR
        Separating conjunction ``h1 ∗ h2``.  Requires disjoint footprints.
        Footprint is ``fp(h1) ∪ fp(h2)``.
    FRAME
        A heap with an explicit frame predicate.  The heap is valid in any
        extension of its footprint that satisfies the frame condition.
    QUANTIFIED
        A heap described by a universally or existentially quantified formula.
        Typically arises from list-segment or tree-segment predicates.
    ALLOCATED
        A location that has been freshly allocated (value unconstrained).
    DEALLOCATED
        A location that has been freed.  Any subsequent dereference is undefined.
    """

    EMPTY = "empty"
    POINTS_TO = "points_to"
    STAR = "star"
    FRAME = "frame"
    QUANTIFIED = "quantified"
    ALLOCATED = "allocated"
    DEALLOCATED = "deallocated"


# ---------------------------------------------------------------------------
# SeparationLogicFragment
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class SeparationLogicFragment:
    """Tracks which separation-logic fragment a heap summary inhabits.

    Immutable value object; safe as a dict key and in sets.

    Fields
    ------
    heap_id : str
        The ``heap_id`` of the :class:`HeapSummary` this record describes.
    kind : HeapKind
        The top-level structural form of the heap.
    pointer_count : int
        The number of distinct pointer locations in the heap's footprint.
    has_quantifiers : bool
        Whether any separating conjunct contains a quantifier (``forall``
        or ``exists``).
    has_frame : bool
        Whether a frame predicate has been attached to the heap.

    Example
    -------
    >>> frag = SeparationLogicFragment(
    ...     heap_id="h_abc",
    ...     kind=HeapKind.POINTS_TO,
    ...     pointer_count=1,
    ...     has_quantifiers=False,
    ...     has_frame=False,
    ... )
    >>> frag.kind
    <HeapKind.POINTS_TO: 'points_to'>
    """

    heap_id: str
    kind: HeapKind
    pointer_count: int
    has_quantifiers: bool
    has_frame: bool

    def classify_heap(self, heap: HeapSummary) -> str:
        """Return a short string classification for *heap*.

        Args:
            heap: The :class:`HeapSummary` to classify.

        Returns:
            One of ``"emp"``, ``"points-to"``, ``"star"``, ``"frame"``,
            ``"quantified"``, ``"allocated"``, ``"deallocated"``.

        Example:
            >>> frag = SeparationLogicFragment("h", HeapKind.EMPTY, 0, False, False)
            >>> encoder = HeapSummaryEncoder()
            >>> emp = encoder.encode_empty_heap(name="ce")
            >>> frag.classify_heap(emp)
            'emp'
        """
        hk = heap.metadata.get("heap_kind", "empty")
        mapping = {
            "empty": "emp",
            "points_to": "points-to",
            "star": "star",
            "frame": "frame",
            "quantified": "quantified",
            "allocated": "allocated",
            "deallocated": "deallocated",
        }
        return mapping.get(hk, str(hk))

    def is_symbolic_heap(self, heap: HeapSummary) -> bool:
        """Return True when *heap* is a symbolic heap (quantifier-free SL).

        A symbolic heap is a separating conjunction of points-to cells and
        pure propositional conjuncts, with no nested quantifiers.

        Args:
            heap: The :class:`HeapSummary` to test.

        Returns:
            ``True`` when the heap is in the symbolic heap fragment.
        """
        for conjunct in heap.separating_conjuncts:
            if "forall" in conjunct or "exists" in conjunct:
                return False
        hk = heap.metadata.get("heap_kind", "empty")
        return hk in ("empty", "points_to", "star")

    def count_pointers(self, heap: HeapSummary) -> int:
        """Count the number of distinct pointer locations in *heap*.

        Args:
            heap: The :class:`HeapSummary` to inspect.

        Returns:
            The size of ``heap.footprint``.

        Example:
            >>> frag = SeparationLogicFragment("h", HeapKind.STAR, 2, False, False)
            >>> encoder = HeapSummaryEncoder()
            >>> h1 = encoder.encode_points_to("0", "1")
            >>> h2 = encoder.encode_points_to("1", "2")
            >>> star = encoder.encode_star(h1, h2)
            >>> frag.count_pointers(star)
            2
        """
        return len(heap.footprint)

    def estimate_complexity(self, heap: HeapSummary) -> int:
        """Estimate the SMT proof complexity for *heap* on a 0–100 scale.

        The score accounts for pointer count, quantifiers, and frame
        annotations.

        Args:
            heap: The :class:`HeapSummary` to evaluate.

        Returns:
            Integer complexity in ``[0, 100]``.

        Example:
            >>> frag = SeparationLogicFragment("h", HeapKind.STAR, 3, False, False)
            >>> encoder = HeapSummaryEncoder()
            >>> h1 = encoder.encode_points_to("0", "1")
            >>> h2 = encoder.encode_points_to("1", "2")
            >>> star = encoder.encode_star(h1, h2)
            >>> 0 <= frag.estimate_complexity(star) <= 100
            True
        """
        ptrs = self.count_pointers(heap)
        base = min(ptrs * 5, 50)
        q_pen = 30 if self.has_quantifiers else 0
        f_pen = 10 if self.has_frame else 0
        hk = heap.metadata.get("heap_kind", "empty")
        hk_pen = {
            "empty": 0, "points_to": 0, "star": 5, "frame": 15,
            "quantified": 35, "allocated": 5, "deallocated": 5,
        }.get(hk, 10)
        return min(base + q_pen + f_pen + hk_pen, 100)

    def to_fragment_tag(self, heap: HeapSummary) -> str:
        """Map *heap* to a fragment tag string used by the solver router.

        Args:
            heap: The :class:`HeapSummary` to tag.

        Returns:
            A string such as ``"QF_SL_PTRS"``, ``"QF_SL_STAR"``, or
            ``"SL_QUANTIFIED"``.

        Example:
            >>> frag = SeparationLogicFragment("h", HeapKind.EMPTY, 0, False, False)
            >>> encoder = HeapSummaryEncoder()
            >>> emp = encoder.encode_empty_heap(name="ftag_test")
            >>> frag.to_fragment_tag(emp)
            'QF_SL_EMP'
        """
        if self.has_quantifiers:
            return "SL_QUANTIFIED"
        hk = heap.metadata.get("heap_kind", "empty")
        return {
            "empty": "QF_SL_EMP",
            "points_to": "QF_SL_PTRS",
            "star": "QF_SL_STAR",
            "allocated": "QF_SL_STAR",
            "deallocated": "QF_SL_STAR",
            "frame": "QF_SL_FRAME",
        }.get(hk, "QF_SL")


# ---------------------------------------------------------------------------
# HeapSummaryEncoder
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class HeapSummaryEncoder:
    """Encode separation-logic heaps as Z3 array constraints.

    This is the primary entry point for Ch27 heap encoding.  It maintains
    a footprint tracker (location → heap_id) and a composition log for
    auditing separating conjunctions.

    Each produced :class:`~jugeo.encodings.collection_heap_encodings.models.HeapSummary`
    stores auxiliary data in its ``metadata`` dict under the keys:

    * ``"heap_kind"``        — ``"empty"`` / ``"points_to"`` / ``"star"`` / …
    * ``"name"``             — the symbolic name used for the Z3 array symbol
    * ``"declarations"``     — list of SMT-LIB2 ``declare-*`` strings
    * ``"heap_array_decl"``  — the main ``(declare-fun heap (...) ...)`` string

    Fields
    ------
    _heap_cache : dict
        Maps heap_id → HeapSummary for deduplication.
    _footprint_tracker : dict
        Maps location string → heap_id to detect aliasing.
    _composition_log : list
        Records (h1_name, op, h2_name) entries for each compose call.

    Example
    -------
    >>> encoder = HeapSummaryEncoder()
    >>> h = encoder.encode_points_to("0", "42", heap_name="h0")
    >>> h.metadata["heap_kind"]
    'points_to'
    >>> "0" in h.footprint
    True
    """

    _heap_cache: dict[str, HeapSummary] = field(default_factory=dict)
    _footprint_tracker: dict[str, str] = field(default_factory=dict)
    _composition_log: list[tuple[str, str, str]] = field(default_factory=list)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _make_heap_id(self, name: str, kind: str) -> str:
        """Compute a stable heap ID from name and kind.

        Args:
            name: Heap symbol name.
            kind: HeapKind string.

        Returns:
            A 16-character hex digest.
        """
        return hashlib.sha256(f"{name}:{kind}".encode()).hexdigest()[:16]

    def _make_heap_name(self, base: str) -> str:
        """Generate a unique heap array symbol name.

        Args:
            base: Human-readable base (e.g. ``"heap"``).

        Returns:
            A collision-resistant name string.
        """
        return f"{base}_{uuid.uuid4().hex[:8]}"

    def _check_disjoint_footprints(
        self, h1: HeapSummary, h2: HeapSummary
    ) -> bool:
        """Return True when h1 and h2 have disjoint footprints.

        Args:
            h1: First heap summary.
            h2: Second heap summary.

        Returns:
            ``True`` iff ``h1.footprint ∩ h2.footprint = ∅``.
        """
        return len(h1.footprint & h2.footprint) == 0

    def _merge_points_to(
        self,
        d1: dict[str, str],
        d2: dict[str, str],
    ) -> dict[str, str]:
        """Merge two points-to dicts, keeping the first value on conflict.

        Args:
            d1: First points-to dict.
            d2: Second points-to dict.

        Returns:
            A merged dict with no duplicate keys.
        """
        merged: dict[str, str] = dict(d1)
        for loc, val in d2.items():
            if loc not in merged:
                merged[loc] = val
            else:
                logger.warning(
                    "_merge_points_to: location %r already present; "
                    "keeping first value %r",
                    loc, merged[loc],
                )
        return merged

    def _disjointness_assertion(
        self,
        fp1: frozenset[str],
        fp2: frozenset[str],
    ) -> str:
        """Build an SMT-LIB2 assertion that all cross-pairs (loc1, loc2) differ.

        For every ``loc1 ∈ fp1`` and ``loc2 ∈ fp2`` we assert
        ``(not (= loc1_lit loc2_lit))``.  When either footprint is empty
        the assertion is ``(assert true)`` (trivially satisfied).

        Args:
            fp1: First footprint.
            fp2: Second footprint.

        Returns:
            A single SMT-LIB2 ``(assert ...)`` string.
        """
        if not fp1 or not fp2:
            return "(assert true)"
        parts: list[str] = []
        for l1 in sorted(fp1):
            for l2 in sorted(fp2):
                ll1 = self._loc_to_smt2(l1)
                ll2 = self._loc_to_smt2(l2)
                parts.append(f"(not (= {ll1} {ll2}))")
        if len(parts) == 1:
            return f"(assert {parts[0]})"
        return f"(assert (and {' '.join(parts)}))"

    def _loc_to_smt2(self, loc: str) -> str:
        """Normalise a location identifier to an SMT-LIB2 integer literal.

        If *loc* is already a numeric string, return it as-is (abs value).
        Otherwise hash to a non-negative integer.

        Args:
            loc: Location identifier string.

        Returns:
            SMT-LIB2 integer literal string.
        """
        try:
            return str(abs(int(loc)))
        except ValueError:
            return str(int(hashlib.sha256(loc.encode()).hexdigest(), 16) % (2**30))

    def _val_to_smt2(self, val: str) -> str:
        """Normalise a value string to an SMT-LIB2 literal.

        Wraps negative integers in Z3 negation form; hashes non-numeric strings.

        Args:
            val: Value string.

        Returns:
            SMT-LIB2 literal string.
        """
        try:
            int_val = int(val)
            if int_val < 0:
                return f"(- {abs(int_val)})"
            return str(int_val)
        except ValueError:
            return str(int(hashlib.sha256(val.encode()).hexdigest(), 16) % (2**30))

    # ------------------------------------------------------------------
    # Public encoding API
    # ------------------------------------------------------------------

    def encode_points_to(
        self,
        loc: str,
        val: str,
        *,
        heap_name: str | None = None,
    ) -> HeapSummary:
        """Build a HeapSummary for the points-to predicate ``loc ↦ val``.

        Declares a Z3 array ``(declare-fun <heap_name> (Int) Int)`` and
        asserts ``(= (<heap_name> <loc_lit>) <val_lit>)``.  The footprint is
        the singleton set ``{loc}``.

        The ``metadata`` dict will contain:
        * ``"heap_kind"``     → ``"points_to"``
        * ``"name"``          → the heap array symbol name
        * ``"declarations"``  → ``["(declare-fun <name> (Int) Int)"]``

        Args:
            loc: The heap location identifier (string; will be converted to an
                integer literal via :meth:`_loc_to_smt2`).
            val: The value stored at *loc* (string; converted via
                :meth:`_val_to_smt2`).
            heap_name: Optional name for the Z3 heap array.  Auto-generated
                if ``None``.

        Returns:
            A :class:`HeapSummary` with a singleton footprint, one
            separating conjunct, and ``metadata["heap_kind"] == "points_to"``.

        Raises:
            ValueError: If *loc* is empty.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_points_to("0", "42", heap_name="h0")
            >>> h.metadata["heap_kind"]
            'points_to'
            >>> "0" in h.footprint
            True
            >>> len(h.separating_conjuncts)
            1
        """
        if not loc:
            raise ValueError("loc must be a non-empty location identifier")

        t0 = time.monotonic()
        name = heap_name if heap_name is not None else self._make_heap_name("heap")
        loc_lit = self._loc_to_smt2(loc)
        val_lit = self._val_to_smt2(val)

        heap_id = self._make_heap_id(name, "points_to")
        if heap_id in self._heap_cache:
            logger.debug("encode_points_to: cache hit for %r", name)
            return self._heap_cache[heap_id]

        heap_decl = f"(declare-fun {name} (Int) Int)"
        assertion = _POINTS_TO_TEMPLATE.format(
            heap=name, loc=loc_lit, val=val_lit
        )

        if loc in self._footprint_tracker:
            logger.warning(
                "encode_points_to: location %r already in footprint of heap %r",
                loc, self._footprint_tracker[loc],
            )
        self._footprint_tracker[loc] = heap_id

        heap = HeapSummary(
            location_sort=_DEFAULT_LOCATION_SORT,
            value_sort=_DEFAULT_VALUE_SORT,
            points_to_map={loc: val},
            footprint=frozenset({loc}),
            separating_conjuncts=[assertion],
            frame_condition=None,
            heap_id=heap_id,
            metadata={
                "heap_kind": "points_to",
                "name": name,
                "declarations": [heap_decl],
            },
        )
        self._heap_cache[heap_id] = heap
        elapsed_ms = (time.monotonic() - t0) * 1000.0
        logger.debug(
            "encode_points_to %r: loc=%r val=%r %.2f ms",
            name, loc, val, elapsed_ms,
        )
        return heap

    def encode_empty_heap(self, *, name: str | None = None) -> HeapSummary:
        """Build a HeapSummary for the empty heap ``emp``.

        The empty heap has an empty footprint and contributes no assertions.
        It is the unit element for the separating conjunction (∗).

        The ``metadata`` dict will contain:
        * ``"heap_kind"`` → ``"empty"``
        * ``"name"``      → the given or generated name

        Args:
            name: Optional logical name for the empty heap record.  Defaults
                to a generated name prefixed with ``"emp_"``.

        Returns:
            A :class:`HeapSummary` with empty footprint, empty
            ``separating_conjuncts``, and ``metadata["heap_kind"] == "empty"``.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_empty_heap(name="emp0")
            >>> h.metadata["heap_kind"]
            'empty'
            >>> len(h.footprint)
            0
            >>> len(h.separating_conjuncts)
            0
        """
        heap_name = name if name is not None else self._make_heap_name("emp")
        heap_id = self._make_heap_id(heap_name, "empty")
        if heap_id in self._heap_cache:
            return self._heap_cache[heap_id]

        heap = HeapSummary(
            location_sort=_DEFAULT_LOCATION_SORT,
            value_sort=_DEFAULT_VALUE_SORT,
            points_to_map={},
            footprint=frozenset(),
            separating_conjuncts=[],
            frame_condition=None,
            heap_id=heap_id,
            metadata={"heap_kind": "empty", "name": heap_name, "declarations": []},
        )
        self._heap_cache[heap_id] = heap
        logger.debug("encode_empty_heap: created %r", heap_name)
        return heap

    def encode_star(
        self, h1: HeapSummary, h2: HeapSummary
    ) -> HeapSummary:
        """Build the separating conjunction ``h1 ∗ h2``.

        Checks that the footprints of *h1* and *h2* are disjoint (logs a
        warning if not).  The composed heap:
        * Merges ``declarations`` from both inputs.
        * Merges ``separating_conjuncts`` from both inputs.
        * Adds a disjointness assertion for every cross-product pair.
        * Unions the footprints.
        * Merges the ``points_to_map`` dicts.

        Args:
            h1: Left heap operand.
            h2: Right heap operand.

        Returns:
            A :class:`HeapSummary` with ``metadata["heap_kind"] == "star"``.

        Raises:
            TypeError: If *h1* or *h2* are not :class:`HeapSummary` instances.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h1 = encoder.encode_points_to("0", "10", heap_name="ha")
            >>> h2 = encoder.encode_points_to("1", "20", heap_name="hb")
            >>> star = encoder.encode_star(h1, h2)
            >>> star.metadata["heap_kind"]
            'star'
            >>> len(star.footprint)
            2
        """
        t0 = time.monotonic()
        overlap = h1.footprint & h2.footprint
        if overlap:
            logger.warning(
                "encode_star: footprints overlap at %s — encoding may be UNSAT",
                sorted(overlap),
            )

        h1_name = h1.metadata.get("name", h1.heap_id[:8])
        h2_name = h2.metadata.get("name", h2.heap_id[:8])
        star_name = f"star_{h1_name}_{h2_name}"
        heap_id = self._make_heap_id(star_name, "star")
        if heap_id in self._heap_cache:
            self._composition_log.append((h1_name, "*", h2_name))
            return self._heap_cache[heap_id]

        # Merge declarations (deduplicate)
        seen_decls: set[str] = set()
        merged_decls: list[str] = []
        for d in (
            *h1.metadata.get("declarations", []),
            *h2.metadata.get("declarations", []),
        ):
            if d not in seen_decls:
                merged_decls.append(d)
                seen_decls.add(d)

        # Disjointness assertion
        disj = self._disjointness_assertion(h1.footprint, h2.footprint)

        merged_conjuncts = (
            list(h1.separating_conjuncts)
            + list(h2.separating_conjuncts)
            + [disj]
        )
        merged_pts = self._merge_points_to(h1.points_to_map, h2.points_to_map)
        merged_fp = h1.footprint | h2.footprint

        heap = HeapSummary(
            location_sort=h1.location_sort,
            value_sort=h1.value_sort,
            points_to_map=merged_pts,
            footprint=merged_fp,
            separating_conjuncts=merged_conjuncts,
            frame_condition=None,
            heap_id=heap_id,
            metadata={
                "heap_kind": "star",
                "name": star_name,
                "declarations": merged_decls,
                "operands": [h1_name, h2_name],
            },
        )
        self._heap_cache[heap_id] = heap
        self._composition_log.append((h1_name, "*", h2_name))
        elapsed_ms = (time.monotonic() - t0) * 1000.0
        logger.debug(
            "encode_star %r: fp_size=%d %.2f ms",
            star_name, len(merged_fp), elapsed_ms,
        )
        return heap

    def encode_frame(
        self, heap: HeapSummary, frame_pred: str
    ) -> HeapSummary:
        """Apply the frame rule to *heap* with frame predicate *frame_pred*.

        The resulting heap asserts everything in *heap* plus an extra
        assertion ``(assert <frame_pred>)`` representing the frame condition.
        The footprint is unchanged (the frame is outside the footprint by
        definition of the frame rule).

        Args:
            heap: The heap to frame.
            frame_pred: An SMT-LIB2 formula string for the frame condition
                (without the outer ``(assert ...)`` wrapper).

        Returns:
            A new :class:`HeapSummary` with ``metadata["heap_kind"] == "frame"``
            and ``frame_condition == frame_pred``.

        Raises:
            ValueError: If *frame_pred* is empty.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_points_to("0", "7", heap_name="hf")
            >>> framed = encoder.encode_frame(h, "(> fv 0)")
            >>> framed.metadata["heap_kind"]
            'frame'
            >>> framed.frame_condition
            '(> fv 0)'
        """
        if not frame_pred.strip():
            raise ValueError("frame_pred must be a non-empty formula string")

        frame_assertion = f"(assert {frame_pred.strip()})"
        h_name = heap.metadata.get("name", heap.heap_id[:8])
        framed_name = f"frame_{h_name}"
        heap_id = self._make_heap_id(framed_name, "frame")
        if heap_id in self._heap_cache:
            return self._heap_cache[heap_id]

        new_conjuncts = list(heap.separating_conjuncts) + [frame_assertion]

        framed = HeapSummary(
            location_sort=heap.location_sort,
            value_sort=heap.value_sort,
            points_to_map=dict(heap.points_to_map),
            footprint=heap.footprint,
            separating_conjuncts=new_conjuncts,
            frame_condition=frame_pred.strip(),
            heap_id=heap_id,
            metadata={
                "heap_kind": "frame",
                "name": framed_name,
                "declarations": list(heap.metadata.get("declarations", [])),
                "parent": h_name,
            },
        )
        self._heap_cache[heap_id] = framed
        logger.debug("encode_frame %r: frame_pred=%r", framed_name, frame_pred)
        return framed

    def encode_allocation(
        self, heap: HeapSummary, loc: str
    ) -> HeapSummary:
        """Return a new heap with location *loc* freshly allocated.

        Allocation adds *loc* to the footprint with an unconstrained value.
        A note assertion ``(assert true) ; freshly allocated <loc>`` is
        appended to the conjuncts to mark the event in the proof trace.

        Args:
            heap: The existing heap.
            loc: Location identifier to allocate.

        Returns:
            A new :class:`HeapSummary` with ``metadata["heap_kind"] == "allocated"``
            and *loc* added to the footprint.

        Raises:
            ValueError: If *loc* is already in the heap's footprint
                (double allocation).

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> emp = encoder.encode_empty_heap(name="alloc_test")
            >>> allocated = encoder.encode_allocation(emp, "loc5")
            >>> "loc5" in allocated.footprint
            True
        """
        if loc in heap.footprint:
            raise ValueError(
                f"Location {loc!r} is already in the footprint of heap "
                f"{heap.metadata.get('name', heap.heap_id)!r}; "
                f"cannot allocate twice"
            )

        h_name = heap.metadata.get("name", heap.heap_id[:8])
        alloc_name = f"alloc_{h_name}_{loc}"
        heap_id = self._make_heap_id(alloc_name, "allocated")
        if heap_id in self._heap_cache:
            return self._heap_cache[heap_id]

        alloc_note = f"(assert true) ; freshly allocated {loc}"
        new_conjuncts = list(heap.separating_conjuncts) + [alloc_note]
        new_fp = heap.footprint | {loc}

        allocated = HeapSummary(
            location_sort=heap.location_sort,
            value_sort=heap.value_sort,
            points_to_map=dict(heap.points_to_map),
            footprint=new_fp,
            separating_conjuncts=new_conjuncts,
            frame_condition=heap.frame_condition,
            heap_id=heap_id,
            metadata={
                "heap_kind": "allocated",
                "name": alloc_name,
                "declarations": list(heap.metadata.get("declarations", [])),
                "allocated_loc": loc,
                "parent": h_name,
            },
        )
        self._heap_cache[heap_id] = allocated
        logger.debug(
            "encode_allocation: allocated %r in heap %r", loc, h_name
        )
        return allocated

    def encode_deallocation(
        self, heap: HeapSummary, loc: str
    ) -> HeapSummary:
        """Return a new heap with location *loc* removed from the footprint.

        Deallocation invalidates the points-to assertion for *loc* and
        removes it from the footprint.  A note is added to the conjuncts to
        record the event.

        Args:
            heap: The existing heap.
            loc: Location identifier to deallocate.

        Returns:
            A new :class:`HeapSummary` with ``metadata["heap_kind"] == "deallocated"``
            and *loc* removed from the footprint.

        Raises:
            ValueError: If *loc* is not in the heap's footprint.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_points_to("3", "99", heap_name="hd")
            >>> freed = encoder.encode_deallocation(h, "3")
            >>> "3" not in freed.footprint
            True
        """
        if loc not in heap.footprint:
            raise ValueError(
                f"Location {loc!r} is not in the footprint of heap "
                f"{heap.metadata.get('name', heap.heap_id)!r}; cannot deallocate"
            )

        h_name = heap.metadata.get("name", heap.heap_id[:8])
        dealloc_name = f"dealloc_{h_name}_{loc}"
        heap_id = self._make_heap_id(dealloc_name, "deallocated")
        if heap_id in self._heap_cache:
            return self._heap_cache[heap_id]

        dealloc_note = f"(assert true) ; deallocated {loc}"
        new_conjuncts = list(heap.separating_conjuncts) + [dealloc_note]
        new_fp = heap.footprint - {loc}
        new_pts = {l: v for l, v in heap.points_to_map.items() if l != loc}
        self._footprint_tracker.pop(loc, None)

        deallocated = HeapSummary(
            location_sort=heap.location_sort,
            value_sort=heap.value_sort,
            points_to_map=new_pts,
            footprint=new_fp,
            separating_conjuncts=new_conjuncts,
            frame_condition=heap.frame_condition,
            heap_id=heap_id,
            metadata={
                "heap_kind": "deallocated",
                "name": dealloc_name,
                "declarations": list(heap.metadata.get("declarations", [])),
                "freed_loc": loc,
                "parent": h_name,
            },
        )
        self._heap_cache[heap_id] = deallocated
        logger.debug(
            "encode_deallocation: freed %r from heap %r", loc, h_name
        )
        return deallocated

    def verify_separation(
        self,
        h1: HeapSummary,
        h2: HeapSummary,
        session: Any,
    ) -> Any:
        """Build and check a Z3 query asserting h1 and h2 have disjoint footprints.

        Constructs an SMT-LIB2 script that declares integer constants for
        every location in both footprints, then asserts that all cross-product
        pairs are distinct.  Returns SAT if separation holds.

        Args:
            h1: First heap summary.
            h2: Second heap summary.
            session: A Z3Session-compatible object with a ``check`` method.

        Returns:
            A :class:`~jugeo.solver.z3_session.Z3Result` — SAT means disjoint,
            UNSAT means aliases exist.

        Raises:
            RuntimeError: If *session* is ``None``.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h1 = encoder.encode_points_to("0", "1")
            >>> h2 = encoder.encode_points_to("1", "2")
            >>> # result = encoder.verify_separation(h1, h2, session)
        """
        if session is None:
            raise RuntimeError("Z3 session required for verify_separation")

        all_locs = h1.footprint | h2.footprint
        lines: list[str] = ["(set-logic QF_LIA)"]
        for loc in sorted(all_locs):
            loc_lit = self._loc_to_smt2(loc)
            lines.append(f"(declare-const loc_{loc_lit} Int)")
            lines.append(f"(assert (= loc_{loc_lit} {loc_lit}))")

        for l1 in sorted(h1.footprint):
            for l2 in sorted(h2.footprint):
                ll1 = self._loc_to_smt2(l1)
                ll2 = self._loc_to_smt2(l2)
                lines.append(f"(assert (not (= {ll1} {ll2})))")

        lines.append("(check-sat)")
        smt2 = "\n".join(lines)
        logger.debug(
            "verify_separation: %d locs, query size %d", len(all_locs), len(smt2)
        )
        if hasattr(session, "check_smt2"):
            return session.check_smt2(smt2)
        return session.check(smt2)

    def verify_entailment(
        self,
        premise: HeapSummary,
        conclusion: HeapSummary,
        session: Any,
    ) -> Any:
        """Check that *premise* logically entails *conclusion*.

        Builds an SMT-LIB2 query asserting all conjuncts of *premise* and the
        negation of the conclusion's conjuncts.  UNSAT means the entailment is
        valid (premise ⊨ conclusion).

        Args:
            premise: The antecedent heap.
            conclusion: The consequent heap.
            session: A Z3Session-compatible object.

        Returns:
            A :class:`~jugeo.solver.z3_session.Z3Result` — UNSAT iff valid.

        Raises:
            RuntimeError: If *session* is ``None``.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_points_to("0", "5", heap_name="ent_h")
            >>> # result = encoder.verify_entailment(h, h, session)
            >>> # UNSAT means h ⊨ h (reflexivity)
        """
        if session is None:
            raise RuntimeError("Z3 session required for verify_entailment")

        all_decls = list(dict.fromkeys(
            premise.metadata.get("declarations", [])
            + conclusion.metadata.get("declarations", [])
        ))

        # Negate each conclusion conjunct in turn
        neg_parts: list[str] = []
        for conj in conclusion.separating_conjuncts:
            inner = conj.strip()
            if inner.startswith("(assert "):
                inner = inner[len("(assert "):-1]
            if inner.strip() in {"true", "(assert true)"}:
                continue
            neg_parts.append(f"(not {inner})")

        if not neg_parts:
            lines = ["(set-logic QF_AUFLIA)", *all_decls,
                     *premise.separating_conjuncts, "(check-sat)"]
        else:
            neg_disj = (
                f"(or {' '.join(neg_parts)})"
                if len(neg_parts) > 1 else neg_parts[0]
            )
            lines = [
                "(set-logic QF_AUFLIA)",
                *all_decls,
                *premise.separating_conjuncts,
                f"(assert {neg_disj})",
                "(check-sat)",
            ]
        smt2 = "\n".join(lines)
        logger.debug("verify_entailment: query size %d", len(smt2))
        if hasattr(session, "check_smt2"):
            return session.check_smt2(smt2)
        return session.check(smt2)

    def extract_footprint(self, heap: HeapSummary) -> frozenset[str]:
        """Return the footprint of *heap*.

        Args:
            heap: The :class:`HeapSummary` to inspect.

        Returns:
            The ``footprint`` frozenset.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_points_to("loc0", "0")
            >>> fp = encoder.extract_footprint(h)
            >>> "loc0" in fp
            True
        """
        return heap.footprint

    def to_separation_formula(self, heap: HeapSummary) -> str:
        """Produce a human-readable separation-logic formula for *heap*.

        Returns a string like ``"loc0 ↦ 42 * loc1 ↦ 7"`` or ``"emp"`` for
        the empty heap.

        Args:
            heap: The :class:`HeapSummary` to render.

        Returns:
            A Unicode separation-logic formula string.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_empty_heap(name="sl_empty")
            >>> encoder.to_separation_formula(h)
            'emp'
        """
        pts = heap.points_to_map
        if not pts:
            return _EMP_HEAP_EXPR
        parts = [f"{loc} ↦ {val}" for loc, val in sorted(pts.items())]
        formula = _STAR_SEPARATOR.join(parts)
        if heap.frame_condition:
            formula = f"({formula}) * frame({heap.frame_condition})"
        return formula

    def to_smt2(self, heap: HeapSummary) -> str:
        """Serialize the complete heap encoding to an SMT-LIB2 string.

        The output is a valid SMT-LIB2 script containing:
        * A header comment with encoding metadata.
        * A ``(set-logic QF_AUFLIA)`` directive.
        * All declarations.
        * All separating conjuncts.
        * A ``(check-sat)`` footer.

        Args:
            heap: The :class:`HeapSummary` to serialize.

        Returns:
            A multi-line SMT-LIB2 string.

        Example:
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_empty_heap(name="smt2_test")
            >>> smt = encoder.to_smt2(h)
            >>> "(check-sat)" in smt
            True
        """
        hk = heap.metadata.get("heap_kind", "?")
        name = heap.metadata.get("name", heap.heap_id[:8])
        lines: list[str] = [
            f"; JuGeo heap encoding v{_HEAP_ENCODING_VERSION}",
            f"; heap_kind={hk}  name={name}",
            f"; footprint_size={len(heap.footprint)}",
            "(set-logic QF_AUFLIA)",
            "",
            "; --- Declarations ---",
        ]
        for decl in heap.metadata.get("declarations", []):
            lines.append(decl)
        lines.append("")
        lines.append("; --- Separating Conjuncts ---")
        for conj in heap.separating_conjuncts:
            lines.append(conj)
        if heap.frame_condition:
            lines.append("")
            lines.append("; --- Frame Condition ---")
            lines.append(f"(assert {heap.frame_condition})")
        lines.append("")
        lines.append("(check-sat)")
        lines.append("(get-model)")
        return "\n".join(lines)

    def clear_cache(self) -> None:
        """Invalidate the internal heap cache and footprint tracker."""
        self._heap_cache.clear()
        self._footprint_tracker.clear()
        logger.debug("HeapSummaryEncoder: cache cleared")

    def get_composition_log(self) -> list[tuple[str, str, str]]:
        """Return the composition log as a list of (h1_name, op, h2_name) tuples.

        Returns:
            A copy of the internal composition log.
        """
        return list(self._composition_log)


# ---------------------------------------------------------------------------
# HeapCompositionEngine
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class HeapCompositionEngine:
    """Higher-level combinators for composing multiple heap summaries.

    Wraps a :class:`HeapSummaryEncoder` to provide safe composition,
    fold-with-star, overlap detection, and summary formatting.

    Example
    -------
    >>> engine = HeapCompositionEngine()
    >>> h1 = engine._encoder.encode_points_to("10", "1")
    >>> h2 = engine._encoder.encode_points_to("11", "2")
    >>> composed = engine.compose_all([h1, h2])
    >>> composed.metadata["heap_kind"]
    'star'
    """

    _encoder: HeapSummaryEncoder = field(default_factory=HeapSummaryEncoder)

    def safe_compose(
        self, h1: HeapSummary, h2: HeapSummary
    ) -> HeapSummary | None:
        """Compose *h1* and *h2* if their footprints are disjoint.

        Returns the star-composition if footprints are disjoint, or ``None``
        if they overlap (indicating a potential alias violation).

        Args:
            h1: First heap.
            h2: Second heap.

        Returns:
            A star-composed :class:`HeapSummary`, or ``None`` on overlap.

        Example:
            >>> engine = HeapCompositionEngine()
            >>> ha = engine._encoder.encode_points_to("0", "1")
            >>> hb = engine._encoder.encode_points_to("1", "2")
            >>> result = engine.safe_compose(ha, hb)
            >>> result is not None
            True
        """
        if h1.footprint & h2.footprint:
            overlap = sorted(h1.footprint & h2.footprint)
            logger.info(
                "safe_compose: footprints overlap at %s; returning None", overlap
            )
            return None
        return self._encoder.encode_star(h1, h2)

    def compose_all(self, heaps: list[HeapSummary]) -> HeapSummary:
        """Fold a list of heap summaries with separating conjunction.

        Left-folds: ``heaps[0] ∗ heaps[1] ∗ … ∗ heaps[n-1]``.  If *heaps*
        is empty, returns the empty heap.

        Args:
            heaps: List of :class:`HeapSummary` objects to compose.

        Returns:
            The star-composed heap.

        Raises:
            ValueError: If any consecutive pair has overlapping footprints.

        Example:
            >>> engine = HeapCompositionEngine()
            >>> h1 = engine._encoder.encode_points_to("20", "1")
            >>> h2 = engine._encoder.encode_points_to("21", "2")
            >>> h3 = engine._encoder.encode_points_to("22", "3")
            >>> result = engine.compose_all([h1, h2, h3])
            >>> len(result.footprint)
            3
        """
        if not heaps:
            return self._encoder.encode_empty_heap()
        result = heaps[0]
        for heap in heaps[1:]:
            composed = self.safe_compose(result, heap)
            if composed is None:
                overlap = sorted(result.footprint & heap.footprint)
                raise ValueError(
                    f"compose_all: aliasing detected at locations {overlap}"
                )
            result = composed
        return result

    def check_frame_condition(
        self, heap: HeapSummary, frame: str
    ) -> bool:
        """Check whether *frame* is syntactically present in the heap.

        Returns ``True`` if ``heap.frame_condition == frame`` or if *frame*
        appears as a substring of any separating conjunct.  For semantic
        frame checking use :meth:`HeapInvariantChecker.verify_frame_rule`.

        Args:
            heap: The :class:`HeapSummary` to inspect.
            frame: The frame predicate string to look for.

        Returns:
            ``True`` if the frame condition is present.

        Example:
            >>> engine = HeapCompositionEngine()
            >>> h = engine._encoder.encode_empty_heap()
            >>> engine.check_frame_condition(h, "some_pred")
            False
        """
        if heap.frame_condition == frame:
            return True
        return any(frame in conj for conj in heap.separating_conjuncts)

    def summarize_composition(self, heaps: list[HeapSummary]) -> str:
        """Produce a human-readable summary of a list of heaps.

        Args:
            heaps: List of :class:`HeapSummary` objects.

        Returns:
            A multi-line summary string with footprint sizes and kinds.

        Example:
            >>> engine = HeapCompositionEngine()
            >>> h = engine._encoder.encode_empty_heap(name="sum_test")
            >>> summary = engine.summarize_composition([h])
            >>> "emp" in summary
            True
        """
        if not heaps:
            return "No heaps to summarize."
        lines: list[str] = [f"Composition summary ({len(heaps)} heaps):"]
        total_locs: set[str] = set()
        for i, heap in enumerate(heaps):
            hk = heap.metadata.get("heap_kind", "?")
            name = heap.metadata.get("name", heap.heap_id[:8])
            n_conj = len(heap.separating_conjuncts)
            fp_size = len(heap.footprint)
            lines.append(
                f"  [{i}] {name}: kind={hk}  "
                f"footprint_size={fp_size}  conjuncts={n_conj}"
            )
            total_locs |= heap.footprint
        lines.append(f"  Total unique locations: {len(total_locs)}")
        # Overlap detection
        seen: set[str] = set()
        overlaps: set[str] = set()
        for heap in heaps:
            overlaps |= seen & heap.footprint
            seen |= heap.footprint
        if overlaps:
            lines.append(f"  ⚠  Aliased locations: {sorted(overlaps)}")
        else:
            lines.append("  ✓  No aliasing detected.")
        return "\n".join(lines)

    def find_overlap(
        self, h1: HeapSummary, h2: HeapSummary
    ) -> frozenset[str]:
        """Return the set of locations that appear in both footprints.

        Args:
            h1: First heap.
            h2: Second heap.

        Returns:
            ``frozenset`` of aliased location strings.

        Example:
            >>> engine = HeapCompositionEngine()
            >>> ha = engine._encoder.encode_points_to("5", "0")
            >>> hb = engine._encoder.encode_points_to("5", "1")
            >>> engine.find_overlap(ha, hb)
            frozenset({'5'})
        """
        return h1.footprint & h2.footprint


# ---------------------------------------------------------------------------
# HeapInvariantChecker
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class HeapInvariantChecker:
    """Verify structural invariants of heap summaries.

    Integrates with a Z3Session to check dangling-pointer freedom,
    single-ownership, and frame-rule correctness.

    Example
    -------
    >>> checker = HeapInvariantChecker()
    >>> encoder = HeapSummaryEncoder()
    >>> h = encoder.encode_points_to("0", "1")
    >>> checker.check_no_dangling(h, frozenset({"0"}))
    True
    """

    _encoder: HeapSummaryEncoder = field(default_factory=HeapSummaryEncoder)

    def check_no_dangling(
        self,
        heap: HeapSummary,
        allocated_set: frozenset[str],
    ) -> bool:
        """Check that every location in the footprint is in *allocated_set*.

        A "dangling" location appears in the footprint but not in
        *allocated_set*, corresponding to a use-after-free or uninitialised
        pointer dereference.

        Args:
            heap: The :class:`HeapSummary` to check.
            allocated_set: The set of currently allocated location strings.

        Returns:
            ``True`` if no dangling pointers are found; ``False`` otherwise.

        Example:
            >>> checker = HeapInvariantChecker()
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_points_to("loc0", "5")
            >>> checker.check_no_dangling(h, frozenset({"loc0"}))
            True
            >>> checker.check_no_dangling(h, frozenset())
            False
        """
        dangling = heap.footprint - allocated_set
        if dangling:
            logger.warning(
                "check_no_dangling: dangling locations %s in heap %r",
                sorted(dangling),
                heap.metadata.get("name", heap.heap_id[:8]),
            )
            return False
        return True

    def check_single_ownership(
        self, heaps: list[HeapSummary]
    ) -> bool:
        """Verify that no location appears in more than one heap's footprint.

        Args:
            heaps: List of :class:`HeapSummary` objects to check.

        Returns:
            ``True`` if all footprints are pairwise disjoint.

        Example:
            >>> checker = HeapInvariantChecker()
            >>> encoder = HeapSummaryEncoder()
            >>> h1 = encoder.encode_points_to("0", "1")
            >>> h2 = encoder.encode_points_to("1", "2")
            >>> checker.check_single_ownership([h1, h2])
            True
        """
        seen: set[str] = set()
        for heap in heaps:
            overlap = seen & heap.footprint
            if overlap:
                logger.warning(
                    "check_single_ownership: location(s) %s owned by multiple heaps",
                    sorted(overlap),
                )
                return False
            seen |= heap.footprint
        return True

    def verify_frame_rule(
        self,
        heap: HeapSummary,
        session: Any,
    ) -> Any:
        """Verify that the frame condition of *heap* is satisfiable.

        Constructs a Z3 query from the heap's declarations, separating
        conjuncts, and frame condition assertion.  Returns SAT if the
        heap-plus-frame is consistent.

        Args:
            heap: The :class:`HeapSummary` with a frame condition to check.
            session: A Z3Session-compatible object.

        Returns:
            A :class:`~jugeo.solver.z3_session.Z3Result`.

        Raises:
            RuntimeError: If *session* is ``None``.
            ValueError: If the heap has no frame condition set.
        """
        if session is None:
            raise RuntimeError("Z3 session required for verify_frame_rule")
        if not heap.frame_condition:
            raise ValueError(
                f"Heap {heap.metadata.get('name', heap.heap_id)!r} has no "
                "frame condition; use encode_frame() first"
            )
        smt2 = self._encoder.to_smt2(heap)
        logger.debug(
            "verify_frame_rule: %r query size %d",
            heap.metadata.get("name", heap.heap_id[:8]),
            len(smt2),
        )
        if hasattr(session, "check_smt2"):
            return session.check_smt2(smt2)
        return session.check(smt2)

    def summarize_invariants(self, heap: HeapSummary) -> str:
        """Produce a human-readable summary of the heap's structural invariants.

        Args:
            heap: The :class:`HeapSummary` to summarize.

        Returns:
            A multi-line string listing footprint, points-to map, and frame.

        Example:
            >>> checker = HeapInvariantChecker()
            >>> encoder = HeapSummaryEncoder()
            >>> h = encoder.encode_empty_heap(name="inv_sum")
            >>> summary = checker.summarize_invariants(h)
            >>> "empty" in summary or "emp" in summary
            True
        """
        hk = heap.metadata.get("heap_kind", "?")
        name = heap.metadata.get("name", heap.heap_id[:8])
        n_conj = len(heap.separating_conjuncts)

        lines: list[str] = [
            f"Heap invariant summary for {name!r}:",
            f"  heap_kind     : {hk}",
            f"  footprint     : {{{', '.join(sorted(heap.footprint))}}}",
            f"  pointer count : {len(heap.points_to_map)}",
            f"  conjuncts     : {n_conj}",
            f"  frame cond    : {heap.frame_condition or 'none'}",
        ]
        if heap.points_to_map:
            lines.append("  points-to map :")
            for loc, val in sorted(heap.points_to_map.items()):
                lines.append(f"    {loc} ↦ {val}")
        sl_formula = self._encoder.to_separation_formula(heap)
        lines.append(f"  SL formula    : {sl_formula}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Module-level convenience function
# ---------------------------------------------------------------------------


def encode_points_to_quick(loc: str, val: str) -> HeapSummary:
    """Convenience wrapper: encode a points-to cell with a fresh encoder.

    Equivalent to ``HeapSummaryEncoder().encode_points_to(loc, val)``.

    Args:
        loc: Location identifier.
        val: Value string.

    Returns:
        A :class:`HeapSummary` with ``metadata["heap_kind"] == "points_to"``.

    Example:
        >>> h = encode_points_to_quick("0", "42")
        >>> h.metadata["heap_kind"]
        'points_to'
        >>> "0" in h.footprint
        True
    """
    return HeapSummaryEncoder().encode_points_to(loc, val)
