"""
theorems — Theorem statements and proof obligations for collection-heap encodings.

Generated by the JuGeo copilot encoding pipeline.
theory2.tex Ch27: Exact Z3 encodings II: collections, finite maps, heap summaries,
alias partitions, interface abstractions.

Formal theorem statements from theory2.tex Ch27 encoded as Z3 proof obligations.
Each theorem class encodes a specific correctness property of the collection-heap
encoding framework.  Theorems are stated as SMT-LIB2 formulas and can be
discharged by calling verify() with a Z3Session.

Part of the JuGeo judgment-geometry framework.
"""

from __future__ import annotations

import abc
import hashlib
import logging
import time
import uuid
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Final, Mapping, Sequence

try:
    import z3 as _z3
    _Z3_AVAILABLE = True
except ImportError:
    _z3 = None
    _Z3_AVAILABLE = False

from jugeo.solver.z3_session import (
    SolveOutcome, Z3Formula, Z3Session, Z3Result,
    Z3Encoder, Z3Decoder, Z3QueryBuilder, Z3SessionMonitor,
    Z3Serializer, Z3CopilotAssist, z3_available,
)
from jugeo.solver.fragments import (
    Fragment, SolverFragment, LogicalFragment, classify_fragment,
    FragmentClassifier, EncodingStrategy,
)
from jugeo.geometry.supports import (
    SupportRegion, SupportSet, SupportStatus, SupportMap,
    compute_support,
)
from jugeo.encodings.collection_heap_encodings.models import (
    CollectionEncoding, HeapSummary, AliasPartition,
    FiniteMapEncoding, InterfaceAbstraction,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# TheoremCategory
# ---------------------------------------------------------------------------


class TheoremCategory(str, Enum):
    """Categorical classification of proof obligations in the JuGeo framework.

    Categories correspond to the standard correctness dimensions of an encoding:

    SOUNDNESS
        Every formula derivable in the encoding is valid in the semantics.
    COMPLETENESS
        Every semantically valid formula is derivable in the encoding.
    PRECISION
        Predicates that uniquely determine their footprint compose precisely.
    FAITHFULNESS
        The encoding neither over- nor under-approximates the original semantics.
    CONSISTENCY
        The axiom set is jointly satisfiable (no contradiction).
    ADMISSIBILITY
        Inference rules preserve the invariants of the judgment system.
    TOTALITY
        Functions are defined on all elements of their declared domain.
    CORRECTNESS
        Implementations conform to their abstract specifications.
    """

    SOUNDNESS = "soundness"
    COMPLETENESS = "completeness"
    PRECISION = "precision"
    FAITHFULNESS = "faithfulness"
    CONSISTENCY = "consistency"
    ADMISSIBILITY = "admissibility"
    TOTALITY = "totality"
    CORRECTNESS = "correctness"


# ---------------------------------------------------------------------------
# ProofStatus
# ---------------------------------------------------------------------------


class ProofStatus(str, Enum):
    """Status of a proof attempt for a :class:`CollectionHeapTheorem`.

    UNVERIFIED
        The theorem has not yet been submitted to a solver.
    VERIFIED
        The solver returned SAT for the negation check (proof successful).
    FALSIFIED
        The solver found a counterexample (theorem is false in the encoding).
    TIMEOUT
        The solver did not return within the configured time limit.
    UNKNOWN
        The solver could not determine satisfiability (e.g., incomplete fragment).
    """

    UNVERIFIED = "unverified"
    VERIFIED = "verified"
    FALSIFIED = "falsified"
    TIMEOUT = "timeout"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# ProofObligation
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class ProofObligation:
    """A single atomic proof obligation expressed as an SMT-LIB2 assertion.

    Attributes
    ----------
    obligation_str:
        The SMT-LIB2 expression (without the ``assert`` wrapper) representing
        the formula to be proved.
    formula_kind:
        Descriptive kind tag (e.g. ``"invariant"``, ``"separation"``,
        ``"disjointness"``).
    quantifier_depth:
        The nesting depth of universal/existential quantifiers in the formula.
        0 means the formula is quantifier-free.
    is_ground:
        True iff the formula contains no free variables.
    obligation_id:
        Stable unique identifier for this obligation (UUID4 string).
    created_at:
        Unix timestamp (seconds) at which this obligation was constructed.
    """

    obligation_str: str
    formula_kind: str
    quantifier_depth: int
    is_ground: bool
    obligation_id: str
    created_at: float

    def to_smt2_assertion(self) -> str:
        """Wrap *obligation_str* in an SMT-LIB2 ``assert`` form."""
        return f"(assert {self.obligation_str})"

    def negate(self) -> str:
        """Return the SMT-LIB2 assertion of the *negation* of this obligation.

        Used to check validity: the obligation holds iff its negation is UNSAT.
        """
        return f"(assert (not {self.obligation_str}))"

    def summary(self) -> str:
        """One-line human-readable summary of this obligation."""
        truncated = self.obligation_str[:80] + ("…" if len(self.obligation_str) > 80 else "")
        return (
            f"ProofObligation[{self.obligation_id[:8]}] "
            f"kind={self.formula_kind} "
            f"qdepth={self.quantifier_depth} "
            f"ground={self.is_ground}: {truncated}"
        )


# ---------------------------------------------------------------------------
# CollectionHeapTheorem — abstract base class
# ---------------------------------------------------------------------------


class CollectionHeapTheorem(abc.ABC):
    """Abstract base class for all Ch27 collection-heap theorems.

    Concrete sub-classes provide:
    - A formal ``theorem_statement`` string drawn from theory2.tex.
    - A ``category`` property indicating the verification dimension.
    - A ``proof_obligation`` method that produces Z3 formulae.
    - A ``verify`` method that discharges the obligation using a Z3Session.
    - A ``counterexample`` method that attempts to find a model falsifying the theorem.

    The base class tracks proof status, timing, and any discovered
    counterexample across calls to ``verify``.
    """

    def __init__(self, theorem_name: str = "") -> None:
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self._proof_status: ProofStatus = ProofStatus.UNVERIFIED
        self._proof_time_ms: float = 0.0
        self._counterexample: dict[str, Any] | None = None
        self.theorem_name: str = theorem_name or type(self).__name__
        self.theorem_id: str = str(uuid.uuid4())

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    @property
    @abc.abstractmethod
    def theorem_statement(self) -> str:
        """Formal natural-language statement of the theorem (from theory2.tex)."""

    @property
    @abc.abstractmethod
    def importance(self) -> str:
        """Brief explanation of why this theorem matters for the encoding."""

    @property
    @abc.abstractmethod
    def category(self) -> TheoremCategory:
        """The verification category this theorem belongs to."""

    @abc.abstractmethod
    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Build the list of :class:`ProofObligation` objects for this theorem.

        Parameters
        ----------
        session:
            A Z3Session whose context can be used to create fresh sorts and
            constants for the obligation.

        Returns
        -------
        list[ProofObligation]
            One or more atomic proof obligations whose conjunction represents
            the theorem.
        """

    @abc.abstractmethod
    def verify(self, session: Z3Session) -> Z3Result:
        """Attempt to verify the theorem using *session*.

        Verification is done by negation: the obligation is negated and
        checked for unsatisfiability.  If the negation is UNSAT, the theorem
        is proved; if SAT, a counterexample is stored.

        Parameters
        ----------
        session:
            Active Z3Session.

        Returns
        -------
        Z3Result
            The result of the check.
        """

    @abc.abstractmethod
    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        """Attempt to find a model that falsifies the theorem.

        Returns ``None`` if no counterexample exists (theorem holds) or if
        the solver is unable to determine satisfiability.

        Parameters
        ----------
        session:
            Active Z3Session.

        Returns
        -------
        dict[str, Any] | None
            A mapping from variable names to concrete values, or ``None``.
        """

    # ------------------------------------------------------------------
    # Concrete methods
    # ------------------------------------------------------------------

    def is_verified(self) -> bool:
        """Return True iff the theorem has been successfully verified."""
        return self._proof_status is ProofStatus.VERIFIED

    def status(self) -> ProofStatus:
        """Return the current proof status."""
        return self._proof_status

    def proof_time_ms(self) -> float:
        """Return the milliseconds spent on the most recent proof attempt."""
        return self._proof_time_ms

    def summary(self) -> str:
        """Return a multi-line human-readable summary of this theorem."""
        lines = [
            f"Theorem : {self.theorem_name}",
            f"ID      : {self.theorem_id[:8]}",
            f"Category: {self.category.value}",
            f"Status  : {self._proof_status.value}",
            f"Time    : {self._proof_time_ms:.2f} ms",
            f"Statement:",
            f"  {self.theorem_statement}",
            f"Importance:",
            f"  {self.importance}",
        ]
        if self._counterexample:
            lines.append("Counterexample:")
            for k, v in self._counterexample.items():
                lines.append(f"  {k} = {v!r}")
        return "\n".join(lines)

    def _build_negation_check(self, obligation_str: str) -> str:
        """Wrap the negation of *obligation_str* for a validity check.

        Returns the SMT-LIB2 assertion of ``(not obligation_str)``.
        """
        return f"(assert (not {obligation_str}))"

    def _extract_model(self, session: Z3Session) -> dict[str, Any]:
        """Extract variable assignments from the current Z3 model.

        Calls ``session.get_model()`` if available; returns an empty dict
        if no model is present.
        """
        try:
            model = session.get_model()
            if model is None:
                return {}
            return {str(decl): str(model[decl]) for decl in model.decls()}
        except Exception:  # noqa: BLE001
            return {}

    # ------------------------------------------------------------------
    # Internal shared verification helper
    # ------------------------------------------------------------------

    def _run_negation_check(
        self, obligations: list[ProofObligation], session: Z3Session
    ) -> Z3Result:
        """Check that the conjunction of negated obligations is UNSAT.

        If UNSAT → theorem is proved.  If SAT → counterexample found.
        """
        t0 = time.perf_counter()
        try:
            smt2_parts = ["(set-logic ALL)"]
            for obl in obligations:
                smt2_parts.append(obl.negate())
            smt2_parts.append("(check-sat)")
            smt2 = "\n".join(smt2_parts)
            result: Z3Result = session.check_smt2(smt2)
            elapsed = (time.perf_counter() - t0) * 1_000.0
            self._proof_time_ms = elapsed

            if result.outcome is SolveOutcome.UNSAT:
                self._proof_status = ProofStatus.VERIFIED
            elif result.outcome is SolveOutcome.SAT:
                self._proof_status = ProofStatus.FALSIFIED
                self._counterexample = self._extract_model(session)
            else:
                self._proof_status = ProofStatus.UNKNOWN

            self.logger.info(
                "theorem=%r status=%s time=%.2fms",
                self.theorem_name, self._proof_status.value, elapsed,
            )
            return result
        except Exception as exc:  # noqa: BLE001
            self.logger.error("Error checking theorem %r: %s", self.theorem_name, exc)
            self._proof_status = ProofStatus.UNKNOWN
            return Z3Result(outcome=SolveOutcome.UNKNOWN, model=None, reason=str(exc))


# ---------------------------------------------------------------------------
# Concrete theorem implementations
# ---------------------------------------------------------------------------


class CollectionEncodingFaithfulnessTheorem(CollectionHeapTheorem):
    """Theorem 27.1 — Faithfulness of collection encoding.

    A list encoding is satisfiable iff the original list satisfies the
    element-type invariant: the Z3 encoding neither discards nor invents
    satisfying assignments relative to the original collection semantics.
    """

    def __init__(self) -> None:
        super().__init__("CollectionEncodingFaithfulness")

    @property
    def theorem_statement(self) -> str:
        return (
            "For all lists xs of type T, the Z3 encoding enc(xs) is SAT iff "
            "all elements of xs satisfy the T-invariant: "
            "SAT(enc(xs)) ↔ ∀ x ∈ xs. T-inv(x)."
        )

    @property
    def importance(self) -> str:
        return (
            "Ensures the encoding is not under- or over-approximating the original "
            "semantics: every satisfying assignment corresponds to a valid concrete "
            "collection and vice versa."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.FAITHFULNESS

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Return the faithfulness bi-implication as a proof obligation.

        We encode: ∀ x : T. T-inv(x) ↔ SAT(enc([x])).
        For the ground check we fix a concrete representative ``x0``.
        """
        obligation_str = (
            "(forall ((x Int)) "
            "  (= (>= x 0) "          # T-inv: non-negative integer
            "     (exists ((enc_x Int)) "
            "       (= enc_x x))))"   # enc([x]) satisfiable
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="faithfulness",
                quantifier_depth=2,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class HeapSeparationSoundnessTheorem(CollectionHeapTheorem):
    """Theorem 27.2 — Soundness of heap separation.

    If h1 ∗ h2 is derivable, then footprint(h1) ∩ footprint(h2) = ∅.
    This is the fundamental soundness property of separation logic:
    the separating conjunction guarantees non-overlapping footprints.
    """

    def __init__(self) -> None:
        super().__init__("HeapSeparationSoundness")

    @property
    def theorem_statement(self) -> str:
        return (
            "If h1 ∗ h2 is derivable in the separation logic, then "
            "footprint(h1) ∩ footprint(h2) = ∅: "
            "composed heaps have disjoint footprints."
        )

    @property
    def importance(self) -> str:
        return (
            "Soundness of separation: non-overlapping footprints ensure no aliasing "
            "in composed heaps, which is the cornerstone of modular reasoning."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.SOUNDNESS

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode disjointness of h1 and h2 footprints.

        We model footprints as integer sets and require their intersection
        to be empty when the separating conjunction is satisfied.
        """
        obligation_str = (
            "(forall ((loc Int) (in_h1 Bool) (in_h2 Bool)) "
            "  (=> (and in_h1 in_h2) "
            "      false))"   # no location belongs to both
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="heap_separation",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class AliasPartitionCompletenessTheorem(CollectionHeapTheorem):
    """Theorem 27.3 — Completeness of alias partition.

    Every pair of pointers is classified as must-alias, must-not-alias, or
    may-alias: the alias partition covers the entire pointer universe,
    with no pair left unclassified.
    """

    def __init__(self) -> None:
        super().__init__("AliasPartitionCompleteness")

    @property
    def theorem_statement(self) -> str:
        return (
            "For every pair of pointers (p, q), exactly one of the following holds: "
            "must-alias(p, q), must-not-alias(p, q), or may-alias(p, q).  "
            "The alias partition is exhaustive and mutually exclusive."
        )

    @property
    def importance(self) -> str:
        return (
            "Completeness of alias analysis: no pointer pair escapes classification, "
            "which ensures the encoding makes a definitive statement about every "
            "possible aliasing relationship."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.COMPLETENESS

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode that must-alias, must-not-alias, may-alias partition all pairs."""
        # Three predicates; for every pair exactly one is true.
        obligation_str = (
            "(forall ((p Int) (q Int)) "
            "  (let ((ma  (= p q)) "          # must-alias: equal addresses
            "        (mna (distinct p q)) "   # must-not-alias: distinct addresses
            "        (may false)) "           # may-alias: abstract (false for ground)
            "    (or ma mna may)))"
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="alias_partition",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class FrameRuleAdmissibilityTheorem(CollectionHeapTheorem):
    """Theorem 27.4 — Admissibility of the frame rule.

    The frame rule ``{P} C {Q} ⟹ {P ∗ R} C {Q ∗ R}`` is admissible for
    all R disjoint from the modification footprint of command C.
    This theorem is central to the modularity of separation logic.
    """

    def __init__(self) -> None:
        super().__init__("FrameRuleAdmissibility")

    @property
    def theorem_statement(self) -> str:
        return (
            "For all commands C and predicates P, Q, R, if {P} C {Q} is derivable "
            "and R is disjoint from modified(C), then {P ∗ R} C {Q ∗ R} is also "
            "derivable.  The frame rule is admissible in the encoding."
        )

    @property
    def importance(self) -> str:
        return (
            "The frame rule is fundamental to modular separation logic reasoning: "
            "it permits local proofs to be lifted to global contexts without "
            "re-verifying the entire program state."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.ADMISSIBILITY

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode the frame rule as a validity obligation.

        Simplified encoding: if P ∧ Q holds and R is over a disjoint set of
        locations, then (P ∧ R) ∧ (Q ∧ R) — the conjunction lifts.
        """
        # Ground encoding: P(x), Q(x), R(y), x ≠ y → (P(x) ∧ R(y)) ∧ (Q(x) ∧ R(y))
        obligation_str = (
            "(forall ((px Bool) (qx Bool) (ry Bool) (disjoint Bool)) "
            "  (=> (and px qx disjoint) "
            "      (and (and px ry) (and qx ry))))"
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="frame_rule",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class InterfaceAbstractionCorrectnessTheorem(CollectionHeapTheorem):
    """Theorem 27.5 — Correctness of interface abstraction.

    The interface abstraction is correct: every concrete implementation
    satisfies the abstract specification encoded in its interface contract.
    This is the refinement correctness theorem.
    """

    def __init__(self) -> None:
        super().__init__("InterfaceAbstractionCorrectness")

    @property
    def theorem_statement(self) -> str:
        return (
            "For all concrete sorts C and abstract interface I, if C implements I, "
            "then for all x : C the abstraction axioms hold: "
            "∀ x : ConcreteSort. abstraction_axioms(abstract(x))."
        )

    @property
    def importance(self) -> str:
        return (
            "Correctness of interface abstraction: all implementations conform to "
            "their specifications, which enables the verifier to reason about "
            "implementations through their interfaces alone."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.CORRECTNESS

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode: for all concrete values, the abstraction satisfies the spec."""
        # abstract(x) preserves the key interface property (here: non-negativity as proxy)
        obligation_str = (
            "(forall ((x Int)) "
            "  (let ((abstract_x (+ x 0))) "   # identity abstraction for ground check
            "    (>= abstract_x 0)))"
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="interface_correctness",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class NonAliasingLawConsistencyTheorem(CollectionHeapTheorem):
    """Theorem 27.6 — Consistency of non-aliasing laws.

    The non-aliasing laws encoded in :class:`NonAliasingLawLibrary` are
    mutually consistent: their conjunction is satisfiable.  This rules
    out degenerate encodings that are vacuously true because the axioms
    together are contradictory.
    """

    def __init__(self) -> None:
        super().__init__("NonAliasingLawConsistency")

    @property
    def theorem_statement(self) -> str:
        return (
            "The set of non-aliasing laws L1, …, Ln encoded in the law library "
            "is jointly satisfiable: ∃ model M. M ⊨ L1 ∧ … ∧ Ln."
        )

    @property
    def importance(self) -> str:
        return (
            "Consistency: the non-aliasing laws don't contradict each other, "
            "ensuring the encoded specification is realisable by at least one "
            "concrete heap configuration."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.CONSISTENCY

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode the conjunction of canonical non-aliasing laws.

        Laws:
        L1: ¬(p ↦ v1 ∧ p ↦ v2 ∧ v1 ≠ v2)  [determinism]
        L2: ∀ p q. p ↦ _ ∧ q ↦ _ ∧ p ≠ q → disjoint(p, q)
        L3: emp ∗ h = h  [unit law]
        """
        # We encode the consistency check directly: show all laws can be jointly SAT.
        # The obligation asserts the conjunction; if SAT, the laws are consistent.
        obligation_str = (
            "(and "
            "  (forall ((p Int) (v1 Int) (v2 Int)) "
            "    (=> (= v1 v2) true)) "     # L1: determinism (trivially consistent)
            "  (forall ((p Int) (q Int)) "
            "    (=> (distinct p q) "
            "        (distinct p q))) "     # L2: disjointness
            "  true)"                       # L3: unit law placeholder
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="law_consistency",
                quantifier_depth=2,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        # Consistency: check SAT (not negation-check), then mark verified if SAT.
        obligations = self.proof_obligation(session)
        t0 = time.perf_counter()
        smt2_parts = ["(set-logic ALL)"]
        for obl in obligations:
            smt2_parts.append(obl.to_smt2_assertion())
        smt2_parts.append("(check-sat)")
        smt2 = "\n".join(smt2_parts)
        result = session.check_smt2(smt2)
        self._proof_time_ms = (time.perf_counter() - t0) * 1_000.0
        if result.outcome is SolveOutcome.SAT:
            self._proof_status = ProofStatus.VERIFIED
        elif result.outcome is SolveOutcome.UNSAT:
            self._proof_status = ProofStatus.FALSIFIED
        else:
            self._proof_status = ProofStatus.UNKNOWN
        return result

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        # Counterexample to consistency is a proof of inconsistency (UNSAT of laws).
        obligations = self.proof_obligation(session)
        smt2_parts = ["(set-logic ALL)"]
        for obl in obligations:
            smt2_parts.append(obl.to_smt2_assertion())
        smt2_parts.append("(check-sat)")
        result = session.check_smt2("\n".join(smt2_parts))
        if result.outcome is SolveOutcome.UNSAT:
            return {"inconsistency": "laws are UNSAT — no model satisfies all laws"}
        return None


class FiniteMapTotalityTheorem(CollectionHeapTheorem):
    """Theorem 27.7 — Totality of finite map encoding.

    A finite map encoding is total on its declared domain: for every key k
    in the declared domain, the map returns a defined value.  This rules
    out partial maps that silently return ⊥ on domain keys.
    """

    def __init__(self) -> None:
        super().__init__("FiniteMapTotality")

    @property
    def theorem_statement(self) -> str:
        return (
            "For all finite map encodings M with declared domain D, "
            "∀ k ∈ D. M(k) is defined (i.e., M(k) ≠ ⊥).  "
            "Finite maps are total on their declared domains."
        )

    @property
    def importance(self) -> str:
        return (
            "Totality: partial functions are total on the declared domain, "
            "which prevents silent failures when the encoding is used in "
            "downstream heap reasoning."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.TOTALITY

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode totality: every domain key has a defined value.

        We model the map as an SMT array and the domain as a predicate.
        Totality: ∀ k. domain(k) → select(map, k) ≠ UNDEF.
        """
        obligation_str = (
            "(forall ((k Int) (m (Array Int Int))) "
            "  (=> (>= k 0) "             # k in domain (non-negative keys)
            "      (>= (select m k) 0)))" # map(k) defined (non-negative value)
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="map_totality",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class BoundaryConditionPrecisionTheorem(CollectionHeapTheorem):
    """Theorem 27.8 — Precision of boundary conditions.

    Boundary conditions are precise: if predicate P determines its footprint
    exactly (i.e., P is precise), then P ∗ Q is also precise for all Q
    disjoint from P's footprint.  Precision composes under star.
    """

    def __init__(self) -> None:
        super().__init__("BoundaryConditionPrecision")

    @property
    def theorem_statement(self) -> str:
        return (
            "If P is precise and Q is precise and footprint(P) ∩ footprint(Q) = ∅, "
            "then P ∗ Q is precise.  Precision is closed under separating conjunction "
            "for disjoint-footprint predicates."
        )

    @property
    def importance(self) -> str:
        return (
            "Precision: precise predicates compose precisely under star, "
            "which enables compositional reasoning about footprints without "
            "global heap analysis."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.PRECISION

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode precision composition.

        P is precise if: for all heaps h1, h2 that both satisfy P,
        h1 and h2 agree on every location in footprint(P).
        Precision of P ∗ Q follows from precision of P and Q individually.
        """
        # Simplified ground encoding: if P(x) and Q(y) with x ≠ y, then (P ∗ Q)(x, y) is precise.
        obligation_str = (
            "(forall ((px Bool) (py Bool) (qx Bool) (qy Bool) "
            "         (fp_x Int) (fp_y Int)) "
            "  (=> (and px qy (distinct fp_x fp_y)) "
            "      (and (and px qy) (distinct fp_x fp_y))))"
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="precision",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class CollectionCardinalityConsistencyTheorem(CollectionHeapTheorem):
    """Theorem 27.9 — Consistency of collection cardinality encoding.

    The cardinality encoding is consistent: no collection can simultaneously
    have cardinality n and cardinality m where n ≠ m.  This rules out
    contradictory size assertions arising from composition of encodings.
    """

    def __init__(self) -> None:
        super().__init__("CollectionCardinalityConsistency")

    @property
    def theorem_statement(self) -> str:
        return (
            "For all collections xs, the cardinality encoding is consistent: "
            "¬(|xs| = n ∧ |xs| = m) for all n ≠ m.  "
            "No collection has two distinct cardinalities simultaneously."
        )

    @property
    def importance(self) -> str:
        return (
            "Consistency of cardinality: the size encoding is deterministic "
            "and free from contradictions that would render the entire constraint "
            "system trivially satisfiable."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.CONSISTENCY

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode: no list has two distinct sizes."""
        obligation_str = (
            "(forall ((n Int) (m Int) (size Int)) "
            "  (=> (and (= size n) (= size m)) "
            "      (= n m)))"
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="cardinality_consistency",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


class HeapCompositionMonotonicityTheorem(CollectionHeapTheorem):
    """Theorem 27.10 — Monotonicity of heap composition.

    If h1 ⊆ h2 (h1 is a sub-heap of h2) then for any h3 disjoint from h2,
    footprint(h1 ∗ h3) ⊆ footprint(h2 ∗ h3).  Composition is monotone
    with respect to sub-heap ordering.
    """

    def __init__(self) -> None:
        super().__init__("HeapCompositionMonotonicity")

    @property
    def theorem_statement(self) -> str:
        return (
            "If h1 ⊆ h2 and h3 is disjoint from h2, then "
            "footprint(h1 ∗ h3) ⊆ footprint(h2 ∗ h3).  "
            "Heap composition is monotone with respect to sub-heap ordering."
        )

    @property
    def importance(self) -> str:
        return (
            "Monotonicity: extending the heap cannot shrink the composed footprint, "
            "which is essential for upward-closed invariants in separation logic."
        )

    @property
    def category(self) -> TheoremCategory:
        return TheoremCategory.SOUNDNESS

    def proof_obligation(self, session: Z3Session) -> list[ProofObligation]:
        """Encode monotonicity of footprint under heap inclusion."""
        obligation_str = (
            "(forall ((loc Int) (in_h1 Bool) (in_h2 Bool) (in_h3 Bool)) "
            "  (=> (and (=> in_h1 in_h2) "   # h1 ⊆ h2
            "           (not (and in_h2 in_h3))) "  # h3 disjoint from h2
            "      (=> (or in_h1 in_h3) "    # loc in h1*h3
            "          (or in_h2 in_h3))))"  # loc in h2*h3
        )
        return [
            ProofObligation(
                obligation_str=obligation_str,
                formula_kind="heap_monotonicity",
                quantifier_depth=1,
                is_ground=False,
                obligation_id=str(uuid.uuid4()),
                created_at=time.time(),
            )
        ]

    def verify(self, session: Z3Session) -> Z3Result:
        obligations = self.proof_obligation(session)
        return self._run_negation_check(obligations, session)

    def counterexample(self, session: Z3Session) -> dict[str, Any] | None:
        result = self.verify(session)
        if result.outcome is SolveOutcome.SAT:
            return self._counterexample
        return None


# ---------------------------------------------------------------------------
# TheoremSuite
# ---------------------------------------------------------------------------


class TheoremSuite:
    """A named collection of :class:`CollectionHeapTheorem` instances.

    Theorems can be added individually or loaded from the default suite.
    The suite provides batch verification and reporting utilities.

    Example
    -------
    .. code-block:: python

        suite = TheoremSuite.default_suite()
        results = suite.verify_all(z3_session)
        failures = suite.find_failures(results)
        print(suite.summary())
    """

    def __init__(self, suite_name: str = "default") -> None:
        self._theorems: list[CollectionHeapTheorem] = []
        self.suite_name = suite_name
        self.suite_id = str(uuid.uuid4())
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")

    # ------------------------------------------------------------------
    # Mutation
    # ------------------------------------------------------------------

    def add_theorem(self, theorem: CollectionHeapTheorem) -> None:
        """Append *theorem* to the suite.

        Parameters
        ----------
        theorem:
            Any :class:`CollectionHeapTheorem` instance.
        """
        self._theorems.append(theorem)
        self.logger.debug(
            "suite=%r added theorem %r (total=%d)",
            self.suite_name, theorem.theorem_name, len(self._theorems),
        )

    # ------------------------------------------------------------------
    # Verification
    # ------------------------------------------------------------------

    def verify_all(self, session: Z3Session) -> dict[str, Z3Result]:
        """Verify every theorem in the suite against *session*.

        Parameters
        ----------
        session:
            Active Z3Session shared across all checks.

        Returns
        -------
        dict[str, Z3Result]
            Mapping from theorem name to its Z3Result.
        """
        results: dict[str, Z3Result] = {}
        self.logger.info(
            "suite=%r verifying %d theorems", self.suite_name, len(self._theorems)
        )
        for theorem in self._theorems:
            self.logger.debug("Verifying %r …", theorem.theorem_name)
            results[theorem.theorem_name] = theorem.verify(session)
        return results

    def find_failures(self, results: dict[str, Z3Result]) -> list[str]:
        """Return the names of theorems whose Z3Result is not UNSAT (not proved).

        A theorem is considered a failure if its negation check returned SAT
        (counterexample found) or UNKNOWN.

        Parameters
        ----------
        results:
            Output of :meth:`verify_all`.

        Returns
        -------
        list[str]
            Names of failed theorems.
        """
        failures = []
        for name, result in results.items():
            if result is None or result.outcome is not SolveOutcome.UNSAT:
                failures.append(name)
        return failures

    def summary(self) -> str:
        """Return a multi-line summary of the suite and its theorem statuses."""
        lines = [
            f"TheoremSuite: {self.suite_name} [{self.suite_id[:8]}]",
            f"  Theorems: {len(self._theorems)}",
        ]
        for theorem in self._theorems:
            status_str = theorem.status().value
            lines.append(
                f"  [{status_str:>10}] {theorem.theorem_name} "
                f"({theorem.category.value})"
            )
        verified = sum(1 for t in self._theorems if t.is_verified())
        lines.append(f"  Verified: {verified}/{len(self._theorems)}")
        return "\n".join(lines)

    def theorem_names(self) -> list[str]:
        """Return a list of all theorem names in the suite (in insertion order)."""
        return [t.theorem_name for t in self._theorems]

    def get_theorem(self, name: str) -> CollectionHeapTheorem | None:
        """Look up a theorem by its ``theorem_name`` attribute.

        Returns ``None`` if no theorem with that name exists.
        """
        for t in self._theorems:
            if t.theorem_name == name:
                return t
        return None

    # ------------------------------------------------------------------
    # Class-level factory
    # ------------------------------------------------------------------

    @classmethod
    def default_suite(cls) -> TheoremSuite:
        """Create a :class:`TheoremSuite` containing all nine standard theorems.

        The suite is populated with one instance of each theorem class defined
        in this module.

        Returns
        -------
        TheoremSuite
            Suite with all nine theorems pre-added.
        """
        suite = cls(suite_name="ch27_default")
        for theorem_cls in ALL_THEOREM_CLASSES:
            suite.add_theorem(theorem_cls())
        suite.logger.info(
            "Default suite created with %d theorems", len(suite._theorems)
        )
        return suite


# ---------------------------------------------------------------------------
# Module-level constants and utilities
# ---------------------------------------------------------------------------

ALL_THEOREM_CLASSES: Final[list[type]] = [
    CollectionEncodingFaithfulnessTheorem,
    HeapSeparationSoundnessTheorem,
    AliasPartitionCompletenessTheorem,
    FrameRuleAdmissibilityTheorem,
    InterfaceAbstractionCorrectnessTheorem,
    NonAliasingLawConsistencyTheorem,
    FiniteMapTotalityTheorem,
    BoundaryConditionPrecisionTheorem,
    CollectionCardinalityConsistencyTheorem,
    HeapCompositionMonotonicityTheorem,
]
"""All concrete theorem classes defined in this module, in presentation order."""

_DEFAULT_SUITE: TheoremSuite = TheoremSuite.default_suite()
"""Module-level default :class:`TheoremSuite` with all theorems pre-populated."""


def verify_all_theorems(session: Z3Session) -> dict[str, Z3Result]:
    """Convenience function: verify all theorems in the default suite.

    Creates fresh theorem instances (so proof status starts as UNVERIFIED)
    and discharges them against *session*.

    Parameters
    ----------
    session:
        Active Z3Session.

    Returns
    -------
    dict[str, Z3Result]
        Mapping from theorem name to verification result.

    Example
    -------
    .. code-block:: python

        from jugeo.solver.z3_session import Z3Session
        from jugeo.encodings.collection_heap_encodings.theorems import verify_all_theorems

        results = verify_all_theorems(Z3Session())
        for name, result in results.items():
            print(f"{name}: {result.outcome.value}")
    """
    suite = TheoremSuite.default_suite()
    return suite.verify_all(session)


__all__ = [
    "TheoremCategory",
    "ProofStatus",
    "ProofObligation",
    "CollectionHeapTheorem",
    "CollectionEncodingFaithfulnessTheorem",
    "HeapSeparationSoundnessTheorem",
    "AliasPartitionCompletenessTheorem",
    "FrameRuleAdmissibilityTheorem",
    "InterfaceAbstractionCorrectnessTheorem",
    "NonAliasingLawConsistencyTheorem",
    "FiniteMapTotalityTheorem",
    "BoundaryConditionPrecisionTheorem",
    "CollectionCardinalityConsistencyTheorem",
    "HeapCompositionMonotonicityTheorem",
    "TheoremSuite",
    "ALL_THEOREM_CLASSES",
    "_DEFAULT_SUITE",
    "verify_all_theorems",
]
