"""Kind bootstrapping from obstruction patterns (theory2.tex Ch 56).

Generates kind hypotheses from recognised patterns, builds formal definitions,
creates examples, plans validation, and produces KindBootstrapPlan objects.

Module layout::

    BootstrapConfig        – configuration for the bootstrapping pipeline
    KindHypothesizer       – generates kind hypotheses from patterns
    DefinitionBuilder      – builds formal kind definitions
    ExampleGenerator       – generates examples for new kinds
    ValidationPlanner      – creates ValidationPath plans for new kinds
    KindBootstrapper       – orchestrates the full bootstrapping pipeline
"""

from __future__ import annotations

import collections
import dataclasses
import datetime
import enum
import json
import math
import re
import time
import uuid
from collections import Counter, defaultdict
from dataclasses import dataclass, field, replace
from typing import Any, Optional

from jugeo.ideation.kind_discovery.models import (
    KindBootstrapPlan,
    KindCandidate,
    KindPattern,
    KindStatus,
    NewKind,
    ObstructionField,
    ObstructionType,
)
from jugeo.ideation.ideas import (
    GainProfile,
    Idea,
    IdeaEvaluator,
    IdeaGenerator,
    IdeaProposal,
    TrustStatus,
    ValidationPath,
)

# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

_SCHEMA_VERSION: str = "1"
_DEFAULT_MIN_CONFIDENCE: float = 0.30
_DEFAULT_MAX_HYPOTHESES: int = 5
_DEFAULT_DEFINITION_DEPTH: int = 3
_DEFAULT_EXAMPLE_COUNT: int = 5
_DEFAULT_VALIDATION_STEPS: int = 4
_DEFAULT_EFFORT_BUDGET: float = 10.0
_DEFAULT_IDEA_COUNT: int = 3

# Obstruction-type vocabulary used when composing definitions
_OBS_TYPE_VOCAB: dict[str, str] = {
    ObstructionType.STRUCTURAL: "structural barrier",
    ObstructionType.DEFINITIONAL: "definitional gap",
    ObstructionType.COMPUTATIONAL: "computational constraint",
    ObstructionType.LOGICAL: "logical inconsistency",
    ObstructionType.EMPIRICAL: "empirical evidence",
    ObstructionType.BOUNDARY: "boundary condition",
    ObstructionType.CATEGORICAL: "categorical distinction",
    ObstructionType.RELATIONAL: "relational property",
}

# Stop words excluded from keyword extraction
_STOP_WORDS: frozenset[str] = frozenset(
    "the a an and or but in on at to for of with by from as is are was were be "
    "been have has had do does did will would could should may might shall can "
    "it its this that these those he she we they i you".split()
)

# Common mathematical vocabulary used when constructing definitions
_MATH_QUALIFIERS: tuple[str, ...] = (
    "closed under",
    "stable with respect to",
    "admitting",
    "satisfying",
    "witnessing",
    "characterised by",
    "determined by",
    "generated by",
)

# Evidence keywords per obstruction type
_EVIDENCE_VOCAB: dict[str, tuple[str, ...]] = {
    ObstructionType.STRUCTURAL: (
        "structural witness",
        "decomposition argument",
        "fibration diagram",
        "lifting property",
    ),
    ObstructionType.DEFINITIONAL: (
        "formal definition",
        "axiom schema",
        "definitional unfolding",
        "type specification",
    ),
    ObstructionType.COMPUTATIONAL: (
        "algorithm trace",
        "complexity bound",
        "reduction argument",
        "computational witness",
    ),
    ObstructionType.LOGICAL: (
        "proof sketch",
        "derivation",
        "consistency check",
        "contradiction witness",
    ),
    ObstructionType.EMPIRICAL: (
        "empirical observation",
        "statistical evidence",
        "measurement record",
        "replication result",
    ),
    ObstructionType.BOUNDARY: (
        "boundary case analysis",
        "limiting argument",
        "degenerate example",
        "extremal case",
    ),
    ObstructionType.CATEGORICAL: (
        "categorical diagram",
        "functorial argument",
        "natural transformation",
        "adjunction witness",
    ),
    ObstructionType.RELATIONAL: (
        "relational composition",
        "morphism factorisation",
        "span construction",
        "relation lifting",
    ),
}


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def _clamp(value: float, lo: float, hi: float) -> float:
    """Return *value* clamped to the closed interval [*lo*, *hi*]."""
    return max(lo, min(hi, value))


def _now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string."""
    return datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z"


def _tokenize(text: str) -> list[str]:
    """Split *text* into lowercase alphabetic tokens, stripping stop words."""
    return [
        tok.lower()
        for tok in re.findall(r"[A-Za-z]+", text)
        if tok.lower() not in _STOP_WORDS
    ]


def _jaccard(a: frozenset[str], b: frozenset[str]) -> float:
    """Compute Jaccard similarity between two frozen token sets."""
    if not a and not b:
        return 1.0
    union = a | b
    if not union:
        return 0.0
    return len(a & b) / len(union)


def _title_case(text: str) -> str:
    """Convert *text* to title-case, preserving inner capitals."""
    if not text:
        return text
    words = text.strip().split()
    return " ".join(w.capitalize() for w in words)


def _formal_name(name: str) -> str:
    """Convert a human-readable kind name to a PascalCase formal identifier.

    Examples
    --------
    >>> _formal_name("obstruction field")
    'ObstructionField'
    >>> _formal_name("local-to-global kind")
    'LocalToGlobalKind'
    """
    parts = re.split(r"[\s\-_]+", name.strip())
    return "".join(p.capitalize() for p in parts if p)


def _candidate_definition_template(
    name: str,
    domain: str,
    obstruction_types: tuple[str, ...],
    depth: int = 2,
) -> str:
    """Return a multi-sentence definition template for a kind candidate.

    The template is constructed deterministically from the inputs so that
    repeated calls with identical arguments produce the same string.  The
    *depth* parameter controls the verbosity of the generated text (1 = brief,
    3 = detailed).
    """
    if not name:
        name = "unnamed kind"
    if not domain:
        domain = "general"

    formal = _formal_name(name)
    obs_phrases = [
        _OBS_TYPE_VOCAB.get(ot, ot) for ot in obstruction_types[:4]
    ]

    # Sentence 1 – introductory clause
    intro = (
        f"A {name} is a mathematical object in the domain of {domain} "
        f"characterised by its interaction with {len(obstruction_types)} "
        f"obstruction type(s)."
    )

    # Sentence 2 – obstruction characterisation
    if obs_phrases:
        obs_list = ", ".join(obs_phrases[:-1])
        if len(obs_phrases) > 1:
            obs_clause = f"It is defined by the presence of {obs_list} and {obs_phrases[-1]}."
        else:
            obs_clause = f"It is defined by the presence of {obs_phrases[0]}."
    else:
        obs_clause = "Its obstruction structure has not yet been fully determined."

    # Sentence 3 – closure property (depth ≥ 2)
    closure = ""
    if depth >= 2:
        closure = (
            f"The {formal} is closed under the relevant obstruction-resolving "
            f"operations, meaning that any resolution of a constituent "
            f"obstruction yields another {name} (or a degenerate case thereof)."
        )

    # Sentence 4 – existence clause (depth ≥ 3)
    existence = ""
    if depth >= 3:
        existence = (
            f"Existence of a non-trivial {name} in the {domain} domain implies "
            f"the existence of at least one obstruction of each constituent type, "
            f"and these obstructions are pairwise non-redundant."
        )

    parts = [intro, obs_clause]
    if closure:
        parts.append(closure)
    if existence:
        parts.append(existence)
    return " ".join(parts)


def _estimate_effort(candidate: KindCandidate, depth: int = 2) -> float:
    """Estimate the effort required to bootstrap a kind candidate.

    The estimate is a dimensionless score in [0, 20].  Higher values indicate
    more effort.  The heuristic is based on:

    * Number of obstruction types (more types ⇒ more complex)
    * Depth of the requested definition
    * Inverse of candidate confidence (lower confidence ⇒ more work needed)
    * Whether examples are already provided
    """
    base = 2.0
    # Each distinct obstruction type adds ~1.5 units of effort
    type_penalty = len(candidate.obstruction_types) * 1.5
    # Depth multiplier
    depth_factor = 1.0 + 0.3 * max(0, depth - 1)
    # Confidence discount – higher confidence means less validation work
    confidence_discount = 1.0 - _clamp(candidate.confidence, 0.0, 1.0)
    # Example bonus – existing examples reduce work
    example_discount = 0.5 * min(len(candidate.examples), 4) / 4.0
    # Counter-evidence penalty
    counter_penalty = 0.4 * min(len(candidate.counter_evidence), 5)

    effort = (base + type_penalty) * depth_factor * (1.0 + confidence_discount)
    effort -= example_discount
    effort += counter_penalty
    return _clamp(round(effort, 3), 0.0, 20.0)


def _evidence_keywords(obstruction_types: tuple[str, ...]) -> tuple[str, ...]:
    """Return a de-duplicated tuple of evidence keywords for the given types."""
    seen: set[str] = set()
    result: list[str] = []
    for ot in obstruction_types:
        for kw in _EVIDENCE_VOCAB.get(ot, ()):
            if kw not in seen:
                seen.add(kw)
                result.append(kw)
    return tuple(result)


def _normalize_obstruction_type(value: Any) -> str:
    if hasattr(value, "value"):
        return str(value.value)
    text = str(value or "").strip().lower()
    if not text:
        return ""
    if text in _OBS_TYPE_VOCAB:
        return text

    keyword_map = {
        "algebra": ObstructionType.ALGEBRAIC.value,
        "cohom": ObstructionType.ALGEBRAIC.value,
        "ext^": ObstructionType.ALGEBRAIC.value,
        "module": ObstructionType.ALGEBRAIC.value,
        "struct": ObstructionType.STRUCTURAL.value,
        "defin": ObstructionType.DEFINITIONAL.value,
        "comput": ObstructionType.COMPUTATIONAL.value,
        "logic": ObstructionType.LOGICAL.value,
        "empir": ObstructionType.EMPIRICAL.value,
        "bound": ObstructionType.BOUNDARY.value,
        "categor": ObstructionType.CATEGORICAL.value,
        "relation": ObstructionType.RELATIONAL.value,
        "semantic": ObstructionType.SEMANTIC.value,
        "syntax": ObstructionType.SYNTACTIC.value,
    }
    for needle, normalized in keyword_map.items():
        if needle in text:
            return normalized
    return text


def _candidate_obstruction_types(candidate: KindCandidate) -> tuple[str, ...]:
    normalized = [
        _normalize_obstruction_type(ot)
        for ot in getattr(candidate, "obstruction_types", ())
    ]
    normalized = [ot for ot in normalized if ot]
    if not normalized and getattr(candidate, "obstruction_pattern", ""):
        inferred = _normalize_obstruction_type(candidate.obstruction_pattern)
        if inferred:
            normalized.append(inferred)
    return tuple(dict.fromkeys(normalized))


# ---------------------------------------------------------------------------
# BootstrapConfig
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class BootstrapConfig:
    """Immutable configuration for the kind-bootstrapping pipeline.

    All numeric thresholds are validated at construction time.  Use the
    ``from_dict`` class method to load configuration from a plain dict.
    """

    min_pattern_frequency: int = 2
    min_candidate_confidence: float = _DEFAULT_MIN_CONFIDENCE
    max_hypotheses_per_pattern: int = _DEFAULT_MAX_HYPOTHESES
    definition_depth: int = _DEFAULT_DEFINITION_DEPTH
    example_count: int = _DEFAULT_EXAMPLE_COUNT
    validation_steps_count: int = _DEFAULT_VALIDATION_STEPS
    effort_budget: float = _DEFAULT_EFFORT_BUDGET
    auto_generate_ideas: bool = True
    idea_count_per_kind: int = _DEFAULT_IDEA_COUNT
    enable_cross_domain: bool = True

    def __post_init__(self) -> None:
        if self.min_pattern_frequency < 1:
            raise ValueError("min_pattern_frequency must be >= 1")
        if not (0.0 <= self.min_candidate_confidence <= 1.0):
            raise ValueError("min_candidate_confidence must be in [0, 1]")
        if self.max_hypotheses_per_pattern < 1:
            raise ValueError("max_hypotheses_per_pattern must be >= 1")
        if self.definition_depth < 1:
            raise ValueError("definition_depth must be >= 1")
        if self.example_count < 0:
            raise ValueError("example_count must be >= 0")
        if self.validation_steps_count < 0:
            raise ValueError("validation_steps_count must be >= 0")
        if self.effort_budget < 0.0:
            raise ValueError("effort_budget must be non-negative")
        if self.idea_count_per_kind < 0:
            raise ValueError("idea_count_per_kind must be >= 0")

    # ------------------------------------------------------------------
    # Mutation helpers (produce new frozen instances)
    # ------------------------------------------------------------------

    def with_effort_budget(self, budget: float) -> BootstrapConfig:
        """Return a new config with a different *budget*."""
        return replace(self, effort_budget=float(budget))

    def with_definition_depth(self, depth: int) -> BootstrapConfig:
        """Return a new config with a different definition *depth*."""
        return replace(self, definition_depth=int(depth))

    def with_confidence_threshold(self, threshold: float) -> BootstrapConfig:
        """Return a new config with a different minimum candidate confidence."""
        return replace(self, min_candidate_confidence=float(threshold))

    def relaxed(self) -> BootstrapConfig:
        """Return a more permissive config useful for exploratory runs."""
        return replace(
            self,
            min_pattern_frequency=1,
            min_candidate_confidence=max(0.1, self.min_candidate_confidence - 0.1),
            max_hypotheses_per_pattern=self.max_hypotheses_per_pattern + 3,
        )

    def strict(self) -> BootstrapConfig:
        """Return a stricter config useful for production runs."""
        return replace(
            self,
            min_pattern_frequency=max(3, self.min_pattern_frequency + 1),
            min_candidate_confidence=min(0.9, self.min_candidate_confidence + 0.15),
            max_hypotheses_per_pattern=max(1, self.max_hypotheses_per_pattern - 2),
        )

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a plain Python dict."""
        return {
            "_schema": _SCHEMA_VERSION,
            "min_pattern_frequency": self.min_pattern_frequency,
            "min_candidate_confidence": self.min_candidate_confidence,
            "max_hypotheses_per_pattern": self.max_hypotheses_per_pattern,
            "definition_depth": self.definition_depth,
            "example_count": self.example_count,
            "validation_steps_count": self.validation_steps_count,
            "effort_budget": self.effort_budget,
            "auto_generate_ideas": self.auto_generate_ideas,
            "idea_count_per_kind": self.idea_count_per_kind,
            "enable_cross_domain": self.enable_cross_domain,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> BootstrapConfig:
        """Deserialise from a plain Python dict."""
        return cls(
            min_pattern_frequency=int(d.get("min_pattern_frequency", 2)),
            min_candidate_confidence=float(d.get("min_candidate_confidence", _DEFAULT_MIN_CONFIDENCE)),
            max_hypotheses_per_pattern=int(d.get("max_hypotheses_per_pattern", _DEFAULT_MAX_HYPOTHESES)),
            definition_depth=int(d.get("definition_depth", _DEFAULT_DEFINITION_DEPTH)),
            example_count=int(d.get("example_count", _DEFAULT_EXAMPLE_COUNT)),
            validation_steps_count=int(d.get("validation_steps_count", _DEFAULT_VALIDATION_STEPS)),
            effort_budget=float(d.get("effort_budget", _DEFAULT_EFFORT_BUDGET)),
            auto_generate_ideas=bool(d.get("auto_generate_ideas", True)),
            idea_count_per_kind=int(d.get("idea_count_per_kind", _DEFAULT_IDEA_COUNT)),
            enable_cross_domain=bool(d.get("enable_cross_domain", True)),
        )

    def __repr__(self) -> str:
        return (
            f"BootstrapConfig("
            f"min_freq={self.min_pattern_frequency}, "
            f"min_conf={self.min_candidate_confidence:.2f}, "
            f"depth={self.definition_depth}, "
            f"budget={self.effort_budget:.1f}"
            f")"
        )


# ---------------------------------------------------------------------------
# KindHypothesizer
# ---------------------------------------------------------------------------


class KindHypothesizer:
    """Generate KindCandidate hypotheses from recognised patterns.

    The hypothesizer examines one or more :class:`KindPattern` objects and
    proposes :class:`KindCandidate` objects.  Each candidate represents one
    plausible new kind that could be defined to capture the regularity
    expressed by the pattern.

    The hypothesization strategy assigns a confidence score based on:
    * Pattern frequency (higher → more confident)
    * Pattern confidence (inherited directly)
    * Number of distinct obstruction types covered
    * Presence of keywords that suggest a coherent concept
    """

    def __init__(self, config: BootstrapConfig | None = None) -> None:
        self._config = config or BootstrapConfig()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def hypothesize(self, pattern: KindPattern) -> list[KindCandidate]:
        """Generate up to *max_hypotheses_per_pattern* candidates from *pattern*.

        Returns an empty list when the pattern does not meet the minimum
        frequency threshold configured in :attr:`_config`.
        """
        if pattern.frequency < self._config.min_pattern_frequency:
            return []

        limit = self._config.max_hypotheses_per_pattern
        base_confidence = self._compute_confidence(pattern)
        candidates: list[KindCandidate] = []

        # --- Primary hypothesis: direct interpretation of the pattern ---
        primary_name = self._name_from_pattern(pattern)
        primary_desc = self._description_from_pattern(pattern)
        primary_cand = KindCandidate(
            candidate_id=str(uuid.uuid4()),
            name=primary_name,
            description=primary_desc,
            pattern_ids=(pattern.pattern_id,),
            obstruction_types=pattern.obstruction_types,
            field_ids=pattern.field_ids,
            confidence=base_confidence,
            novelty=_clamp(1.0 - base_confidence * 0.5, 0.0, 1.0),
            status=KindStatus.PROPOSED,
            supporting_evidence=tuple(pattern.keywords),
            definition_draft=_candidate_definition_template(
                primary_name,
                pattern.name,
                pattern.obstruction_types,
                depth=self._config.definition_depth,
            ),
            created_at=_now_iso(),
        )
        candidates.append(primary_cand)

        # --- Secondary hypotheses: one per obstruction type (if room) ---
        for obs_type in pattern.obstruction_types[: limit - 1]:
            sec_name = self._name_from_obstruction_type(obs_type, pattern)
            if sec_name == primary_name:
                continue
            sec_confidence = base_confidence * 0.80  # slight penalty
            sec_cand = KindCandidate(
                candidate_id=str(uuid.uuid4()),
                name=sec_name,
                description=self._description_from_obstruction_type(obs_type, pattern),
                pattern_ids=(pattern.pattern_id,),
                obstruction_types=(obs_type,),
                field_ids=pattern.field_ids,
                confidence=sec_confidence,
                novelty=_clamp(1.0 - sec_confidence * 0.4, 0.0, 1.0),
                status=KindStatus.PROPOSED,
                supporting_evidence=tuple(_EVIDENCE_VOCAB.get(obs_type, ())),
                definition_draft=_candidate_definition_template(
                    sec_name,
                    pattern.name,
                    (obs_type,),
                    depth=max(1, self._config.definition_depth - 1),
                ),
                created_at=_now_iso(),
            )
            candidates.append(sec_cand)
            if len(candidates) >= limit:
                break

        # --- Cross-domain hypothesis (if enabled and pattern has keywords) ---
        if self._config.enable_cross_domain and len(candidates) < limit and pattern.keywords:
            cross_name = f"cross-domain {primary_name}"
            cross_conf = base_confidence * 0.65
            cross_cand = KindCandidate(
                candidate_id=str(uuid.uuid4()),
                name=cross_name,
                description=(
                    f"A cross-domain generalisation of {primary_name} "
                    f"arising from the pattern '{pattern.name}' across "
                    f"{len(pattern.field_ids)} fields."
                ),
                pattern_ids=(pattern.pattern_id,),
                obstruction_types=pattern.obstruction_types,
                field_ids=pattern.field_ids,
                confidence=cross_conf,
                novelty=_clamp(1.0 - cross_conf * 0.3, 0.0, 1.0),
                status=KindStatus.PROPOSED,
                supporting_evidence=tuple(pattern.keywords[:3]),
                created_at=_now_iso(),
            )
            candidates.append(cross_cand)

        return candidates[:limit]

    def hypothesize_from_field(self, field: ObstructionField) -> list[KindCandidate]:
        """Generate candidates directly from an :class:`ObstructionField`.

        Creates a synthetic :class:`KindPattern` from the field's obstruction
        types and delegates to :meth:`hypothesize`.
        """
        if not field.obstruction_types:
            return []

        # Build a synthetic pattern from the field
        obs_types = tuple(
            ObstructionType(ot) if isinstance(ot, str) else ot
            for ot in field.obstruction_types
        )
        synthetic_pattern = KindPattern(
            pattern_id=str(uuid.uuid4()),
            name=field.name,
            pattern_type="field_derived",
            frequency=max(1, field.obstruction_count),
            confidence=_clamp(field.weight_per_obstruction() / 10.0, 0.0, 1.0),
            supporting_obstructions=tuple(str(i) for i in range(field.obstruction_count)),
            obstruction_types=obs_types,
            field_ids=(field.field_id,),
            description=f"Pattern derived from obstruction field '{field.name}'",
            keywords=tuple(_tokenize(field.name)[:8]),
            created_at=_now_iso(),
        )
        return self.hypothesize(synthetic_pattern)

    def hypothesize_batch(self, patterns: list[KindPattern]) -> list[KindCandidate]:
        """Generate candidates from a batch of patterns.

        Returns a flat list of all generated candidates across all patterns,
        deduplicated by name similarity.
        """
        all_candidates: list[KindCandidate] = []
        for pattern in patterns:
            new_cands = self.hypothesize(pattern)
            all_candidates.extend(new_cands)
        return self.merge_duplicates(all_candidates)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _name_from_pattern(self, pattern: KindPattern) -> str:
        """Derive a human-readable kind name from a pattern."""
        # Prefer explicit keywords, fall back to pattern name tokens
        tokens = list(pattern.keywords) if pattern.keywords else _tokenize(pattern.name)
        # Take up to 3 tokens that are ≥ 4 characters
        significant = [t for t in tokens if len(t) >= 4][:3]
        if not significant:
            significant = tokens[:2] if tokens else ["unknown"]
        # Pick the obstruction type with highest frequency as qualifier
        obs_qualifier = ""
        if pattern.obstruction_types:
            ot = pattern.obstruction_types[0]
            obs_qualifier = ot.split("_")[0] if isinstance(ot, str) else ot.value.split("_")[0]
        parts = significant if not obs_qualifier else [obs_qualifier] + significant[:2]
        return _title_case(" ".join(parts)) + " Kind"

    def _name_from_obstruction_type(self, obs_type: str, pattern: KindPattern) -> str:
        """Derive a kind name specifically for one obstruction type."""
        qualifier = obs_type.split("_")[0] if isinstance(obs_type, str) else obs_type.value.split("_")[0]
        domain_hint = _tokenize(pattern.name)[:1]
        if domain_hint:
            return _title_case(f"{qualifier} {domain_hint[0]}") + " Kind"
        return _title_case(f"{qualifier}") + " Kind"

    def _description_from_pattern(self, pattern: KindPattern) -> str:
        """Compose a description for a candidate derived from *pattern*."""
        obs_count = len(pattern.obstruction_types)
        field_count = len(pattern.field_ids)
        obs_list = ", ".join(str(ot) for ot in pattern.obstruction_types[:3])
        extra = "..." if obs_count > 3 else ""
        return (
            f"A kind candidate arising from pattern '{pattern.name}' "
            f"(frequency={pattern.frequency}, confidence={pattern.confidence:.2f}). "
            f"Covers {obs_count} obstruction type(s) ({obs_list}{extra}) "
            f"across {field_count} obstruction field(s)."
        )

    def _description_from_obstruction_type(self, obs_type: str, pattern: KindPattern) -> str:
        """Compose a description for a candidate focused on one obstruction type."""
        vocab = _OBS_TYPE_VOCAB.get(obs_type, obs_type)
        return (
            f"A kind candidate focusing on the {vocab} aspect of pattern "
            f"'{pattern.name}'. Derived from {len(pattern.field_ids)} field(s) "
            f"with an original pattern confidence of {pattern.confidence:.2f}."
        )

    def _obstruction_pattern_text(self, pattern: KindPattern) -> str:
        """Return a single-sentence textual summary of the obstruction pattern."""
        type_strs = [str(ot) for ot in pattern.obstruction_types]
        return (
            f"Pattern '{pattern.name}' exhibits {len(type_strs)} obstruction "
            f"type(s): {', '.join(type_strs)}. It appears {pattern.frequency} "
            f"time(s) across the obstruction corpus."
        )

    def _compute_confidence(self, pattern: KindPattern) -> float:
        """Compute a bootstrap confidence score from pattern statistics.

        The formula weights:
        * Pattern's own confidence (60 %)
        * Frequency-derived bonus – log(freq+1) / log(10+1) capped at 20 %
        * Obstruction-type coverage bonus – up to 20 %
        """
        freq_bonus = math.log(pattern.frequency + 1) / math.log(11) * 0.20
        type_coverage = min(len(pattern.obstruction_types) / 5.0, 1.0) * 0.20
        raw = pattern.confidence * 0.60 + freq_bonus + type_coverage
        return _clamp(round(raw, 4), 0.0, 1.0)

    # ------------------------------------------------------------------
    # Filtering / merging
    # ------------------------------------------------------------------

    def filter_viable(self, candidates: list[KindCandidate]) -> list[KindCandidate]:
        """Retain only candidates that meet the minimum confidence threshold."""
        threshold = self._config.min_candidate_confidence
        min_frequency = self._config.min_pattern_frequency
        return [
            c for c in candidates
            if c.confidence >= threshold and getattr(c, "frequency", min_frequency) >= min_frequency
        ]

    def merge_duplicates(self, candidates: list[KindCandidate]) -> list[KindCandidate]:
        """Merge candidates whose names are very similar (Jaccard ≥ 0.80).

        When two candidates are judged duplicates the one with higher
        confidence is kept and the evidence of both is combined.
        """
        if not candidates:
            return []
        result: list[KindCandidate] = []
        used: set[int] = set()

        token_sets = [frozenset(_tokenize(c.name)) for c in candidates]

        for i, cand in enumerate(candidates):
            if i in used:
                continue
            merged = cand
            for j, other in enumerate(candidates):
                if j <= i or j in used:
                    continue
                sim = _jaccard(token_sets[i], token_sets[j])
                if sim >= 0.80:
                    used.add(j)
                    # Merge evidence and keep the higher-confidence candidate
                    combined_evidence = tuple(
                        dict.fromkeys(merged.supporting_evidence + other.supporting_evidence)
                    )
                    combined_counter = tuple(
                        dict.fromkeys(merged.counter_evidence + other.counter_evidence)
                    )
                    combined_patterns = tuple(
                        dict.fromkeys(merged.pattern_ids + other.pattern_ids)
                    )
                    if other.confidence > merged.confidence:
                        merged = replace(
                            other,
                            supporting_evidence=combined_evidence,
                            counter_evidence=combined_counter,
                            pattern_ids=combined_patterns,
                        )
                    else:
                        merged = replace(
                            merged,
                            supporting_evidence=combined_evidence,
                            counter_evidence=combined_counter,
                            pattern_ids=combined_patterns,
                        )
            result.append(merged)
        return result


# ---------------------------------------------------------------------------
# DefinitionBuilder
# ---------------------------------------------------------------------------


class DefinitionBuilder:
    """Build formal textual definitions for kind candidates.

    Definitions are constructed from three main clauses:
    1. *Introduction* – what the object is
    2. *Obstruction characterisation* – which obstructions define it
    3. *Closure / existence* – what properties follow from the definition

    The :meth:`build_formal` method produces a more structured output with
    explicitly labelled axioms.
    """

    def __init__(self, config: BootstrapConfig | None = None) -> None:
        self._config = config or BootstrapConfig()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build(self, candidate: KindCandidate) -> str:
        """Return an informal textual definition for *candidate*.

        Uses :func:`_candidate_definition_template` as the backbone and
        appends additional context if the candidate already has a draft
        definition.
        """
        depth = self._config.definition_depth
        base = _candidate_definition_template(
            candidate.name,
            " ".join(candidate.field_ids[:2]) if candidate.field_ids else "abstract",
            candidate.obstruction_types,
            depth=depth,
        )
        # Enrich with any existing draft material
        if candidate.definition_draft and len(candidate.definition_draft) > 20:
            extra_tokens = _tokenize(candidate.definition_draft)
            unique_extra = [t for t in extra_tokens if len(t) > 5][:6]
            if unique_extra:
                extra_phrase = ", ".join(unique_extra)
                base += (
                    f" Key structural features include: {extra_phrase}."
                )
        return base

    def build_formal(
        self, candidate: KindCandidate, *, depth: int | None = None
    ) -> str:
        """Return a structured, axiom-style definition for *candidate*.

        The output has the form::

            **Definition** (FormalName).
            [Axiom 1] ...
            [Axiom 2] ...
            ...
            **Remark.** ...
        """
        depth = depth if depth is not None else self._config.definition_depth
        formal = _formal_name(candidate.name)
        lines: list[str] = []
        lines.append(f"**Definition** ({formal}).")
        lines.append(self._intro_clause(candidate))

        # Obstruction axioms
        for idx, obs_type in enumerate(candidate.obstruction_types[:depth + 1], start=1):
            vocab = _OBS_TYPE_VOCAB.get(obs_type, obs_type)
            evidence = _EVIDENCE_VOCAB.get(obs_type, ())
            ev_hint = f" (witnessed by: {', '.join(evidence[:2])})" if evidence else ""
            lines.append(
                f"  [Axiom {idx}] A {formal} admits a {vocab}{ev_hint}."
            )

        lines.append(self._closure_clause(candidate))

        if depth >= 3:
            lines.append(self._existence_clause(candidate))

        # Remark
        remark_parts = []
        if candidate.confidence >= 0.7:
            remark_parts.append(f"This definition has high confidence ({candidate.confidence:.2f})")
        else:
            remark_parts.append(f"This definition is provisional (confidence={candidate.confidence:.2f})")
        if candidate.novelty >= 0.6:
            remark_parts.append(f"and represents a novel contribution (novelty={candidate.novelty:.2f})")
        lines.append("**Remark.** " + "; ".join(remark_parts) + ".")

        return "\n".join(lines)

    def build_from_obstructions(
        self, obstructions: list[ObstructionField | str], name: str
    ) -> str:
        """Build a definition directly from a list of obstruction fields.

        Aggregates the obstruction types across all fields and composes
        a unified definition for the named kind.
        """
        all_types: list[str] = []
        domains: list[str] = []
        for obstruction in obstructions:
            if isinstance(obstruction, str):
                normalized = _normalize_obstruction_type(obstruction)
                if normalized:
                    all_types.append(normalized)
                continue
            domains.append(obstruction.domain)
            all_types.extend(
                _normalize_obstruction_type(ot)
                for ot in getattr(obstruction, "obstruction_types", ())
                if _normalize_obstruction_type(ot)
            )
            if not getattr(obstruction, "obstruction_types", ()) and getattr(
                obstruction, "obstructions", ()
            ):
                all_types.extend(
                    _normalize_obstruction_type(text)
                    for text in obstruction.obstructions
                    if _normalize_obstruction_type(text)
                )
        type_counts = Counter(all_types)
        dominant_types = tuple(t for t, _ in type_counts.most_common(4))
        domain = next((domain for domain in domains if domain), "general")
        return _candidate_definition_template(
            name,
            domain,
            dominant_types,
            depth=self._config.definition_depth,
        )

    # ------------------------------------------------------------------
    # Clause builders
    # ------------------------------------------------------------------

    def _intro_clause(self, candidate: KindCandidate) -> str:
        """Return the introductory clause of a formal definition."""
        formal = _formal_name(candidate.name)
        num_types = len(candidate.obstruction_types)
        return (
            f"A {formal} X is an object satisfying the following {num_types} "
            f"obstruction-derived axioms, arising from the pattern(s) "
            f"{', '.join(candidate.pattern_ids[:3])}."
        )

    def _obstruction_clause(self, candidate: KindCandidate) -> str:
        """Return a clause describing the obstruction structure."""
        if not candidate.obstruction_types:
            return "No specific obstruction structure has been identified."
        type_phrases = [_OBS_TYPE_VOCAB.get(ot, ot) for ot in candidate.obstruction_types]
        joined = "; ".join(type_phrases)
        return (
            f"The obstruction structure of a {candidate.name} comprises: {joined}."
        )

    def _closure_clause(self, candidate: KindCandidate) -> str:
        """Return a closure property clause."""
        formal = _formal_name(candidate.name)
        return (
            f"  [Closure] The class of {formal}s is closed under "
            f"obstruction-resolution: if X is a {formal} and f : X → Y "
            f"resolves all constituent obstructions, then Y is also a {formal}."
        )

    def _existence_clause(self, candidate: KindCandidate) -> str:
        """Return an existence clause."""
        formal = _formal_name(candidate.name)
        return (
            f"  [Existence] There exists at least one non-degenerate {formal}; "
            f"moreover, each of the {len(candidate.obstruction_types)} obstruction "
            f"types is witnessed in this example."
        )

    # ------------------------------------------------------------------
    # Refinement
    # ------------------------------------------------------------------

    def refine_definition(
        self,
        definition: str,
        *,
        extra_constraints: tuple[str, ...] = (),
    ) -> str:
        """Append extra constraints to an existing definition text.

        Each constraint in *extra_constraints* is appended as an additional
        numbered axiom following any existing axioms in the definition.
        """
        if not extra_constraints:
            return definition
        # Count existing axioms
        existing_axioms = len(re.findall(r"\[Axiom \d+\]", definition))
        extra_lines: list[str] = []
        for idx, constraint in enumerate(extra_constraints, start=existing_axioms + 1):
            extra_lines.append(f"  [Axiom {idx}] {constraint}")
        return definition + "\n" + "\n".join(extra_lines)

    def validate_definition(self, definition: str) -> tuple[bool, list[str]]:
        """Perform basic quality checks on a definition string.

        Returns a (valid, issues) tuple where *issues* lists any detected
        problems.  A definition is considered valid when there are no issues.
        """
        issues: list[str] = []
        if len(definition) < 50:
            issues.append("Definition is too short (< 50 characters).")
        if not re.search(r"\bKind\b|\bkind\b", definition):
            issues.append("Definition does not mention 'kind'.")
        if not re.search(r"\baxiom\b|\bAxiom\b|\bsatisfying\b|\bcharacterised by\b", definition, re.IGNORECASE):
            issues.append("Definition lacks an explicit axiom or characterisation clause.")
        if definition.count(".") < 2:
            issues.append("Definition has fewer than 2 sentences.")
        if re.search(r"placeholder|TODO|FIXME|stub", definition, re.IGNORECASE):
            issues.append("Definition contains placeholder text.")
        return len(issues) == 0, issues


# ---------------------------------------------------------------------------
# ExampleGenerator
# ---------------------------------------------------------------------------


class ExampleGenerator:
    """Generate illustrative examples for a kind candidate or new kind.

    Produces three categories of examples:
    * **Positive examples** – objects that satisfy the kind's definition
    * **Negative examples** – objects that conspicuously fail one axiom
    * **Boundary examples** – objects on the edge (degenerate / limiting cases)
    """

    def __init__(self, config: BootstrapConfig | None = None) -> None:
        self._config = config or BootstrapConfig()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, candidate: KindCandidate) -> list[str]:
        """Return a combined list of positive, negative, and boundary examples."""
        target = max(1, self._config.example_count)
        pos_count = max(1, target - 2)
        neg_count = min(2, target - pos_count)
        boundary_count = max(0, target - pos_count - neg_count)

        positives = self.generate_positive(candidate)[:pos_count]
        negatives = self.generate_negative(candidate)[:neg_count]
        boundaries = self.generate_boundary(candidate)[:boundary_count]
        return positives + negatives + boundaries

    def generate_positive(self, candidate: KindCandidate) -> list[str]:
        """Generate positive examples for *candidate*."""
        examples: list[str] = []
        formal = _formal_name(candidate.name)
        obstruction_types = _candidate_obstruction_types(candidate)

        # One example per obstruction type
        for obs_type in obstruction_types[: self._config.example_count]:
            ex = self._example_from_obstruction(obs_type, formal)
            examples.append(ex)

        # If fewer than requested, generate generic structural examples
        generic_templates = [
            f"The {formal} arising as the limit of the canonical tower in the {candidate.name} domain.",
            f"Any minimal obstruction-free extension of a {candidate.name} is itself a {formal}.",
            f"The colimit of the diagram of {candidate.name} inclusions is a {formal}.",
            f"The pullback of two {formal}s along a common morphism is a {formal}.",
        ]
        for tmpl in generic_templates:
            if len(examples) >= self._config.example_count:
                break
            examples.append(tmpl)
        return examples[: self._config.example_count]

    def generate_negative(self, candidate: KindCandidate) -> list[str]:
        """Generate negative (counter-)examples for *candidate*."""
        formal = _formal_name(candidate.name)
        negatives: list[str] = []
        obstruction_types = _candidate_obstruction_types(candidate)

        for obs_type in obstruction_types[:3]:
            neg = self._negative_example_from_obstruction(obs_type, formal)
            negatives.append(neg)

        # Generic negatives
        missing_vocab = (
            _OBS_TYPE_VOCAB.get(obstruction_types[0], "obstruction")
            if obstruction_types
            else "obstruction witness"
        )
        generic = [
            f"A {formal} with one axiom violated: it lacks a complete {missing_vocab}.",
            f"The empty object is not a {formal} because existence is violated.",
        ]
        negatives.extend(generic)
        return negatives[:3]

    def generate_boundary(self, candidate: KindCandidate) -> list[str]:
        """Generate boundary/degenerate examples for *candidate*."""
        formal = _formal_name(candidate.name)
        return [
            f"The terminal {formal}: admits every obstruction trivially (degenerate).",
            f"The initial {formal}: admits no obstruction; existence axiom is borderline satisfied.",
        ]

    def generate_from_definition(self, definition: str, name: str) -> list[str]:
        """Generate examples based on the definition text and kind name.

        Parses axiom markers in *definition* to produce one example per axiom.
        """
        formal = _formal_name(name)
        axioms = re.findall(r"\[Axiom \d+\]\s+(.*?)(?=\[Axiom|\Z)", definition, re.DOTALL)
        examples: list[str] = []
        for i, axiom_text in enumerate(axioms[:5], start=1):
            axiom_summary = axiom_text.strip().split(".")[0][:80]
            examples.append(
                f"Example {i}: A {formal} satisfying axiom {i} "
                f"({axiom_summary}...)."
            )
        if not examples:
            examples.append(
                f"Canonical example: the free {formal} generated by a single "
                f"element of the base domain."
            )
        return examples

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _example_from_obstruction(self, obs_type: str, formal_name: str) -> str:
        """Construct a positive example sentence for one obstruction type."""
        vocab = _OBS_TYPE_VOCAB.get(obs_type, obs_type)
        evidence = _EVIDENCE_VOCAB.get(obs_type, ())
        ev_phrase = f" (witnessed by a {evidence[0]})" if evidence else ""
        return (
            f"Positive: A {formal_name} exhibiting a canonical {vocab}{ev_phrase}."
        )

    def _negative_example_from_obstruction(self, obs_type: str, formal_name: str) -> str:
        """Construct a negative example sentence for one obstruction type."""
        vocab = _OBS_TYPE_VOCAB.get(obs_type, obs_type)
        return (
            f"Negative: An object that fails to admit a {vocab} and therefore "
            f"is not a {formal_name}."
        )

    def format_examples(self, examples: list[str]) -> str:
        """Format a list of example strings as a numbered markdown list."""
        if not examples:
            return "(no examples)"
        lines = [f"{i}. {ex}" for i, ex in enumerate(examples, start=1)]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# ValidationPlanner
# ---------------------------------------------------------------------------


class ValidationPlanner:
    """Create :class:`ValidationPath` objects for kind candidates and new kinds.

    The planner constructs ordered validation steps, required evidence, and
    success criteria based on the obstruction types and confidence of the
    candidate.  Higher confidence candidates receive shorter, more targeted
    plans; lower confidence candidates receive more exploratory plans.
    """

    # Templates for validation steps, keyed by validation-phase index
    _PHASE_TEMPLATES: tuple[str, ...] = (
        "Verify the informal definition against at least two known examples.",
        "Formalise the definition within the target proof assistant or framework.",
        "Check that the closure axiom holds for the provided positive examples.",
        "Identify at least one non-trivial negative example and verify exclusion.",
        "Construct the canonical existence witness for the kind.",
        "Verify consistency of the obstruction axioms by checking no pair is contradictory.",
        "Run an automated sanity check (type-checker / solver discharge) on the axioms.",
        "Obtain human attestation from a domain expert.",
    )

    def __init__(self, config: BootstrapConfig | None = None) -> None:
        self._config = config or BootstrapConfig()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def plan(self, candidate: KindCandidate) -> ValidationPath:
        """Create a :class:`ValidationPath` for *candidate*."""
        steps = self._steps_for_candidate(candidate)
        evidence = self._evidence_for_candidate(candidate)
        criteria = self._criteria_for_candidate(candidate)
        return ValidationPath(
            steps=steps,
            required_evidence=evidence,
            success_criteria=criteria,
        )

    def plan_for_new_kind(self, kind: NewKind) -> ValidationPath:
        """Create a validation plan for an already-bootstrapped :class:`NewKind`.

        Produces a more thorough plan than :meth:`plan` since the kind already
        has a definition and examples that can be leveraged.
        """
        # Build base plan from a synthetic candidate
        synthetic = KindCandidate(
            candidate_id=kind.candidate_id or str(uuid.uuid4()),
            name=kind.name,
            description=kind.description,
            obstruction_types=kind.obstruction_types,
            confidence=kind.confidence,
            novelty=kind.novelty,
            examples=kind.examples,
        )
        base_path = self.plan(synthetic)

        # Extend with kind-specific steps
        kind_label = kind.name or kind.formal_name or "this kind"
        extra_steps: list[str] = [
            f"Confirm that {kind_label} is distinct from adjacent notions in the literature."
        ]
        extra_evidence_items: list[str] = [f"named examples of {kind_label}"]
        if kind.examples:
            extra_steps.append(
                f"Validate all {len(kind.examples)} provided examples of {kind_label} individually."
            )
        if kind.theorems:
            extra_steps.append(
                f"Verify the {len(kind.theorems)} stated theorem(s) about {kind_label} hold for all "
                f"positive examples."
            )
        if kind.related_kinds:
            extra_steps.append(
                f"Check that {kind_label} is properly distinct from related kinds: "
                f"{', '.join(kind.related_kinds[:3])}."
            )

        if extra_steps:
            combined_steps = base_path.steps + tuple(extra_steps)
            extra_evidence = tuple(
                dict.fromkeys(
                    list(_evidence_keywords(kind.obstruction_types)) + extra_evidence_items
                )
            )
            combined_evidence = tuple(dict.fromkeys(base_path.required_evidence + extra_evidence))
            return ValidationPath(
                steps=combined_steps,
                required_evidence=combined_evidence,
                success_criteria=base_path.success_criteria,
            )
        return base_path

    def _evidence_for_candidate(self, candidate: KindCandidate) -> tuple[str, ...]:
        """Derive required evidence items from the candidate's obstruction types."""
        kws = _evidence_keywords(candidate.obstruction_types)
        # Add confidence-based evidence requirements
        extra: list[str] = []
        if candidate.confidence < 0.5:
            extra.append("independent corroboration from a second source")
        if candidate.novelty > 0.7:
            extra.append("novelty assessment from a domain expert")
        return tuple(dict.fromkeys(list(kws) + extra))

    def _steps_for_candidate(self, candidate: KindCandidate) -> tuple[str, ...]:
        """Derive validation steps from the candidate's properties."""
        n_steps = self._config.validation_steps_count
        # Choose steps based on confidence
        high_confidence = candidate.confidence >= 0.7
        selected: list[str] = []
        if high_confidence:
            # Targeted steps: focus on formalisation and verification
            indices = [1, 2, 3, 4, 6]
        else:
            # Exploratory steps: start from informal verification
            indices = [0, 1, 2, 3, 4, 5, 7]

        for idx in indices[:n_steps]:
            selected.append(self._PHASE_TEMPLATES[idx])

        # Ensure at least n_steps are returned
        extra_idx = 0
        while len(selected) < n_steps and extra_idx < len(self._PHASE_TEMPLATES):
            tmpl = self._PHASE_TEMPLATES[extra_idx]
            if tmpl not in selected:
                selected.append(tmpl)
            extra_idx += 1

        return tuple(selected[:n_steps])

    def _criteria_for_candidate(self, candidate: KindCandidate) -> tuple[str, ...]:
        """Derive success criteria from the candidate's properties."""
        criteria: list[str] = [
            "All positive examples satisfy every stated axiom.",
            "All negative examples fail at least one axiom.",
            "The closure axiom is verified for a non-trivial morphism.",
        ]
        if candidate.confidence >= 0.6:
            criteria.append("An automated solver discharges the consistency check.")
        if len(candidate.obstruction_types) >= 3:
            criteria.append(
                "Each of the constituent obstruction types is independently witnessed."
            )
        return tuple(criteria)

    def strengthen_plan(
        self,
        path: ValidationPath,
        *,
        extra_evidence: tuple[str, ...] = (),
    ) -> ValidationPath:
        """Return a strengthened plan with additional evidence requirements."""
        combined = tuple(dict.fromkeys(path.required_evidence + extra_evidence))
        extra_step = (
            "Perform a cross-validation check against an independent obstruction corpus.",
        )
        combined_steps = path.steps + extra_step
        extra_criterion = "Cross-validation passes with precision ≥ 0.90."
        combined_criteria = path.success_criteria + (extra_criterion,)
        return ValidationPath(
            steps=combined_steps,
            required_evidence=combined,
            success_criteria=combined_criteria,
        )

    def plan_from_bootstrap(self, plan: KindBootstrapPlan) -> ValidationPath:
        """Extract a :class:`ValidationPath` from a :class:`KindBootstrapPlan`."""
        return ValidationPath(
            steps=plan.steps,
            required_evidence=plan.required_evidence,
            success_criteria=plan.success_criteria,
        )


# ---------------------------------------------------------------------------
# KindBootstrapper
# ---------------------------------------------------------------------------


class KindBootstrapper:
    """Orchestrate the full kind-bootstrapping pipeline.

    The bootstrapper takes :class:`KindPattern` objects (or
    :class:`KindCandidate` objects) and produces fully-defined
    :class:`NewKind` objects together with :class:`KindBootstrapPlan` objects
    and (optionally) associated :class:`Idea` objects.

    Pipeline stages
    ---------------
    1. Hypothesize candidates from patterns (:class:`KindHypothesizer`)
    2. Build definitions for each viable candidate (:class:`DefinitionBuilder`)
    3. Generate examples (:class:`ExampleGenerator`)
    4. Plan validation (:class:`ValidationPlanner`)
    5. Optionally generate ideas (:class:`IdeaGenerator`)
    6. Assemble :class:`NewKind` and :class:`KindBootstrapPlan` objects
    """

    def __init__(
        self,
        config: BootstrapConfig | None = None,
        generator: IdeaGenerator | None = None,
        evaluator: IdeaEvaluator | None = None,
    ) -> None:
        self._config = config or BootstrapConfig()
        self._hypothesizer = KindHypothesizer(self._config)
        self._def_builder = DefinitionBuilder(self._config)
        self._ex_generator = ExampleGenerator(self._config)
        self._val_planner = ValidationPlanner(self._config)
        self._generator = generator or IdeaGenerator()
        self._evaluator = evaluator or IdeaEvaluator()
        self._bootstrapped_kinds: list[NewKind] = []

    # ------------------------------------------------------------------
    # Public API – main entry points
    # ------------------------------------------------------------------

    def bootstrap(self, patterns: list[KindPattern]) -> list[NewKind]:
        """Bootstrap new kinds from a list of patterns.

        Runs the full pipeline: hypothesize → filter → build → plan → assemble.
        """
        if not patterns:
            return []
        candidates = self._hypothesizer.hypothesize_batch(patterns)
        viable = self._hypothesizer.filter_viable(candidates)
        return self.bootstrap_from_candidates(viable)

    def bootstrap_from_candidates(
        self, candidates: list[KindCandidate]
    ) -> list[NewKind]:
        """Bootstrap new kinds from pre-existing :class:`KindCandidate` objects.

        Unlike :meth:`bootstrap`, this skips the hypothesize step and uses
        the candidates directly.
        """
        new_kinds: list[NewKind] = []
        total_effort = 0.0

        for candidate in candidates:
            if not candidate.is_viable(self._config.min_candidate_confidence):
                continue
            effort = _estimate_effort(candidate, depth=self._config.definition_depth)
            if total_effort + effort > self._config.effort_budget:
                # Skip expensive candidates once we exceed the effort budget
                continue
            kind = self.bootstrap_single(candidate)
            if kind is not None:
                new_kinds.append(kind)
                total_effort += effort

        self._bootstrapped_kinds.extend(new_kinds)
        return new_kinds

    def bootstrap_single(self, candidate: KindCandidate) -> NewKind | None:
        """Bootstrap a single :class:`NewKind` from one candidate.

        Returns ``None`` if the candidate is not viable or if definition
        validation fails.
        """
        if not candidate.is_viable(self._config.min_candidate_confidence):
            return None

        # 1. Build definition
        definition = self._def_builder.build_formal(candidate)
        valid, issues = self._def_builder.validate_definition(definition)
        if not valid and len(issues) > 2:
            # Too many issues – fall back to informal definition
            definition = self._def_builder.build(candidate)

        # 2. Generate examples
        examples = self._ex_generator.generate(candidate)

        # 3. Plan validation
        val_path = self._val_planner.plan(candidate)

        # 4. Assemble NewKind
        kind_id = str(uuid.uuid4())
        now = _now_iso()
        kind = NewKind(
            kind_id=kind_id,
            name=candidate.name,
            formal_name=_formal_name(candidate.name),
            definition=definition,
            formal_definition=definition,
            description=candidate.description,
            domain=" | ".join(candidate.field_ids[:3]) if candidate.field_ids else "general",
            examples=tuple(examples),
            obstruction_types=_candidate_obstruction_types(candidate),
            status=KindStatus.PROVISIONAL,
            confidence=candidate.confidence,
            novelty=candidate.novelty,
            candidate_id=candidate.candidate_id,
            created_at=now,
        )
        return kind

    def create_bootstrap_plan(self, candidate: KindCandidate) -> KindBootstrapPlan:
        """Create a :class:`KindBootstrapPlan` for *candidate*."""
        val_path = self._val_planner.plan(candidate)
        effort = _estimate_effort(candidate, depth=self._config.definition_depth)
        priority = _clamp(
            candidate.confidence * 0.5 + candidate.novelty * 0.5, 0.0, 1.0
        )
        return KindBootstrapPlan(
            plan_id=str(uuid.uuid4()),
            candidate_id=candidate.candidate_id,
            kind_name=candidate.name,
            target_kind=candidate.name,
            steps=val_path.steps,
            required_evidence=val_path.required_evidence,
            success_criteria=val_path.success_criteria,
            effort_estimate=effort,
            estimated_effort=effort,
            priority=priority,
            status=KindStatus.BOOTSTRAP_PENDING,
            created_at=_now_iso(),
        )

    # ------------------------------------------------------------------
    # Idea generation
    # ------------------------------------------------------------------

    def generate_ideas_for_kind(self, kind: NewKind) -> list[Idea]:
        """Generate research ideas motivated by the newly discovered kind.

        Uses the :class:`IdeaGenerator` to propose ideas whose purpose is
        centred on the kind's definition and domain.
        """
        if not self._config.auto_generate_ideas:
            return []
        count = self._config.idea_count_per_kind
        purpose = f"Develop and apply the {kind.name} to problems in {kind.domain}"
        target_area = kind.domain if kind.domain else "ideation"
        observations = tuple(
            f"The {kind.name} exhibits obstruction type: {ot}"
            for ot in kind.obstruction_types[:3]
        )
        try:
            raw = self._generator.generate(
                purpose=purpose,
                target_area=target_area,
                observations=observations,
                count=count,
            )
            return list(raw)
        except Exception:
            return []

    # ------------------------------------------------------------------
    # Evaluation and ranking
    # ------------------------------------------------------------------

    def evaluate_kind(
        self, kind: NewKind, *, portfolio: tuple[Idea, ...] = ()
    ) -> float:
        """Return a composite quality score in [0, 1] for *kind*.

        The score combines:
        * Confidence (30 %)
        * Novelty (30 %)
        * Definition completeness (20 %)
        * Example coverage (20 %)
        """
        conf_score = kind.confidence
        novelty_score = kind.novelty
        # Definition completeness: reward longer, axiom-rich definitions
        def_len = len(kind.definition)
        axiom_count = len(re.findall(r"\[Axiom \d+\]", kind.definition))
        def_score = _clamp(
            (def_len / 800.0) * 0.5 + (axiom_count / 5.0) * 0.5, 0.0, 1.0
        )
        # Example coverage: reward having both positive and negative examples
        has_pos = any("Positive" in e or "example" in e.lower() for e in kind.examples)
        has_neg = any("Negative" in e or "not a" in e.lower() for e in kind.examples)
        ex_score = _clamp(
            len(kind.examples) / max(1.0, self._config.example_count) * 0.6
            + 0.2 * has_pos
            + 0.2 * has_neg,
            0.0,
            1.0,
        )
        composite = (
            0.30 * conf_score
            + 0.30 * novelty_score
            + 0.20 * def_score
            + 0.20 * ex_score
        )
        return _clamp(round(composite, 4), 0.0, 1.0)

    def rank_kinds(self, kinds: list[NewKind]) -> list[tuple[NewKind, float]]:
        """Return kinds sorted by quality score, highest first."""
        scored = [(k, self.evaluate_kind(k)) for k in kinds]
        return sorted(scored, key=lambda x: x[1], reverse=True)

    # ------------------------------------------------------------------
    # Reporting
    # ------------------------------------------------------------------

    def full_report(self, kinds: list[NewKind]) -> dict[str, Any]:
        """Return a comprehensive dict report for a list of new kinds."""
        ranked = self.rank_kinds(kinds)
        by_status: dict[str, int] = Counter(k.status for k in kinds)
        avg_confidence = (
            sum(k.confidence for k in kinds) / len(kinds) if kinds else 0.0
        )
        avg_novelty = (
            sum(k.novelty for k in kinds) / len(kinds) if kinds else 0.0
        )
        obstruction_type_dist: Counter = Counter()
        for k in kinds:
            obstruction_type_dist.update(k.obstruction_types)
        return {
            "total_kinds": len(kinds),
            "by_status": dict(by_status),
            "average_confidence": round(avg_confidence, 4),
            "average_novelty": round(avg_novelty, 4),
            "top_3": [
                {"name": k.name, "score": round(s, 4), "status": k.status}
                for k, s in ranked[:3]
            ],
            "obstruction_type_distribution": dict(obstruction_type_dist),
            "config": self._config.to_dict(),
            "generated_at": _now_iso(),
        }

    def diagnostics(self, kinds: list[NewKind]) -> dict[str, Any]:
        """Return structured diagnostics for a list of new kinds."""
        if not kinds:
            return {
                "total_kinds": 0,
                "ranked_kinds": [],
                "score_stats": {"mean": 0.0, "max": 0.0, "min": 0.0},
                "below_confidence": [],
                "config": self._config.to_dict(),
                "generated_at": _now_iso(),
            }
        ranked = self.rank_kinds(kinds)
        ranked_kinds = []
        for kind, score in ranked:
            ranked_kinds.append(
                {
                    "name": kind.name,
                    "score": score,
                    "confidence": kind.confidence,
                    "novelty": kind.novelty,
                    "obstruction_type_count": len(kind.obstruction_types),
                    "example_count": len(kind.examples),
                    "definition_word_count": len(kind.definition.split()),
                }
            )

        low_conf = [
            {"name": kind.name, "confidence": kind.confidence}
            for kind, _ in ranked
            if kind.confidence < self._config.min_candidate_confidence
        ]
        scores = [s for _, s in ranked]
        mean_score = sum(scores) / len(scores) if scores else 0.0
        max_score = max(scores) if scores else 0.0
        min_score = min(scores) if scores else 0.0
        return {
            "total_kinds": len(kinds),
            "ranked_kinds": ranked_kinds,
            "score_stats": {
                "mean": round(mean_score, 4),
                "max": round(max_score, 4),
                "min": round(min_score, 4),
            },
            "below_confidence": low_conf,
            "config": self._config.to_dict(),
            "generated_at": _now_iso(),
        }
