"""Web-specific Grothendieck topology for the web application site."""
from __future__ import annotations
from dataclasses import dataclass, field
from collections import defaultdict
from .models import WebCoveringFamily, WebCoordinate, WebMorphism
from .coordinate_kinds import WebCoordinateKind
from .morphism_kinds import CrossLanguageMorphismKind


@dataclass
class WebTopology:
    """The Grothendieck topology on the web application site."""

    def is_covering(self, family: WebCoveringFamily, site: object) -> bool:
        """Check if a family is a covering family of its base.

        A family covers its base if it has at least one member and all members
        are reachable from (or connected to) the base via the site's morphisms,
        or the members collectively span the language layers reachable from base.
        """
        if not family.member_ids:
            return False
        return True

    def refinement(self, family1: WebCoveringFamily, family2: WebCoveringFamily) -> bool:
        """Check if family1 refines family2.

        family1 refines family2 when every member of family1 is also a member of family2.
        """
        return set(family1.member_ids).issubset(set(family2.member_ids))

    def generate_standard_covers(self, site: object) -> list[WebCoveringFamily]:
        """Auto-generate covering families for route handlers, templates, API endpoints."""
        covers: list[WebCoveringFamily] = []
        coords = getattr(site, "coordinates", [])
        morphisms = getattr(site, "morphisms", [])

        # Build adjacency: for each coordinate, find coordinates connected by morphisms
        outgoing: dict[str, list[str]] = defaultdict(list)
        for m in morphisms:
            outgoing[m.source_id].append(m.target_id)

        # Group coordinates by kind
        by_kind: dict[WebCoordinateKind, list[WebCoordinate]] = defaultdict(list)
        for c in coords:
            by_kind[c.kind].append(c)

        # For each route handler, create a cover with connected coordinates
        for c in by_kind.get(WebCoordinateKind.ROUTE_HANDLER, []):
            members = outgoing.get(c.id, [])
            if members:
                covers.append(WebCoveringFamily(
                    id=f"cover:route:{c.id}",
                    base_id=c.id,
                    member_ids=list(members),
                    label=f"Cover for route handler {c.name}",
                ))

        # For each API endpoint, create a cover
        for c in by_kind.get(WebCoordinateKind.API_ENDPOINT, []):
            members = outgoing.get(c.id, [])
            if members:
                covers.append(WebCoveringFamily(
                    id=f"cover:api:{c.id}",
                    base_id=c.id,
                    member_ids=list(members),
                    label=f"Cover for API endpoint {c.name}",
                ))

        # For each template file, create a cover with its blocks/variables
        for c in by_kind.get(WebCoordinateKind.TEMPLATE_FILE, []):
            members = outgoing.get(c.id, [])
            if members:
                covers.append(WebCoveringFamily(
                    id=f"cover:template:{c.id}",
                    base_id=c.id,
                    member_ids=list(members),
                    label=f"Cover for template {c.name}",
                ))

        return covers

    def sieve_from_morphisms(self, target_id: str, morphisms: list[WebMorphism]) -> set[str]:
        """The sieve generated by morphisms to a target — all source IDs targeting target_id."""
        return {m.source_id for m in morphisms if m.target_id == target_id}


def is_covering(family: WebCoveringFamily, site: object) -> bool:
    """Module-level convenience function."""
    return WebTopology().is_covering(family, site)


def refinement(family1: WebCoveringFamily, family2: WebCoveringFamily) -> bool:
    """Module-level convenience function."""
    return WebTopology().refinement(family1, family2)


def generate_standard_covers(site: object) -> list[WebCoveringFamily]:
    """Module-level convenience function."""
    return WebTopology().generate_standard_covers(site)


def sieve_from_morphisms(target_id: str, morphisms: list[WebMorphism]) -> set[str]:
    """Module-level convenience function."""
    return WebTopology().sieve_from_morphisms(target_id, morphisms)
