"""Stage S01: Self-Improving System — JuGeo cyclic_picture package.

copilot: shared-core marker
Theory reference: theory2.tex Ch65

Overview
--------
Stage S01 implements the self-improvement pipeline stage of the cyclic picture
framework described in Ch65 of theory2.tex.  The cyclic picture is a
formalisation of how a mature geometric-reasoning system bootstraps itself
through successive capability expansions while preserving soundness.  S01 is
the opening stage: it receives a raw ``MatureSystem`` object and drives it
through one or more improvement cycles, each of which may extend the system's
capability set, re-tune its priority weights, and record detailed metrics so
that later stages (S02 federated deployment, S03 mature pipeline) can consume
a stable, improved artefact.

Self-improvement soundness theorem (Ch65, §3.2)
-----------------------------------------------
The theorem states that, given a monotone improvement strategy *σ* and a
capability lattice *L*, every finite sequence of improvement cycles produces a
system whose capability set lies strictly above the starting point in *L*,
provided the improvement score exceeds the zero threshold at each step.  The
classes in this module implement the computational witnesses for that theorem:

* ``ImprovementStrategy`` encodes *σ* as a priority-weighted mapping from
  capability domains to improvement kinds.
* ``MetricsTracker`` provides the observation functor that maps system states
  to real-valued measurement sequences.
* ``CapabilityExpander`` maintains the capability lattice element for the
  current system and proposes upward moves.
* ``SelfImprovementRunner`` orchestrates a full sequence of cycles and
  produces the evidence record consumed by the provenance layer.

All public names are listed in ``__all__``.
"""
from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Optional

__all__ = [
    "ImprovementStrategy",
    "MetricsTracker",
    "CapabilityExpander",
    "SelfImprovementRunner",
    "run_improvement_cycle",
    "assess_improvement",
    "compute_improvement_score",
    "select_best_strategy",
]

# ---------------------------------------------------------------------------
# Cross-module imports (guarded)
# ---------------------------------------------------------------------------
try:
    from jugeo.maturity.cyclic_picture.models import (
        ImprovementCycle,
        ImprovementKind,
        MaturityLevel,
        MatureSystem,
        SelfImprovingEngine,
        FederationState,
    )
except Exception:
    pass

# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------


def _utcnow() -> str:
    """Return the current UTC time as an ISO-8601 string.

    Uses ``time.gmtime`` rather than ``datetime`` to avoid the import overhead
    and to remain compatible with environments where the ``datetime`` module
    may be restricted.  The returned string is always in the format
    ``YYYY-MM-DDTHH:MM:SSZ``.
    """
    t = time.gmtime()
    return (
        f"{t.tm_year:04d}-{t.tm_mon:02d}-{t.tm_mday:02d}"
        f"T{t.tm_hour:02d}:{t.tm_min:02d}:{t.tm_sec:02d}Z"
    )


def _uid() -> str:
    """Generate a short, unique identifier string.

    Produces a 16-character hex string derived from a UUID4 value.  The
    truncation keeps identifiers human-readable while providing enough entropy
    (64 bits) for practical uniqueness within a single pipeline run.

    Returns
    -------
    str
        A 16-character lowercase hexadecimal string.
    """
    return uuid.uuid4().hex[:16]


def _clamp(value: float, lo: float, hi: float) -> float:
    """Clamp *value* to the closed interval [*lo*, *hi*].

    Parameters
    ----------
    value:
        The floating-point number to clamp.
    lo:
        The lower bound (inclusive).
    hi:
        The upper bound (inclusive).

    Returns
    -------
    float
        The clamped value.
    """
    return max(lo, min(hi, value))


# ---------------------------------------------------------------------------
# ImprovementStrategy
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class ImprovementStrategy:
    """An improvement strategy encodes the target improvement kinds and scoring
    logic for a self-improvement cycle, acting as the computational witness for
    the monotone strategy *σ* described in Ch65 §3.2.

    Attributes
    ----------
    strategy_id : str
        Unique identifier for this strategy instance, generated by ``_uid()``.
    name : str
        Human-readable name, e.g. ``'balanced'`` or ``'geometry-first'``.
    description : str
        Prose description of what this strategy optimises.
    target_kinds : list[str]
        List of ``ImprovementKind`` values as strings that this strategy
        targets.  By default populated with all five canonical kinds:
        capability, efficiency, coverage, robustness, federation.
    """

    strategy_id: str
    name: str
    description: str
    target_kinds: list = field(default_factory=list)

    # ------------------------------------------------------------------
    @classmethod
    def create(cls, name: str, description: str) -> "ImprovementStrategy":
        """Factory method that constructs a new ``ImprovementStrategy``.

        Generates a fresh ``strategy_id`` via ``_uid()`` and populates
        ``target_kinds`` with every value in the ``ImprovementKind`` enum so
        that the strategy covers all improvement dimensions by default.

        Parameters
        ----------
        name:
            Short human-readable label for the strategy.
        description:
            Detailed prose explaining what the strategy targets and why.

        Returns
        -------
        ImprovementStrategy
            A freshly created instance with all ``ImprovementKind`` values as
            strings in ``target_kinds``.
        """
        try:
            kinds = [k.value for k in ImprovementKind]
        except Exception:
            kinds = ["capability", "efficiency", "coverage", "robustness", "federation"]
        return cls(
            strategy_id=_uid(),
            name=name,
            description=description,
            target_kinds=kinds,
        )

    # ------------------------------------------------------------------
    def score_opportunity(self, before: float, after: float) -> float:
        """Compute the relative improvement between two scalar metric values.

        Returns the normalised gain clamped at zero so that negative
        regressions score as 0.0 rather than a negative number.  The formula
        is::

            max(0.0, (after - before) / max(|before|, 1e-9))

        This satisfies the monotonicity requirement of the soundness theorem:
        a strategy never rewards regression.

        Parameters
        ----------
        before:
            The metric value before the improvement cycle.
        after:
            The metric value after the improvement cycle.

        Returns
        -------
        float
            Non-negative relative improvement score.
        """
        denom = max(abs(before), 1e-9)
        return max(0.0, (after - before) / denom)

    # ------------------------------------------------------------------
    def recommend_next_kind(self, history: list = None) -> str:
        """Recommend the next improvement kind based on cycle history length.

        Cycles through ``target_kinds`` using the length of *history* as a
        round-robin index so that successive calls with growing histories step
        through every kind in order.

        Parameters
        ----------
        history:
            Optional list of past cycle records.  Only its length is used.
            Defaults to an empty list when ``None``.

        Returns
        -------
        str
            The recommended improvement kind string.
        """
        if not self.target_kinds:
            return "capability"
        idx = len(history or []) % len(self.target_kinds)
        return self.target_kinds[idx]

    # ------------------------------------------------------------------
    def to_dict(self) -> dict:
        """Serialise this strategy to a plain dictionary.

        Returns
        -------
        dict
            A JSON-serialisable dictionary with keys ``strategy_id``, ``name``,
            ``description``, and ``target_kinds``.
        """
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "description": self.description,
            "target_kinds": list(self.target_kinds),
        }


# ---------------------------------------------------------------------------
# MetricsTracker
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class MetricsTracker:
    """A windowed time-series tracker for named float metrics.

    Maintains an append-only list of observations for each metric key and
    provides rolling statistics (current, delta, trend, windowed average) over
    a configurable window.  This class is the observation functor referred to
    in Ch65 §3.2 — it maps a sequence of system states to a real-valued
    measurement stream.

    Attributes
    ----------
    tracker_id : str
        Unique identifier for this tracker instance.
    window_size : int
        Maximum number of recent observations used by windowed statistics.
    metrics : dict[str, list[float]]
        Raw observation lists, keyed by metric name.  Grows unboundedly; the
        window is applied only at query time.
    """

    tracker_id: str
    window_size: int
    metrics: dict = field(default_factory=dict)

    # ------------------------------------------------------------------
    @classmethod
    def create(cls, window_size: int = 20) -> "MetricsTracker":
        """Factory method for ``MetricsTracker``.

        Parameters
        ----------
        window_size:
            Number of recent values to use for windowed statistics.  Defaults
            to 20, which is sufficient for a typical improvement run of
            ten-to-twenty cycles.

        Returns
        -------
        MetricsTracker
            A fresh instance with an empty metrics dictionary.
        """
        return cls(
            tracker_id=_uid(),
            window_size=window_size,
            metrics={},
        )

    # ------------------------------------------------------------------
    def record(self, key: str, value: float) -> None:
        """Append *value* to the observation list for metric *key*.

        Creates the list on first access so callers never need to initialise
        keys explicitly.

        Parameters
        ----------
        key:
            The metric name, e.g. ``'accuracy'`` or ``'throughput'``.
        value:
            The observed float value to append.
        """
        if key not in self.metrics:
            self.metrics[key] = []
        self.metrics[key].append(float(value))

    # ------------------------------------------------------------------
    def current(self, key: str) -> Optional[float]:
        """Return the most recently recorded value for *key*, or ``None``.

        Parameters
        ----------
        key:
            The metric name to query.

        Returns
        -------
        float or None
            The last element of the observation list, or ``None`` if the key
            has no observations or does not exist.
        """
        vals = self.metrics.get(key)
        if not vals:
            return None
        return vals[-1]

    # ------------------------------------------------------------------
    def delta(self, key: str) -> Optional[float]:
        """Return the most recent one-step change for *key*.

        * If the key has two or more observations, returns ``last - second_last``.
        * If the key has exactly one observation, returns ``0.0`` (no change
          yet observable).
        * If the key is unknown or has no observations, returns ``None``.

        Parameters
        ----------
        key:
            The metric name to query.

        Returns
        -------
        float or None
        """
        vals = self.metrics.get(key)
        if vals is None or len(vals) == 0:
            return None
        if len(vals) == 1:
            return 0.0
        return vals[-1] - vals[-2]

    # ------------------------------------------------------------------
    def trend(self, key: str) -> float:
        """Estimate the linear trend (slope) over the last *window_size* values.

        Uses a simple first-to-last slope estimate:
        ``(last - first) / max(n - 1, 1)`` where *n* is the number of windowed
        values.  This is computationally cheap and sufficient for the heuristic
        steering decisions made by ``SelfImprovementRunner``.

        Parameters
        ----------
        key:
            The metric name to query.

        Returns
        -------
        float
            Estimated slope.  Returns ``0.0`` if fewer than two observations
            are available.
        """
        vals = self.metrics.get(key, [])
        window = vals[-self.window_size:] if vals else []
        n = len(window)
        if n < 2:
            return 0.0
        return (window[-1] - window[0]) / max(n - 1, 1)

    # ------------------------------------------------------------------
    def windowed_average(self, key: str) -> float:
        """Return the arithmetic mean of the last *window_size* values for *key*.

        Parameters
        ----------
        key:
            The metric name to query.

        Returns
        -------
        float
            The windowed mean.  Returns ``0.0`` if the key has no observations.
        """
        vals = self.metrics.get(key, [])
        window = vals[-self.window_size:] if vals else []
        if not window:
            return 0.0
        return sum(window) / len(window)

    # ------------------------------------------------------------------
    def to_dict(self) -> dict:
        """Serialise this tracker to a plain dictionary.

        Returns
        -------
        dict
            A JSON-serialisable dictionary with keys ``tracker_id``,
            ``window_size``, and the metric key names stored under ``keys``.
        """
        return {
            "tracker_id": self.tracker_id,
            "window_size": self.window_size,
            "keys": list(self.metrics.keys()),
        }


# ---------------------------------------------------------------------------
# CapabilityExpander
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class CapabilityExpander:
    """Maintains the current capability set and proposes upward expansions.

    This class is the capability-lattice element referred to in Ch65 §3.2.
    ``known_capabilities`` is the current position in the lattice; every call
    to ``propose_expansions`` suggests moves that would raise it.

    Attributes
    ----------
    expander_id : str
        Unique identifier for this expander instance.
    known_capabilities : list[str]
        The capabilities currently known/enabled for the system.
    """

    expander_id: str
    known_capabilities: list = field(default_factory=list)

    # ------------------------------------------------------------------
    @classmethod
    def create(cls, initial_capabilities: list = None) -> "CapabilityExpander":
        """Factory method for ``CapabilityExpander``.

        Parameters
        ----------
        initial_capabilities:
            Optional list of capability strings to seed the expander with.
            Defaults to an empty list when ``None``.

        Returns
        -------
        CapabilityExpander
            A fresh instance with the given initial capabilities.
        """
        return cls(
            expander_id=_uid(),
            known_capabilities=list(initial_capabilities) if initial_capabilities else [],
        )

    # ------------------------------------------------------------------
    def add_capability(self, cap: str) -> None:
        """Add *cap* to ``known_capabilities`` if not already present.

        Idempotent: adding a capability that already exists is a no-op.

        Parameters
        ----------
        cap:
            The capability string to add.
        """
        if cap not in self.known_capabilities:
            self.known_capabilities.append(cap)

    # ------------------------------------------------------------------
    def remove_capability(self, cap: str) -> None:
        """Remove *cap* from ``known_capabilities`` if present.

        No-op if *cap* is not in the list, so callers do not need to guard
        with ``in`` checks.

        Parameters
        ----------
        cap:
            The capability string to remove.
        """
        if cap in self.known_capabilities:
            self.known_capabilities.remove(cap)

    # ------------------------------------------------------------------
    def propose_expansions(self, candidate_pool: list = None) -> list:
        """Return a list of capabilities not yet in ``known_capabilities``.

        If *candidate_pool* is provided, returns the subset of pool members
        that are not already known.  If no pool is provided, returns a
        default set of three generic capability strings (excluding any that
        happen to already be known).

        Parameters
        ----------
        candidate_pool:
            Optional list of candidate capability strings to filter against.

        Returns
        -------
        list[str]
            Capabilities that are in the pool but not yet known.
        """
        if candidate_pool is not None:
            return [c for c in candidate_pool if c not in self.known_capabilities]
        defaults = [
            "streaming_inference",
            "incremental_learning",
            "distributed_aggregation",
        ]
        return [d for d in defaults if d not in self.known_capabilities]

    # ------------------------------------------------------------------
    def to_dict(self) -> dict:
        """Serialise this expander to a plain dictionary.

        Returns
        -------
        dict
            A JSON-serialisable dictionary with keys ``expander_id`` and
            ``known_capabilities``.
        """
        return {
            "expander_id": self.expander_id,
            "known_capabilities": list(self.known_capabilities),
        }


# ---------------------------------------------------------------------------
# SelfImprovementRunner
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class SelfImprovementRunner:
    """Orchestrates a sequence of improvement cycles using a strategy, metrics
    tracker, and capability expander.

    ``SelfImprovementRunner`` is the top-level object for stage S01.  It wires
    together ``ImprovementStrategy``, ``MetricsTracker``, and
    ``CapabilityExpander`` into a coherent pipeline and records a history of
    cycle results that can be summarised into a report.

    Attributes
    ----------
    runner_id : str
        Unique identifier for this runner instance.
    strategy : ImprovementStrategy
        The strategy used to score and recommend improvements.
    tracker : MetricsTracker
        The metrics tracker that records per-cycle observations.
    expander : CapabilityExpander
        The capability expander that proposes new capabilities.
    cycle_history : list[dict]
        Append-only log of cycle result dictionaries produced by
        ``run_one_cycle``.
    """

    runner_id: str
    strategy: ImprovementStrategy
    tracker: MetricsTracker
    expander: CapabilityExpander
    cycle_history: list = field(default_factory=list)

    # ------------------------------------------------------------------
    @classmethod
    def create(cls) -> "SelfImprovementRunner":
        """Factory method for ``SelfImprovementRunner``.

        Creates a fresh strategy, tracker, and expander with default parameters
        and wires them together into a new runner.

        Returns
        -------
        SelfImprovementRunner
            A fully initialised runner ready to execute improvement cycles.
        """
        return cls(
            runner_id=_uid(),
            strategy=ImprovementStrategy.create("default", "Default improvement strategy"),
            tracker=MetricsTracker.create(),
            expander=CapabilityExpander.create(),
            cycle_history=[],
        )

    # ------------------------------------------------------------------
    def run_one_cycle(self, before_metrics: dict, after_metrics: dict) -> dict:
        """Execute a single improvement cycle and record the result.

        Records each metric in *before_metrics* and *after_metrics* to the
        tracker, computes the overall gain, and appends a result dict to
        ``cycle_history``.

        Parameters
        ----------
        before_metrics:
            Dict mapping metric names to their pre-cycle float values.
        after_metrics:
            Dict mapping metric names to their post-cycle float values.

        Returns
        -------
        dict
            A result dictionary with keys ``cycle_id``, ``gain``,
            ``before_metrics``, ``after_metrics``, and ``timestamp``.
        """
        for k, v in before_metrics.items():
            self.tracker.record("before_" + k, float(v))
        for k, v in after_metrics.items():
            self.tracker.record("after_" + k, float(v))

        gain = compute_improvement_score(before_metrics, after_metrics)
        result = {
            "cycle_id": _uid(),
            "gain": gain,
            "before_metrics": dict(before_metrics),
            "after_metrics": dict(after_metrics),
            "timestamp": _utcnow(),
        }
        self.cycle_history.append(result)
        return result

    # ------------------------------------------------------------------
    def run_n_cycles(self, n: int, metric_fn=None) -> list:
        """Execute *n* improvement cycles in sequence.

        Parameters
        ----------
        n:
            Number of cycles to run.  If ``n <= 0``, returns an empty list
            immediately.
        metric_fn:
            Optional callable with signature ``() -> (before_dict, after_dict)``.
            If provided, its return value is used as the metrics for each cycle.
            If ``None``, dummy metrics are used (``{"score": 0.5}`` before and
            ``{"score": 0.8}`` after).

        Returns
        -------
        list[dict]
            List of cycle result dicts in execution order.
        """
        results = []
        for _ in range(n):
            if metric_fn is not None:
                before, after = metric_fn()
            else:
                before = {"score": 0.5}
                after = {"score": 0.8}
            results.append(self.run_one_cycle(before, after))
        return results

    # ------------------------------------------------------------------
    def generate_report(self) -> dict:
        """Summarise all executed cycles into a report dictionary.

        Returns
        -------
        dict
            A dictionary with keys ``runner_id``, ``total_cycles``,
            ``avg_gain``, and ``cycle_history``.
        """
        total = len(self.cycle_history)
        avg_gain = (
            sum(c["gain"] for c in self.cycle_history) / total if total > 0 else 0.0
        )
        return {
            "runner_id": self.runner_id,
            "total_cycles": total,
            "avg_gain": avg_gain,
            "cycle_history": list(self.cycle_history),
        }

    # ------------------------------------------------------------------
    def to_dict(self) -> dict:
        """Serialise this runner to a plain dictionary.

        Returns
        -------
        dict
            A JSON-serialisable dictionary with keys ``runner_id``,
            ``strategy``, ``tracker``, and ``expander``.
        """
        return {
            "runner_id": self.runner_id,
            "strategy": self.strategy.to_dict(),
            "tracker": self.tracker.to_dict(),
            "expander": self.expander.to_dict(),
        }


# ---------------------------------------------------------------------------
# Free functions
# ---------------------------------------------------------------------------


def run_improvement_cycle(system: Any = None, kind: str = "capability") -> dict:
    """Run a single named improvement cycle against *system*.

    Creates dummy before/after metric dicts and computes the gain.  This
    function is a convenience wrapper suitable for quick integration tests and
    scripting; for production use prefer ``SelfImprovementRunner.run_one_cycle``.

    Parameters
    ----------
    system:
        An optional system object.  Accepted but not inspected; present for
        API compatibility with callers that pass a ``MatureSystem`` instance.
    kind:
        The improvement kind string, e.g. ``'capability'``.  Included in the
        returned dict for traceability.

    Returns
    -------
    dict
        A dictionary with keys ``cycle_id``, ``kind``, and ``gain``.
    """
    before = {"score": 0.5, "coverage": 0.6}
    after = {"score": 0.75, "coverage": 0.85}
    gain = compute_improvement_score(before, after)
    return {
        "cycle_id": _uid(),
        "kind": kind,
        "gain": gain,
    }


def assess_improvement(before: dict, after: dict) -> dict:
    """Return the absolute change for each key in *before*.

    For every key *k* in *before*, the result maps *k* to
    ``after.get(k, 0.0) - before[k]``.  Keys present only in *after* are
    ignored; keys present only in *before* use ``0.0`` as the after-value.

    Parameters
    ----------
    before:
        Baseline metric dictionary.
    after:
        Post-cycle metric dictionary.

    Returns
    -------
    dict
        Mapping from metric name to absolute change (may be negative).
    """
    result = {}
    for k, v in before.items():
        result[k] = float(after.get(k, 0.0)) - float(v)
    return result


def compute_improvement_score(before: dict, after: dict) -> float:
    """Compute the mean relative improvement across shared keys.

    Implements the same formula as ``models._compute_gain_from_metrics``:

        score = mean over shared keys of (after_k - before_k) / max(|before_k|, 1e-9)

    Parameters
    ----------
    before:
        Metric values before the improvement.
    after:
        Metric values after the improvement.

    Returns
    -------
    float
        Mean relative improvement, or ``0.0`` if there are no shared keys.
    """
    shared = set(before.keys()) & set(after.keys())
    if not shared:
        return 0.0
    total = 0.0
    for k in shared:
        denom = max(abs(float(before[k])), 1e-9)
        total += (float(after[k]) - float(before[k])) / denom
    return total / len(shared)


def select_best_strategy(
    strategies: list,
    context: dict = None,
) -> "ImprovementStrategy":
    """Return the strategy with the most target kinds.

    Selects the ``ImprovementStrategy`` whose ``target_kinds`` list is longest.
    On a tie, returns the first strategy in *strategies* with the maximum
    length.  The *context* parameter is accepted for API compatibility but is
    not currently used.

    Parameters
    ----------
    strategies:
        Non-empty list of ``ImprovementStrategy`` instances.
    context:
        Optional context dictionary; reserved for future use.

    Returns
    -------
    ImprovementStrategy
        The strategy with the most target kinds.
    """
    return max(strategies, key=lambda s: len(s.target_kinds))
