"""Schema templates for descent, trust, evidence, federation, and invalidation subsystems.

Encodes the theorem template library for Chapter 36 of theory2.tex. Each template
class provides pre-built TheoremSchema instances covering the required proofs for
its subsystem. Templates use {variable} placeholders that are instantiated with
concrete mathematical objects at proof time.

copilot: schema template library for all JuGeo subsystems.

Background
----------
Chapter 36 of theory2.tex specifies the *proof burden* for each JuGeo
subsystem: the minimal set of theorems that must be discharged before the
subsystem can be trusted in production. This module encodes that burden as a
library of :class:`~jugeo.encodings.theorem_schemas.models.TheoremSchema`
objects, one per theorem family, each with carefully chosen ``{variable}``
placeholders so that concrete proof obligations can be mass-generated by
binding the variables to specific mathematical objects at proof time.

The five subsystems covered here — Descent, Trust, Evidence, Federation, and
Invalidation — are the ones whose mathematical content is most thoroughly
developed in theory2.tex.  The remaining three (Memory, Judgment, Encoding)
are handled directly in :mod:`jugeo.encodings.theorem_schemas.subsystem_schemas`
because they do not yet have sufficiently general template structure.

Mathematical context
--------------------
* **Descent**: The JuGeo semantic site is a Grothendieck site.  The descent
  subsystem manages the sheaf condition, pullback functors, and effective
  descent morphisms.  Correctness requires that every pack's local sections
  glue uniquely to global sections, and that pullback commutes with the sheaf
  condition in the expected functorial way.

* **Trust**: Trust is modelled as a commutative quantale ``(T, ≤, ⊗, ⊤)``.
  The trust subsystem maintains a monotone trust map, a composition law, a
  propagation mechanism over evidence channels, and a downward-closed
  revocation semantics.  Soundness of trust annotations is a joint property of
  the trust map and the semantic model.

* **Evidence**: An evidence bundle ``B`` is a finite set of discharge records
  paired with the propositions they support.  The evidence subsystem must prove
  that every discharged item is *sound* (true in the model), that the bundle is
  *complete* (covers all obligations), that items are *independent* when
  claimed to be, and that all items remain *fresh* with respect to the current
  revocation log.

* **Federation**: A JuGeo federation is a diagram of packs connected by
  interface morphisms.  The federation subsystem must prove consistency of
  shared boundary judgments, compatibility of interface morphisms with judgment
  types, cross-pack descent, global coherence, and boundary agreement.

* **Invalidation**: The invalidation subsystem maintains a directed acyclic
  graph ``σ`` of dependency edges between judgments.  It must prove that
  cascade BFS/DFS terminates (because ``σ`` is a DAG), that support sets are
  correct, that stale-marking is conservative, that the cascade is complete
  (every dependent judgment is reached), and that dependency trace records are
  not forged.
"""

from __future__ import annotations

import time
import uuid
from typing import Any

from jugeo.encodings.theorem_schemas.models import (
    TheoremSchema,
    SubsystemSchema,
    SchemaInstance,
    ProofStyle,
    SubsystemKind,
    ProofAgent,
)

__all__ = [
    "DescentSchemaTemplate",
    "TrustSchemaTemplate",
    "EvidenceSchemaTemplate",
    "FederationSchemaTemplate",
    "InvalidationSchemaTemplate",
    "ALL_TEMPLATES",
    "build_all_templates",
    "make_theorem_schema",
    "describe_template",
    "list_all_schema_names",
]

# ---------------------------------------------------------------------------
# Internal factory helper
# ---------------------------------------------------------------------------


def make_theorem_schema(
    name: str,
    template_statement: str,
    variables: dict[str, str],
    subsystem: SubsystemKind,
    proof_style: ProofStyle = ProofStyle.AUTOMATED,
    description: str = "",
    prerequisites: list[str] | None = None,
    difficulty: int = 5,
    tags: list[str] | None = None,
) -> TheoremSchema:
    """Construct a :class:`TheoremSchema` with all standard fields populated.

    This factory is the canonical way to create schemas within this module.
    It ensures that every schema receives a fresh UUID, a creation timestamp,
    and sensible defaults for optional fields.  Difficulty and prerequisite
    information are stored in the schema's ``metadata`` dict so that they are
    available to downstream tooling without polluting the core API.

    Parameters
    ----------
    name:
        Short ``snake_case`` identifier for the theorem.
    template_statement:
        The theorem statement with ``{variable}`` placeholders.
    variables:
        Mapping from placeholder name (matching ``{name}`` in the template)
        to a brief English description of what the variable ranges over.
    subsystem:
        The owning :class:`SubsystemKind`.
    proof_style:
        How the theorem should be discharged.  Defaults to
        :attr:`~ProofStyle.AUTOMATED`.
    description:
        Longer prose description of the theorem's mathematical content.
    prerequisites:
        Names of schemas that must be discharged before this one.
    difficulty:
        Proof difficulty on 1–10 scale.
    tags:
        Free-form keyword tags for search and categorisation.

    Returns
    -------
    TheoremSchema
        A fully-populated schema ready for registration.

    Examples
    --------
    >>> s = make_theorem_schema(
    ...     name="descent_compat",
    ...     template_statement="For {f}, the datum {D} satisfies compatibility.",
    ...     variables={"f": "a site morphism", "D": "a descent datum"},
    ...     subsystem=SubsystemKind.DESCENT,
    ... )
    >>> s.name
    'descent_compat'
    """
    all_tags = list(tags or [])
    all_tags.append(f"difficulty:{difficulty}")
    for prereq in (prerequisites or []):
        all_tags.append(f"prereq:{prereq}")

    return TheoremSchema(
        name=name,
        template_statement=template_statement,
        variables=variables,
        proof_style=proof_style,
        subsystem=subsystem,
        schema_id=str(uuid.uuid4()),
        tags=all_tags,
        description=description if description else f"Theorem schema: {name}",
        metadata={
            "prerequisites": list(prerequisites or []),
            "difficulty": difficulty,
            "source_chapter": "theory2.tex §36",
        },
        created_at=time.time(),
    )


# ---------------------------------------------------------------------------
# Descent schema template
# ---------------------------------------------------------------------------


class DescentSchemaTemplate:
    """Template library for the Descent subsystem proof burden.

    The Descent subsystem is responsible for ensuring that the JuGeo semantic
    site behaves as a Grothendieck site: local data glues to global sections,
    pullback functors respect the sheaf condition, and every effective descent
    morphism admits a canonical inverse to the descent category.

    This class creates five :class:`TheoremSchema` objects as attributes and
    provides a uniform interface — :meth:`get_all_schemas`,
    :meth:`get_schema_by_name`, :meth:`as_subsystem_schema`,
    :meth:`required_names`, and :meth:`describe` — used by the registry.

    The five schemas are:

    ``descent_compatibility_schema``
        Compatibility of a descent datum with pullback along a morphism.
    ``pullback_consistency_schema``
        The pullback functor preserves the sheaf condition.
    ``sheaf_condition_schema``
        The equalizer diagram for the sheaf condition is exact.
    ``descent_data_coherence_schema``
        The coherence conditions on descent data in the fibered category.
    ``effective_descent_schema``
        Characterisation of effective descent morphisms.

    See theory2.tex §36.2.1 for the full statement of these requirements.
    """

    def __init__(self) -> None:
        """Instantiate all five descent theorem schemas as instance attributes.

        Each schema is constructed via :func:`make_theorem_schema` with
        complete mathematical content drawn from theory2.tex §36.2.1.
        """
        self.descent_compatibility_schema: TheoremSchema = make_theorem_schema(
            name="descent_compatibility",
            template_statement=(
                "For morphism {f} in the semantic site, the descent datum {D} "
                "satisfies compatibility: the pullback {f^*D} is canonically "
                "isomorphic to {D} restricted along {f}."
            ),
            variables={
                "f": "a morphism in the semantic site",
                "D": "a descent datum over the target of f",
                "f^*D": "the pullback of D along f",
            },
            subsystem=SubsystemKind.DESCENT,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Establishes that pulling back a descent datum along any morphism "
                "in the site recovers the original datum up to canonical isomorphism. "
                "This is the base coherence condition for the fibered category of "
                "descent data over the semantic site. It implies that descent data "
                "behave functorially with respect to the site morphisms."
            ),
            prerequisites=[],
            difficulty=4,
            tags=["descent", "pullback", "compatibility", "fibered-category"],
        )

        self.pullback_consistency_schema: TheoremSchema = make_theorem_schema(
            name="pullback_consistency",
            template_statement=(
                "The pullback functor {f^*} along {f} preserves the sheaf condition: "
                "if {S} satisfies descent along {U_cover}, then {f^*S} satisfies "
                "descent along {f^{-1}(U_cover)}."
            ),
            variables={
                "f^*": "the pullback functor induced by f",
                "f": "a morphism in the semantic site",
                "S": "a sheaf satisfying descent along U_cover",
                "U_cover": "a covering sieve on the target object",
                "f^{-1}(U_cover)": "the induced covering sieve on the source object",
            },
            subsystem=SubsystemKind.DESCENT,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "The pullback functor f^* sends sheaves to sheaves. More precisely, "
                "if a presheaf S satisfies the sheaf condition for a covering sieve "
                "U_cover of an object X, then its pullback f^*S satisfies the sheaf "
                "condition for the induced covering sieve f^{-1}(U_cover). "
                "This schema must be discharged for every morphism f and cover U_cover "
                "appearing in the execution trace. Proof proceeds by diagram chase "
                "in the category of sheaves on the induced site."
            ),
            prerequisites=["descent_compatibility"],
            difficulty=5,
            tags=["descent", "pullback", "sheaf", "functor", "cover"],
        )

        self.sheaf_condition_schema: TheoremSchema = make_theorem_schema(
            name="sheaf_condition",
            template_statement=(
                "The presheaf {P} satisfies the sheaf condition: for every cover "
                "{U} of {X}, the equalizer diagram "
                "Gamma({X},{P}) to prod_i Gamma({U_i},{P}) implies prod_ij Gamma({U_ij},{P}) "
                "is exact."
            ),
            variables={
                "P": "a presheaf on the semantic site",
                "U": "a covering family of X",
                "X": "the base object being covered",
                "U_i": "the individual covering objects U_i in U",
                "U_ij": "the pairwise intersections U_i cap U_j",
            },
            subsystem=SubsystemKind.DESCENT,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "The classical sheaf condition states that the global sections of P "
                "over X are uniquely determined by compatible local sections over a "
                "covering family {U_i to X}. The equalizer diagram encodes this "
                "exactly: injectivity of the left map says local sections determine "
                "global sections, and exactness at the product says compatible local "
                "sections glue. Discharging this schema for every cover used in the "
                "execution guarantees that section-assembly is well-defined."
            ),
            prerequisites=[],
            difficulty=3,
            tags=["sheaf", "equalizer", "gluing", "cover", "sections"],
        )

        self.descent_data_coherence_schema: TheoremSchema = make_theorem_schema(
            name="descent_data_coherence",
            template_statement=(
                "The descent datum {D} over cover {U_cover} of {X} satisfies the "
                "full coherence conditions: the transition isomorphisms "
                "{phi_ij : D_i|_{U_ij} to D_j|_{U_ij}} satisfy the cocycle condition "
                "{phi_jk circ phi_ij = phi_ik} on all triple overlaps {U_ijk}."
            ),
            variables={
                "D": "a descent datum assembled from local pieces",
                "U_cover": "the covering sieve on X",
                "X": "the base object",
                "phi_ij : D_i|_{U_ij} to D_j|_{U_ij}": "the transition isomorphism on pairwise overlaps",
                "U_ij": "the pairwise overlap U_i cap U_j",
                "phi_jk circ phi_ij = phi_ik": "the cocycle condition on triple overlaps",
                "U_ijk": "the triple overlap U_i cap U_j cap U_k",
            },
            subsystem=SubsystemKind.DESCENT,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Descent data must satisfy a cocycle condition on triple overlaps "
                "to define a globally coherent object. The coherence conditions "
                "ensure that the transition isomorphisms phi_ij form a 1-cocycle "
                "in the Cech cohomology of the cover, which is the correct "
                "categorical condition for the datum to be effective. Without this "
                "coherence, multiple distinct local objects could claim to represent "
                "the same global descent datum, leading to inconsistency in the "
                "semantic model."
            ),
            prerequisites=["descent_compatibility"],
            difficulty=6,
            tags=["descent", "coherence", "cocycle", "cech", "transition-isomorphism"],
        )

        self.effective_descent_schema: TheoremSchema = make_theorem_schema(
            name="effective_descent",
            template_statement=(
                "The morphism {f : Y to X} is an effective descent morphism: the "
                "comparison functor {K_f : Sh(X) to Desc(f)} from sheaves on {X} "
                "to {f}-descent data is an equivalence of categories."
            ),
            variables={
                "f : Y to X": "a morphism in the semantic site",
                "K_f : Sh(X) to Desc(f)": "the comparison functor from sheaves on X to f-descent data",
                "Sh(X)": "the category of sheaves on X",
                "Desc(f)": "the category of f-descent data",
            },
            subsystem=SubsystemKind.DESCENT,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "An effective descent morphism f : Y to X is one for which the "
                "comparison functor K_f : Sh(X) to Desc(f) is an equivalence. This "
                "is the content of Grothendieck's descent theory: data on X is "
                "equivalent to data on Y together with coherent gluing. In JuGeo, "
                "this theorem must be discharged for every morphism that is used "
                "to pull back or push forward semantic content across the pack "
                "boundary. Proof proceeds by verifying that K_f is full, faithful, "
                "and essentially surjective, typically via the Barr-Beck monadicity "
                "theorem applied to the adjunction f^* dashv f_*."
            ),
            prerequisites=["descent_compatibility", "descent_data_coherence"],
            difficulty=8,
            tags=["descent", "effective-descent", "equivalence", "comparison-functor"],
        )

    # ------------------------------------------------------------------
    # Interface methods
    # ------------------------------------------------------------------

    def get_all_schemas(self) -> list[TheoremSchema]:
        """Return all five descent theorem schemas in canonical order.

        The canonical order is: compatibility, sheaf_condition,
        pullback_consistency, coherence, effective_descent.  This ordering
        respects prerequisite dependencies.

        Returns
        -------
        list[TheoremSchema]
            All five schemas in dependency order.
        """
        return [
            self.descent_compatibility_schema,
            self.sheaf_condition_schema,
            self.pullback_consistency_schema,
            self.descent_data_coherence_schema,
            self.effective_descent_schema,
        ]

    def get_schema_by_name(self, name: str) -> TheoremSchema | None:
        """Retrieve a schema by its ``name`` field.

        Performs a linear scan over the five schemas and returns the first
        match, or ``None`` if no schema has the given name.

        Parameters
        ----------
        name:
            The schema name to search for.

        Returns
        -------
        TheoremSchema or None
        """
        for schema in self.get_all_schemas():
            if schema.name == name:
                return schema
        return None

    def as_subsystem_schema(self) -> SubsystemSchema:
        """Wrap all descent schemas in a :class:`SubsystemSchema` bundle.

        Constructs a fresh :class:`SubsystemSchema` with all five schemas
        registered via ``add_schema``.

        Returns
        -------
        SubsystemSchema
            The bundle ready for registration in the theorem-schema registry.
        """
        bundle = SubsystemSchema(
            subsystem_name=SubsystemKind.DESCENT,
            subsystem_id=str(uuid.uuid4()),
            required_theorems=self.required_names(),
        )
        for schema in self.get_all_schemas():
            bundle.add_schema(schema)
        return bundle

    def required_names(self) -> list[str]:
        """Return the list of theorem names required by the Descent subsystem.

        Returns
        -------
        list[str]
            Theorem names in dependency order.
        """
        return [s.name for s in self.get_all_schemas()]

    def describe(self) -> str:
        """Return a human-readable description of this template library.

        Summarises the purpose of the Descent subsystem and lists the five
        theorems it must discharge, with difficulty ratings.

        Returns
        -------
        str
            Multi-line description string.
        """
        lines: list[str] = [
            "DescentSchemaTemplate — Descent subsystem theorem library",
            "  theory2.tex §36.2.1",
            "  Purpose: Encode the sheaf/descent proof burden for the semantic site.",
            "  Theorems:",
        ]
        for s in self.get_all_schemas():
            diff = s.metadata.get("difficulty", "?")
            lines.append(
                f"    [{diff}/10] {s.name}: {s.description[:80]}..."
            )
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Trust schema template
# ---------------------------------------------------------------------------


class TrustSchemaTemplate:
    """Template library for the Trust subsystem proof burden.

    The Trust subsystem maintains the trust algebra ``(T, ≤, ⊗, ⊤)`` and
    must prove that the trust map is monotone, that trust composition is
    well-defined and associative, that trust propagates correctly over
    evidence channels, that revocation is downward-closed, and that trust
    annotations are sound with respect to the semantic model.

    The five schemas are:

    ``trust_monotonicity_schema``
        Trust is monotone in the trust order.
    ``trust_composition_schema``
        Trust composes transitively via the tensor ⊗.
    ``trust_propagation_schema``
        Trust annotations transport correctly over evidence channels.
    ``trust_revocation_schema``
        Revocation is downward-closed in the dependency graph.
    ``trust_annotation_soundness_schema``
        Trust annotations are sound with respect to the semantic model.

    See theory2.tex §36.2.2 for the mathematical context.
    """

    def __init__(self) -> None:
        """Instantiate all five trust theorem schemas as instance attributes."""
        self.trust_monotonicity_schema: TheoremSchema = make_theorem_schema(
            name="trust_monotonicity",
            template_statement=(
                "If {A} is trusted at level {t1} and {t1} <= {t2} in the trust "
                "algebra, then {A} is trusted at level {t2}: trust is monotone "
                "in the trust order."
            ),
            variables={
                "A": "an agent or component in the trust graph",
                "t1": "the lower trust level at which A is known to be trusted",
                "t2": "any trust level above t1 in the trust partial order",
            },
            subsystem=SubsystemKind.TRUST,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Monotonicity of the trust map means that once an agent A is "
                "trusted at level t1, it is automatically trusted at any higher "
                "level t2 >= t1 in the trust partial order. This ensures that "
                "raising the trust threshold never produces spurious distrust. "
                "In the quantale model, this corresponds to the up-set property: "
                "for all a in T, the set {t | A trusted at t} is an up-set. "
                "Proof: by definition of the trust map combined with the "
                "order-preserving property of the trust algebra operations."
            ),
            prerequisites=[],
            difficulty=2,
            tags=["trust", "monotone", "order", "quantale"],
        )

        self.trust_composition_schema: TheoremSchema = make_theorem_schema(
            name="trust_composition",
            template_statement=(
                "Trust composes: if {A} trusts {B} at level {t1} and {B} certifies "
                "{C} at level {t2}, then {A} transitively trusts {C} at level "
                "{t1 tensor t2}."
            ),
            variables={
                "A": "the trusting agent",
                "B": "the intermediate certifying agent",
                "C": "the target agent whose trust is composed",
                "t1": "the direct trust level of A in B",
                "t2": "the certification level of B for C",
                "t1 tensor t2": "the transitive trust level computed via the quantale tensor",
            },
            subsystem=SubsystemKind.TRUST,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Trust composition defines a transitive closure of the trust "
                "relation via the tensor product tensor of the trust quantale. If "
                "agent A trusts B at level t1 and B in turn certifies C at level "
                "t2, then A's transitive trust in C is at level t1 tensor t2. The "
                "tensor is commutative and associative, with top element top as "
                "unit. This schema must be discharged for every trust chain "
                "appearing in the execution. Proof: by the quantale multiplication "
                "axioms and the definition of the certification relation."
            ),
            prerequisites=["trust_monotonicity"],
            difficulty=4,
            tags=["trust", "composition", "tensor", "quantale", "transitive"],
        )

        self.trust_propagation_schema: TheoremSchema = make_theorem_schema(
            name="trust_propagation",
            template_statement=(
                "Trust propagates along evidence channels: if evidence item {e} "
                "has trust annotation {T} and is transmitted over channel {ch}, "
                "the received annotation is {ch.transport(T)}."
            ),
            variables={
                "e": "an evidence item being transmitted",
                "T": "the trust annotation attached to e before transmission",
                "ch": "the evidence channel over which e is transmitted",
                "ch.transport(T)": "the received trust annotation after channel attenuation",
            },
            subsystem=SubsystemKind.TRUST,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Evidence channels may attenuate or transform trust annotations "
                "during transmission. The channel transport map ch.transport must "
                "be order-preserving (it cannot raise trust) and must compose "
                "correctly with the trust tensor: for two channels ch1 and ch2 "
                "composed sequentially, (ch1 circ ch2).transport(T) = "
                "ch1.transport(ch2.transport(T)). This schema verifies that the "
                "received trust annotation accurately reflects the channel's "
                "attenuation policy, preventing trust inflation attacks where a "
                "low-quality channel claims to produce high-quality annotations."
            ),
            prerequisites=["trust_monotonicity"],
            difficulty=5,
            tags=["trust", "propagation", "channel", "transport", "attenuation"],
        )

        self.trust_revocation_schema: TheoremSchema = make_theorem_schema(
            name="trust_revocation",
            template_statement=(
                "Trust revocation is downward-closed: if trust at {coord} is "
                "revoked, all judgments depending on {coord} in the invalidation "
                "graph must be re-evaluated."
            ),
            variables={
                "coord": "the coordinate at which trust is being revoked",
            },
            subsystem=SubsystemKind.TRUST,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "When trust at a coordinate coord is revoked (e.g. because a "
                "certificate expires or is compromised), every judgment that "
                "depends on coord in the dependency graph inherits the revocation "
                "and must be re-evaluated. This is the downward-closure property "
                "of revocation: the set of affected judgments is the downward "
                "closure of {coord} in the dependency DAG. Without this property, "
                "stale or compromised trust could silently persist in derived "
                "judgments. Proof: by induction on the dependency depth combined "
                "with the cascade termination theorem of the Invalidation subsystem."
            ),
            prerequisites=["trust_composition"],
            difficulty=6,
            tags=["trust", "revocation", "downward-closed", "cascade", "invalidation"],
        )

        self.trust_annotation_soundness_schema: TheoremSchema = make_theorem_schema(
            name="trust_annotation_soundness",
            template_statement=(
                "The trust annotation {tau} attached to judgment {J} is sound: "
                "the semantic value of {J} in model {M} satisfies the trust "
                "level {tau} — formally, M satisfies trust(J) >= {tau}."
            ),
            variables={
                "tau": "a trust annotation element in the trust quantale T",
                "J": "the judgment carrying annotation tau",
                "M": "the semantic model against which soundness is checked",
            },
            subsystem=SubsystemKind.TRUST,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Soundness of trust annotations requires that every annotation tau "
                "placed on a judgment J faithfully reflects the actual trust level "
                "that the semantic model M assigns to J. This is a joint property "
                "of the annotation assignment algorithm and the semantic model "
                "interpretation. If this schema fails, the trust subsystem could "
                "label a judgment as trusted when the model considers it "
                "untrustworthy, or vice versa. Proof: by semantic model inspection "
                "combined with the annotation assignment rules in section 36.2.2."
            ),
            prerequisites=["trust_monotonicity", "trust_composition"],
            difficulty=7,
            tags=["trust", "soundness", "annotation", "semantic-model"],
        )

    def get_all_schemas(self) -> list[TheoremSchema]:
        """Return all five trust theorem schemas in dependency order.

        Returns
        -------
        list[TheoremSchema]
            Schemas ordered: monotonicity, composition, propagation,
            revocation, annotation soundness.
        """
        return [
            self.trust_monotonicity_schema,
            self.trust_composition_schema,
            self.trust_propagation_schema,
            self.trust_revocation_schema,
            self.trust_annotation_soundness_schema,
        ]

    def get_schema_by_name(self, name: str) -> TheoremSchema | None:
        """Retrieve a trust schema by name.

        Parameters
        ----------
        name:
            Schema name to search for.

        Returns
        -------
        TheoremSchema or None
        """
        for schema in self.get_all_schemas():
            if schema.name == name:
                return schema
        return None

    def as_subsystem_schema(self) -> SubsystemSchema:
        """Wrap all trust schemas in a :class:`SubsystemSchema` bundle.

        Returns
        -------
        SubsystemSchema
        """
        bundle = SubsystemSchema(
            subsystem_name=SubsystemKind.TRUST,
            subsystem_id=str(uuid.uuid4()),
            required_theorems=self.required_names(),
        )
        for schema in self.get_all_schemas():
            bundle.add_schema(schema)
        return bundle

    def required_names(self) -> list[str]:
        """Return the list of theorem names required by the Trust subsystem.

        Returns
        -------
        list[str]
        """
        return [s.name for s in self.get_all_schemas()]

    def describe(self) -> str:
        """Return a human-readable description of this template library.

        Returns
        -------
        str
        """
        lines: list[str] = [
            "TrustSchemaTemplate — Trust subsystem theorem library",
            "  theory2.tex §36.2.2",
            "  Purpose: Encode the trust algebra proof burden.",
            "  Theorems:",
        ]
        for s in self.get_all_schemas():
            diff = s.metadata.get("difficulty", "?")
            lines.append(f"    [{diff}/10] {s.name}: {s.description[:80]}...")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Evidence schema template
# ---------------------------------------------------------------------------


class EvidenceSchemaTemplate:
    """Template library for the Evidence subsystem proof burden.

    The Evidence subsystem assembles, validates, and tracks evidence bundles.
    Each bundle ``B`` is a finite set of discharge records coupled to the
    propositions they support.  The subsystem must prove soundness,
    completeness, independence (where claimed), freshness, and manifest
    coverage.

    The five schemas are:

    ``evidence_soundness_schema``
        Every discharged item in a bundle is sound.
    ``evidence_completeness_schema``
        The bundle covers all proof obligations of the target proposition.
    ``evidence_independence_schema``
        Claimed-independent items do not mutually depend on each other.
    ``evidence_freshness_schema``
        Items are not stale or revoked.
    ``manifest_coverage_schema``
        The evidence manifest covers every outstanding obligation.

    See theory2.tex §36.2.3 for the mathematical context.
    """

    def __init__(self) -> None:
        """Instantiate all five evidence theorem schemas as instance attributes."""
        self.evidence_soundness_schema: TheoremSchema = make_theorem_schema(
            name="evidence_soundness",
            template_statement=(
                "Every discharged evidence item {e} in bundle {B} is sound: "
                "the proposition {phi} supported by {e} is true in the semantic model."
            ),
            variables={
                "e": "an evidence item that has been discharged",
                "B": "the evidence bundle containing e",
                "phi": "the proposition supported by e",
            },
            subsystem=SubsystemKind.EVIDENCE,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Evidence soundness is the core correctness requirement for the "
                "evidence subsystem: every item e in bundle B must support a "
                "proposition phi that is genuinely true in the semantic model. An "
                "unsound item is one that appears to support a proposition but the "
                "underlying semantic fact is false. Soundness must be verified "
                "against the current state of the semantic model at the time of "
                "discharge, because model state may change over time due to "
                "updates or revocations. Proof: by semantic oracle query against "
                "the model at the coordinate of discharge."
            ),
            prerequisites=[],
            difficulty=5,
            tags=["evidence", "soundness", "bundle", "semantic-model"],
        )

        self.evidence_completeness_schema: TheoremSchema = make_theorem_schema(
            name="evidence_completeness",
            template_statement=(
                "The evidence bundle {B} is complete for proposition {phi}: every "
                "proof obligation of {phi} is covered by some item {e} in {B}."
            ),
            variables={
                "B": "the evidence bundle being checked for completeness",
                "phi": "the proposition whose proof obligations must be covered",
                "e": "an individual evidence item in B covering one obligation",
            },
            subsystem=SubsystemKind.EVIDENCE,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Evidence completeness requires that bundle B provides at least "
                "one discharge record for each proof obligation generated by "
                "proposition phi. Incompleteness means that some obligation remains "
                "open, making the judgment that phi holds unsupported. Completeness "
                "is complementary to soundness: together they say that the bundle "
                "is exactly what is needed — no more spurious items and no missing "
                "obligations. The set of obligations is determined by the proof "
                "rules in the JuGeo judgment calculus."
            ),
            prerequisites=["evidence_soundness"],
            difficulty=4,
            tags=["evidence", "completeness", "bundle", "obligations"],
        )

        self.evidence_independence_schema: TheoremSchema = make_theorem_schema(
            name="evidence_independence",
            template_statement=(
                "The evidence items {e1} and {e2} in bundle {B} are independent: "
                "the validity of {e1} does not logically depend on {e2}."
            ),
            variables={
                "e1": "the first evidence item claimed to be independent",
                "e2": "the second evidence item claimed to be independent",
                "B": "the bundle containing both e1 and e2",
            },
            subsystem=SubsystemKind.EVIDENCE,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "When evidence items are declared to be independent in a bundle, "
                "this independence must be provable: neither e1's validity depends "
                "on e2 nor vice versa in the dependency graph of the bundle. "
                "Independence is important for compositionality: if e1 and e2 are "
                "independent, then revoking e2 does not automatically invalidate "
                "e1 and vice versa. The dependency graph of a bundle is the "
                "restriction of the global invalidation graph to the items of "
                "that bundle. Independence of e1 and e2 means they lie in "
                "different connected components of this restriction."
            ),
            prerequisites=["evidence_soundness"],
            difficulty=5,
            tags=["evidence", "independence", "bundle", "dependency"],
        )

        self.evidence_freshness_schema: TheoremSchema = make_theorem_schema(
            name="evidence_freshness",
            template_statement=(
                "Evidence item {e} is fresh: its timestamp {ts} satisfies "
                "{ts} >= {freshness_threshold} and no revocation event has been "
                "recorded for {e}."
            ),
            variables={
                "e": "the evidence item whose freshness is being verified",
                "ts": "the creation timestamp of e",
                "freshness_threshold": "the system-wide minimum acceptable timestamp",
            },
            subsystem=SubsystemKind.EVIDENCE,
            proof_style=ProofStyle.INDUCTIVE,
            description=(
                "Evidence freshness requires that item e was produced after the "
                "current freshness threshold (a system-wide configurable cut-off "
                "time) and that no revocation event has been entered into the "
                "revocation log for e. Stale evidence is dangerous: the world may "
                "have changed since e was produced, making the proposition it "
                "supports no longer true. Revoked evidence is evidence that has "
                "been explicitly withdrawn by its producer. Both conditions must "
                "be checked against the revocation log at query time."
            ),
            prerequisites=[],
            difficulty=3,
            tags=["evidence", "freshness", "timestamp", "revocation", "staleness"],
        )

        self.manifest_coverage_schema: TheoremSchema = make_theorem_schema(
            name="manifest_coverage",
            template_statement=(
                "The evidence manifest {M} covers all outstanding obligations for "
                "judgment {J}: for every obligation {o} in obligations({J}), "
                "there exists an entry {m} in {M} such that {m} discharges {o}."
            ),
            variables={
                "M": "the evidence manifest being checked for surjectivity",
                "J": "the judgment whose obligations must be mapped in M",
                "o": "an individual proof obligation of J",
                "m": "a manifest entry that discharges obligation o",
            },
            subsystem=SubsystemKind.EVIDENCE,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "The evidence manifest is a structured record that maps each "
                "proof obligation of a judgment to the evidence item that "
                "discharges it. Manifest coverage requires that this mapping is "
                "surjective: every obligation has an entry. This is a stronger "
                "form of the completeness condition that additionally requires "
                "the mapping to be explicitly recorded, enabling audit trails "
                "and incremental re-discharge after revocation. Proof: by "
                "enumeration of obligations(J) and checking membership in M."
            ),
            prerequisites=["evidence_completeness", "evidence_freshness"],
            difficulty=4,
            tags=["evidence", "manifest", "coverage", "obligations", "audit"],
        )

    def get_all_schemas(self) -> list[TheoremSchema]:
        """Return all five evidence theorem schemas in dependency order.

        Returns
        -------
        list[TheoremSchema]
        """
        return [
            self.evidence_soundness_schema,
            self.evidence_freshness_schema,
            self.evidence_completeness_schema,
            self.evidence_independence_schema,
            self.manifest_coverage_schema,
        ]

    def get_schema_by_name(self, name: str) -> TheoremSchema | None:
        """Retrieve an evidence schema by name.

        Parameters
        ----------
        name:
            Schema name to search for.

        Returns
        -------
        TheoremSchema or None
        """
        for schema in self.get_all_schemas():
            if schema.name == name:
                return schema
        return None

    def as_subsystem_schema(self) -> SubsystemSchema:
        """Wrap all evidence schemas in a :class:`SubsystemSchema` bundle.

        Returns
        -------
        SubsystemSchema
        """
        bundle = SubsystemSchema(
            subsystem_name=SubsystemKind.EVIDENCE,
            subsystem_id=str(uuid.uuid4()),
            required_theorems=self.required_names(),
        )
        for schema in self.get_all_schemas():
            bundle.add_schema(schema)
        return bundle

    def required_names(self) -> list[str]:
        """Return the list of theorem names required by the Evidence subsystem.

        Returns
        -------
        list[str]
        """
        return [s.name for s in self.get_all_schemas()]

    def describe(self) -> str:
        """Return a human-readable description of this template library.

        Returns
        -------
        str
        """
        lines: list[str] = [
            "EvidenceSchemaTemplate — Evidence subsystem theorem library",
            "  theory2.tex §36.2.3",
            "  Purpose: Encode the evidence bundle proof burden.",
            "  Theorems:",
        ]
        for s in self.get_all_schemas():
            diff = s.metadata.get("difficulty", "?")
            lines.append(f"    [{diff}/10] {s.name}: {s.description[:80]}...")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Federation schema template
# ---------------------------------------------------------------------------


class FederationSchemaTemplate:
    """Template library for the Federation subsystem proof burden.

    The Federation subsystem governs multi-pack consistency.  A federation
    ``F`` is a diagram of pack objects connected by interface morphisms; the
    subsystem must prove global consistency, pairwise pack compatibility,
    cross-pack descent, federation-wide coherence, and boundary agreement.

    The five schemas are:

    ``federation_consistency_schema``
        Shared boundary judgments agree after restriction.
    ``pack_compatibility_schema``
        Interface morphisms preserve judgment types and trust levels.
    ``cross_pack_descent_schema``
        Judgments descend across pack boundaries via interface morphisms.
    ``federation_coherence_schema``
        The federation diagram is globally coherent.
    ``boundary_agreement_schema``
        Boundary sections agree on overlapping domains.

    See theory2.tex §36.2.4 for the mathematical context.
    """

    def __init__(self) -> None:
        """Instantiate all five federation theorem schemas as instance attributes."""
        self.federation_consistency_schema: TheoremSchema = make_theorem_schema(
            name="federation_consistency",
            template_statement=(
                "The federation {F} is consistent: for any two packs {P1} and {P2} "
                "in {F}, their shared boundary judgments agree after restriction."
            ),
            variables={
                "F": "the full federation diagram of packs and interface morphisms",
                "P1": "the first pack in the consistency check",
                "P2": "the second pack sharing a boundary with P1",
            },
            subsystem=SubsystemKind.FEDERATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Federation consistency is the master consistency condition for a "
                "multi-pack deployment. Two packs P1 and P2 share a boundary if "
                "there exists a common interface morphism from a third object to "
                "both. Consistency requires that restricting a boundary judgment "
                "from P1 to the shared interface produces the same result as "
                "restricting the corresponding judgment from P2. This is the "
                "Mayer-Vietoris type condition for the federation. Proof: by "
                "checking all pairs of packs in F and verifying restriction "
                "agreement, typically via the diagram-chase method."
            ),
            prerequisites=[],
            difficulty=6,
            tags=["federation", "consistency", "boundary", "multi-pack"],
        )

        self.pack_compatibility_schema: TheoremSchema = make_theorem_schema(
            name="pack_compatibility",
            template_statement=(
                "Packs {P1} and {P2} are compatible: the interface morphism "
                "{i : P1 to P2} preserves all judgment types and trust levels."
            ),
            variables={
                "P1": "the source pack of the interface morphism",
                "P2": "the target pack of the interface morphism",
                "i : P1 to P2": "the interface morphism being checked for compatibility",
            },
            subsystem=SubsystemKind.FEDERATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Pack compatibility requires that the interface morphism "
                "i : P1 to P2 is a morphism of judgment structures: it maps "
                "judgments in P1 to judgments in P2 of the same type and "
                "preserves trust levels (i.e., it is trust-order-preserving). "
                "Without compatibility, an interface could silently demote a "
                "high-trust judgment to a low-trust judgment or change its "
                "semantic type, violating the invariants that the Trust and "
                "Judgment subsystems depend on. Proof: by checking the interface "
                "morphism type signature and the trust-order preservation "
                "condition against the declaration in the pack manifest."
            ),
            prerequisites=["federation_consistency"],
            difficulty=5,
            tags=["federation", "compatibility", "interface-morphism", "trust"],
        )

        self.cross_pack_descent_schema: TheoremSchema = make_theorem_schema(
            name="cross_pack_descent",
            template_statement=(
                "Cross-pack descent holds: a judgment {J} valid in {P1} descends "
                "to {P2} via {f} if and only if {f^*J} satisfies the local "
                "conditions of {P2}."
            ),
            variables={
                "J": "the judgment being transported across the pack boundary",
                "P1": "the source pack where J is valid",
                "P2": "the target pack to which J is being descended",
                "f": "the interface morphism along which descent proceeds",
                "f^*J": "the pulled-back judgment after applying f",
            },
            subsystem=SubsystemKind.FEDERATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Cross-pack descent generalises the Descent subsystem's effective "
                "descent theorem to the multi-pack setting. A judgment J that holds "
                "in pack P1 can be transported to pack P2 via an interface morphism "
                "f if and only if the pulled-back judgment f^*J satisfies P2's local "
                "well-formedness and trust conditions. The biconditional form "
                "ensures that no judgment is lost in transport (necessity) and that "
                "no spurious judgment is gained (sufficiency). Proof: by composing "
                "the effective descent theorem of the Descent subsystem with the "
                "pack compatibility condition."
            ),
            prerequisites=["federation_consistency", "pack_compatibility"],
            difficulty=7,
            tags=["federation", "descent", "cross-pack", "transport"],
        )

        self.federation_coherence_schema: TheoremSchema = make_theorem_schema(
            name="federation_coherence",
            template_statement=(
                "The federation diagram {F} is coherent: for any composable pair "
                "of interface morphisms {f : P1 to P2} and {g : P2 to P3}, the "
                "composite {g circ f : P1 to P3} equals the direct interface morphism "
                "where it exists."
            ),
            variables={
                "F": "the federation diagram of packs and morphisms",
                "f : P1 to P2": "the first interface morphism in the composable pair",
                "g : P2 to P3": "the second interface morphism in the composable pair",
                "g circ f : P1 to P3": "the composite morphism",
            },
            subsystem=SubsystemKind.FEDERATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Federation coherence requires that the category of packs and "
                "interface morphisms in F is, in fact, a category: composition of "
                "morphisms is well-defined and associative, and every pack has an "
                "identity morphism. When a direct interface morphism h : P1 to P3 "
                "exists alongside the composable pair (f, g), coherence additionally "
                "requires that h = g circ f (the federation diagram commutes). This "
                "ensures that the multi-pack structure is globally consistent and "
                "that there are no shortcut paths that bypass the established "
                "compatibility conditions. Proof: by checking the commutativity "
                "conditions on all triangles and squares in the federation diagram."
            ),
            prerequisites=["pack_compatibility", "cross_pack_descent"],
            difficulty=7,
            tags=["federation", "coherence", "composition", "category"],
        )

        self.boundary_agreement_schema: TheoremSchema = make_theorem_schema(
            name="boundary_agreement",
            template_statement=(
                "Boundary sections agree: for packs {P1} and {P2} sharing boundary "
                "{dP12}, the sections of judgment {J} restricted to {dP12} "
                "from {P1} and from {P2} are equal."
            ),
            variables={
                "P1": "the first pack in the boundary agreement check",
                "P2": "the second pack sharing the boundary with P1",
                "dP12": "the shared boundary object of P1 and P2",
                "J": "the judgment whose restrictions are being compared",
            },
            subsystem=SubsystemKind.FEDERATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Boundary agreement is the local form of federation consistency, "
                "applied to a single judgment J at the shared boundary dP12 of "
                "two adjacent packs. It requires that restricting J from P1 to "
                "the boundary gives the same result as restricting J from P2 to "
                "the boundary. This is an instance of the sheaf gluing condition "
                "in the federation context: the two local sections agree on "
                "overlaps. Boundary agreement is checked for every pair of "
                "adjacent packs and every judgment that spans the boundary. Proof "
                "by model query at the boundary coordinate."
            ),
            prerequisites=["federation_consistency", "federation_coherence"],
            difficulty=5,
            tags=["federation", "boundary", "agreement", "sheaf", "gluing"],
        )

    def get_all_schemas(self) -> list[TheoremSchema]:
        """Return all five federation theorem schemas in dependency order.

        Returns
        -------
        list[TheoremSchema]
        """
        return [
            self.federation_consistency_schema,
            self.pack_compatibility_schema,
            self.cross_pack_descent_schema,
            self.federation_coherence_schema,
            self.boundary_agreement_schema,
        ]

    def get_schema_by_name(self, name: str) -> TheoremSchema | None:
        """Retrieve a federation schema by name.

        Parameters
        ----------
        name:
            Schema name to search for.

        Returns
        -------
        TheoremSchema or None
        """
        for schema in self.get_all_schemas():
            if schema.name == name:
                return schema
        return None

    def as_subsystem_schema(self) -> SubsystemSchema:
        """Wrap all federation schemas in a :class:`SubsystemSchema` bundle.

        Returns
        -------
        SubsystemSchema
        """
        bundle = SubsystemSchema(
            subsystem_name=SubsystemKind.FEDERATION,
            subsystem_id=str(uuid.uuid4()),
            required_theorems=self.required_names(),
        )
        for schema in self.get_all_schemas():
            bundle.add_schema(schema)
        return bundle

    def required_names(self) -> list[str]:
        """Return the list of theorem names required by the Federation subsystem.

        Returns
        -------
        list[str]
        """
        return [s.name for s in self.get_all_schemas()]

    def describe(self) -> str:
        """Return a human-readable description of this template library.

        Returns
        -------
        str
        """
        lines: list[str] = [
            "FederationSchemaTemplate — Federation subsystem theorem library",
            "  theory2.tex §36.2.4",
            "  Purpose: Encode the multi-pack consistency proof burden.",
            "  Theorems:",
        ]
        for s in self.get_all_schemas():
            diff = s.metadata.get("difficulty", "?")
            lines.append(f"    [{diff}/10] {s.name}: {s.description[:80]}...")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Invalidation schema template
# ---------------------------------------------------------------------------


class InvalidationSchemaTemplate:
    """Template library for the Invalidation subsystem proof burden.

    The Invalidation subsystem maintains the invalidation DAG ``sigma`` and
    orchestrates cascading updates when trust or evidence is revoked.  It
    must prove cascade termination, support-set correctness, stale-marking
    conservativity, cascade completeness, and dependency trace integrity.

    The five schemas are:

    ``cascade_termination_schema``
        BFS/DFS over the DAG terminates.
    ``support_correctness_schema``
        The support set of a judgment correctly characterises its validity.
    ``stale_conservativity_schema``
        Stale marking is conservative (no false invalidations).
    ``invalidation_completeness_schema``
        Every dependent judgment is eventually marked stale.
    ``dependency_trace_integrity_schema``
        Dependency trace records are authentic and unforged.

    See theory2.tex §36.2.5 for the mathematical context.
    """

    def __init__(self) -> None:
        """Instantiate all five invalidation theorem schemas as instance attributes."""
        self.cascade_termination_schema: TheoremSchema = make_theorem_schema(
            name="cascade_termination",
            template_statement=(
                "The invalidation cascade {C} terminates: the invalidation graph "
                "{sigma} is a DAG, so BFS/DFS from any node visits each node at most once."
            ),
            variables={
                "C": "the invalidation cascade being traced",
                "sigma": "the invalidation dependency graph (must be a DAG)",
            },
            subsystem=SubsystemKind.INVALIDATION,
            proof_style=ProofStyle.INDUCTIVE,
            description=(
                "Cascade termination is the liveness property of the invalidation "
                "subsystem: it guarantees that the cascade algorithm always halts "
                "in finite time. The proof relies on the fact that the dependency "
                "graph sigma is a DAG (no cycles), which is enforced by the judgment "
                "formation rules in the Judgment subsystem. Since sigma is a DAG, any "
                "BFS or DFS traversal visits each node at most once, and since the "
                "graph is finite (bounded by the number of live judgments), the "
                "traversal terminates. Proof: by well-founded induction on the "
                "topological order of sigma."
            ),
            prerequisites=[],
            difficulty=4,
            tags=["invalidation", "termination", "DAG", "BFS", "DFS", "cascade"],
        )

        self.support_correctness_schema: TheoremSchema = make_theorem_schema(
            name="support_correctness",
            template_statement=(
                "The support set {S} of judgment {J} is correct: {J} is valid if "
                "and only if all coordinates in {S} carry valid evidence."
            ),
            variables={
                "S": "the support set of judgment J, listing its dependency coordinates",
                "J": "the judgment whose support set is being verified",
            },
            subsystem=SubsystemKind.INVALIDATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "The support set S(J) of a judgment J is the set of coordinates "
                "whose evidence was used in discharging J. Support correctness "
                "says that J is valid (currently holds in the model) if and only "
                "if every coordinate in S(J) still carries valid, non-revoked "
                "evidence. The 'if' direction (sufficiency) means that having "
                "valid evidence at all support coordinates is enough for J to be "
                "valid; the 'only if' direction (necessity) means that any "
                "invalidation of a support coordinate must invalidate J. This "
                "biconditional is essential for the correctness of incremental "
                "re-evaluation after revocation."
            ),
            prerequisites=["cascade_termination"],
            difficulty=6,
            tags=["invalidation", "support-set", "correctness", "biconditional"],
        )

        self.stale_conservativity_schema: TheoremSchema = make_theorem_schema(
            name="stale_conservativity",
            template_statement=(
                "Stale-manifest conservativity holds: marking judgment {J} as "
                "stale is a conservative operation — it does not introduce false "
                "invalidations."
            ),
            variables={
                "J": "the judgment being marked stale",
            },
            subsystem=SubsystemKind.INVALIDATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Conservativity of stale marking means that the invalidation "
                "subsystem may mark a judgment J as stale even if J is actually "
                "still valid (an overapproximation), but it must never fail to "
                "mark a judgment that is genuinely invalid (no underapproximation). "
                "Formally, the set of stale judgments is an overapproximation of "
                "the set of actually-invalid judgments. This is the safety "
                "property of the invalidation subsystem: it may cause unnecessary "
                "re-evaluation work, but it will never silently retain a stale "
                "judgment as valid. Proof: by showing that the stale-marking "
                "rule is a monotone function on the powerset of judgments."
            ),
            prerequisites=["support_correctness"],
            difficulty=5,
            tags=["invalidation", "conservativity", "stale", "overapproximation"],
        )

        self.invalidation_completeness_schema: TheoremSchema = make_theorem_schema(
            name="invalidation_completeness",
            template_statement=(
                "The invalidation cascade for root {r} is complete: every judgment "
                "{J} reachable from {r} in the dependency graph {sigma} is marked "
                "stale before the cascade terminates."
            ),
            variables={
                "r": "the root node triggering the invalidation cascade",
                "J": "any judgment reachable from r in sigma",
                "sigma": "the invalidation dependency graph",
            },
            subsystem=SubsystemKind.INVALIDATION,
            proof_style=ProofStyle.INDUCTIVE,
            description=(
                "Invalidation completeness is the dual of cascade termination: "
                "it guarantees that the cascade marks every dependent judgment "
                "stale, not just some of them. Together with stale conservativity, "
                "completeness makes the invalidation subsystem sound: the set of "
                "stale judgments after a cascade is exactly the overapproximation "
                "of the reachable subgraph of sigma rooted at r. Proof: by showing "
                "that the BFS/DFS frontier is exhausted exactly when the reachable "
                "set has been fully visited, which follows from the DAG property "
                "and the completeness of the graph traversal algorithm."
            ),
            prerequisites=["cascade_termination", "stale_conservativity"],
            difficulty=5,
            tags=["invalidation", "completeness", "cascade", "reachability"],
        )

        self.dependency_trace_integrity_schema: TheoremSchema = make_theorem_schema(
            name="dependency_trace_integrity",
            template_statement=(
                "The dependency trace {T} for judgment {J} has integrity: every "
                "edge {(u, v)} in {T} corresponds to a genuine proof dependency — "
                "the proof of {v} explicitly used {u} as a premise."
            ),
            variables={
                "T": "the dependency trace record for judgment J",
                "J": "the judgment whose trace is being verified",
                "(u, v)": "a dependency edge in T from premise u to consequence v",
                "u": "the premise judgment in the dependency edge",
                "v": "the consequence judgment depending on u",
            },
            subsystem=SubsystemKind.INVALIDATION,
            proof_style=ProofStyle.AUTOMATED,
            description=(
                "Dependency trace integrity prevents adversarial or erroneous "
                "insertion of spurious edges into the dependency graph sigma. A "
                "spurious edge (u, v) would make v appear to depend on u even "
                "though v's proof did not use u; this could cause v to be "
                "invalidated when u is revoked, even though v remains valid. "
                "Integrity is enforced by the proof bookkeeping mechanism: "
                "every edge added to sigma must be accompanied by a proof citation "
                "identifying the inference step that introduced the dependency. "
                "Proof: by showing that the trace construction algorithm is "
                "deterministic and that no edge can be added without a valid "
                "citation in the proof record."
            ),
            prerequisites=["support_correctness"],
            difficulty=6,
            tags=["invalidation", "integrity", "trace", "dependency-graph"],
        )

    def get_all_schemas(self) -> list[TheoremSchema]:
        """Return all five invalidation theorem schemas in dependency order.

        Returns
        -------
        list[TheoremSchema]
        """
        return [
            self.cascade_termination_schema,
            self.support_correctness_schema,
            self.stale_conservativity_schema,
            self.invalidation_completeness_schema,
            self.dependency_trace_integrity_schema,
        ]

    def get_schema_by_name(self, name: str) -> TheoremSchema | None:
        """Retrieve an invalidation schema by name.

        Parameters
        ----------
        name:
            Schema name to search for.

        Returns
        -------
        TheoremSchema or None
        """
        for schema in self.get_all_schemas():
            if schema.name == name:
                return schema
        return None

    def as_subsystem_schema(self) -> SubsystemSchema:
        """Wrap all invalidation schemas in a :class:`SubsystemSchema` bundle.

        Returns
        -------
        SubsystemSchema
        """
        bundle = SubsystemSchema(
            subsystem_name=SubsystemKind.INVALIDATION,
            subsystem_id=str(uuid.uuid4()),
            required_theorems=self.required_names(),
        )
        for schema in self.get_all_schemas():
            bundle.add_schema(schema)
        return bundle

    def required_names(self) -> list[str]:
        """Return the list of theorem names required by the Invalidation subsystem.

        Returns
        -------
        list[str]
        """
        return [s.name for s in self.get_all_schemas()]

    def describe(self) -> str:
        """Return a human-readable description of this template library.

        Returns
        -------
        str
        """
        lines: list[str] = [
            "InvalidationSchemaTemplate — Invalidation subsystem theorem library",
            "  theory2.tex §36.2.5",
            "  Purpose: Encode the cascade invalidation proof burden.",
            "  Theorems:",
        ]
        for s in self.get_all_schemas():
            diff = s.metadata.get("difficulty", "?")
            lines.append(f"    [{diff}/10] {s.name}: {s.description[:80]}...")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Module-level registry helpers
# ---------------------------------------------------------------------------

#: Registry mapping subsystem name to template class.
#: Used by :func:`build_all_templates` and external callers.
ALL_TEMPLATES: dict[str, type] = {
    "descent": DescentSchemaTemplate,
    "trust": TrustSchemaTemplate,
    "evidence": EvidenceSchemaTemplate,
    "federation": FederationSchemaTemplate,
    "invalidation": InvalidationSchemaTemplate,
}


def build_all_templates() -> dict[str, Any]:
    """Instantiate all template classes and return a dict of live instances.

    Constructs one instance of each template class in :data:`ALL_TEMPLATES`
    and returns a dictionary mapping subsystem name to the instantiated
    template object.  This is the primary entry point for code that needs
    to access all template schemas at once, e.g. during registry
    initialisation or full-system validation.

    Returns
    -------
    dict[str, object]
        Keys are subsystem names (``"descent"``, ``"trust"``, etc.);
        values are instantiated template objects.

    Examples
    --------
    >>> templates = build_all_templates()
    >>> descent = templates["descent"]
    >>> schemas = descent.get_all_schemas()
    >>> print(len(schemas))
    5
    """
    return {name: cls() for name, cls in ALL_TEMPLATES.items()}


def describe_template(subsystem_name: str) -> str:
    """Return the :meth:`describe` output for a named subsystem template.

    Instantiates the template class for *subsystem_name* and returns its
    human-readable description.

    Parameters
    ----------
    subsystem_name:
        One of ``"descent"``, ``"trust"``, ``"evidence"``,
        ``"federation"``, ``"invalidation"``.

    Returns
    -------
    str
        Multi-line description, or an error message if not found.

    Raises
    ------
    KeyError
        If *subsystem_name* is not in :data:`ALL_TEMPLATES`.
    """
    cls = ALL_TEMPLATES[subsystem_name]
    instance = cls()
    return instance.describe()


def list_all_schema_names() -> dict[str, list[str]]:
    """Return the complete list of theorem names for every subsystem template.

    Instantiates each template class and collects the result of
    :meth:`required_names` into a dictionary.

    Returns
    -------
    dict[str, list[str]]
        Mapping from subsystem name to list of required theorem names.

    Examples
    --------
    >>> names = list_all_schema_names()
    >>> "descent_compatibility" in names["descent"]
    True
    """
    result: dict[str, list[str]] = {}
    for name, cls in ALL_TEMPLATES.items():
        instance = cls()
        result[name] = instance.required_names()
    return result
