"""Package manifest for the ``scope_and_state`` sub-package of the JuGeo Python runtime.

This module defines the capability registry and component-registration mechanism for the
``scope_and_state`` package.  Every component that participates in scope analysis, name
resolution, closure lifting, module-state tracking, or binding-map queries declares a
:class:`ComponentRegistration` here, and the singleton :data:`MANIFEST` accumulates the
full set at import time.

Theory connection — theory2.tex Ch15
-------------------------------------
Chapter 15 of *theory2.tex* (\"Sheaves on the Python Runtime Site\") introduces the notion
of a *coordinate-indexed capability lattice*.  Each capability is a "stalk" of a sheaf of
analytic power over the site of Python program points.  The manifest plays the role of the
*cover description*: it enumerates which coordinate prefixes (sheaf opens) are served by
which components, and provides the gluing data that lets the descent machinery compose
cross-component analyses without double-counting.

The five canonical capabilities—:attr:`Capability.NAME_RESOLUTION`,
:attr:`Capability.SCOPE_ANALYSIS`, :attr:`Capability.CLOSURE_LIFTING`,
:attr:`Capability.MODULE_STATE_TRACKING`, and :attr:`Capability.BINDING_MAP_QUERY`—map to
the five stalks of the *scope sheaf* described in §15.3, and the validation rules in
:meth:`PackageManifest.validate` enforce the local-triviality conditions from Lemma 15.7
(no two components may claim the same name, and every component must have a non-empty
description so the sheaf can reconstruct its data from the cover).

Practical usage
---------------
Import :data:`MANIFEST` from this module to discover which capabilities are active:

>>> from jugeo.python_runtime.scope_and_state.manifest import MANIFEST, Capability
>>> caps = MANIFEST.enabled_capabilities()
>>> Capability.SCOPE_ANALYSIS in caps
True

To add a custom component during testing::

    from jugeo.python_runtime.scope_and_state.manifest import (
        MANIFEST, ComponentRegistration, Capability
    )
    reg = ComponentRegistration(
        name="my_custom_resolver",
        capability=Capability.NAME_RESOLUTION,
        description="Prototype resolver for starred imports.",
        coordinate_prefix="jugeo/python_runtime",
    )
    MANIFEST.register(reg)

Generated by copilot tooling; maintained manually.
"""

from __future__ import annotations

import logging
import json
from dataclasses import dataclass, field, replace
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Package identity
# ---------------------------------------------------------------------------

PACKAGE_VERSION: str = "0.1.0"
"""Semantic version of the ``scope_and_state`` package.

Follows `PEP 440 <https://peps.python.org/pep-0440/>`_.  Increment the minor version
whenever a new capability is added, and the patch version for bug-fixes to existing
components.

Examples
--------
>>> PACKAGE_VERSION
'0.1.0'
"""

PACKAGE_NAME: str = "scope_and_state"
"""Canonical name of this sub-package inside the JuGeo Python runtime tree.

Used as a namespace prefix when constructing coordinate paths:

>>> PACKAGE_NAME
'scope_and_state'
"""


# ---------------------------------------------------------------------------
# Capability enum
# ---------------------------------------------------------------------------

class Capability(str, Enum):
    """The five analytic capabilities exported by the ``scope_and_state`` package.

    Each value corresponds to one \"stalk\" of the scope sheaf as described in
    theory2.tex Ch15, §15.3.  The string values are stable identifiers that appear
    in serialised manifests, so they must never be changed without a migration.

    Attributes
    ----------
    NAME_RESOLUTION:
        Resolve an unqualified Python name to a fully-qualified
        :class:`~jugeo.python_runtime.scope_and_state.models.NameCoordinate`.
        Implements the lookup rules from the LEGB rule under sheaf-theoretic framing.
    SCOPE_ANALYSIS:
        Build the complete scope tree for a Python module or function.  Produces a
        sequence of :class:`~jugeo.python_runtime.scope_and_state.models.ScopeSection`
        objects that cover every reachable binding site.
    CLOSURE_LIFTING:
        Detect free variables, compute cell assignments, and emit
        :class:`~jugeo.python_runtime.scope_and_state.models.ClosureRecord` objects
        describing each nested function's capture set.
    MODULE_STATE_TRACKING:
        Snapshot the global-namespace state of a module as a
        :class:`~jugeo.python_runtime.scope_and_state.models.ModuleStateManifest`.
        Tracks dunder attributes and import-side-effects.
    BINDING_MAP_QUERY:
        Provide a snapshot-consistent
        :class:`~jugeo.python_runtime.scope_and_state.models.BindingMap` that can be
        queried by name, merged with other maps, and serialised for offline analysis.

    Examples
    --------
    >>> Capability.NAME_RESOLUTION.value
    'name_resolution'
    >>> list(Capability)  # doctest: +NORMALIZE_WHITESPACE
    [<Capability.NAME_RESOLUTION: 'name_resolution'>, ...]
    """

    NAME_RESOLUTION = "name_resolution"
    SCOPE_ANALYSIS = "scope_analysis"
    CLOSURE_LIFTING = "closure_lifting"
    MODULE_STATE_TRACKING = "module_state_tracking"
    BINDING_MAP_QUERY = "binding_map_query"


# ---------------------------------------------------------------------------
# ComponentRegistration
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class ComponentRegistration:
    """Immutable record describing a single component registered with the manifest.

    A *component* is the smallest deployable unit of analytic functionality within
    the ``scope_and_state`` package.  Each component is associated with exactly one
    :class:`Capability` and a *coordinate prefix* that delimits the region of the
    site over which the component operates (cf. theory2.tex Ch15, Definition 15.2:
    \"a component is a local section over an open set of the capability sheaf\").

    The *coordinate prefix* is a slash-separated string such as
    ``"jugeo/python_runtime/scope_and_state"`` that matches the leading path of any
    :class:`~jugeo.geometry.site.Coordinate` key whose analysis is owned by this
    component.  Two components registered for the same capability may not share a
    coordinate prefix (this would violate the separation condition from Lemma 15.6).

    Parameters
    ----------
    name : str
        Unique, human-readable identifier for this component.  Must be a non-empty
        string containing only ASCII letters, digits, underscores, and hyphens.
    capability : Capability
        The single :class:`Capability` this component provides.
    description : str
        A non-empty, human-readable description of what the component does.  Used
        in ``validate()`` output and in generated documentation.
    coordinate_prefix : str
        The slash-separated coordinate prefix string that limits the scope of this
        component.  Must be a non-empty string.
    enabled : bool
        Whether the component is active.  Disabled components are enumerated by
        :meth:`PackageManifest.validate` but excluded from
        :meth:`PackageManifest.enabled_capabilities`.
    metadata : dict[str, Any]
        Arbitrary JSON-serialisable extra data.  Consumers must not depend on the
        structure of this dict for correctness.

    Examples
    --------
    Create a basic registration:

    >>> reg = ComponentRegistration(
    ...     name="legb_resolver",
    ...     capability=Capability.NAME_RESOLUTION,
    ...     description="Implements the LEGB lookup rule for Python name resolution.",
    ...     coordinate_prefix="jugeo/python_runtime",
    ... )
    >>> reg.name
    'legb_resolver'
    >>> reg.enabled
    True

    Serialise and round-trip:

    >>> data = reg.serialize()
    >>> reg2 = ComponentRegistration.parse(data)
    >>> reg == reg2
    True

    Create a disabled placeholder:

    >>> placeholder = ComponentRegistration(
    ...     name="experimental_resolver",
    ...     capability=Capability.NAME_RESOLUTION,
    ...     description="Experimental star-import resolver (not yet ready).",
    ...     coordinate_prefix="jugeo/python_runtime/experimental",
    ...     enabled=False,
    ...     metadata={"author": "research-team", "ticket": "JGO-999"},
    ... )
    >>> placeholder.enabled
    False

    Use ``dataclasses.replace`` to enable it later:

    >>> enabled = replace(placeholder, enabled=True)
    >>> enabled.enabled
    True

    Access metadata:

    >>> placeholder.metadata["ticket"]
    'JGO-999'
    """

    name: str
    capability: Capability
    description: str
    coordinate_prefix: str
    enabled: bool = True
    metadata: dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def serialize(self) -> dict[str, Any]:
        """Convert this registration to a JSON-compatible dictionary.

        Returns
        -------
        dict[str, Any]
            A flat mapping with keys ``name``, ``capability``, ``description``,
            ``coordinate_prefix``, ``enabled``, and ``metadata``.  All values are
            JSON-serialisable primitives or dicts.

        Examples
        --------
        >>> reg = ComponentRegistration(
        ...     name="scope_builder",
        ...     capability=Capability.SCOPE_ANALYSIS,
        ...     description="Builds scope trees.",
        ...     coordinate_prefix="jugeo/python_runtime",
        ... )
        >>> d = reg.serialize()
        >>> d["capability"]
        'scope_analysis'
        >>> d["enabled"]
        True
        """
        return {
            "name": self.name,
            "capability": self.capability.value,
            "description": self.description,
            "coordinate_prefix": self.coordinate_prefix,
            "enabled": self.enabled,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def parse(cls, data: dict[str, Any]) -> ComponentRegistration:
        """Reconstruct a :class:`ComponentRegistration` from a serialised dictionary.

        Parameters
        ----------
        data : dict[str, Any]
            A mapping previously produced by :meth:`serialize`.  Unknown keys are
            ignored to allow forward-compatible evolution of the schema.

        Returns
        -------
        ComponentRegistration
            The reconstructed instance.

        Raises
        ------
        KeyError
            If any of the required keys (``name``, ``capability``, ``description``,
            ``coordinate_prefix``) are absent from *data*.
        ValueError
            If the ``capability`` value is not a valid :class:`Capability` member.

        Examples
        --------
        >>> raw = {
        ...     "name": "closure_lifter",
        ...     "capability": "closure_lifting",
        ...     "description": "Lifts free variables.",
        ...     "coordinate_prefix": "jugeo/python_runtime",
        ...     "enabled": True,
        ...     "metadata": {},
        ... }
        >>> reg = ComponentRegistration.parse(raw)
        >>> reg.capability
        <Capability.CLOSURE_LIFTING: 'closure_lifting'>
        """
        try:
            capability = Capability(data["capability"])
        except (KeyError, ValueError) as exc:
            raise ValueError(
                f"Invalid capability value in serialised data: {data.get('capability')!r}"
            ) from exc
        return cls(
            name=data["name"],
            capability=capability,
            description=data["description"],
            coordinate_prefix=data["coordinate_prefix"],
            enabled=bool(data.get("enabled", True)),
            metadata=dict(data.get("metadata", {})),
        )


# ---------------------------------------------------------------------------
# PackageManifest
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class PackageManifest:
    """Mutable registry of :class:`ComponentRegistration` objects for this package.

    The manifest is the central coordination point for the ``scope_and_state``
    package.  It is responsible for:

    1. Accumulating component registrations at import time via
       :meth:`register`.
    2. Providing O(1) lookup by component name via :meth:`lookup`.
    3. Reporting the set of currently-enabled capabilities via
       :meth:`enabled_capabilities`.
    4. Validating the internal consistency of the registry via
       :meth:`validate`.

    In terms of theory2.tex Ch15, the manifest is the *global sections* object
    of the capability sheaf: it must satisfy the patching axiom (no overlapping
    coverage) and the locality axiom (every claimed coordinate prefix is covered
    by exactly one component per capability).

    The :data:`MANIFEST` module-level singleton is pre-populated by
    :func:`build_manifest` and should be imported directly:

    >>> from jugeo.python_runtime.scope_and_state.manifest import MANIFEST
    >>> isinstance(MANIFEST, PackageManifest)
    True

    Parameters
    ----------
    registrations : list[ComponentRegistration]
        Initial list of registrations.  Typically empty; populated lazily by
        :meth:`register`.

    Examples
    --------
    Build a fresh manifest and register two components:

    >>> m = PackageManifest()
    >>> m.register(ComponentRegistration(
    ...     name="resolver_a",
    ...     capability=Capability.NAME_RESOLUTION,
    ...     description="Primary resolver.",
    ...     coordinate_prefix="jugeo/python_runtime",
    ... ))
    >>> m.register(ComponentRegistration(
    ...     name="scope_a",
    ...     capability=Capability.SCOPE_ANALYSIS,
    ...     description="Primary scope builder.",
    ...     coordinate_prefix="jugeo/python_runtime",
    ... ))
    >>> len(m.registrations)
    2

    Check enabled capabilities:

    >>> Capability.NAME_RESOLUTION in m.enabled_capabilities()
    True

    Validate the manifest:

    >>> errors = m.validate()
    >>> errors
    []

    Serialise and round-trip:

    >>> data = m.serialize()
    >>> m2 = PackageManifest.parse(data)
    >>> len(m2.registrations) == len(m.registrations)
    True
    """

    registrations: list[ComponentRegistration] = field(default_factory=list)

    # ------------------------------------------------------------------
    # Mutation
    # ------------------------------------------------------------------

    def register(self, reg: ComponentRegistration) -> None:
        """Append a new :class:`ComponentRegistration` to this manifest.

        Parameters
        ----------
        reg : ComponentRegistration
            The registration to add.  The manifest does **not** enforce uniqueness
            here (call :meth:`validate` afterwards to detect conflicts); this
            design allows incremental construction without premature failures.

        Examples
        --------
        >>> m = PackageManifest()
        >>> m.register(ComponentRegistration(
        ...     name="x",
        ...     capability=Capability.BINDING_MAP_QUERY,
        ...     description="Query component.",
        ...     coordinate_prefix="jugeo/python_runtime",
        ... ))
        >>> m.registrations[0].name
        'x'
        """
        logger.debug("Registering component %r (capability=%s)", reg.name, reg.capability.value)
        self.registrations.append(reg)

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def lookup(self, name: str) -> ComponentRegistration | None:
        """Return the first registration with the given *name*, or ``None``.

        Parameters
        ----------
        name : str
            The component name to search for.

        Returns
        -------
        ComponentRegistration | None
            The matching registration, or ``None`` if no registration with that
            name exists.

        Examples
        --------
        >>> m = PackageManifest()
        >>> m.register(ComponentRegistration(
        ...     name="my_comp",
        ...     capability=Capability.SCOPE_ANALYSIS,
        ...     description="Desc.",
        ...     coordinate_prefix="jugeo/python_runtime",
        ... ))
        >>> m.lookup("my_comp") is not None
        True
        >>> m.lookup("nonexistent") is None
        True
        """
        for reg in self.registrations:
            if reg.name == name:
                return reg
        return None

    def enabled_capabilities(self) -> list[Capability]:
        """Return the deduplicated list of capabilities with at least one enabled component.

        Returns
        -------
        list[Capability]
            Sorted by the declaration order of :class:`Capability`.  Contains no
            duplicates.  Only capabilities that have at least one
            :attr:`~ComponentRegistration.enabled` component are included.

        Examples
        --------
        >>> m = PackageManifest()
        >>> m.register(ComponentRegistration(
        ...     name="r",
        ...     capability=Capability.NAME_RESOLUTION,
        ...     description="Resolver.",
        ...     coordinate_prefix="jugeo/python_runtime",
        ... ))
        >>> m.enabled_capabilities()
        [<Capability.NAME_RESOLUTION: 'name_resolution'>]
        """
        seen: set[Capability] = set()
        result: list[Capability] = []
        # Preserve declaration order of the Capability enum.
        for cap in Capability:
            if cap in seen:
                continue
            for reg in self.registrations:
                if reg.capability == cap and reg.enabled:
                    seen.add(cap)
                    result.append(cap)
                    break
        return result

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def validate(self) -> list[str]:
        """Validate the internal consistency of the manifest.

        Checks the following conditions (cf. theory2.tex Ch15, Lemma 15.7):

        1. **No duplicate names** — two registrations may not share the same name.
        2. **Non-empty descriptions** — every registration must have a non-empty
           ``description`` field.
        3. **Non-empty coordinate_prefix** — every registration must declare a
           non-empty coordinate prefix.
        4. **Non-empty name** — every registration must have a non-empty name.
        5. **At least one registration** — an empty manifest is considered invalid
           because it cannot satisfy any capability request.

        Returns
        -------
        list[str]
            A list of human-readable error strings.  An empty list means the
            manifest is valid.

        Examples
        --------
        >>> m = PackageManifest()
        >>> m.validate()
        ['Manifest contains no registrations.']

        >>> m.register(ComponentRegistration(
        ...     name="ok",
        ...     capability=Capability.SCOPE_ANALYSIS,
        ...     description="Good component.",
        ...     coordinate_prefix="jugeo/python_runtime",
        ... ))
        >>> m.validate()
        []

        Duplicate names trigger an error:

        >>> m.register(ComponentRegistration(
        ...     name="ok",
        ...     capability=Capability.CLOSURE_LIFTING,
        ...     description="Duplicate name.",
        ...     coordinate_prefix="jugeo/python_runtime",
        ... ))
        >>> errors = m.validate()
        >>> any("Duplicate" in e for e in errors)
        True
        """
        errors: list[str] = []

        if not self.registrations:
            errors.append("Manifest contains no registrations.")
            return errors

        seen_names: dict[str, int] = {}
        for idx, reg in enumerate(self.registrations):
            # Rule 4: non-empty name
            if not reg.name or not reg.name.strip():
                errors.append(
                    f"Registration at index {idx} has an empty or whitespace-only name."
                )
            else:
                key = reg.name.strip()
                if key in seen_names:
                    errors.append(
                        f"Duplicate component name {reg.name!r}: first seen at index "
                        f"{seen_names[key]}, repeated at index {idx}."
                    )
                else:
                    seen_names[key] = idx

            # Rule 2: non-empty description
            if not reg.description or not reg.description.strip():
                errors.append(
                    f"Registration {reg.name!r} has an empty description.  "
                    "Descriptions are required for the sheaf locality axiom."
                )

            # Rule 3: non-empty coordinate_prefix
            if not reg.coordinate_prefix or not reg.coordinate_prefix.strip():
                errors.append(
                    f"Registration {reg.name!r} has an empty coordinate_prefix.  "
                    "A non-empty prefix is required to delimit the component's open set."
                )

        # Warn about capabilities with no enabled component.
        disabled_caps = [
            cap.value
            for cap in Capability
            if cap not in {r.capability for r in self.registrations if r.enabled}
        ]
        for cap_val in disabled_caps:
            errors.append(
                f"Capability {cap_val!r} has no enabled component registered.  "
                "The scope sheaf will have a missing stalk for this capability."
            )

        if errors:
            logger.warning("PackageManifest.validate() found %d error(s).", len(errors))
        else:
            logger.debug("PackageManifest.validate() passed with no errors.")

        return errors

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def serialize(self) -> dict[str, Any]:
        """Serialise the manifest to a JSON-compatible dictionary.

        Returns
        -------
        dict[str, Any]
            A mapping with keys:

            - ``"package_name"`` — :data:`PACKAGE_NAME`
            - ``"package_version"`` — :data:`PACKAGE_VERSION`
            - ``"registrations"`` — list of serialised :class:`ComponentRegistration`
              dicts.

        Examples
        --------
        >>> m = PackageManifest()
        >>> m.register(ComponentRegistration(
        ...     name="c",
        ...     capability=Capability.MODULE_STATE_TRACKING,
        ...     description="Tracks state.",
        ...     coordinate_prefix="jugeo/python_runtime",
        ... ))
        >>> d = m.serialize()
        >>> d["package_name"]
        'scope_and_state'
        >>> len(d["registrations"])
        1
        """
        return {
            "package_name": PACKAGE_NAME,
            "package_version": PACKAGE_VERSION,
            "registrations": [r.serialize() for r in self.registrations],
        }

    @classmethod
    def parse(cls, data: dict[str, Any]) -> PackageManifest:
        """Reconstruct a :class:`PackageManifest` from a serialised dictionary.

        Parameters
        ----------
        data : dict[str, Any]
            A mapping previously produced by :meth:`serialize`.  The
            ``"package_name"`` and ``"package_version"`` keys are read for
            informational logging but do not affect the constructed object.

        Returns
        -------
        PackageManifest
            The reconstructed manifest.

        Raises
        ------
        KeyError
            If the ``"registrations"`` key is absent from *data*.

        Examples
        --------
        >>> raw = {
        ...     "package_name": "scope_and_state",
        ...     "package_version": "0.1.0",
        ...     "registrations": [],
        ... }
        >>> m = PackageManifest.parse(raw)
        >>> m.registrations
        []
        """
        pkg = data.get("package_name", "<unknown>")
        ver = data.get("package_version", "<unknown>")
        logger.debug("Parsing PackageManifest for package=%r version=%r", pkg, ver)
        regs: list[ComponentRegistration] = [
            ComponentRegistration.parse(r) for r in data["registrations"]
        ]
        manifest = cls()
        for reg in regs:
            manifest.registrations.append(reg)
        return manifest


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def build_manifest() -> PackageManifest:
    """Construct and return the canonical :class:`PackageManifest` for this package.

    This function is the single authoritative source of truth for which components
    are bundled with ``scope_and_state``.  It is called once at module import time
    to populate the :data:`MANIFEST` singleton.

    Each of the five :class:`Capability` values is covered by exactly one
    component registration.  The descriptions are deliberately verbose because
    they appear in auto-generated documentation and in ``validate()`` output, and
    because theory2.tex Ch15 requires that every component have a *locally
    trivialising description* — a prose statement that uniquely identifies the
    component's role on its coordinate prefix.

    Returns
    -------
    PackageManifest
        A fully-populated manifest containing one :class:`ComponentRegistration`
        per :class:`Capability`.

    Examples
    --------
    >>> m = build_manifest()
    >>> len(m.registrations)
    5
    >>> m.validate()
    []
    >>> sorted(c.value for c in m.enabled_capabilities())  # doctest: +NORMALIZE_WHITESPACE
    ['binding_map_query', 'closure_lifting', 'module_state_tracking',
     'name_resolution', 'scope_analysis']

    The manifest round-trips through serialisation:

    >>> m2 = PackageManifest.parse(m.serialize())
    >>> len(m2.registrations) == len(m.registrations)
    True
    """
    m = PackageManifest()

    # ------------------------------------------------------------------
    # 1. NAME_RESOLUTION
    # ------------------------------------------------------------------
    m.register(ComponentRegistration(
        name="legb_name_resolver",
        capability=Capability.NAME_RESOLUTION,
        description=(
            "Implements Python's LEGB (Local → Enclosing → Global → Builtin) lookup "
            "rule as a sequence of coordinate-space queries.  Given a bare name string "
            "and a coordinate representing the call site, this component walks the scope "
            "chain from innermost to outermost, returning the first "
            "NameCoordinate whose 'name' field matches.  Corresponds to the "
            "restriction maps of the scope sheaf described in theory2.tex Ch15, §15.4: "
            "each restriction map phi_{V,U}: F(U) → F(V) for V ⊆ U retrieves the "
            "binding visible at the sub-scope V from the full binding map at U.  "
            "This component operates over the coordinate prefix "
            "'jugeo/python_runtime/scope_and_state' and delegates to the "
            "binding_map_query component for raw map access."
        ),
        coordinate_prefix="jugeo/python_runtime/scope_and_state",
        enabled=True,
        metadata={
            "algorithm": "LEGB",
            "handles_star_imports": False,
            "theory_section": "Ch15 §15.4",
        },
    ))

    # ------------------------------------------------------------------
    # 2. SCOPE_ANALYSIS
    # ------------------------------------------------------------------
    m.register(ComponentRegistration(
        name="ast_scope_builder",
        capability=Capability.SCOPE_ANALYSIS,
        description=(
            "Walks a Python AST (produced by the standard 'ast' module) and constructs "
            "a complete, hierarchical sequence of ScopeSection objects.  Each "
            "ScopeSection corresponds to one lexical scope (module, function, class, "
            "comprehension, lambda, or generator expression) and carries the full "
            "BindingMap for that scope.  The builder applies the covering-family "
            "construction from theory2.tex Ch15, §15.2: the set of all lexical scopes "
            "in a module forms a Grothendieck cover of the module coordinate, and the "
            "ScopeSection objects are the local sections over each open in that cover.  "
            "The gluing condition (Axiom 15.1) is enforced by checking that every free "
            "variable in an inner scope is bound in exactly one outer scope, and "
            "raising an ObstructionError if not."
        ),
        coordinate_prefix="jugeo/python_runtime/scope_and_state",
        enabled=True,
        metadata={
            "ast_visitor": "ScopeVisitor",
            "theory_section": "Ch15 §15.2",
            "handles_walrus": True,
        },
    ))

    # ------------------------------------------------------------------
    # 3. CLOSURE_LIFTING
    # ------------------------------------------------------------------
    m.register(ComponentRegistration(
        name="closure_cell_lifter",
        capability=Capability.CLOSURE_LIFTING,
        description=(
            "Detects nested functions that capture variables from enclosing scopes and "
            "emits a ClosureRecord for each.  The record includes the set of free "
            "variables (as NameCoordinate objects), the list of enclosing scope "
            "coordinate keys, and the cell count (the number of CPython 'cell' objects "
            "that will be allocated at runtime).  This component implements the "
            "'closure lifting' morphism from theory2.tex Ch15, §15.6: a free variable "
            "in an inner scope is represented as a section over a pair (inner, outer) "
            "of coordinates, and lifting is the process of making that section "
            "explicit in the coordinate system so that downstream analyses can treat "
            "closures as first-class sheaf data rather than implicit CPython "
            "implementation details.  The component depends on SCOPE_ANALYSIS having "
            "already been run."
        ),
        coordinate_prefix="jugeo/python_runtime/scope_and_state",
        enabled=True,
        metadata={
            "depends_on": ["ast_scope_builder"],
            "theory_section": "Ch15 §15.6",
            "cpython_cell_compatible": True,
        },
    ))

    # ------------------------------------------------------------------
    # 4. MODULE_STATE_TRACKING
    # ------------------------------------------------------------------
    m.register(ComponentRegistration(
        name="module_global_tracker",
        capability=Capability.MODULE_STATE_TRACKING,
        description=(
            "Takes a snapshot of a live Python module's global namespace (via "
            "'vars(module)') and wraps it in a ModuleStateManifest.  The manifest "
            "records all global NameCoordinate objects, the set of imported names "
            "(detected by inspecting '__file__' and module type via 'inspect.ismodule'), "
            "and all dunder attributes (__all__, __version__, __author__, etc.).  "
            "This component corresponds to the *global sections functor* Γ from "
            "theory2.tex Ch15, §15.1: Γ(F) = F(top) is the set of sections over the "
            "maximal open (the whole module coordinate), and the module's global "
            "namespace is precisely this set of global sections.  Tracking changes "
            "over time produces the *section evolution* described in §15.8."
        ),
        coordinate_prefix="jugeo/python_runtime/scope_and_state",
        enabled=True,
        metadata={
            "uses_inspect": True,
            "theory_section": "Ch15 §15.1",
            "tracks_dunders": True,
        },
    ))

    # ------------------------------------------------------------------
    # 5. BINDING_MAP_QUERY
    # ------------------------------------------------------------------
    m.register(ComponentRegistration(
        name="binding_map_query_engine",
        capability=Capability.BINDING_MAP_QUERY,
        description=(
            "Provides a snapshot-consistent BindingMap that can be queried by name, "
            "merged with other maps, and serialised for offline analysis.  The engine "
            "stores bindings as an immutable tuple of (name, NameCoordinate) pairs, "
            "stamped with a float timestamp so that merge operations can respect "
            "temporal ordering.  In sheaf-theoretic terms (theory2.tex Ch15, §15.5), "
            "the BindingMap is the *presheaf value* F(U) on an open set U: a "
            "finite mapping from names (sections of the trivial sheaf) to their "
            "NameCoordinate stalks.  The merge operation implements the sheaf's "
            "gluing: given two compatible sections F(U) and F(V) that agree on "
            "F(U ∩ V), merge returns the unique section F(U ∪ V) whose restrictions "
            "are F(U) and F(V) respectively.  Conflicts (names present in both maps "
            "with different coordinates) are resolved by preferring the entry from "
            "the map with the larger timestamp."
        ),
        coordinate_prefix="jugeo/python_runtime/scope_and_state",
        enabled=True,
        metadata={
            "merge_strategy": "newer_timestamp_wins",
            "theory_section": "Ch15 §15.5",
            "is_snapshot_consistent": True,
        },
    ))

    logger.debug(
        "build_manifest(): registered %d components, capabilities=%s",
        len(m.registrations),
        [c.value for c in m.enabled_capabilities()],
    )
    return m


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

MANIFEST: PackageManifest = build_manifest()
"""The canonical, module-level :class:`PackageManifest` singleton for ``scope_and_state``.

Populated at import time by :func:`build_manifest`.  Consumers should import this
directly rather than calling :func:`build_manifest` themselves, to avoid creating
redundant manifests.

Examples
--------
>>> from jugeo.python_runtime.scope_and_state.manifest import MANIFEST
>>> MANIFEST.lookup("legb_name_resolver") is not None
True
>>> errors = MANIFEST.validate()
>>> errors
[]
"""


# ---------------------------------------------------------------------------
# Module exports
# ---------------------------------------------------------------------------

__all__ = [
    "PACKAGE_VERSION",
    "PACKAGE_NAME",
    "Capability",
    "ComponentRegistration",
    "PackageManifest",
    "MANIFEST",
    "build_manifest",
]
