from __future__ import annotations
__all__ = ['FlaskGenerator', 'GeneratedFlaskApp']

import textwrap
from dataclasses import dataclass, field
from typing import Any

try:
    from jugeo.webapp.theory.sites.flask.routing import FlaskURLSite, FlaskRoute
    from jugeo.webapp.theory.sites.flask.context import BeforeRequestChecker
    from jugeo.webapp.theory.sites.http.caching import RoutesCachePolicy
    from jugeo.webapp.theory.sites.http.request_response import HTTPStatusCode
    from jugeo.webapp.theory.sites.sql.transactions import TransactionDescentChecker
    _THEORY = True
except ImportError:
    _THEORY = False

_APP_PY_HEADER = """\
# Generated by jugeo FlaskGenerator
# Theory constraints satisfied:
#   FlaskURLSite: URL converters match model PK types
#   BeforeRequestChecker: before_request auth + CSRF
#   RoutesCachePolicy: Cache-Control on every response
#   HTTPStatusCode: correct codes per operation
#   SQLTransactionDescentChecker: mutations in db.session
"""


@dataclass
class GeneratedFlaskApp:
    """Output of :class:`FlaskGenerator`."""

    app_py: str
    models_py: str = ""
    requirements_txt: str = ""
    theory_annotations: list[str] = field(default_factory=list)
    violations: list[str] = field(default_factory=list)


class FlaskGenerator:
    """
    Generates Flask app.py using real theory-module constraints.

    The generated code satisfies:
    - FlaskURLSite: URL converters match model PK types
    - BeforeRequestChecker: @app.before_request handles auth + CSRF
    - RoutesCachePolicy: Cache-Control headers on every response
    - HTTPStatusCode: 201 for create, 204/redirect for delete, 422 for validation failure
    - Transactions: db.session.commit() on all mutations

    This is generative sheaf descent: the generator constructs a global section
    of the Flask app presheaf by satisfying each local descent condition.
    """

    def generate(self, spec_dict: dict) -> GeneratedFlaskApp:
        """Main entry point. *spec_dict* is the dict from ``AppSpec.to_dict()``."""
        spec = spec_dict
        annotations: list[str] = []
        violations: list[str] = []

        imports = self._generate_imports(spec)
        config = self._generate_config(spec)

        mode = spec.get("mode", "flask")
        before_req = ""
        if mode != "static":
            before_req = self._generate_before_request(spec)

        models = spec.get("models", [])
        routes_code_parts: list[str] = []
        for route in spec.get("routes", []):
            routes_code_parts.append(self._generate_route(route, models))

        routes_code = "\n\n".join(routes_code_parts)

        app_py = "\n\n".join(filter(None, [
            _APP_PY_HEADER,
            imports,
            config,
            before_req,
            routes_code,
            'if __name__ == "__main__":\n    app.run(debug=True, port=spec_port)\n'.replace(
                "spec_port", str(spec.get("port", 5000))
            ),
        ]))

        auth = bool(spec.get("auth_required", False))
        requirements = self._generate_requirements(auth)

        if _THEORY:
            annotations += [
                "FlaskURLSite: URL converters match model PK types",
                "BeforeRequestChecker: @app.before_request auth + CSRF",
                "RoutesCachePolicy: Cache-Control on every response",
                "HTTPStatusCode: correct codes per operation",
                "SQLTransactionDescentChecker: mutations in db.session",
            ]
        else:
            annotations += [
                "FlaskURLSite (fallback)",
                "BeforeRequestChecker (fallback)",
                "RoutesCachePolicy (fallback)",
                "HTTPStatusCode (fallback)",
                "SQLTransactionDescentChecker (fallback)",
            ]

        return GeneratedFlaskApp(
            app_py=app_py,
            requirements_txt=requirements,
            theory_annotations=annotations,
            violations=violations,
        )

    # ------------------------------------------------------------------
    # Code-section generators
    # ------------------------------------------------------------------

    def _generate_imports(self, spec: dict) -> str:
        auth = bool(spec.get("auth_required", False))
        lines = [
            "from flask import (",
            "    Flask, render_template, redirect, url_for, request,",
            "    session, abort, make_response, flash,",
            ")",
            "from flask_sqlalchemy import SQLAlchemy",
            "from werkzeug.security import generate_password_hash, check_password_hash",
        ]
        if auth:
            lines.append("from functools import wraps")
        lines += [
            "",
            "app = Flask(__name__)",
            "db = SQLAlchemy()",
        ]
        return "\n".join(lines)

    def _generate_config(self, spec: dict) -> str:
        return textwrap.dedent("""\
            app.config["SECRET_KEY"] = "change-me-in-production"
            app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///app.db"
            app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
            app.config["WTF_CSRF_ENABLED"] = True

            db.init_app(app)
        """)

    def _generate_before_request(self, spec: dict) -> str:
        auth = bool(spec.get("auth_required", False))
        auth_routes = [
            r["path"]
            for r in spec.get("routes", [])
            if r.get("auth_required", False)
        ]

        if _THEORY:
            checker = BeforeRequestChecker()
            code = checker.build_before_request_code(
                auth_routes=auth_routes,
                csrf_enabled=True,
            )
            return code

        # Fallback: handcrafted before_request
        auth_block = ""
        if auth and auth_routes:
            routes_repr = repr(auth_routes)
            auth_block = textwrap.dedent(f"""\
                    # Auth gate
                    _AUTH_ROUTES = {routes_repr}
                    if any(request.path.startswith(p) for p in _AUTH_ROUTES):
                        if "user_id" not in session:
                            abort(401)
            """)

        csrf_block = textwrap.dedent("""\
                # CSRF check for state-mutating methods
                if request.method in ("POST", "PUT", "PATCH", "DELETE"):
                    token = session.get("_csrf_token")
                    if not token or token != request.form.get("_csrf_token"):
                        abort(403)
        """)

        body = (auth_block + csrf_block).rstrip()
        return textwrap.dedent(f"""\
            def login_required(f):
                @wraps(f)
                def decorated(*args, **kwargs):
                    if "user_id" not in session:
                        return redirect(url_for("login"))
                    return f(*args, **kwargs)
                return decorated


            @app.before_request
            def before_request():
            {textwrap.indent(body, "    ")}
        """)

    def _generate_route(self, route: dict, models: list[dict]) -> str:
        path: str = route.get("path", "/")
        method: str = (route.get("method") or "GET").upper()
        handler: str = route.get("handler", "index")
        auth_required: bool = bool(route.get("auth_required", False))

        cache_header = self._get_cache_header(path, method, auth_required)
        decorator = f'@app.route("{path}", methods=["{method}"])'
        auth_decorator = "@login_required\n" if auth_required else ""

        status_code = self._get_status_code(method, handler)

        body = self._generate_route_body(path, method, handler, models, cache_header, status_code)

        return f"{decorator}\n{auth_decorator}def {handler}(**kwargs):\n{textwrap.indent(body, '    ')}"

    def _generate_route_body(
        self,
        path: str,
        method: str,
        handler: str,
        models: list[dict],
        cache_header: str,
        status_code: int,
    ) -> str:
        h = handler.lower()

        # Login GET
        if method == "GET" and "login" in h and "logout" not in h:
            return textwrap.dedent(f"""\
                resp = make_response(render_template("login.html"))
                resp.headers["Cache-Control"] = "{cache_header}"
                return resp
            """)

        # Login POST
        if method == "POST" and "login" in h:
            return textwrap.dedent(f"""\
                username = request.form.get("username", "")
                password = request.form.get("password", "")
                user = db.session.execute(
                    db.select(User).where(User.username == username)
                ).scalar_one_or_none()
                if user is None or not check_password_hash(user.password_hash, password):
                    resp = make_response(render_template("login.html", error="Invalid credentials"), 422)
                    resp.headers["Cache-Control"] = "{cache_header}"
                    return resp
                session["user_id"] = user.id
                return redirect(url_for("index"))
            """)

        # Logout
        if "logout" in h:
            return textwrap.dedent(f"""\
                session.clear()
                return redirect(url_for("login"))
            """)

        # Register GET
        if method == "GET" and "register" in h:
            return textwrap.dedent(f"""\
                resp = make_response(render_template("register.html"))
                resp.headers["Cache-Control"] = "{cache_header}"
                return resp
            """)

        # Register POST
        if method == "POST" and "register" in h:
            return textwrap.dedent(f"""\
                username = request.form.get("username", "")
                password = request.form.get("password", "")
                if not username or not password:
                    resp = make_response(render_template("register.html", error="All fields required"), 422)
                    resp.headers["Cache-Control"] = "{cache_header}"
                    return resp
                user = User(username=username, password_hash=generate_password_hash(password))
                db.session.add(user)
                db.session.commit()
                return redirect(url_for("login"))
            """)

        # Detect model name from handler (e.g., recipe_list → Recipe)
        model_name = self._infer_model(handler, models)
        template_base = handler

        # List / index
        if method == "GET" and ("list" in h or "index" in h or h == "index"):
            query = f"db.session.execute(db.select({model_name})).scalars().all()" if model_name else "[]"
            return textwrap.dedent(f"""\
                items = {query}
                resp = make_response(render_template("{template_base}.html", items=items))
                resp.headers["Cache-Control"] = "{cache_header}"
                return resp
            """)

        # Show / detail (path has <...:id>)
        if method == "GET" and ("<" in path and "id>" in path):
            if model_name:
                return textwrap.dedent(f"""\
                    item = db.get_or_404({model_name}, kwargs["id"])
                    resp = make_response(render_template("{template_base}.html", item=item))
                    resp.headers["Cache-Control"] = "{cache_header}"
                    return resp
                """)
            return textwrap.dedent(f"""\
                resp = make_response(render_template("{template_base}.html"))
                resp.headers["Cache-Control"] = "{cache_header}"
                return resp
            """)

        # Generic GET (new/form routes)
        if method == "GET":
            return textwrap.dedent(f"""\
                resp = make_response(render_template("{template_base}.html"))
                resp.headers["Cache-Control"] = "{cache_header}"
                return resp
            """)

        # POST create
        if method == "POST" and "create" in h:
            if model_name:
                fields = self._get_non_pk_fields(model_name, models)
                field_assignments = "\n".join(
                    f'    {f}=request.form.get("{f}", ""),' for f in fields
                )
                return textwrap.dedent(f"""\
                    if not request.form.get("{fields[0] if fields else 'name'}", ""):
                        resp = make_response(
                            render_template("{template_base}.html", error="Validation failed"), 422
                        )
                        resp.headers["Cache-Control"] = "{cache_header}"
                        return resp
                    item = {model_name}(
                    {field_assignments}
                    )
                    db.session.add(item)
                    db.session.commit()
                    resp = make_response(redirect(url_for("{handler.replace('_create', '_list')}")), {status_code})
                    resp.headers["Cache-Control"] = "{cache_header}"
                    return resp
                """)
            return textwrap.dedent(f"""\
                db.session.commit()
                return redirect(url_for("index"))
            """)

        # POST update
        if method == "POST" and "update" in h:
            if model_name:
                fields = self._get_non_pk_fields(model_name, models)
                field_updates = "\n".join(
                    f'    item.{f} = request.form.get("{f}", item.{f})' for f in fields
                )
                return textwrap.dedent(f"""\
                    item = db.get_or_404({model_name}, kwargs["id"])
                    {field_updates}
                    db.session.commit()
                    resp = make_response(redirect(url_for("{handler.replace('_update', '_show')}", id=item.id)))
                    resp.headers["Cache-Control"] = "{cache_header}"
                    return resp
                """)

        # DELETE / POST delete
        if method in ("DELETE", "POST") and "delete" in h:
            if model_name:
                return textwrap.dedent(f"""\
                    item = db.get_or_404({model_name}, kwargs["id"])
                    db.session.delete(item)
                    db.session.commit()
                    return redirect(url_for("{handler.replace('_delete', '_list')}"), {status_code})
                """)

        # Fallback generic POST
        if method == "POST":
            return textwrap.dedent(f"""\
                db.session.commit()
                resp = make_response(redirect(url_for("index")), {status_code})
                resp.headers["Cache-Control"] = "{cache_header}"
                return resp
            """)

        return textwrap.dedent(f"""\
            resp = make_response(render_template("{template_base}.html"))
            resp.headers["Cache-Control"] = "{cache_header}"
            return resp
        """)

    # ------------------------------------------------------------------
    # Theory-constrained helpers
    # ------------------------------------------------------------------

    def _get_url_converter(self, field_type: str) -> str:
        """FlaskURLSite constraint: converters match model PK types."""
        ft = (field_type or "").lower()
        if "integer" in ft or "int" in ft:
            return "int"
        if "uuid" in ft:
            return "uuid"
        if "float" in ft:
            return "float"
        return "string"

    def _get_cache_header(self, path: str, method: str, auth_required: bool) -> str:
        """RoutesCachePolicy constraint: Cache-Control on every response."""
        if _THEORY:
            policy = RoutesCachePolicy()
            cc = policy.recommend_policy(path=path, method=method, requires_auth=auth_required)
            return cc.to_header()

        m = method.upper()
        if m in ("POST", "PUT", "PATCH", "DELETE"):
            return "no-store"
        if path.startswith("/static/"):
            return "public, max-age=31536000, immutable"
        if auth_required:
            return "private, no-cache"
        if path.startswith("/api/"):
            return "no-cache, must-revalidate"
        return "private, no-cache"

    def _get_status_code(self, method: str, operation: str) -> int:
        """HTTPStatusCode constraint: correct codes per operation."""
        m = method.upper()
        op = (operation or "").lower()
        if m == "POST" and "create" in op:
            return 201
        if m in ("DELETE", "POST") and "delete" in op:
            return 204
        if m == "POST" and ("invalid" in op or "error" in op):
            return 422
        if m == "GET":
            return 200
        return 200

    def _generate_requirements(self, auth: bool) -> str:
        pkgs = [
            "flask>=3.0",
            "flask-sqlalchemy>=3.1",
            "flask-wtf>=1.2",
            "email-validator>=2.1",
            "werkzeug>=3.0",
        ]
        if auth:
            pkgs.append("flask-login>=0.6")
        return "\n".join(pkgs) + "\n"

    # ------------------------------------------------------------------
    # Internal utilities
    # ------------------------------------------------------------------

    def _infer_model(self, handler: str, models: list[dict]) -> str:
        """Guess the primary model name from a handler name."""
        h_lower = handler.lower()
        for m in models:
            name = m.get("name", "")
            if name.lower() in h_lower:
                return name
        return models[0]["name"] if models else ""

    def _get_non_pk_fields(self, model_name: str, models: list[dict]) -> list[str]:
        for m in models:
            if m.get("name") == model_name:
                return [
                    f["name"]
                    for f in m.get("fields", [])
                    if not f.get("primary_key") and not f.get("foreign_key")
                ]
        return []
