from __future__ import annotations
__all__ = ['JSGenerator', 'GeneratedJS']

import re
from dataclasses import dataclass, field

try:
    from jugeo.webapp.theory.functors.py_js_semantics import TranspilationHazardScanner
    from jugeo.webapp.theory.functors.js_scoping import ScopingAnalyzer
    from jugeo.webapp.theory.functors.js_this_binding import THIS_BINDING_ANALYSES
    from jugeo.webapp.theory.functors.js_truthiness import NullishCoalescingGuide
    _THEORY = True
except ImportError:
    _THEORY = False


@dataclass
class GeneratedJS:
    """Output of :class:`JSGenerator`."""

    csrf_js: str = ""
    form_validation_js: str = ""
    interactions_js: str = ""
    theory_annotations: list[str] = field(default_factory=list)
    violations: list[str] = field(default_factory=list)


class JSGenerator:
    """
    Generates JavaScript satisfying theory-module descent conditions.

    Generated JS satisfies:
    - No Python→JS semantic traps (TranspilationHazardScanner)
    - let/const only — no var (ScopingAnalyzer)
    - Arrow function callbacks — no this-binding loss (THIS_BINDING_ANALYSES)
    - ?? for defaults — not || (NullishCoalescingGuide)
    - async/await for all fetch() calls (EventLoopSite)
    - parseInt always with radix 10 (SafeArithmeticPatterns)
    - Explicit null checks: x == null (catches both null and undefined)
    """

    def generate(self, spec_dict: dict) -> GeneratedJS:
        """Main entry point. *spec_dict* is the dict from AppSpec.to_dict()."""
        spec = spec_dict
        annotations: list[str] = []
        violations: list[str] = []

        if _THEORY:
            annotations.append("TranspilationHazardScanner: active")
            annotations.append("ScopingAnalyzer: active — const/let only")
            annotations.append("THIS_BINDING_ANALYSES: active — arrow functions required")
            annotations.append("NullishCoalescingGuide: active — ?? not ||")
        else:
            annotations.append("theory modules unavailable — static descent conditions applied")
            annotations.append("ScopingAnalyzer: static — const/let only pattern enforced")
            annotations.append("THIS_BINDING_ANALYSES: static — arrow function pattern enforced")
            annotations.append("NullishCoalescingGuide: static — ?? pattern enforced")
            annotations.append("EventLoopSite: static — async/await pattern enforced")
            annotations.append("SafeArithmeticPatterns: static — parseInt radix 10 enforced")

        mode = spec.get("mode", "flask")

        csrf_js = self._generate_csrf_js(spec) if mode == "flask" else ""
        form_validation_js = self._generate_form_validation_js(spec)
        interactions_js = self._generate_interactions_js(spec)

        all_code = "\n".join(filter(None, [csrf_js, form_validation_js, interactions_js]))
        violations = self._verify_generated_js(all_code)

        return GeneratedJS(
            csrf_js=csrf_js,
            form_validation_js=form_validation_js,
            interactions_js=interactions_js,
            theory_annotations=annotations,
            violations=violations,
        )

    def _generate_csrf_js(self, spec: dict) -> str:
        return """\
// Generated by jugeo JSGenerator
// Theory: ScopingAnalyzer(const only), js_this_binding(arrow fns)
// [ScopingAnalyzer: const only]
const CSRF = (() => {
  // [js_truthiness: ?? not || — empty string is valid token placeholder]
  const token = document.querySelector('meta[name="csrf-token"]')?.content ?? '';

  // [THIS_BINDING_ANALYSES: arrow function — no this binding needed]
  const headers = () => ({
    'X-CSRFToken': token,
    'Content-Type': 'application/json',
  });

  // [EventLoopSite: async/await wrapper for all mutating fetches]
  const post = async (url, data) => {
    // [js_error_handling: always check response.ok]
    const response = await fetch(url, {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      throw new Error(`Request failed: ${response.status}`);
    }
    return response.json();
  };

  const del = async (url) => {
    const response = await fetch(url, { method: 'DELETE', headers: headers() });
    if (!response.ok) throw new Error(`Delete failed: ${response.status}`);
    return response.status;
  };

  return { token, headers, post, del };
})();
"""

    def _generate_form_validation_js(self, spec: dict) -> str:
        forms = spec.get("forms", [])
        if not forms:
            return ""

        return """\
// Generated by jugeo JSGenerator
// Theory: TranspilationHazardScanner, ScopingAnalyzer, js_truthiness
// [TranspilationHazardScanner: no Python truthiness patterns]
// [js_truthiness: explicit .trim() !== '' not if(value)]
const FormValidator = (() => {
  const validate = (formEl) => {
    const errors = {};
    formEl.querySelectorAll('[data-required]').forEach(input => {
      // [js_truthiness: explicit empty check, not falsy check]
      if (input.value.trim() === '') {
        errors[input.name] = 'This field is required';
      }
    });
    formEl.querySelectorAll('[data-type="email"]').forEach(input => {
      // [js_string_ops: test() not match() for boolean check]
      if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(input.value)) {
        errors[input.name] = 'Please enter a valid email';
      }
    });
    formEl.querySelectorAll('[data-minlength]').forEach(input => {
      // [js_numeric: parseInt with radix 10]
      const min = parseInt(input.dataset.minlength, 10);
      if (input.value.length < min) {
        errors[input.name] = `Must be at least ${min} characters`;
      }
    });
    return errors;
  };

  const attachTo = (formEl, onSuccess) => {
    formEl.addEventListener('submit', async (e) => {
      e.preventDefault();
      const errors = validate(formEl);
      // [js_collections: Object.keys not len()]
      if (Object.keys(errors).length > 0) {
        displayErrors(formEl, errors);
        return;
      }
      if (onSuccess != null) await onSuccess(formEl);
    });
  };

  const displayErrors = (formEl, errors) => {
    // [ScopingAnalyzer: const in for...of]
    for (const [name, msg] of Object.entries(errors)) {
      const input = formEl.querySelector(`[name="${name}"]`);
      // [js_prototype: in operator checks property, not value membership]
      if (input != null) {
        input.setAttribute('aria-invalid', 'true');
        const errEl = formEl.querySelector(`[data-error-for="${name}"]`);
        if (errEl != null) errEl.textContent = msg;
      }
    }
  };

  return { validate, attachTo };
})();
"""

    def _generate_interactions_js(self, spec: dict) -> str:
        domain_nouns = spec.get("domain_nouns", [])
        noun = domain_nouns[0].capitalize() if domain_nouns else "App"

        return f"""\
// Generated by jugeo JSGenerator
// Theory: ScopingAnalyzer, THIS_BINDING_ANALYSES, js_truthiness
// [ScopingAnalyzer: const, IIFE pattern for encapsulation]
const {noun}Interactions = (() => {{
  // [THIS_BINDING_ANALYSES: arrow functions throughout]
  const init = () => {{
    document.querySelectorAll('[data-action="delete"]').forEach(btn => {{
      btn.addEventListener('click', async (e) => {{
        e.preventDefault();
        // [js_truthiness: explicit comparison not truthiness]
        if (confirm('Are you sure?') !== true) return;
        const url = btn.dataset.url ?? btn.closest('form')?.action;
        // [js_prototype: != null catches both null and undefined]
        if (url == null) return;
        try {{
          await CSRF.del(url);
          // [js_collections: closest() returns null not undefined on miss]
          const row = btn.closest('[data-item]');
          if (row != null) row.remove();
        }} catch (err) {{
          console.error('Delete failed:', err);
        }}
      }});
    }});
  }};
  return {{ init }};
}})();

document.addEventListener('DOMContentLoaded', {noun}Interactions.init);
"""

    def _verify_generated_js(self, code: str) -> list[str]:
        violations: list[str] = []

        if _THEORY:
            try:
                scanner = TranspilationHazardScanner()
                # Strip JS line comments before scanning: // is floor-division in Python
                # but a comment delimiter in JS, causing false positives.
                code_no_comments = re.sub(r'//[^\n]*', '', code)
                hazards = scanner.scan(code_no_comments)
                violations.extend(hazards)
            except Exception:
                pass

            try:
                analyzer = ScopingAnalyzer()
                scoping_issues = analyzer.detect_var_in_loop(code)
                violations.extend(scoping_issues)
            except Exception:
                pass

        # Static check: no bare `var ` outside comments or strings
        stripped = re.sub(r'//[^\n]*', '', code)
        stripped = re.sub(r'/\*.*?\*/', '', stripped, flags=re.DOTALL)
        stripped = re.sub(r'"[^"\\]*(?:\\.[^"\\]*)*"', '""', stripped)
        stripped = re.sub(r"'[^'\\]*(?:\\.[^'\\]*)*'", "''", stripped)
        stripped = re.sub(r'`[^`\\]*(?:\\.[^`\\]*)*`', '``', stripped)

        if re.search(r'\bvar\s', stripped):
            violations.append("ScopingAnalyzer: 'var' keyword detected — use const/let only")

        return violations
