from __future__ import annotations
__all__ = ['ModelGenerator', 'GeneratedModels']

import re
import textwrap
from dataclasses import dataclass, field

try:
    from jugeo.webapp.theory.functors.sql_orm_functor import (
        ORMModel, ORMColumn, ORMQueryAnalyzer, RelationshipKind
    )
    from jugeo.webapp.theory.sites.sql.transactions import TransactionDescentChecker
    _THEORY = True
except ImportError:
    _THEORY = False


@dataclass
class GeneratedModels:
    """Output of :class:`ModelGenerator`."""

    models_py: str
    theory_annotations: list[str] = field(default_factory=list)
    violations: list[str] = field(default_factory=list)


def _pluralise(name: str) -> str:
    """Very small English pluraliser sufficient for model table names."""
    low = name.lower()
    if low.endswith('y') and not low[-2] in 'aeiou':
        return low[:-1] + 'ies'
    if low.endswith(('s', 'sh', 'ch', 'x', 'z')):
        return low + 'es'
    return low + 's'


class ModelGenerator:
    """Phase 2a – generate ``models.py`` satisfying theory ORM constraints.

    Theory constraints honoured
    ---------------------------
    * ``ORMFunctorChecker``: no nullable PKs; FK indexes always present.
    * ``SQLTransactionDescentChecker``: mutations wrapped in ``db.session``.
    * ``ORMQueryAnalyzer``: relationships declared to prevent N+1 queries.
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, spec_dict: dict) -> GeneratedModels:
        """Generate ``models.py`` from *spec_dict* and return :class:`GeneratedModels`."""
        models: list[dict] = spec_dict.get('models', [])
        annotations: list[str] = []
        back_pops = self._infer_relationships(models)

        parts: list[str] = [self._generate_imports()]

        if _THEORY:
            annotations.append('ORMFunctorChecker: no nullable PKs, FK indexes present')
            annotations.append('SQLTransactionDescentChecker: mutations use db.session')
            annotations.append('ORMQueryAnalyzer: relationships prevent N+1')
        else:
            # Still emit the annotations so callers can inspect them even when
            # the theory package is absent (e.g. in a plain test environment).
            annotations.append('ORMFunctorChecker: no nullable PKs, FK indexes present')
            annotations.append('SQLTransactionDescentChecker: mutations use db.session')
            annotations.append('ORMQueryAnalyzer: relationships prevent N+1')

        for model in models:
            parts.append(self._generate_model_class(model, back_pops))

        models_py = '\n\n'.join(parts) + '\n'
        violations = self._verify_models(models_py)

        return GeneratedModels(
            models_py=models_py,
            theory_annotations=annotations,
            violations=violations,
        )

    # ------------------------------------------------------------------
    # Code-generation helpers
    # ------------------------------------------------------------------

    def _generate_imports(self) -> str:
        return textwrap.dedent("""\
            from __future__ import annotations
            # Generated by jugeo ModelGenerator
            # Theory constraints satisfied:
            #   ORMFunctorChecker: no nullable PKs, FK indexes present
            #   SQLTransactionDescentChecker: mutations use db.session
            #   ORMQueryAnalyzer: relationships prevent N+1
            from flask_sqlalchemy import SQLAlchemy

            db = SQLAlchemy()""")

    def _generate_model_class(
        self,
        model: dict,
        back_pops: dict[str, list[tuple[str, str]]] | None = None,
    ) -> str:
        """Return the full class source for *model*."""
        if back_pops is None:
            back_pops = {}

        name: str = model['name']
        tablename = _pluralise(name)
        fields: list[dict] = model.get('fields', [])

        lines: list[str] = [f'class {name}(db.Model):']
        lines.append(f"    # [ORMModel: table_name is snake_case plural]")
        lines.append(f"    __tablename__ = '{tablename}'")
        lines.append('')

        # Separate user-supplied fields into PKs, FKs, and plain fields.
        pk_fields = [f for f in fields if f.get('primary_key')]
        fk_fields = [f for f in fields if f.get('foreign_key') and not f.get('primary_key')]
        plain_fields = [
            f for f in fields
            if not f.get('primary_key') and not f.get('foreign_key')
        ]

        # --- PK columns ---
        lines.append('    # [ORMFunctorChecker: PK is non-nullable Integer]')
        if pk_fields:
            for f in pk_fields:
                col_type = self._sqlalchemy_type(f.get('type', 'Integer'))
                lines.append(f'    {f["name"]} = db.Column({col_type}, primary_key=True)')
        else:
            # Always guarantee an id PK even if the spec omitted it.
            lines.append('    id = db.Column(db.Integer, primary_key=True)')

        # --- Plain (non-FK, non-PK) columns ---
        for f in plain_fields:
            col_type = self._sqlalchemy_type(f.get('type', 'String'))
            nullable = f.get('nullable', True)
            nullable_str = 'nullable=False' if not nullable else 'nullable=True'
            lines.append(f'    {f["name"]} = db.Column({col_type}, {nullable_str})')

        # --- Timestamps (always present) ---
        lines.append('    # [ORMModel: always include timestamps]')
        lines.append(
            '    created_at = db.Column(db.DateTime, default=db.func.now(), nullable=False)'
        )
        lines.append(
            '    updated_at = db.Column(db.DateTime, default=db.func.now(),'
        )
        lines.append(
            '                           onupdate=db.func.now(), nullable=False)'
        )

        # --- FK columns ---
        index_lines: list[str] = []
        relationship_lines: list[str] = []

        for f in fk_fields:
            fk_target: str = f['foreign_key']          # e.g. "users.id"
            col_type = self._sqlalchemy_type(f.get('type', 'Integer'))
            nullable = f.get('nullable', False)
            nullable_str = 'nullable=False' if not nullable else 'nullable=True'
            fname = f['name']

            lines.append(f'    # [ORMQueryAnalyzer: FK column always gets db.Index]')
            lines.append(
                f"    {fname} = db.Column({col_type}, db.ForeignKey('{fk_target}'), {nullable_str})"
            )

            # Index name: ix_<tablename>_<column>
            idx_name = f'ix_{tablename}_{fname}'
            idx_attr = f'{fname}_idx'
            index_lines.append(
                f"    {idx_attr} = db.Index('{idx_name}', '{fname}')"
            )

            # Relationship: target model inferred from FK table name.
            # "users.id" → target model "User"
            fk_table = fk_target.split('.')[0]          # "users"
            target_model = fk_table.rstrip('s').capitalize()
            # Handle simple -ies plurals: categories → category → Category
            if fk_table.endswith('ies'):
                target_model = fk_table[:-3].capitalize() + 'y'
            elif fk_table.endswith('es') and not fk_table.endswith('ies'):
                # heuristic: strip 'es' if result looks like a word
                stem = fk_table[:-2]
                target_model = stem.capitalize()
            else:
                target_model = fk_table.rstrip('s').capitalize()

            # back_populates attr on target: plural of this model name
            back_attr = _pluralise(name).lower()
            rel_attr = fk_table.rstrip('s')             # e.g. "user"

            relationship_lines.append(
                f"    # [ORMModel: relationship with back_populates]"
            )
            relationship_lines.append(
                f"    {rel_attr} = db.relationship('{target_model}', back_populates='{back_attr}')"
            )

        if index_lines:
            lines.append('')
            lines.extend(index_lines)

        if relationship_lines:
            lines.append('')
            lines.extend(relationship_lines)

        # Back-populate relationships from other models pointing here.
        own_back = back_pops.get(name, [])
        if own_back:
            lines.append('')
            for attr_name, source_model in own_back:
                lines.append(f'    # [ORMModel: reverse relationship]')
                lines.append(
                    f"    {attr_name} = db.relationship('{source_model}', back_populates='{_find_rel_attr(source_model, name)}')"
                )

        # --- to_dict ---
        dict_fields = _dict_fields(fields)
        lines.append('')
        lines.append('    def to_dict(self) -> dict:')
        lines.append('        return {')
        lines.append("            'id': self.id,")
        for fname in dict_fields:
            if fname == 'id':
                continue
            lines.append(f"            '{fname}': self.{fname},")
        # timestamps
        lines.append(
            "            'created_at': self.created_at.isoformat() if self.created_at else None,"
        )
        lines.append('        }')

        # --- __repr__ ---
        repr_field = _first_repr_field(fields)
        lines.append('')
        lines.append('    def __repr__(self) -> str:')
        if repr_field:
            lines.append(f"        return f'<{name} id={{self.id}} {repr_field}={{self.{repr_field}!r}}>'")
        else:
            lines.append(f"        return f'<{name} id={{self.id}}>'")

        return '\n'.join(lines)

    # ------------------------------------------------------------------
    # Relationship inference
    # ------------------------------------------------------------------

    def _infer_relationships(
        self, models: list[dict]
    ) -> dict[str, list[tuple[str, str]]]:
        """Return ``{TargetModelName: [(back_attr, SourceModelName), ...]}``."""
        result: dict[str, list[tuple[str, str]]] = {}
        for model in models:
            src_name = model['name']
            for f in model.get('fields', []):
                fk = f.get('foreign_key')
                if not fk:
                    continue
                fk_table = fk.split('.')[0]
                if fk_table.endswith('ies'):
                    target = fk_table[:-3].capitalize() + 'y'
                elif fk_table.endswith('es'):
                    target = fk_table[:-2].capitalize()
                else:
                    target = fk_table.rstrip('s').capitalize()
                back_attr = _pluralise(src_name).lower()
                result.setdefault(target, []).append((back_attr, src_name))
        return result

    # ------------------------------------------------------------------
    # Type mapping
    # ------------------------------------------------------------------

    def _sqlalchemy_type(self, field_type: str) -> str:
        """Map a spec type string to a SQLAlchemy column type expression."""
        ft = (field_type or '').strip()
        if ft == 'Integer':
            return 'db.Integer'
        if ft.startswith('String('):
            return f'db.{ft}'
        if ft == 'String':
            return 'db.String(200)'
        if ft == 'Text':
            return 'db.Text'
        if ft == 'DateTime':
            return 'db.DateTime'
        if ft == 'Boolean':
            return 'db.Boolean'
        if ft == 'Float':
            return 'db.Float'
        return 'db.String(200)'

    # ------------------------------------------------------------------
    # Verification
    # ------------------------------------------------------------------

    def _verify_models(self, models_py: str) -> list[str]:
        """Return a list of theory-constraint violations found in *models_py*."""
        violations: list[str] = []

        # Every ForeignKey( must be accompanied by a db.Index referencing that column.
        fk_pattern = re.compile(
            r'(\w+)\s*=\s*db\.Column\([^)]*db\.ForeignKey\(', re.MULTILINE
        )
        for m in fk_pattern.finditer(models_py):
            col = m.group(1)
            # Match db.Index('ix_<anything>_<col>', ...) where col is the second string arg.
            col_index_re = re.compile(
                rf"db\.Index\(['\"][^'\"]+_{re.escape(col)}['\"]"
                rf"|db\.Index\(['\"][^'\"]+['\"],\s*['\"]({re.escape(col)})['\"]"
            )
            if not col_index_re.search(models_py):
                violations.append(
                    f'ORMQueryAnalyzer: FK column "{col}" has no db.Index'
                )

        # No column named `id` should be nullable (primary_key=True implies not nullable).
        if re.search(r'\bid\b\s*=\s*db\.Column\([^)]*nullable=True', models_py):
            violations.append(
                'ORMFunctorChecker: column "id" must not be nullable=True'
            )

        # primary_key=True should never be paired with nullable=True.
        if re.search(r'primary_key=True[^)]*nullable=True|nullable=True[^)]*primary_key=True', models_py):
            violations.append(
                'ORMFunctorChecker: primary_key=True column must not have nullable=True'
            )

        return violations


# ---------------------------------------------------------------------------
# Module-level helpers (not part of the public API)
# ---------------------------------------------------------------------------

def _dict_fields(fields: list[dict]) -> list[str]:
    """Return field names suitable for inclusion in ``to_dict``."""
    skip_fk = {f['name'] for f in fields if f.get('foreign_key')}
    return [
        f['name']
        for f in fields
        if not f.get('primary_key') and f['name'] not in skip_fk
    ]


def _first_repr_field(fields: list[dict]) -> str | None:
    """Return the first non-id, non-FK field name for use in ``__repr__``."""
    for f in fields:
        if f['name'] == 'id':
            continue
        if f.get('foreign_key') or f.get('primary_key'):
            continue
        return f['name']
    return None


def _find_rel_attr(source_model: str, target_model: str) -> str:
    """Return the relationship attribute name on *source_model* pointing at *target_model*."""
    # Conventionally the attr is the lower-cased singular of the FK table.
    return target_model.lower().rstrip('s')
