from __future__ import annotations

"""Theory2.tex Ch8 §8.1 — Project Sites. A project is modelled as a semantic site: a small
category whose objects are coordinate objects (modules, classes, functions) and whose morphisms
are dependency/inclusion arrows, equipped with a Grothendieck topology generated by module
covers. copilot: shared-core §8.1 implementation — project site machinery for LLM-assisted
verification."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Iterator, Callable, Sequence
import time
import uuid
import math
import hashlib
import json
import collections
import itertools

from jugeo.geometry.hypercovers import HypercoverLevel, CechNerve, HypercoverKind
from jugeo.geometry.descent import DescentEngine, DescentResult, LocalSection, GluingData
from jugeo.geometry.site import CoordinateObject, SemanticSite, CoordinateKind
from jugeo.geometry.covers import Cover, CoverMetric
from jugeo.judgments.judgment_terms import JudgmentTerm, JudgmentKind
from jugeo.evidence.certificates import Certificate, CertificateStatus
from jugeo.foundations.project_hypercovers.models import (
    ProjectSite, ModuleCover, FleetMember, HypercoverDecomposition,
    ProjectKind, CoverStrategy, FleetStatus, DecompositionStatus,
    CoordinateMorphism, OverlapCell, CohomologyClass, TrustTier,
)


@dataclass(slots=True)
class CoordinateRegistry:
    """Registry of all coordinates in a project site.

    Acts as a fast-lookup store with indexing by kind, depth, and name prefix.
    Theory2.tex §8.1. Coordinates are keyed by their dot-separated path string
    (e.g. ``"jugeo.geometry.site"``), which serves as the canonical identifier
    throughout the site machinery. The registry maintains four complementary
    indices so that all lookup patterns needed by topology generators and
    inspectors run in sub-linear time after an initial O(n) build.

    Parameters
    ----------
    _by_id : dict[str, CoordinateObject]
        Primary index: coord_key -> CoordinateObject.
    _by_kind : dict[str, list[str]]
        Secondary index: CoordinateKind.value -> list of coord_keys.
    _by_prefix : dict[str, list[str]]
        Prefix index: parent prefix -> list of coord_keys.
    _depth_index : dict[int, list[str]]
        Depth index: depth integer -> list of coord_keys.

    Notes
    -----
    All four indices are kept in sync by ``register`` and ``unregister``.
    The ``_by_prefix`` key for a top-level module (no dot in key) is the empty
    string ``""``, which collects all root-level coordinates.

    Examples
    --------
    >>> reg = CoordinateRegistry()
    >>> coord = CoordinateObject(components=("jugeo", "geometry", "site"), kind=CoordinateKind.MODULE, metadata={})
    >>> reg.register(coord)
    >>> reg.count()
    1
    >>> reg.get("jugeo.geometry.site") is coord
    True
    """

    _by_id: dict[str, CoordinateObject] = field(default_factory=dict)
    _by_kind: dict[str, list[str]] = field(default_factory=dict)
    _by_prefix: dict[str, list[str]] = field(default_factory=dict)
    _depth_index: dict[int, list[str]] = field(default_factory=dict)

    def register(self, coord: CoordinateObject) -> None:
        """Add a coordinate object to all registry indices.

        Parameters
        ----------
        coord : CoordinateObject
            The coordinate to register. Its ``key`` attribute is used as the
            canonical identifier across all indices. If a coordinate with the
            same key already exists, it is silently overwritten.

        Returns
        -------
        None

        Notes
        -----
        The prefix is computed as the dot-joined components minus the final
        component. A top-level module such as ``"jugeo"`` gets an empty-string
        prefix ``""``. All four indices are updated atomically within the method.

        Examples
        --------
        >>> reg = CoordinateRegistry()
        >>> coord = CoordinateObject(components=("a", "b"), kind=CoordinateKind.MODULE, metadata={})
        >>> reg.register(coord)
        >>> reg.contains("a.b")
        True
        """
        key = coord.key
        self._by_id[key] = coord

        kind_val = coord.kind.value
        if kind_val not in self._by_kind:
            self._by_kind[kind_val] = []
        if key not in self._by_kind[kind_val]:
            self._by_kind[kind_val].append(key)

        parts = key.split(".")
        prefix = ".".join(parts[:-1])
        if prefix not in self._by_prefix:
            self._by_prefix[prefix] = []
        if key not in self._by_prefix[prefix]:
            self._by_prefix[prefix].append(key)

        depth = coord.depth
        if depth not in self._depth_index:
            self._depth_index[depth] = []
        if key not in self._depth_index[depth]:
            self._depth_index[depth].append(key)

    def unregister(self, coord_id: str) -> bool:
        """Remove a coordinate from all registry indices.

        Parameters
        ----------
        coord_id : str
            The key of the coordinate to remove (dot-separated path).

        Returns
        -------
        bool
            ``True`` if the coordinate was present and removed; ``False`` if
            no coordinate with that key existed.

        Notes
        -----
        All four indices are cleaned up. Stale empty lists are left in place
        to avoid repeated dict key creation on re-registration.

        Examples
        --------
        >>> reg = CoordinateRegistry()
        >>> coord = CoordinateObject(components=("x",), kind=CoordinateKind.MODULE, metadata={})
        >>> reg.register(coord)
        >>> reg.unregister("x")
        True
        >>> reg.unregister("x")
        False
        """
        if coord_id not in self._by_id:
            return False
        coord = self._by_id.pop(coord_id)

        kind_val = coord.kind.value
        if kind_val in self._by_kind and coord_id in self._by_kind[kind_val]:
            self._by_kind[kind_val].remove(coord_id)

        parts = coord_id.split(".")
        prefix = ".".join(parts[:-1])
        if prefix in self._by_prefix and coord_id in self._by_prefix[prefix]:
            self._by_prefix[prefix].remove(coord_id)

        depth = coord.depth
        if depth in self._depth_index and coord_id in self._depth_index[depth]:
            self._depth_index[depth].remove(coord_id)

        return True

    def get(self, coord_id: str) -> CoordinateObject | None:
        """Return the coordinate for the given id, or None if absent.

        Parameters
        ----------
        coord_id : str
            The dot-separated path key to look up.

        Returns
        -------
        CoordinateObject | None
            The matching coordinate, or ``None``.

        Examples
        --------
        >>> reg = CoordinateRegistry()
        >>> reg.get("nonexistent") is None
        True
        """
        return self._by_id.get(coord_id)

    def get_by_kind(self, kind: CoordinateKind) -> list[CoordinateObject]:
        """Return all coordinates with the given kind.

        Parameters
        ----------
        kind : CoordinateKind
            The kind to filter by (e.g. ``CoordinateKind.MODULE``).

        Returns
        -------
        list[CoordinateObject]
            Possibly-empty list of all registered coordinates of that kind.

        Notes
        -----
        The lookup is O(k) where k is the number of coordinates of that kind,
        since the kind index stores only keys and a second dict lookup is needed
        per entry.

        Examples
        --------
        >>> reg = CoordinateRegistry()
        >>> coords = reg.get_by_kind(CoordinateKind.FUNCTION)
        >>> isinstance(coords, list)
        True
        """
        keys = self._by_kind.get(kind.value, [])
        return [self._by_id[k] for k in keys if k in self._by_id]

    def get_by_prefix(self, prefix: str) -> list[CoordinateObject]:
        """Return all coordinates whose key starts with the given prefix.

        Parameters
        ----------
        prefix : str
            Dot-separated prefix to match. For example ``"jugeo.geometry"``
            will return ``"jugeo.geometry.site"``, ``"jugeo.geometry.covers"``,
            etc.

        Returns
        -------
        list[CoordinateObject]
            All registered coordinates whose key begins with *prefix* followed
            by a dot, or equals *prefix* exactly.

        Notes
        -----
        This method scans all registered ids rather than relying solely on the
        ``_by_prefix`` index, because the index stores only *exact* parent
        prefixes. A multi-level prefix lookup therefore requires the linear
        scan to handle grandchildren and deeper descendants correctly.

        Examples
        --------
        >>> reg = CoordinateRegistry()
        >>> reg.get_by_prefix("jugeo.geometry")
        []
        """
        results = []
        for cid, coord in self._by_id.items():
            if cid == prefix or cid.startswith(prefix + "."):
                results.append(coord)
        return results

    def get_at_depth(self, depth: int) -> list[CoordinateObject]:
        """Return all coordinates at a specific depth level.

        Parameters
        ----------
        depth : int
            Number of dot-separated components in the key (e.g. depth 3 for
            ``"jugeo.geometry.site"``).

        Returns
        -------
        list[CoordinateObject]
            All registered coordinates at that depth.

        Examples
        --------
        >>> reg = CoordinateRegistry()
        >>> reg.get_at_depth(0)
        []
        """
        keys = self._depth_index.get(depth, [])
        return [self._by_id[k] for k in keys if k in self._by_id]

    def all_ids(self) -> list[str]:
        """Return all registered coordinate keys.

        Returns
        -------
        list[str]
            Snapshot of all currently registered keys.
        """
        return list(self._by_id.keys())

    def all_coords(self) -> list[CoordinateObject]:
        """Return all registered coordinate objects.

        Returns
        -------
        list[CoordinateObject]
            Snapshot of all currently registered coordinates.
        """
        return list(self._by_id.values())

    def count(self) -> int:
        """Return the total number of registered coordinates.

        Returns
        -------
        int
            Number of entries in the primary index.
        """
        return len(self._by_id)

    def contains(self, coord_id: str) -> bool:
        """Check whether a coordinate id is registered.

        Parameters
        ----------
        coord_id : str
            The key to test.

        Returns
        -------
        bool
            ``True`` iff the key is present.
        """
        return coord_id in self._by_id

    def find(self, predicate: Callable[[CoordinateObject], bool]) -> list[CoordinateObject]:
        """Return all coordinates satisfying a predicate.

        Parameters
        ----------
        predicate : Callable[[CoordinateObject], bool]
            A callable that receives a ``CoordinateObject`` and returns
            ``True`` for those that should be included.

        Returns
        -------
        list[CoordinateObject]
            All coordinates for which *predicate* returns ``True``.

        Notes
        -----
        This is a linear scan over all registered coordinates. For large
        registries and repeated queries, consider materializing the filtered
        list and caching it externally.

        Examples
        --------
        >>> reg = CoordinateRegistry()
        >>> reg.find(lambda c: c.depth > 2)
        []
        """
        return [c for c in self._by_id.values() if predicate(c)]

    def clear(self) -> None:
        """Remove all coordinates from every index.

        Returns
        -------
        None

        Notes
        -----
        After calling ``clear``, ``count()`` returns 0 and all index dicts are
        empty. This is useful for resetting a builder between successive
        ``build`` calls.
        """
        self._by_id.clear()
        self._by_kind.clear()
        self._by_prefix.clear()
        self._depth_index.clear()

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable summary of the registry.

        Returns
        -------
        dict[str, Any]
            Contains ``total``, ``by_kind`` (kind value -> count),
            ``by_depth`` (depth str -> count), and ``ids`` (list of all keys).

        Notes
        -----
        The returned dict is intended for logging and diagnostics; it omits
        full coordinate metadata to keep the payload small.
        """
        by_kind = {k: len(v) for k, v in self._by_kind.items()}
        by_depth = {str(d): len(v) for d, v in self._depth_index.items()}
        return {
            "total": self.count(),
            "by_kind": by_kind,
            "by_depth": by_depth,
            "ids": self.all_ids(),
        }


@dataclass(slots=True)
class TopologyGenerator:
    """Computes the Grothendieck topology on a project site from the import (dependency) graph.

    For each coordinate, produces the set of covering families according to
    the chosen strategy. Theory2.tex §8.1, Def 8.4. A Grothendieck topology
    on the site category ``C`` is an assignment ``J(U)`` of *sieves* (here
    represented as lists of coord-id lists) to each object ``U`` such that the
    maximality, stability, and transitivity axioms hold. This class computes
    an approximation suitable for LLM-assisted project analysis.

    Parameters
    ----------
    strategy : CoverStrategy
        The algorithm used to derive covering families. Defaults to GREEDY.
    min_cover_size : int
        Minimum cardinality of any non-identity covering family. Defaults to 1.
    max_cover_size : int
        Maximum number of coordinates allowed in a single covering family.
        Defaults to 20.
    _topology_cache : dict[str, list[list[str]]]
        Internal cache keyed by site_id to avoid recomputing stable topologies.

    Notes
    -----
    The identity cover ``[coord_id]`` is always included for every coordinate
    to satisfy the maximality axiom of Grothendieck topologies.

    Examples
    --------
    >>> gen = TopologyGenerator(strategy=CoverStrategy.GREEDY)
    >>> gen.strategy
    <CoverStrategy.GREEDY: ...>
    """

    strategy: CoverStrategy = CoverStrategy.GREEDY
    min_cover_size: int = 1
    max_cover_size: int = 20
    _topology_cache: dict[str, list[list[str]]] = field(default_factory=dict)

    def generate(self, site: ProjectSite) -> dict[str, list[list[str]]]:
        """Generate the Grothendieck topology for the given project site.

        Parameters
        ----------
        site : ProjectSite
            The site whose topology should be computed. All coordinates and
            morphisms present at call time are used.

        Returns
        -------
        dict[str, list[list[str]]]
            Mapping from coord_id to list of covering families. Each covering
            family is a list of coord_ids.

        Notes
        -----
        The result is cached in ``_topology_cache`` keyed by ``site.site_id``.
        Repeated calls for the same site_id return the cached result without
        recomputation. To force regeneration, call ``clear_cache`` first.

        Examples
        --------
        >>> gen = TopologyGenerator()
        >>> # site = build_project_site(...)
        >>> # topo = gen.generate(site)
        """
        if site.site_id in self._topology_cache:
            return self._topology_cache[site.site_id]
        topology: dict[str, list[list[str]]] = {}
        for coord_id, coord in site.coordinates.items():
            families = self._generate_for_coord(coord, site)
            topology[coord_id] = families
        self._topology_cache[site.site_id] = topology
        return topology

    def _generate_for_coord(
        self, coord: CoordinateObject, site: ProjectSite
    ) -> list[list[str]]:
        """Compute the covering families for a single coordinate.

        Parameters
        ----------
        coord : CoordinateObject
            The coordinate whose covering families are being computed.
        site : ProjectSite
            The ambient site providing morphism and topology information.

        Returns
        -------
        list[list[str]]
            A list of covering families. Each family is a list of coord_ids.
            The identity cover ``[coord.key]`` is always included as the first
            element.

        Notes
        -----
        Strategy dispatch:

        * **GREEDY** — builds a cover from the immediate outgoing morphism
          targets plus the coord itself.
        * **HIERARCHICAL** — groups all sibling coordinates (same parent prefix)
          into one cover.
        * **DEPENDENCY** — BFS up to ``max_cover_size`` hops.
        * **SEMANTIC** — identical to GREEDY for unknown strategies.
        """
        identity_cover = [coord.key]
        families: list[list[str]] = [identity_cover]

        if self.strategy in (CoverStrategy.GREEDY, CoverStrategy.SEMANTIC):
            outgoing = site.get_outgoing_morphisms(coord.key)
            dep_cover: list[str] = [coord.key]
            for morph in outgoing:
                if site.get_coordinate(morph.target_id) is not None:
                    dep_cover.append(morph.target_id)
            if len(dep_cover) > 1:
                families.append(dep_cover[: self.max_cover_size])

        elif self.strategy == CoverStrategy.HIERARCHICAL:
            parts = coord.key.split(".")
            parent_prefix = ".".join(parts[:-1])
            sibling_family: list[str] = []
            for cid in site.coordinates:
                if parent_prefix == "":
                    if "." not in cid:
                        sibling_family.append(cid)
                else:
                    cid_prefix = ".".join(cid.split(".")[:-1])
                    if cid_prefix == parent_prefix:
                        sibling_family.append(cid)
            if len(sibling_family) > 1 or (
                len(sibling_family) == 1 and sibling_family[0] != coord.key
            ):
                families.append(sibling_family[: self.max_cover_size])

        elif self.strategy == CoverStrategy.DEPENDENCY:
            visited: set[str] = {coord.key}
            queue: collections.deque[str] = collections.deque([coord.key])
            bfs_cover: list[str] = [coord.key]
            while queue and len(bfs_cover) < self.max_cover_size:
                current = queue.popleft()
                for morph in site.get_outgoing_morphisms(current):
                    tid = morph.target_id
                    if tid not in visited and site.get_coordinate(tid) is not None:
                        visited.add(tid)
                        bfs_cover.append(tid)
                        queue.append(tid)
            if len(bfs_cover) > 1:
                families.append(bfs_cover)

        else:
            outgoing = site.get_outgoing_morphisms(coord.key)
            dep_cover = [coord.key] + [
                morph.target_id
                for morph in outgoing
                if site.get_coordinate(morph.target_id) is not None
            ]
            if len(dep_cover) > 1:
                families.append(dep_cover[: self.max_cover_size])

        return families

    def validate_topology(
        self, topology: dict[str, list[list[str]]], site: ProjectSite
    ) -> list[str]:
        """Check whether a topology satisfies basic Grothendieck axioms.

        Parameters
        ----------
        topology : dict[str, list[list[str]]]
            The topology to validate, as returned by ``generate``.
        site : ProjectSite
            The site the topology was computed for.

        Returns
        -------
        list[str]
            A list of violation strings. An empty list means the topology is
            valid with respect to the checks performed.

        Raises
        ------
        TypeError
            If ``topology`` or ``site`` are not of the expected types.

        Notes
        -----
        Checks performed:

        1. Every coord in ``site.coordinates`` appears as a key in *topology*.
        2. Every coord has at least one covering family.
        3. Every coord has an identity cover (a family containing only that
           coord's key) somewhere in its family list.
        """
        violations: list[str] = []
        for coord_id in site.coordinates:
            if coord_id not in topology:
                violations.append(f"Coord '{coord_id}' missing from topology")
                continue
            families = topology[coord_id]
            if not families:
                violations.append(f"Coord '{coord_id}' has no covering families")
                continue
            has_identity = any(
                len(fam) == 1 and fam[0] == coord_id for fam in families
            )
            if not has_identity:
                violations.append(
                    f"Coord '{coord_id}' lacks an identity cover ['{coord_id}']"
                )
        return violations

    def clear_cache(self) -> None:
        """Discard all cached topology results.

        Returns
        -------
        None

        Notes
        -----
        After clearing, the next call to ``generate`` will recompute the full
        topology from scratch, which may be expensive for large sites.
        """
        self._topology_cache.clear()

    def compute_covering_dimension(
        self, topology: dict[str, list[list[str]]]
    ) -> int:
        """Compute the covering dimension of the topology.

        The covering dimension is the minimum over all coordinates of the
        minimum covering-family size for that coordinate.

        Parameters
        ----------
        topology : dict[str, list[list[str]]]
            A topology dict as returned by ``generate``.

        Returns
        -------
        int
            The covering dimension, or 0 if the topology is empty.

        Notes
        -----
        This is an approximation of the sheaf-theoretic covering dimension;
        a value of 1 corresponds to a topology in which every object is covered
        by a singletonFamily (the identity cover), which is always present.
        """
        if not topology:
            return 0
        min_dim = math.inf
        for families in topology.values():
            if not families:
                continue
            min_size = min(len(fam) for fam in families)
            if min_size < min_dim:
                min_dim = min_size
        return int(min_dim) if min_dim != math.inf else 0

    def summarize(self, topology: dict[str, list[list[str]]]) -> dict[str, Any]:
        """Return a statistical summary of a topology.

        Parameters
        ----------
        topology : dict[str, list[list[str]]]
            The topology to summarize.

        Returns
        -------
        dict[str, Any]
            Keys: ``total_coords``, ``total_families``, ``avg_families_per_coord``,
            ``avg_family_size``, ``covering_dimension``, ``strategy``.

        Notes
        -----
        ``avg_family_size`` is the mean cardinality across all families in the
        entire topology (not per-coordinate). ``covering_dimension`` uses
        ``compute_covering_dimension``.
        """
        total_coords = len(topology)
        all_families = [fam for fams in topology.values() for fam in fams]
        total_families = len(all_families)
        avg_families_per_coord = (
            total_families / total_coords if total_coords > 0 else 0.0
        )
        avg_family_size = (
            sum(len(f) for f in all_families) / total_families
            if total_families > 0
            else 0.0
        )
        return {
            "total_coords": total_coords,
            "total_families": total_families,
            "avg_families_per_coord": round(avg_families_per_coord, 3),
            "avg_family_size": round(avg_family_size, 3),
            "covering_dimension": self.compute_covering_dimension(topology),
            "strategy": self.strategy.value if hasattr(self.strategy, "value") else str(self.strategy),
        }


@dataclass(slots=True)
class SemanticSiteBuilder:
    """Builds a ProjectSite from a codebase description.

    Accepts a list of module names, their import relationships, and optional
    ``CoordinateKind`` annotations, then assembles a fully-indexed
    ``ProjectSite`` with a Grothendieck topology computed by the chosen
    strategy. Theory2.tex §8.1.

    Parameters
    ----------
    registry : CoordinateRegistry
        Internal registry used to accumulate coordinate objects before the
        final ``build`` call.
    topology_generator : TopologyGenerator
        Generator used to derive the Grothendieck topology when ``build`` is
        called.
    _pending_morphisms : list[tuple[str, str, str]]
        Buffer of ``(source_name, target_name, morphism_kind)`` triples added
        via ``add_dependency``. Resolved into ``CoordinateMorphism`` objects
        during ``build``.

    Notes
    -----
    The builder is stateful: calling ``build`` does *not* reset the builder.
    To reuse the builder for a second site, call ``reset`` first. This design
    allows incremental construction where modules and dependencies are added
    in multiple passes.

    Examples
    --------
    >>> builder = SemanticSiteBuilder()
    >>> builder.add_module("mylib.core")
    >>> builder.add_module("mylib.utils")
    >>> builder.add_dependency("mylib.core", "mylib.utils")
    >>> site = builder.build("mylib")
    >>> site.name
    'mylib'
    """

    registry: CoordinateRegistry = field(default_factory=CoordinateRegistry)
    topology_generator: TopologyGenerator = field(default_factory=TopologyGenerator)
    _pending_morphisms: list[tuple[str, str, str]] = field(default_factory=list)

    def add_module(
        self,
        name: str,
        kind: CoordinateKind = CoordinateKind.MODULE,
        metadata: dict[str, Any] | None = None,
    ) -> CoordinateObject:
        """Create and register a coordinate for the given module name.

        Parameters
        ----------
        name : str
            Dot-separated module path, e.g. ``"jugeo.geometry.site"``.
        kind : CoordinateKind, optional
            The semantic kind of the coordinate. Defaults to MODULE.
        metadata : dict[str, Any] | None, optional
            Optional dict of extra metadata attached to the coordinate.

        Returns
        -------
        CoordinateObject
            The newly created (and registered) coordinate object.

        Notes
        -----
        If a coordinate with the same key has already been registered, it is
        overwritten by the new one. This allows updating the kind or metadata
        of an existing module entry.

        Examples
        --------
        >>> builder = SemanticSiteBuilder()
        >>> coord = builder.add_module("pkg.module")
        >>> coord.key
        'pkg.module'
        """
        coord = CoordinateObject(
            components=tuple(name.split(".")),
            kind=kind,
            metadata=metadata or {},
        )
        self.registry.register(coord)
        return coord

    def add_dependency(
        self,
        source_name: str,
        target_name: str,
        morphism_kind: str = "import",
    ) -> None:
        """Record a dependency edge between two module names.

        Parameters
        ----------
        source_name : str
            Dot-separated key of the depending module.
        target_name : str
            Dot-separated key of the depended-upon module.
        morphism_kind : str, optional
            Semantic label for the arrow, e.g. ``"import"``, ``"calls"``,
            ``"inherits"``. Defaults to ``"import"``.

        Returns
        -------
        None

        Notes
        -----
        The edge is not materialised into a ``CoordinateMorphism`` until
        ``build`` is called; it is stored in ``_pending_morphisms`` as a raw
        triple. This deferred resolution allows adding dependencies before all
        coordinates have been registered.
        """
        self._pending_morphisms.append((source_name, target_name, morphism_kind))

    def add_bulk_modules(
        self,
        names: list[str],
        kind: CoordinateKind = CoordinateKind.MODULE,
    ) -> list[CoordinateObject]:
        """Register multiple modules at once.

        Parameters
        ----------
        names : list[str]
            Sequence of dot-separated module names to register.
        kind : CoordinateKind, optional
            Kind applied uniformly to all modules. Defaults to MODULE.

        Returns
        -------
        list[CoordinateObject]
            List of newly created coordinate objects in the same order as
            *names*.

        Notes
        -----
        This is a convenience wrapper around repeated ``add_module`` calls.
        Mixed-kind bulk registration should be performed via separate calls.
        """
        return [self.add_module(name, kind) for name in names]

    def add_bulk_dependencies(self, edges: list[tuple[str, str]]) -> None:
        """Record multiple dependency edges at once.

        Parameters
        ----------
        edges : list[tuple[str, str]]
            Each element is a ``(source_name, target_name)`` pair. The
            ``morphism_kind`` defaults to ``"import"`` for every edge.

        Returns
        -------
        None
        """
        for src, tgt in edges:
            self.add_dependency(src, tgt)

    def build(
        self,
        project_name: str,
        project_kind: ProjectKind = ProjectKind.LIBRARY,
    ) -> ProjectSite:
        """Assemble the accumulated modules and edges into a ``ProjectSite``.

        Parameters
        ----------
        project_name : str
            Human-readable name for the project site.
        project_kind : ProjectKind, optional
            Classification of the project (LIBRARY, APPLICATION, etc.).
            Defaults to LIBRARY.

        Returns
        -------
        ProjectSite
            A fully constructed project site with coordinates, morphisms, and
            a pre-computed Grothendieck topology.

        Notes
        -----
        The topology is computed immediately after morphism resolution and
        stored on the returned site. The builder's internal state is *not*
        reset after build; call ``reset`` to start fresh.

        Examples
        --------
        >>> builder = SemanticSiteBuilder()
        >>> builder.add_module("a")
        >>> site = builder.build("example")
        >>> site.name
        'example'
        """
        site = ProjectSite(
            site_id=uuid.uuid4().hex,
            name=project_name,
            description=f"Project site for {project_name}",
            project_kind=project_kind,
            cover_strategy=self.topology_generator.strategy,
        )
        for coord in self.registry.all_coords():
            site.add_coordinate(coord)
        self._resolve_morphisms(site)
        site.topology = self.topology_generator.generate(site)
        return site

    def set_strategy(self, strategy: CoverStrategy) -> None:
        """Set the cover strategy used during topology generation.

        Parameters
        ----------
        strategy : CoverStrategy
            The new strategy to apply on subsequent ``build`` calls.

        Returns
        -------
        None
        """
        self.topology_generator.strategy = strategy

    def reset(self) -> None:
        """Clear all accumulated modules and pending morphisms.

        Returns
        -------
        None

        Notes
        -----
        After ``reset``, the builder is in the same state as a freshly
        constructed instance (registry empty, pending morphisms empty). The
        ``topology_generator`` strategy and configuration are preserved.
        """
        self.registry.clear()
        self._pending_morphisms.clear()

    def build_from_dict(self, spec: dict[str, Any]) -> ProjectSite:
        """Build a project site from a plain-dict specification.

        Parameters
        ----------
        spec : dict[str, Any]
            Expected keys:

            * ``"name"`` (str): project name.
            * ``"kind"`` (str, optional): ProjectKind value; defaults to
              ``"LIBRARY"``.
            * ``"modules"`` (list[dict]): each entry has ``"name"`` (str),
              ``"kind"`` (str, optional), and ``"deps"`` (list[str], optional).

        Returns
        -------
        ProjectSite
            The constructed site.

        Raises
        ------
        KeyError
            If the spec is missing the required ``"name"`` key.

        Notes
        -----
        All modules are registered before any dependency edges are resolved,
        so forward-references in ``"deps"`` are handled correctly.

        Examples
        --------
        >>> builder = SemanticSiteBuilder()
        >>> spec = {"name": "myproject", "modules": [{"name": "a", "deps": ["b"]}, {"name": "b"}]}
        >>> site = builder.build_from_dict(spec)
        >>> site.name
        'myproject'
        """
        project_name = spec["name"]
        kind_str = spec.get("kind", "LIBRARY")
        project_kind = ProjectKind[kind_str] if isinstance(kind_str, str) else kind_str

        module_entries = spec.get("modules", [])
        for entry in module_entries:
            mod_name = entry["name"]
            mod_kind_str = entry.get("kind", "MODULE")
            mod_kind = (
                CoordinateKind[mod_kind_str]
                if isinstance(mod_kind_str, str)
                else mod_kind_str
            )
            self.add_module(mod_name, mod_kind, entry.get("metadata"))

        for entry in module_entries:
            src = entry["name"]
            for dep in entry.get("deps", []):
                self.add_dependency(src, dep)

        return self.build(project_name, project_kind)

    def _resolve_morphisms(self, site: ProjectSite) -> None:
        """Resolve pending morphism triples into ``CoordinateMorphism`` objects.

        Parameters
        ----------
        site : ProjectSite
            The site into which morphisms should be inserted. Any missing
            endpoint coordinates are auto-registered.

        Returns
        -------
        None

        Notes
        -----
        If a source or target coordinate referenced in a pending morphism has
        not been added to the site, it is created as a MODULE coordinate and
        inserted automatically. This ensures the dependency graph is complete
        even when partial specifications are given.
        """
        for src, tgt, kind in self._pending_morphisms:
            if site.get_coordinate(src) is None:
                coord = self.add_module(src)
                site.add_coordinate(coord)
            if site.get_coordinate(tgt) is None:
                coord = self.add_module(tgt)
                site.add_coordinate(coord)
            morph = CoordinateMorphism(
                source_id=src,
                target_id=tgt,
                morphism_kind=kind,
            )
            site.add_morphism(morph)


@dataclass(slots=True)
class ProjectSiteInspector:
    """Analyzes and reports on the structure of a project site.

    Covers connectivity, coverage, topology density, and semantic coherence.
    Theory2.tex §8.1. The inspector is a stateful object: call ``set_site`` to
    attach it to a new site before running analysis methods. All analysis
    methods operate purely on the site data and do not mutate it.

    Parameters
    ----------
    site : ProjectSite
        The project site being analyzed. Defaults to a placeholder site; use
        ``set_site`` to attach a real one before calling analysis methods.

    Notes
    -----
    Graph algorithms (Tarjan's SCC, Kahn's topological sort, BFS reachability)
    are implemented directly on the morphism list. For large sites (thousands
    of coordinates), these algorithms run in O(V + E) time. Tarjan's algorithm
    is implemented iteratively to avoid Python's default recursion limit.

    Examples
    --------
    >>> inspector = ProjectSiteInspector()
    >>> site = build_project_site("demo", ["a", "b", "c"], [("a", "b"), ("b", "c")])
    >>> inspector.set_site(site)
    >>> inspector.find_root_coordinates()
    ['a']
    """

    site: ProjectSite = field(
        default_factory=lambda: ProjectSite(
            site_id=uuid.uuid4().hex,
            name="__default__",
            description="",
            project_kind=ProjectKind.LIBRARY,
        )
    )

    def set_site(self, site: ProjectSite) -> None:
        """Replace the current site with a new one.

        Parameters
        ----------
        site : ProjectSite
            The site to analyze.

        Returns
        -------
        None
        """
        self.site = site

    def compute_adjacency_matrix(self) -> dict[str, dict[str, int]]:
        """Build an adjacency matrix from site morphisms.

        Returns
        -------
        dict[str, dict[str, int]]
            Nested dict: ``matrix[source_id][target_id] = 1`` for each
            morphism. Entries not present imply no edge.

        Notes
        -----
        The outer dict contains an entry for every coordinate in the site
        (not just those with edges), so the full vertex set is always
        represented.
        """
        matrix: dict[str, dict[str, int]] = {
            cid: {} for cid in self.site.coordinates
        }
        for morph in self.site.morphisms:
            src, tgt = morph.source_id, morph.target_id
            if src in matrix:
                matrix[src][tgt] = 1
        return matrix

    def find_strongly_connected_components(self) -> list[list[str]]:
        """Compute strongly connected components using Tarjan's algorithm.

        Returns
        -------
        list[list[str]]
            A list of SCCs, each represented as a list of coord_ids. SCCs are
            returned in reverse topological order (sinks first).

        Notes
        -----
        Implemented iteratively to avoid Python's recursion limit on large
        sites. The algorithm uses an explicit call stack with continuation
        frames to simulate the recursive version faithfully.

        Examples
        --------
        >>> inspector = ProjectSiteInspector()
        >>> # A site with no edges: every coord is its own SCC.
        """
        adj: dict[str, list[str]] = {cid: [] for cid in self.site.coordinates}
        for m in self.site.morphisms:
            if m.source_id in adj:
                adj[m.source_id].append(m.target_id)

        index_counter = [0]
        stack: list[str] = []
        on_stack: set[str] = set()
        index: dict[str, int] = {}
        lowlink: dict[str, int] = {}
        sccs: list[list[str]] = []

        def _strongconnect(start: str) -> None:
            call_stack: list[tuple[str, Iterator[str], bool]] = []
            call_stack.append((start, iter(adj.get(start, [])), True))
            while call_stack:
                v, neighbours, first_visit = call_stack[-1]
                if first_visit:
                    index[v] = index_counter[0]
                    lowlink[v] = index_counter[0]
                    index_counter[0] += 1
                    stack.append(v)
                    on_stack.add(v)
                    call_stack[-1] = (v, neighbours, False)
                try:
                    w = next(neighbours)
                    if w not in index:
                        call_stack.append((w, iter(adj.get(w, [])), True))
                    elif w in on_stack:
                        lowlink[v] = min(lowlink[v], index[w])
                except StopIteration:
                    call_stack.pop()
                    if call_stack:
                        parent = call_stack[-1][0]
                        lowlink[parent] = min(lowlink[parent], lowlink[v])
                    if lowlink[v] == index[v]:
                        scc: list[str] = []
                        while True:
                            w = stack.pop()
                            on_stack.discard(w)
                            scc.append(w)
                            if w == v:
                                break
                        sccs.append(scc)

        for node in self.site.coordinates:
            if node not in index:
                _strongconnect(node)
        return sccs

    def find_topological_order(self) -> list[str] | None:
        """Compute a topological ordering of coordinates via Kahn's algorithm.

        Returns
        -------
        list[str] | None
            A valid topological ordering of all coordinates, or ``None`` if
            the morphism graph contains a cycle.

        Notes
        -----
        Kahn's algorithm processes nodes with zero in-degree iteratively,
        decrementing in-degrees of their successors. If not all nodes are
        processed (due to a cycle), ``None`` is returned. The resulting order
        is consistent with the dependency direction: if A depends on B, B
        appears before A.
        """
        in_degree: dict[str, int] = {cid: 0 for cid in self.site.coordinates}
        adj: dict[str, list[str]] = {cid: [] for cid in self.site.coordinates}
        for m in self.site.morphisms:
            if m.target_id in in_degree:
                in_degree[m.target_id] += 1
            if m.source_id in adj:
                adj[m.source_id].append(m.target_id)

        queue: collections.deque[str] = collections.deque(
            cid for cid, deg in in_degree.items() if deg == 0
        )
        order: list[str] = []
        while queue:
            node = queue.popleft()
            order.append(node)
            for neighbour in adj.get(node, []):
                in_degree[neighbour] -= 1
                if in_degree[neighbour] == 0:
                    queue.append(neighbour)

        if len(order) != len(self.site.coordinates):
            return None
        return order

    def compute_in_degree(self, coord_id: str) -> int:
        """Count the number of morphisms targeting a coordinate.

        Parameters
        ----------
        coord_id : str
            The coord to query.

        Returns
        -------
        int
            Number of incoming morphisms.
        """
        return sum(1 for m in self.site.morphisms if m.target_id == coord_id)

    def compute_out_degree(self, coord_id: str) -> int:
        """Count the number of morphisms originating from a coordinate.

        Parameters
        ----------
        coord_id : str
            The coord to query.

        Returns
        -------
        int
            Number of outgoing morphisms.
        """
        return sum(1 for m in self.site.morphisms if m.source_id == coord_id)

    def find_root_coordinates(self) -> list[str]:
        """Return coordinates with no incoming morphisms (in-degree == 0).

        Returns
        -------
        list[str]
            Sorted list of root coord_ids. These are the entry-points of the
            dependency graph — modules that nothing else depends on.
        """
        return sorted(
            cid
            for cid in self.site.coordinates
            if self.compute_in_degree(cid) == 0
        )

    def find_leaf_coordinates(self) -> list[str]:
        """Return coordinates with no outgoing morphisms (out-degree == 0).

        Returns
        -------
        list[str]
            Sorted list of leaf coord_ids. These are the most primitive
            utilities in the dependency graph.
        """
        return sorted(
            cid
            for cid in self.site.coordinates
            if self.compute_out_degree(cid) == 0
        )

    def compute_reachability(self, source_id: str) -> set[str]:
        """Return all coordinates reachable from source_id.

        Parameters
        ----------
        source_id : str
            Starting coordinate.

        Returns
        -------
        set[str]
            Set of coord_ids reachable by following outgoing morphisms. The
            source itself is *not* included.

        Notes
        -----
        Uses iterative BFS. Cycles are handled correctly by the visited-set
        guard.
        """
        adj: dict[str, list[str]] = {cid: [] for cid in self.site.coordinates}
        for m in self.site.morphisms:
            if m.source_id in adj:
                adj[m.source_id].append(m.target_id)

        visited: set[str] = set()
        queue: collections.deque[str] = collections.deque(adj.get(source_id, []))
        while queue:
            node = queue.popleft()
            if node in visited:
                continue
            visited.add(node)
            queue.extend(adj.get(node, []))
        return visited

    def find_cycles(self) -> list[list[str]]:
        """Find simple cycles of length at most 6 in the morphism graph.

        Returns
        -------
        list[list[str]]
            List of cycles, each represented as a list of coord_ids forming
            the cycle (the last element is the same as the first for clarity).

        Notes
        -----
        Uses DFS path tracking. Only cycles up to length 6 are returned to
        keep runtime bounded for large sites. Duplicate cycles (same nodes in
        different rotation) are not filtered.
        """
        adj: dict[str, list[str]] = {cid: [] for cid in self.site.coordinates}
        for m in self.site.morphisms:
            if m.source_id in adj:
                adj[m.source_id].append(m.target_id)

        cycles: list[list[str]] = []
        max_len = 6

        def dfs(start: str, current: str, path: list[str]) -> None:
            if len(path) > max_len:
                return
            for neighbour in adj.get(current, []):
                if neighbour == start and len(path) >= 2:
                    cycles.append(path + [start])
                elif neighbour not in path:
                    dfs(start, neighbour, path + [neighbour])

        for node in self.site.coordinates:
            dfs(node, node, [node])
        return cycles

    def compute_site_metrics(self) -> dict[str, Any]:
        """Compute a comprehensive set of structural metrics for the site.

        Returns
        -------
        dict[str, Any]
            Dictionary with keys: ``coord_count``, ``morphism_count``,
            ``scc_count``, ``has_cycles``, ``avg_in_degree``,
            ``avg_out_degree``, ``root_count``, ``leaf_count``,
            ``diameter_estimate``.

        Notes
        -----
        ``diameter_estimate`` is computed as the length of the longest BFS
        path found starting from any root coordinate. This is a lower bound on
        the true diameter of the underlying undirected graph.
        """
        coords = list(self.site.coordinates.keys())
        n = len(coords)
        m = len(self.site.morphisms)
        sccs = self.find_strongly_connected_components()
        has_cycles = any(len(scc) > 1 for scc in sccs)
        avg_in = sum(self.compute_in_degree(c) for c in coords) / n if n > 0 else 0.0
        avg_out = sum(self.compute_out_degree(c) for c in coords) / n if n > 0 else 0.0
        roots = self.find_root_coordinates()
        leaves = self.find_leaf_coordinates()

        diameter = 0
        for root in roots:
            reachable = self.compute_reachability(root)
            if len(reachable) > diameter:
                diameter = len(reachable)

        return {
            "coord_count": n,
            "morphism_count": m,
            "scc_count": len(sccs),
            "has_cycles": has_cycles,
            "avg_in_degree": round(avg_in, 3),
            "avg_out_degree": round(avg_out, 3),
            "root_count": len(roots),
            "leaf_count": len(leaves),
            "diameter_estimate": diameter,
        }

    def report(self, verbose: bool = False) -> str:
        """Generate a human-readable analysis report.

        Parameters
        ----------
        verbose : bool, optional
            When ``True``, include the full list of SCCs in the report.
            Defaults to ``False``.

        Returns
        -------
        str
            Multi-line string summarizing the site structure, connectivity,
            and any detected cycles.

        Notes
        -----
        Suitable for printing to stdout or logging. The verbose output adds
        per-SCC details that can be lengthy for large sites.
        """
        metrics = self.compute_site_metrics()
        roots = self.find_root_coordinates()
        leaves = self.find_leaf_coordinates()
        cycles = self.find_cycles()
        lines = [
            f"=== Project Site Report: {self.site.name} ===",
            f"Coordinates : {metrics['coord_count']}",
            f"Morphisms   : {metrics['morphism_count']}",
            f"SCCs        : {metrics['scc_count']}",
            f"Has cycles  : {metrics['has_cycles']}",
            f"Avg in-deg  : {metrics['avg_in_degree']}",
            f"Avg out-deg : {metrics['avg_out_degree']}",
            f"Roots ({metrics['root_count']}): {roots[:10]}{'...' if len(roots) > 10 else ''}",
            f"Leaves ({metrics['leaf_count']}): {leaves[:10]}{'...' if len(leaves) > 10 else ''}",
            f"Diameter est: {metrics['diameter_estimate']}",
        ]
        if cycles:
            lines.append(f"Cycles ({len(cycles)}): {cycles[:3]}{'...' if len(cycles) > 3 else ''}")
        else:
            lines.append("Cycles      : none detected (≤ length 6)")
        if verbose:
            sccs = self.find_strongly_connected_components()
            lines.append(f"\nSCC breakdown ({len(sccs)} components):")
            for i, scc in enumerate(sccs):
                lines.append(f"  SCC {i:03d}: {scc}")
        return "\n".join(lines)


def build_project_site(
    name: str,
    modules: list[str],
    dependencies: list[tuple[str, str]],
    kind: ProjectKind = ProjectKind.LIBRARY,
    strategy: CoverStrategy = CoverStrategy.GREEDY,
) -> ProjectSite:
    """Build a ProjectSite from a flat list of modules and dependency edges.

    Parameters
    ----------
    name : str
        Human-readable project name.
    modules : list[str]
        Dot-separated module names to register as coordinates.
    dependencies : list[tuple[str, str]]
        Each element is ``(source, target)`` indicating that *source* imports
        *target*.
    kind : ProjectKind, optional
        Classification of the project. Defaults to LIBRARY.
    strategy : CoverStrategy, optional
        Cover strategy for topology generation. Defaults to GREEDY.

    Returns
    -------
    ProjectSite
        Fully constructed project site with topology.

    Notes
    -----
    This is a high-level convenience function wrapping ``SemanticSiteBuilder``.
    It resets the builder before use, so calling it multiple times is safe.

    Examples
    --------
    >>> site = build_project_site("mylib", ["mylib.a", "mylib.b"], [("mylib.a", "mylib.b")])
    >>> site.name
    'mylib'
    """
    builder = SemanticSiteBuilder()
    builder.set_strategy(strategy)
    builder.add_bulk_modules(modules)
    builder.add_bulk_dependencies(dependencies)
    return builder.build(name, kind)


def compute_site_morphisms(site: ProjectSite) -> list[CoordinateMorphism]:
    """Return only the morphisms whose endpoints both exist in the site.

    Parameters
    ----------
    site : ProjectSite
        The project site to inspect.

    Returns
    -------
    list[CoordinateMorphism]
        Filtered list of morphisms where both source and target coordinates
        are present in ``site.coordinates``.

    Notes
    -----
    Dangling morphisms (those referencing removed or never-added coordinates)
    can accumulate in a site that has had coordinates removed. This function
    provides a clean view of valid morphisms without mutating the site.

    Examples
    --------
    >>> site = build_project_site("p", ["a", "b"], [("a", "b")])
    >>> morphs = compute_site_morphisms(site)
    >>> len(morphs)
    1
    """
    return [
        m
        for m in site.morphisms
        if site.get_coordinate(m.source_id) is not None
        and site.get_coordinate(m.target_id) is not None
    ]


def site_from_modules(
    module_spec: dict[str, list[str]],
    project_name: str = "unnamed",
) -> ProjectSite:
    """Build a ProjectSite from an adjacency-list module specification.

    Parameters
    ----------
    module_spec : dict[str, list[str]]
        Mapping from module name to list of imported module names, e.g.
        ``{"a": ["b", "c"], "b": [], "c": ["b"]}``.
    project_name : str, optional
        Name for the resulting project site. Defaults to ``"unnamed"``.

    Returns
    -------
    ProjectSite
        Constructed site with all modules registered and dependency morphisms
        added.

    Notes
    -----
    All modules appearing as keys *or* values are registered, ensuring the
    site is complete even if some dependencies are external (not listed as
    keys).

    Examples
    --------
    >>> spec = {"core": ["utils"], "utils": []}
    >>> site = site_from_modules(spec, "myproject")
    >>> "core" in site.coordinates
    True
    """
    all_names: set[str] = set(module_spec.keys())
    for deps in module_spec.values():
        all_names.update(deps)
    edges: list[tuple[str, str]] = []
    for src, targets in module_spec.items():
        for tgt in targets:
            edges.append((src, tgt))
    return build_project_site(project_name, sorted(all_names), edges)


def analyze_site_topology(site: ProjectSite) -> dict[str, Any]:
    """Produce a combined structural and topological analysis of a site.

    Parameters
    ----------
    site : ProjectSite
        The site to analyze.

    Returns
    -------
    dict[str, Any]
        Combined dict containing graph metrics (from ``ProjectSiteInspector``)
        and topology summary (from ``TopologyGenerator``). Keys include all
        fields from ``compute_site_metrics`` plus ``topology`` (the summary
        dict from ``TopologyGenerator.summarize``).

    Notes
    -----
    The topology is recomputed from scratch using the GREEDY strategy.
    If the site already has a pre-computed topology in ``site.topology``,
    that is used directly for the summary to avoid redundant work.

    Examples
    --------
    >>> site = build_project_site("demo", ["a", "b"], [("a", "b")])
    >>> analysis = analyze_site_topology(site)
    >>> "coord_count" in analysis
    True
    """
    inspector = ProjectSiteInspector()
    inspector.set_site(site)
    metrics = inspector.compute_site_metrics()

    gen = TopologyGenerator()
    if site.topology:
        topo_summary = gen.summarize(site.topology)
    else:
        topo = gen.generate(site)
        topo_summary = gen.summarize(topo)

    return {**metrics, "topology": topo_summary}


def find_minimal_cover(site: ProjectSite, target_id: str) -> list[str]:
    """Find a minimal covering set for a target coordinate.

    Parameters
    ----------
    site : ProjectSite
        The site in which to search for a cover.
    target_id : str
        The coordinate for which a cover is sought.

    Returns
    -------
    list[str]
        A list of coord_ids that together cover the site reachable from
        *target_id*. If the target has no outgoing morphisms, returns
        ``[target_id]``.

    Notes
    -----
    The algorithm starts with the immediate outgoing neighbours of *target_id*
    as a candidate cover. It then performs one additional BFS expansion to
    improve coverage. This greedy approach does not guarantee an optimal cover
    but runs in linear time and is well-suited for incremental LLM-assisted
    analysis.

    Examples
    --------
    >>> site = build_project_site("p", ["a", "b", "c"], [("a", "b"), ("b", "c")])
    >>> find_minimal_cover(site, "a")
    ['b', 'c']
    """
    adj: dict[str, list[str]] = {cid: [] for cid in site.coordinates}
    for m in site.morphisms:
        if m.source_id in adj:
            adj[m.source_id].append(m.target_id)

    direct: list[str] = adj.get(target_id, [])
    if not direct:
        return [target_id]

    covered: set[str] = set(direct)
    for node in list(covered):
        for neighbour in adj.get(node, []):
            covered.add(neighbour)

    return sorted(covered)


# copilot: §8.1 project-sites implementation — SemanticSiteBuilder and friends are
# designed for LLM-assisted project topology construction and analysis.
