"""
manifest — Package manifest for JuGeo text_encodings.

Generated by the JuGeo copilot encoding pipeline.
theory2.tex Ch28: Exact Z3 encodings III: strings, symbolic text, naming laws,
documentation shadows.

Part of the JuGeo judgment-geometry framework.
"""
from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any, Final, Mapping

# ---------------------------------------------------------------------------
# Module logger
# ---------------------------------------------------------------------------

_logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Provenance and version constants
# ---------------------------------------------------------------------------

MANIFEST_SPEC_PROVENANCE: Final[Mapping[str, str | int]] = {
    "semantic_source": "preliminaries/theory2.tex",
    "chapter": 28,
    "section": "exact-z3-encodings-iii",
    "generated_by": "jugeo-copilot",
    "version": 1,
}
"""Provenance metadata for the text_encodings manifest, referencing theory2.tex Ch28."""

CHAPTER_TAG: Final[str] = "ch28-exact-z3-encodings-iii"
"""Canonical chapter tag used to cross-reference this package with theory2.tex Ch28."""

# ---------------------------------------------------------------------------
# Section registry
# ---------------------------------------------------------------------------

SECTION_NAMES: Final[list[str]] = [
    "strings",
    "symbolic_text",
    "naming_laws",
    "documentation_shadows",
]
"""All four section modules comprising the text_encodings package."""

SECTION_REGISTRY: Final[Mapping[str, str]] = {
    "strings": "strings.py",
    "symbolic_text": "symbolic_text.py",
    "naming_laws": "naming_laws.py",
    "documentation_shadows": "documentation_shadows.py",
}
"""Mapping from logical section name to the file that implements it."""

# ---------------------------------------------------------------------------
# Theorem targets
# ---------------------------------------------------------------------------

THEOREM_TARGETS: Final[list[str]] = [
    "thm:string-decidability",
    "thm:naming-law-completeness",
    "thm:doc-shadow-soundness",
    "thm:regex-to-smt2-preservation",
    "thm:normalization-idempotence",
    "thm:countermodel-existence",
    "thm:repair-termination",
    "thm:symbolic-text-saturation",
    "thm:unicode-block-coverage",
]
"""
Theorem names from theory2.tex Ch28 that the text_encodings package is designed to
validate through exact Z3 encodings.  Each name corresponds to a theorem or lemma
in the chapter.
"""

# ---------------------------------------------------------------------------
# Capability flags
# ---------------------------------------------------------------------------

CAPABILITY_FLAGS: Final[Mapping[str, bool]] = {
    "z3_strings": True,
    "naming_laws": True,
    "doc_shadows": True,
    "normalization": True,
    "countermodels": True,
    "repair_engine": True,
}
"""
Boolean feature flags indicating which capabilities are active in this build of the
text_encodings package.
"""

# ---------------------------------------------------------------------------
# Unicode text features (informational)
# ---------------------------------------------------------------------------

UNICODE_TEXT_FEATURES: Final[Mapping[str, Any]] = {
    "normalization_forms": ["NFC", "NFD", "NFKC", "NFKD"],
    "default_normalization": "NFC",
    "supported_scripts": [
        "Latin", "Greek", "Cyrillic", "CJK", "Arabic", "Hebrew",
        "Devanagari", "Japanese_Kana",
    ],
    "max_codepoint": 0x10FFFF,
    "surrogate_pairs_supported": False,
    "bidi_aware": False,
    "collation_locale": "en_US.UTF-8",
    "z3_string_sort": "String",
    "smt2_string_theory": "QF_SLIA",
}
"""
Metadata about the Unicode text features exploited by the encodings in this package.
"""

# ---------------------------------------------------------------------------
# Encoding complexity estimates
# ---------------------------------------------------------------------------

ENCODING_COMPLEXITY_ESTIMATES: Final[Mapping[str, str]] = {
    "strings": "O(n) — linear in number of string constraints",
    "symbolic_text": "O(n * k) — linear in variables, linear in constraints per variable",
    "naming_laws": "O(m * log m) — quasi-linear in law complexity",
    "documentation_shadows": "O(d * c) — linear in doc length, linear in extracted constraints",
    "regex_to_z3": "O(2^r) — exponential worst-case for complex regexes",
    "normalization": "O(n) — linear in string length",
    "countermodel_search": "O(exp) — NP-hard in general",
    "repair_engine": "O(n^2) — quadratic in number of violations",
}
"""
Rough complexity estimates for each encoding subsystem in the text_encodings package.
These are informational only; actual performance depends on the Z3 solver heuristics.
"""

# ---------------------------------------------------------------------------
# Text encoding families
# ---------------------------------------------------------------------------

TEXT_ENCODING_FAMILIES_REGISTRY: Final[list[str]] = [
    "smt2-string-theory",
    "regex-constraint-encoding",
    "naming-law-encoding",
    "documentation-shadow-encoding",
    "unicode-normalization-encoding",
    "symbolic-concatenation-encoding",
    "length-constraint-encoding",
    "character-class-encoding",
    "prefix-suffix-encoding",
    "semantic-constraint-encoding",
]
"""
Registry of the encoding families implemented in the text_encodings package.
Each family corresponds to a distinct class of Z3 string constraints.
"""

# ---------------------------------------------------------------------------
# Naming law names
# ---------------------------------------------------------------------------

NAMING_LAW_NAMES: Final[list[str]] = [
    "snake_case",
    "camel_case",
    "pascal_case",
    "kebab_case",
    "screaming_snake_case",
    "lower_camel_case",
    "upper_camel_case",
    "dot_notation",
    "namespace_qualified",
    "uuid_format",
    "semver_format",
    "iso8601_date",
]
"""
Standard naming law names understood by the text_encodings package.
These correspond to common identifier and value conventions in software systems.
"""

# ---------------------------------------------------------------------------
# Validation error codes
# ---------------------------------------------------------------------------

VALIDATION_ERROR_CODES: Final[Mapping[str, str]] = {
    "E001": "Missing section in registry",
    "E002": "Theorem target list is empty",
    "E003": "Capability flag missing required key",
    "E004": "Chapter reference does not match CHAPTER_TAG",
    "E005": "Provenance missing required key",
    "E006": "Section count mismatch between SECTION_NAMES and SECTION_REGISTRY",
    "E007": "Duplicate section name detected",
    "E008": "Duplicate theorem target detected",
    "E009": "Invalid capability flag value (must be bool)",
    "E010": "Manifest generated_at timestamp is in the future",
}
"""Error codes used in manifest validation."""

# ---------------------------------------------------------------------------
# Required capability keys
# ---------------------------------------------------------------------------

_REQUIRED_CAPABILITY_KEYS: Final[list[str]] = [
    "z3_strings",
    "naming_laws",
    "doc_shadows",
    "normalization",
    "countermodels",
    "repair_engine",
]

_REQUIRED_PROVENANCE_KEYS: Final[list[str]] = [
    "semantic_source",
    "chapter",
    "section",
    "generated_by",
    "version",
]

# ---------------------------------------------------------------------------
# ManifestValidator
# ---------------------------------------------------------------------------


class ManifestValidator:
    """
    Validates a :class:`TextEncodingManifest` against the invariants described
    in theory2.tex Ch28.

    Instances are stateless; all methods accept the manifest as an argument.

    Example::

        validator = ManifestValidator()
        errors = validator.run_all(manifest)
        if errors:
            for e in errors:
                print(e)
    """

    def check_sections(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Verify that the manifest's section_names list is non-empty, contains no
        duplicates, and that every entry also appears in the section registry.

        Args:
            manifest: The manifest to inspect.

        Returns:
            A (possibly empty) list of human-readable error strings.
        """
        errors: list[str] = []
        seen: set[str] = set()
        for name in manifest.section_names:
            if name in seen:
                errors.append(f"[E007] Duplicate section name: {name!r}")
            seen.add(name)
        for name in manifest.section_names:
            if name not in SECTION_REGISTRY:
                errors.append(f"[E001] Section {name!r} not in global SECTION_REGISTRY")
        return errors

    def check_theorems(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Ensure that theorem_targets is non-empty and contains no duplicates.

        Args:
            manifest: The manifest to inspect.

        Returns:
            A (possibly empty) list of human-readable error strings.
        """
        errors: list[str] = []
        if not manifest.theorem_targets:
            errors.append("[E002] theorem_targets must not be empty")
        seen: set[str] = set()
        for t in manifest.theorem_targets:
            if t in seen:
                errors.append(f"[E008] Duplicate theorem target: {t!r}")
            seen.add(t)
        return errors

    def check_capabilities(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Verify that all required capability keys are present and hold boolean values.

        Args:
            manifest: The manifest to inspect.

        Returns:
            A (possibly empty) list of human-readable error strings.
        """
        errors: list[str] = []
        for key in _REQUIRED_CAPABILITY_KEYS:
            if key not in manifest.capability_flags:
                errors.append(f"[E003] Missing capability flag: {key!r}")
            elif not isinstance(manifest.capability_flags[key], bool):
                errors.append(f"[E009] Capability flag {key!r} must be bool")
        return errors

    def check_provenance(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Check that the manifest provenance dict contains all required keys.

        Args:
            manifest: The manifest to inspect.

        Returns:
            A (possibly empty) list of human-readable error strings.
        """
        errors: list[str] = []
        for key in _REQUIRED_PROVENANCE_KEYS:
            if key not in manifest.provenance:
                errors.append(f"[E005] Missing provenance key: {key!r}")
        return errors

    def check_chapter_ref(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Verify that chapter_ref matches the module-level CHAPTER_TAG.

        Args:
            manifest: The manifest to inspect.

        Returns:
            A (possibly empty) list of human-readable error strings.
        """
        errors: list[str] = []
        if manifest.chapter_ref != CHAPTER_TAG:
            errors.append(
                f"[E004] chapter_ref {manifest.chapter_ref!r} != CHAPTER_TAG {CHAPTER_TAG!r}"
            )
        return errors

    def check_timestamp(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Warn if generated_at is in the future.

        Args:
            manifest: The manifest to inspect.

        Returns:
            A (possibly empty) list of human-readable error strings.
        """
        errors: list[str] = []
        now = time.time()
        if manifest.generated_at > now + 60:
            errors.append(
                f"[E010] generated_at ({manifest.generated_at:.1f}) is more than 60 s in the future"
            )
        return errors

    def run_all(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Run all validation checks and aggregate results.

        Args:
            manifest: The manifest to validate.

        Returns:
            A flat list of all error strings found across all checks.
        """
        errors: list[str] = []
        errors.extend(self.check_sections(manifest))
        errors.extend(self.check_theorems(manifest))
        errors.extend(self.check_capabilities(manifest))
        errors.extend(self.check_provenance(manifest))
        errors.extend(self.check_chapter_ref(manifest))
        errors.extend(self.check_timestamp(manifest))
        return errors


# ---------------------------------------------------------------------------
# ManifestSerializer
# ---------------------------------------------------------------------------


class ManifestSerializer:
    """
    Serializes and deserializes :class:`TextEncodingManifest` objects to and from
    plain Python dicts, making them suitable for JSON or YAML persistence.

    Example::

        s = ManifestSerializer()
        d = s.to_dict(manifest)
        m2 = s.from_dict(d)
    """

    def to_dict(self, manifest: TextEncodingManifest) -> dict[str, Any]:
        """
        Convert a manifest to a JSON-serializable dict.

        Args:
            manifest: The manifest to serialize.

        Returns:
            A plain dict representation of the manifest.
        """
        return {
            "chapter_ref": manifest.chapter_ref,
            "section_names": list(manifest.section_names),
            "theorem_targets": list(manifest.theorem_targets),
            "capability_flags": dict(manifest.capability_flags),
            "generated_at": manifest.generated_at,
            "provenance": dict(manifest.provenance),
        }

    def from_dict(self, data: dict[str, Any]) -> TextEncodingManifest:
        """
        Reconstruct a :class:`TextEncodingManifest` from a plain dict.

        Args:
            data: Dict previously produced by :meth:`to_dict`.

        Returns:
            A new :class:`TextEncodingManifest` instance.

        Raises:
            KeyError: If a required key is absent from *data*.
        """
        return TextEncodingManifest(
            chapter_ref=data["chapter_ref"],
            section_names=list(data["section_names"]),
            theorem_targets=list(data["theorem_targets"]),
            capability_flags=dict(data["capability_flags"]),
            generated_at=float(data.get("generated_at", time.time())),
            provenance=dict(data.get("provenance", {})),
        )

    def to_summary_lines(self, manifest: TextEncodingManifest) -> list[str]:
        """
        Return a list of human-readable summary lines for display.

        Args:
            manifest: The manifest to summarize.

        Returns:
            A list of strings, one per attribute.
        """
        return [
            f"Chapter : {manifest.chapter_ref}",
            f"Sections: {', '.join(manifest.section_names)}",
            f"Theorems: {manifest.theorem_count()} target(s)",
            f"Capabilities: {manifest.capability_summary()}",
            f"Generated at: {manifest.generated_at:.3f}",
            f"Valid: {manifest.is_complete()}",
        ]


# ---------------------------------------------------------------------------
# TextEncodingManifest dataclass
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class TextEncodingManifest:
    """
    Central manifest for the JuGeo text_encodings package.

    Holds the chapter reference, list of section modules, theorem targets,
    capability flags, and provenance metadata.  Instances are mutable; use
    :meth:`add_section` and :meth:`flag_capability` to extend them.

    Attributes:
        chapter_ref: The canonical chapter tag (should equal CHAPTER_TAG).
        section_names: Ordered list of section module names.
        theorem_targets: List of theorem identifiers from theory2.tex Ch28.
        capability_flags: Mutable dict of capability boolean flags.
        generated_at: Unix timestamp of manifest creation.
        provenance: Metadata dict describing the manifest's origin.

    Example::

        m = build_manifest()
        print(m.summary())
    """

    chapter_ref: str
    section_names: list[str]
    theorem_targets: list[str]
    capability_flags: dict[str, bool]
    generated_at: float = field(default_factory=time.time)
    provenance: Mapping[str, str | int] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Enumeration helpers
    # ------------------------------------------------------------------

    def enumerate_sections(self) -> list[tuple[int, str]]:
        """
        Return a numbered list of sections (1-based).

        Returns:
            List of (index, section_name) tuples.

        Example::

            for idx, name in manifest.enumerate_sections():
                print(f"{idx}. {name}")
        """
        return list(enumerate(self.section_names, start=1))

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def validate(self) -> list[str]:
        """
        Validate this manifest and return a list of error strings.

        Returns:
            Empty list if the manifest is valid; otherwise a list of
            human-readable error messages.

        Example::

            errors = manifest.validate()
            assert errors == []
        """
        validator = ManifestValidator()
        errors = validator.run_all(self)
        if errors:
            _logger.warning("Manifest validation found %d error(s)", len(errors))
            for e in errors:
                _logger.debug("  %s", e)
        return errors

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """
        Export this manifest as a plain Python dict.

        Returns:
            A JSON-serializable dict representation.
        """
        return ManifestSerializer().to_dict(self)

    # ------------------------------------------------------------------
    # Display helpers
    # ------------------------------------------------------------------

    def summary(self) -> str:
        """
        Return a concise human-readable summary of the manifest.

        Returns:
            A multi-line string describing the manifest's key attributes.

        Example::

            print(manifest.summary())
        """
        lines = ManifestSerializer().to_summary_lines(self)
        return "\n".join(lines)

    def capability_summary(self) -> str:
        """
        Return a one-line string summarising which capabilities are enabled.

        Returns:
            A comma-separated list of ``flag=True/False`` entries.
        """
        parts = [f"{k}={'on' if v else 'off'}" for k, v in self.capability_flags.items()]
        return ", ".join(parts)

    def theorem_count(self) -> int:
        """
        Return the number of theorem targets registered.

        Returns:
            Integer count of theorem_targets entries.
        """
        return len(self.theorem_targets)

    # ------------------------------------------------------------------
    # Completeness check
    # ------------------------------------------------------------------

    def is_complete(self) -> bool:
        """
        Return True if the manifest passes all validations and every declared
        section is present in the global SECTION_REGISTRY.

        Returns:
            True when no validation errors are found.
        """
        errors = self.validate()
        return len(errors) == 0

    # ------------------------------------------------------------------
    # Mutation helpers
    # ------------------------------------------------------------------

    def add_section(self, name: str, file_name: str) -> None:
        """
        Add a new section to the manifest.

        If *name* is already in section_names it is not added again, but the
        global SECTION_REGISTRY is updated (module-level dict is immutable via
        Final, so this logs a warning instead).

        Args:
            name: Logical section name (e.g. ``"new_section"``).
            file_name: Python file name for the section (e.g. ``"new_section.py"``).

        Example::

            manifest.add_section("extra", "extra.py")
        """
        if name not in self.section_names:
            self.section_names.append(name)
            _logger.debug("Added section %r -> %r to manifest", name, file_name)
        else:
            _logger.debug("Section %r already present in manifest", name)

    def flag_capability(self, name: str, value: bool) -> None:
        """
        Set or update a capability flag.

        Args:
            name: Capability flag key (e.g. ``"z3_strings"``).
            value: Boolean flag value.

        Example::

            manifest.flag_capability("repair_engine", False)
        """
        self.capability_flags[name] = value
        _logger.debug("Set capability flag %r = %r", name, value)

    # ------------------------------------------------------------------
    # Merge
    # ------------------------------------------------------------------

    def merge_with(self, other: TextEncodingManifest) -> TextEncodingManifest:
        """
        Merge this manifest with *other*, producing a new manifest.

        Section names and theorem targets are union-merged (preserving order
        from self first, then any additions from other).  Capability flags from
        *other* override those in self when keys collide.

        Args:
            other: Another :class:`TextEncodingManifest` to merge in.

        Returns:
            A new :class:`TextEncodingManifest` that combines both manifests.

        Raises:
            ValueError: If the two manifests have differing chapter_ref values.

        Example::

            merged = m1.merge_with(m2)
        """
        if self.chapter_ref != other.chapter_ref:
            raise ValueError(
                f"Cannot merge manifests with differing chapter_ref: "
                f"{self.chapter_ref!r} vs {other.chapter_ref!r}"
            )
        merged_sections = list(self.section_names)
        for s in other.section_names:
            if s not in merged_sections:
                merged_sections.append(s)

        merged_theorems = list(self.theorem_targets)
        for t in other.theorem_targets:
            if t not in merged_theorems:
                merged_theorems.append(t)

        merged_flags = {**self.capability_flags, **other.capability_flags}

        merged_prov: dict[str, str | int] = {**self.provenance, **other.provenance}

        result = TextEncodingManifest(
            chapter_ref=self.chapter_ref,
            section_names=merged_sections,
            theorem_targets=merged_theorems,
            capability_flags=merged_flags,
            generated_at=time.time(),
            provenance=merged_prov,
        )
        _logger.debug(
            "Merged manifest: %d sections, %d theorems",
            len(merged_sections),
            len(merged_theorems),
        )
        return result


# ---------------------------------------------------------------------------
# Factory functions
# ---------------------------------------------------------------------------


def build_manifest() -> TextEncodingManifest:
    """
    Construct and return the canonical :class:`TextEncodingManifest` for the
    text_encodings package.

    The manifest is populated from the module-level constants defined in this
    file and represents the complete, authoritative description of the package
    contents as generated by the JuGeo copilot encoding pipeline.

    Returns:
        A fully populated :class:`TextEncodingManifest` instance.

    Example::

        m = build_manifest()
        assert m.is_complete()
    """
    _logger.debug("Building text_encodings manifest for chapter %r", CHAPTER_TAG)
    manifest = TextEncodingManifest(
        chapter_ref=CHAPTER_TAG,
        section_names=list(SECTION_NAMES),
        theorem_targets=list(THEOREM_TARGETS),
        capability_flags=dict(CAPABILITY_FLAGS),
        generated_at=time.time(),
        provenance=dict(MANIFEST_SPEC_PROVENANCE),
    )
    _logger.info(
        "text_encodings manifest built: %d sections, %d theorems",
        len(manifest.section_names),
        manifest.theorem_count(),
    )
    return manifest


def validate_manifest(manifest: TextEncodingManifest) -> bool:
    """
    Validate *manifest* and log any errors found.

    This is a convenience wrapper around :meth:`TextEncodingManifest.validate`
    that logs at WARNING level when errors are present and returns a simple
    boolean result.

    Args:
        manifest: The manifest to validate.

    Returns:
        True if the manifest passes all checks; False otherwise.

    Example::

        ok = validate_manifest(MANIFEST)
        assert ok, "Manifest is invalid — check logs for details"
    """
    errors = manifest.validate()
    if errors:
        _logger.warning(
            "Manifest validation failed with %d error(s):", len(errors)
        )
        for i, err in enumerate(errors, start=1):
            _logger.warning("  [%d] %s", i, err)
        return False
    _logger.info("Manifest validation passed (chapter=%r)", manifest.chapter_ref)
    return True


# ---------------------------------------------------------------------------
# Additional helpers
# ---------------------------------------------------------------------------


def describe_encoding_family(family: str) -> str:
    """
    Return a short human-readable description for a known encoding family.

    Args:
        family: A name from TEXT_ENCODING_FAMILIES_REGISTRY.

    Returns:
        A description string, or a generic message if the family is unknown.

    Example::

        print(describe_encoding_family("smt2-string-theory"))
    """
    descriptions: dict[str, str] = {
        "smt2-string-theory": (
            "Direct SMT2 string-theory assertions using Z3's built-in String sort."
        ),
        "regex-constraint-encoding": (
            "Regex patterns compiled to Z3 str.in_re constraints."
        ),
        "naming-law-encoding": (
            "Structural naming conventions encoded as conjunction of string constraints."
        ),
        "documentation-shadow-encoding": (
            "Natural-language documentation parsed to formal string assertions."
        ),
        "unicode-normalization-encoding": (
            "NFC/NFD/NFKC/NFKD normalization enforced via Z3 string rewrite rules."
        ),
        "symbolic-concatenation-encoding": (
            "String concatenation expressed through Z3 str.++ operator."
        ),
        "length-constraint-encoding": (
            "Integer-bounded length constraints using str.len."
        ),
        "character-class-encoding": (
            "Character-class membership tests via re.range and re.union."
        ),
        "prefix-suffix-encoding": (
            "Prefix and suffix membership via str.prefixof / str.suffixof."
        ),
        "semantic-constraint-encoding": (
            "High-level semantic invariants translated to conjunction of SMT2 assertions."
        ),
    }
    return descriptions.get(family, f"Unknown encoding family: {family!r}")


def list_active_capabilities(manifest: TextEncodingManifest) -> list[str]:
    """
    Return the names of all capability flags that are currently enabled.

    Args:
        manifest: The manifest whose capability_flags to inspect.

    Returns:
        A list of flag names whose value is True.

    Example::

        active = list_active_capabilities(MANIFEST)
        print("Active:", active)
    """
    return [k for k, v in manifest.capability_flags.items() if v]


def list_inactive_capabilities(manifest: TextEncodingManifest) -> list[str]:
    """
    Return the names of all capability flags that are currently disabled.

    Args:
        manifest: The manifest whose capability_flags to inspect.

    Returns:
        A list of flag names whose value is False.
    """
    return [k for k, v in manifest.capability_flags.items() if not v]


def section_file_for(section_name: str) -> str | None:
    """
    Look up the file name for a given section in the global SECTION_REGISTRY.

    Args:
        section_name: The logical section name to look up.

    Returns:
        The corresponding file name string, or None if not found.

    Example::

        fname = section_file_for("naming_laws")
        # fname == "naming_laws.py"
    """
    return SECTION_REGISTRY.get(section_name)


def theorem_index(theorem_name: str) -> int | None:
    """
    Return the 0-based index of *theorem_name* in THEOREM_TARGETS, or None.

    Args:
        theorem_name: A theorem identifier string.

    Returns:
        Integer index if found; None otherwise.
    """
    try:
        return THEOREM_TARGETS.index(theorem_name)
    except ValueError:
        return None


def naming_law_index(law_name: str) -> int | None:
    """
    Return the 0-based index of *law_name* in NAMING_LAW_NAMES, or None.

    Args:
        law_name: A naming law identifier.

    Returns:
        Integer index if found; None otherwise.
    """
    try:
        return NAMING_LAW_NAMES.index(law_name)
    except ValueError:
        return None


def complexity_estimate_for(section_name: str) -> str | None:
    """
    Return the complexity estimate string for *section_name*.

    Args:
        section_name: A section name key in ENCODING_COMPLEXITY_ESTIMATES.

    Returns:
        Complexity estimate string, or None if the section is not known.
    """
    return ENCODING_COMPLEXITY_ESTIMATES.get(section_name)


def print_manifest_report(manifest: TextEncodingManifest) -> None:
    """
    Print a structured report about *manifest* to stdout.

    Intended for debugging and CLI inspection.  Each attribute is printed on
    its own line with a label prefix.

    Args:
        manifest: The manifest to report on.
    """
    print("=" * 60)
    print("TextEncodingManifest Report")
    print("=" * 60)
    print(f"  chapter_ref    : {manifest.chapter_ref}")
    print(f"  sections       : {', '.join(manifest.section_names)}")
    print(f"  theorem_count  : {manifest.theorem_count()}")
    print(f"  capabilities   : {manifest.capability_summary()}")
    print(f"  generated_at   : {manifest.generated_at:.3f}")
    print(f"  is_complete    : {manifest.is_complete()}")
    print("-" * 60)
    print("Sections:")
    for idx, name in manifest.enumerate_sections():
        fname = section_file_for(name) or "<unknown>"
        print(f"  {idx:2d}. {name:<30} -> {fname}")
    print("-" * 60)
    print("Theorem targets:")
    for t in manifest.theorem_targets:
        print(f"  - {t}")
    print("=" * 60)


# ---------------------------------------------------------------------------
# Module-level manifest singleton
# ---------------------------------------------------------------------------

MANIFEST: Final[TextEncodingManifest] = build_manifest()
"""
Module-level singleton manifest for the text_encodings package.

Constructed once at import time via :func:`build_manifest`.  Import this
constant when you need a reference to the package manifest::

    from jugeo.encodings.text_encodings.manifest import MANIFEST
    print(MANIFEST.summary())
"""
