/-
  Paper14_OperadicComposition.lean — Operadic Composition of Verification Strategies

  Formalizes the core structures from Paper 14 of the Judgment Geometry series:
    • Color  = four types of verification problem
    • Move   = ten semantic generators of the operad V
    • Path   = typed sequence of composable moves (free category on moves)
    • seqComp = sequential composition (the unary operadic composition law)
    • Operad axioms: left unit, right unit, associativity (no sorry)
    • SmallCategory record: bundles all category/operad axioms
    • Idempotent generator classification (endomorphic moves)
    • Valid/blocked pair enumeration by native_decide
    • Reachability in the move-color graph
    • Explicit strategy witnesses for all four recovery patterns
    • TypeChecks predicate: list-level operadic composition law
    • Synthesis completeness: every path decomposes into single steps
-/

namespace JudgmentGeometry.Paper14

-- ════════════════════════════════════════════════════════════════════
-- § 1  Colors (types of verification problems)
-- ════════════════════════════════════════════════════════════════════

/-- The four kinds of verification problem that strategies act on. -/
inductive Color : Type where
  | goal         -- an unverified claim to be established
  | partialPrf   -- a partially verified claim (needs completion)
  | verified     -- a fully verified claim
  | obstructed   -- a claim blocked by a cohomological obstruction
  deriving DecidableEq, Repr, BEq, Inhabited

-- ════════════════════════════════════════════════════════════════════
-- § 2  Moves (generators of the operad V)
-- ════════════════════════════════════════════════════════════════════

/-- The ten semantic moves generating the verification operad V. -/
inductive Move : Type where
  | verify    -- discharge a goal via SMT or mechanical proof
  | construct -- build a partial proof fragment from a goal
  | normalize -- simplify a goal without changing its type
  | glue      -- assemble a partial proof into a verified claim
  | restrict_ -- decompose a goal into a sub-goal (open cover restriction)
  | transport -- push a verified claim along a coordinate morphism
  | repair    -- convert an obstructed claim into a fresh goal
  | promote   -- raise the trust level of a verified claim
  | challenge -- question a verified claim, reverting it to a goal
  | escalate  -- intensify an obstructed claim (raise urgency)
  deriving DecidableEq, Repr, BEq

-- ════════════════════════════════════════════════════════════════════
-- § 3  Type signatures (source and target colors)
-- ════════════════════════════════════════════════════════════════════

/-- Source color: the type of verification problem the move consumes. -/
def Move.src : Move → Color
  | .verify    => .goal
  | .construct => .goal
  | .normalize => .goal
  | .glue      => .partialPrf
  | .restrict_ => .goal
  | .transport => .verified
  | .repair    => .obstructed
  | .promote   => .verified
  | .challenge => .verified
  | .escalate  => .obstructed

/-- Target color: the type of verification problem the move produces. -/
def Move.tgt : Move → Color
  | .verify    => .verified
  | .construct => .partialPrf
  | .normalize => .goal
  | .glue      => .verified
  | .restrict_ => .goal
  | .transport => .verified
  | .repair    => .goal
  | .promote   => .verified
  | .challenge => .goal
  | .escalate  => .obstructed

-- ════════════════════════════════════════════════════════════════════
-- § 4  Typed strategy paths (free category on the move graph)
-- ════════════════════════════════════════════════════════════════════

/-- A typed strategy sequence from color `a` to color `b`.
    Represents a path in the free category generated by the moves. -/
inductive Path : Color → Color → Type where
  | nil  {c : Color}                                                   : Path c c
  | cons {c d : Color} (m : Move) (h : m.src = c) (p : Path m.tgt d) : Path c d

-- ════════════════════════════════════════════════════════════════════
-- § 5  Sequential composition (the operadic composition law)
-- ════════════════════════════════════════════════════════════════════

/-- Sequential composition of two strategy paths.
    Corresponds to operadic composition γ in the unary (1-colored) setting. -/
def Path.seqComp {a b c : Color} : Path a b → Path b c → Path a c
  | .nil,        q => q
  | .cons m h p, q => .cons m h (p.seqComp q)

/-- The identity strategy: the empty sequence that leaves a problem unchanged. -/
@[inline] def Path.idPath (c : Color) : Path c c := .nil

-- ════════════════════════════════════════════════════════════════════
-- § 6  Operad axioms (proved by structural induction, no sorry)
-- ════════════════════════════════════════════════════════════════════

/-- Left unit law: composing the identity on the left is neutral. -/
@[simp]
theorem Path.id_seqComp {a b : Color} (p : Path a b) :
    (Path.idPath a).seqComp p = p := rfl

/-- Right unit law: composing the identity on the right is neutral. -/
theorem Path.seqComp_id {a b : Color} : ∀ (p : Path a b),
    p.seqComp (Path.idPath b) = p
  | .nil        => rfl
  | .cons m h p => congrArg (Path.cons m h) (Path.seqComp_id p)

/-- Associativity of sequential composition:  p ∘ (q ∘ r) = (p ∘ q) ∘ r.
    This is the central operad axiom. -/
theorem Path.seqComp_assoc {a b c d : Color} :
    ∀ (p : Path a b) (q : Path b c) (r : Path c d),
    p.seqComp (q.seqComp r) = (p.seqComp q).seqComp r
  | .nil,        _, _ => rfl
  | .cons m h p, q, r => congrArg (Path.cons m h) (Path.seqComp_assoc p q r)

-- ════════════════════════════════════════════════════════════════════
-- § 7  Verification category (all axioms bundled as a record)
-- ════════════════════════════════════════════════════════════════════

/-- A small category structure over object type `Ob`. -/
structure SmallCategory (Ob : Type) where
  Hom   : Ob → Ob → Type
  id    : (a : Ob) → Hom a a
  comp  : {a b c : Ob} → Hom a b → Hom b c → Hom a c
  id_L  : ∀ {a b : Ob} (f : Hom a b), comp (id a) f = f
  id_R  : ∀ {a b : Ob} (f : Hom a b), comp f (id b) = f
  assoc : ∀ {a b c d : Ob} (f : Hom a b) (g : Hom b c) (h : Hom c d),
          comp f (comp g h) = comp (comp f g) h

/-- The verification category whose morphisms are typed strategy paths.
    This is the canonical algebra over the unary fragment of V. -/
def verifCategory : SmallCategory Color where
  Hom   := Path
  id    := Path.idPath
  comp  := Path.seqComp
  id_L  := Path.id_seqComp
  id_R  := Path.seqComp_id
  assoc := Path.seqComp_assoc

-- ════════════════════════════════════════════════════════════════════
-- § 8  Path length
-- ════════════════════════════════════════════════════════════════════

/-- The number of moves in a strategy sequence. -/
def Path.length {a b : Color} : Path a b → Nat
  | .nil        => 0
  | .cons _ _ p => 1 + p.length

/-- Length is additive under sequential composition. -/
theorem Path.length_seqComp {a b c : Color} :
    ∀ (p : Path a b) (q : Path b c),
    (p.seqComp q).length = p.length + q.length
  | .nil,        _ => by simp [Path.seqComp, Path.length]
  | .cons _ _ p, q => by
      simp only [Path.seqComp, Path.length]
      have ih := Path.length_seqComp p q
      omega

-- ════════════════════════════════════════════════════════════════════
-- § 9  Endomorphic (idempotent) generators
--       These correspond to quadratic relations R1–R5 of V.
-- ════════════════════════════════════════════════════════════════════

/-- A move is endomorphic if its source and target colors coincide.
    These satisfy the idempotency relation m ∘ m ~ m in the operad. -/
def Move.isEndo (m : Move) : Bool := m.src == m.tgt

theorem normalize_endo  : Move.isEndo .normalize  = true := by decide
theorem escalate_endo   : Move.isEndo .escalate   = true := by decide
theorem promote_endo    : Move.isEndo .promote    = true := by decide
theorem transport_endo  : Move.isEndo .transport  = true := by decide
theorem restrict_endo   : Move.isEndo .restrict_  = true := by decide

theorem verify_not_endo    : Move.isEndo .verify    = false := by decide
theorem construct_not_endo : Move.isEndo .construct = false := by decide
theorem glue_not_endo      : Move.isEndo .glue      = false := by decide
theorem repair_not_endo    : Move.isEndo .repair    = false := by decide
theorem challenge_not_endo : Move.isEndo .challenge = false := by decide

/-- Exactly five of the ten generators are endomorphic. -/
theorem endo_count :
    (([.normalize, .escalate, .promote, .transport, .restrict_] : List Move).filter
      Move.isEndo).length = 5 := by decide

-- ════════════════════════════════════════════════════════════════════
-- § 10  Valid and blocked composition pairs
-- ════════════════════════════════════════════════════════════════════

/-- Two moves are composable when the first's target equals the second's source. -/
def Move.composable (m1 m2 : Move) : Bool := m1.tgt == m2.src

/-- The complete list of all ten semantic moves. -/
def allMoves : List Move :=
  [.verify, .construct, .normalize, .glue, .restrict_,
   .transport, .repair, .promote, .challenge, .escalate]

theorem allMoves_length : allMoves.length = 10 := by decide

/-- All 100 ordered pairs of moves. -/
def allPairs : List (Move × Move) :=
  allMoves.bind (fun m1 => allMoves.map (fun m2 => (m1, m2)))

theorem allPairs_length : allPairs.length = 100 := by decide

/-- Valid pairs: type-compatible for sequential composition. -/
def validPairs : List (Move × Move) :=
  allPairs.filter (fun p => Move.composable p.1 p.2)

/-- Blocked pairs: type-obstructed.
    These become the generators of the Koszul dual V^!. -/
def blockedPairs : List (Move × Move) :=
  allPairs.filter (fun p => !Move.composable p.1 p.2)

/-- There are exactly 31 valid 2-step compositions. -/
theorem validPairs_length : validPairs.length = 31 := by native_decide

/-- There are exactly 69 blocked pairs (obstruction generators of V^!). -/
theorem blockedPairs_length : blockedPairs.length = 69 := by native_decide

/-- Valid and blocked pairs partition all 100 ordered pairs. -/
theorem valid_blocked_partition :
    validPairs.length + blockedPairs.length = allPairs.length := by native_decide

/-- The blocked pairs form the majority: more than twice the valid pairs. -/
theorem blocked_dominates_valid :
    blockedPairs.length > validPairs.length := by native_decide

-- ════════════════════════════════════════════════════════════════════
-- § 11  Reachability in the move-color graph
-- ════════════════════════════════════════════════════════════════════

/-- Direct 1-step reachability: is there a move from color `a` to color `b`? -/
def directlyReachable (a b : Color) : Bool :=
  allMoves.any (fun m => m.src == a && m.tgt == b)

theorem goal_to_verified    : directlyReachable .goal        .verified   = true := by decide
theorem goal_to_partial     : directlyReachable .goal        .partialPrf = true := by decide
theorem goal_to_goal        : directlyReachable .goal        .goal       = true := by decide
theorem obstr_to_goal       : directlyReachable .obstructed  .goal       = true := by decide
theorem verified_to_goal    : directlyReachable .verified    .goal       = true := by decide
theorem obstr_to_obstr      : directlyReachable .obstructed  .obstructed = true := by decide
theorem verified_to_verified : directlyReachable .verified   .verified   = true := by decide

/-- Partial proofs cannot be reached directly from obstructed claims. -/
theorem obstr_not_to_partial :
    directlyReachable .obstructed .partialPrf = false := by decide

-- ════════════════════════════════════════════════════════════════════
-- § 12  Explicit strategy witnesses
-- ════════════════════════════════════════════════════════════════════

/-- A single VERIFY discharges a goal directly. -/
theorem verify_strategy_exists :
    ∃ p : Path .goal .verified, p.length = 1 :=
  ⟨.cons .verify rfl .nil, rfl⟩

/-- REPAIR followed by VERIFY handles an obstructed claim in 2 steps. -/
theorem repair_then_verify :
    ∃ p : Path .obstructed .verified, p.length = 2 :=
  ⟨.cons .repair rfl (.cons .verify rfl .nil), rfl⟩

/-- NORMALIZE followed by VERIFY: simplify the goal, then close. -/
theorem normalize_then_verify :
    ∃ p : Path .goal .verified, p.length = 2 :=
  ⟨.cons .normalize rfl (.cons .verify rfl .nil), rfl⟩

/-- CONSTRUCT followed by GLUE: build a partial proof, then assemble. -/
theorem construct_then_glue :
    ∃ p : Path .goal .verified, p.length = 2 :=
  ⟨.cons .construct rfl (.cons .glue rfl .nil), rfl⟩

/-- ESCALATE, REPAIR, VERIFY: a 3-step obstruction recovery sequence. -/
theorem escalate_repair_verify :
    ∃ p : Path .obstructed .verified, p.length = 3 :=
  ⟨.cons .escalate rfl (.cons .repair rfl (.cons .verify rfl .nil)), rfl⟩

/-- CHALLENGE, NORMALIZE, VERIFY: re-examine and re-prove a claim. -/
theorem challenge_normalize_verify :
    ∃ p : Path .verified .verified, p.length = 3 :=
  ⟨.cons .challenge rfl (.cons .normalize rfl (.cons .verify rfl .nil)), rfl⟩

-- ════════════════════════════════════════════════════════════════════
-- § 13  Decomposition: every path factors through single steps
-- ════════════════════════════════════════════════════════════════════

/-- Every non-trivial path begins with a single-step sub-path.
    This is the key lemma for synthesis completeness: operadic composition
    generates ALL valid strategy sequences. -/
theorem Path.decomp_head {a b : Color} :
    ∀ (p : Path a b), p.length ≥ 1 →
    ∃ (m : Move) (h : m.src = a) (q : Path m.tgt b), p = .cons m h q
  | .cons m h q, _ => ⟨m, h, q, rfl⟩

/-- Every path is either empty or begins with a single-step composition. -/
theorem Path.all_paths_composed {a b : Color} :
    ∀ (p : Path a b),
    p.length = 0 ∨
    ∃ (m : Move) (h : m.src = a) (q : Path m.tgt b),
    p = (Path.cons m h Path.nil).seqComp q
  | .nil        => Or.inl rfl
  | .cons m h q => Or.inr ⟨m, h, q, by simp [Path.seqComp]⟩

/-- Composing a non-empty path strictly increases total length. -/
theorem Path.seqComp_length_strict {a b c : Color}
    (p : Path a b) (q : Path b c) (hp : p.length ≥ 1) :
    (p.seqComp q).length > q.length := by
  have := Path.length_seqComp p q; omega

-- ════════════════════════════════════════════════════════════════════
-- § 14  TypeChecks predicate (list-level operadic composition law)
-- ════════════════════════════════════════════════════════════════════

/-- TypeChecks a ms b: the move list ms is a valid strategy from color a to b.
    This is the propositional characterization of Path membership. -/
def TypeChecks : Color → List Move → Color → Prop
  | c, [],      d => c = d
  | c, m :: ms, d => m.src = c ∧ TypeChecks m.tgt ms d

theorem TypeChecks_nil {c : Color} : TypeChecks c [] c := rfl

/-- Sequential composition of type-checked sequences. -/
theorem TypeChecks_comp {a b c : Color} {ms ns : List Move} :
    TypeChecks a ms b → TypeChecks b ns c → TypeChecks a (ms ++ ns) c := by
  intro h1 h2
  induction ms generalizing a with
  | nil =>
    simp only [List.nil_append]
    cases h1; exact h2
  | cons m rest ih =>
    simp only [List.cons_append]
    obtain ⟨hm, hrest⟩ := h1
    exact ⟨hm, ih hrest h2⟩

/-- Right unit: appending [] preserves type-checking. -/
theorem TypeChecks_id_right {a b : Color} {ms : List Move}
    (h : TypeChecks a ms b) : TypeChecks a (ms ++ []) b := by
  rwa [List.append_nil]

/-- Associativity: re-bracketing concatenation preserves type-checking.
    This is the operadic associativity axiom at the list level. -/
theorem TypeChecks_assoc {a b c d : Color} {ms ns ks : List Move}
    (h1 : TypeChecks a ms b) (h2 : TypeChecks b ns c) (h3 : TypeChecks c ks d) :
    TypeChecks a (ms ++ ns ++ ks) d := by
  rw [List.append_assoc]
  exact TypeChecks_comp h1 (TypeChecks_comp h2 h3)

/-- The list-level operadic associativity law: (ms ++ ns) ++ ks = ms ++ (ns ++ ks). -/
theorem TypeChecks_comp_assoc_law (ms ns ks : List Move) :
    (ms ++ ns) ++ ks = ms ++ (ns ++ ks) := List.append_assoc ms ns ks

-- ════════════════════════════════════════════════════════════════════
-- § 15  Grand operad theorem (summary)
-- ════════════════════════════════════════════════════════════════════

/-- **Grand Operad Theorem**: The verification strategies form a category
    satisfying all operad axioms, with 31 valid 2-step compositions,
    69 blocked (Koszul-dual) pairs, and explicit strategies for all
    four goal-to-verified recovery patterns. -/
theorem grand_operad_theorem :
    -- (1) Category axioms hold for Path / seqComp
    (∀ {a b : Color} (p : Path a b), (Path.idPath a).seqComp p = p) ∧
    (∀ {a b : Color} (p : Path a b), p.seqComp (Path.idPath b) = p) ∧
    (∀ {a b c d : Color} (p : Path a b) (q : Path b c) (r : Path c d),
      p.seqComp (q.seqComp r) = (p.seqComp q).seqComp r) ∧
    -- (2) Exactly 31 valid move pairs
    validPairs.length = 31 ∧
    -- (3) Exactly 69 blocked (obstruction generator) pairs
    blockedPairs.length = 69 ∧
    -- (4) Direct verification strategy exists (length 1)
    (∃ p : Path .goal .verified, p.length = 1) ∧
    -- (5) Obstruction recovery strategy exists (length 2)
    (∃ p : Path .obstructed .verified, p.length = 2) := by
  exact ⟨Path.id_seqComp, Path.seqComp_id, Path.seqComp_assoc,
         validPairs_length, blockedPairs_length,
         verify_strategy_exists, repair_then_verify⟩

end JudgmentGeometry.Paper14
