"""CSS code generators — design system, layout, components, game UI, animations.

These are FRAMEWORK-level generators: given theme tokens and active concepts,
they produce a comprehensive CSS design system.  The output scales with the
``scale`` parameter — at scale=5 (production), this produces 3500+ lines of
CSS covering every component state, responsive breakpoint, animation, and
utility class.
"""
from __future__ import annotations

from . import register


def _design_system_css(theme: dict | None = None, scale: int = 3) -> str:
    t = theme or {}
    bg = t.get("bg", "#0a0a1a")
    surface = t.get("bg_surface", "#141428")
    card = t.get("bg_card", "#1e1e3a")
    primary = t.get("primary", "#6366f1")
    primary_lt = t.get("primary_light", "#818cf8")
    primary_dk = t.get("primary_dark", "#4338ca")
    accent = t.get("accent", "#f59e0b")
    accent_lt = t.get("accent_light", "#fbbf24")
    text = t.get("text", "#e2e8f0")
    muted = t.get("text_muted", "#94a3b8")
    success = t.get("success", "#10b981")
    warning = t.get("warning", "#f59e0b")
    danger = t.get("danger", "#ef4444")
    info = t.get("info", "#3b82f6")

    lines = [f"""\
/* ══════════════════════════════════════════════════════════════════════
   Design System — Generated by jugeo-webapp CSS generator
   Scale: {scale}
   ══════════════════════════════════════════════════════════════════════ */

/* ── Custom Properties ──────────────────────────────────────────── */
:root {{
  /* Colors — primary palette */
  --ct-bg: {bg};
  --ct-surface: {surface};
  --ct-card: {card};
  --ct-primary: {primary};
  --ct-primary-light: {primary_lt};
  --ct-primary-dark: {primary_dk};
  --ct-accent: {accent};
  --ct-accent-light: {accent_lt};

  /* Colors — text */
  --ct-text: {text};
  --ct-text-muted: {muted};

  /* Colors — semantic */
  --ct-success: {success};
  --ct-warning: {warning};
  --ct-danger: {danger};
  --ct-info: {info};

  /* Spacing scale */
  --ct-space-1: 0.25rem;
  --ct-space-2: 0.5rem;
  --ct-space-3: 0.75rem;
  --ct-space-4: 1rem;
  --ct-space-6: 1.5rem;
  --ct-space-8: 2rem;
  --ct-space-12: 3rem;
  --ct-space-16: 4rem;

  /* Border radius */
  --ct-radius: 8px;
  --ct-radius-sm: 4px;
  --ct-radius-lg: 16px;
  --ct-radius-xl: 24px;
  --ct-radius-full: 9999px;

  /* Shadows */
  --ct-shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.3);
  --ct-shadow: 0 4px 12px rgba(0, 0, 0, 0.4);
  --ct-shadow-lg: 0 8px 32px rgba(0, 0, 0, 0.5);
  --ct-shadow-xl: 0 16px 48px rgba(0, 0, 0, 0.6);

  /* Typography */
  --ct-font: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  --ct-font-mono: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
  --ct-font-display: 'Inter', -apple-system, sans-serif;

  /* Transitions */
  --ct-transition: 0.2s ease;
  --ct-transition-slow: 0.4s ease;
  --ct-transition-fast: 0.1s ease;

  /* Z-index layers */
  --ct-z-dropdown: 100;
  --ct-z-sticky: 120;
  --ct-z-modal: 200;
  --ct-z-toast: 300;
  --ct-z-tooltip: 400;
  --ct-z-debug: 9999;
}}

/* ── Reset & Base ───────────────────────────────────────────────── */
*, *::before, *::after {{
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}}

html {{
  font-size: 16px;
  scroll-behavior: smooth;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
}}

body {{
  font-family: var(--ct-font);
  background: var(--ct-bg);
  color: var(--ct-text);
  line-height: 1.6;
  min-height: 100vh;
  overflow-x: hidden;
}}

/* ── Typography ─────────────────────────────────────────────────── */
h1 {{ font-size: 2.5rem; font-weight: 800; line-height: 1.2; letter-spacing: -0.02em; margin-bottom: 1rem; font-family: var(--ct-font-display); }}
h2 {{ font-size: 2rem; font-weight: 700; line-height: 1.25; letter-spacing: -0.01em; margin-bottom: 0.75rem; }}
h3 {{ font-size: 1.5rem; font-weight: 600; line-height: 1.3; margin-bottom: 0.5rem; }}
h4 {{ font-size: 1.25rem; font-weight: 600; line-height: 1.35; margin-bottom: 0.5rem; }}
h5 {{ font-size: 1.1rem; font-weight: 500; margin-bottom: 0.4rem; }}
h6 {{ font-size: 0.95rem; font-weight: 500; color: var(--ct-text-muted); margin-bottom: 0.4rem; }}
p {{ margin-bottom: 1rem; color: var(--ct-text-muted); }}
a {{ color: var(--ct-primary-light); text-decoration: none; transition: color var(--ct-transition); }}
a:hover {{ color: var(--ct-accent); }}
code {{ font-family: var(--ct-font-mono); font-size: 0.9em; background: var(--ct-surface); padding: 0.15em 0.4em; border-radius: var(--ct-radius-sm); }}
pre {{ font-family: var(--ct-font-mono); background: var(--ct-surface); padding: 1rem; border-radius: var(--ct-radius); overflow-x: auto; margin-bottom: 1rem; border: 1px solid rgba(255,255,255,0.05); }}
img {{ max-width: 100%; height: auto; display: block; }}
strong {{ font-weight: 600; color: var(--ct-text); }}
small {{ font-size: 0.85em; color: var(--ct-text-muted); }}
::selection {{ background: var(--ct-primary); color: white; }}

/* ── Scrollbar ──────────────────────────────────────────────────── */
::-webkit-scrollbar {{ width: 8px; height: 8px; }}
::-webkit-scrollbar-track {{ background: var(--ct-bg); }}
::-webkit-scrollbar-thumb {{ background: var(--ct-surface); border-radius: 4px; }}
::-webkit-scrollbar-thumb:hover {{ background: var(--ct-primary-dark); }}

/* ── Focus ──────────────────────────────────────────────────────── */
:focus-visible {{ outline: 2px solid var(--ct-primary); outline-offset: 2px; }}
:focus:not(:focus-visible) {{ outline: none; }}

/* ── Text utilities ─────────────────────────────────────────────── */
.text-muted {{ color: var(--ct-text-muted); }}
.text-primary {{ color: var(--ct-primary-light); }}
.text-accent {{ color: var(--ct-accent); }}
.text-success {{ color: var(--ct-success); }}
.text-warning {{ color: var(--ct-warning); }}
.text-danger {{ color: var(--ct-danger); }}
.text-info {{ color: var(--ct-info); }}
.text-sm {{ font-size: 0.875rem; }}
.text-lg {{ font-size: 1.125rem; }}
.text-xl {{ font-size: 1.5rem; }}
.text-2xl {{ font-size: 2rem; }}
.text-center {{ text-align: center; }}
.text-right {{ text-align: right; }}
.font-mono {{ font-family: var(--ct-font-mono); }}
.font-bold {{ font-weight: 700; }}
.font-light {{ font-weight: 300; }}
.sr-only {{ position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; }}
.truncate {{ overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
.line-clamp-2 {{ display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }}
.line-clamp-3 {{ display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }}"""]

    if scale >= 3:
        lines.append("""\
/* ── Misc text & list utilities ─ */
.opacity-0 { opacity: 0; } .opacity-50 { opacity: 0.5; } .opacity-100 { opacity: 1; }
.pointer-events-none { pointer-events: none; }
.select-none { user-select: none; }
.cursor-pointer { cursor: pointer; }
.cursor-grab { cursor: grab; }
.cursor-grabbing { cursor: grabbing; }
.overflow-hidden { overflow: hidden; }
.overflow-auto { overflow: auto; }
.overflow-x-auto { overflow-x: auto; overflow-y: hidden; }
hr { border: none; border-top: 1px solid rgba(255,255,255,0.06); margin: 1.5rem 0; }
mark { background: var(--ct-accent); color: var(--ct-bg); padding: 0.1em 0.3em; border-radius: 2px; }
blockquote { border-left: 3px solid var(--ct-primary); padding-left: 1rem; color: var(--ct-text-muted); margin: 1rem 0; font-style: italic; }
ul, ol { padding-left: 1.5rem; margin-bottom: 1rem; color: var(--ct-text-muted); }
li { margin-bottom: 0.25rem; }
table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; }
th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid rgba(255,255,255,0.06); }
th { font-weight: 600; color: var(--ct-text); background: var(--ct-surface); }
tbody tr:hover { background: rgba(255,255,255,0.02); }
dt { font-weight: 600; color: var(--ct-text); margin-top: 0.75rem; }
dd { color: var(--ct-text-muted); margin-left: 1rem; }""")

    return "\n".join(lines)


def _layout_css(scale: int = 3) -> str:
    lines = ["""\
/* ── Layout Utilities ─────────────────────────────────────────── */
.container { width: 100%; max-width: 1200px; margin: 0 auto; padding: 0 1.5rem; }
.container-sm { max-width: 800px; }
.container-lg { max-width: 1400px; }
.container-xl { max-width: 1600px; }

/* Grid system */
.grid { display: grid; gap: 1.5rem; }
.grid-2 { grid-template-columns: repeat(2, 1fr); }
.grid-3 { grid-template-columns: repeat(3, 1fr); }
.grid-4 { grid-template-columns: repeat(4, 1fr); }
.grid-5 { grid-template-columns: repeat(5, 1fr); }
.grid-6 { grid-template-columns: repeat(6, 1fr); }
.grid-auto { grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); }
.grid-auto-sm { grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); }

/* Flexbox */
.flex { display: flex; gap: 1rem; }
.flex-col { flex-direction: column; }
.flex-row { flex-direction: row; }
.flex-wrap { flex-wrap: wrap; }
.flex-center { align-items: center; justify-content: center; }
.flex-between { justify-content: space-between; align-items: center; }
.flex-end { justify-content: flex-end; }
.flex-1 { flex: 1; }
.flex-none { flex: none; }
.flex-shrink-0 { flex-shrink: 0; }
.items-center { align-items: center; }
.items-start { align-items: flex-start; }
.items-end { align-items: flex-end; }
.items-stretch { align-items: stretch; }
.justify-center { justify-content: center; }
.justify-between { justify-content: space-between; }
.justify-end { justify-content: flex-end; }
.justify-around { justify-content: space-around; }
.self-center { align-self: center; }
.self-start { align-self: flex-start; }
.self-end { align-self: flex-end; }

/* Gap */
.gap-0 { gap: 0; } .gap-1 { gap: 0.25rem; } .gap-2 { gap: 0.5rem; }
.gap-3 { gap: 0.75rem; } .gap-4 { gap: 1rem; } .gap-5 { gap: 1.25rem; }
.gap-6 { gap: 1.5rem; } .gap-8 { gap: 2rem; } .gap-10 { gap: 2.5rem; }
.gap-12 { gap: 3rem; }"""]

    # Spacing utilities
    spacings = [("0", "0"), ("1", "0.25rem"), ("2", "0.5rem"), ("3", "0.75rem"),
                ("4", "1rem"), ("5", "1.25rem"), ("6", "1.5rem"), ("8", "2rem"),
                ("10", "2.5rem"), ("12", "3rem"), ("16", "4rem")]
    for prop_prefix, css_prop in [("m", "margin"), ("p", "padding")]:
        for suffix, val in spacings:
            lines.append(f".{prop_prefix}-{suffix} {{ {css_prop}: {val}; }}")
        for side, css_side in [("t", "top"), ("b", "bottom"), ("l", "left"), ("r", "right")]:
            for suffix, val in spacings:
                lines.append(f".{prop_prefix}{side}-{suffix} {{ {css_prop}-{css_side}: {val}; }}")
        lines.append(f".{prop_prefix}x-auto {{ {css_prop}-left: auto; {css_prop}-right: auto; }}")

    lines.append("""\

/* Dimensions */
.w-full { width: 100%; } .w-auto { width: auto; } .w-screen { width: 100vw; }
.h-full { height: 100%; } .h-auto { height: auto; } .h-screen { height: 100vh; }
.min-h-screen { min-height: 100vh; }
.max-w-xs { max-width: 20rem; }
.max-w-sm { max-width: 24rem; }
.max-w-md { max-width: 28rem; }
.max-w-lg { max-width: 32rem; }
.max-w-xl { max-width: 36rem; }
.max-w-full { max-width: 100%; }

/* Position */
.relative { position: relative; }
.absolute { position: absolute; }
.fixed { position: fixed; }
.sticky { position: sticky; top: 0; }
.inset-0 { inset: 0; }
.top-0 { top: 0; } .right-0 { right: 0; } .bottom-0 { bottom: 0; } .left-0 { left: 0; }

/* Display */
.hidden { display: none; }
.block { display: block; }
.inline-block { display: inline-block; }
.inline-flex { display: inline-flex; }

/* ── App shell layout ─────────────────────────────────────── */
.ct-app {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.ct-nav {
  display: flex;
  align-items: center;
  gap: 1.5rem;
  padding: 0.75rem 1.5rem;
  background: var(--ct-surface);
  border-bottom: 1px solid rgba(255,255,255,0.06);
  position: sticky;
  top: 0;
  z-index: var(--ct-z-sticky);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
}

.ct-nav__brand {
  font-weight: 700;
  font-size: 1.1rem;
  color: var(--ct-text);
  white-space: nowrap;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.ct-nav__links {
  display: flex;
  gap: 0.5rem;
  overflow-x: auto;
  scrollbar-width: none;
}
.ct-nav__links::-webkit-scrollbar { display: none; }

.ct-nav__links a {
  color: var(--ct-text-muted);
  font-size: 0.9rem;
  padding: 0.3rem 0.7rem;
  border-radius: var(--ct-radius-sm);
  transition: all var(--ct-transition);
  white-space: nowrap;
}
.ct-nav__links a:hover,
.ct-nav__links a.active {
  color: var(--ct-text);
  background: rgba(255,255,255,0.05);
}
.ct-nav__links a.active {
  color: var(--ct-primary-light);
  background: rgba(99,102,241,0.1);
}

.ct-nav__actions {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-left: auto;
}

.ct-hamburger {
  display: none;
  background: none;
  border: none;
  color: var(--ct-text);
  font-size: 1.5rem;
  cursor: pointer;
  padding: 0.25rem;
}

.ct-main { flex: 1; padding: 2rem 1.5rem; }

.ct-footer {
  padding: 1.5rem;
  text-align: center;
  color: var(--ct-text-muted);
  font-size: 0.8rem;
  border-top: 1px solid rgba(255,255,255,0.06);
}

.ct-sidebar {
  width: 280px;
  background: var(--ct-surface);
  border-right: 1px solid rgba(255,255,255,0.06);
  padding: 1rem;
  overflow-y: auto;
  transition: width var(--ct-transition-slow), padding var(--ct-transition-slow);
  flex-shrink: 0;
}
.ct-sidebar.collapsed {
  width: 0;
  padding: 0;
  overflow: hidden;
  border-right: none;
}

.ct-layout { display: flex; flex: 1; overflow: hidden; }
.ct-layout__main { flex: 1; overflow-y: auto; }

/* ── Section wrapper ── */
.ct-section {
  padding: var(--ct-space-12) 0;
}
.ct-section + .ct-section {
  border-top: 1px solid rgba(255,255,255,0.04);
}
.ct-section__header {
  margin-bottom: var(--ct-space-8);
}
.ct-section__header h2 {
  margin-bottom: var(--ct-space-2);
}
.ct-section__header p {
  max-width: 600px;
}""")
    lines.append("""\

/* ── Responsive ─────────────────────────────────────────────── */
@media (max-width: 1440px) {
  .container-lg { max-width: 1200px; }
  .hide-xxl { display: none; }
}

@media (max-width: 1024px) {
  .grid-4, .grid-5, .grid-6 { grid-template-columns: repeat(2, 1fr); }
  .grid-3 { grid-template-columns: repeat(2, 1fr); }
  .ct-sidebar { width: 220px; }
  .hide-lg { display: none; }
  .show-lg { display: block; }
}

@media (max-width: 768px) {
  html { font-size: 15px; }
  .grid-2, .grid-3, .grid-4, .grid-5, .grid-6 { grid-template-columns: 1fr; }
  .ct-nav { flex-wrap: wrap; padding: 0.5rem 1rem; }
  .ct-nav__links { width: 100%; order: 3; }
  .ct-hamburger { display: block; }
  .ct-nav__links { display: none; flex-direction: column; gap: 0; }
  .ct-nav__links.open { display: flex; }
  .ct-nav__links a { padding: 0.6rem 0.7rem; }
  .ct-sidebar {
    position: fixed;
    left: 0; top: 0;
    height: 100vh;
    z-index: var(--ct-z-modal);
    transform: translateX(-100%);
    transition: transform var(--ct-transition-slow);
    width: 280px;
  }
  .ct-sidebar.open { transform: translateX(0); }
  .ct-main { padding: 1rem; }
  h1 { font-size: 1.75rem; }
  h2 { font-size: 1.5rem; }
  .flex:not(.flex-col) { flex-direction: column; }
  .hide-md { display: none; }
  .show-md { display: block; }
}

@media (max-width: 480px) {
  html { font-size: 14px; }
  .ct-main { padding: 0.75rem; }
  .container { padding: 0 0.75rem; }
  h1 { font-size: 1.5rem; }
  h2 { font-size: 1.25rem; }
  .hide-sm { display: none; }
  .show-sm { display: block; }
  .card { padding: 1rem; }
  .modal { min-width: auto; width: calc(100vw - 2rem); }
}

@media (min-width: 1441px) {
  .container { max-width: 1400px; }
  .show-xl { display: block; }
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}""")

    return "\n".join(lines)


def _components_css(scale: int = 3) -> str:
    lines = ["""\
/* ══════════════════════════════════════════════════════════════════════
   Components
   ══════════════════════════════════════════════════════════════════════ */

/* ── Buttons ────────────────────────────────────────────────────── */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.6rem 1.25rem;
  border: none;
  border-radius: var(--ct-radius);
  font-family: var(--ct-font);
  font-size: 0.9rem;
  font-weight: 500;
  cursor: pointer;
  transition: all var(--ct-transition);
  text-decoration: none;
  line-height: 1.4;
  white-space: nowrap;
}
.btn:disabled { opacity: 0.5; cursor: not-allowed; pointer-events: none; }
.btn-primary { background: var(--ct-primary); color: white; }
.btn-primary:hover { background: var(--ct-primary-light); box-shadow: 0 0 20px rgba(99,102,241,0.3); transform: translateY(-1px); }
.btn-primary:active { transform: translateY(0); box-shadow: none; }
.btn-accent { background: var(--ct-accent); color: var(--ct-bg); font-weight: 600; }
.btn-accent:hover { background: var(--ct-accent-light); box-shadow: 0 0 20px rgba(245,158,11,0.3); }
.btn-success { background: var(--ct-success); color: white; }
.btn-success:hover { filter: brightness(1.1); }
.btn-danger { background: var(--ct-danger); color: white; }
.btn-danger:hover { filter: brightness(1.1); }
.btn-info { background: var(--ct-info); color: white; }
.btn-info:hover { filter: brightness(1.1); }
.btn-ghost { background: transparent; color: var(--ct-text-muted); border: 1px solid rgba(255,255,255,0.1); }
.btn-ghost:hover { color: var(--ct-text); background: rgba(255,255,255,0.05); border-color: rgba(255,255,255,0.2); }
.btn-link { background: none; border: none; color: var(--ct-primary-light); padding: 0; }
.btn-link:hover { color: var(--ct-accent); text-decoration: underline; }
.btn-sm { padding: 0.35rem 0.75rem; font-size: 0.8rem; }
.btn-lg { padding: 0.8rem 2rem; font-size: 1rem; }
.btn-xl { padding: 1rem 2.5rem; font-size: 1.1rem; }
.btn-icon { width: 2.5rem; height: 2.5rem; padding: 0; border-radius: var(--ct-radius-full); }
.btn-icon-sm { width: 2rem; height: 2rem; padding: 0; border-radius: var(--ct-radius-full); font-size: 0.8rem; }
.btn-block { width: 100%; }
.btn-group { display: flex; gap: 0; }
.btn-group .btn { border-radius: 0; }
.btn-group .btn:first-child { border-radius: var(--ct-radius) 0 0 var(--ct-radius); }
.btn-group .btn:last-child { border-radius: 0 var(--ct-radius) var(--ct-radius) 0; }

/* ── Cards ──────────────────────────────────────────────────────── */
.card {
  background: var(--ct-card);
  border-radius: var(--ct-radius-lg);
  padding: 1.5rem;
  border: 1px solid rgba(255,255,255,0.04);
  transition: all var(--ct-transition);
}
.card:hover { transform: translateY(-2px); box-shadow: var(--ct-shadow-lg); border-color: rgba(255,255,255,0.08); }
.card-flat { border: none; background: var(--ct-surface); }
.card-flat:hover { transform: none; box-shadow: none; }
.card-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 1rem; padding-bottom: 0.75rem; border-bottom: 1px solid rgba(255,255,255,0.06); }
.card-body { }
.card-footer { margin-top: 1rem; padding-top: 0.75rem; border-top: 1px solid rgba(255,255,255,0.06); display: flex; justify-content: flex-end; gap: 0.5rem; }
.card-image { margin: -1.5rem -1.5rem 1.5rem; border-radius: var(--ct-radius-lg) var(--ct-radius-lg) 0 0; overflow: hidden; }
.card-image img { width: 100%; aspect-ratio: 16/9; object-fit: cover; }
.card-compact { padding: 1rem; }

/* ── Modals ─────────────────────────────────────────────────────── */
.modal-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.6);
  backdrop-filter: blur(4px);
  z-index: var(--ct-z-modal);
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  visibility: hidden;
  transition: all var(--ct-transition);
}
.modal-backdrop.active { opacity: 1; visibility: visible; }
.modal {
  background: var(--ct-card);
  border-radius: var(--ct-radius-lg);
  padding: 2rem;
  min-width: 400px;
  max-width: 90vw;
  max-height: 85vh;
  overflow-y: auto;
  box-shadow: var(--ct-shadow-xl);
  transform: scale(0.95) translateY(10px);
  transition: transform var(--ct-transition);
  border: 1px solid rgba(255,255,255,0.06);
}
.modal-backdrop.active .modal { transform: scale(1) translateY(0); }
.modal-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 1.5rem; }
.modal-header h2, .modal-header h3 { margin-bottom: 0; }
.modal-close { background: none; border: none; color: var(--ct-text-muted); font-size: 1.5rem; cursor: pointer; padding: 0.25rem; line-height: 1; border-radius: var(--ct-radius-sm); transition: all var(--ct-transition); }
.modal-close:hover { color: var(--ct-text); background: rgba(255,255,255,0.05); }
.modal-footer { margin-top: 1.5rem; padding-top: 1rem; border-top: 1px solid rgba(255,255,255,0.06); display: flex; justify-content: flex-end; gap: 0.5rem; }

/* ── Forms ──────────────────────────────────────────────────────── */
.form-group { margin-bottom: 1.25rem; }
.form-group label { display: block; margin-bottom: 0.4rem; font-size: 0.875rem; font-weight: 500; color: var(--ct-text); }
.form-row { display: flex; gap: 1rem; }
.form-row .form-group { flex: 1; }

input[type="text"], input[type="email"], input[type="password"], input[type="number"],
input[type="search"], input[type="url"], input[type="tel"], textarea, select {
  width: 100%;
  padding: 0.6rem 0.9rem;
  background: var(--ct-surface);
  border: 1px solid rgba(255,255,255,0.1);
  border-radius: var(--ct-radius);
  color: var(--ct-text);
  font-family: var(--ct-font);
  font-size: 0.9rem;
  transition: border-color var(--ct-transition), box-shadow var(--ct-transition);
}
input:focus, textarea:focus, select:focus {
  border-color: var(--ct-primary);
  box-shadow: 0 0 0 3px rgba(99,102,241,0.2);
  outline: none;
}
input::placeholder, textarea::placeholder { color: var(--ct-text-muted); opacity: 0.7; }
textarea { resize: vertical; min-height: 100px; }
select {
  appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' fill='%2394a3b8' viewBox='0 0 16 16'%3E%3Cpath d='M8 11L3 6h10z'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 0.75rem center;
  padding-right: 2.5rem;
}
.form-hint { font-size: 0.8rem; color: var(--ct-text-muted); margin-top: 0.3rem; }
.form-error { font-size: 0.8rem; color: var(--ct-danger); margin-top: 0.3rem; }
input.invalid, textarea.invalid, select.invalid { border-color: var(--ct-danger); }
input.valid, textarea.valid, select.valid { border-color: var(--ct-success); }

/* ── Badges ─────────────────────────────────────────────────────── */
.badge { display: inline-flex; align-items: center; padding: 0.2rem 0.6rem; font-size: 0.75rem; font-weight: 600; border-radius: var(--ct-radius-full); }
.badge-primary { background: rgba(99,102,241,0.15); color: var(--ct-primary-light); }
.badge-success { background: rgba(16,185,129,0.15); color: var(--ct-success); }
.badge-warning { background: rgba(245,158,11,0.15); color: var(--ct-warning); }
.badge-danger { background: rgba(239,68,68,0.15); color: var(--ct-danger); }
.badge-info { background: rgba(59,130,246,0.15); color: var(--ct-info); }
.badge-neutral { background: rgba(148,163,184,0.15); color: var(--ct-text-muted); }

/* ── Progress ───────────────────────────────────────────────────── */
.progress { height: 8px; background: var(--ct-surface); border-radius: var(--ct-radius-full); overflow: hidden; }
.progress-bar { height: 100%; background: var(--ct-primary); border-radius: var(--ct-radius-full); transition: width var(--ct-transition-slow); }
.progress-bar.success { background: var(--ct-success); }
.progress-bar.warning { background: var(--ct-warning); }
.progress-bar.danger { background: var(--ct-danger); }
.progress-striped .progress-bar { background-image: linear-gradient(45deg, rgba(255,255,255,0.1) 25%, transparent 25%, transparent 50%, rgba(255,255,255,0.1) 50%, rgba(255,255,255,0.1) 75%, transparent 75%); background-size: 1rem 1rem; animation: progressStripe 1s linear infinite; }

/* ── Tabs ───────────────────────────────────────────────────────── */
.tabs { display: flex; border-bottom: 1px solid rgba(255,255,255,0.06); gap: 0; overflow-x: auto; scrollbar-width: none; }
.tabs::-webkit-scrollbar { display: none; }
.tab { padding: 0.6rem 1.25rem; cursor: pointer; color: var(--ct-text-muted); font-size: 0.9rem; border-bottom: 2px solid transparent; transition: all var(--ct-transition); background: none; border-top: none; border-left: none; border-right: none; white-space: nowrap; }
.tab:hover { color: var(--ct-text); background: rgba(255,255,255,0.02); }
.tab.active { color: var(--ct-primary-light); border-bottom-color: var(--ct-primary); }
.tab-content { display: none; padding: 1.5rem 0; }
.tab-content.active { display: block; }

/* ── Toggle switch ──────────────────────────────────────────────── */
.toggle { position: relative; display: inline-block; width: 44px; height: 24px; }
.toggle input { opacity: 0; width: 0; height: 0; }
.toggle-slider { position: absolute; inset: 0; background: var(--ct-surface); border-radius: 12px; cursor: pointer; transition: var(--ct-transition); border: 1px solid rgba(255,255,255,0.1); }
.toggle-slider::before { content: ''; position: absolute; height: 18px; width: 18px; left: 2px; bottom: 2px; background: white; border-radius: 50%; transition: var(--ct-transition); }
.toggle input:checked + .toggle-slider { background: var(--ct-primary); border-color: var(--ct-primary); }
.toggle input:checked + .toggle-slider::before { transform: translateX(20px); }

/* ── Tooltips ───────────────────────────────────────────────────── */
.tooltip { position: relative; }
.tooltip::after { content: attr(data-tooltip); position: absolute; bottom: calc(100% + 8px); left: 50%; transform: translateX(-50%); background: var(--ct-surface); color: var(--ct-text); padding: 0.4rem 0.75rem; border-radius: var(--ct-radius-sm); font-size: 0.8rem; white-space: nowrap; pointer-events: none; opacity: 0; transition: opacity var(--ct-transition); z-index: var(--ct-z-tooltip); box-shadow: var(--ct-shadow); border: 1px solid rgba(255,255,255,0.06); }
.tooltip:hover::after { opacity: 1; }"""]

    if scale >= 3:
        lines.append("""\
/* ── Dropdown ───────────────────────────────────────────────── */
.dropdown { position: relative; display: inline-block; }
.dropdown-menu { position: absolute; top: calc(100% + 4px); left: 0; min-width: 180px; background: var(--ct-card); border: 1px solid rgba(255,255,255,0.08); border-radius: var(--ct-radius); box-shadow: var(--ct-shadow-lg); z-index: var(--ct-z-dropdown); opacity: 0; visibility: hidden; transform: translateY(-4px); transition: all var(--ct-transition); }
.dropdown.open .dropdown-menu { opacity: 1; visibility: visible; transform: translateY(0); }
.dropdown-item { display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem 1rem; color: var(--ct-text-muted); font-size: 0.875rem; cursor: pointer; transition: all var(--ct-transition); }
.dropdown-item:hover { background: rgba(255,255,255,0.05); color: var(--ct-text); }
.dropdown-item.active { color: var(--ct-primary-light); }
.dropdown-divider { border-top: 1px solid rgba(255,255,255,0.06); margin: 0.25rem 0; }
.dropdown-header { padding: 0.5rem 1rem; font-size: 0.75rem; font-weight: 600; color: var(--ct-text-muted); text-transform: uppercase; letter-spacing: 0.05em; }

/* ── Range slider ───────────────────────────────────────────── */
input[type="range"] { -webkit-appearance: none; width: 100%; height: 6px; background: var(--ct-surface); border-radius: 3px; outline: none; }
input[type="range"]::-webkit-slider-thumb { -webkit-appearance: none; width: 18px; height: 18px; background: var(--ct-primary); border-radius: 50%; cursor: pointer; border: 2px solid var(--ct-bg); box-shadow: 0 0 4px rgba(99,102,241,0.4); transition: all var(--ct-transition); }
input[type="range"]::-webkit-slider-thumb:hover { transform: scale(1.2); box-shadow: 0 0 8px rgba(99,102,241,0.6); }
input[type="range"]::-moz-range-thumb { width: 18px; height: 18px; background: var(--ct-primary); border-radius: 50%; cursor: pointer; border: 2px solid var(--ct-bg); }

/* ── Checkbox & Radio ───────────────────────────────────────── */
.checkbox, .radio { display: flex; align-items: center; gap: 0.5rem; cursor: pointer; font-size: 0.9rem; color: var(--ct-text-muted); }
.checkbox input, .radio input { width: 18px; height: 18px; accent-color: var(--ct-primary); cursor: pointer; }""")

    if scale >= 4:
        lines.append("""\
/* ── Toast notifications ────────────────────────────────────── */
.toast-container { position: fixed; top: 1rem; right: 1rem; z-index: var(--ct-z-toast); display: flex; flex-direction: column; gap: 0.5rem; pointer-events: none; max-width: 400px; }
.toast { pointer-events: all; display: flex; align-items: flex-start; gap: 0.75rem; padding: 0.75rem 1.25rem; background: var(--ct-card); border-radius: var(--ct-radius); box-shadow: var(--ct-shadow-lg); border-left: 3px solid var(--ct-primary); animation: slideInRight 0.3s ease; min-width: 280px; }
.toast.success { border-left-color: var(--ct-success); }
.toast.warning { border-left-color: var(--ct-warning); }
.toast.error { border-left-color: var(--ct-danger); }
.toast-icon { font-size: 1.1rem; flex-shrink: 0; margin-top: 0.1rem; }
.toast-body { flex: 1; }
.toast-title { font-weight: 600; font-size: 0.9rem; color: var(--ct-text); }
.toast-message { font-size: 0.85rem; color: var(--ct-text-muted); margin-top: 0.15rem; }
.toast-close { background: none; border: none; color: var(--ct-text-muted); cursor: pointer; margin-left: auto; font-size: 1.1rem; flex-shrink: 0; padding: 0; line-height: 1; }
.toast-close:hover { color: var(--ct-text); }

/* ── Accordion ──────────────────────────────────────────────── */
.accordion { border: 1px solid rgba(255,255,255,0.06); border-radius: var(--ct-radius); overflow: hidden; }
.accordion-item { border-bottom: 1px solid rgba(255,255,255,0.06); }
.accordion-item:last-child { border-bottom: none; }
.accordion-trigger { width: 100%; display: flex; align-items: center; justify-content: space-between; padding: 1rem 1.25rem; background: none; border: none; color: var(--ct-text); font-family: var(--ct-font); font-size: 0.95rem; font-weight: 500; cursor: pointer; transition: background var(--ct-transition); }
.accordion-trigger:hover { background: rgba(255,255,255,0.02); }
.accordion-trigger::after { content: '+'; font-size: 1.2rem; color: var(--ct-text-muted); transition: transform var(--ct-transition); flex-shrink: 0; }
.accordion-item.open .accordion-trigger::after { content: '\\2212'; }
.accordion-content { max-height: 0; overflow: hidden; transition: max-height var(--ct-transition-slow); }
.accordion-item.open .accordion-content { max-height: 500px; }
.accordion-body { padding: 0 1.25rem 1rem; color: var(--ct-text-muted); font-size: 0.9rem; line-height: 1.6; }

/* ── Breadcrumbs ────────────────────────────────────────────── */
.breadcrumb { display: flex; align-items: center; gap: 0.5rem; font-size: 0.85rem; color: var(--ct-text-muted); flex-wrap: wrap; }
.breadcrumb-separator { color: rgba(255,255,255,0.2); }
.breadcrumb a { color: var(--ct-text-muted); }
.breadcrumb a:hover { color: var(--ct-primary-light); }
.breadcrumb-current { color: var(--ct-text); font-weight: 500; }

/* ── Pagination ─────────────────────────────────────────────── */
.pagination { display: flex; align-items: center; gap: 0.25rem; }
.page-btn { width: 2.25rem; height: 2.25rem; display: flex; align-items: center; justify-content: center; border: 1px solid rgba(255,255,255,0.08); border-radius: var(--ct-radius-sm); background: none; color: var(--ct-text-muted); font-size: 0.85rem; cursor: pointer; transition: all var(--ct-transition); }
.page-btn:hover { background: rgba(255,255,255,0.05); color: var(--ct-text); }
.page-btn.active { background: var(--ct-primary); border-color: var(--ct-primary); color: white; }
.page-btn:disabled { opacity: 0.3; cursor: not-allowed; }""")

    if scale >= 5:
        lines.append("""\
/* ── Skeleton loading ───────────────────────────────────────── */
.skeleton { background: linear-gradient(90deg, var(--ct-surface) 25%, rgba(255,255,255,0.05) 50%, var(--ct-surface) 75%); background-size: 200% 100%; animation: shimmer 1.5s infinite; border-radius: var(--ct-radius-sm); }
.skeleton-text { height: 1rem; margin-bottom: 0.5rem; width: 80%; }
.skeleton-text:last-child { width: 60%; }
.skeleton-title { height: 1.5rem; margin-bottom: 0.75rem; width: 50%; }
.skeleton-circle { width: 48px; height: 48px; border-radius: 50%; }
.skeleton-card { height: 200px; border-radius: var(--ct-radius); }
.skeleton-avatar { width: 40px; height: 40px; border-radius: 50%; }

/* ── Empty state ────────────────────────────────────────────── */
.empty-state { text-align: center; padding: 3rem 1.5rem; color: var(--ct-text-muted); }
.empty-state__icon { font-size: 3rem; margin-bottom: 1rem; opacity: 0.5; }
.empty-state__title { font-size: 1.25rem; font-weight: 600; color: var(--ct-text); margin-bottom: 0.5rem; }
.empty-state__desc { max-width: 400px; margin: 0 auto 1.5rem; }

/* ── Avatar ─────────────────────────────────────────────────── */
.avatar { width: 40px; height: 40px; border-radius: 50%; background: var(--ct-primary); display: flex; align-items: center; justify-content: center; font-weight: 700; color: white; font-size: 0.9rem; flex-shrink: 0; overflow: hidden; }
.avatar img { width: 100%; height: 100%; object-fit: cover; }
.avatar-sm { width: 28px; height: 28px; font-size: 0.7rem; }
.avatar-lg { width: 56px; height: 56px; font-size: 1.2rem; }
.avatar-xl { width: 72px; height: 72px; font-size: 1.5rem; }
.avatar-group { display: flex; }
.avatar-group .avatar { margin-left: -8px; border: 2px solid var(--ct-bg); }
.avatar-group .avatar:first-child { margin-left: 0; }

/* ── Chip / Tag ─────────────────────────────────────────────── */
.chip { display: inline-flex; align-items: center; gap: 0.3rem; padding: 0.25rem 0.75rem; background: var(--ct-surface); border-radius: var(--ct-radius-full); font-size: 0.8rem; color: var(--ct-text-muted); border: 1px solid rgba(255,255,255,0.06); }
.chip-close { background: none; border: none; color: var(--ct-text-muted); cursor: pointer; font-size: 0.9rem; line-height: 1; padding: 0; margin-left: 0.15rem; }
.chip-close:hover { color: var(--ct-danger); }
.chip-primary { background: rgba(99,102,241,0.1); color: var(--ct-primary-light); border-color: rgba(99,102,241,0.2); }

/* ── Divider ────────────────────────────────────────────────── */
.divider { display: flex; align-items: center; gap: 1rem; color: var(--ct-text-muted); font-size: 0.8rem; margin: 1.5rem 0; }
.divider::before, .divider::after { content: ''; flex: 1; border-top: 1px solid rgba(255,255,255,0.06); }

/* ── Stat card ──────────────────────────────────────────────── */
.stat { text-align: center; padding: 1.25rem; }
.stat-value { font-size: 2rem; font-weight: 800; color: var(--ct-text); line-height: 1.2; font-family: var(--ct-font-mono); }
.stat-label { font-size: 0.8rem; color: var(--ct-text-muted); margin-top: 0.25rem; text-transform: uppercase; letter-spacing: 0.05em; }
.stat-change { font-size: 0.8rem; font-weight: 500; margin-top: 0.25rem; }
.stat-change.up { color: var(--ct-success); }
.stat-change.down { color: var(--ct-danger); }

/* ── Alert ──────────────────────────────────────────────────── */
.alert { display: flex; align-items: flex-start; gap: 0.75rem; padding: 1rem 1.25rem; border-radius: var(--ct-radius); margin-bottom: 1rem; border: 1px solid; }
.alert-info { background: rgba(59,130,246,0.08); border-color: rgba(59,130,246,0.2); color: var(--ct-info); }
.alert-success { background: rgba(16,185,129,0.08); border-color: rgba(16,185,129,0.2); color: var(--ct-success); }
.alert-warning { background: rgba(245,158,11,0.08); border-color: rgba(245,158,11,0.2); color: var(--ct-warning); }
.alert-danger { background: rgba(239,68,68,0.08); border-color: rgba(239,68,68,0.2); color: var(--ct-danger); }
.alert-title { font-weight: 600; margin-bottom: 0.25rem; }
.alert-message { font-size: 0.9rem; opacity: 0.9; }

/* ── Timeline ───────────────────────────────────────────────── */
.timeline { position: relative; padding-left: 2rem; }
.timeline::before { content: ''; position: absolute; left: 0.6rem; top: 0; bottom: 0; width: 2px; background: rgba(255,255,255,0.06); }
.timeline-item { position: relative; padding-bottom: 1.5rem; }
.timeline-dot { position: absolute; left: -1.65rem; top: 0.3rem; width: 12px; height: 12px; border-radius: 50%; background: var(--ct-primary); border: 2px solid var(--ct-bg); }
.timeline-item.complete .timeline-dot { background: var(--ct-success); }
.timeline-time { font-size: 0.8rem; color: var(--ct-text-muted); margin-bottom: 0.25rem; }
.timeline-content { font-size: 0.9rem; color: var(--ct-text); }""")

    return "\n".join(lines)


def _game_ui_css(scale: int = 3) -> str:
    lines = ["""\
/* ══════════════════════════════════════════════════════════════════════
   Game UI
   ══════════════════════════════════════════════════════════════════════ */

/* ── Canvas container ───────────────────────────────────────────── */
.ct-canvas-container {
  position: relative;
  width: 100%;
  aspect-ratio: 3 / 2;
  background: var(--ct-bg);
  border-radius: var(--ct-radius-lg);
  overflow: hidden;
  border: 1px solid rgba(255,255,255,0.06);
}
.ct-canvas-container canvas {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
.ct-canvas-container.fullscreen {
  position: fixed;
  inset: 0;
  z-index: 150;
  border-radius: 0;
  aspect-ratio: auto;
}

/* ── HUD overlay ────────────────────────────────────────────────── */
.ct-hud {
  position: absolute;
  inset: 0;
  pointer-events: none;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
.ct-hud > * { pointer-events: all; }

.ct-hud-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem 1rem;
  background: linear-gradient(to bottom, rgba(0,0,0,0.7) 0%, transparent 100%);
}

.ct-hud-bottom {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  background: linear-gradient(to top, rgba(0,0,0,0.7) 0%, transparent 100%);
}

.ct-hud-left {
  position: absolute;
  left: 0;
  top: 50%;
  transform: translateY(-50%);
  padding: 0.5rem;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.ct-hud-right {
  position: absolute;
  right: 0;
  top: 50%;
  transform: translateY(-50%);
  padding: 0.5rem;
}

/* ── Turn & player info ─────────────────────────────────────────── */
.ct-turn-indicator {
  font-family: var(--ct-font-mono);
  font-size: 0.85rem;
  color: var(--ct-accent);
  font-weight: 600;
  display: flex;
  align-items: center;
  gap: 0.4rem;
}
.ct-turn-indicator__phase {
  font-size: 0.7rem;
  color: var(--ct-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

.ct-player-info {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}
.ct-player-swatch {
  width: 16px;
  height: 16px;
  border-radius: 4px;
  border: 1px solid rgba(255,255,255,0.2);
  box-shadow: 0 0 6px currentColor;
}
.ct-player-name {
  font-size: 0.85rem;
  font-weight: 500;
}
.ct-chromaticity {
  font-family: var(--ct-font-mono);
  color: var(--ct-accent);
  font-weight: 700;
  font-size: 0.9rem;
}

/* ── Action buttons ─────────────────────────────────────────────── */
.ct-action-bar { display: flex; gap: 0.4rem; }
.ct-action-btn {
  width: 48px;
  height: 48px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: rgba(0,0,0,0.5);
  border: 1px solid rgba(255,255,255,0.1);
  border-radius: var(--ct-radius);
  cursor: pointer;
  color: var(--ct-text-muted);
  font-size: 0.65rem;
  gap: 0.15rem;
  transition: all var(--ct-transition);
  backdrop-filter: blur(4px);
}
.ct-action-btn:hover {
  color: var(--ct-text);
  background: rgba(99,102,241,0.2);
  border-color: var(--ct-primary);
  box-shadow: 0 0 12px rgba(99,102,241,0.3);
}
.ct-action-btn.active {
  color: var(--ct-primary-light);
  background: rgba(99,102,241,0.15);
  border-color: var(--ct-primary);
  animation: pulseGlow 2s ease-in-out infinite;
}
.ct-action-btn.disabled { opacity: 0.3; pointer-events: none; }
.ct-action-btn__icon { font-size: 1.2rem; }
.ct-action-btn__label { font-size: 0.6rem; text-transform: uppercase; letter-spacing: 0.05em; }

/* ── Palette selector ───────────────────────────────────────────── */
.ct-palette {
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem;
  padding: 0.75rem;
  background: var(--ct-card);
  border-radius: var(--ct-radius);
}
.ct-swatch {
  width: 36px;
  height: 36px;
  border-radius: var(--ct-radius-sm);
  cursor: pointer;
  border: 2px solid transparent;
  transition: all var(--ct-transition);
  box-shadow: inset 0 0 0 1px rgba(0,0,0,0.2);
}
.ct-swatch:hover { transform: scale(1.15); box-shadow: 0 0 8px currentColor; }
.ct-swatch.selected { border-color: white; box-shadow: 0 0 12px rgba(255,255,255,0.3); transform: scale(1.1); }
.ct-palette-label { width: 100%; font-size: 0.75rem; color: var(--ct-text-muted); margin-bottom: 0.25rem; font-weight: 500; }

/* ── Territory info panel ───────────────────────────────────────── */
.ct-territory-info {
  background: var(--ct-card);
  border-radius: var(--ct-radius);
  padding: 1rem;
  min-width: 200px;
  border: 1px solid rgba(255,255,255,0.04);
}
.ct-territory-info__title {
  font-weight: 600;
  margin-bottom: 0.5rem;
  display: flex;
  align-items: center;
  gap: 0.4rem;
}
.ct-territory-info__row {
  display: flex;
  justify-content: space-between;
  padding: 0.3rem 0;
  font-size: 0.85rem;
  border-bottom: 1px solid rgba(255,255,255,0.04);
}
.ct-territory-info__row:last-child { border-bottom: none; }
.ct-territory-info__label { color: var(--ct-text-muted); }
.ct-territory-info__value { color: var(--ct-text); font-weight: 500; font-family: var(--ct-font-mono); }

/* ── Minimap ────────────────────────────────────────────────────── */
.ct-minimap {
  position: absolute;
  bottom: 1rem;
  right: 1rem;
  width: 160px;
  height: 120px;
  background: rgba(0,0,0,0.6);
  border: 1px solid rgba(255,255,255,0.1);
  border-radius: var(--ct-radius);
  overflow: hidden;
  pointer-events: all;
  backdrop-filter: blur(4px);
  cursor: crosshair;
}
.ct-minimap canvas { width: 100%; height: 100%; }
.ct-minimap__viewport {
  position: absolute;
  border: 1px solid var(--ct-accent);
  background: rgba(245,158,11,0.1);
  pointer-events: none;
}

/* ── Score display ──────────────────────────────────────────────── */
.ct-score {
  font-family: var(--ct-font-mono);
  font-size: 1.4rem;
  font-weight: 800;
  color: var(--ct-accent);
}
.ct-score-pop { animation: scoreCount 0.4s ease-out; }

/* ── Resource bars ──────────────────────────────────────────────── */
.ct-resource-bar { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.4rem; }
.ct-resource-bar__icon { font-size: 0.9rem; width: 1.2rem; text-align: center; }
.ct-resource-bar__fill { flex: 1; height: 8px; background: var(--ct-surface); border-radius: 4px; overflow: hidden; }
.ct-resource-bar__fill-inner { height: 100%; background: linear-gradient(90deg, var(--ct-primary), var(--ct-accent)); border-radius: 4px; transition: width 0.5s ease; }
.ct-resource-bar__fill-inner.low { background: linear-gradient(90deg, var(--ct-danger), var(--ct-warning)); }
.ct-resource-bar__label { font-size: 0.75rem; color: var(--ct-text-muted); min-width: 40px; text-align: right; font-family: var(--ct-font-mono); }"""]

    if scale >= 4:
        lines.append("""\
/* ── Victory / defeat overlay ───────────────────────────────── */
.ct-victory-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.75);
  backdrop-filter: blur(8px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  z-index: 150;
  animation: fadeIn 0.5s ease;
}
.ct-victory-title {
  font-size: 3rem;
  font-weight: 900;
  margin-bottom: 1rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}
.ct-victory-title.win {
  background: linear-gradient(135deg, var(--ct-accent), var(--ct-primary));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
.ct-victory-title.lose { color: var(--ct-danger); }
.ct-victory-subtitle { color: var(--ct-text-muted); font-size: 1.1rem; margin-bottom: 2rem; }
.ct-victory-stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; margin-bottom: 2rem; }
.ct-victory-actions { display: flex; gap: 1rem; }

/* ── AI thinking indicator ──────────────────────────────────── */
.ct-ai-thinking { display: flex; align-items: center; gap: 0.5rem; color: var(--ct-text-muted); font-size: 0.85rem; }
.ct-ai-thinking__label { font-style: italic; }
.ct-ai-thinking__dots { display: flex; gap: 0.2rem; }
.ct-ai-thinking__dots span { width: 6px; height: 6px; border-radius: 50%; background: var(--ct-primary); animation: aiDot 1.2s ease infinite; }
.ct-ai-thinking__dots span:nth-child(2) { animation-delay: 0.2s; }
.ct-ai-thinking__dots span:nth-child(3) { animation-delay: 0.4s; }

/* ── Combat effects ─────────────────────────────────────────── */
.ct-combat-overlay { position: absolute; pointer-events: none; }
.ct-combat-flash { animation: combatFlash 0.8s ease; }
.ct-damage-number {
  position: absolute;
  font-family: var(--ct-font-mono);
  font-weight: 800;
  font-size: 1.5rem;
  color: var(--ct-danger);
  text-shadow: 0 0 8px rgba(239,68,68,0.5);
  animation: damageFloat 1s ease-out forwards;
  pointer-events: none;
}

/* ── Hex cell highlight ─────────────────────────────────────── */
.ct-cell-highlight { animation: hexPulse 1.5s ease-in-out infinite; }
.ct-cell-hover { outline: 2px solid var(--ct-primary); outline-offset: -1px; }""")

    if scale >= 5:
        lines.append("""\
/* ── Gallery ────────────────────────────────────────────────── */
.ct-gallery-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1rem; }
.ct-gallery-card { background: var(--ct-card); border-radius: var(--ct-radius); overflow: hidden; cursor: pointer; transition: all var(--ct-transition); border: 1px solid rgba(255,255,255,0.04); }
.ct-gallery-card:hover { transform: translateY(-4px); box-shadow: var(--ct-shadow-lg); border-color: rgba(255,255,255,0.1); }
.ct-gallery-card__image { width: 100%; aspect-ratio: 4/3; object-fit: cover; background: var(--ct-surface); }
.ct-gallery-card__info { padding: 0.75rem; }
.ct-gallery-card__title { font-weight: 600; font-size: 0.9rem; margin-bottom: 0.25rem; }
.ct-gallery-card__meta { font-size: 0.75rem; color: var(--ct-text-muted); display: flex; justify-content: space-between; align-items: center; }

/* ── Gallery lightbox ───────────────────────────────────────── */
.ct-lightbox { position: fixed; inset: 0; background: rgba(0,0,0,0.9); z-index: var(--ct-z-modal); display: flex; align-items: center; justify-content: center; animation: fadeIn 0.3s ease; }
.ct-lightbox img { max-width: 90vw; max-height: 85vh; border-radius: var(--ct-radius); box-shadow: var(--ct-shadow-xl); }
.ct-lightbox__nav { position: absolute; top: 50%; transform: translateY(-50%); background: rgba(255,255,255,0.1); border: none; color: white; font-size: 2rem; cursor: pointer; padding: 1rem; border-radius: var(--ct-radius); }
.ct-lightbox__nav.prev { left: 1rem; }
.ct-lightbox__nav.next { right: 1rem; }
.ct-lightbox__close { position: absolute; top: 1rem; right: 1rem; background: none; border: none; color: white; font-size: 2rem; cursor: pointer; }

/* ── Tutorial overlay ───────────────────────────────────────── */
.ct-tutorial-overlay { position: fixed; inset: 0; z-index: 200; pointer-events: none; }
.ct-tutorial-overlay.active { pointer-events: all; }
.ct-tutorial-backdrop { position: absolute; inset: 0; background: rgba(0,0,0,0.6); }
.ct-tutorial-highlight { position: absolute; box-shadow: 0 0 0 9999px rgba(0,0,0,0.6); border-radius: var(--ct-radius); z-index: 1; transition: all 0.4s ease; }
.ct-tutorial-step { position: absolute; background: var(--ct-card); padding: 1.25rem; border-radius: var(--ct-radius-lg); max-width: 360px; box-shadow: var(--ct-shadow-lg); z-index: 2; border: 1px solid var(--ct-primary); animation: scaleIn 0.3s ease; }
.ct-tutorial-step__title { font-weight: 600; margin-bottom: 0.5rem; font-size: 1rem; }
.ct-tutorial-step__text { font-size: 0.9rem; color: var(--ct-text-muted); margin-bottom: 1rem; line-height: 1.5; }
.ct-tutorial-nav { display: flex; justify-content: space-between; align-items: center; }
.ct-tutorial-dots { display: flex; gap: 0.3rem; }
.ct-tutorial-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--ct-surface); transition: background var(--ct-transition); }
.ct-tutorial-dot.active { background: var(--ct-primary); }
.ct-tutorial-dot.complete { background: var(--ct-success); }

/* ── Settings panel ─────────────────────────────────────────── */
.ct-settings-section { margin-bottom: 2rem; }
.ct-settings-section h3 { font-size: 1rem; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 1px solid rgba(255,255,255,0.06); }
.ct-settings-row { display: flex; align-items: center; justify-content: space-between; padding: 0.6rem 0; }
.ct-settings-row + .ct-settings-row { border-top: 1px solid rgba(255,255,255,0.03); }
.ct-settings-row__label { font-size: 0.9rem; color: var(--ct-text-muted); }
.ct-settings-row__desc { font-size: 0.8rem; color: rgba(148,163,184,0.6); margin-top: 0.15rem; }
.ct-settings-row__control { flex-shrink: 0; margin-left: 1rem; }

/* ── Loading screen ─────────────────────────────────────────── */
.ct-loading { position: fixed; inset: 0; background: var(--ct-bg); display: flex; flex-direction: column; align-items: center; justify-content: center; z-index: 300; }
.ct-loading__spinner { width: 48px; height: 48px; border: 3px solid var(--ct-surface); border-top-color: var(--ct-primary); border-radius: 50%; animation: spin 0.8s linear infinite; margin-bottom: 1.5rem; }
.ct-loading__text { color: var(--ct-text-muted); font-size: 0.9rem; margin-bottom: 1rem; }
.ct-loading__progress { width: 200px; height: 4px; background: var(--ct-surface); border-radius: 2px; overflow: hidden; }
.ct-loading__progress-bar { height: 100%; background: var(--ct-primary); border-radius: 2px; transition: width 0.3s ease; }""")

    return "\n".join(lines)


def _animations_css(scale: int = 3) -> str:
    lines = ["""\
/* ══════════════════════════════════════════════════════════════════════
   Animations
   ══════════════════════════════════════════════════════════════════════ */

/* ── Keyframes ──────────────────────────────────────────────────── */
@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
@keyframes fadeOut { from { opacity: 1; } to { opacity: 0; } }
@keyframes fadeInUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }
@keyframes fadeInDown { from { opacity: 0; transform: translateY(-20px); } to { opacity: 1; transform: translateY(0); } }
@keyframes slideInLeft { from { opacity: 0; transform: translateX(-40px); } to { opacity: 1; transform: translateX(0); } }
@keyframes slideInRight { from { opacity: 0; transform: translateX(40px); } to { opacity: 1; transform: translateX(0); } }
@keyframes slideInUp { from { transform: translateY(100%); } to { transform: translateY(0); } }
@keyframes slideInDown { from { transform: translateY(-100%); } to { transform: translateY(0); } }
@keyframes scaleIn { from { transform: scale(0.9); opacity: 0; } to { transform: scale(1); opacity: 1; } }
@keyframes scaleOut { from { transform: scale(1); opacity: 1; } to { transform: scale(0.9); opacity: 0; } }
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
@keyframes pulseGlow { 0%, 100% { box-shadow: 0 0 8px rgba(99,102,241,0.3); } 50% { box-shadow: 0 0 24px rgba(99,102,241,0.6); } }
@keyframes glow { 0%, 100% { filter: brightness(1); } 50% { filter: brightness(1.3); } }
@keyframes shake { 0%,100% { transform: translateX(0); } 10%,30%,50%,70%,90% { transform: translateX(-4px); } 20%,40%,60%,80% { transform: translateX(4px); } }
@keyframes shimmer { 0% { background-position: -200% 0; } 100% { background-position: 200% 0; } }
@keyframes gradientShift { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }
@keyframes float { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-8px); } }
@keyframes spin { to { transform: rotate(360deg); } }
@keyframes bounce { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-15px); } }
@keyframes expandRing { from { transform: scale(0); opacity: 0.8; } to { transform: scale(3); opacity: 0; } }
@keyframes ripple { to { transform: scale(2.5); opacity: 0; } }
@keyframes progressStripe { from { background-position: 1rem 0; } to { background-position: 0 0; } }

/* Game-specific keyframes */
@keyframes hexPulse { 0%, 100% { opacity: 0.6; transform: scale(1); } 50% { opacity: 1; transform: scale(1.05); } }
@keyframes aiDot { 0%, 100% { opacity: 0.3; transform: scale(0.8); } 50% { opacity: 1; transform: scale(1.2); } }
@keyframes combatFlash { 0%, 100% { opacity: 1; } 50% { filter: brightness(2); } }
@keyframes scoreCount { from { transform: scale(1.3); color: var(--ct-accent-light); } to { transform: scale(1); } }
@keyframes damageFloat { 0% { transform: translateY(0); opacity: 1; } 100% { transform: translateY(-60px); opacity: 0; } }
@keyframes captureExpand { from { transform: scale(0.8); opacity: 0.8; } to { transform: scale(1.5); opacity: 0; } }

/* ── Utility classes ────────────────────────────────────────────── */
.animate-fade-in { animation: fadeIn 0.5s ease; }
.animate-fade-up { animation: fadeInUp 0.6s ease forwards; opacity: 0; }
.animate-fade-down { animation: fadeInDown 0.6s ease forwards; opacity: 0; }
.animate-slide-left { animation: slideInLeft 0.6s ease forwards; opacity: 0; }
.animate-slide-right { animation: slideInRight 0.6s ease forwards; opacity: 0; }
.animate-scale { animation: scaleIn 0.5s ease forwards; opacity: 0; }
.animate-pulse { animation: pulse 2s infinite; }
.animate-float { animation: float 3s ease-in-out infinite; }
.animate-spin { animation: spin 1s linear infinite; }
.animate-bounce { animation: bounce 1s ease infinite; }
.animate-shake { animation: shake 0.5s ease; }
.gradient-bg { background: linear-gradient(135deg, var(--ct-primary), var(--ct-accent), var(--ct-primary)); background-size: 200% 200%; animation: gradientShift 6s ease infinite; }

/* Hover effects */
.hover-lift { transition: transform var(--ct-transition), box-shadow var(--ct-transition); }
.hover-lift:hover { transform: translateY(-3px); box-shadow: var(--ct-shadow-lg); }
.hover-glow:hover { box-shadow: 0 0 20px rgba(99,102,241,0.3); }
.hover-scale:hover { transform: scale(1.03); }
.hover-bright:hover { filter: brightness(1.1); }

/* Transitions */
.transition-all { transition: all var(--ct-transition); }
.transition-fast { transition: all var(--ct-transition-fast); }
.transition-slow { transition: all var(--ct-transition-slow); }
.transition-none { transition: none; }"""]

    if scale >= 4:
        lines.append("""\
/* ── Stagger delays ─────────────────────────────────────────── */
.delay-1 { animation-delay: 0.1s; }
.delay-2 { animation-delay: 0.2s; }
.delay-3 { animation-delay: 0.3s; }
.delay-4 { animation-delay: 0.4s; }
.delay-5 { animation-delay: 0.5s; }
.delay-6 { animation-delay: 0.6s; }
.delay-7 { animation-delay: 0.7s; }
.delay-8 { animation-delay: 0.8s; }
.delay-9 { animation-delay: 0.9s; }
.delay-10 { animation-delay: 1.0s; }

/* Duration variants */
.duration-100 { animation-duration: 100ms; }
.duration-200 { animation-duration: 200ms; }
.duration-300 { animation-duration: 300ms; }
.duration-500 { animation-duration: 500ms; }
.duration-700 { animation-duration: 700ms; }
.duration-1000 { animation-duration: 1000ms; }

/* Loading spinner */
.spinner { width: 32px; height: 32px; border: 3px solid var(--ct-surface); border-top-color: var(--ct-primary); border-radius: 50%; animation: spin 0.8s linear infinite; }
.spinner-sm { width: 18px; height: 18px; border-width: 2px; }
.spinner-lg { width: 48px; height: 48px; border-width: 4px; }

/* Page transitions */
.page-enter { animation: fadeInUp 0.4s ease; }
.page-leave { animation: fadeOut 0.2s ease; }

/* Scroll reveal */
.reveal { opacity: 0; transform: translateY(20px); transition: all 0.6s ease; }
.reveal.visible { opacity: 1; transform: translateY(0); }""")

    return "\n".join(lines)


@register("design_system")
def generate_design_system_css(scale: int = 3, **kwargs) -> tuple[str, str, str]:
    """Generate comprehensive CSS design system.

    At scale=5 (production), produces 3500+ lines covering design tokens,
    layout system, full component library, game UI, and animations.
    """
    parts = [
        _design_system_css(kwargs.get("theme"), scale),
        _layout_css(scale),
        _components_css(scale),
        _game_ui_css(scale),
        _animations_css(scale),
    ]
    return ("", "\n\n".join(parts), "")
