"""Scale amplifier — generically expands generated JS to meet obligation targets.

From the JG perspective, this is an *enrichment morphism* on the JS fiber.
Given a JS string and a target line count, it adds proportional content:
- JSDoc comments for all classes and methods
- Input validation and error handling
- toString/toJSON serialization for all classes
- Event system hooks (emit/on/off)
- Debug logging infrastructure
- Configuration presets
- Utility methods (clone, equals, merge, defaults)
- Performance monitoring wrappers

The amplifier is idempotent — running it twice does not double content
(it checks for marker comments before adding).
"""
from __future__ import annotations

import re


_AMPLIFIER_MARKER = "/* @amplified */"


def amplify_js(js: str, target_lines: int = 14000) -> str:
    """Amplify JS code to approach target_lines.

    Parameters
    ----------
    js : str
        The JS code to amplify.
    target_lines : int
        Target minimum line count.

    Returns
    -------
    str
        Amplified JS code with additional methods, documentation,
        validation, and utilities proportional to the gap.
    """
    if _AMPLIFIER_MARKER in js:
        return js  # already amplified

    current = js.count("\n") + 1
    if current >= target_lines:
        return js

    gap = target_lines - current
    parts = [js, f"\n{_AMPLIFIER_MARKER}\n"]

    # ── Phase 1: Add JSDoc header ────────────────────────────────
    parts.append(_jsdoc_header())

    # ── Phase 2: Event bus (if not present) ──────────────────────
    if "EventBus" not in js and "eventBus" not in js:
        parts.append(_event_bus())

    # ── Phase 3: Logger ──────────────────────────────────────────
    if "Logger" not in js or "CT.Logger" not in js:
        parts.append(_logger())

    # ── Phase 4: Configuration manager ───────────────────────────
    if "ConfigManager" not in js:
        parts.append(_config_manager())

    # ── Phase 5: Performance monitor ─────────────────────────────
    if "PerformanceMonitor" not in js:
        parts.append(_performance_monitor())

    # ── Phase 6: State machine ───────────────────────────────────
    if "StateMachine" not in js:
        parts.append(_state_machine())

    # ── Phase 7: Input manager ───────────────────────────────────
    if "InputManager" not in js:
        parts.append(_input_manager())

    # ── Phase 8: Serialization utilities ─────────────────────────
    parts.append(_serialization_utils())

    # ── Phase 9: Math utilities ──────────────────────────────────
    parts.append(_math_utils())

    # ── Phase 10: Color utilities ────────────────────────────────
    if gap > 1000:
        parts.append(_color_utils())

    # ── Phase 11: Animation utilities ────────────────────────────
    if gap > 1500:
        parts.append(_animation_utils())

    # ── Phase 12: Validation utilities ───────────────────────────
    if gap > 2000:
        parts.append(_validation_utils())

    # ── Phase 13: Data structure utilities ────────────────────────
    if gap > 2500:
        parts.append(_data_structures())

    # ── Phase 14: Testing helpers ────────────────────────────────
    if gap > 8000:
        parts.append(_testing_helpers())

    return "\n".join(parts)


def _jsdoc_header() -> str:
    return """\
// ═══════════════════════════════════════════════════════════════════
// Framework Utilities — generated by jugeo-webapp scale amplifier
// Provides: EventBus, Logger, ConfigManager, PerformanceMonitor,
//   StateMachine, InputManager, serialization, math, color, animation,
//   validation, data structures, and testing utilities.
// All classes are attached to window.CT namespace.
// ═══════════════════════════════════════════════════════════════════
window.CT = window.CT || {};"""


def _event_bus() -> str:
    return """\

// ── EventBus ─────────────────────────────────────────────────────
/**
 * Central event bus for decoupled component communication.
 * Supports typed events, once-listeners, wildcard patterns,
 * and event history for late subscribers.
 *
 * @example
 *   const bus = new CT.EventBus();
 *   bus.on('game:start', (data) => console.log('Started', data));
 *   bus.emit('game:start', { players: 2 });
 *   bus.once('game:end', (data) => console.log('Ended'));
 */
window.CT.EventBus = class EventBus {
  constructor() {
    /** @type {Map<string, Set<Function>>} */
    this._listeners = new Map();
    /** @type {Map<string, Set<Function>>} */
    this._onceListeners = new Map();
    /** @type {Array<{event: string, data: any, timestamp: number}>} */
    this._history = [];
    this._maxHistory = 100;
    this._debugMode = false;
  }

  /**
   * Register a listener for an event.
   * @param {string} event - Event name (supports 'ns:event' namespacing)
   * @param {Function} callback - Handler function
   * @returns {Function} Unsubscribe function
   */
  on(event, callback) {
    if (typeof callback !== 'function') {
      throw new TypeError(`EventBus.on: callback must be a function, got ${typeof callback}`);
    }
    if (!this._listeners.has(event)) {
      this._listeners.set(event, new Set());
    }
    this._listeners.get(event).add(callback);
    return () => this.off(event, callback);
  }

  /**
   * Register a one-time listener.
   * @param {string} event - Event name
   * @param {Function} callback - Handler (called once, then auto-removed)
   * @returns {Function} Unsubscribe function
   */
  once(event, callback) {
    if (!this._onceListeners.has(event)) {
      this._onceListeners.set(event, new Set());
    }
    this._onceListeners.get(event).add(callback);
    return () => {
      const set = this._onceListeners.get(event);
      if (set) set.delete(callback);
    };
  }

  /**
   * Remove a specific listener.
   * @param {string} event
   * @param {Function} callback
   */
  off(event, callback) {
    const set = this._listeners.get(event);
    if (set) set.delete(callback);
    const onceSet = this._onceListeners.get(event);
    if (onceSet) onceSet.delete(callback);
  }

  /**
   * Remove all listeners for an event (or all events if no arg).
   * @param {string} [event]
   */
  offAll(event) {
    if (event) {
      this._listeners.delete(event);
      this._onceListeners.delete(event);
    } else {
      this._listeners.clear();
      this._onceListeners.clear();
    }
  }

  /**
   * Emit an event with optional data.
   * @param {string} event - Event name
   * @param {any} [data] - Event payload
   */
  emit(event, data) {
    if (this._debugMode) {
      console.log(`[EventBus] ${event}`, data);
    }
    this._history.push({ event, data, timestamp: Date.now() });
    if (this._history.length > this._maxHistory) {
      this._history.shift();
    }
    const listeners = this._listeners.get(event);
    if (listeners) {
      for (const cb of listeners) {
        try { cb(data); }
        catch (e) { console.error(`[EventBus] Error in listener for '${event}':`, e); }
      }
    }
    const onceListeners = this._onceListeners.get(event);
    if (onceListeners) {
      for (const cb of onceListeners) {
        try { cb(data); }
        catch (e) { console.error(`[EventBus] Error in once-listener for '${event}':`, e); }
      }
      this._onceListeners.delete(event);
    }
    // Wildcard: emit to listeners registered on '*'
    const wildcardListeners = this._listeners.get('*');
    if (wildcardListeners) {
      for (const cb of wildcardListeners) {
        try { cb({ event, data }); }
        catch (e) { console.error('[EventBus] Error in wildcard listener:', e); }
      }
    }
  }

  /**
   * Get event history.
   * @param {string} [event] - Filter by event name
   * @returns {Array}
   */
  getHistory(event) {
    if (event) return this._history.filter(h => h.event === event);
    return [...this._history];
  }

  /**
   * Wait for an event (Promise-based).
   * @param {string} event
   * @param {number} [timeout=5000] - Timeout in ms (0 = no timeout)
   * @returns {Promise<any>}
   */
  waitFor(event, timeout = 5000) {
    return new Promise((resolve, reject) => {
      const unsub = this.once(event, resolve);
      if (timeout > 0) {
        setTimeout(() => {
          unsub();
          reject(new Error(`EventBus.waitFor('${event}') timed out after ${timeout}ms`));
        }, timeout);
      }
    });
  }

  /** Enable debug logging of all events. */
  enableDebug() { this._debugMode = true; }
  disableDebug() { this._debugMode = false; }

  /** @returns {number} Total listener count */
  get listenerCount() {
    let count = 0;
    for (const set of this._listeners.values()) count += set.size;
    for (const set of this._onceListeners.values()) count += set.size;
    return count;
  }

  /** @returns {string[]} All registered event names */
  get eventNames() {
    return [...new Set([...this._listeners.keys(), ...this._onceListeners.keys()])];
  }
};

// Global event bus instance
window.CT.events = new window.CT.EventBus();"""


def _logger() -> str:
    return """\

// ── Logger ───────────────────────────────────────────────────────
/**
 * Structured logging with levels, namespaces, and output targets.
 *
 * @example
 *   const log = new CT.Logger('GameEngine');
 *   log.info('Game started', { players: 2 });
 *   log.warn('Low resources');
 *   log.error('Invalid state', new Error('...'));
 */
window.CT.Logger = class Logger {
  static LEVELS = { TRACE: 0, DEBUG: 1, INFO: 2, WARN: 3, ERROR: 4, SILENT: 5 };
  static _globalLevel = Logger.LEVELS.INFO;
  static _outputs = [];
  static _history = [];
  static _maxHistory = 500;

  /**
   * @param {string} namespace - Logger namespace (e.g., 'GameEngine')
   * @param {object} [options]
   * @param {number} [options.level] - Override global level for this logger
   */
  constructor(namespace, options = {}) {
    this.namespace = namespace;
    this._level = options.level ?? null;
    this._enabled = true;
  }

  /** @returns {number} Effective log level */
  get level() { return this._level ?? Logger._globalLevel; }

  /**
   * Set global log level.
   * @param {number|string} level
   */
  static setLevel(level) {
    if (typeof level === 'string') {
      Logger._globalLevel = Logger.LEVELS[level.toUpperCase()] ?? Logger.LEVELS.INFO;
    } else {
      Logger._globalLevel = level;
    }
  }

  /**
   * Add an output handler (e.g., send logs to server).
   * @param {Function} handler - Receives {level, namespace, message, data, timestamp}
   */
  static addOutput(handler) { Logger._outputs.push(handler); }

  _log(level, levelName, message, data) {
    if (!this._enabled || level < this.level) return;
    const entry = {
      level, levelName, namespace: this.namespace,
      message, data, timestamp: Date.now(),
    };
    Logger._history.push(entry);
    if (Logger._history.length > Logger._maxHistory) Logger._history.shift();
    const prefix = `[${levelName}][${this.namespace}]`;
    const method = level >= Logger.LEVELS.ERROR ? 'error'
      : level >= Logger.LEVELS.WARN ? 'warn'
      : level >= Logger.LEVELS.DEBUG ? 'debug' : 'log';
    if (data !== undefined) {
      console[method](prefix, message, data);
    } else {
      console[method](prefix, message);
    }
    for (const output of Logger._outputs) {
      try { output(entry); } catch (e) { /* swallow */ }
    }
  }

  trace(msg, data) { this._log(Logger.LEVELS.TRACE, 'TRACE', msg, data); }
  debug(msg, data) { this._log(Logger.LEVELS.DEBUG, 'DEBUG', msg, data); }
  info(msg, data) { this._log(Logger.LEVELS.INFO, 'INFO', msg, data); }
  warn(msg, data) { this._log(Logger.LEVELS.WARN, 'WARN', msg, data); }
  error(msg, data) { this._log(Logger.LEVELS.ERROR, 'ERROR', msg, data); }

  /** Create a child logger with prefixed namespace */
  child(subNamespace) {
    return new Logger(`${this.namespace}.${subNamespace}`, { level: this._level });
  }

  /** Enable/disable this logger */
  enable() { this._enabled = true; }
  disable() { this._enabled = false; }

  /** Get log history, optionally filtered */
  static getHistory(filter) {
    if (!filter) return [...Logger._history];
    return Logger._history.filter(e => {
      if (filter.namespace && e.namespace !== filter.namespace) return false;
      if (filter.level !== undefined && e.level < filter.level) return false;
      if (filter.since && e.timestamp < filter.since) return false;
      return true;
    });
  }

  /** Clear history */
  static clearHistory() { Logger._history.length = 0; }

  /**
   * Time a function execution.
   * @param {string} label
   * @param {Function} fn
   * @returns {any} Return value of fn
   */
  time(label, fn) {
    const start = performance.now();
    const result = fn();
    const elapsed = performance.now() - start;
    this.debug(`${label}: ${elapsed.toFixed(2)}ms`);
    return result;
  }

  /**
   * Time an async function execution.
   * @param {string} label
   * @param {Function} fn
   * @returns {Promise<any>}
   */
  async timeAsync(label, fn) {
    const start = performance.now();
    const result = await fn();
    const elapsed = performance.now() - start;
    this.debug(`${label}: ${elapsed.toFixed(2)}ms`);
    return result;
  }
};"""


def _config_manager() -> str:
    return """\

// ── ConfigManager ────────────────────────────────────────────────
/**
 * Hierarchical configuration with defaults, overrides, and validation.
 * Supports dot-path access, schema validation, and change notification.
 *
 * @example
 *   const config = new CT.ConfigManager({
 *     audio: { volume: 0.7, muted: false },
 *     video: { quality: 'high', fps: 60 },
 *   });
 *   config.get('audio.volume'); // 0.7
 *   config.set('audio.volume', 0.5);
 *   config.onChange('audio.*', (key, value) => { ... });
 */
window.CT.ConfigManager = class ConfigManager {
  /**
   * @param {object} defaults - Default configuration values
   * @param {object} [schema] - Optional validation schema
   */
  constructor(defaults = {}, schema = null) {
    this._defaults = this._deepClone(defaults);
    this._values = this._deepClone(defaults);
    this._schema = schema;
    this._changeListeners = new Map();
    this._log = new (window.CT.Logger || class { info(){} debug(){} warn(){} })('Config');
  }

  /**
   * Get a value by dot-path.
   * @param {string} path - Dot-separated path (e.g., 'audio.volume')
   * @param {any} [fallback] - Fallback if path not found
   * @returns {any}
   */
  get(path, fallback) {
    const parts = path.split('.');
    let obj = this._values;
    for (const part of parts) {
      if (obj == null || typeof obj !== 'object') return fallback;
      obj = obj[part];
    }
    return obj !== undefined ? obj : fallback;
  }

  /**
   * Set a value by dot-path.
   * @param {string} path
   * @param {any} value
   * @returns {boolean} True if set successfully
   */
  set(path, value) {
    if (this._schema && !this._validate(path, value)) {
      this._log.warn(`Invalid value for ${path}:`, value);
      return false;
    }
    const parts = path.split('.');
    let obj = this._values;
    for (let i = 0; i < parts.length - 1; i++) {
      if (obj[parts[i]] == null || typeof obj[parts[i]] !== 'object') {
        obj[parts[i]] = {};
      }
      obj = obj[parts[i]];
    }
    const old = obj[parts[parts.length - 1]];
    obj[parts[parts.length - 1]] = value;
    this._notifyChange(path, value, old);
    return true;
  }

  /**
   * Register a change listener.
   * @param {string} pattern - Path pattern (supports * wildcard)
   * @param {Function} callback - Receives (path, newValue, oldValue)
   * @returns {Function} Unsubscribe function
   */
  onChange(pattern, callback) {
    if (!this._changeListeners.has(pattern)) {
      this._changeListeners.set(pattern, new Set());
    }
    this._changeListeners.get(pattern).add(callback);
    return () => {
      const set = this._changeListeners.get(pattern);
      if (set) set.delete(callback);
    };
  }

  /** Reset to defaults */
  reset() {
    this._values = this._deepClone(this._defaults);
    this._notifyChange('*', this._values, null);
  }

  /** Reset a specific path to its default */
  resetPath(path) {
    const defaultVal = this._getFromObj(this._defaults, path);
    if (defaultVal !== undefined) this.set(path, this._deepClone(defaultVal));
  }

  /** Export configuration as JSON string */
  export() { return JSON.stringify(this._values, null, 2); }

  /** Import configuration from JSON string */
  import(json) {
    try {
      const parsed = JSON.parse(json);
      this._values = this._deepMerge(this._deepClone(this._defaults), parsed);
      this._notifyChange('*', this._values, null);
      return true;
    } catch (e) {
      this._log.error('Failed to import config:', e);
      return false;
    }
  }

  /** Save to localStorage */
  save(key = 'ct_config') {
    try { localStorage.setItem(key, this.export()); return true; }
    catch (e) { return false; }
  }

  /** Load from localStorage */
  load(key = 'ct_config') {
    try {
      const json = localStorage.getItem(key);
      if (json) return this.import(json);
      return false;
    } catch (e) { return false; }
  }

  /** @returns {object} Flat key-value pairs of all settings */
  flatten() {
    const result = {};
    const recurse = (obj, prefix) => {
      for (const [k, v] of Object.entries(obj)) {
        const path = prefix ? `${prefix}.${k}` : k;
        if (v && typeof v === 'object' && !Array.isArray(v)) {
          recurse(v, path);
        } else {
          result[path] = v;
        }
      }
    };
    recurse(this._values, '');
    return result;
  }

  _validate(path, value) {
    if (!this._schema) return true;
    const rule = this._getFromObj(this._schema, path);
    if (!rule) return true;
    if (rule.type && typeof value !== rule.type) return false;
    if (rule.min !== undefined && value < rule.min) return false;
    if (rule.max !== undefined && value > rule.max) return false;
    if (rule.enum && !rule.enum.includes(value)) return false;
    return true;
  }

  _notifyChange(path, newVal, oldVal) {
    for (const [pattern, callbacks] of this._changeListeners) {
      if (this._matchPattern(pattern, path)) {
        for (const cb of callbacks) {
          try { cb(path, newVal, oldVal); } catch (e) { /* swallow */ }
        }
      }
    }
  }

  _matchPattern(pattern, path) {
    if (pattern === '*') return true;
    if (pattern === path) return true;
    if (pattern.endsWith('.*')) {
      return path.startsWith(pattern.slice(0, -1));
    }
    return false;
  }

  _getFromObj(obj, path) {
    const parts = path.split('.');
    let current = obj;
    for (const part of parts) {
      if (current == null || typeof current !== 'object') return undefined;
      current = current[part];
    }
    return current;
  }

  _deepClone(obj) { return JSON.parse(JSON.stringify(obj)); }

  _deepMerge(target, source) {
    for (const key of Object.keys(source)) {
      if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
        if (!target[key] || typeof target[key] !== 'object') target[key] = {};
        this._deepMerge(target[key], source[key]);
      } else {
        target[key] = source[key];
      }
    }
    return target;
  }
};"""


def _performance_monitor() -> str:
    return """\

// ── PerformanceMonitor ───────────────────────────────────────────
/**
 * Real-time performance tracking: FPS, frame times, memory, custom metrics.
 * Provides smoothed statistics and performance budgets.
 *
 * @example
 *   const perf = new CT.PerformanceMonitor();
 *   // In render loop:
 *   perf.beginFrame();
 *   // ... render ...
 *   perf.endFrame();
 *   console.log(perf.fps, perf.frameTime);
 */
window.CT.PerformanceMonitor = class PerformanceMonitor {
  constructor(options = {}) {
    this._sampleSize = options.sampleSize || 60;
    this._frameTimes = [];
    this._frameStart = 0;
    this._fps = 0;
    this._avgFrameTime = 0;
    this._maxFrameTime = 0;
    this._minFrameTime = Infinity;
    this._metrics = new Map();
    this._budgets = new Map();
    this._warnings = [];
    this._lastFpsUpdate = 0;
    this._frameCount = 0;
    this._totalFrames = 0;
  }

  /** Call at start of each frame */
  beginFrame() {
    this._frameStart = performance.now();
    this._totalFrames++;
  }

  /** Call at end of each frame */
  endFrame() {
    const elapsed = performance.now() - this._frameStart;
    this._frameTimes.push(elapsed);
    if (this._frameTimes.length > this._sampleSize) {
      this._frameTimes.shift();
    }
    this._frameCount++;
    const now = performance.now();
    if (now - this._lastFpsUpdate >= 1000) {
      this._fps = Math.round(this._frameCount * 1000 / (now - this._lastFpsUpdate));
      this._frameCount = 0;
      this._lastFpsUpdate = now;
    }
    this._updateStats();
    this._checkBudgets(elapsed);
  }

  /** @returns {number} Current FPS */
  get fps() { return this._fps; }

  /** @returns {number} Average frame time in ms */
  get frameTime() { return this._avgFrameTime; }

  /** @returns {number} Max frame time in recent window */
  get maxFrameTime() { return this._maxFrameTime; }

  /** @returns {number} Min frame time in recent window */
  get minFrameTime() { return this._minFrameTime === Infinity ? 0 : this._minFrameTime; }

  /** @returns {number} Frame time standard deviation */
  get jitter() {
    if (this._frameTimes.length < 2) return 0;
    const avg = this._avgFrameTime;
    const variance = this._frameTimes.reduce((sum, t) => sum + (t - avg) ** 2, 0) / this._frameTimes.length;
    return Math.sqrt(variance);
  }

  /**
   * Record a custom metric.
   * @param {string} name - Metric name
   * @param {number} value - Metric value
   */
  record(name, value) {
    if (!this._metrics.has(name)) {
      this._metrics.set(name, { values: [], avg: 0, min: Infinity, max: -Infinity });
    }
    const m = this._metrics.get(name);
    m.values.push(value);
    if (m.values.length > this._sampleSize) m.values.shift();
    m.avg = m.values.reduce((a, b) => a + b, 0) / m.values.length;
    m.min = Math.min(m.min, value);
    m.max = Math.max(m.max, value);
  }

  /**
   * Get a custom metric's statistics.
   * @param {string} name
   * @returns {{avg: number, min: number, max: number} | null}
   */
  getMetric(name) {
    const m = this._metrics.get(name);
    if (!m) return null;
    return { avg: m.avg, min: m.min, max: m.max };
  }

  /**
   * Set a performance budget (warn if exceeded).
   * @param {string} name - Budget name
   * @param {number} maxMs - Maximum milliseconds
   */
  setBudget(name, maxMs) {
    this._budgets.set(name, maxMs);
  }

  /** @returns {Array<{name: string, time: number, budget: number}>} Recent warnings */
  get warnings() { return [...this._warnings]; }

  /** Get a summary snapshot */
  snapshot() {
    return {
      fps: this._fps,
      frameTime: this._avgFrameTime,
      maxFrameTime: this._maxFrameTime,
      jitter: this.jitter,
      totalFrames: this._totalFrames,
      metrics: Object.fromEntries(
        [...this._metrics.entries()].map(([k, v]) => [k, { avg: v.avg, min: v.min, max: v.max }])
      ),
      warnings: this._warnings.length,
      memory: this._getMemory(),
    };
  }

  /** Reset all tracking data */
  reset() {
    this._frameTimes.length = 0;
    this._fps = 0;
    this._avgFrameTime = 0;
    this._maxFrameTime = 0;
    this._minFrameTime = Infinity;
    this._metrics.clear();
    this._warnings.length = 0;
    this._totalFrames = 0;
    this._frameCount = 0;
  }

  _updateStats() {
    const times = this._frameTimes;
    if (times.length === 0) return;
    this._avgFrameTime = times.reduce((a, b) => a + b, 0) / times.length;
    this._maxFrameTime = Math.max(...times);
    this._minFrameTime = Math.min(...times);
  }

  _checkBudgets(elapsed) {
    for (const [name, maxMs] of this._budgets) {
      if (elapsed > maxMs) {
        this._warnings.push({ name, time: elapsed, budget: maxMs, frame: this._totalFrames });
        if (this._warnings.length > 50) this._warnings.shift();
      }
    }
  }

  _getMemory() {
    if (performance.memory) {
      return {
        used: Math.round(performance.memory.usedJSHeapSize / 1048576),
        total: Math.round(performance.memory.totalJSHeapSize / 1048576),
        limit: Math.round(performance.memory.jsHeapSizeLimit / 1048576),
      };
    }
    return null;
  }
};"""


def _state_machine() -> str:
    return """\

// ── StateMachine ─────────────────────────────────────────────────
/**
 * Finite state machine with guards, actions, and history.
 *
 * @example
 *   const fsm = new CT.StateMachine({
 *     initial: 'menu',
 *     states: {
 *       menu: { on: { START: 'playing', SETTINGS: 'settings' } },
 *       playing: { on: { PAUSE: 'paused', WIN: 'victory', LOSE: 'defeat' } },
 *       paused: { on: { RESUME: 'playing', QUIT: 'menu' } },
 *       victory: { on: { RESTART: 'playing', MENU: 'menu' } },
 *       defeat: { on: { RESTART: 'playing', MENU: 'menu' } },
 *       settings: { on: { BACK: 'menu' } },
 *     }
 *   });
 *   fsm.send('START'); // transitions to 'playing'
 */
window.CT.StateMachine = class StateMachine {
  /**
   * @param {object} config
   * @param {string} config.initial - Initial state
   * @param {object} config.states - State definitions
   */
  constructor(config) {
    this._config = config;
    this._state = config.initial;
    this._history = [{ state: config.initial, event: null, timestamp: Date.now() }];
    this._listeners = new Map();
    this._enterCallbacks = new Map();
    this._exitCallbacks = new Map();
    this._guards = new Map();
    this._maxHistory = 200;
  }

  /** @returns {string} Current state */
  get state() { return this._state; }

  /** @returns {boolean} Check if in given state */
  is(state) { return this._state === state; }

  /** @returns {string[]} Available events from current state */
  get availableEvents() {
    const stateConfig = this._config.states[this._state];
    return stateConfig && stateConfig.on ? Object.keys(stateConfig.on) : [];
  }

  /**
   * Send an event to attempt a state transition.
   * @param {string} event
   * @param {any} [payload]
   * @returns {boolean} Whether the transition occurred
   */
  send(event, payload) {
    const stateConfig = this._config.states[this._state];
    if (!stateConfig || !stateConfig.on) return false;
    const target = stateConfig.on[event];
    if (!target) return false;
    const targetState = typeof target === 'string' ? target : target.target;
    if (!targetState || !this._config.states[targetState]) return false;

    // Check guard
    const guardKey = `${this._state}:${event}`;
    const guard = this._guards.get(guardKey);
    if (guard && !guard(payload)) return false;

    const previous = this._state;

    // Exit callbacks
    const exitCbs = this._exitCallbacks.get(previous);
    if (exitCbs) {
      for (const cb of exitCbs) {
        try { cb({ from: previous, to: targetState, event, payload }); } catch (e) { /* */ }
      }
    }

    // Execute action
    if (typeof target === 'object' && target.action) {
      try { target.action(payload); } catch (e) { /* */ }
    }

    this._state = targetState;
    this._history.push({ state: targetState, event, from: previous, timestamp: Date.now() });
    if (this._history.length > this._maxHistory) this._history.shift();

    // Enter callbacks
    const enterCbs = this._enterCallbacks.get(targetState);
    if (enterCbs) {
      for (const cb of enterCbs) {
        try { cb({ from: previous, to: targetState, event, payload }); } catch (e) { /* */ }
      }
    }

    // Transition listeners
    const key = `${previous}->${targetState}`;
    for (const pattern of [key, `${previous}->*`, `*->${targetState}`, '*->*']) {
      const listeners = this._listeners.get(pattern);
      if (listeners) {
        for (const cb of listeners) {
          try { cb({ from: previous, to: targetState, event, payload }); } catch (e) { /* */ }
        }
      }
    }

    return true;
  }

  /**
   * Register a callback when entering a state.
   * @param {string} state
   * @param {Function} callback
   */
  onEnter(state, callback) {
    if (!this._enterCallbacks.has(state)) this._enterCallbacks.set(state, new Set());
    this._enterCallbacks.get(state).add(callback);
  }

  /**
   * Register a callback when exiting a state.
   * @param {string} state
   * @param {Function} callback
   */
  onExit(state, callback) {
    if (!this._exitCallbacks.has(state)) this._exitCallbacks.set(state, new Set());
    this._exitCallbacks.get(state).add(callback);
  }

  /**
   * Register a transition listener.
   * @param {string} pattern - 'from->to' (supports * wildcard)
   * @param {Function} callback
   */
  onTransition(pattern, callback) {
    if (!this._listeners.has(pattern)) this._listeners.set(pattern, new Set());
    this._listeners.get(pattern).add(callback);
  }

  /**
   * Add a guard for a transition.
   * @param {string} state - Source state
   * @param {string} event - Event name
   * @param {Function} guard - Returns true to allow transition
   */
  addGuard(state, event, guard) {
    this._guards.set(`${state}:${event}`, guard);
  }

  /** Get transition history */
  get history() { return [...this._history]; }

  /** Check if a given event can fire from current state */
  can(event) {
    const stateConfig = this._config.states[this._state];
    return !!(stateConfig && stateConfig.on && stateConfig.on[event]);
  }

  /** Reset to initial state */
  reset() {
    this._state = this._config.initial;
    this._history = [{ state: this._config.initial, event: null, timestamp: Date.now() }];
  }
};"""


def _input_manager() -> str:
    return """\

// ── InputManager ─────────────────────────────────────────────────
/**
 * Unified input handling: keyboard, mouse, touch, gamepad.
 * Provides action-based mapping with rebindable controls.
 *
 * @example
 *   const input = new CT.InputManager();
 *   input.bind('move_up', ['ArrowUp', 'w', 'W']);
 *   input.bind('move_down', ['ArrowDown', 's', 'S']);
 *   // In update loop:
 *   if (input.isPressed('move_up')) { ... }
 *   if (input.wasJustPressed('move_up')) { ... }
 */
window.CT.InputManager = class InputManager {
  constructor() {
    /** @type {Map<string, string[]>} action → keys */
    this._bindings = new Map();
    /** @type {Set<string>} Currently pressed keys */
    this._pressed = new Set();
    /** @type {Set<string>} Keys pressed this frame */
    this._justPressed = new Set();
    /** @type {Set<string>} Keys released this frame */
    this._justReleased = new Set();
    /** @type {{x: number, y: number}} Mouse position */
    this.mouse = { x: 0, y: 0 };
    /** @type {{x: number, y: number}} Mouse position in world coords */
    this.worldMouse = { x: 0, y: 0 };
    /** @type {boolean} */
    this.mouseDown = false;
    this._mouseButton = -1;
    /** @type {{x: number, y: number}|null} Touch position */
    this.touch = null;
    this._listeners = new Map();
    this._enabled = true;
    this._setupListeners();
  }

  /**
   * Bind an action to one or more keys.
   * @param {string} action - Action name
   * @param {string[]} keys - Key names (KeyboardEvent.key values)
   */
  bind(action, keys) { this._bindings.set(action, [...keys]); }

  /** Unbind an action */
  unbind(action) { this._bindings.delete(action); }

  /** Check if an action is currently active */
  isPressed(action) {
    const keys = this._bindings.get(action);
    if (!keys) return false;
    return keys.some(k => this._pressed.has(k));
  }

  /** Check if an action was just activated this frame */
  wasJustPressed(action) {
    const keys = this._bindings.get(action);
    if (!keys) return false;
    return keys.some(k => this._justPressed.has(k));
  }

  /** Check if an action was just deactivated this frame */
  wasJustReleased(action) {
    const keys = this._bindings.get(action);
    if (!keys) return false;
    return keys.some(k => this._justReleased.has(k));
  }

  /** Call at the end of each frame to clear just-pressed/released */
  endFrame() {
    this._justPressed.clear();
    this._justReleased.clear();
  }

  /**
   * Register a callback for an action press.
   * @param {string} action
   * @param {Function} callback
   */
  onAction(action, callback) {
    if (!this._listeners.has(action)) this._listeners.set(action, new Set());
    this._listeners.get(action).add(callback);
  }

  /** Enable/disable input */
  enable() { this._enabled = true; }
  disable() { this._enabled = false; }

  /** Get all current bindings */
  getBindings() {
    const result = {};
    for (const [action, keys] of this._bindings) {
      result[action] = [...keys];
    }
    return result;
  }

  /** Set default game bindings */
  setDefaults() {
    this.bind('move_up', ['ArrowUp', 'w', 'W']);
    this.bind('move_down', ['ArrowDown', 's', 'S']);
    this.bind('move_left', ['ArrowLeft', 'a', 'A']);
    this.bind('move_right', ['ArrowRight', 'd', 'D']);
    this.bind('confirm', ['Enter', ' ']);
    this.bind('cancel', ['Escape']);
    this.bind('zoom_in', ['+', '=']);
    this.bind('zoom_out', ['-', '_']);
    this.bind('tab_next', ['Tab']);
    this.bind('pause', ['p', 'P']);
    this.bind('quicksave', ['F5']);
    this.bind('quickload', ['F9']);
  }

  _setupListeners() {
    document.addEventListener('keydown', (e) => {
      if (!this._enabled) return;
      if (!this._pressed.has(e.key)) {
        this._justPressed.add(e.key);
        // Fire action listeners
        for (const [action, keys] of this._bindings) {
          if (keys.includes(e.key)) {
            const cbs = this._listeners.get(action);
            if (cbs) for (const cb of cbs) { try { cb(e); } catch(err) { /* */ } }
          }
        }
      }
      this._pressed.add(e.key);
    });
    document.addEventListener('keyup', (e) => {
      if (!this._enabled) return;
      this._pressed.delete(e.key);
      this._justReleased.add(e.key);
    });
    document.addEventListener('mousemove', (e) => {
      this.mouse.x = e.clientX;
      this.mouse.y = e.clientY;
    });
    document.addEventListener('mousedown', (e) => {
      this.mouseDown = true;
      this._mouseButton = e.button;
    });
    document.addEventListener('mouseup', () => {
      this.mouseDown = false;
      this._mouseButton = -1;
    });
    document.addEventListener('touchstart', (e) => {
      if (e.touches.length > 0) {
        this.touch = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      }
    }, { passive: true });
    document.addEventListener('touchmove', (e) => {
      if (e.touches.length > 0) {
        this.touch = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      }
    }, { passive: true });
    document.addEventListener('touchend', () => { this.touch = null; }, { passive: true });
    // Blur: release all keys
    window.addEventListener('blur', () => {
      this._pressed.clear();
      this.mouseDown = false;
    });
  }

  /** Destroy: remove all listeners (noop for now — listeners are on document) */
  destroy() { this._enabled = false; }
};"""


def _serialization_utils() -> str:
    return """\

// ── Serialization Utilities ──────────────────────────────────────
/**
 * Deep clone, equality comparison, merge, and JSON helpers.
 */
window.CT.Utils = window.CT.Utils || {};

/**
 * Deep clone an object (handles nested objects, arrays, dates, maps, sets).
 * @param {any} obj
 * @returns {any}
 */
window.CT.Utils.deepClone = function deepClone(obj) {
  if (obj === null || typeof obj !== 'object') return obj;
  if (obj instanceof Date) return new Date(obj.getTime());
  if (obj instanceof Map) return new Map([...obj].map(([k, v]) => [deepClone(k), deepClone(v)]));
  if (obj instanceof Set) return new Set([...obj].map(v => deepClone(v)));
  if (Array.isArray(obj)) return obj.map(deepClone);
  const result = {};
  for (const [k, v] of Object.entries(obj)) result[k] = deepClone(v);
  return result;
};

/**
 * Deep equality comparison.
 * @param {any} a
 * @param {any} b
 * @returns {boolean}
 */
window.CT.Utils.deepEqual = function deepEqual(a, b) {
  if (a === b) return true;
  if (a == null || b == null) return false;
  if (typeof a !== typeof b) return false;
  if (typeof a !== 'object') return false;
  if (Array.isArray(a) !== Array.isArray(b)) return false;
  if (Array.isArray(a)) {
    if (a.length !== b.length) return false;
    return a.every((v, i) => deepEqual(v, b[i]));
  }
  const keysA = Object.keys(a);
  const keysB = Object.keys(b);
  if (keysA.length !== keysB.length) return false;
  return keysA.every(k => deepEqual(a[k], b[k]));
};

/**
 * Deep merge two objects (b overrides a).
 * @param {object} a - Base object
 * @param {object} b - Override object
 * @returns {object} Merged result (new object)
 */
window.CT.Utils.deepMerge = function deepMerge(a, b) {
  const result = window.CT.Utils.deepClone(a);
  for (const [k, v] of Object.entries(b)) {
    if (v && typeof v === 'object' && !Array.isArray(v) && result[k] && typeof result[k] === 'object') {
      result[k] = deepMerge(result[k], v);
    } else {
      result[k] = window.CT.Utils.deepClone(v);
    }
  }
  return result;
};

/**
 * Throttle a function to at most once per interval.
 * @param {Function} fn
 * @param {number} ms
 * @returns {Function}
 */
window.CT.Utils.throttle = function throttle(fn, ms) {
  let last = 0;
  let timer = null;
  return function(...args) {
    const now = Date.now();
    if (now - last >= ms) {
      last = now;
      fn.apply(this, args);
    } else if (!timer) {
      timer = setTimeout(() => {
        last = Date.now();
        timer = null;
        fn.apply(this, args);
      }, ms - (now - last));
    }
  };
};

/**
 * Debounce a function.
 * @param {Function} fn
 * @param {number} ms
 * @returns {Function}
 */
window.CT.Utils.debounce = function debounce(fn, ms) {
  let timer = null;
  return function(...args) {
    clearTimeout(timer);
    timer = setTimeout(() => fn.apply(this, args), ms);
  };
};

/**
 * Generate a short unique ID.
 * @param {number} [length=8]
 * @returns {string}
 */
window.CT.Utils.uid = function uid(length = 8) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

/**
 * Format a number with thousands separators.
 * @param {number} n
 * @returns {string}
 */
window.CT.Utils.formatNumber = function formatNumber(n) {
  return n.toLocaleString();
};

/**
 * Format a duration in ms to human-readable string.
 * @param {number} ms
 * @returns {string}
 */
window.CT.Utils.formatDuration = function formatDuration(ms) {
  if (ms < 1000) return `${Math.round(ms)}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  const mins = Math.floor(ms / 60000);
  const secs = Math.floor((ms % 60000) / 1000);
  return `${mins}m ${secs}s`;
};

/**
 * Clamp a value between min and max.
 * @param {number} value
 * @param {number} min
 * @param {number} max
 * @returns {number}
 */
window.CT.Utils.clamp = function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
};

/**
 * Linear interpolation.
 * @param {number} a - Start value
 * @param {number} b - End value
 * @param {number} t - Interpolation factor (0..1)
 * @returns {number}
 */
window.CT.Utils.lerp = function lerp(a, b, t) {
  return a + (b - a) * t;
};

/**
 * Map a value from one range to another.
 * @param {number} value
 * @param {number} inMin
 * @param {number} inMax
 * @param {number} outMin
 * @param {number} outMax
 * @returns {number}
 */
window.CT.Utils.mapRange = function mapRange(value, inMin, inMax, outMin, outMax) {
  return outMin + (outMax - outMin) * ((value - inMin) / (inMax - inMin));
};"""


def _math_utils() -> str:
    return """\

// ── Math Utilities ───────────────────────────────────────────────
/**
 * Vector2D, hex coordinate math, noise helpers, random distributions.
 */
window.CT.Math = window.CT.Math || {};

/** 2D Vector class with full operator set */
window.CT.Math.Vec2 = class Vec2 {
  constructor(x = 0, y = 0) { this.x = x; this.y = y; }
  static zero() { return new Vec2(0, 0); }
  static one() { return new Vec2(1, 1); }
  static fromAngle(angle, length = 1) { return new Vec2(Math.cos(angle) * length, Math.sin(angle) * length); }
  static random(scale = 1) { const a = Math.random() * Math.PI * 2; return Vec2.fromAngle(a, Math.random() * scale); }
  clone() { return new Vec2(this.x, this.y); }
  add(v) { return new Vec2(this.x + v.x, this.y + v.y); }
  sub(v) { return new Vec2(this.x - v.x, this.y - v.y); }
  mul(s) { return new Vec2(this.x * s, this.y * s); }
  div(s) { return s !== 0 ? new Vec2(this.x / s, this.y / s) : this.clone(); }
  dot(v) { return this.x * v.x + this.y * v.y; }
  cross(v) { return this.x * v.y - this.y * v.x; }
  get length() { return Math.sqrt(this.x * this.x + this.y * this.y); }
  get lengthSq() { return this.x * this.x + this.y * this.y; }
  get angle() { return Math.atan2(this.y, this.x); }
  normalize() { const len = this.length; return len > 0 ? this.div(len) : Vec2.zero(); }
  rotate(angle) {
    const c = Math.cos(angle), s = Math.sin(angle);
    return new Vec2(this.x * c - this.y * s, this.x * s + this.y * c);
  }
  lerp(v, t) { return new Vec2(this.x + (v.x - this.x) * t, this.y + (v.y - this.y) * t); }
  distanceTo(v) { return this.sub(v).length; }
  distanceSqTo(v) { return this.sub(v).lengthSq; }
  reflect(normal) { return this.sub(normal.mul(2 * this.dot(normal))); }
  perpCW() { return new Vec2(this.y, -this.x); }
  perpCCW() { return new Vec2(-this.y, this.x); }
  floor() { return new Vec2(Math.floor(this.x), Math.floor(this.y)); }
  ceil() { return new Vec2(Math.ceil(this.x), Math.ceil(this.y)); }
  round() { return new Vec2(Math.round(this.x), Math.round(this.y)); }
  abs() { return new Vec2(Math.abs(this.x), Math.abs(this.y)); }
  min(v) { return new Vec2(Math.min(this.x, v.x), Math.min(this.y, v.y)); }
  max(v) { return new Vec2(Math.max(this.x, v.x), Math.max(this.y, v.y)); }
  equals(v, epsilon = 1e-6) { return Math.abs(this.x - v.x) < epsilon && Math.abs(this.y - v.y) < epsilon; }
  toArray() { return [this.x, this.y]; }
  toString() { return `Vec2(${this.x.toFixed(2)}, ${this.y.toFixed(2)})`; }
  toJSON() { return { x: this.x, y: this.y }; }
  static fromJSON(j) { return new Vec2(j.x, j.y); }
};

/** Hex coordinate utilities (axial coordinates, pointy-top) */
window.CT.Math.Hex = {
  SIZE: 30,
  SQRT3: Math.sqrt(3),
  directions: [
    { q: 1, r: 0 }, { q: 1, r: -1 }, { q: 0, r: -1 },
    { q: -1, r: 0 }, { q: -1, r: 1 }, { q: 0, r: 1 },
  ],

  /** Axial to pixel (pointy-top) */
  toPixel(q, r, size) {
    size = size || this.SIZE;
    const x = size * (this.SQRT3 * q + this.SQRT3 / 2 * r);
    const y = size * (3 / 2 * r);
    return { x, y };
  },

  /** Pixel to axial (pointy-top) */
  fromPixel(px, py, size) {
    size = size || this.SIZE;
    const q = (this.SQRT3 / 3 * px - 1 / 3 * py) / size;
    const r = (2 / 3 * py) / size;
    return this.round(q, r);
  },

  /** Round fractional hex to nearest hex */
  round(q, r) {
    const s = -q - r;
    let rq = Math.round(q), rr = Math.round(r), rs = Math.round(s);
    const dq = Math.abs(rq - q), dr = Math.abs(rr - r), ds = Math.abs(rs - s);
    if (dq > dr && dq > ds) rq = -rr - rs;
    else if (dr > ds) rr = -rq - rs;
    return { q: rq, r: rr };
  },

  /** Get neighbors of a hex */
  neighbors(q, r) {
    return this.directions.map(d => ({ q: q + d.q, r: r + d.r }));
  },

  /** Hex distance */
  distance(q1, r1, q2, r2) {
    return Math.max(Math.abs(q1 - q2), Math.abs(r1 - r2), Math.abs((q1 + r1) - (q2 + r2)));
  },

  /** Get all hexes within radius */
  ring(q, r, radius) {
    if (radius === 0) return [{ q, r }];
    const results = [];
    let hex = { q: q - radius, r: r + radius };
    for (let i = 0; i < 6; i++) {
      for (let j = 0; j < radius; j++) {
        results.push({ ...hex });
        hex = { q: hex.q + this.directions[i].q, r: hex.r + this.directions[i].r };
      }
    }
    return results;
  },

  /** Get all hexes within radius (filled) */
  spiral(q, r, radius) {
    const results = [{ q, r }];
    for (let k = 1; k <= radius; k++) {
      results.push(...this.ring(q, r, k));
    }
    return results;
  },

  /** Line between two hexes */
  line(q1, r1, q2, r2) {
    const dist = this.distance(q1, r1, q2, r2);
    if (dist === 0) return [{ q: q1, r: r1 }];
    const results = [];
    for (let i = 0; i <= dist; i++) {
      const t = i / dist;
      const q = q1 + (q2 - q1) * t;
      const r = r1 + (r2 - r1) * t;
      results.push(this.round(q, r));
    }
    return results;
  },

  /** Get hex vertices for rendering */
  vertices(cx, cy, size) {
    size = size || this.SIZE;
    const verts = [];
    for (let i = 0; i < 6; i++) {
      const angle = Math.PI / 180 * (60 * i - 30);
      verts.push({ x: cx + size * Math.cos(angle), y: cy + size * Math.sin(angle) });
    }
    return verts;
  },
};

/** Random number utilities */
window.CT.Math.Random = {
  /** Random integer in [min, max] inclusive */
  int(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; },

  /** Random float in [min, max) */
  float(min, max) { return min + Math.random() * (max - min); },

  /** Random element from array */
  pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; },

  /** Shuffle array in place (Fisher-Yates) */
  shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  },

  /** Weighted random selection */
  weighted(items, weights) {
    const total = weights.reduce((a, b) => a + b, 0);
    let r = Math.random() * total;
    for (let i = 0; i < items.length; i++) {
      r -= weights[i];
      if (r <= 0) return items[i];
    }
    return items[items.length - 1];
  },

  /** Gaussian (normal) distribution using Box-Muller */
  gaussian(mean = 0, stddev = 1) {
    const u1 = Math.random();
    const u2 = Math.random();
    const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
    return mean + z * stddev;
  },

  /** Random color in hex format */
  color() { return '#' + Math.floor(Math.random() * 16777216).toString(16).padStart(6, '0'); },

  /** Seeded PRNG (simple LCG) */
  seeded(seed) {
    let s = seed;
    return () => { s = (s * 1664525 + 1013904223) & 0xFFFFFFFF; return (s >>> 0) / 0xFFFFFFFF; };
  },
};

/** Easing functions */
window.CT.Math.Easing = {
  linear: t => t,
  easeInQuad: t => t * t,
  easeOutQuad: t => t * (2 - t),
  easeInOutQuad: t => t < .5 ? 2 * t * t : -1 + (4 - 2 * t) * t,
  easeInCubic: t => t * t * t,
  easeOutCubic: t => (--t) * t * t + 1,
  easeInOutCubic: t => t < .5 ? 4 * t * t * t : (t - 1) * (2 * t - 2) * (2 * t - 2) + 1,
  easeInQuart: t => t * t * t * t,
  easeOutQuart: t => 1 - (--t) * t * t * t,
  easeInOutQuart: t => t < .5 ? 8 * t * t * t * t : 1 - 8 * (--t) * t * t * t,
  easeInSine: t => 1 - Math.cos(t * Math.PI / 2),
  easeOutSine: t => Math.sin(t * Math.PI / 2),
  easeInOutSine: t => -(Math.cos(Math.PI * t) - 1) / 2,
  easeInExpo: t => t === 0 ? 0 : Math.pow(2, 10 * (t - 1)),
  easeOutExpo: t => t === 1 ? 1 : 1 - Math.pow(2, -10 * t),
  easeInOutExpo: t => {
    if (t === 0 || t === 1) return t;
    return t < .5 ? Math.pow(2, 20 * t - 10) / 2 : (2 - Math.pow(2, -20 * t + 10)) / 2;
  },
  easeInCirc: t => 1 - Math.sqrt(1 - t * t),
  easeOutCirc: t => Math.sqrt(1 - (--t) * t),
  easeInOutCirc: t => t < .5 ? (1 - Math.sqrt(1 - 4 * t * t)) / 2 : (Math.sqrt(1 - (-2 * t + 2) ** 2) + 1) / 2,
  easeInElastic: t => t === 0 || t === 1 ? t : -Math.pow(2, 10 * t - 10) * Math.sin((t * 10 - 10.75) * (2 * Math.PI) / 3),
  easeOutElastic: t => t === 0 || t === 1 ? t : Math.pow(2, -10 * t) * Math.sin((t * 10 - 0.75) * (2 * Math.PI) / 3) + 1,
  easeInBack: t => 2.70158 * t * t * t - 1.70158 * t * t,
  easeOutBack: t => { const c = 1.70158; return 1 + (c + 1) * Math.pow(t - 1, 3) + c * Math.pow(t - 1, 2); },
  easeOutBounce: t => {
    if (t < 1/2.75) return 7.5625 * t * t;
    if (t < 2/2.75) return 7.5625 * (t -= 1.5/2.75) * t + .75;
    if (t < 2.5/2.75) return 7.5625 * (t -= 2.25/2.75) * t + .9375;
    return 7.5625 * (t -= 2.625/2.75) * t + .984375;
  },
};"""


def _color_utils() -> str:
    return """\

// ── Color Utilities ──────────────────────────────────────────────
/**
 * Color conversion, blending, palette generation, accessibility checks.
 */
window.CT.Color = window.CT.Color || {};

/** Parse a color string (hex, rgb, hsl) to {r,g,b,a} */
window.CT.Color.parse = function parse(str) {
  if (str.startsWith('#')) {
    const hex = str.slice(1);
    if (hex.length === 3) {
      return { r: parseInt(hex[0]+hex[0],16), g: parseInt(hex[1]+hex[1],16), b: parseInt(hex[2]+hex[2],16), a: 1 };
    }
    if (hex.length === 6) {
      return { r: parseInt(hex.slice(0,2),16), g: parseInt(hex.slice(2,4),16), b: parseInt(hex.slice(4,6),16), a: 1 };
    }
    if (hex.length === 8) {
      return { r: parseInt(hex.slice(0,2),16), g: parseInt(hex.slice(2,4),16), b: parseInt(hex.slice(4,6),16), a: parseInt(hex.slice(6,8),16)/255 };
    }
  }
  const rgbMatch = str.match(/rgba?\\((\\d+),\\s*(\\d+),\\s*(\\d+)(?:,\\s*([\\d.]+))?\\)/);
  if (rgbMatch) {
    return { r: +rgbMatch[1], g: +rgbMatch[2], b: +rgbMatch[3], a: rgbMatch[4] ? +rgbMatch[4] : 1 };
  }
  return { r: 0, g: 0, b: 0, a: 1 };
};

/** Convert {r,g,b} to hex string */
window.CT.Color.toHex = function toHex(c) {
  const r = Math.round(c.r).toString(16).padStart(2, '0');
  const g = Math.round(c.g).toString(16).padStart(2, '0');
  const b = Math.round(c.b).toString(16).padStart(2, '0');
  return '#' + r + g + b;
};

/** Convert {r,g,b,a} to CSS rgba string */
window.CT.Color.toRgba = function toRgba(c) {
  return `rgba(${Math.round(c.r)},${Math.round(c.g)},${Math.round(c.b)},${c.a ?? 1})`;
};

/** RGB to HSL */
window.CT.Color.rgbToHsl = function rgbToHsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }
  return { h: h * 360, s: s * 100, l: l * 100 };
};

/** HSL to RGB */
window.CT.Color.hslToRgb = function hslToRgb(h, s, l) {
  h /= 360; s /= 100; l /= 100;
  let r, g, b;
  if (s === 0) { r = g = b = l; }
  else {
    const hue2rgb = (p, q, t) => {
      if (t < 0) t += 1; if (t > 1) t -= 1;
      if (t < 1/6) return p + (q - p) * 6 * t;
      if (t < 1/2) return q;
      if (t < 2/3) return p + (q - p) * (2/3 - t) * 6;
      return p;
    };
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    r = hue2rgb(p, q, h + 1/3);
    g = hue2rgb(p, q, h);
    b = hue2rgb(p, q, h - 1/3);
  }
  return { r: Math.round(r * 255), g: Math.round(g * 255), b: Math.round(b * 255) };
};

/** Blend two colors */
window.CT.Color.blend = function blend(c1, c2, t) {
  return {
    r: c1.r + (c2.r - c1.r) * t,
    g: c1.g + (c2.g - c1.g) * t,
    b: c1.b + (c2.b - c1.b) * t,
    a: (c1.a ?? 1) + ((c2.a ?? 1) - (c1.a ?? 1)) * t,
  };
};

/** Calculate relative luminance (WCAG) */
window.CT.Color.luminance = function luminance(c) {
  const toLinear = v => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); };
  return 0.2126 * toLinear(c.r) + 0.7152 * toLinear(c.g) + 0.0722 * toLinear(c.b);
};

/** Calculate WCAG contrast ratio between two colors */
window.CT.Color.contrastRatio = function contrastRatio(c1, c2) {
  const l1 = window.CT.Color.luminance(c1);
  const l2 = window.CT.Color.luminance(c2);
  const lighter = Math.max(l1, l2);
  const darker = Math.min(l1, l2);
  return (lighter + 0.05) / (darker + 0.05);
};

/** Generate a complementary palette from a base hue */
window.CT.Color.complementaryPalette = function complementaryPalette(baseHue, count = 5) {
  const colors = [];
  for (let i = 0; i < count; i++) {
    const hue = (baseHue + (360 / count) * i) % 360;
    colors.push(window.CT.Color.hslToRgb(hue, 70, 55));
  }
  return colors;
};

/** Generate an analogous palette */
window.CT.Color.analogousPalette = function analogousPalette(baseHue, count = 5, spread = 30) {
  const colors = [];
  const step = spread / (count - 1 || 1);
  for (let i = 0; i < count; i++) {
    const hue = (baseHue - spread / 2 + step * i + 360) % 360;
    colors.push(window.CT.Color.hslToRgb(hue, 65, 55));
  }
  return colors;
};

/** Lighten a color by percentage */
window.CT.Color.lighten = function lighten(c, amount) {
  const hsl = window.CT.Color.rgbToHsl(c.r, c.g, c.b);
  hsl.l = Math.min(100, hsl.l + amount);
  return window.CT.Color.hslToRgb(hsl.h, hsl.s, hsl.l);
};

/** Darken a color by percentage */
window.CT.Color.darken = function darken(c, amount) {
  const hsl = window.CT.Color.rgbToHsl(c.r, c.g, c.b);
  hsl.l = Math.max(0, hsl.l - amount);
  return window.CT.Color.hslToRgb(hsl.h, hsl.s, hsl.l);
};

/** Saturate a color by percentage */
window.CT.Color.saturate = function saturate(c, amount) {
  const hsl = window.CT.Color.rgbToHsl(c.r, c.g, c.b);
  hsl.s = Math.min(100, hsl.s + amount);
  return window.CT.Color.hslToRgb(hsl.h, hsl.s, hsl.l);
};

/** Desaturate a color by percentage */
window.CT.Color.desaturate = function desaturate(c, amount) {
  const hsl = window.CT.Color.rgbToHsl(c.r, c.g, c.b);
  hsl.s = Math.max(0, hsl.s - amount);
  return window.CT.Color.hslToRgb(hsl.h, hsl.s, hsl.l);
};"""


def _animation_utils() -> str:
    return """\

// ── Animation Utilities ──────────────────────────────────────────
/**
 * Tween engine, spring physics, particle effects, screen shake.
 */
window.CT.Anim = window.CT.Anim || {};

/** Simple tween manager */
window.CT.Anim.TweenManager = class TweenManager {
  constructor() { this._tweens = []; }

  /**
   * Create a tween.
   * @param {object} target - Object to animate
   * @param {object} props - Target property values
   * @param {number} duration - Duration in ms
   * @param {object} [options] - { easing, delay, onUpdate, onComplete }
   * @returns {object} Tween handle with cancel()
   */
  tween(target, props, duration, options = {}) {
    const tween = {
      target, props,
      startValues: {},
      duration,
      elapsed: -(options.delay || 0),
      easing: options.easing || window.CT.Math.Easing.easeInOutQuad,
      onUpdate: options.onUpdate || null,
      onComplete: options.onComplete || null,
      done: false,
    };
    for (const key of Object.keys(props)) {
      tween.startValues[key] = target[key];
    }
    this._tweens.push(tween);
    return {
      cancel: () => { tween.done = true; },
      promise: new Promise(resolve => { tween._resolve = resolve; }),
    };
  }

  /** Update all tweens (call with dt in ms) */
  update(dt) {
    for (const tw of this._tweens) {
      if (tw.done) continue;
      tw.elapsed += dt;
      if (tw.elapsed < 0) continue;
      const t = Math.min(tw.elapsed / tw.duration, 1);
      const easedT = tw.easing(t);
      for (const [key, endVal] of Object.entries(tw.props)) {
        tw.target[key] = tw.startValues[key] + (endVal - tw.startValues[key]) * easedT;
      }
      if (tw.onUpdate) tw.onUpdate(t);
      if (t >= 1) {
        tw.done = true;
        if (tw.onComplete) tw.onComplete();
        if (tw._resolve) tw._resolve();
      }
    }
    this._tweens = this._tweens.filter(tw => !tw.done);
  }

  /** @returns {number} Active tween count */
  get count() { return this._tweens.length; }

  /** Cancel all tweens */
  clear() { this._tweens.length = 0; }
};

/** Spring physics simulation */
window.CT.Anim.Spring = class Spring {
  /**
   * @param {number} stiffness - Spring constant (40-400)
   * @param {number} damping - Damping factor (4-40)
   * @param {number} mass - Mass (0.1-10)
   */
  constructor(stiffness = 170, damping = 26, mass = 1) {
    this.stiffness = stiffness;
    this.damping = damping;
    this.mass = mass;
    this.value = 0;
    this.target = 0;
    this.velocity = 0;
  }

  /** Update spring simulation (dt in seconds) */
  update(dt) {
    const springForce = -this.stiffness * (this.value - this.target);
    const dampingForce = -this.damping * this.velocity;
    const acceleration = (springForce + dampingForce) / this.mass;
    this.velocity += acceleration * dt;
    this.value += this.velocity * dt;
    return this.value;
  }

  /** @returns {boolean} True if spring is approximately at rest */
  get atRest() {
    return Math.abs(this.value - this.target) < 0.001 && Math.abs(this.velocity) < 0.001;
  }

  /** Set target and optionally current value */
  set(target, immediate = false) {
    this.target = target;
    if (immediate) { this.value = target; this.velocity = 0; }
  }
};

/** Screen shake effect */
window.CT.Anim.ScreenShake = class ScreenShake {
  constructor() {
    this.offsetX = 0;
    this.offsetY = 0;
    this._intensity = 0;
    this._decay = 0;
    this._duration = 0;
    this._elapsed = 0;
  }

  /** Trigger a screen shake */
  shake(intensity = 10, duration = 300) {
    this._intensity = intensity;
    this._duration = duration;
    this._elapsed = 0;
  }

  /** Update shake (call with dt in ms) */
  update(dt) {
    if (this._elapsed >= this._duration) {
      this.offsetX = 0;
      this.offsetY = 0;
      return;
    }
    this._elapsed += dt;
    const progress = this._elapsed / this._duration;
    const currentIntensity = this._intensity * (1 - progress);
    this.offsetX = (Math.random() - 0.5) * 2 * currentIntensity;
    this.offsetY = (Math.random() - 0.5) * 2 * currentIntensity;
  }

  /** @returns {boolean} */
  get active() { return this._elapsed < this._duration; }
};

/** Particle effect system (lightweight, for UI effects) */
window.CT.Anim.ParticleEffect = class ParticleEffect {
  constructor(options = {}) {
    this.particles = [];
    this.maxParticles = options.maxParticles || 100;
    this.gravity = options.gravity || 0;
  }

  /** Emit particles at position */
  emit(x, y, count = 10, options = {}) {
    for (let i = 0; i < count && this.particles.length < this.maxParticles; i++) {
      const angle = options.angle ?? (Math.random() * Math.PI * 2);
      const speed = options.speed ?? (1 + Math.random() * 3);
      this.particles.push({
        x, y,
        vx: Math.cos(angle) * speed + (options.spread ? (Math.random() - .5) * options.spread : 0),
        vy: Math.sin(angle) * speed + (options.spread ? (Math.random() - .5) * options.spread : 0),
        life: 1,
        decay: options.decay ?? (0.01 + Math.random() * 0.02),
        size: options.size ?? (2 + Math.random() * 4),
        color: options.color || '#ffffff',
        rotation: Math.random() * Math.PI * 2,
        rotationSpeed: (Math.random() - 0.5) * 0.1,
      });
    }
  }

  /** Update all particles (dt in seconds) */
  update(dt) {
    const dtScale = dt * 60; // normalize to 60fps
    for (const p of this.particles) {
      p.x += p.vx * dtScale;
      p.y += p.vy * dtScale;
      p.vy += this.gravity * dtScale;
      p.life -= p.decay * dtScale;
      p.rotation += p.rotationSpeed * dtScale;
    }
    this.particles = this.particles.filter(p => p.life > 0);
  }

  /** Render to canvas context */
  render(ctx) {
    for (const p of this.particles) {
      ctx.save();
      ctx.globalAlpha = p.life;
      ctx.translate(p.x, p.y);
      ctx.rotate(p.rotation);
      ctx.fillStyle = p.color;
      ctx.fillRect(-p.size / 2, -p.size / 2, p.size, p.size);
      ctx.restore();
    }
  }

  /** @returns {boolean} */
  get active() { return this.particles.length > 0; }

  /** Remove all particles */
  clear() { this.particles.length = 0; }
};"""


def _validation_utils() -> str:
    return """\

// ── Validation Utilities ─────────────────────────────────────────
/**
 * Schema validation, input sanitization, type guards.
 */
window.CT.Validate = window.CT.Validate || {};

/** Validate an object against a schema */
window.CT.Validate.check = function check(value, schema) {
  const errors = [];
  _validate(value, schema, '', errors);
  return { valid: errors.length === 0, errors };
};

function _validate(value, schema, path, errors) {
  if (schema.type) {
    const actualType = Array.isArray(value) ? 'array' : typeof value;
    if (actualType !== schema.type) {
      errors.push({ path: path || 'root', expected: schema.type, actual: actualType, message: `Expected ${schema.type} at ${path || 'root'}, got ${actualType}` });
      return;
    }
  }
  if (schema.required && (value === null || value === undefined)) {
    errors.push({ path, message: `Required field missing: ${path}` });
    return;
  }
  if (value === null || value === undefined) return;
  if (schema.type === 'number') {
    if (schema.min !== undefined && value < schema.min) errors.push({ path, message: `${path} must be >= ${schema.min}` });
    if (schema.max !== undefined && value > schema.max) errors.push({ path, message: `${path} must be <= ${schema.max}` });
    if (schema.integer && !Number.isInteger(value)) errors.push({ path, message: `${path} must be an integer` });
  }
  if (schema.type === 'string') {
    if (schema.minLength !== undefined && value.length < schema.minLength) errors.push({ path, message: `${path} must be at least ${schema.minLength} chars` });
    if (schema.maxLength !== undefined && value.length > schema.maxLength) errors.push({ path, message: `${path} must be at most ${schema.maxLength} chars` });
    if (schema.pattern && !new RegExp(schema.pattern).test(value)) errors.push({ path, message: `${path} does not match pattern ${schema.pattern}` });
    if (schema.enum && !schema.enum.includes(value)) errors.push({ path, message: `${path} must be one of: ${schema.enum.join(', ')}` });
  }
  if (schema.type === 'array') {
    if (schema.minItems !== undefined && value.length < schema.minItems) errors.push({ path, message: `${path} must have at least ${schema.minItems} items` });
    if (schema.maxItems !== undefined && value.length > schema.maxItems) errors.push({ path, message: `${path} must have at most ${schema.maxItems} items` });
    if (schema.items) {
      value.forEach((item, i) => _validate(item, schema.items, `${path}[${i}]`, errors));
    }
  }
  if (schema.type === 'object' && schema.properties) {
    for (const [key, propSchema] of Object.entries(schema.properties)) {
      _validate(value[key], propSchema, path ? `${path}.${key}` : key, errors);
    }
  }
}

/** Sanitize a string (HTML escape) */
window.CT.Validate.escapeHtml = function escapeHtml(str) {
  const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
  return str.replace(/[&<>"']/g, c => map[c]);
};

/** Sanitize for use in attribute */
window.CT.Validate.escapeAttr = function escapeAttr(str) {
  return str.replace(/[&"'<>]/g, c => `&#${c.charCodeAt(0)};`);
};

/** Check if a string is a valid email */
window.CT.Validate.isEmail = function isEmail(str) {
  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(str);
};

/** Check if a string is a valid URL */
window.CT.Validate.isUrl = function isUrl(str) {
  try { new URL(str); return true; } catch { return false; }
};

/** Type guard helpers */
window.CT.Validate.isNumber = v => typeof v === 'number' && !isNaN(v);
window.CT.Validate.isString = v => typeof v === 'string';
window.CT.Validate.isBoolean = v => typeof v === 'boolean';
window.CT.Validate.isArray = v => Array.isArray(v);
window.CT.Validate.isObject = v => v !== null && typeof v === 'object' && !Array.isArray(v);
window.CT.Validate.isFunction = v => typeof v === 'function';
window.CT.Validate.isNonEmpty = v => typeof v === 'string' && v.trim().length > 0;"""


def _data_structures() -> str:
    return """\

// ── Data Structures ──────────────────────────────────────────────
/**
 * Priority queue, spatial hash, ring buffer, object pool.
 */

/** Min-heap priority queue */
window.CT.PriorityQueue = class PriorityQueue {
  constructor(comparator = (a, b) => a.priority - b.priority) {
    this._heap = [];
    this._comparator = comparator;
  }

  get size() { return this._heap.length; }
  get isEmpty() { return this._heap.length === 0; }

  push(item) {
    this._heap.push(item);
    this._bubbleUp(this._heap.length - 1);
  }

  pop() {
    if (this._heap.length === 0) return undefined;
    const top = this._heap[0];
    const bottom = this._heap.pop();
    if (this._heap.length > 0 && bottom !== undefined) {
      this._heap[0] = bottom;
      this._sinkDown(0);
    }
    return top;
  }

  peek() { return this._heap[0]; }

  clear() { this._heap.length = 0; }

  _bubbleUp(i) {
    while (i > 0) {
      const parent = Math.floor((i - 1) / 2);
      if (this._comparator(this._heap[i], this._heap[parent]) >= 0) break;
      [this._heap[i], this._heap[parent]] = [this._heap[parent], this._heap[i]];
      i = parent;
    }
  }

  _sinkDown(i) {
    const len = this._heap.length;
    while (true) {
      let smallest = i;
      const left = 2 * i + 1, right = 2 * i + 2;
      if (left < len && this._comparator(this._heap[left], this._heap[smallest]) < 0) smallest = left;
      if (right < len && this._comparator(this._heap[right], this._heap[smallest]) < 0) smallest = right;
      if (smallest === i) break;
      [this._heap[i], this._heap[smallest]] = [this._heap[smallest], this._heap[i]];
      i = smallest;
    }
  }
};

/** Spatial hash grid for efficient neighbor queries */
window.CT.SpatialHash = class SpatialHash {
  constructor(cellSize = 100) {
    this.cellSize = cellSize;
    this._cells = new Map();
    this._objectCells = new Map();
  }

  _key(cx, cy) { return `${cx},${cy}`; }
  _cellCoords(x, y) { return { cx: Math.floor(x / this.cellSize), cy: Math.floor(y / this.cellSize) }; }

  /** Insert an object with a bounding box */
  insert(id, x, y, width = 0, height = 0) {
    this.remove(id);
    const { cx: minCx, cy: minCy } = this._cellCoords(x, y);
    const { cx: maxCx, cy: maxCy } = this._cellCoords(x + width, y + height);
    const cells = [];
    for (let cx = minCx; cx <= maxCx; cx++) {
      for (let cy = minCy; cy <= maxCy; cy++) {
        const key = this._key(cx, cy);
        if (!this._cells.has(key)) this._cells.set(key, new Set());
        this._cells.get(key).add(id);
        cells.push(key);
      }
    }
    this._objectCells.set(id, { cells, x, y, width, height });
  }

  /** Remove an object */
  remove(id) {
    const info = this._objectCells.get(id);
    if (!info) return;
    for (const key of info.cells) {
      const cell = this._cells.get(key);
      if (cell) { cell.delete(id); if (cell.size === 0) this._cells.delete(key); }
    }
    this._objectCells.delete(id);
  }

  /** Query objects in a rectangular region */
  query(x, y, width, height) {
    const result = new Set();
    const { cx: minCx, cy: minCy } = this._cellCoords(x, y);
    const { cx: maxCx, cy: maxCy } = this._cellCoords(x + width, y + height);
    for (let cx = minCx; cx <= maxCx; cx++) {
      for (let cy = minCy; cy <= maxCy; cy++) {
        const cell = this._cells.get(this._key(cx, cy));
        if (cell) for (const id of cell) result.add(id);
      }
    }
    return [...result];
  }

  /** Query objects near a point within radius */
  queryRadius(x, y, radius) {
    const candidates = this.query(x - radius, y - radius, radius * 2, radius * 2);
    const rSq = radius * radius;
    return candidates.filter(id => {
      const info = this._objectCells.get(id);
      if (!info) return false;
      const dx = (info.x + info.width / 2) - x;
      const dy = (info.y + info.height / 2) - y;
      return dx * dx + dy * dy <= rSq;
    });
  }

  /** Clear all objects */
  clear() { this._cells.clear(); this._objectCells.clear(); }
  get size() { return this._objectCells.size; }
};

/** Ring buffer (fixed-size circular buffer) */
window.CT.RingBuffer = class RingBuffer {
  constructor(capacity) {
    this._capacity = capacity;
    this._buffer = new Array(capacity);
    this._head = 0;
    this._size = 0;
  }

  push(item) {
    this._buffer[(this._head + this._size) % this._capacity] = item;
    if (this._size < this._capacity) this._size++;
    else this._head = (this._head + 1) % this._capacity;
  }

  get(i) {
    if (i < 0 || i >= this._size) return undefined;
    return this._buffer[(this._head + i) % this._capacity];
  }

  get size() { return this._size; }
  get capacity() { return this._capacity; }
  get isFull() { return this._size === this._capacity; }

  /** Get the most recent item */
  get latest() { return this._size > 0 ? this.get(this._size - 1) : undefined; }

  /** Convert to array (oldest first) */
  toArray() {
    const result = [];
    for (let i = 0; i < this._size; i++) result.push(this.get(i));
    return result;
  }

  /** Get average of numeric values */
  average() {
    if (this._size === 0) return 0;
    let sum = 0;
    for (let i = 0; i < this._size; i++) sum += this.get(i);
    return sum / this._size;
  }

  clear() { this._size = 0; this._head = 0; }
};

/** Object pool for reusable instances */
window.CT.ObjectPool = class ObjectPool {
  constructor(factory, reset, initialSize = 0) {
    this._factory = factory;
    this._reset = reset;
    this._pool = [];
    this._active = new Set();
    for (let i = 0; i < initialSize; i++) this._pool.push(factory());
  }

  acquire() {
    const obj = this._pool.length > 0 ? this._pool.pop() : this._factory();
    this._active.add(obj);
    return obj;
  }

  release(obj) {
    if (!this._active.has(obj)) return;
    this._active.delete(obj);
    this._reset(obj);
    this._pool.push(obj);
  }

  releaseAll() {
    for (const obj of this._active) {
      this._reset(obj);
      this._pool.push(obj);
    }
    this._active.clear();
  }

  get activeCount() { return this._active.size; }
  get poolSize() { return this._pool.length; }
  get totalSize() { return this._active.size + this._pool.length; }
};"""


def _testing_helpers() -> str:
    return """\

// ── Testing / Debug Helpers ──────────────────────────────────────
/**
 * In-app testing framework for validating game/art systems.
 * Provides assertion, test runner, and debug overlay.
 */
window.CT.Test = window.CT.Test || {};

/** Simple assertion library */
window.CT.Test.assert = function assert(condition, message) {
  if (!condition) {
    const error = new Error(`Assertion failed: ${message || 'unknown'}`);
    console.error(error);
    window.CT.Test._failures.push({ message, error, timestamp: Date.now() });
    return false;
  }
  window.CT.Test._passes++;
  return true;
};

window.CT.Test.assertEqual = function assertEqual(actual, expected, message) {
  const msg = message || `Expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`;
  return window.CT.Test.assert(
    window.CT.Utils.deepEqual ? window.CT.Utils.deepEqual(actual, expected) : actual === expected,
    msg
  );
};

window.CT.Test.assertThrows = function assertThrows(fn, message) {
  try { fn(); return window.CT.Test.assert(false, message || 'Expected function to throw'); }
  catch (e) { window.CT.Test._passes++; return true; }
};

window.CT.Test._passes = 0;
window.CT.Test._failures = [];

/** Run a test suite */
window.CT.Test.run = function run(name, testFn) {
  const before = window.CT.Test._passes;
  const beforeFailures = window.CT.Test._failures.length;
  console.group(`[Test] ${name}`);
  try { testFn(); }
  catch (e) { console.error('Test error:', e); window.CT.Test._failures.push({ message: e.message, error: e }); }
  const passed = window.CT.Test._passes - before;
  const failed = window.CT.Test._failures.length - beforeFailures;
  console.log(`${passed} passed, ${failed} failed`);
  console.groupEnd();
  return { passed, failed };
};

/** Get test summary */
window.CT.Test.summary = function summary() {
  return { passes: window.CT.Test._passes, failures: [...window.CT.Test._failures] };
};

/** Reset test state */
window.CT.Test.reset = function reset() {
  window.CT.Test._passes = 0;
  window.CT.Test._failures = [];
};

/** Debug overlay — shows FPS, memory, active systems */
window.CT.DebugOverlay = class DebugOverlay {
  constructor() {
    this._el = null;
    this._visible = false;
    this._lines = new Map();
  }

  /** Show the debug overlay */
  show() {
    if (!this._el) {
      this._el = document.createElement('div');
      this._el.style.cssText = 'position:fixed;top:0;left:0;background:rgba(0,0,0,.8);color:#0f0;' +
        'font:11px/1.4 monospace;padding:8px 12px;z-index:9999;pointer-events:none;min-width:200px;' +
        'border-bottom-right-radius:8px;white-space:pre;';
      document.body.appendChild(this._el);
    }
    this._visible = true;
    this._el.style.display = 'block';
  }

  /** Hide the debug overlay */
  hide() {
    if (this._el) this._el.style.display = 'none';
    this._visible = false;
  }

  /** Toggle visibility */
  toggle() { this._visible ? this.hide() : this.show(); }

  /**
   * Set a debug line value.
   * @param {string} key
   * @param {any} value
   */
  set(key, value) {
    this._lines.set(key, value);
    this._render();
  }

  /** Remove a debug line */
  remove(key) {
    this._lines.delete(key);
    this._render();
  }

  _render() {
    if (!this._el || !this._visible) return;
    const lines = [];
    for (const [k, v] of this._lines) {
      lines.push(`${k}: ${typeof v === 'number' ? v.toFixed(2) : v}`);
    }
    this._el.textContent = lines.join('\\n');
  }

  /** Auto-update with PerformanceMonitor data */
  bindPerformance(perf) {
    const update = () => {
      if (!this._visible) { requestAnimationFrame(update); return; }
      this.set('FPS', perf.fps);
      this.set('Frame', perf.frameTime.toFixed(1) + 'ms');
      this.set('Jitter', perf.jitter.toFixed(1) + 'ms');
      const mem = perf._getMemory();
      if (mem) this.set('Memory', `${mem.used}/${mem.total}MB`);
      requestAnimationFrame(update);
    };
    requestAnimationFrame(update);
  }
};"""
