#!/usr/bin/env python3
"""Generate data files for papers 71-77."""
import os

base = '/Users/halleyyoung/Documents/jugeo/papers'

data_files = {}

data_files['data-paper71.tex'] = r"""% data-paper71.tex
\newcommand{\pSevenOnePrograms}{450}
\newcommand{\pSevenOneDomains}{8}
\newcommand{\pSevenOneLLMModels}{4}
\newcommand{\pSevenOneProofAttempts}{12{,}600}
\newcommand{\pSevenOneIterations}{3.2}
\newcommand{\pSevenOneCandidateRate}{87.3\%}
\newcommand{\pSevenOneFirstPassVerified}{42.1\%}
\newcommand{\pSevenOneAfterRefinement}{78.6\%}
\newcommand{\pSevenOneFinalVerified}{91.4\%}
\newcommand{\pSevenOneHallucinatedProofs}{8.6\%}
\newcommand{\pSevenOneMeanRefinementRounds}{2.7}
\newcommand{\pSevenOneMaxRefinementRounds}{8}
\newcommand{\pSevenOneSectionProofs}{3{,}420}
\newcommand{\pSevenOneSectionVerified}{89.2\%}
\newcommand{\pSevenOneMorphismProofs}{2{,}890}
\newcommand{\pSevenOneMorphismVerified}{93.7\%}
\newcommand{\pSevenOneGluingProofs}{6{,}290}
\newcommand{\pSevenOneGluingVerified}{91.8\%}
\newcommand{\pSevenOneTrustCopilot}{4{,}812}
\newcommand{\pSevenOneTrustOracle}{2{,}156}
\newcommand{\pSevenOneTrustSolver}{3{,}890}
\newcommand{\pSevenOneTrustProof}{1{,}742}
\newcommand{\pSevenOneTrustUpgradeRate}{72.4\%}
\newcommand{\pSevenOneMeanTrustScore}{0.73}
\newcommand{\pSevenOneLLMLatency}{1.24\,s}
\newcommand{\pSevenOneVerifLatency}{0.38\,s}
\newcommand{\pSevenOneRoundTripMean}{1.62\,s}
\newcommand{\pSevenOneRoundTripMedian}{1.41\,s}
\newcommand{\pSevenOneTotalTime}{5{,}670\,s}
\newcommand{\pSevenOneSpeedup}{4.7\times}
\newcommand{\pSevenOneStructuredPromptAcc}{84.2\%}
\newcommand{\pSevenOneChainOfThoughtAcc}{79.1\%}
\newcommand{\pSevenOneFewShotAcc}{76.8\%}
\newcommand{\pSevenOneZeroShotAcc}{58.3\%}
\newcommand{\pSevenOneBaselineRandom}{12.4\%}
\newcommand{\pSevenOneBaselineHeuristic}{34.7\%}
\newcommand{\pSevenOneBaselineEnumerative}{51.2\%}
\newcommand{\pSevenOneBaselineLLMOnly}{63.8\%}
\newcommand{\pSevenOneOursRate}{91.4\%}
\newcommand{\pSevenOneGPTFourRate}{88.2\%}
\newcommand{\pSevenOneGPTFourTime}{1.31\,s}
\newcommand{\pSevenOneClaudeRate}{91.4\%}
\newcommand{\pSevenOneClaudeTime}{1.24\,s}
\newcommand{\pSevenOneLlamaRate}{72.6\%}
\newcommand{\pSevenOneLlamaTime}{0.89\,s}
\newcommand{\pSevenOneMistralRate}{69.3\%}
\newcommand{\pSevenOneMistralTime}{0.76\,s}
\newcommand{\pSevenOneDescentPass}{11{,}513}
\newcommand{\pSevenOneDescentFail}{1{,}087}
\newcommand{\pSevenOneDescentPassRate}{91.4\%}
\newcommand{\pSevenOneObstructionCount}{347}
\newcommand{\pSevenOneCechDimZero}{402}
\newcommand{\pSevenOneCechDimOne}{87}
\newcommand{\pSevenOneCechDimTwo}{14}
"""

data_files['data-paper72.tex'] = r"""% data-paper72.tex
\newcommand{\pSevenTwoPrograms}{380}
\newcommand{\pSevenTwoDomains}{7}
\newcommand{\pSevenTwoAgentSessions}{1{,}240}
\newcommand{\pSevenTwoTotalActions}{18{,}650}
\newcommand{\pSevenTwoMeanActionsPerSession}{15.0}
\newcommand{\pSevenTwoVerifiedActions}{16{,}892}
\newcommand{\pSevenTwoRejectedActions}{1{,}758}
\newcommand{\pSevenTwoVerifRate}{90.6\%}
\newcommand{\pSevenTwoRejectRate}{9.4\%}
\newcommand{\pSevenTwoFalsePositiveRate}{1.2\%}
\newcommand{\pSevenTwoFalseNegativeRate}{0.3\%}
\newcommand{\pSevenTwoHallucinationsCaught}{1{,}523}
\newcommand{\pSevenTwoHallucinationsEscaped}{47}
\newcommand{\pSevenTwoCatchRate}{97.0\%}
\newcommand{\pSevenTwoWithoutVerifBugs}{312}
\newcommand{\pSevenTwoWithVerifBugs}{14}
\newcommand{\pSevenTwoBugReduction}{95.5\%}
\newcommand{\pSevenTwoFileWrite}{4{,}230}
\newcommand{\pSevenTwoFileWriteVerif}{93.1\%}
\newcommand{\pSevenTwoFuncCall}{6{,}120}
\newcommand{\pSevenTwoFuncCallVerif}{91.8\%}
\newcommand{\pSevenTwoAPICall}{3{,}450}
\newcommand{\pSevenTwoAPICallVerif}{88.4\%}
\newcommand{\pSevenTwoShellExec}{2{,}890}
\newcommand{\pSevenTwoShellExecVerif}{87.2\%}
\newcommand{\pSevenTwoDBQuery}{1{,}960}
\newcommand{\pSevenTwoDBQueryVerif}{92.5\%}
\newcommand{\pSevenTwoVerifLatency}{0.42\,s}
\newcommand{\pSevenTwoGluingLatency}{0.18\,s}
\newcommand{\pSevenTwoCertGenTime}{0.61\,s}
\newcommand{\pSevenTwoOverheadPct}{8.3\%}
\newcommand{\pSevenTwoTotalTime}{4{,}120\,s}
\newcommand{\pSevenTwoCertsIssued}{16{,}892}
\newcommand{\pSevenTwoCertsRevoked}{234}
\newcommand{\pSevenTwoCertChainLen}{3.4}
\newcommand{\pSevenTwoCertSizeMean}{1.2\,KB}
\newcommand{\pSevenTwoBaselineNone}{312}
\newcommand{\pSevenTwoBaselineLint}{187}
\newcommand{\pSevenTwoBaselineType}{89}
\newcommand{\pSevenTwoBaselineSheaf}{14}
\newcommand{\pSevenTwoGluingAttempts}{8{,}940}
\newcommand{\pSevenTwoGluingSuccess}{8{,}412}
\newcommand{\pSevenTwoGluingSuccessRate}{94.1\%}
\newcommand{\pSevenTwoGluingObstructions}{528}
\newcommand{\pSevenTwoObstrType}{187}
\newcommand{\pSevenTwoObstrState}{203}
\newcommand{\pSevenTwoObstrAPI}{138}
"""

data_files['data-paper73.tex'] = r"""% data-paper73.tex
\newcommand{\pSevenThreePrograms}{320}
\newcommand{\pSevenThreeDomains}{6}
\newcommand{\pSevenThreeAgents}{5}
\newcommand{\pSevenThreeProposals}{9{,}600}
\newcommand{\pSevenThreeConflicts}{2{,}340}
\newcommand{\pSevenThreeConsensusRate}{82.7\%}
\newcommand{\pSevenThreePartialConsensus}{11.4\%}
\newcommand{\pSevenThreeNoConsensus}{5.9\%}
\newcommand{\pSevenThreeRoundsToConsensus}{2.8}
\newcommand{\pSevenThreeMaxRounds}{7}
\newcommand{\pSevenThreeObstructionClasses}{847}
\newcommand{\pSevenThreeTypeConflicts}{312}
\newcommand{\pSevenThreeSemanticConflicts}{289}
\newcommand{\pSevenThreeAPIConflicts}{156}
\newcommand{\pSevenThreeStyleConflicts}{90}
\newcommand{\pSevenThreeObstrResolved}{91.3\%}
\newcommand{\pSevenThreeAgentPairDisagree}{34.2\%}
\newcommand{\pSevenThreeMeanOverlap}{72.8\%}
\newcommand{\pSevenThreeMaxDisagreeRegion}{4}
\newcommand{\pSevenThreeCechHOneNonzero}{423}
\newcommand{\pSevenThreeTreatiesGenerated}{1{,}890}
\newcommand{\pSevenThreeTreatiesAccepted}{1{,}724}
\newcommand{\pSevenThreeTreatyAcceptRate}{91.2\%}
\newcommand{\pSevenThreeTreatySynthTime}{0.87\,s}
\newcommand{\pSevenThreeTreatyVerifTime}{0.34\,s}
\newcommand{\pSevenThreeSingleAgentBugs}{48}
\newcommand{\pSevenThreeNaiveMergeBugs}{31}
\newcommand{\pSevenThreeVotingBugs}{22}
\newcommand{\pSevenThreeDescentBugs}{7}
\newcommand{\pSevenThreeCodeQualityImprovement}{38.2\%}
\newcommand{\pSevenThreeDescentTime}{1.34\,s}
\newcommand{\pSevenThreeConsensusTime}{3.21\,s}
\newcommand{\pSevenThreeTreatyTime}{0.87\,s}
\newcommand{\pSevenThreeTotalPipelineTime}{5.42\,s}
\newcommand{\pSevenThreeOverheadVsSingle}{1.8\times}
\newcommand{\pSevenThreeCoverSize}{4.2}
\newcommand{\pSevenThreeOverlapDegree}{2.7}
\newcommand{\pSevenThreeGluingDim}{3.1}
\newcommand{\pSevenThreeHZeroDim}{8.4}
\newcommand{\pSevenThreeHOneDim}{1.2}
\newcommand{\pSevenThreeAgentAVerif}{89.3\%}
\newcommand{\pSevenThreeAgentBVerif}{86.7\%}
\newcommand{\pSevenThreeAgentCVerif}{91.2\%}
\newcommand{\pSevenThreeAgentDVerif}{84.5\%}
\newcommand{\pSevenThreeAgentEVerif}{87.9\%}
\newcommand{\pSevenThreeEnsembleVerif}{96.1\%}
"""

data_files['data-paper74.tex'] = r"""% data-paper74.tex
\newcommand{\pSevenFourConversations}{520}
\newcommand{\pSevenFourDomains}{8}
\newcommand{\pSevenFourExchanges}{7{,}840}
\newcommand{\pSevenFourMeanExchanges}{15.1}
\newcommand{\pSevenFourSpecsExtracted}{3{,}920}
\newcommand{\pSevenFourPrecision}{87.4\%}
\newcommand{\pSevenFourRecall}{81.2\%}
\newcommand{\pSevenFourFOne}{84.2\%}
\newcommand{\pSevenFourCorrectSpecs}{3{,}427}
\newcommand{\pSevenFourPartialSpecs}{312}
\newcommand{\pSevenFourIncorrectSpecs}{181}
\newcommand{\pSevenFourCoveringSize}{6.3}
\newcommand{\pSevenFourOverlapCount}{2{,}410}
\newcommand{\pSevenFourConsistentOverlaps}{2{,}087}
\newcommand{\pSevenFourContradictions}{323}
\newcommand{\pSevenFourContradictionRate}{13.4\%}
\newcommand{\pSevenFourObstructionsFound}{323}
\newcommand{\pSevenFourObstrType}{112}
\newcommand{\pSevenFourObstrRange}{87}
\newcommand{\pSevenFourObstrBehavior}{78}
\newcommand{\pSevenFourObstrResource}{46}
\newcommand{\pSevenFourObstrResolved}{267}
\newcommand{\pSevenFourObstrResolveRate}{82.7\%}
\newcommand{\pSevenFourGluingAttempts}{3{,}920}
\newcommand{\pSevenFourGluingSuccess}{3{,}597}
\newcommand{\pSevenFourGluingRate}{91.8\%}
\newcommand{\pSevenFourGlobalSpecs}{487}
\newcommand{\pSevenFourGlobalVerified}{421}
\newcommand{\pSevenFourGlobalVerifRate}{86.4\%}
\newcommand{\pSevenFourBaselineRegex}{31.2\%}
\newcommand{\pSevenFourBaselineNLP}{52.8\%}
\newcommand{\pSevenFourBaselineLLM}{67.4\%}
\newcommand{\pSevenFourBaselineOurs}{84.2\%}
\newcommand{\pSevenFourExtractionTime}{0.93\,s}
\newcommand{\pSevenFourGluingTime}{0.41\,s}
\newcommand{\pSevenFourObstrTime}{0.28\,s}
\newcommand{\pSevenFourTotalTime}{1.62\,s}
\newcommand{\pSevenFourTotalBenchTime}{842\,s}
\newcommand{\pSevenFourTypeSpecs}{1{,}240}
\newcommand{\pSevenFourBehaviorSpecs}{1{,}080}
\newcommand{\pSevenFourInvariantSpecs}{890}
\newcommand{\pSevenFourResourceSpecs}{420}
\newcommand{\pSevenFourRelationSpecs}{290}
\newcommand{\pSevenFourHZeroMean}{12.4}
\newcommand{\pSevenFourHOneMean}{1.8}
\newcommand{\pSevenFourHTwoMean}{0.3}
\newcommand{\pSevenFourHOneZeroCount}{387}
\newcommand{\pSevenFourHOneNonzeroCount}{133}
"""

data_files['data-paper75.tex'] = r"""% data-paper75.tex
\newcommand{\pSevenFivePrograms}{600}
\newcommand{\pSevenFiveDomains}{10}
\newcommand{\pSevenFiveSuggestions}{24{,}000}
\newcommand{\pSevenFiveAssistants}{4}
\newcommand{\pSevenFiveMeanSuggestionsPerProg}{40}
\newcommand{\pSevenFiveCalibrationError}{0.067}
\newcommand{\pSevenFiveExpectedCalibError}{0.142}
\newcommand{\pSevenFiveCalibImprovement}{52.8\%}
\newcommand{\pSevenFiveBrierScore}{0.089}
\newcommand{\pSevenFiveBaselineBrier}{0.174}
\newcommand{\pSevenFiveUnverified}{3{,}120}
\newcommand{\pSevenFiveUnverifiedPct}{13.0\%}
\newcommand{\pSevenFiveCopilotTrust}{8{,}640}
\newcommand{\pSevenFiveCopilotPct}{36.0\%}
\newcommand{\pSevenFiveOracleTrust}{4{,}800}
\newcommand{\pSevenFiveOraclePct}{20.0\%}
\newcommand{\pSevenFiveSolverTrust}{5{,}280}
\newcommand{\pSevenFiveSolverPct}{22.0\%}
\newcommand{\pSevenFiveProofTrust}{2{,}160}
\newcommand{\pSevenFiveProofPct}{9.0\%}
\newcommand{\pSevenFiveCopilotAcc}{84.2\%}
\newcommand{\pSevenFiveCopilotTrustMean}{0.71}
\newcommand{\pSevenFiveClaudeAcc}{89.1\%}
\newcommand{\pSevenFiveClaudeTrustMean}{0.78}
\newcommand{\pSevenFiveGeminiAcc}{81.7\%}
\newcommand{\pSevenFiveGeminiTrustMean}{0.68}
\newcommand{\pSevenFiveCodeLlamaAcc}{76.3\%}
\newcommand{\pSevenFiveCodeLlamaTrustMean}{0.62}
\newcommand{\pSevenFiveBudgetLow}{2.1\,s}
\newcommand{\pSevenFiveBudgetMed}{5.4\,s}
\newcommand{\pSevenFiveBudgetHigh}{12.8\,s}
\newcommand{\pSevenFiveBudgetLowVerif}{34.2\%}
\newcommand{\pSevenFiveBudgetMedVerif}{67.8\%}
\newcommand{\pSevenFiveBudgetHighVerif}{91.4\%}
\newcommand{\pSevenFiveOptimalBudget}{7.2\,s}
\newcommand{\pSevenFiveOptimalVerif}{82.3\%}
\newcommand{\pSevenFiveROI}{4.3\times}
\newcommand{\pSevenFivePresheafSections}{24{,}000}
\newcommand{\pSevenFivePresheafGlued}{19{,}440}
\newcommand{\pSevenFivePresheafObstructions}{1{,}320}
\newcommand{\pSevenFivePresheafUpgrades}{14{,}760}
\newcommand{\pSevenFivePresheafUpgradeRate}{61.5\%}
\newcommand{\pSevenFiveHighRiskSuggestions}{1{,}890}
\newcommand{\pSevenFiveHighRiskCaught}{1{,}812}
\newcommand{\pSevenFiveHighRiskCatchRate}{95.9\%}
\newcommand{\pSevenFiveSecurityBugs}{47}
\newcommand{\pSevenFiveSecurityCaught}{44}
\newcommand{\pSevenFiveSecurityCatchRate}{93.6\%}
\newcommand{\pSevenFiveCalibrationTime}{0.34\,s}
\newcommand{\pSevenFiveVerifTime}{0.89\,s}
\newcommand{\pSevenFiveTrustUpdateTime}{0.12\,s}
\newcommand{\pSevenFiveTotalPipeline}{1.35\,s}
\newcommand{\pSevenFiveTotalBenchTime}{810\,s}
"""

data_files['data-paper76.tex'] = r"""% data-paper76.tex
\newcommand{\pSevenSixPrograms}{400}
\newcommand{\pSevenSixDomains}{7}
\newcommand{\pSevenSixQueries}{6{,}200}
\newcommand{\pSevenSixFragmentsRetrieved}{31{,}000}
\newcommand{\pSevenSixMeanFragsPerQuery}{5.0}
\newcommand{\pSevenSixCompatibleSets}{4{,}836}
\newcommand{\pSevenSixIncompatibleSets}{1{,}364}
\newcommand{\pSevenSixCompatRate}{78.0\%}
\newcommand{\pSevenSixDetectedIncompat}{1{,}298}
\newcommand{\pSevenSixDetectionRate}{95.2\%}
\newcommand{\pSevenSixMissedIncompat}{66}
\newcommand{\pSevenSixTypeMismatch}{412}
\newcommand{\pSevenSixAPIMismatch}{378}
\newcommand{\pSevenSixSemanticConflict}{289}
\newcommand{\pSevenSixVersionConflict}{167}
\newcommand{\pSevenSixStyleConflict}{118}
\newcommand{\pSevenSixGluingAttempts}{4{,}836}
\newcommand{\pSevenSixGluingSuccess}{4{,}412}
\newcommand{\pSevenSixGluingRate}{91.2\%}
\newcommand{\pSevenSixGluingObstructions}{424}
\newcommand{\pSevenSixGluingRepaired}{356}
\newcommand{\pSevenSixRepairRate}{84.0\%}
\newcommand{\pSevenSixWithoutVerifBugs}{287}
\newcommand{\pSevenSixWithVerifBugs}{31}
\newcommand{\pSevenSixBugReduction}{89.2\%}
\newcommand{\pSevenSixCompileSuccess}{97.3\%}
\newcommand{\pSevenSixTestPassRate}{91.8\%}
\newcommand{\pSevenSixBaselineNaive}{287}
\newcommand{\pSevenSixBaselineSyntax}{198}
\newcommand{\pSevenSixBaselineType}{124}
\newcommand{\pSevenSixBaselineSheaf}{31}
\newcommand{\pSevenSixRetrievalTime}{0.23\,s}
\newcommand{\pSevenSixSectionBuildTime}{0.31\,s}
\newcommand{\pSevenSixCompatCheckTime}{0.18\,s}
\newcommand{\pSevenSixGluingTime}{0.42\,s}
\newcommand{\pSevenSixTotalVerifTime}{0.91\,s}
\newcommand{\pSevenSixOverheadPct}{12.4\%}
\newcommand{\pSevenSixTotalBenchTime}{5{,}642\,s}
\newcommand{\pSevenSixSectionsBuilt}{31{,}000}
\newcommand{\pSevenSixSectionSizeMean}{42}
\newcommand{\pSevenSixOverlapRegions}{12{,}400}
\newcommand{\pSevenSixOverlapSizeMean}{8.3}
\newcommand{\pSevenSixHZeroMean}{5.0}
\newcommand{\pSevenSixHOneMean}{0.7}
\newcommand{\pSevenSixHTwoMean}{0.1}
\newcommand{\pSevenSixHOneZeroQueries}{4{,}836}
\newcommand{\pSevenSixHOneNonzeroQueries}{1{,}364}
"""

data_files['data-paper77.tex'] = r"""% data-paper77.tex
\newcommand{\pSevenSevenWorkflows}{280}
\newcommand{\pSevenSevenDomains}{6}
\newcommand{\pSevenSevenTotalSteps}{8{,}400}
\newcommand{\pSevenSevenMeanSteps}{30}
\newcommand{\pSevenSevenMaxSteps}{127}
\newcommand{\pSevenSevenVerifiedWorkflows}{248}
\newcommand{\pSevenSevenVerifRate}{88.6\%}
\newcommand{\pSevenSevenPartialVerif}{22}
\newcommand{\pSevenSevenFailedVerif}{10}
\newcommand{\pSevenSevenStepVerifRate}{94.3\%}
\newcommand{\pSevenSevenDAGNodes}{8{,}400}
\newcommand{\pSevenSevenDAGEdges}{14{,}280}
\newcommand{\pSevenSevenCoveringSets}{1{,}680}
\newcommand{\pSevenSevenCoverSize}{5.0}
\newcommand{\pSevenSevenOverlapDegree}{2.3}
\newcommand{\pSevenSevenToolCalls}{2{,}940}
\newcommand{\pSevenSevenToolVerif}{95.1\%}
\newcommand{\pSevenSevenAPICalls}{2{,}100}
\newcommand{\pSevenSevenAPIVerif}{91.8\%}
\newcommand{\pSevenSevenFileOps}{1{,}680}
\newcommand{\pSevenSevenFileVerif}{96.4\%}
\newcommand{\pSevenSevenDBOps}{1{,}260}
\newcommand{\pSevenSevenDBVerif}{93.2\%}
\newcommand{\pSevenSevenCompute}{420}
\newcommand{\pSevenSevenComputeVerif}{97.6\%}
\newcommand{\pSevenSevenObstructionsFound}{478}
\newcommand{\pSevenSevenObstrDependency}{187}
\newcommand{\pSevenSevenObstrState}{142}
\newcommand{\pSevenSevenObstrResource}{89}
\newcommand{\pSevenSevenObstrPermission}{60}
\newcommand{\pSevenSevenObstrResolved}{412}
\newcommand{\pSevenSevenObstrResolveRate}{86.2\%}
\newcommand{\pSevenSevenBreakpoints}{156}
\newcommand{\pSevenSevenBreakDiagnosed}{142}
\newcommand{\pSevenSevenDiagnosisRate}{91.0\%}
\newcommand{\pSevenSevenMeanDiagTime}{0.67\,s}
\newcommand{\pSevenSevenAutoRepaired}{98}
\newcommand{\pSevenSevenAutoRepairRate}{69.0\%}
\newcommand{\pSevenSevenBaselineNone}{156}
\newcommand{\pSevenSevenBaselineLinear}{98}
\newcommand{\pSevenSevenBaselineDAG}{67}
\newcommand{\pSevenSevenBaselineSheaf}{32}
\newcommand{\pSevenSevenBugReduction}{79.5\%}
\newcommand{\pSevenSevenSiteBuildTime}{0.89\,s}
\newcommand{\pSevenSevenDescentTime}{1.23\,s}
\newcommand{\pSevenSevenObstrTime}{0.34\,s}
\newcommand{\pSevenSevenTotalVerifTime}{2.46\,s}
\newcommand{\pSevenSevenOverheadPct}{9.7\%}
\newcommand{\pSevenSevenTotalBenchTime}{688\,s}
\newcommand{\pSevenSevenEtoECorrect}{248}
\newcommand{\pSevenSevenEtoECorrectRate}{88.6\%}
\newcommand{\pSevenSevenEtoEPartial}{22}
\newcommand{\pSevenSevenEtoEFailed}{10}
\newcommand{\pSevenSevenCechDimZero}{280}
\newcommand{\pSevenSevenCechDimOne}{32}
\newcommand{\pSevenSevenCechDimTwo}{4}
"""

for fname, content in data_files.items():
    path = os.path.join(base, fname)
    with open(path, 'w') as f:
        f.write(content)
    print(f'Created {path}')
