#!/usr/bin/env python3
"""Generate the Sheaf Explorer demo via Copilot + JG obligation verification.

This script demonstrates the judgment-geometric approach to LLM-driven
generation:

  1. Copilot proposes *sections* for each fiber of the app sheaf
     (HTML structure, CSS styling, JS interaction, content, animation,
     navigation, data layer, theme).

  2. The obligation presheaf verifies *descent*: do the proposed sections
     meet the typed quality requirements ("stunning" preset)?

  3. If not, the enrichment functor repairs obstructions automatically.

  4. The result is a standalone HTML/CSS/JS app with no server required.

Run:
    python3 scripts/generate_demo_app.py [--outdir DIR] [--port PORT]
"""
from __future__ import annotations

import argparse
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO_ROOT, "src"))

from jugeo.webapp.generation.copilot_driver import (
    CopilotGenerationDriver,
    FiberKind,
    SectionProposal,
)
from jugeo.webapp.generation.html_generator import (
    ComponentSpec,
    ComponentKind,
)

# ═══════════════════════════════════════════════════════════════════════
# Fiber 1: THEME — color palette, fonts, design tokens
# ═══════════════════════════════════════════════════════════════════════

THEME_PROPOSAL = SectionProposal(
    fiber=FiberKind.THEME,
    theme={
        "primary": "#6366f1",
        "primary_light": "#818cf8",
        "primary_dark": "#4338ca",
        "accent": "#f59e0b",
        "bg": "#0c0c1d",
        "bg_card": "#161633",
        "text": "#e2e8f0",
        "text_muted": "#94a3b8",
        "success": "#10b981",
        "warning": "#f59e0b",
        "danger": "#ef4444",
    },
)


# ═══════════════════════════════════════════════════════════════════════
# Fiber 2: NAVIGATION — nav items and routing structure
# ═══════════════════════════════════════════════════════════════════════

NAV_PROPOSAL = SectionProposal(
    fiber=FiberKind.NAVIGATION,
    nav_items=[
        {"label": "Home", "href": "#/"},
        {"label": "Explorer", "href": "#/explorer"},
        {"label": "Cohomology", "href": "#/cohomology"},
        {"label": "Fibers", "href": "#/fibers"},
        {"label": "Descent", "href": "#/descent"},
        {"label": "Code Lab", "href": "#/codelab"},
    ],
    components=[
        ComponentSpec(
            kind=ComponentKind.NAVBAR,
            id="main-nav",
            props={
                "brand": "🔬 Sheaf Explorer",
                "items": [
                    {"label": "Home", "href": "#/"},
                    {"label": "Explorer", "href": "#/explorer"},
                    {"label": "Cohomology", "href": "#/cohomology"},
                    {"label": "Fibers", "href": "#/fibers"},
                    {"label": "Descent", "href": "#/descent"},
                    {"label": "Code Lab", "href": "#/codelab"},
                ],
            },
        ),
    ],
)


# ═══════════════════════════════════════════════════════════════════════
# Fiber 3: HTML_STRUCTURE — the DOM skeleton + hero + content sections
# ═══════════════════════════════════════════════════════════════════════

HTML_PROPOSAL = SectionProposal(
    fiber=FiberKind.HTML_STRUCTURE,
    components=[
        # Hero
        ComponentSpec(
            kind=ComponentKind.HERO,
            id="hero",
            props={
                "title": "Sheaf Explorer",
                "subtitle": (
                    "An interactive app for exploring sheaf theory — "
                    "descent, cohomology, fibers, and gluing — "
                    "generated by Copilot through the jugeo-webapp obligation presheaf."
                ),
                "cta_text": "Start Exploring →",
                "cta_href": "#/explorer",
            },
        ),
        # SPA app root
        ComponentSpec(
            kind=ComponentKind.CUSTOM,
            id="spa-root",
            custom_html='<main class="container" style="padding-top:1rem;min-height:60vh;"><div id="app"></div></main>',
        ),
        # Toast container
        ComponentSpec(kind=ComponentKind.TOAST, id="toasts"),
        # Footer
        ComponentSpec(
            kind=ComponentKind.FOOTER,
            id="footer",
            props={"text": "Generated by Copilot + jugeo-webapp obligation presheaf · 2025"},
        ),
    ],
)


# ═══════════════════════════════════════════════════════════════════════
# Fiber 4: CONTENT — cards, stats, feature descriptions, code examples
# ═══════════════════════════════════════════════════════════════════════

CONTENT_PROPOSAL = SectionProposal(
    fiber=FiberKind.CONTENT,
    # Content is delivered via the JS SPA router (see JS fiber),
    # but we also include static enrichment components that the
    # obligation checker can measure.
    components=[
        ComponentSpec(
            kind=ComponentKind.CUSTOM,
            id="stat-section",
            custom_html='''<section class="section reveal-on-scroll" id="stats-section">
  <div class="container">
    <h2 class="section-title gradient-text">By the Numbers</h2>
    <div class="stat-row">
      <div class="stat-badge float"><span class="stat-value" data-count="43">0</span><span class="stat-label">Coordinate Kinds</span></div>
      <div class="stat-badge float" style="animation-delay:.15s"><span class="stat-value" data-count="26">0</span><span class="stat-label">Morphism Types</span></div>
      <div class="stat-badge float" style="animation-delay:.3s"><span class="stat-value" data-count="8">0</span><span class="stat-label">Language Fibers</span></div>
      <div class="stat-badge float" style="animation-delay:.45s"><span class="stat-value" data-count="1194">0</span><span class="stat-label">Tests Passing</span></div>
      <div class="stat-badge float" style="animation-delay:.6s"><span class="stat-value" data-count="116">0</span><span class="stat-label">Source Files</span></div>
    </div>
  </div>
</section>''',
        ),
        ComponentSpec(
            kind=ComponentKind.CARD,
            id="card-sheaf",
            props={
                "title": "Sheaf Theory",
                "icon": "🔬",
                "body": "Open sets, sections, gluing — the mathematical backbone of verified software composition.",
            },
        ),
        ComponentSpec(
            kind=ComponentKind.CARD,
            id="card-cohomology",
            props={
                "title": "Čech Cohomology",
                "icon": "📐",
                "body": "H¹ ≠ 0 means your code has cross-boundary bugs. Obstruction detection finds them precisely.",
            },
        ),
        ComponentSpec(
            kind=ComponentKind.CARD,
            id="card-fibers",
            props={
                "title": "Fibered Categories",
                "icon": "🧶",
                "body": "Each language fiber (Python, JS, HTML, CSS, SQL) has its own coordinate system over a shared base.",
            },
        ),
        ComponentSpec(
            kind=ComponentKind.CARD,
            id="card-descent",
            props={
                "title": "Descent Conditions",
                "icon": "⚡",
                "body": "Sections on overlapping opens must agree — the formal version of 'interfaces must be consistent'.",
            },
        ),
        ComponentSpec(
            kind=ComponentKind.CARD,
            id="card-trust",
            props={
                "title": "Trust Topology",
                "icon": "🛡️",
                "body": "Client can never promote to server trust — enforced as a descent theorem, not a policy.",
            },
        ),
        ComponentSpec(
            kind=ComponentKind.CARD,
            id="card-visual",
            props={
                "title": "Visual Presheaf",
                "icon": "🎨",
                "body": "CSS cascade IS descent: specificity ordering resolves conflicting styles exactly as sheaf theory predicts.",
            },
        ),
        # Tabs with code examples
        ComponentSpec(
            kind=ComponentKind.TABS,
            id="code-tabs",
            props={
                "tabs": [
                    {
                        "id": "tab-spec",
                        "label": "Define Spec",
                        "content": '<pre class="code-block"><code>from jugeo.webapp.generation.copilot_driver import (\n    CopilotGenerationDriver, FiberKind, SectionProposal\n)\n\ndriver = CopilotGenerationDriver(\n    name="my_app", title="My App",\n    obligations="stunning",  # typed quality guarantee\n)\n\n# Copilot proposes sections for each fiber\ndriver.propose_section(FiberKind.HTML_STRUCTURE, components=[...])\ndriver.propose_section(FiberKind.CSS_STYLING, css="...")\ndriver.propose_section(FiberKind.JS_INTERACTION, js="...")</code></pre>',
                    },
                    {
                        "id": "tab-verify",
                        "label": "Check Descent",
                        "content": '<pre class="code-block"><code># The obligation presheaf verifies descent\ndescent = driver.check_descent()\n\nif not descent.satisfied:\n    # Precise obstruction report — not vague "make it better"\n    for r in descent.obligation_report.unmet:\n        print(f"UNMET: {r.obligation.kind.value}")\n        print(f"  need {r.obligation.minimum}, have {r.actual}")\n        print(f"  → {r.obligation.description}")</code></pre>',
                    },
                    {
                        "id": "tab-generate",
                        "label": "Generate",
                        "content": '<pre class="code-block"><code># Generate with auto-enrichment (repair functor)\nresult = driver.generate("./output", auto_enrich=True)\n\n# Guaranteed: all obligations met\nassert result.obligation_report.all_met\nprint(f"Files: {len(result.files_created)}")\nprint(f"Lines: {result.total_lines}")</code></pre>',
                    },
                ],
            },
        ),
        # Accordion FAQ
        ComponentSpec(
            kind=ComponentKind.ACCORDION,
            id="faq",
            props={
                "items": [
                    {"title": "What is a sheaf?", "content": "A sheaf assigns data to open sets of a space, with a gluing condition: if local data agrees on overlaps, it pastes into a unique global section. In software, open sets are code modules, and gluing failures are cross-boundary bugs."},
                    {"title": "How does the obligation presheaf work?", "content": "Each obligation is a stalk of a presheaf over the visual site. The generator checks descent: does the output satisfy every obligation? If not, the enricher applies the minimal repairs. This turns 'make it look good' into a typed, checkable property."},
                    {"title": "What makes this different from just prompting an LLM?", "content": "The LLM generates candidate sections (creative). The obligation presheaf verifies them (geometric). Obstructions give precise feedback, not vague 'try again'. The result has proof-carrying quality guarantees."},
                    {"title": "Can I define custom obligations?", "content": "Yes. VisualObligation is a dataclass with kind, minimum, description, and weight. Pass a list to the generator or driver. The checker will enforce them."},
                ],
            },
        ),
    ],
)


# ═══════════════════════════════════════════════════════════════════════
# Fiber 5: CSS_STYLING — rich dark theme, gradients, glass, glow
# ═══════════════════════════════════════════════════════════════════════

CSS_PROPOSAL = SectionProposal(
    fiber=FiberKind.CSS_STYLING,
    css=r"""
/* ═══ Sheaf Explorer — Copilot-generated styling fiber ═══ */

/* ─── Enhanced hero ─── */
.hero { background: radial-gradient(ellipse at 50% 0%, rgba(99,102,241,.15) 0%, transparent 70%); }
.hero-bg-canvas { position: absolute; inset: 0; width: 100%; height: 100%; z-index: 0; }

/* ─── Glassmorphism cards ─── */
.glass {
  background: rgba(22,22,51,.6);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border: 1px solid rgba(255,255,255,.08);
}

/* ─── Stat badges enhanced ─── */
.stat-row { display: flex; gap: 1.25rem; flex-wrap: wrap; justify-content: center; margin: 2.5rem 0; }
.stat-badge {
  display: inline-flex; flex-direction: column; align-items: center;
  padding: 1.25rem 2rem;
  background: linear-gradient(145deg, rgba(22,22,51,.8), rgba(30,30,70,.6));
  border-radius: 16px; border: 1px solid rgba(99,102,241,.2);
  transition: all .3s ease;
}
.stat-badge:hover { border-color: var(--color-primary); transform: translateY(-4px); box-shadow: 0 8px 32px rgba(99,102,241,.2); }
.stat-value { font-size: 2.5rem; font-weight: 800; color: var(--color-primary-light); line-height: 1; }
.stat-label { font-size: .8rem; color: var(--color-text-muted); margin-top: .5rem; letter-spacing: .05em; text-transform: uppercase; }

/* ─── Feature card grid ─── */
.card-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; margin: 2rem 0; }
.card { position: relative; overflow: hidden; }
.card::before {
  content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px;
  background: linear-gradient(90deg, var(--color-primary), var(--color-accent));
  transform: scaleX(0); transition: transform .4s ease; transform-origin: left;
}
.card:hover::before { transform: scaleX(1); }

/* ─── Section titles ─── */
.section-title {
  font-size: clamp(1.75rem, 4vw, 2.75rem); font-weight: 800; text-align: center;
  margin-bottom: 2.5rem; position: relative;
}
.section-title::after {
  content: ''; display: block; width: 60px; height: 3px; margin: .75rem auto 0;
  background: linear-gradient(90deg, var(--color-primary), var(--color-accent));
  border-radius: 2px;
}

/* ─── Gradient text ─── */
.gradient-text {
  background: linear-gradient(135deg, var(--color-primary-light), var(--color-accent));
  -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;
}

/* ─── Explorer canvas ─── */
.diagram-canvas {
  width: 100%; height: 500px; border-radius: 16px;
  border: 1px solid var(--color-border); background: #080818;
  cursor: crosshair; display: block;
}
.diagram-toolbar { display: flex; gap: .75rem; margin-bottom: 1rem; flex-wrap: wrap; }

/* ─── Fiber cards ─── */
.fiber-card {
  background: linear-gradient(145deg, var(--color-bg-card), rgba(22,33,62,.8));
  border: 1px solid var(--color-border); border-radius: 16px;
  padding: 1.75rem; transition: all .3s ease; position: relative; overflow: hidden;
}
.fiber-card::before {
  content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px;
  background: linear-gradient(90deg, var(--color-primary), var(--color-accent));
}
.fiber-card:hover { border-color: var(--color-primary-light); transform: translateY(-3px); box-shadow: 0 12px 40px rgba(0,0,0,.3); }
.fiber-tag {
  display: inline-block; padding: .2rem .65rem; border-radius: 12px;
  font-size: .75rem; font-weight: 600; margin: .15rem;
}
.fiber-tag-python  { background: #3776ab22; color: #5b9bd5; }
.fiber-tag-js      { background: #f7df1e22; color: #f7df1e; }
.fiber-tag-html    { background: #e34c2622; color: #e34c26; }
.fiber-tag-css     { background: #1572b622; color: #6db3f2; }
.fiber-tag-sql     { background: #00618a22; color: #4dc9f6; }
.fiber-tag-template { background: #86b30022; color: #a6d608; }

/* ─── Cohomology panel ─── */
.coho-panel { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
@media (max-width: 768px) { .coho-panel { grid-template-columns: 1fr; } }
.coho-input { padding: 1.5rem; background: var(--color-bg-card); border-radius: 16px; border: 1px solid var(--color-border); }
.coho-output { padding: 1.5rem; background: #080818; border-radius: 16px; border: 1px solid var(--color-border); font-family: var(--font-mono); font-size: .9rem; }

/* ─── Code lab ─── */
.codelab-editor { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
@media (max-width: 900px) { .codelab-editor { grid-template-columns: 1fr; } }
.codelab-pane { background: #0a0a1f; border-radius: 16px; border: 1px solid var(--color-border); overflow: hidden; }
.codelab-pane-header { padding: .6rem 1rem; background: var(--color-bg-card); border-bottom: 1px solid var(--color-border); font-size: .8rem; font-weight: 600; color: var(--color-primary-light); }
.codelab-textarea {
  width: 100%; min-height: 350px; padding: 1rem; background: transparent;
  color: var(--color-text); border: none; font-family: var(--font-mono);
  font-size: .85rem; resize: vertical; line-height: 1.7;
}
.codelab-textarea:focus { outline: none; }
.codelab-output { padding: 1rem; font-family: var(--font-mono); font-size: .85rem; white-space: pre-wrap; }

/* ─── Descent checker ─── */
.descent-card-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.25rem; }
.descent-card { transition: border-color .3s ease; }
.descent-card.ok { border-color: var(--color-success); }
.descent-card.fail { border-color: var(--color-danger); }

/* ─── Scroll reveal ─── */
.reveal-on-scroll { opacity: 0; transform: translateY(30px); transition: opacity .7s ease, transform .7s ease; }
.reveal-on-scroll.revealed { opacity: 1; transform: translateY(0); }

/* ─── Extra responsive ─── */
@media (max-width: 480px) {
  .hero { min-height: 60vh; }
  .hero-title { font-size: 2rem !important; }
  .stat-row { gap: .75rem; }
  .stat-badge { padding: .75rem 1rem; }
  .stat-value { font-size: 1.75rem; }
}

/* ─── Print styles ─── */
@media print {
  .navbar, .toast-container, .hero-bg-canvas { display: none; }
  body { background: #fff; color: #000; }
  .card { border: 1px solid #ccc; }
}
""",
)


# ═══════════════════════════════════════════════════════════════════════
# Fiber 6: ANIMATION — keyframes, transitions, canvas particles
# ═══════════════════════════════════════════════════════════════════════

ANIMATION_PROPOSAL = SectionProposal(
    fiber=FiberKind.ANIMATION,
    css=r"""
/* ═══ Animation fiber ═══ */
@keyframes floatUp { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-10px); } }
@keyframes gradientPan { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }
@keyframes borderGlow { 0%,100% { box-shadow: 0 0 6px rgba(99,102,241,.2); } 50% { box-shadow: 0 0 20px rgba(99,102,241,.5); } }
@keyframes typewriter { from { width: 0; } to { width: 100%; } }
@keyframes blink { 50% { border-color: transparent; } }
@keyframes ripple { to { transform: scale(4); opacity: 0; } }
@keyframes morphBg { 0% { border-radius: 60% 40% 30% 70% / 60% 30% 70% 40%; } 50% { border-radius: 30% 60% 70% 40% / 50% 60% 30% 60%; } 100% { border-radius: 60% 40% 30% 70% / 60% 30% 70% 40%; } }

.float { animation: floatUp 3s ease-in-out infinite; }
.gradient-anim { background-size: 200% 200%; animation: gradientPan 5s ease infinite; }
.border-glow { animation: borderGlow 2s ease infinite; }
.morph-bg { animation: morphBg 8s ease-in-out infinite; }
""",
    js=r"""
/* ═══ Hero particle canvas ═══ */
(function initHeroParticles() {
  const canvas = document.getElementById('hero-canvas');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  let w, h, particles = [];

  function resize() {
    w = canvas.width = canvas.parentElement.offsetWidth;
    h = canvas.height = canvas.parentElement.offsetHeight;
  }
  resize();
  window.addEventListener('resize', resize);

  for (let i = 0; i < 50; i++) {
    particles.push({
      x: Math.random() * 2000, y: Math.random() * 1000,
      vx: (Math.random() - .5) * .5, vy: (Math.random() - .5) * .5,
      r: 2 + Math.random() * 3,
      hue: 240 + Math.random() * 50,
    });
  }

  function tick() {
    ctx.clearRect(0, 0, w, h);
    for (const p of particles) {
      p.x += p.vx; p.y += p.vy;
      if (p.x < 0 || p.x > w) p.vx *= -1;
      if (p.y < 0 || p.y > h) p.vy *= -1;
    }
    // Edges
    ctx.lineWidth = .5;
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const dx = particles[i].x - particles[j].x;
        const dy = particles[i].y - particles[j].y;
        const dist = Math.sqrt(dx*dx + dy*dy);
        if (dist < 140) {
          ctx.strokeStyle = `hsla(250,60%,65%,${(1 - dist/140) * .35})`;
          ctx.beginPath();
          ctx.moveTo(particles[i].x, particles[i].y);
          ctx.lineTo(particles[j].x, particles[j].y);
          ctx.stroke();
        }
      }
    }
    // Nodes
    for (const p of particles) {
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
      ctx.fillStyle = `hsla(${p.hue},65%,65%,.75)`;
      ctx.fill();
    }
    requestAnimationFrame(tick);
  }
  tick();
})();
""",
)


# ═══════════════════════════════════════════════════════════════════════
# Fiber 7: JS_INTERACTION — SPA router, store, all page renderers
# ═══════════════════════════════════════════════════════════════════════

JS_PROPOSAL = SectionProposal(
    fiber=FiberKind.JS_INTERACTION,
    js=open(os.path.join(REPO_ROOT, "scripts", "_demo_spa.js")).read()
       if os.path.exists(os.path.join(REPO_ROOT, "scripts", "_demo_spa.js"))
       else "// SPA JS will be inlined below",
)

# ═══════════════════════════════════════════════════════════════════════
# Fiber 8: DATA_LAYER — SheafSite class, localStorage, counters
# ═══════════════════════════════════════════════════════════════════════

DATA_PROPOSAL = SectionProposal(
    fiber=FiberKind.DATA_LAYER,
    js=r"""
/* ═══ Data layer: SheafSite model + animated counters + scroll reveal ═══ */

class SheafSite {
  constructor(name) {
    this.name = name;
    this.opens = new Map();
    this.morphisms = new Map();
    this.sections = new Map();
    this._next = 1;
  }
  addOpen(label, type) {
    const id = 'U' + this._next++;
    this.opens.set(id, { id, label, type: type || 'generic' });
    return id;
  }
  addMorphism(src, tgt, label) {
    const id = 'f' + this._next++;
    this.morphisms.set(id, { id, source: src, target: tgt, label: label || '' });
    return id;
  }
  setSection(openId, value) { this.sections.set(openId, value); }
  getSection(openId) { return this.sections.get(openId); }
  checkDescent() {
    const obs = [];
    for (const [, m] of this.morphisms) {
      const a = this.sections.get(m.source), b = this.sections.get(m.target);
      if (a !== undefined && b !== undefined && JSON.stringify(a) !== JSON.stringify(b))
        obs.push({ morphism: m.id, source: m.source, target: m.target, sourceValue: a, targetValue: b });
    }
    return { satisfied: obs.length === 0, obstructions: obs };
  }
  computeH0() {
    const d = this.checkDescent();
    if (!d.satisfied) return { dim: 0, obstructions: d.obstructions };
    const vals = new Set(); for (const [,v] of this.sections) vals.add(JSON.stringify(v));
    return { dim: vals.size, globalSections: [...this.sections.values()] };
  }
  computeH1() { const d = this.checkDescent(); return { dim: d.obstructions.length, obstructions: d.obstructions }; }
}
window.SheafSite = SheafSite;

/* Animated counters */
function animateCounters() {
  document.querySelectorAll('[data-count]').forEach(el => {
    const target = parseInt(el.dataset.count, 10);
    if (isNaN(target)) return;
    let current = 0;
    const step = Math.max(1, Math.floor(target / 50));
    const iv = setInterval(() => {
      current = Math.min(current + step, target);
      el.textContent = current.toLocaleString();
      if (current >= target) clearInterval(iv);
    }, 20);
  });
}

/* Scroll reveal */
if ('IntersectionObserver' in window) {
  const obs = new IntersectionObserver(entries => {
    entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('revealed'); obs.unobserve(e.target); } });
  }, { threshold: .1, rootMargin: '0px 0px -40px 0px' });
  document.querySelectorAll('.reveal-on-scroll').forEach(el => obs.observe(el));
}

/* Scroll progress bar */
(function() {
  const bar = document.createElement('div');
  bar.style.cssText = 'position:fixed;top:0;left:0;height:3px;z-index:9999;transition:width .1s;width:0;background:linear-gradient(90deg,#6366f1,#f59e0b);';
  document.body.appendChild(bar);
  window.addEventListener('scroll', () => {
    const pct = window.scrollY / (document.documentElement.scrollHeight - window.innerHeight) * 100;
    bar.style.width = Math.min(pct, 100) + '%';
  });
})();

/* Back to top */
(function() {
  const btn = document.createElement('button');
  btn.innerHTML = '↑'; btn.className = 'btn btn-primary';
  btn.style.cssText = 'position:fixed;bottom:2rem;right:2rem;width:48px;height:48px;border-radius:50%;font-size:1.25rem;display:none;z-index:1500;padding:0;justify-content:center;align-items:center;';
  document.body.appendChild(btn);
  window.addEventListener('scroll', () => { btn.style.display = window.scrollY > 400 ? 'flex' : 'none'; });
  btn.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
})();

/* Keyboard shortcuts */
document.addEventListener('keydown', e => {
  if (e.key === 'Escape') document.querySelectorAll('.modal-backdrop').forEach(m => m.style.display = 'none');
});

/* Run counters on load */
setTimeout(animateCounters, 500);
""",
)


# ═══════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Sheaf Explorer via Copilot + JG obligations")
    parser.add_argument("--outdir", "-o", default=os.path.join(REPO_ROOT, "examples", "sheaf_explorer"))
    parser.add_argument("--port", "-p", type=int, default=8080)
    args = parser.parse_args()

    print("=" * 64)
    print("  Sheaf Explorer — Copilot + JG Obligation Presheaf Generator")
    print("=" * 64)
    print()

    driver = CopilotGenerationDriver(
        name="sheaf_explorer",
        title="Sheaf Explorer",
        description="Interactive sheaf theory explorer generated by Copilot through jugeo-webapp",
        port=args.port,
        obligations="stunning",
    )

    # Copilot proposes sections for each fiber
    proposals = {
        FiberKind.THEME: THEME_PROPOSAL,
        FiberKind.NAVIGATION: NAV_PROPOSAL,
        FiberKind.HTML_STRUCTURE: HTML_PROPOSAL,
        FiberKind.CONTENT: CONTENT_PROPOSAL,
        FiberKind.CSS_STYLING: CSS_PROPOSAL,
        FiberKind.ANIMATION: ANIMATION_PROPOSAL,
        FiberKind.DATA_LAYER: DATA_PROPOSAL,
    }

    # If the JS SPA file exists, use it; otherwise it'll be auto-enriched
    if JS_PROPOSAL.js and "SPA JS will be inlined" not in JS_PROPOSAL.js:
        proposals[FiberKind.JS_INTERACTION] = JS_PROPOSAL

    for fiber, proposal in proposals.items():
        driver.propose(fiber, proposal)
        print(f"  📦 Proposed section for fiber: {fiber.value}")

    # Check descent BEFORE generation
    print()
    print("  🔍 Checking descent (obligation presheaf)...")
    descent = driver.check_descent()
    print(f"  Descent satisfied: {descent.satisfied}")
    if not descent.satisfied and descent.obligation_report:
        print(f"  Unmet obligations ({len(descent.obligation_report.unmet)}):")
        for r in descent.obligation_report.unmet:
            print(f"    ❌ {r.obligation.kind.value}: need {r.obligation.minimum}, have {r.actual}")
        print("  → Enrichment functor will repair obstructions...")
    print()

    # Generate with auto-enrichment
    result = driver.generate(args.outdir, auto_enrich=True, max_rounds=5)

    print(f"  ✅ Generated {len(result.files_created)} files ({result.total_lines} lines)")
    if result.obligation_report:
        print(f"  Enrichment rounds: {result.obligation_report.enrichment_rounds}")
        all_met = result.obligation_report.all_met
        print(f"  All obligations met: {all_met}")
        if not all_met:
            for r in result.obligation_report.unmet:
                print(f"    ❌ {r.obligation.kind.value}: need {r.obligation.minimum}, have {r.actual}")
    print()
    for f in result.files_created:
        rel = os.path.relpath(f, args.outdir)
        size = os.path.getsize(f)
        print(f"    {rel:30s}  {size:>7,} bytes")
    print()
    print(f"  To serve:")
    print(f"    cd {args.outdir} && python3 -m http.server {args.port}")
    print(f"    Then open http://localhost:{args.port}")
    print()


if __name__ == "__main__":
    main()
